app/Models/User.php

Fixes #9.
@peppy: please move user_id 1 to group 6 if merging this ┐(･_･)┌

Remove profile page block on certain user_ids.

---

app/Libraries/ProfileCover.php
bootstrap.sh
resources/assets/less/users.less

Misc fixes

---

db-osu-data.sql
db-osu-structure.sql
db-osu_store-structure.sql
dump_database.sh

Comes with a random mixture of various charsets and collations. And row formats.

Put back the missing auto_increment.

---

app/helpers.php

Fix case when input is 0.

---

app/Models/Forum/Post.php
resources/assets/coffee/forum/post-box.coffee
resources/assets/coffee/forum/topic-ajax.coffee
resources/assets/coffee/osu_common.coffee
resources/assets/js/jsx/profile_page/contents.jsx
resources/assets/less/app.less
resources/assets/less/base.less
resources/assets/less/forum/base.less
resources/assets/less/forum/create-topic.less
resources/assets/less/forum/post-box.less
resources/assets/less/home.less
resources/assets/less/login-modal.less
resources/assets/less/store/base.less
resources/assets/less/store/header.less
resources/assets/less/users.less
resources/assets/less/variables.less
resources/views/forum/topics/_post.blade.php
resources/views/forum/topics/_post_edit.blade.php
resources/views/forum/topics/create.blade.php
resources/views/forum/topics/show.blade.php
resources/views/users/show.blade.php

Unified style for post editor footer.
Includes style updates, indentation:
- 4 spaces for blade files
- 2 spaces for [less css](https://github.com/less/less-docs#less-standards)

Editor footer

---

app/Models/Forum/Post.php
resources/assets/coffee/forum/post-box.coffee
resources/assets/coffee/forum/topic-ajax.coffee
resources/assets/coffee/osu_common.coffee
resources/assets/js/jsx/profile_page/contents.jsx
resources/assets/less/app.less
resources/assets/less/base.less
resources/assets/less/forum/base.less
resources/assets/less/forum/create-topic.less
resources/assets/less/forum/post-box.less
resources/assets/less/home.less
resources/assets/less/login-modal.less
resources/assets/less/store/base.less
resources/assets/less/store/header.less
resources/assets/less/users.less
resources/assets/less/variables.less
resources/views/forum/topics/_post.blade.php
resources/views/forum/topics/_post_edit.blade.php
resources/views/forum/topics/create.blade.php
resources/views/forum/topics/show.blade.php
resources/views/users/show.blade.php

Includes #62. May want to check that one first.

Forum updates

---

resources/assets/js/jsx/profile_page/contents.jsx
resources/assets/js/jsx/profile_page/header.jsx
resources/assets/less/base.less
resources/assets/less/forum/base.less
resources/assets/less/forum/post-box.less
resources/assets/less/users.less
resources/views/forum/topics/_post_box_footer.blade.php
resources/views/forum/topics/create.blade.php

Unified button style

---

resources/assets/coffee/forum.coffee
resources/assets/coffee/forum/topic-ajax.coffee

Yesterday's style update broke the link handling.

Fix post link

---

app/Libraries/ProfileCover.php
app/Transformers/UserTransformer.php
resources/assets/js/jsx/profile_page/header.jsx
resources/assets/less/users.less

It will allow people to re-select their custom cover past their supporter period (but still can't upload a new one).

Profile custom selection

---

resources/assets/less/users.less

Hopefully stands out less than black when new background is being loaded.

Transparent background color for profile header.

---

resources/assets/coffee/osu_common.coffee

Fix incorrect class name.

---

resources/assets/coffee/forum/post-box.coffee
resources/assets/less/forum/post-box.less
resources/lang/en/forum.php

Not sure why I haven't created pull request for this :confused:

Remove unused post editor toolbar show/hide link

---

gulpfile.js

Missed one place when removing it.

Remove unused main.js

---

resources/assets/js/jsx/profile_page/header.jsx

- fix react errors
- prevent previewing when uploading

Fix upload button

---

composer.json

As discussed in public slack, the authors section of composer.json is going to get out of hand and should probably be disposed of.

composer.json modifications

---

resources/assets/coffee/react/profile-page/contents.coffee
resources/assets/less/users.less

At least not yet another button style :dancer:

Style up profile page edit link

---

resources/views/layout/header.blade.php

Don't show the loading spinner by default

---

app/Models/User.php

Fix username change 0day.

---

app/Models/UserStatistics/Taiko.php

And styleci added a check on this.

php class name is case insensitive

---

resources/lang/en/users.php

Reported by Nabile on the osu!public slack.

Fix typo in users.show.extra.kudosu.empty

---

app/Models/Store/Address.php
app/Models/Store/OrderItem.php
app/Models/Store/Product.php

Maybe move them all to single database later? ┐(･_･)┌

Use connection data instead of hardcoding database name

---

resources/assets/coffee/react/profile-page/contents.coffee
resources/assets/coffee/react/profile-page/extra.coffee
resources/assets/coffee/react/profile-page/main.coffee
resources/assets/coffee/react/profile-page/user-page-editor.coffee
resources/assets/coffee/react/profile-page/user-page.coffee
resources/assets/less/forum/post-box.less
resources/lang/en/common.php
resources/lang/en/users.php

And people will complain that the user page width changes again :dancer:

Move user page to extra area

---

resources/assets/coffee/react/profile-page/user-page.coffee
resources/assets/less/forum/base.less

Fix positioning of user page edit button

---

resources/assets/coffee/react/profile-page/extra.coffee

By fix I mean just remove it altogether and scan on initial load instead.

Fix wrong initial section in profile page extra

---

gulpfile.js
resources/assets/coffee/react/flag-country.coffee
resources/assets/coffee/react/profile-page/info.coffee
resources/assets/coffee/react/user-card.coffee
resources/assets/less/bem-index.less
resources/assets/less/bem/flag-country.less
resources/assets/less/bem/userinfo-small.less

Add country flag to user profile

---

resources/assets/coffee/store.coffee
resources/views/store/product.blade.php

- actual image during initial load animation instead of gray (grey) box
- fixed positioning during initial load
- how do I English

Improved store preview zoom handling

---

resources/assets/less/bem/profile-extra-tabs.less

Need to centralize all z-index somewhere later.

Increase z-index in accordance to profile page editor button

---

gulpfile.js
resources/assets/coffee/global-drag.coffee
resources/assets/coffee/main.coffee
resources/assets/coffee/react/profile-page/cover-selector.coffee
resources/assets/coffee/react/profile-page/cover-uploader.coffee
resources/assets/less/users.less
resources/lang/en/users.php

It now covers entire cover selector dialog.
On related note: (╯°□°）╯︵ uoıʇɐɯıuɐ
This be fix #116

Extend dropzone for cover image upload

---

app/Models/Event.php

Fix event parser, etc

---

app/Models/User.php
app/Models/UserGroup.php

Use correct name for the bridge model and fix its relation

---

resources/assets/coffee/bootstrap-modal.coffee

And reset the padding as well.
Still not sure how to properly fix this.
At least this one will prevent black page when the avatar is clicked repeatedly.
Closes #54.

Remove all backdrops when modal is hidden

---

gulpfile.js
resources/assets/coffee/navbar-mobile.coffee
resources/assets/less/base.less
resources/assets/less/bem-index.less
resources/assets/less/bem/navbar-mobile.less
resources/assets/less/bootstrap-variables.less
resources/assets/less/layout/nav.less
resources/assets/less/sections.less
resources/assets/less/variables.less
resources/views/layout/header.blade.php

Fixes #4, based on design in #11 and closes #11 as well.

Update style for mobile navigation

---

resources/assets/less/forum/base.less

Broken during layout css rewrite.

Fix broken style for forum topic header

---

resources/assets/less/forum/create-topic.less
resources/assets/less/forum/post-box.less
resources/assets/less/layout.less
resources/views/forum/topics/create.blade.php

I thought I've fixed it :confused:

Forum mobile fixes

---

app/Http/Controllers/AccountController.php
resources/assets/coffee/react/profile-page/cover-uploader.coffee
resources/lang/en/errors.php

- missing error message
- actual error message for non-supporter

Fixes for cover uploader

---

resources/views/layout/header.blade.php

:santa: 
Reported by [Lemmmy](http://jizz.ppy.sh/u/Lemmmy).

Remove duplicated title

---

app/Http/Controllers/Forum/TopicsController.php
app/Libraries/BBCodeFromDB.php
app/helpers.php
phpunit.xml
resources/assets/coffee/forum.coffee
resources/assets/coffee/forum/topic-ajax.coffee
resources/assets/less/bem-index.less
resources/assets/less/bem/proportional-container.less
resources/assets/less/forum/base.less
resources/views/forum/topics/_post.blade.php
resources/views/forum/topics/_posts.blade.php
tests/Libraries/bbcode_examples/basic_img.html

:hammer: 
Initial loads will be slow until the image data are cached.

Forum image size

---

resources/assets/less/layout.less

Fix main background in safari

---

resources/assets/less/bem-index.less
resources/assets/less/bem/link.less
resources/assets/less/colours.less
resources/assets/less/forum/base.less
resources/views/forum/topics/_post.blade.php

Comes with 16 shades of gr(a|e)y.

Update action buttons and post permalink style

---

app/Libraries/BBCodeForDB.php
app/Libraries/BBCodeFromDB.php
tests/Libraries/bbcode_examples/basic_notice.base.txt
tests/Libraries/bbcode_examples/basic_notice.db.txt
tests/Libraries/bbcode_examples/basic_notice.html

And slight cleanup at rendering side.
With test!

notice bbcode tag support

---

app/Models/Event.php

And refactor to not repeat it too much.
Fixes #162.

Always html entity decode event strings

---

resources/assets/less/bem/forum-topic-nav.less

Fix animation duration and type

---

resources/assets/coffee/adjust-footer.coffee
resources/assets/coffee/forum-posts-seek.coffee
resources/assets/less/bem/forum-topic-nav.less
resources/assets/less/forum/base.less
resources/views/forum/topics/show.blade.php
resources/views/layout/footer.blade.php
resources/views/master.blade.php

Animations and counter styling and cleanup

Posts nav again

---

resources/assets/coffee/fade.coffee

Sometimes the setTimeout in `in` function is ran after another, unrelated event.
- mouseenter called, settimeout queued
- mouseleave called
- settimeout event ran <- whoops
Noticed on firefox.

Async sucks ;_;

---

app/helpers.php
resources/assets/coffee/forum.coffee
resources/assets/less/forum/base.less
resources/views/forum/topics/_post.blade.php

Forum post scroll again

---

resources/assets/coffee/forum.coffee

Fix missed update to new scroll system

---

gulpfile.js
resources/assets/coffee/forum-auto-click.coffee
resources/assets/coffee/forum-posts-seek.coffee
resources/assets/coffee/forum-search-modal.coffee
resources/assets/coffee/forum-topic-post-jump.coffee
resources/assets/coffee/forum.coffee
resources/assets/coffee/main.coffee
resources/assets/less/bem/forum-topic-nav.less
resources/views/forum/topics/show.blade.php

- allow jump to post from counter area
- refactor `forum.coffee`
- remove search button since it's redundant

Jump to post from counter

---

app/Http/Controllers/Forum/TopicsController.php

Ensure valid jumpTo number.

---

resources/assets/coffee/forum.coffee

Ensure (js side) jumpTo number is a valid number

---

resources/assets/less/base.less
resources/assets/less/bbcode.less
resources/assets/less/beatmaps.less
resources/assets/less/bootstrap-variables.less
resources/assets/less/colours.less
resources/assets/less/functions.less
resources/assets/less/home.less
resources/assets/less/layout.less
resources/assets/less/notifications.less
resources/assets/less/photoswipe-fix.less
resources/assets/less/sections.less
resources/assets/less/store.less
resources/assets/less/tooltip.less
resources/assets/less/tournament.less
resources/assets/less/users.less
resources/assets/less/variables.less
resources/assets/less/wiki.less

Without these there are many variable and function declarations that cannot be resolved by a naive less linter.

Explicitly import app.less into other less files (fixes linting issues).

---

resources/lang/en/forum.php

Update edit button text

---

gulpfile.js
resources/assets/coffee/header-menu.coffee
resources/assets/coffee/main.coffee
resources/assets/coffee/menu.coffee
resources/assets/less/bem-index.less
resources/assets/less/bem/js-menu.less
resources/assets/less/bem/logo-menu.less
resources/assets/less/bem/osu-nav.less
resources/assets/less/layout/nav.less
resources/views/layout/header.blade.php

Less code, more sharing. Maybe.

Use (js) Menu for header menu as well

---

resources/assets/less/bem/forum-category-header.less
resources/assets/less/forum/base.less
resources/views/forum/forums/show.blade.php
resources/views/forum/topics/create.blade.php
resources/views/forum/topics/show.blade.php

Fixes background problem in safari as well.

Clean up forum header css

---

bower.json
gulpfile.js
resources/assets/coffee/main.coffee

Not even used apart for one method.

Remove history.js

---

resources/assets/less/bem/osu-layout.less
resources/assets/less/bootstrap-variables.less
resources/views/store/index.blade.php

- More items per row
- No more "more to come"
- Fix horizontal scroll in mobile

Store three columns

---

resources/views/forum/forums/show.blade.php

Jump to topics listing when going to next/previous page

---

app/Http/Controllers/AccountController.php
app/Models/Forum/Post.php

Check post lock status

---

app/Models/Forum/Topic.php

Wrong variable name

---

resources/assets/coffee/forum-topic-cover.coffee
resources/assets/coffee/react/profile-page/header.coffee
resources/assets/less/app.less
resources/assets/less/bem-index.less
resources/assets/less/bem/forum-category-header.less
resources/assets/less/bem/spinner.less
resources/assets/less/keyframes.less
resources/assets/less/users.less
resources/views/forum/topics/_header.blade.php
resources/views/objects/_spinner.blade.php

- spins
- centered cover in popup

Spinner and stuff

---

app/Libraries/BBCodeFromDB.php
resources/assets/less/bbcode.less
resources/assets/less/bem/forum-category-header.less
tests/Libraries/bbcode_examples/basic_code.html

- remove extra newlines inside code block
- add back shadow to forum title

Misc fixes (again)

---

app/Libraries/BBCodeFromDB.php
resources/assets/coffee/react/profile-page.coffee
resources/assets/coffee/react/profile-page/user-page-editor.coffee
resources/assets/less/bbcode.less
resources/views/layout/_current_user.blade.php
resources/views/users/show.blade.php
tests/Libraries/BBCodeFromDBTest.php
tests/Libraries/bbcode_examples/basic_code.html
tests/Libraries/bbcode_examples/code_with_surrounding_newlines.base.txt
tests/Libraries/bbcode_examples/code_with_surrounding_newlines.db.txt
tests/Libraries/bbcode_examples/code_with_surrounding_newlines.html

- allows creation of blank line in code block again
- pass json as javascript object immediately instead of telling javascript to parse json text

Blank line code and immediate object parsing

---

database/migrations/2015_11_16_065319_create_topic_covers_table.php
database/migrations/2015_11_20_122003_add_unique_index_to_forum_topic_covers_forum_id.php

hopefully no one managed to have two cover images for one topic yet.

topic can only have one cover image

---

database/migrations/2015_11_20_122003_add_unique_index_to_forum_topic_covers_forum_id.php
gulpfile.js
resources/assets/coffee/adjust-paddings.coffee
resources/assets/coffee/forum-topic-reply.coffee
resources/assets/coffee/forum.coffee
resources/assets/coffee/main.coffee
resources/assets/coffee/sync-height.coffee
resources/views/forum/topics/_header.blade.php
resources/views/forum/topics/show.blade.php
resources/views/layout/footer.blade.php
resources/views/layout/header.blade.php
resources/views/master.blade.php

Hide header when first post not loaded

---

app/Models/User.php

Should've realized when seeing most of the entries are single digit :dancer:

Wrong unit for calculating level

---

resources/assets/coffee/fade.coffee
resources/assets/coffee/header-menu.coffee
resources/assets/less/bem/osu-nav.less
resources/assets/less/layout/nav.less
resources/views/layout/header.blade.php

[MDN](https://developer.mozilla.org/en/docs/Web/CSS/pointer-events) doesn't mention problem of the attribute in IE whereas [Can I Use](http://caniuse.com/pointer-events) says the link must be `block` or `inline-block`... except it's more like must not be `inline`. ┐(-｡ｰ;)┌
There's also weird thing with `position: static` and `opacity` (or other combinations).

Less broken menu in ie

---

resources/assets/coffee/logout.coffee

Because it's the right thing to do™.

Clean up local storage data when logging out

---

resources/assets/coffee/forum-topic-reply.coffee
resources/assets/coffee/main.coffee
resources/assets/coffee/sticky-footer.coffee
resources/assets/less/bem/forum-post.less
resources/views/forum/topics/show.blade.php

It was kinda wrong (and too complicated).
And fix styling.

Fix logic for sticking reply box

---

resources/assets/coffee/forum-topic-reply.coffee
resources/views/forum/topics/show.blade.php

Fixes #242.
Reload-less version would require a lot of consistency check at which point might as well migrate completely to react or something (which probably not a bad thing?).

Reload when posting right after logging in as guest

---

app/Http/Controllers/StoreController.php
app/Providers/AppServiceProvider.php
resources/lang/en/validation.php

Forgot to create pull request for this :S

Ensure street address contains both number and letter

---

gulpfile.js
resources/assets/coffee/forum-topic-reply.coffee
resources/assets/coffee/local-storage-polyfill.coffee
resources/assets/coffee/main.coffee

- storage size in safari private mode is 0, making it unusable. Fix with in-memory object.
- wrong blank value in IE.
- some cleanups.

Local storage fixes

---

resources/assets/coffee/forum-topic-reply.coffee

Hopefully not too slow ¯\\\_(ツ)_/¯

Topic reply box auto hide

---

app/Http/Controllers/UsersController.php
resources/assets/coffee/store.coffee
resources/lang/en/errors.php

Fixes error when user is logged out but still have the rename store page loaded.

Username availability auth check

---

gulpfile.js
resources/assets/coffee/bootstrap-modal.coffee
resources/assets/coffee/editor-zoom.coffee
resources/assets/coffee/forum-topic-reply.coffee
resources/assets/coffee/main.coffee
resources/assets/coffee/sticky-footer.coffee
resources/assets/less/bem-index.less
resources/assets/less/bem/fixed-bar.less
resources/assets/less/bem/forum-post.less
resources/assets/less/bem/js-editor-zoom.less
resources/assets/less/bem/osu-layout.less
resources/assets/less/forum/post-box.less
resources/assets/less/variables.less
resources/lang/en/forum.php
resources/views/forum/posts/_form_body.blade.php
resources/views/forum/topics/_post_box_footer.blade.php
resources/views/forum/topics/_post_edit.blade.php
resources/views/forum/topics/show.blade.php
resources/views/layout/footer.blade.php
resources/views/master.blade.php

Dealing with on screen keyboard is (╯°□°)╯︵ ┻━┻
Also probably doesn't work in iphone.
<sub>iphone sucks</sub>

Usable post editor in mobile

---

resources/assets/coffee/header-menu.coffee
resources/assets/less/bem/osu-nav.less
resources/views/layout/header.blade.php

Should've done this from beginning.

Top menu positioning

---

resources/assets/less/bem/forum-post.less
resources/assets/less/bem/forum-topic-headernav.less

- collapsed post on mobile version
- wrong fixed header alignment

Fixes for IE

---

resources/assets/less/bem/loading-overlay.less

Correctly showing overlay animation from starting point.

Only animate with --visible class

---

resources/assets/coffee/bootstrap-modal.coffee
resources/assets/coffee/forum-posts-seek.coffee
resources/assets/coffee/menu.coffee
resources/assets/coffee/osu_common.coffee
resources/assets/less/base.less
resources/assets/less/bem/forum-topic-nav.less
resources/assets/less/bem/logo-menu.less
resources/views/forum/topics/show.blade.php
resources/views/objects/logo-menu.blade.php

iphone's safari is a bit of lost cause ¯\\\_(ツ)_/¯

More mobile fixes

---

resources/assets/less/bem/forum-topic-nav.less

Weird blank space if there's an additional fixed element. Like the reply box

The 'new' fixed seek bar height doesn't really work

---

resources/assets/less/bem/loading-overlay.less

Forgot that there's another animation.

Fix overlay animation

---

app/Models/Forum/TopicCover.php

Always return at least a new object

Fix topic create

---

app/Models/Forum/TopicCover.php
app/Transformers/Forum/ForumCoverTransformer.php
app/Transformers/Forum/TopicCoverTransformer.php

Just create a new object within transformer. Saves pain.

Refactor cover transform

---

resources/assets/less/bem/forum-topic-nav.less
resources/views/forum/topics/show.blade.php

Not really visible but it's currently slightly off.

Properly centre seek bar's page navigation

---

resources/assets/coffee/tooltip-default.coffee
resources/lang/en/forum.php
resources/lang/en/users.php
resources/views/forum/_cover.blade.php
resources/views/forum/forums/_topics.blade.php
resources/views/forum/topics/_post.blade.php
resources/views/forum/topics/_post_info.blade.php
resources/views/forum/topics/show.blade.php
resources/views/layout/header.blade.php
resources/views/objects/logo-menu.blade.php
resources/views/objects/user-dropdown.blade.php
resources/views/store/products/username-change.blade.php
resources/views/tournaments/show.blade.php

Now with customisable position.

Tooltips again

---

.travis.yml
app/Models/User.php

For once the test is useful (☞ﾟ∀ﾟ)☞
(the error message is useless though)

Fix function declaration

---

resources/assets/coffee/react/profile-page/header.coffee
resources/lang/en/users.php

Will add something like `click to change` when it's implemented.

Remove title/tooltip for user avatar

---

app/Models/Genre.php
app/Models/Language.php

More fix on static functions

---

app/Http/Controllers/APIController.php
app/Http/Controllers/BeatmapController.php
app/Http/Controllers/HomeController.php
app/Models/Beatmap.php
app/Models/BeatmapSet.php
app/Models/Event.php
app/Models/Score/Best/Combined.php
app/Models/Score/Best/Fruits.php
app/Models/Score/Best/Model.php
app/Models/Score/Fruits.php
app/Models/Score/Model.php
app/Models/User.php
app/Models/UserStatistics/Fruits.php
app/helpers.php
resources/assets/coffee/react/beatmaps/difficulty-icon.coffee
resources/assets/coffee/react/profile-page/contents-tab.coffee
resources/assets/coffee/react/profile-page/contents.coffee
resources/assets/coffee/react/profile-page/recent-activities.coffee
resources/assets/less/beatmaps.less
resources/assets/less/icons.less
resources/lang/en/beatmaps.php
resources/lang/en/common.php

Consistency \o/
There's one place left (user achievements) which shall be updated together with other achievements updates.

All the fruits

---

resources/assets/less/app.less
resources/assets/less/bem-index.less
resources/assets/less/bem/footer.less
resources/assets/less/bem/profile-extra-tabs.less
resources/views/layout/footer.blade.php

Fix styling in IE

---

resources/assets/coffee/react/profile-page/rank.coffee
resources/assets/coffee/tooltip-default.coffee
resources/lang/en/users.php

- fix tooltip not displaying on some cases
- add tooltips to rank area in profile page

Tooltip fixes and additions

---

app/Models/UserStatistics/Model.php
resources/assets/less/layout/nav-background.less

Disable header animation for less cpu stress test

---

app/helpers.php

Don't return wrong registration date if it's null

---

app/Http/Controllers/AccountController.php
app/Libraries/ProfileCover.php
app/Models/UserProfileCustomization.php

Forgot to update this part after refactor.

Update error handling of profile cover upload

---

app/Models/Forum/Authorize.php
app/Models/Forum/Topic.php
app/Models/User.php

Only counts posts in forums which posts are counted

---

app/Models/Score/Model.php

Add conditional to skip redundant mod

---

app/Http/Controllers/StoreController.php
app/Http/Middleware/CheckUserRestricted.php
resources/lang/en/errors.php

They like to fuck things up (surprise surprise)

Disallow restricted users from placing orders at the osu!store.

---

resources/assets/less/colours.less

Apparently this one is better or something ┐(･_･)┌

A different darker pink colour

---

resources/assets/less/bem-index.less
resources/assets/less/bem/osu-page-header.less
resources/views/tournaments/index.blade.php
resources/views/tournaments/show.blade.php

Don't add padding in tournament header on mobile

---

resources/assets/less/colours.less

Revert "A different darker pink colour"

---

resources/assets/coffee/react/profile-page/beatmaps.coffee
resources/assets/coffee/react/profile-page/extra.coffee

That's what happens when two similar things are merged.
Also re: broken achievement badges, some slugs need updating:
- ctb is now fruits
- combo achievements should be prefixed with `osu-` instead of `all-`

Failing at merging

---

resources/assets/coffee/react/profile-page.coffee

Fix beatmap display on profiles (again)

---

resources/assets/coffee/react/profile-page/recent-achievements.coffee

Actual link on "and {x} more" in recent achievements section.

Medals more link

---

app/Http/Controllers/APIController.php

Causing error. Whoops :dancer:

Wrong syntax.

---

.styleci.yml
app/Console/Commands/StoreCheckOrderTrackingStatus.php
app/Http/Controllers/APIController.php
app/Http/Controllers/NotificationController.php
app/Http/Controllers/Store/Admin/OrderController.php
app/Http/Controllers/Store/Admin/OrderItemController.php
app/Http/Controllers/StoreController.php
app/Models/BeatmapSet.php
app/Models/Mod.php
app/Models/Store/Order.php
app/Models/Store/OrderItem.php
app/Models/User.php
app/Traits/ModdingAPI.php
app/Transformers/GenreTransformer.php
app/Transformers/LanguageTransformer.php
app/helpers.php
app/start/osu.php

(except in blade files since styleci doesn't check them)

Strict comparison with styleci

---

bin/db_dump
database/db-osu-data.sql
database/db-osu-structure.sql

Didn't know there's a language called "Instrumental".

Add osu_languages structure and data

---

app/Http/Controllers/StoreController.php

```
+------------------+
|                  |
|    Thanks PHP    |
|                  |
+------------------+
```

Thanks php

---

resources/assets/coffee/_classes/tooltip-default.coffee
resources/assets/less/bem/tooltip-default.less
resources/views/forum/topics/show.blade.php

There is probably better way than this... ┐(-｡ｰ;)┌

Match fixed positioning for tooltip

---

README.md
bootstrap.sh
build.sh
vagrant/Dockerfile
vagrant/Vagrantfile
vagrant/conf/nginx-osu-next
vagrant/mysql_user.sql

Now with php 7. I think this mostly works. The whole setup kind of sucks though ¯\\\_(ツ)_/¯

Vagrant 2016

---

resources/assets/coffee/_classes/forum.coffee
resources/assets/coffee/osu_common.coffee
resources/assets/coffee/react/profile-page/extra.coffee

I have no additional comments.

OCD Compliance™ for profile extra page tabs

---

resources/assets/coffee/_classes/line-chart.coffee
resources/assets/less/bem/chart.less

Referencing gradient url by id in css doesn't quite work in firefox (or probably firefox is the correct one).

Firefox graph fix

---

resources/assets/coffee/react/profile-page/historical.coffee

As it turned out there's another part relying on chart always loaded

---

resources/assets/coffee/bootstrap-modal.coffee

I'm not really satisfied with using `setTimeout triggerModal, 10` but as I'm new to webdev, I don't know better alternatives. It gets the job done but somebody more experienced can improve this.

Make user card appear faster. Fixes #172

---

resources/assets/coffee/react/profile-page/beatmaps.coffee
resources/assets/coffee/react/profile-page/extra.coffee
resources/assets/coffee/react/profile-page/historical.coffee
resources/assets/coffee/react/profile-page/kudosu.coffee
resources/assets/coffee/react/profile-page/medals.coffee
resources/assets/coffee/react/profile-page/recent-activities.coffee
resources/assets/coffee/react/profile-page/top-ranks.coffee
resources/assets/coffee/react/profile-page/user-page.coffee
resources/assets/less/bem/profile-extra.less

Also, I don't remember the logic in forum's `scrollTo` so this one will have to make do for now ¯\\\_(ツ)_/¯

Scroll again

---

app/Http/Controllers/CommunityController.php
resources/assets/coffee/_classes/line-chart.coffee
resources/assets/coffee/react/profile-page/beatmaps.coffee
resources/assets/coffee/react/profile-page/extra.coffee
resources/assets/coffee/react/profile-page/historical.coffee
resources/assets/less/bem/chart.less

I don't think I've tested enough but heyyy ヽ( ﾟ ヮﾟ)ﾉ
Now using same scales and tick values for y axis (I think).
I'll let you guys fight over how to format the tooltip and axis values.
Unrelated commits included because this branch branches off #357.

Chart part 2

---

app/Models/Store/Order.php
app/Models/Store/Product.php
resources/assets/less/bem/osu-layout.less
resources/assets/less/store/base.less
resources/assets/less/variables.less
resources/lang/en/store.php
resources/views/store/_product.blade.php
resources/views/store/index.blade.php
resources/views/store/product.blade.php

- inStock thingy
- out of stock rearrange (and demote if currently promoted)

Store updates

---

resources/assets/coffee/_classes/line-chart.coffee
resources/assets/coffee/react/profile-page/historical.coffee

Now it goes to the closest point instead of always to the right side point of the cursor. Fixed ticks alignment as well.

Chart tooltip update

---

resources/assets/coffee/react/profile-page/extra.coffee
resources/assets/less/bem/medals-group.less
resources/assets/less/bem/profile-extra-tabs.less

Hides the overflowing tab in mobile and fixes medal boxes alignment.

Profile style update

---

bin/db_dump
database/db-osu-data.sql
database/db-osu-structure.sql

Add missing required table and data

---

app/Http/Controllers/Store/Admin/OrderController.php
app/Models/Store/Order.php
resources/views/store/admin.blade.php

This whole page needs a rewrite in react with client-side support for this stuff, but needed to get this one out quickly so we can more easily send out osu!go orders.

Add the ability to filter the store admin by a specific product.

---

resources/assets/coffee/react/profile-page/main.coffee

That was a nice try

---

resources/assets/coffee/react/profile-page/extra.coffee

One place missed the method update

---

resources/assets/coffee/react/profile-page/extra.coffee
resources/assets/less/bem/profile-extra-tabs.less
resources/assets/less/variables.less

Better animation or something?

Duplicate extra pages tabs instead of toggling position

---

resources/assets/coffee/_classes/line-chart.coffee
resources/assets/coffee/react/profile-page/extra.coffee

Turns out I already have everything in place for line chart transition animation.
Also fixes reordering pages.

Animations and fixes

---

app/Models/Log.php

Wrong function declaration

---

resources/assets/coffee/react/profile-page/beatmaps.coffee
resources/assets/coffee/react/profile-page/extra-header.coffee
resources/assets/coffee/react/profile-page/extra.coffee
resources/assets/coffee/react/profile-page/historical.coffee
resources/assets/coffee/react/profile-page/kudosu.coffee
resources/assets/coffee/react/profile-page/medals.coffee
resources/assets/coffee/react/profile-page/performance.coffee
resources/assets/coffee/react/profile-page/recent-activities.coffee
resources/assets/coffee/react/profile-page/top-ranks.coffee
resources/assets/coffee/react/profile-page/user-page.coffee
resources/assets/less/bem/profile-extra-tabs.less

Maybe. And one less paint reflash.
Still need further improvements.
- less reflow
- full `PureRenderMixin`? (last time tried didn't change much)
- ?

Slightly speed up react rendering

---

app/Http/Controllers/StoreController.php

Which is null to be immediately 404'd.

Add default id for getInvoice

---

resources/assets/coffee/react/profile-page/extra.coffee

Fix reordering pages

---

app/Models/User.php

Had several people complain they aren't sure which minute/hour the new username would become available (and annoyance at the display staying on "1 day remaining" for much longer than one day). This fixes that, while not adding localisation support just yet.

Add better messaging for username availability.

---

config/osu.php
resources/views/home/support-the-game.blade.php

Not sure what's happened here ಠ_ಠ

Fix link to get supporter tag

---

app/Http/Controllers/Forum/Admin/Controller.php
app/Http/Controllers/Forum/Admin/ForumCoversController.php
app/Http/Controllers/Forum/ForumCoversController.php
app/Http/Controllers/Forum/TopicCoversController.php
app/Http/Controllers/Forum/TopicsController.php
app/Http/routes.php
app/Libraries/ForumDefaultTopicCover.php
app/Models/Forum/ForumCover.php
app/Models/Forum/TopicCover.php
app/Traits/Imageable.php
app/Transformers/Forum/ForumCoverTransformer.php
app/Transformers/Forum/TopicCoverTransformer.php
app/helpers.php
database/migrations/2016_03_15_080726_add_default_topic_cover_to_forum_covers.php
resources/assets/coffee/_classes/forum-cover.coffee
resources/assets/less/base.less
resources/assets/less/bem-index.less
resources/assets/less/bem/forum-category-header.less
resources/assets/less/bem/forum-cover-admin-item.less
resources/lang/en/forum.php
resources/lang/en/layout.php
resources/views/forum/_cover.blade.php
resources/views/forum/admin/forum_covers/index.blade.php
resources/views/forum/forums/show.blade.php
resources/views/forum/topics/_header.blade.php

- upload fixes
- reduce height
- allow custom fallback
- some kind of admin page for forum covers (shall be at https://new.ppy.sh/forum/admin/forum-covers )

Forum cover updates

---

app/Models/Forum/TopicCover.php
resources/assets/less/bem/forum-cover-admin-item.less

whoops :dancer:  Doesn't help php doesn't throw error on nonexistent class name here.

Cover fixes

---

resources/assets/less/bem/product-box.less
resources/views/store/_product.blade.php

Incomplete check. Also, less stupid css [1].
Fixes issue #433.
[1] http://getbem.com/faq/#block-modifier-affects-elements

Fix wrong size of out of stock promoted item

---

app/Http/routes.php

One route missed the name update

---

resources/assets/coffee/react/slack-page/button-container.coffee

Fixed misnamed locale on slack page

---

app/Http/Controllers/BeatmapsetsController.php
resources/assets/coffee/_classes/url.coffee
resources/assets/coffee/react/beatmap-discussions/discussion.coffee
resources/assets/coffee/react/beatmap-discussions/main.coffee
resources/assets/coffee/react/beatmap-discussions/new-discussion.coffee
resources/assets/coffee/react/beatmap-discussions/new-reply.coffee
resources/assets/coffee/react/beatmap-discussions/overview.coffee
resources/assets/less/bem/beatmap-discussion-new.less
resources/lang/en/beatmaps.php

<del>Hopefully this is 445</del>.

Modding fixes

---

resources/assets/coffee/react/_components/beatmap-icon.coffee
resources/assets/coffee/react/beatmap-discussions/beatmap-list-item.coffee
resources/assets/coffee/react/beatmap-discussions/beatmap-list.coffee
resources/assets/less/bem/beatmap-discussions-overview.less
resources/assets/less/bem/beatmap-icon.less
resources/assets/less/bem/beatmap-list-item.less
resources/assets/less/bem/beatmap-list.less

Now with menu nesting

---

app/Transformers/BeatmapTransformer.php
resources/assets/coffee/react/beatmap-discussions/beatmap-list-item.coffee
resources/assets/coffee/react/beatmap-discussions/beatmap-list.coffee

Fixes #464.
Also modified display version name (only in listing) to `[#{num}k] #{version}`.

Sort osu!mania listing by key size first

---

app/Models/BeatmapDiscussion.php
gulpfile.js
resources/assets/coffee/react/beatmap-discussions/discussion.coffee
resources/assets/coffee/react/beatmap-discussions/discussions.coffee
resources/assets/less/bem/beatmap-discussion-vote.less
resources/assets/less/bem/beatmap-icon.less
resources/assets/less/bem/beatmap-list.less
resources/assets/less/icons.less
resources/lang/en/beatmaps.php

- weird bug with minifier affecting safari
- fix mode icon positioning
- fix timestamp validation
- ignore branch name ;_;
- improved vote button

More modding fixes

---

database/factories/ModelFactory.php

Code-style fix

---

app/Models/Event.php
resources/assets/coffee/react/profile-page/recent-activities.coffee

Fix profile pages breaking when events fail to parse

---

resources/assets/coffee/react/profile-page/achievement-badge.coffee

Should be day of month, not week.

Wrong date format

---

resources/assets/less/bem/store-header.less
resources/assets/less/variables.less

Store notice styling

---

app/Http/Controllers/Forum/TopicsController.php
resources/views/forum/topics/create.blade.php

Update one missed place for route update

---

app/Libraries/BBCodeFromDB.php
resources/assets/less/bbcode.less
tests/Libraries/bbcode_examples/list_title.base.txt
tests/Libraries/bbcode_examples/list_title.db.txt
tests/Libraries/bbcode_examples/list_title.html

This fixes #29, and fixes #495. Hopefully. I mean, "fixes".
Merging this means people will complain again once we use actual text formatting library unless someone can figure out how to "extend" the library to support this as well.
Or idk, depends on where we're even going ¯\\\_(ツ)_/¯

Support for list "title"

---

resources/assets/coffee/react/profile-page/contents.coffee
resources/assets/coffee/react/profile-page/header.coffee
resources/assets/coffee/react/profile-page/main.coffee

Fixes some bugs which were found when reviewing other pull request ¯\\\_(ツ)_/¯

Fix profile page

---

app/Http/Controllers/UsersController.php
app/Models/Achievement.php
app/Models/User.php
app/Transformers/AchievementTransformer.php
app/Transformers/UserAchievementTransformer.php
app/Transformers/UserTransformer.php
database/migrations/2016_05_10_080557_update_achievements_table.php
resources/assets/coffee/react/_components/user-card.coffee
resources/assets/coffee/react/profile-page.coffee
resources/assets/coffee/react/profile-page/contents.coffee
resources/assets/coffee/react/profile-page/extra.coffee
resources/assets/coffee/react/profile-page/main.coffee
resources/assets/coffee/react/profile-page/medals.coffee
resources/assets/coffee/react/profile-page/recent-achievements.coffee
resources/lang/en/users.php
resources/views/users/show.blade.php

Probably need the new badges as well later?

Achievement by mode

---

app/Http/Controllers/AccountController.php
app/Models/User.php
resources/assets/coffee/react/profile-page/user-page.coffee
resources/assets/less/bem/forum-post-actions.less

Something was broken on both frontend and backend =D
And misc cleanups.

User page fixes

---

app/Http/Controllers/BeatmapController.php
app/Models/Score/Best/Model.php
app/Models/Score/Model.php
app/Models/User.php
app/Transformers/BeatmapTransformer.php
app/Transformers/UserTransformer.php

Includes fixes #502 and in more places.

Prevent score of restricted user from being listed

---

app/Http/Controllers/BeatmapsController.php
app/Http/Controllers/BeatmapsetsController.php
app/Http/routes.php
app/Models/BeatmapSet.php
app/Transformers/BeatmapSetTransformer.php
resources/assets/coffee/react/beatmapset-page/contents.coffee
resources/assets/coffee/react/beatmapset-page/details.coffee
resources/assets/coffee/react/beatmapset-page/main.coffee
resources/assets/coffee/react/beatmapset-page/scoreboard-item.coffee
resources/assets/coffee/react/beatmapset-page/scoreboard-tab.coffee
resources/assets/coffee/react/beatmapset-page/scoreboard.coffee
resources/assets/coffee/react/beatmapset-page/stats.coffee
resources/assets/less/bem/beatmapset-difficulties.less
resources/assets/less/bem/beatmapset-scoreboard.less
resources/lang/en/beatmaps.php

Speed up beatmapset and other stuff

---

resources/assets/coffee/react/beatmapset-page/main.coffee

Correctly pass null event to scoreboard loader

---

resources/assets/coffee/react/profile-page/recent-activities.coffee

well, generally displaying as not achieved ¯\\\_(ツ)_/¯
Fixes #524.

Fix achievements in recent activities not displaing dates

---

resources/assets/less/bem/badge-achievement.less

Mainly happening in firefox for android. At random.

Fix badge alignment

---

app/Libraries/BBCodeFromDB.php

Doesn't handle making relative links, just parsing existing ones.

Properly parse relative url

---

resources/assets/coffee/react/beatmapset-page/scoreboard.coffee

Forgot to actually use the class.

Fix hiding accuracy column header

---

resources/assets/coffee/react/profile-page/achievement-badge.coffee
resources/assets/less/bem/badge-achievement.less
resources/assets/less/bem/profile-achievements.less

It's pretty messy right now =[

Recent achievements alignment

---

app/Http/Controllers/StoreController.php
app/Models/Store/Order.php

Prevents missing order from unfortunate timing problem?
And apparently at one point I added function to pay from invoice page and then removed it ¯\\\_(ツ)_/¯

Set order state to checkout on clicking pay button

---

app/Http/Controllers/Admin/BeatmapsetsController.php
app/Http/Controllers/BeatmapsController.php
app/Http/Controllers/BeatmapsetsController.php
app/Models/Beatmap.php
app/Models/Beatmapset.php
app/Models/Event.php
app/Models/Score/Model.php
app/Models/User.php
app/Transformers/API/BeatmapTransformer.php
app/Transformers/BeatmapPlaycountTransformer.php
app/Transformers/BeatmapsetTransformer.php
app/Transformers/ScoreTransformer.php
app/Transformers/UserTransformer.php
resources/assets/coffee/react/_components/play-detail.coffee
resources/assets/coffee/react/beatmapset-page/difficulty-chart.coffee
resources/assets/coffee/react/beatmapset-page/extra.coffee
resources/assets/coffee/react/beatmapset-page/main.coffee
resources/assets/coffee/react/beatmapset-page/scoreboard.coffee
resources/assets/coffee/react/beatmapset-page/success-rate.coffee
resources/assets/coffee/react/profile-page/beatmaps.coffee
resources/assets/coffee/react/profile-page/historical.coffee
resources/assets/coffee/react/profile-page/recent-activities.coffee
resources/lang/en/events.php
resources/views/admin/beatmapsets/cover.blade.php

Remaining missed from last update (`beatmapSet`, `beatmap_set`).

Beatmapset rename

---

app/Http/Controllers/Forum/TopicsController.php
app/Http/routes.php
app/Models/Forum/Forum.php
app/Models/Forum/Topic.php
app/Models/User.php
app/start/global.php
database/seeds/ModelSeeders/UserSeeder.php

Whatever recent updates of StyleCI detected new additional problems.

StyleCI fixes

---

resources/assets/coffee/react/_components/mods.coffee
resources/assets/coffee/react/_components/play-detail.coffee
resources/assets/coffee/react/beatmapset-page/scoreboard-item.coffee
resources/assets/less/bem/beatmapset-scoreboard.less

Display mods on beatmap scoreboards

---

app/Http/Kernel.php
app/Http/Middleware/TurbolinksSupport.php
app/helpers.php

Fixes bug regarding redirect of short forum post url.

Add support for turbolinks redirect

---

resources/assets/coffee/react/beatmap-discussions/discussion.coffee

Put wrong route when updating to use laroute.

Fix voting in beatmap modding

---

app/Models/Beatmapset.php
app/Transformers/BeatmapsetTransformer.php
resources/assets/coffee/react/beatmapset-page/header.coffee
resources/assets/coffee/react/beatmapset-page/main.coffee
resources/assets/less/bem/beatmapset-header.less
resources/assets/less/variables.less

Fixes #512.
Currently the design is simply a play/pause button shown on hover of the header.

Audio preview on beatmapset pages

---

app/Http/Controllers/API/Controller.php

Add missing import in API base controller

---

app/Http/Controllers/API/Controller.php

Another missing import

---

resources/assets/less/bem/badge-achievement.less
resources/assets/less/bem/profile-extra-entries.less

Fixes #562 (and hopefully doesn't break anything else)

Avoid cutting off badge on overflow

---

resources/assets/coffee/react/_components/beatmapset-panel.coffee
resources/assets/less/bem/beatmapset-panel.less

Minimise repaints and composite instead so we get tasty GPU acceleration.

Optimise on-hover performance on beatmapsets listing page

---

build.sh

Otherwise artisan may explode.

Remove cache for new builds

---

resources/assets/coffee/logout.coffee
resources/assets/coffee/osu_common.coffee
resources/assets/coffee/ujs-common.coffee
resources/assets/coffee/user-dropdown-modal.coffee
resources/views/forum/topics/show.blade.php

And keep the scroll position when appropriate since the new `Turbolinks.visit` always resets scroll position.

Always use reloadUrl in osu.reloadPage

---

app/Http/Controllers/Forum/ForumsController.php
app/Http/Controllers/Forum/TopicsController.php
app/Http/routes.php
app/Libraries/ValidationErrors.php
app/Models/Forum/FeatureVote.php
app/Models/Forum/Forum.php
app/Models/Forum/Topic.php
app/Traits/Validatable.php
config/osu.php
resources/lang/en/forum.php
resources/lang/en/model_validation.php
resources/views/forum/forums/show.blade.php
resources/views/forum/topics/show.blade.php

Forum feature votes

---

resources/assets/coffee/osu_common.coffee

The syntax looks a bit weird ¯\\\_(ツ)_/¯

Add default parameter

---

app/Http/Controllers/Forum/TopicCoversController.php

Remove unused line

---

resources/assets/coffee/_classes/tooltip-default.coffee
resources/assets/coffee/react/profile-page/achievement-badge.coffee

qtip fixes

---

app/Http/Controllers/API/UsersController.php
app/Http/routes.php

As per title, nothing particularly special. 😃

Add API endpoint for basic metadata about currently authenticated user

---

app/Models/Forum/Post.php
app/Models/Forum/Topic.php

As GMT can now also delete and edit posts.

Remove wrong isAdmin check

---

app/Libraries/OsuAuthorize.php
resources/assets/coffee/main.coffee
resources/assets/coffee/osu_common.coffee
resources/assets/coffee/react/beatmap-discussions/post.coffee
resources/lang/en/authorization.php

Fixes some of the smaller issues in #582, namely:
> Silences/Restrictions should prevent users from posting issues or issue comments
and
> Make links in issues and issue comments clickable

Small modding fixes

---

app/Http/Controllers/Forum/TopicsController.php
app/Http/routes.php
app/Libraries/OsuAuthorize.php
app/Models/Forum/Forum.php
app/Models/Forum/Topic.php
app/Models/Log.php
resources/assets/less/bem/bootstrap/modal-body.less
resources/assets/less/bem/forum-topic-nav.less
resources/lang/en/forum.php
resources/views/forum/topics/show.blade.php

Apparently I already did most of the model stuff a long time ago. Now with actual interface to move the thing.

Topic move

---

resources/assets/coffee/react/beatmap-discussions/discussions.coffee
resources/assets/coffee/react/beatmap-discussions/main.coffee
resources/assets/coffee/react/beatmap-discussions/overview.coffee
resources/assets/less/bem/beatmap-discussions-stats.less
resources/lang/en/beatmaps.php

Addresses some of the issues mentioned in #582 and #450

Add filter to beatmap discussions for threads created by the current user

---

resources/lang/en/authorization.php
resources/lang/en/beatmaps.php
resources/lang/en/community.php
resources/lang/en/errors.php
resources/lang/en/model_validation.php
resources/lang/en/users.php

Small fixes

---

resources/assets/coffee/_classes/forum.coffee

One function missed update to new system

---

resources/lang/nl/admin.php
resources/lang/nl/api.php
resources/lang/nl/authorization.php
resources/lang/nl/bbcode.php
resources/lang/nl/beatmap_discussions.php
resources/lang/nl/beatmaps.php
resources/lang/nl/common.php
resources/lang/nl/community.php
resources/lang/nl/errors.php
resources/lang/nl/events.php
resources/lang/nl/forum.php
resources/lang/nl/help.php
resources/lang/nl/home.php
resources/lang/nl/layout.php
resources/lang/nl/livestreams.php
resources/lang/nl/model_validation.php
resources/lang/nl/ranking.php
resources/lang/nl/status_page.php
resources/lang/nl/store.php
resources/lang/nl/users.php
resources/lang/nl/validation.php

Everyone seems to be doing it so why not Dutch?

Dutch translation

---

resources/lang/pt-br/admin.php
resources/lang/pt-br/api.php
resources/lang/pt-br/authorization.php
resources/lang/pt-br/bbcode.php
resources/lang/pt-br/beatmap_discussions.php
resources/lang/pt-br/beatmaps.php
resources/lang/pt-br/common.php
resources/lang/pt-br/community.php
resources/lang/pt-br/errors.php
resources/lang/pt-br/events.php
resources/lang/pt-br/forum.php
resources/lang/pt-br/help.php
resources/lang/pt-br/home.php
resources/lang/pt-br/layout.php
resources/lang/pt-br/livestreams.php
resources/lang/pt-br/model_validation.php
resources/lang/pt-br/ranking.php
resources/lang/pt-br/status_page.php
resources/lang/pt-br/store.php
resources/lang/pt-br/users.php
resources/lang/pt-br/validation.php

All files translated to Brazilian Portuguese.
There might be some inconsistencies regarding osu!supporter/modding/accuracy, which are some hard words to translate. Should be mostly fine, though.
edit: grammar

Brazilian Portuguese Translation

---

bootstrap.sh

The recent locale update requires php7.0-intl

---

config/database.php

┐(･_･)┌
May or may not be related: https://bugs.php.net/bug.php?id=63343

Persistent connection causes random test failure

---

app/Models/Beatmapset.php

There are over 8000 of such beatmapsets...

Don't fail when beatmapset is missing its thread

---

app/Http/Middleware/SetLocale.php
app/helpers.php
config/app.php
gulpfile.js
resources/views/layout/metadata.blade.php
resources/views/store/objects/order.blade.php

Now with localized timeago and less errors.

Locale fixes

---

app/Models/Forum/Topic.php
app/Models/User.php

Forgot to update after changing syntax. And made it less strict.

Update createNew call for userPage

---

app/Http/Middleware/SetLocale.php
app/Libraries/OsuAuthorize.php
resources/assets/less/bem-index.less
resources/assets/less/bem/forum-post.less
resources/assets/less/bem/forum-topic-reply.less
resources/assets/less/variables.less
resources/lang/en/authorization.php
resources/views/forum/topics/show.blade.php

Fixes #638 ┐(･_･)┌
The warning box only visible at the end of topic and reply buttons are hidden.

Use the previously designed warning box

---

app/Http/Controllers/Forum/TopicsController.php

Wrong priv names

---

resources/lang/es/authorization.php
resources/lang/es/community.php
resources/lang/es/layout.php
resources/lang/es/users.php

I don't know if this is the right place, but there are some mistakes in the spanish translation.

Spanish translation fixes

---

resources/assets/coffee/_classes/forum-posts-seek.coffee
resources/assets/coffee/_classes/forum.coffee
resources/assets/coffee/osu_common.coffee

This should close #639
I don't know if this should be in its own class. If that's the case, tell me.

Navigate between forum posts using left and right keys

---

app/Models/Forum/AuthGroup.php
app/Models/Forum/AuthOption.php
database/migrations/2015_01_01_133337_base_tables.php
database/seeds/ModelSeeders/ForumSeeder.php
database/seeds/ModelSeeders/UserSeeder.php

Add missing forum acl migrations

---

resources/lang/es/authorization.php
resources/lang/es/beatmaps.php
resources/lang/es/community.php
resources/lang/es/events.php
resources/lang/es/forum.php
resources/lang/es/layout.php
resources/lang/es/livestreams.php
resources/lang/es/model_validation.php
resources/lang/es/store.php
resources/lang/es/users.php

One or two flagrant mistakes (desargas, remover imagenes)
Still a lot to do and discuss (unconsistent case, anglicisms...), but now a bit less.

More Spanish transl. fixes

---

resources/assets/coffee/_classes/landing-graph.coffee
resources/assets/coffee/_classes/landing-user-stats.coffee
resources/assets/coffee/_classes/nav.coffee
resources/assets/coffee/_classes/user-login.coffee
resources/assets/less/bem/logo.less
resources/assets/less/bem/nav-popup.less
resources/views/home/landing.blade.php
resources/views/layout/_popup_menu.blade.php
resources/views/layout/header.blade.php
resources/views/layout/metadata.blade.php

There's something else I wanted to fix but I can't remember what it is.

More fixes

---

app/Http/Controllers/StoreController.php

Prevent empty checkout

---

app/Http/Middleware/VerifyCsrfToken.php

Remove workaround needed for laravel 5.1

---

app/Http/Controllers/UsersController.php

To match what input box says =D

Allow logging in by email

---

resources/assets/less/utilities.less

Add missing default header color

---

app/Transformers/ArtistTrackTransformer.php

Add track version to transformer

---

resources/assets/coffee/_classes/forum-posts-seek.coffee
resources/assets/less/base.less
resources/assets/less/bem/forum-topic-nav.less

Removed the transition and replaced `left` with `translateX`.

Animating the left property is too slow

---

app/helpers.php
config/osu.php

Top menu should link to old site for incomplete areas.

---

resources/assets/coffee/_classes/landing-hero.coffee
resources/assets/less/bem/landing-download.less
resources/assets/less/bem/landing-footer-social.less
resources/assets/less/bem/landing-graph.less
resources/assets/less/bem/landing-hero.less
resources/assets/less/bem/landing-middle-buttons.less
resources/assets/less/bem/landing-nav.less
resources/assets/less/bem/landing-sitemap.less
resources/assets/less/bem/osu-layout.less
resources/assets/less/variables.less
resources/views/home/landing.blade.php

Fixing the rest of the styling issues mentioned in #610 and fixes some fixes peppy mentioned in discord. Also includes the new centered slick dots flyte designed

Landing page post PR fixes

---

app/Http/Controllers/HomeController.php
app/Http/routes.php
resources/lang/en/layout.php

Merged all redirect logic in the action itself. Includes fixes #697.

Enable landing page

---

app/Libraries/UserVerification.php

Actually pass country name variable to view

---

app/Models/Count.php
tests/RouteTest.php

And fix when the data isn't there.

Update test for the removed route

---

app/Libraries/BBCodeFromDB.php
app/helpers.php
resources/lang/en/users.php
resources/lang/es/layout.php
resources/lang/es/users.php
resources/lang/nl/layout.php
resources/lang/nl/users.php
resources/lang/pl/layout.php
resources/lang/pl/users.php
resources/lang/pt-br/layout.php
resources/lang/pt-br/users.php
resources/views/home/landing.blade.php
resources/views/home/support-the-game.blade.php
resources/views/layout/footer.blade.php
resources/views/users/_disabled_message-en.blade.php
resources/views/users/_verify_box.blade.php

Ensure base domain and slightly simpler as well.
..and some other fixes.

Fix osu urls

---

app/Models/LoginAttempt.php
resources/assets/coffee/react/profile-page/cover-selection.coffee
resources/assets/coffee/react/profile-page/header.coffee
resources/assets/less/variables.less

Another misc fixes

---

app/Http/Controllers/UsersController.php

Otherwise the csrf token need to be refreshed on each attempts.

Only flush session on successful login

---

app/Http/Controllers/ContestsController.php
app/Models/Contest.php

Let's not fetch all the contest's votes just to count the number of votes you've made 👍

Optimise Voting

---

resources/assets/coffee/react/contest.coffee

Fix the previews for music contest entries not being visible

---

resources/assets/coffee/react/contest/art-entry-list.coffee
resources/assets/coffee/react/contest/art-entry.coffee
resources/assets/less/bem-index.less
resources/assets/less/bem/contest-art-list.less
resources/assets/less/bem/contest.less
resources/lang/en/contest.php

Adds support for showing the results of art contests.

Results page for art contests

---

resources/assets/coffee/react/contest/art-entry.coffee

Wrong class was being added, oops.

Fix visual bug for art entries where results aren't released yet

---

app/Http/Controllers/ContestsController.php
app/Http/routes.php
app/Libraries/OsuAuthorize.php
app/Models/Contest.php
app/Transformers/ContestTransformer.php
database/migrations/2016_09_20_203638_contest_submissions.php
resources/assets/coffee/react/contest/art-entry.coffee
resources/assets/coffee/react/contest/voter.coffee
resources/lang/en/contest.php
resources/views/contests/base.blade.php
resources/views/contests/enter.blade.php
resources/views/contests/voting.blade.php
resources/views/contests/voting/art.blade.php
resources/views/contests/voting/beatmap.blade.php
resources/views/contests/voting/music.blade.php

This doesn't actually add upload logic, but it does locally split the contest system in a way that allows for entry (submission) and voting (plus results).
Should be a clean merge from which we can add more.

Prepare framework for contest submission page.

---

resources/views/contests/base.blade.php

Fix missing bracket

---

app/Http/Controllers/AccountController.php
app/Http/Middleware/VerifyUser.php
app/Http/routes.php
app/Libraries/UserVerification.php
resources/assets/coffee/_classes/user-verification.coffee
resources/lang/en/user_verification.php
resources/views/users/_verify_box.blade.php

Logout and code reissuing on verification

---

app/Libraries/OsuAuthorize.php
resources/assets/less/bem/logo.less

- no blurry logo (and no animation)
- fewer actions allowed for restricted user

Some fixes

---

resources/assets/less/bem-index.less
resources/assets/less/bem/avatar-ribbon.less
resources/assets/less/bem/avatar.less
resources/assets/less/bem/forum-post.less
resources/assets/less/forum/base.less
resources/assets/less/variables.less
resources/views/forum/topics/_post_info.blade.php
resources/views/forum/topics/show.blade.php

Fixes #28.
Also included a bunch of refactors and fix for mobile.

Forum username clipping

---

.travis.yml
build.sh

Just messing about with yarn and travis, ignore this.

Testing Yarn [please ignore this]

---

resources/assets/less/bem/beatmapset-beatmap-picker.less

Implemented using over9000 hacks.

Less flashing on hovering difficulty icons

---

resources/assets/coffee/_classes/forum-topic-reply.coffee
resources/assets/coffee/_classes/forum.coffee

Fixes broken counter when replying after someone replied on same thread without reload.

Reload if there's new post before the latest loaded reply

---

app/Libraries/ProfileCover.php
app/Models/Forum/ForumCover.php
app/Models/Forum/TopicCover.php
composer.json
composer.lock
resources/assets/less/sections.less
resources/lang/en/users.php
resources/lang/es/users.php
resources/lang/fr/users.php
resources/lang/nl/users.php
resources/lang/pl/users.php
resources/lang/pt-br/users.php

Also updates the upload dimensions.

Php package updates

---

app/Http/Controllers/ContestEntriesController.php
resources/assets/coffee/react/contest/entry/uploader.coffee
resources/lang/en/contest.php

Add support for entering non-beatmap contests

---

resources/views/forum/topics/show.blade.php

Hide poll when header is hidden

---

resources/assets/coffee/react/contest/entry/uploader.coffee

Fix file selector filter when clicking entry uploader

---

resources/assets/coffee/_classes/form-placeholder-hide.coffee
resources/assets/less/bem-index.less
resources/assets/less/bem/forum-category-header.less
resources/assets/less/bem/forum-topic-header-counter.less
resources/lang/en/forum.php
resources/views/forum/topics/_header.blade.php
resources/views/forum/topics/_header_counter.blade.php

Implements #616 (the last part).

Topic style update

---

resources/assets/coffee/react/_components/mod.coffee
resources/assets/coffee/react/_components/mods.coffee
resources/assets/less/bem-index.less
resources/assets/less/bem/beatmapset-score-big.less
resources/assets/less/bem/beatmapset-scoreboard.less
resources/assets/less/bem/mod.less
resources/assets/less/bem/mods.less
resources/assets/less/variables.less

Thankfully the old images are cached =D

Update missed mod icon update

---

resources/views/store/invoice.blade.php

Input has been replaced with Request

---

app/Http/Controllers/Admin/Store/OrdersController.php
resources/assets/coffee/_classes/react-turbolinks.coffee

Fix store orders

---

app/Models/Contest.php
resources/assets/coffee/_classes/nav.coffee
resources/lang/en/contest.php
resources/lang/pl/artist.php

Fix count "translation" and others

---

app/Models/Contest.php
app/Transformers/ContestTransformer.php
resources/assets/coffee/react/contest/voting/art-entry.coffee
resources/assets/less/bem/contest-art-list.less

Yeah it's horrible, I'll fix it next week.

Half-step towards orientation support for art contests.

---

app/Http/Controllers/HomeController.php
app/Http/Middleware/SetLocale.php
app/Libraries/LocaleFlag.php
app/Libraries/LocaleMeta.php
app/helpers.php
config/app.php
resources/assets/less/bem/bar.less
resources/assets/less/bem/nav-popup.less
resources/views/forum/topics/_post_info.blade.php
resources/views/layout/_popup_menu.blade.php
resources/views/layout/_popup_user.blade.php
routes/web.php

Also saves per-user locale setting in corresponding table.

Locale switcher

---

app/Jobs/RegenerateBeatmapsetCover.php

This in addition to BSS fixes should resolve #810

Fix Beatmapset Cover Generation

---

.travis.install-mysql-5.7.sh
.travis.yml

We're using MySQL 5.7, so Travis probably should too...

Use MySQL 5.7 on Travis-CI

---

app/Http/Controllers/ContestsController.php
app/Models/Contest.php
app/Models/ContestEntry.php
app/Transformers/ContestEntryTransformer.php
app/Transformers/ContestTransformer.php
database/migrations/2016_11_02_063649_add_user_id_to_contest_entries.php
database/migrations/2016_11_04_022225_add_extra_options_to_contests.php
resources/assets/coffee/react/contest/voting/art-entry-list.coffee
resources/assets/coffee/react/contest/voting/art-entry.coffee
resources/assets/less/bem-index.less
resources/assets/less/bem/contest-art-entry.less
resources/assets/less/bem/contest-art-list.less
resources/assets/less/bem/contest-list-legend.less

Some refactoring work and adds the ability to show (and link to) entrants on contest results page.

Contest System Improvements

---

resources/lang/en/layout.php

Seems this is still used in the mobile layout.

Re-add index TL key

---

resources/assets/coffee/react/beatmap-discussions/nominations.coffee

`or` is `||`, not `&&`

---

app/Libraries/AuthorizationResult.php
app/Models/Beatmapset.php
app/helpers.php

Less queries on beatmapsets index page.

Preload beatmaps when searching beatmapsets

---

app/Models/Score/Best/Model.php

Interestingly no change in line numbers.
Fixes #827.

Include own score when looking for friends score

---

app/helpers.php

Another string to be casted to boolean.

Fix resolving modding issues

---

resources/assets/coffee/react/profile-page/extra.coffee
resources/assets/coffee/react/profile-page/medals.coffee
resources/lang/en/users.php

Except for own profile.
No fix for the messages... yet. ;_;

Only show achieved medals

---

database/migrations/2015_01_01_133337_base_tables.php

Add migration for topic watch

---

resources/assets/coffee/react/beatmap-discussions/beatmap-list.coffee

Fix selecting difficulty in beatmap discussion

---

resources/assets/coffee/react/beatmapset-page/header.coffee
resources/assets/less/bem/beatmap-discussions-header-top.less
resources/assets/less/bem/beatmapset-header.less
resources/assets/less/functions.less

Feels like could be done better but I guess this one fine for now.

Add overlay to beatmap discussions page header

---

resources/assets/coffee/react/beatmap-discussions/new-discussion.coffee

Only send timestamp data when in timeline mode

---

resources/assets/coffee/react/beatmap-discussions/new-discussion.coffee
resources/lang/en/beatmaps.php

Timestamp message and parsing

---

resources/assets/coffee/react/beatmap-discussions/discussion.coffee
resources/assets/coffee/react/beatmap-discussions/discussions.coffee
resources/assets/coffee/react/beatmap-discussions/header.coffee
resources/assets/coffee/react/beatmap-discussions/main.coffee

Updated the chart to reflect current filter.

Discussion chart filter

---

resources/assets/less/bem/beatmap-icon.less

Slightly more centered icons

---

resources/assets/coffee/react/_components/beatmap-basic-stats.coffee
resources/assets/coffee/react/beatmap-discussions/header.coffee
resources/assets/coffee/react/beatmapset-page/stats.coffee
resources/assets/less/bem-index.less
resources/assets/less/bem/beatmap-basic-stats.less
resources/assets/less/bem/beatmap-discussions-header-top.less
resources/assets/less/bem/beatmapset-stats.less

Beatmap stats in discussion

---

resources/assets/coffee/_classes/beatmap-discussions-chart.coffee
resources/assets/coffee/_classes/line-chart.coffee
resources/assets/less/bem/beatmap-discussions-chart.less

Add gradient to the bar/line as per design

---

app/Http/Controllers/Admin/Store/OrderItemsController.php

Cast parameter received by controller action.

Fix updating order item

---

app/Http/Controllers/BeatmapsetsController.php
app/Models/Beatmapset.php
resources/lang/en/beatmaps.php

Add loved category to beatmapset search page

---

app/Http/Controllers/BeatmapsetsController.php
app/Models/BeatmapDiscussion.php
app/Models/Beatmapset.php
app/Models/BeatmapsetDiscussion.php
app/Transformers/BeatmapDiscussionTransformer.php
app/Transformers/BeatmapsetTransformer.php
resources/assets/coffee/react/beatmap-discussions/header.coffee
resources/assets/coffee/react/beatmap-discussions/main.coffee
resources/assets/coffee/react/beatmap-discussions/nominations.coffee

Beatmap discussions fixes

---

app/Models/User.php

Add support for password grant

---

app/Http/Controllers/UsersController.php
app/Models/User.php
resources/lang/en/users.php

In addition to the built-in throttle.

Limit login on oauth endpoint as well

---

app/Models/Beatmapset.php
resources/lang/en/users.php
resources/lang/es/users.php
resources/lang/fr/users.php
resources/lang/nl/users.php
resources/lang/pl/users.php
resources/lang/pt-br/users.php

I think this is the problem source. Properly fixing this requires a different approach.
<sub><sub>Also it's not really that optimized to begin with but the original pull request already took too long.</sub></sub>

Prevent user page from taking too much memory

---

app/Http/Controllers/API/BeatmapsetsController.php
app/Http/Controllers/BeatmapsetsController.php
app/Http/Controllers/UsersController.php
app/Libraries/OsuAuthorize.php
app/Models/Beatmapset.php
app/Models/FavouriteBeatmapset.php
app/Models/User.php
app/Transformers/BeatmapsetTransformer.php
app/Transformers/UserTransformer.php
database/seeds/ModelSeeders/UserProfileSeeder.php
resources/assets/coffee/react/beatmapset-page/header.coffee
resources/assets/coffee/react/beatmapset-page/main.coffee
resources/assets/coffee/react/profile-page.coffee
resources/assets/coffee/react/profile-page/beatmaps.coffee
resources/assets/coffee/react/profile-page/extra.coffee
resources/assets/coffee/react/profile-page/main.coffee
resources/assets/less/bem/beatmapset-header.less
resources/lang/en/beatmaps.php
resources/lang/en/errors.php
resources/lang/fr/users.php
routes/web.php

'Unify' favourite spelling

---

resources/lang/en/users.php
resources/lang/es/users.php
resources/lang/nl/users.php
resources/lang/pl/users.php
resources/lang/pt-br/users.php

Fix merge fail

---

app/Http/Controllers/BeatmapDiscussionPostsController.php
app/Http/Controllers/BeatmapDiscussionsController.php
app/Libraries/OsuAuthorize.php
app/Models/BeatmapDiscussion.php
app/Models/BeatmapDiscussionPost.php
app/Models/DeletedUser.php
app/Transformers/BeatmapDiscussionPostTransformer.php
app/Transformers/BeatmapDiscussionTransformer.php
app/Transformers/BeatmapsetDiscussionTransformer.php
database/migrations/2016_12_01_090638_add_soft_delete_to_beatmap_discussion_posts.php
database/migrations/2016_12_02_092104_add_soft_delete_to_beatmap_discussions.php
resources/assets/coffee/react/beatmap-discussions/discussion.coffee
resources/assets/coffee/react/beatmap-discussions/header.coffee
resources/assets/coffee/react/beatmap-discussions/main.coffee
resources/assets/coffee/react/beatmap-discussions/post.coffee
resources/assets/less/bem/beatmap-discussion-post.less
resources/assets/less/bem/beatmap-discussion.less
resources/assets/less/bem/counter-box.less
resources/lang/en/authorization.php
resources/lang/en/beatmaps.php
resources/lang/en/model_validation.php
resources/lang/en/users.php
resources/lang/es/model_validation.php
resources/lang/fr/model_validation.php
resources/lang/nl/model_validation.php
resources/lang/pl/model_validation.php
resources/lang/pt-br/model_validation.php
routes/web.php

Limited functionality:
- ~~~only for replies~~~ now can delete discussion as well ![](https://e.myconan.net/new.gif)
- only poster or admin can delete
- only admin can restore
- whoever did the last deletion is recorded (but not who restored it)
- event (resolve/unresolve) can't be undone
┐(ﾟ ヮﾟ)┌

Delete discussion post

---

resources/assets/coffee/react/beatmap-discussions/discussion.coffee
resources/assets/coffee/react/beatmap-discussions/discussions.coffee

Fix unable to view general discussions

---

app/Models/DeletedUser.php

Apparently assigning default instance variable using function requires using constructor and stuff. Reverting it for now.

Fix showing deleted user in forum

---

resources/lang/en/accounts.php
resources/lang/en/layout.php
resources/views/layout/_popup_user.blade.php

Forgot to add to menu. And rename page titles.

Account settings link

---

resources/views/accounts/_edit_entry_simple.blade.php

Forgot to quote attribute value

---

app/Models/Multiplayer/Score.php
app/Traits/Scoreable.php

Reflects https://github.com/peppy/osu-stable/pull/2074 .
I think this is okay? First time working on this repo :p

Apply changes to reflect mania ScoreV2 changes.

---

app/Http/Controllers/Forum/TopicsController.php
app/Models/Forum/PollOption.php
app/Models/Forum/Topic.php
app/Models/Forum/TopicPoll.php
resources/views/forum/topics/_poll.blade.php
resources/views/forum/topics/_poll_row.blade.php

Making the loved polls options look less terrible. And fewer queries.

Add bbcode support to poll options

---

app/Http/Controllers/BeatmapsetsController.php
app/Transformers/BeatmapsetTransformer.php
resources/assets/coffee/react/beatmapset-page/header.coffee
resources/assets/less/bem/beatmapset-header.less
resources/assets/less/functions.less
resources/lang/en/beatmaps.php

Also hides download buttons when a beatmapset is no longer available (fixes #881)

Add beatmapset availability info

---

app/Libraries/LocaleMeta.php
config/app.php
resources/assets/less/variables.less

Increasing the height of the menu for now until there's new design for it.
<sub>and sort the locales</sub>

Menu style fix

---

app/Http/Controllers/WikiController.php
app/Libraries/LocaleMeta.php
app/Models/WikiPage.php
composer.json
composer.lock
config/markdown.php
resources/assets/coffee/_classes/wiki.coffee

- tables (with bootstrap styling 💃 )
- more locales
- less non-locales listed as locale
- `shared/` images
Also, `ph` isn't language code. `tl` is 💃

Wiki updates

---

resources/assets/coffee/_classes/wiki.coffee
resources/assets/less/base.less
resources/assets/less/bem/wiki-content.less
resources/assets/less/bem/wiki-page.less
resources/assets/less/bem/wiki-toc-list.less
resources/assets/less/bem/wiki-toc.less
resources/assets/less/variables.less
resources/views/wiki/show.blade.php

- new page headers style
- and a bunch of other style updates
- and some fixes
- all h1 is now removed =D

Wiki fixes

---

app/Http/Controllers/ContestEntriesController.php
resources/assets/coffee/react/contest/entry/uploader.coffee
resources/assets/coffee/react/contest/entry/user-entry-list.coffee
resources/assets/coffee/react/contest/entry/user-entry.coffee
resources/assets/less/bem/contest-userentry-list.less
resources/assets/less/bem/contest-userentry.less
resources/assets/less/bem/contest.less

(also includes minor style/layout fixes)

Allow .osz files (up to 20MB) for beatmap contests (for aspire)

---

resources/assets/coffee/_classes/wiki.coffee

Fix broken image on certain cases.

Ensure absolute url for images in wiki

---

app/Http/Controllers/BeatmapsController.php
app/Models/Score/Best/Model.php
app/Scopes/MacroableModelScope.php
app/Traits/MacroableModel.php

List player once

---

resources/assets/less/bem/wiki-language-list.less
resources/lang/en/wiki.php
resources/views/wiki/show.blade.php

(in wiki)
And slightly shorter wording.

Show currently selected language

---

app/Models/User.php
resources/assets/less/bem-index.less
resources/assets/less/bem/notification-icon.less
resources/views/layout/_header_mobile.blade.php
resources/views/layout/header.blade.php
routes/web.php

Add indicator for forum PMs to header

---

app/Http/Controllers/BeatmapsetsController.php
app/Transformers/BeatmapsetTransformer.php
resources/assets/coffee/react/beatmapset-page/header.coffee
resources/assets/coffee/react/beatmapset-page/scoreboard.coffee
resources/assets/less/bem/beatmap-discussion-nomination.less
resources/assets/less/bem/beatmapset-mapping.less
resources/assets/less/bem/btn-osu-big.less
resources/assets/less/bem/nav-popup.less
resources/assets/less/bem/osu-layout.less
resources/assets/less/bem/osu-page.less
resources/lang/en/beatmaps.php

Link to discussion from beatmapset page... and various other stuff.

Ｍenu hover and beatmapset discussion

---

resources/lang/pt-br/accounts.php

Fix license

---

app/Http/Controllers/Forum/ForumsController.php
resources/assets/coffee/_classes/account-edit.coffee
resources/assets/coffee/_classes/parent-focus.coffee
resources/assets/coffee/main.coffee
resources/assets/less/bem-index.less
resources/assets/less/bem/account-edit-entry.less
resources/assets/less/bem/header-search-box.less
resources/assets/less/bem/osu-nav.less
resources/views/accounts/_edit_entry_simple.blade.php
resources/views/forum/forums/index.blade.php
resources/views/forum/forums/show.blade.php
resources/views/forum/topics/show.blade.php
resources/views/layout/header.blade.php
routes/web.php

- global forum on top forum
- current forum on topic listing
- current topic on topic viewing

Add forum "search"

---

resources/views/forum/topics/_header.blade.php
resources/views/forum/topics/_post.blade.php

Missed forum changes

---

app/Models/Score/Best/Model.php

Just realized it doesn't need anything else so a simple count distinct works here.

Simpler user rank calculation

---

resources/lang/en/model_validation.php
resources/lang/fr/model_validation.php
resources/lang/it/model_validation.php
resources/lang/pt-br/model_validation.php

Fix wrong translation key

---

app/Http/Controllers/BeatmapsetsController.php

Reload the model to avoid using stale data.

Return updated favorite status

---

resources/assets/coffee/react/beatmap-discussions/new-reply.coffee
resources/assets/coffee/react/beatmap-discussions/post.coffee
resources/assets/less/bem/beatmap-discussion-new.less
resources/assets/less/bem/beatmap-discussion-post.less
resources/assets/less/bem/beatmap-discussion-system-post.less
resources/assets/less/bem/beatmap-discussion.less
resources/assets/less/bem/beatmap-discussions.less

Beatmap discussion 2 new

---

resources/views/beatmaps/index.blade.php

Slight darker background on beatmaps index

---

app/Http/Controllers/Forum/PostsController.php

Another missed variable name change

---

composer.json
composer.lock
resources/assets/coffee/_classes/osu-audio.coffee
resources/assets/coffee/main.coffee
resources/assets/coffee/react/_components/beatmapset-panel.coffee
resources/assets/coffee/react/beatmaps/main.coffee
resources/assets/coffee/react/beatmaps/paginator.coffee
resources/assets/coffee/react/beatmaps/search-sort.coffee
resources/assets/less/app.less
resources/assets/less/bem-index.less
resources/assets/less/bem/beatmapset-panel.less
resources/assets/less/bem/beatmapsets-show-more.less
resources/assets/less/bem/beatmapsets-sorting.less
resources/assets/less/bem/beatmapsets.less
resources/assets/less/bem/store-header.less
resources/assets/less/functions.less
resources/views/master.blade.php

Seems working™.
Comes with composer package updates.

Beatmap update design 3 again

---

resources/assets/less/bem/beatmapset-panel.less

Fix broken geometry on firefox

---

resources/lang/en/users.php

:amount already includes the unit

---

app/Exceptions/Handler.php
config/app.php
resources/assets/coffee/react/profile-page/header.coffee
resources/assets/less/bem/profile-header.less
resources/assets/less/bem/spinner.less
resources/assets/less/forum/post-box.less

- skip reporting oauth errors ┐(ಠ_ಠ)┌
- log to single file (dev)
- fix sentry parameters
- misc cleanups

Error report updates and stuff

---

app/Exceptions/GitHubTooLargeException.php
app/Http/Controllers/WikiController.php
app/Models/WikiPage.php
resources/assets/coffee/react/_mixins/scrolling-page.coffee
resources/lang/en/multiplayer.php

- return 422 for oversized files
- case insensitive extension for images
- random profile page fix

Some more fixes for wiki

---

resources/assets/less/bootstrap-variables.less

黑体 is better than Arial Unicode MS
Arial Unicode MS:
黑体:

Add a better font

---

resources/assets/less/bem/beatmap-discussions.less
resources/views/beatmaps/index.blade.php
resources/views/master.blade.php

Style fixes

---

app/helpers.php
resources/assets/less/variables.less
resources/views/layout/metadata.blade.php

Menu fix etc

---

resources/assets/coffee/react/profile-page/header-info.coffee
resources/assets/less/bem/profile-header.less

Mobile fixes and invisible title.

Profile style fixes

---

resources/views/forum/topics/_post_info.blade.php

Will do a better fix later
Fixes #969.

Also escape in forum view

---

app/Models/User.php

Escape some fields

---

app/Models/WikiPage.php
resources/assets/coffee/_classes/osu-audio.coffee
resources/assets/coffee/react/_components/beatmapset-panel.coffee
resources/assets/coffee/react/_components/track-preview.coffee
resources/assets/coffee/react/beatmapset-page/header.coffee
resources/assets/coffee/react/beatmapset-page/main.coffee
resources/assets/coffee/react/beatmapset-page/stats.coffee

- use OsuAudio thingy for beatmapset and contest page as well
- update it to immediately show it's playing (even though it may still be buffering)
- lower volume

Audio update

---

app/Models/Forum/Topic.php
app/Models/Store/Address.php
app/Models/Store/Order.php
resources/lang/en/forum.php
resources/lang/es/forum.php
resources/lang/fr/forum.php
resources/lang/it/forum.php
resources/lang/nl/forum.php
resources/lang/pl/forum.php
resources/lang/pt-br/forum.php
resources/lang/zh/forum.php

More 5.4 fixes

---

app/Models/BeatmapsetEvent.php
app/Models/Forum/Post.php
app/Models/Forum/Topic.php
app/Models/Score/Best/Model.php
app/Models/UserContestEntry.php

~~At least one more I haven't fixed yet.~~ Fixed. The query is weird though technically legal but apparently confuses mysql 5.6 because it's mysql (works in 5.7).

More 5.4 fixes 2

---

app/Models/Beatmapset.php
app/Models/UserContestEntry.php

Otherwise things explode
wasn't paying enough attention (ノ･_･)ノ︵ ┻━┻

Set the values during first commit already

---

app/Models/ContestEntry.php
app/Models/ContestVote.php

Yeah.
Gotta add some actual tests later.

More foreign key update

---

app/Models/Score/Best/Model.php

mysql 5.6 hates order by in aggregate

---

app/Models/BeatmapFailtimes.php
app/Models/BeatmapLeader/Fruits.php
app/Models/BeatmapLeader/Mania.php
app/Models/BeatmapLeader/Model.php
app/Models/BeatmapLeader/Osu.php
app/Models/BeatmapLeader/Taiko.php
app/Models/BeatmapPlaycount.php
app/Models/BeatmapsetUserRating.php
app/Models/Changelog.php
app/Models/FavouriteBeatmapset.php
app/Models/Forum/FeatureVote.php
app/Models/Forum/ForumCover.php
app/Models/Forum/PollOption.php
app/Models/Forum/TopicCover.php
app/Models/Forum/TopicWatch.php
app/Models/Log.php
app/Models/RankHistory.php
app/Models/TournamentRegistration.php
app/Models/User.php
app/Models/UserAchievement.php
app/Models/UserContestEntry.php
app/Models/UserGroup.php

;_;
This should cover everything.

Another foreign key update

---

database/migrations/2017_02_21_084403_mb4_forum_last_topic.php

Updates the cache column charset to utf8.

Emoji topic title

---

database/migrations/2017_02_22_061910_nullables_on_forum_covers.php

Nullables where they should be.

Fix topic and forum covers

---

build.sh

Allow skipping of DB migration via environment variable

---

app/Transformers/UserTransformer.php
resources/assets/coffee/react/beatmap-discussions/nominations.coffee

Fix permission for nominating beatmapset

---

app/Http/Controllers/WikiController.php
app/Models/WikiPage.php

Returns correct mime type.
Also prevent error downloading large file when listing directory.

Wiki image

---

app/Models/WikiPage.php
resources/assets/less/base.less

Undo bootstrap styling for `<code>`

---

app/Libraries/ImageProcessorService.php
app/Models/Beatmapset.php

'cuz having everything as `ErrorException` is dumb. Also silences 'background image missing' errors as they're pretty useless.

Better thumbnailer error tracking

---

README.md
database/factories/AchievementFactory.php
database/factories/CountryFactory.php
database/factories/ProductFactory.php
database/factories/UserFactory.php
database/seeds/DatabaseSeeder.php
database/seeds/ModelSeeders/MiscSeeder.php
database/seeds/ModelSeeders/ProductSeeder.php
database/seeds/ModelSeeders/UserSeeder.php

(one year later)
=D
Updates and closes #433.

Seed updates, updated

---

database/factories/AchievementFactory.php
database/factories/ForumFactory.php
database/factories/StatsFactory.php
database/factories/UserFactory.php
database/migrations/2017_02_06_083745_nullable_cover_json_on_user_profile_customizations.php
database/seeds/DatabaseSeeder.php
database/seeds/ModelSeeders/BeatmapSeeder.php
database/seeds/ModelSeeders/ForumSeeder.php
database/seeds/ModelSeeders/ScoreSeeder.php
database/seeds/ModelSeeders/UserSeeder.php

Fix seeder

---

app/Http/Controllers/Store/Controller.php
app/Http/Controllers/Store/NotificationRequestsController.php
app/Http/Controllers/StoreController.php
resources/lang/en/store.php
resources/lang/es/store.php
resources/lang/fr/store.php
resources/lang/it/store.php
resources/lang/nl/store.php
resources/lang/pl/store.php
resources/lang/pt-br/store.php
resources/lang/zh/store.php
resources/views/store/product.blade.php
routes/web.php

Also fixes unique constraint problem.

Split off store notification request

---

.travis.yml
app/Http/Controllers/Forum/TopicsController.php
app/Models/Forum/AuthOption.php
app/Models/Forum/Authorize.php
app/Models/UserGroup.php
tests/Controllers/ForumForumsControllerTest.php
tests/Controllers/ForumTopicsControllerTest.php

The data initialization is rather crappy ┐(･_･)┌

More tests

---

app/Http/Controllers/Store/NotificationRequestsController.php

Of course I keep forgetting this as well :D
Github green button looks a bit more green now?
Sure is.

Add missing import

---

app/Models/Score/Best/Model.php
app/Transformers/UserTransformer.php

There might be better solution but this one seems to work as well.

Limit one score per beatmap on user profile

---

resources/assets/coffee/react/profile-page/beatmaps.coffee

And then add show more button. Fixes #974.

Only show first 6 of user favorite/ranked beatmaps

---

app/Models/Event.php
app/Models/User.php

Achievement event has been renamed to medal

---

app/Models/Score/Best/Model.php

Ordering by date slows things down.

---

app/Libraries/ImageProcessorService.php

Fix exception rethrow, take 2.

---

app/Models/Score/Best/Model.php

Only use highest score for rank counts

---

bin/mysql_debian_install

No more pgp key download fail

---

resources/lang/en/community.php

"Fix" description

---

resources/lang/pt-br/forum.php

This file was originally translated according to lang/en/forum.php root file.
All translations and dependencies are fully included in this file since the last change, commit: b854c06

added issue_tag in forum to pt-br

---

database/migrations/2017_03_10_080135_add_index_to_user_donations.php

Add correct index to user_donations table

---

resources/assets/less/bem/forum-post.less

Minor style update

---

resources/assets/less/bootstrap-variables.less

reported by **WoldKnight** in osu!
add Microsoft YaHei
rename 黑体->SimHei

fix font and add a new one

---

app/Http/Controllers/Forum/PostsController.php

Fix restoring topic

---

app/Models/BeatmapDiscussion.php
app/Models/Forum/Forum.php
app/Models/Forum/Topic.php
resources/assets/coffee/react/beatmapset-page/scoreboard.coffee
tests/Controllers/HomeControllerTest.php

Fixes and tests

---

app/Http/Controllers/BeatmapDiscussionsController.php

Fix accessing discussion on deleted beatmap

---

app/Models/WikiPage.php
app/helpers.php

The only error they throw is read error.　
Hopefully.
Ａｌｓｏ， https://bugs.php.net/bug.php?id=41321

Fix getimagesize and getimagesizefromstring

---

app/Libraries/BBCodeFromDB.php

Either this or purge current cache.

Forgot about the cache

---

resources/assets/coffee/react/beatmapset-page/header.coffee
resources/assets/less/bem/beatmapset-header.less

Ensure no overflow on long title

---

app/Http/Controllers/HomeController.php
app/Models/BanchoStats.php

Reverse chart

---

app/Http/Controllers/BeatmapDiscussionsController.php
app/Http/Controllers/BeatmapsController.php
app/Http/Controllers/WikiController.php

Not sure why it's not previously detected.

Remove unused imports

---

resources/assets/less/bem/wiki-page.less
resources/assets/less/wiki.less

Break long words/links in wiki pages

---

app/Libraries/OsuAuthorize.php
app/Models/Beatmapset.php
app/Transformers/BeatmapsetTransformer.php
resources/assets/coffee/react/beatmap-discussions/nominations.coffee

┐(ﾟ ヮﾟ)┌
Resolves #1062. Admin only.

Show the nominators

---

app/Models/Forum/TopicWatch.php

Silly me thinking it works as I thought. Of course it doesn't. It converts object into some kind of abomination.

Casting to array doesn't work

---

app/Http/Controllers/AccountController.php
resources/views/emails/user_email_updated-en.blade.php

Not sure if there's better way short of using email confirmation link thingy. Also can use a better wording.

Send message to both addresses

---

app/Http/Controllers/ContestsController.php
app/Http/Controllers/HomeController.php
app/Models/Beatmapset.php
app/Models/Model.php
app/Scopes/MacroableModelScope.php
app/helpers.php
resources/assets/less/bem-index.less
resources/assets/less/bem/user-home-beatmapset.less
resources/assets/less/bem/user-home.less
resources/views/home/_user_beatmapset.blade.php
resources/views/home/user.blade.php

It wasn't sorted before. Fixes #1075.
Also cleaned up some css and sql.

Sort by plays

---

app/Models/Beatmap.php
app/Models/Beatmapset.php

Should fix #1066. I'm not sure if it's the correct behavior ┐(ﾟ ヮﾟ)┌

Also set approval for beatmaps in the set

---

app/Http/Controllers/API/ChatController.php

To senderrrr (~~totally~~ tested).

One missed rename

---

app/Libraries/ProfileCover.php

Absolute url for default covers

---

routes/web.php

Fixes incorrect path being generated for beatmap links

Add prefix for API routes

---

resources/assets/coffee/_classes/account-edit.coffee
resources/assets/less/bem/forum-category-header.less
resources/assets/less/bem/osu-page-header.less
resources/assets/less/bem/osu-page.less
resources/assets/less/bem/wiki-content.less
resources/assets/less/bem/wiki-page.less
resources/views/accounts/_edit_entry_simple.blade.php
resources/views/master.blade.php

Better IE support 💃 
More coming soon... or later...

Browsers fixes

---

app/Http/Controllers/Forum/TopicsController.php

Fix variable name

---

app/Models/Forum/Topic.php
resources/assets/coffee/_classes/forum.coffee
resources/assets/less/bem/forum-post.less
resources/views/forum/topics/show.blade.php

Fixes:
- user topic read marker
- post counter
- mobile fullscreen reply box

Forum fixes

---

app/Http/Kernel.php
app/Http/Middleware/StartSession.php
app/Providers/AppServiceProvider.php

Don't save session if nulled by csrf verifier

---

resources/views/layout/footer.blade.php

Add routes for TOS and Copyright

---

resources/views/home/landing.blade.php

add missing locale_name()                     
before:

fix locale_name

---

resources/assets/coffee/_classes/wiki.coffee

And one other fix.
Fixes #1120.

Don't float wiki page table of contents if too long

---

resources/lang/en/changelog.php
resources/views/home/changelog.blade.php

Add breadcrumbs in changelogs

---

resources/views/home/changelog.blade.php

* highlight the current changelog breadcrumb
* link the breadcrumb to changelog properly when not on main page

Changelog fixes

---

app/Http/Middleware/VerifyUser.php
app/helpers.php
resources/views/admin/contests/show.blade.php
resources/views/artists/index.blade.php
resources/views/contests/index.blade.php
routes/web.php
tests/RouteTest.php

```
/admin/
/api/v2/
/beatmaps/
/beatmapsets/
/community/
/help/
/home/
/oauth/
/session    # no trailing slash
/store/
/users/
```

Namespaces

---

resources/assets/coffee/_classes/turbolinks-disable.coffee

Should be the other way around :dancer:

Fix turbolinks again

---

app/Http/Controllers/SessionsController.php

To allow logging out from new site.

Nuke out old site cookie set at local domain

---

resources/assets/coffee/_classes/wiki.coffee

There's also another toc bug I randomly encounter but couldn't reliably reproduce =[
Fixes #1139.

Fix positioning of wiki toc

---

app/Transformers/UserStatisticsTransformer.php

And php not passing variable to anonymous function.
Fixes #1181.

Wrong variable coupled with null coalesce

---

app/Transformers/UserStatisticsTransformer.php

Forgot about when stats is null.

Fix user with empty stats

---

resources/lang/pt-br/accounts.php
resources/lang/pt-br/admin.php
resources/lang/pt-br/artist.php
resources/lang/pt-br/beatmapsets.php
resources/lang/pt-br/changelog.php
resources/lang/pt-br/common.php
resources/lang/pt-br/home.php
resources/lang/pt-br/layout.php
resources/lang/pt-br/model_validation.php
resources/lang/pt-br/password_reset.php
resources/lang/pt-br/ranking.php
resources/lang/pt-br/wiki.php

All grammar issues, outdated files and not-even-added-files are now updated.
**Do not** forget to review every commit additional information I added (except for the fixes regarding StyleCI), they all have information of what I changed and an explanation of why I modified/deleted that term.
~

Translation overhaul [PT-BR]

---

app/Models/Beatmap.php
resources/lang/en/errors.php
resources/lang/es/errors.php
resources/lang/fr/errors.php
resources/lang/it/errors.php
resources/lang/pt-br/errors.php
resources/lang/zh/errors.php

Ensure valid mode is passed

---

resources/views/layout/footer.blade.php

Reverts ppy/osu-web#1188
I wrote wrong code here:
>layout.legal.*
It should be:
>layout.footer.legal.*
:upside_down_face: : 
this PR is to fix that

Revert #1188 then rewrite it

---

resources/lang/es/layout.php
resources/lang/it/layout.php
resources/lang/nl/layout.php
resources/lang/pl/layout.php
resources/lang/zh/layout.php

Chinese patch-2

---

resources/views/accounts/_edit_playstyle_checkbox.blade.php
resources/views/forum/topics/_create_poll.blade.php

fa-fw shouldn't be used.
Fixes #1195.

Square checkbox

---

resources/lang/en/beatmapsets.php
resources/lang/en/home.php
resources/lang/en/users.php

Fix some awkward wording [en]

---

app/Libraries/OsuMarkdownProcessor.php
app/Models/Wiki/Page.php

- cache missing pages
- only show parsed text for toc. Fixes #1198

Wiki fixes 2

---

app/Libraries/OsuMarkdownProcessor.php

Avoid using image title as text

---

resources/assets/coffee/react/profile-page/cover-uploader.coffee

Fix cover upload

---

app/Http/Controllers/Controller.php
app/Http/Controllers/LegalController.php
app/Http/Controllers/WikiController.php
app/Libraries/OsuMarkdownProcessor.php
app/Models/News/Post.php
app/Models/Wiki/Page.php
app/helpers.php
resources/lang/en/layout.php
resources/views/layout/footer.blade.php
resources/views/wiki/show.blade.php
routes/web.php

Terms and Copyright page at top route

---

resources/assets/less/bem/btn-osu-big.less
resources/assets/less/bem/forum-post.less
resources/assets/less/bem/landing-hero.less
resources/views/home/landing.blade.php

Improved mobile design

---

resources/assets/coffee/react/beatmapset-page/info.coffee
resources/assets/less/bem/beatmap-success-rate.less
resources/assets/less/bem/beatmapset-info.less

I thought there's an open issue for this but apparently not? ಠ_ಠ

Fix styling for beatmap success rate box

---

resources/assets/coffee/react/beatmapset-page/info.coffee

Fixed one thing and broke another ;_;
jsx is a lie.

More chart fixes

---

app/Libraries/OsuMarkdownProcessor.php

Forgot to bump version on stuff updates

---

app/Libraries/OsuMarkdownProcessor.php
resources/assets/less/bem/osu-md.less

...assuming it's markdown image and not inline html, that is.
Can use a merge of ppy/osu-wiki#292.

Center lone image and add caption if it has title

---

app/Libraries/OsuMarkdownProcessor.php

Accidentally committed experimental thing :(

Wrong type

---

app/Models/Store/Product.php

So iterators don't burst into flames

return empty array if images is null.

---

app/Models/User.php

User website validation

---

resources/views/rankings/performance.blade.php
resources/views/rankings/score.blade.php

Clamps grade counts to 0 and fixes flag tooltips

Fixes for rankings

---

resources/assets/coffee/react/beatmapset-page/header.coffee

Fix link to discussion

---

resources/assets/less/bem/proportional-container.less

Allow image slicing with bbcode

---

resources/views/accounts/_edit_email.blade.php

Fix wrong trans()

---

app/Http/Controllers/BeatmapsetsController.php
app/Models/BeatmapDiscussion.php
resources/assets/coffee/react/beatmap-discussions/discussions.coffee
resources/assets/coffee/react/beatmap-discussions/main.coffee
resources/assets/coffee/react/beatmap-discussions/mode-switcher.coffee
resources/assets/coffee/react/beatmap-discussions/new-discussion.coffee
resources/lang/en/beatmaps.php
tests/Models/BeatmapDiscussionTest.php

The branch name reminds me of something but I can't remember exactly what it is ಠ_ಠ

Per-difficulty modding discussion

---

resources/assets/coffee/_classes/user-login.coffee
resources/assets/coffee/osu_common.coffee
resources/assets/coffee/react/profile-page/cover-uploader.coffee
resources/assets/coffee/react/profile-page/header-extra.coffee
resources/assets/coffee/react/profile-page/main.coffee

Verification on profile rearrange 

---

app/Libraries/OsuMarkdownProcessor.php
composer.json
composer.lock
resources/assets/less/bem/osu-md.less

Includes package updates.
Fixes #1225.

Table fixes

---

resources/assets/coffee/_classes/store-supporter-tag.coffee

Add turbolinks support for supporter tag thingy

---

app/Http/Controllers/StoreController.php
resources/views/store/header.blade.php

Resolves #91 
The general consensus is we're going to remove the button, therefore, #91 will no longer be a problem anymore :trollface:

Remove back button link from store banner

---

resources/assets/coffee/_classes/store-supporter-tag.coffee

Another missing bracket

---

app/Models/Store/Order.php
app/Models/Store/Product.php
resources/views/store/invoice.blade.php
resources/views/store/product.blade.php

I'm not sure if `0` weight items should be considered 🤔

Remove shipping-related text when shipping is not involved

---

app/Http/Controllers/BeatmapsetsController.php
app/Http/Middleware/TurbolinksSupport.php
app/Models/Beatmapset.php
app/helpers.php
resources/assets/coffee/_classes/beatmapset-filter.coffee
resources/assets/coffee/_classes/react-turbolinks.coffee
resources/assets/coffee/react/_components/beatmapset-panel.coffee
resources/assets/coffee/react/beatmaps.coffee
resources/assets/coffee/react/beatmaps/main.coffee
resources/assets/coffee/react/beatmaps/paginator.coffee
resources/assets/coffee/react/beatmaps/search-filter.coffee
resources/assets/coffee/react/beatmaps/search-panel.coffee
resources/assets/coffee/react/beatmaps/search-sort.coffee

This thing has gotten a bit larger than I expected 8D
- actual search on main page load
- don't unmount react but save state instead on navigation; fixes #552, closes #553
- added total to `Beatmapset::search()` result
- less confusing castings which also fixes #908 and fixes #1142
- fixed bugs
- added bugs

Beatmapsets search refactor

---

app/Http/Controllers/HomeController.php
app/Models/Build.php

There's also weird inconsistency where changelog and build have different stream_id (null in build but not null in changelog).

Limit searching builds with non-null stream id

---

resources/assets/less/bem/changelog-stream.less
resources/views/home/_changelog_stream.blade.php
resources/views/home/changelog.blade.php

Fix changelog

---

app/Models/User.php
resources/assets/coffee/_classes/nav-search.coffee
resources/views/home/_search_wiki_page.blade.php

┐(ﾟ ヮﾟ)┌
Hides restricted/banned/inactive/etc users, changes sorting order and reduces debounce duration to speed up search. Also removes a stray quote.

Search fixes

---

app/Models/Wiki/Page.php
app/helpers.php
resources/assets/coffee/_classes/nav-search.coffee
resources/assets/less/bem/nav-search.less
resources/assets/less/bem/search.less
resources/lang/en/layout.php
resources/views/home/_search_results.blade.php
resources/views/home/nav_search_result.blade.php
resources/views/layout/_popup_search.blade.php

More search fixes

---

resources/views/home/_search_results.blade.php
resources/views/home/search.blade.php

Abstraction fail as predicted.

Search limit

---

app/Http/Controllers/UsersController.php
app/Models/Store/Order.php

Apply defaultScope on supporter-tag store user lookups

---

app/Http/Controllers/RankingController.php

Handles invalid country codes more gracefully

Misc fixes pt. 2

---

app/Models/News/Post.php
app/helpers.php
resources/views/home/_user_news_post_preview.blade.php

Note that this requires news posts from now on have image embeds in markdown and not html (at least for the header image)

News image fix

---

resources/lang/ru/supporter_tag.php

Add additional index to translation for issue #1284

---

resources/assets/coffee/react-namespaces.coffee
resources/assets/coffee/store-username-change.coffee

Add missing license headers

---

resources/assets/less/variables.less

Whee 💃 
(avoid language menu overflow)

Even taller menu

---

app/Http/Controllers/TournamentsController.php

Fix redirect using correct route

---

package.json
webpack.config.js

mix looks in the wrong place if node_modules is symlinked

---

.travis.yml
app/Models/Forum/Forum.php
app/Models/Forum/Post.php
app/Models/Wiki/Page.php
app/helpers.php
resources/assets/coffee/_classes/nav-search.coffee
resources/assets/coffee/_classes/nav.coffee
resources/assets/coffee/_classes/search.coffee
resources/assets/coffee/main.coffee
resources/assets/less/bem-index.less
resources/assets/less/bem/btn-osu-big.less
resources/assets/less/bem/nav-popup.less
resources/assets/less/bem/osu-checkbox.less
resources/assets/less/bem/page-mode-link.less
resources/assets/less/bem/page-mode.less
resources/assets/less/bem/search-advanced-forum-post.less
resources/assets/less/bem/search-entry.less
resources/assets/less/bem/search-header.less
resources/assets/less/bem/search-result.less
resources/assets/less/bem/search.less
resources/assets/less/functions.less
resources/assets/less/variables.less
resources/lang/en/home.php
resources/lang/en/layout.php
resources/views/forum/topics/_moderate_move.blade.php
resources/views/home/_search_advanced_forum_post.blade.php
resources/views/home/search.blade.php
resources/views/layout/_popup_search.blade.php
yarn.lock

- advanced forum search
- other cleanups

Search cleanup

---

app/Models/Beatmapset.php

Approval maps only require 2 nominations

---

app/Http/Controllers/API/ChatController.php
app/Models/Chat/Channel.php
app/Models/User.php
app/Transformers/API/Chat/MessageTransformer.php
database/migrations/2017_07_14_040809_add_action_field_to_chat_tables.php

Add action support to chat api

---

.env.example
composer.json
composer.lock
config/osu.php
config/sentry.php
config/services.php
package.json
resources/views/layout/metadata.blade.php
webpack.mix.js
yarn.lock

A few updates:
- add error logging for javascript
- add version metadata to errors
- sentry-laravel sdk version bump

Sentry error logging improvements

---

app/Libraries/OsuMarkdownProcessor.php

Forgot about this.
Fixes #1335.

Allow mailto: links

---

app/Models/UserStatistics/Model.php

Correctly compare rank_score

---

resources/assets/coffee/main.coffee
resources/assets/coffee/react/_components/friend-button.coffee
resources/assets/less/bem/friend-button.less
resources/assets/less/bem/usercard.less
resources/views/home/_search_user_quick.blade.php
resources/views/home/nav_search_result.blade.php
resources/views/objects/_usercard.blade.php

Now with card instead of just avatar.
Also fix alignment stuff.

Usercard search

---

resources/assets/coffee/_classes/beatmap-helper.coffee
resources/assets/less/bem/beatmap-icon.less

New difficulty colors

---

resources/assets/coffee/react/_components/friend-button.coffee
resources/assets/less/bem/friend-button.less

Safari doesn't support flex on button 💃

Friend button safari

---

resources/views/layout/metadata.blade.php
webpack.mix.js

Add user locale to error metadata and fix sourcemap generation

More sentry fixes

---

resources/assets/coffee/_classes/account-edit-avatar.coffee
resources/assets/coffee/_classes/forum-cover.coffee
resources/assets/coffee/osu_common.coffee
resources/assets/coffee/react/contest/entry/uploader.coffee
resources/assets/coffee/react/profile-page/cover-uploader.coffee

It recreates the dom every upload, obsoleting previously held reference.

Ensure current object when dealing with fileupload

---

app/helpers.php
resources/assets/coffee/_classes/user-card.coffee
resources/assets/less/bem/usercard.less
resources/views/objects/_usercard.blade.php

Make covers more visible.
And other minor refactors ┐(ツ)┌

Usercard cover visibility

---

resources/assets/coffee/_classes/account-edit.coffee
resources/assets/coffee/_classes/post-preview.coffee
resources/assets/coffee/_classes/turbolinks-ujs.coffee
resources/assets/less/bem/osu-page-header.less
resources/views/accounts/_edit_entry_simple.blade.php
resources/views/accounts/_edit_playstyles.blade.php

Race condition, overloading class (not quite fixed), wrong class, and ujs/turbolinks stuff.

Even more js fixes

---

app/Traits/UserAvatar.php

To allow serving it with correct mime type.

Store avatar extension

---

app/Http/Controllers/FriendsController.php

Fix adding/removing friends

---

app/Models/Score/Best/Model.php

Missed a reference when refactoring stuff, whoops.

Fix beatmapset friend ranking.

---

app/Models/User.php

Fix online friends count

---

app/Http/Middleware/SetLocale.php
config/app.php

Localized carbon

---

resources/assets/coffee/react/_components/beatmapset-mapping.coffee
resources/assets/coffee/react/mp-history/event.coffee
resources/assets/coffee/react/mp-history/game-header.coffee
resources/assets/coffee/react/profile-page/achievement-badge.coffee
resources/assets/coffee/react/profile-page/header-extra.coffee
resources/lang/en/common.php

Use built-in format and add missing ones

---

resources/assets/coffee/react/profile-page/header-extra.coffee

Decided to change the key name and then forgot to update where it's used.

Forgot to update the key used

---

app/helpers.php
resources/lang/en/common.php

Another date formatting

---

resources/lang/ru/layout.php

**Added: 'packs**' => 'паки', (line 55)
**Changed**: 'kudosu' => 'кудос', to 'kudosu' => 'кудосу', (line 69)

Update Russian layot.php

---

app/Http/Controllers/HomeController.php

Another place with missing i18n.

More i18n date

---

resources/lang/en/beatmaps.php
resources/lang/es/beatmaps.php
resources/lang/fr/beatmaps.php
resources/lang/it/beatmaps.php
resources/lang/nl/beatmaps.php
resources/lang/pl/beatmaps.php
resources/lang/pt-br/beatmaps.php
resources/lang/ru/beatmaps.php
resources/lang/zh/beatmaps.php

Outdated translations removed. Fixes #1396.

Rename "total" to "all"

---

app/Models/BeatmapDiscussion.php
database/migrations/2017_08_03_064207_unresolve_non_issue_beatmap_discussions.php
resources/assets/coffee/react/beatmap-discussions/new-reply.coffee
tests/Controllers/BeatmapDiscussionPostsControllerTest.php

Only allow resolve state change for issues

---

resources/assets/less/bem/osu-page.less

Accidentally css

---

resources/assets/coffee/_classes/twitch-player.coffee
resources/views/livestreams/_featured.blade.php

Now with 100% more turbolinks compatibility.

Update twitch player

---

app/Libraries/OsuAuthorize.php
database/migrations/2017_08_03_064207_unresolve_non_issue_beatmap_discussions.php
resources/assets/coffee/react/beatmap-discussions/post.coffee
resources/assets/less/bem/tooltip-default.less

Fixes #1411 and various misc things. Also granted QAT various modding moderation privileges.

Discussion fixes

---

app/Libraries/OsuAuthorize.php

Forgot some of them don't even have user auth check.

Fix auth check on beatmap discussion

---

resources/assets/coffee/react/beatmap-discussions/discussion.coffee
resources/assets/less/bem/beatmap-discussion-vote.less

Disable vote button for own post

---

app/Models/BeatmapDiscussion.php

beatmap_id is not guaranteed to be set.

Fix accessing beatmapset from discussion model

---

app/Libraries/ValidationErrors.php
app/Models/Forum/FeatureVote.php
app/Models/Forum/PollVote.php
app/Models/Forum/TopicPoll.php
app/Models/Forum/TopicVote.php
app/Models/UserEmail.php
app/Models/UserPassword.php

ValidationErrors->isAny() seems to be flipped

---

app/Http/Controllers/Forum/TopicsController.php

No idea why firing event immediately returns response :psyduck:
Also no test for the event whoops.

Workaround travis error

---

app/Libraries/OsuMarkdownProcessor.php
app/helpers.php

Not sure if needed.
Fixes #1421 server side.

Strip utf8 byte order mark before parsing

---

resources/assets/coffee/_classes/nav-search.coffee
resources/assets/less/bem/nav-popup.less
resources/assets/less/variables.less
resources/views/layout/_popup_menu.blade.php
resources/views/layout/_popup_search.blade.php

And a bit of cleanup which ended up not related because design change.

Social links in menu

---

resources/assets/less/bem/nav-search-result.less
resources/views/home/nav_search_result.blade.php

Now a bit less tall thanks to title moved to the right side.

New quick search style

---

resources/views/layout/_popup_menu.blade.php

Change the URL for the Twitter button

---

app/Http/Controllers/RankingController.php
app/Models/CountryStatistics.php
resources/assets/coffee/react/beatmaps/main.coffee

More misc fixes

---

package.json
resources/assets/coffee/react/beatmap-discussions/discussion.coffee
resources/assets/coffee/react/beatmap-discussions/new-reply.coffee
resources/assets/less/bem/beatmap-discussion-post.less
resources/assets/less/bem/btn-osu-big.less
resources/lang/en/beatmap_discussions.php
resources/lang/en/beatmaps.php
webpack.mix.js
yarn.lock

Fixes #1077.
Also nuke out animation.

Click to open reply box in modding

---

app/Libraries/OsuAuthorize.php
app/Models/BeatmapDiscussionPost.php

Ignore system posts when deleting discussion

---

resources/assets/coffee/_classes/reply-preview.coffee
resources/assets/less/bem/fixed-bar.less
resources/assets/less/bem/forum-post-content.less
resources/assets/less/bem/forum-post.less
resources/assets/less/bem/page-mode-link.less
resources/assets/less/bem/page-mode.less
resources/views/forum/topics/show.blade.php

Fixes #1430.
And add new button/tab styling.

Improved post reply preview

---

resources/assets/coffee/_classes/twitch-player.coffee

Not really important because there's only one player at the moment =D

Only open relevant player

---

app/Models/Wiki/Page.php

- title field has highest priority
- (cleaned up) path field has higher priority (requires reindexing)
- limit search in current locale
Incoming complains from people using other locales can't search english wiki pages.

Improve wiki search

---

app/Models/Wiki/Page.php

Turns out it's pretty simple ☜(ﾟヮﾟ☜)

Always include English pages for wiki search

---

app/Libraries/OsuMarkdownProcessor.php

slug removes too many characters.

Only replace spaces with dashes

---

app/Models/Score/Model.php
app/Transformers/ScoreTransformer.php
app/Transformers/UserTransformer.php

Remove beatmapset_id from scores

---

resources/assets/less/bem/osu-md.less

Style h3 for news

---

app/Libraries/BBCodeForDB.php
app/Libraries/BBCodeFromDB.php
tests/Libraries/bbcode_examples/basic_img.db.txt

Something somewhere was broken.

Fix bbcode image url

---

app/Http/Controllers/HomeController.php
app/Libraries/Search.php
app/helpers.php
resources/views/home/nav_search_result.blade.php
resources/views/home/search.blade.php

Simplify search stuff

---

composer.json
composer.lock

No changelog found, hopefully just updating compatibility with backend oauth library ( ･_･)a

Update to latest oauth library

---

app/Http/Controllers/HomeController.php
app/Libraries/Search.php

Supersedes #1478 by not searching at all just to generate url.

Search fix

---

app/Libraries/Search.php
app/Models/Beatmapset.php

Fix missing parameter in search instrumentation

---

webpack.mix.js

burst into flames if node_modules file isn't there

---

app/Models/Beatmap.php
app/Transformers/BeatmapDiscussionTransformer.php
app/Transformers/BeatmapsetDiscussionTransformer.php
database/migrations/2017_09_04_064001_add_deleted_at_to_beatmaps.php
resources/assets/coffee/react/beatmap-discussions/main.coffee

Soft delete for beatmap

---

app/Models/Beatmapset.php

More missed update to beatmapset_id column removal.

Beatmapsets by score fix

---

app/Models/User.php

`isSilenced` is called repeatedly in forum topics.

Memoize isSilenced and refactor variables

---

resources/assets/coffee/react/profile-page/header-main.coffee
resources/assets/coffee/react/profile-page/user-page.coffee
resources/assets/less/bem/btn-circle.less
resources/assets/less/bem/forum-topic-nav.less
resources/views/forum/_cover_editor.blade.php
resources/views/forum/_post_toolbar.blade.php
resources/views/forum/topic_watches/_topic_buttons.blade.php
resources/views/forum/topics/_issue_tag.blade.php
resources/views/forum/topics/_lock.blade.php
resources/views/forum/topics/_moderate_move.blade.php
resources/views/forum/topics/_moderate_pin.blade.php
resources/views/forum/topics/_post.blade.php
resources/views/forum/topics/_post_hide_action.blade.php
resources/views/forum/topics/_watch.blade.php
resources/views/forum/topics/show.blade.php
resources/views/livestreams/_featured.blade.php
resources/views/livestreams/_livestream.blade.php
resources/views/news/index.blade.php
resources/views/news/show.blade.php
resources/views/wiki/show.blade.php

Thx, browsers ┐(' ヮ' )┌
Fixes #1503.

Button fixes

---

package.json
yarn.lock

Should be `username/repository#commithash` instead of the whole URL.

Fix incorrect entry in package.json

---

resources/assets/less/bem/artist-link-button.less

Fixes alignment being slightly off on hover

Featured artist button tweak

---

app/Http/Controllers/Forum/PostsController.php
app/Models/User.php
resources/views/forum/topics/_post_info.blade.php
resources/views/forum/topics/show.blade.php

- replying to deleted post
- less queries
- ~~order by post_time~~
more coming soon™

Forum fixes 

---

app/Models/Score/Best/Model.php
database/migrations/2017_08_29_060956_denormalize_high_score_tables.php

Less joins, faster queries

---

database/migrations/2017_09_08_110651_simplify_forum_posts_index.php
resources/assets/coffee/shared.coffee

The missed migration for `topic_id` `deleted_at` (and `topic_id` itself). And simplified form submission limiter.

A bit more fixes

---

database/migrations/2017_09_12_065003_fix_logs_table_encoding.php

Fix encoding of logs table

---

app/Http/Controllers/WikiController.php
app/Libraries/WikiRedirect.php

Fixes #1538 a bit. Still doesn't handle loop involving two or more redirects.

Wiki redirect

---

app/Libraries/OsuAuthorize.php

Let QAT moderate forums

---

app/Models/Store/Order.php

Die on negative price; ignore submitted value.

fix negative item cost

---

app/Libraries/OsuAuthorize.php
app/Models/Beatmapset.php
app/Transformers/BeatmapsetEventTransformer.php
app/Transformers/BeatmapsetTransformer.php
resources/assets/coffee/react/beatmap-discussions/header.coffee
resources/assets/coffee/react/beatmap-discussions/nominations.coffee

Show nominators to public

---

app/Http/Controllers/Forum/TopicsController.php
app/Models/Forum/Topic.php
resources/lang/en/forum.php
resources/views/forum/topics/_moderate_pin.blade.php

The bar is getting a bit crowded.
Fixes #1533.

Add support for marking topic as announcement

---

app/Models/Build.php

Current history only contains stable and fallback ಠ_ಠ

Ignore test_build flag when logging for history

---

app/Http/Controllers/Forum/PostsController.php
app/Libraries/OsuAuthorize.php
resources/lang/en/authorization.php

Allow editing deleted post

---

resources/assets/coffee/_classes/turbolinks-disqus.coffee
resources/assets/coffee/_classes/turbolinks-reload.coffee
resources/assets/coffee/_classes/twitch-player.coffee
resources/assets/coffee/main.coffee

Refactor loading of external js

---

app/Models/User.php
config/osu.php
resources/assets/less/bem/paginator.less
resources/assets/less/bem/search-result.less
resources/assets/less/bem/search.less
resources/assets/less/variables.less
resources/lang/en/home.php
resources/views/home/_search_advanced_forum_post.blade.php
resources/views/home/_search_results.blade.php
resources/views/home/search.blade.php

Limit user search result

---

app/Models/Forum/TopicPoll.php

Fix poll length calculation

---

resources/assets/coffee/react/beatmapset-page/header.coffee

Mainly just changing indentation =D

Always show beatmapset discussion link if enabled

---

resources/assets/coffee/_classes/forum.coffee

Show delete button for qat

---

app/Models/BeatmapMirror.php

Fix beatmapset/osz download filenames

---

resources/views/friends/index.blade.php

Content section is wider than it should be

Fix missing class on friends listing page

---

app/Http/Controllers/BeatmapsetsController.php
app/Libraries/UserVerification.php
app/helpers.php
resources/views/store/objects/new_address.blade.php

With one broken since forever =D

Unify all request country getter

---

resources/assets/coffee/_classes/landing-user-stats.coffee
resources/assets/less/bem/landing-hero.less

Ensure no blank space at the bottom.
Workarounds/fixes #1593 until someone comes up with better idea.

Fix landing chart alignment

---

resources/assets/coffee/_classes/blackout.coffee
resources/assets/coffee/react/beatmap-discussions/beatmap-list.coffee

Lighter blackout for beatmap selector in discuss

---

resources/lang/pl/home.php

Corrected pl translation

---

routes/web.php
tests/Controllers/UsersControllerTest.php

Not quite ready to be live yet...

Disable user creation route

---

resources/assets/less/variables.less

Honestly I'd just nuke `@media @mobile` ಠ_ಠ
Mobile first stuff.
Though considering the original design is only desktop maybe should go the other way with desktop-first ?_?

Fix wrong max-width for mobile.

---

app/Libraries/Payments/PaypalApiContext.php

paypal default is sandbox :trollface:

---

app/Libraries/Payments/PaypalApiContext.php
resources/assets/lib/store-xsolla.coffee
webpack.mix.js

bug ?_?
Also, match a production setting.

DefinePlugin not doing string replacements?

---

app/Http/Controllers/AccountController.php
app/Models/User.php
database/factories/UserFactory.php
resources/assets/coffee/_classes/account-edit.coffee
resources/assets/coffee/react/_components/friend-button.coffee
resources/assets/coffee/react/profile-page/header-extra.coffee
resources/assets/less/bbcode.less
resources/assets/less/bem/detail-row.less
resources/assets/less/bem/profile-header-extra.less
resources/lang/en/model_validation.php
resources/views/accounts/_edit_entry_simple.blade.php
resources/views/accounts/edit.blade.php

Also tweaks mobile view for said fields.
fixes #1582

Add field limit checks to user profile fields display/editing

---

resources/assets/less/bem/forum-topic-title.less
resources/views/forum/forums/_topic.blade.php
resources/views/forum/topics/_header_title.blade.php

This fixes #1588 (but not #1620)

Truncate long topic/thread titles during display

---

resources/assets/less/bem/navbar-mobile.less
resources/assets/less/bem/osu-nav.less
resources/views/layout/_header_mobile.blade.php
resources/views/layout/header.blade.php

Header title overflow

---

app/Libraries/Payments/NotificationType.php
app/Libraries/Payments/PaymentProcessor.php
app/Libraries/Payments/PaypalPaymentProcessor.php
app/Listeners/Fulfillments/PaymentSubscribers.php
app/Models/Store/Order.php
resources/lang/en/model_validation/payments.php
resources/views/store/invoice.blade.php

#1641
Send a notification and mark as waiting for eCheck to clear instead of exploding.

Support Pending notification from Paypal

---

resources/assets/less/bem/btn-circle.less
resources/views/forum/topics/_issue_tag.blade.php
resources/views/forum/topics/_lock.blade.php
resources/views/forum/topics/_moderate_move.blade.php
resources/views/forum/topics/_moderate_pin.blade.php

Change forum moderation icon colours so they stand out

---

app/Http/Controllers/BeatmapDiscussionPostsController.php
app/Http/Controllers/BeatmapsetWatchesController.php
app/Http/Controllers/BeatmapsetsController.php
app/Http/Controllers/Forum/TopicsController.php
app/Jobs/NotifyBeatmapsetUpdate.php
app/Mail/BeatmapsetUpdateNotice.php
app/Models/BeatmapDiscussion.php
app/Models/Beatmapset.php
app/Models/BeatmapsetWatch.php
app/Models/User.php
app/Transformers/BeatmapsetTransformer.php
database/migrations/2017_10_20_133251_add_beatmapset_watches.php
resources/assets/coffee/react/beatmap-discussions/header.coffee
resources/assets/coffee/react/beatmap-discussions/subscribe.coffee
resources/assets/less/bem-index.less
resources/assets/less/bem/beatmap-discussions-header-bottom.less
resources/assets/less/bem/beatmapset-watches.less
resources/lang/en/beatmapset_watches.php
resources/lang/en/forum.php
resources/lang/en/layout.php
resources/views/beatmapset_watches/index.blade.php
resources/views/emails/beatmapset/update_notice-en.blade.php
resources/views/forum/topic_watches/_topic_buttons.blade.php
resources/views/home/_user_header_nav.blade.php
routes/web.php

Beatmapset watches

---

app/Models/User.php

Don't prefix if user website is blank

---

app/Http/Controllers/StoreController.php
app/Models/Store/Order.php
resources/views/store/invoice.blade.php

because that would be silly :trollface:

Unchecked out carts shouldn't have invoices

---

resources/assets/less/bem/beatmap-discussion-post.less

Prevent overflow on discussion post

---

app/Http/Controllers/Payments/PaypalController.php
resources/lang/en/paypal/errors.php
resources/lang/en/store.php
resources/views/store/checkout.blade.php

Show something besides the something died page.

Show an error message if Paypal checkout fails.

---

app/Listeners/Forum/NotifyEmail.php

Checked wrong attribute. Additionally add skip for event triggerer.
Fixes #1688.

Fix forum new reply listener

---

resources/assets/coffee/_classes/tooltip-default.coffee
resources/assets/less/bem/forum-topic-entry.less
resources/assets/less/utilities.less
resources/views/forum/forums/_topic.blade.php

Fix forum title in mobile

---

.env.example
config/osu.php
resources/assets/coffee/_classes/nav-search.coffee
resources/views/layout/header.blade.php

Not sure why no pull request of this yet.
Fixes #1643.

Configurable minimum search length

---

app/Http/Controllers/UsersController.php
app/Models/User.php
app/Models/UserNotFound.php
resources/assets/coffee/_classes/store-supporter-tag.coffee
resources/assets/coffee/react/_components/friend-button.coffee
resources/assets/less/bem/grid-cell.less
resources/assets/less/bem/grid.less
resources/assets/less/bem/store-slider.less
resources/assets/less/bem/store-supporter-tag.less
resources/assets/less/bem/usercard.less
resources/assets/less/variables.less
resources/lang/en/store.php
resources/lang/en/supporter_tag.php
resources/views/store/products/supporter-tag.blade.php

Change the store supporter page to use usercards and some layout adjustments

Switch supporter store page to use usercards

---

resources/lang/zh/beatmapset_watches.php

[zh] Chinese patch-9.1

---

resources/assets/coffee/react/beatmap-discussions/discussion.coffee
resources/assets/less/bem/beatmap-discussion-new.less
resources/assets/less/bem/beatmap-discussion-post.less
resources/assets/less/bem/beatmap-discussion-system-post.less
resources/assets/less/bem/beatmap-discussion.less

Discussion style update

---

resources/assets/coffee/react/_components/big-button.coffee
resources/assets/coffee/react/beatmap-discussions/new-discussion.coffee
resources/assets/coffee/react/beatmap-discussions/new-reply.coffee

Disable form when posting and remove jump to post on completion. Fixes #1719.

Beatmapset discussion updates

---

resources/assets/less/bem/nav-popup.less
resources/assets/less/bem/search-advanced-forum-post.less
resources/assets/less/bem/search-header.less
resources/assets/less/variables.less

Remove redundant less variable

---

resources/assets/coffee/react/_components/playmode-tabs.coffee
resources/assets/coffee/react/beatmapset-page/header.coffee

Show beatmap counts on beatmapset page

---

app/Models/BeatmapDiscussion.php

Fixes incorrect open issues count in watchlist.

Ignore discussions of deleted beatmaps

---

resources/assets/coffee/_classes/blackout.coffee

Forgot that fade works with opacity as well.

Fix custom blackout opacity

---

app/Console/Commands/KudosuRecalculateDiscussionsGrants.php
app/Console/Kernel.php
app/Models/BeatmapDiscussion.php

Also includes a command that can be used to retroactively grant kudosu with the new thresholds.

Lower threshold for kudosu gain from beatmap discussion upvotes

---

resources/assets/less/bem/beatmap-discussion-new.less
resources/assets/less/bem/beatmap-discussion-nomination.less
resources/assets/less/bem/beatmap-discussion-post.less

Apparently `flex: 1` means "shrink as much as possible even if the contents overflow".

Fixes for best browser ever™

---

app/Models/BeatmapDiscussion.php

beatmap is null on non difficulty specific discussions

---

app/Models/Beatmapset.php
resources/assets/coffee/react/beatmap-discussions/nominations.coffee

Not sure if the logic is correct ┐(°～° )┌
(also not sure why there's a `startOfDay`)

Include the one week delay for ranking maps

---

resources/assets/coffee/react/beatmap-discussions/main.coffee
resources/assets/coffee/react/beatmap-discussions/new-discussion.coffee
resources/assets/less/bem-index.less
resources/assets/less/bem/beatmap-discussion-new-float.less
resources/assets/less/bem/beatmap-discussion-new.less

Float, stick, fix, whatever ಠ_ಠ
Seems to work.

Allow sticking new discussion box

---

resources/assets/coffee/react/_components/playmode-tabs.coffee

single item array returning true instead of 1 :v

Fix modes with single map not showing number

---

app/Libraries/OsuAuthorize.php

60 per hour for normal users and unlimited for QAT/BNG
fixes #1744

Increase upvote limit for beatmap discussions

---

resources/assets/less/bem/forum-post.less

Prevent reply box from overflowing

---

app/Models/Store/Order.php

Remove unused variables

---

app/Models/Beatmapset.php
app/Models/Event.php

Qualification event log

---

resources/assets/less/bem/beatmap-discussion-new.less

Less icon crushing by preventing shrink.

Fix buttons in ie

---

resources/assets/less/bem/beatmap-discussion-new-float.less

Apply pointer events to right element

---

resources/assets/coffee/react/profile-page/main.coffee
resources/assets/coffee/react/profile-page/user-page.coffee

At one point, the html for empty page is no longer empty.

Fix hiding user page when empty

---

app/Libraries/OsuAuthorize.php
app/Models/BeatmapDiscussion.php

Limit voting per discussion

---

app/Exceptions/Handler.php

Thanks, mysql 💃 
(can be more sophisticated)

Hide sql error

---

app/Models/BeatmapDiscussion.php
resources/assets/coffee/react/beatmap-discussions/post.coffee
resources/lang/en/beatmaps.php

With best styling ever.
Fixes #1770? Not sure if should show who denied it as well.

Indicate kudosu denied posts

---

app/Models/Beatmapset.php

It should include WIPs as well. Fixes #1772.

Fix unranked scope

---

resources/assets/coffee/react/beatmapset-page/main.coffee

It doesn't depend on any of the states.

Don't reload disqus on state change

---

app/Models/User.php

Fix wrong field being updated on username change

---

app/Models/BeatmapDiscussion.php
database/factories/BeatmapDiscussionFactory.php
database/migrations/2017_11_22_070257_update_discussion_type_by_mapper.php
resources/assets/coffee/_classes/beatmap-discussion-helper.coffee
resources/assets/coffee/_classes/beatmap-discussions-chart.coffee
resources/assets/coffee/react/beatmap-discussions/discussion.coffee
resources/assets/coffee/react/beatmap-discussions/header.coffee
resources/assets/coffee/react/beatmap-discussions/main.coffee
resources/assets/coffee/react/beatmap-discussions/new-discussion.coffee
resources/assets/less/bem/beatmap-discussion-message-type.less
resources/assets/less/bem/beatmap-discussions-chart.less
resources/assets/less/bem/counter-box.less
resources/assets/less/variables.less
resources/lang/en/beatmaps.php
tests/Controllers/BeatmapDiscussionPostsControllerTest.php
tests/Models/BeatmapDiscussionTest.php

Something like this? ┐(-｡ｰ;)┌
Can use input on icon and color and everything else.
Fixes #1739.

Special post type for mapper

---

resources/assets/coffee/_classes/nav.coffee

Need a bit more testing 💃 
Hopefully good enough to solve #1767.

Add slight delay for showing header menu

---

app/Console/Commands/KudosuRecalculateDiscussionsGrants.php
app/Models/BeatmapDiscussion.php
app/Models/BeatmapsetEvent.php
app/Transformers/BeatmapDiscussionTransformer.php
database/migrations/2017_11_22_081837_remove_kudosu_refresh_votes_from_beatmap_discussions.php
database/migrations/2017_11_22_114135_add_even_more_type_to_beatmapset_events.php
resources/assets/coffee/react/beatmap-discussions/post.coffee
resources/lang/en/beatmapset_events.php
resources/lang/en/users.php

Calculate current/target kudosu difference instead of relying on previous/current votes count.

Simplify kudosu calculation for discussion voting

---

resources/lang/en/beatmapset_events.php

Forgot about this one. Whoops.

Update event translation

---

database/migrations/2017_11_23_102444_add_index_to_kudosu_histories_kudosuable.php

Add index to kudosu histories table

---

app/Http/Controllers/BeatmapsetsController.php
app/Models/Beatmapset.php
app/Transformers/BeatmapsetTransformer.php
resources/assets/coffee/react/beatmapset-page/header.coffee
resources/assets/less/bem-index.less
resources/assets/less/bem/beatmapset-favourites.less
resources/assets/less/bem/beatmapset-header.less
resources/lang/en/beatmapsets.php

Uses a basic placeholder(?) design I made until @arflyte has time to fix/improve. Looks a little something like this:
Fixes #1692

Add display of people who favourited a beatmapset

---

app/Http/Controllers/Store/CheckoutController.php

because `$order` is not in scope.
i r smrt 🥇

Fix free checkouts not redirecting to invoice after complete.

---

resources/assets/coffee/react/beatmapset-page/main.coffee
resources/assets/coffee/react/profile-page/main.coffee
resources/views/beatmapsets/show.blade.php
resources/views/users/show.blade.php

Beatmapset page fix styling

---

resources/assets/coffee/react/beatmap-discussions/new-reply.coffee
resources/assets/less/bem/beatmap-discussion-post.less
resources/lang/en/beatmaps.php
resources/lang/en/common.php

fixes #1746
It looks odd to have 2 buttons both with the reply arrow icon, though...
Left the checkbox in, since it still has an effect when using enter to submit.

Add reply and resolve button to beatmapset discussion

---

database/migrations/2017_11_27_064736_fix_user_sig_encoding.php

Make user_sig column utf8mb4

---

README.md

Update documentation on creating user

---

app/Mail/DonationThanks.php
app/Mail/SupporterGift.php

Supporter tag donation mails should be sent as text/plain

---

.travis.yml
app/framework_helper_overrides.php
bin/phpunit
bootstrap/autoload.php

Because better.
Fixes laravel/framework#12065.

Saner escape

---

resources/assets/coffee/react/beatmapset-page/header.coffee

Looks like bug in laroute ಠ_ಠ
Fixes #1834.
aaronlord/laroute#78.

Escape parameters being passed to laroute

---

app/Http/Controllers/WikiController.php
app/Models/Wiki/Page.php

Try searching by title using elasticsearch if no exact match or redirect.
Fixes #1817.

Add wiki title search

---

app/Http/Controllers/FriendsController.php
app/Models/User.php
app/Transformers/UserTransformer.php
config/osu.php
resources/assets/coffee/react/_components/friend-button.coffee

 Increase max friends for supporters to 500

---

app/Models/BeatmapDiscussion.php
resources/assets/coffee/react/beatmap-discussions/new-discussion.coffee
resources/assets/less/bem/beatmap-discussion-post.less
tests/Controllers/BeatmapDiscussionsControllerTest.php
tests/Models/BeatmapDiscussionTest.php

And disables kudosu granting.
Fixes #1826.

Allow mapper to post suggestions/problems on his own map

---

resources/assets/coffee/react/beatmap-discussions/main.coffee

Put note in pending

---

app/Libraries/BBCodeForDB.php

Allow empty color tag

---

resources/assets/coffee/react/beatmap-discussions/post.coffee

Accidentally broken. Fixes #1861.

Fix check for allow kudosu button

---

app/Models/Wiki/Page.php
app/helpers.php

- doesn't create infinite amount of fields
- doesn't use redis
- seems working
- more codes
- more bugs
- need to hit all pages again
```shell
find wiki/ -name '*.md' | while read line; do
page="${line%/*}"
filename="${line##*/}"
locale="${filename%%.*}"
url="https://osu.ppy.sh/help/${page}?locale=${locale}"
echo "${url}"
curl -sI "${url}" > /dev/null
done
```
Oneliner
```shell
find wiki/ -name '*.md' | while read line; do page="${line%/*}"; filename="${line##*/}"; locale="${filename%%.*}"; url="https://osu.ppy.sh/help/${page}?locale=${locale}"; echo "${url}"; curl -sI "${url}" > /dev/null; done
```

Wiki index v2

---

app/Models/Wiki/Page.php

Escaping and join keywords not needed for match parameter

---

app/Models/User.php

Revert better search for now because too slow

---

resources/assets/less/bem/paginator.less
resources/assets/less/bem/search-result.less
resources/assets/less/variables.less
resources/views/home/_search_results.blade.php
resources/views/objects/_pagination.blade.php

With previous -15px margin, the layout is broken when there's no pagination ( ･ ヮ･)b

Fix search pagination layout

---

app/Http/Controllers/BeatmapDiscussionPostsController.php
app/Http/Controllers/BeatmapsetsController.php
app/Models/Beatmapset.php
app/Models/BeatmapsetEvent.php
database/migrations/2017_11_29_033957_add_nomination_reset_type_to_beatmapset_events.php
resources/assets/coffee/react/beatmap-discussions/main.coffee
resources/assets/coffee/react/beatmap-discussions/new-discussion.coffee
resources/assets/coffee/react/beatmap-discussions/nominations.coffee
resources/lang/en/beatmaps.php
resources/lang/en/beatmapset_events.php

Reset nominations when a BN/QAT posts a new problem on a beatmapset that already has nominations (but is not yet qualified)

Bubble popping

---

app/Models/Beatmapset.php

Fix bbcode escaping party when editing beatmapset description

---

resources/views/forum/topics/_moderate_move.blade.php
resources/views/home/_search_advanced_forum_post.blade.php

After the sane laravel escape patch is applied.
Fixes #1882.

Less escaping

---

resources/assets/coffee/react/beatmap-discussions/event.coffee
resources/assets/less/bem/beatmapset-event.less

Add missing color for some beatmapset events.
And kebabs 🥙

Event colors

---

resources/assets/coffee/react/beatmap-discussions/nominations.coffee

Hide hype button for beatmapset owner

---

resources/assets/coffee/react/beatmap-discussions/main.coffee

Probably should look into using promise thingy already.
Fixes #1877.

Set correct filter when jumping to discussion

---

app/Models/Forum/Authorize.php
app/Models/Forum/Topic.php

Hides topics in forums user don't have access to.
Fixes #1883.

ACL for Topic Watch

---

resources/assets/coffee/react/beatmap-discussions/post.coffee
resources/assets/less/bem/beatmap-discussion-post.less

Discussion editor fixes

---

app/Libraries/BBCodeFromDB.php
tests/Libraries/bbcode_examples/autolink.html

Ignore comments when cleaning up spaces.
Fixes #1699.

Fix multiple links parsing

---

app/helpers.php
resources/views/home/landing.blade.php
resources/views/layout/_popup_menu.blade.php
resources/views/layout/header_mobile/nav.blade.php
resources/views/objects/logo-menu.blade.php

Fixes #1706.
(exception as in it's the only one which links to different area than its first menu item)

Add exception for home main link

---

app/Http/Controllers/AccountController.php

Fixes #1676? While keeping in line with #142? ┐(･_･)┌

Allow silenced users to update some settings

---

app/Models/BeatmapDiscussionPost.php
resources/assets/coffee/react/beatmap-discussions/new-discussion.coffee
resources/assets/coffee/react/beatmap-discussions/new-reply.coffee
resources/assets/coffee/react/beatmap-discussions/post.coffee

And limit to 500 characters.
Probably should add memo on shift-enter for newline.

Newline in discussion post
