app/Libraries/ProfileCover.php
The best method ( ﾟ◡ﾟ)
`jhead` is required (otherwise nothing will happen).
Fixes #3.
=> Autorotate and strip exif.

.travis.yml
I contacted travis-ci, and they're fixing the pull request build issues (see https://github.com/travis-ci/travis-scheduler/commit/85688758392f362c4efc5f73b1fc59affda85b97).
This just adds 5.6 and 7.0 to the build matrix, which we should have parity with anyway.
=> Build and run on PHP 5.6 and 7, and try to fix travis PR issues

resources/assets/coffee/forum.coffee, resources/assets/coffee/forum/post-box.coffee, resources/assets/coffee/forum/topic-ajax.coffee, resources/assets/coffee/store.coffee
I missed the problem with string sometimes being parsed as something not in base 10 :(
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt
Shouldn't* be a problem but a good practice anyway.
*until it is.
=> parseInt must be called with radix parameter.

.travis.yml
Also, faster build times are always better.
=> Add caching to NPM and Composer because why the hell not

resources/assets/less/store/base.less
100px was too narrow, causing misalignment.
=> Extend price column in store cart view

.travis.yml
Should cut another chunk out of global build times. I forgot this the first time.
=> Cache bower_components for faster build times

app/Http/Controllers/Forum/PostsController.php, resources/assets/coffee/forum.coffee, resources/assets/coffee/osu_common.coffee, resources/assets/coffee/react/profile-page/kudosu.coffee, resources/views/forum/topics/show.blade.php, resources/views/layout/_global_variables.blade.php, resources/views/layout/metadata.blade.php
First time the `/forum/p/:id` actually used (I think)... and turns out there's special care needed for it \o/
Or so it was. Made it a plain redirect.
=> Fix forum post link

resources/assets/less/forum/base.less
The custom font we have doesn't really work well for long prose sections.
=> Use sans-serif (OS/browser default) for forum post text.

resources/views/layout/metadata.blade.php
Just a tiny optimization that Chrome's audits suggested.
>The following external CSS files were included after an external JavaScript file in the document head. To ensure CSS files are downloaded in parallel, always include external CSS before external JavaScript.
=> Include CSS BEFORE including JS

resources/views/forum/topics/_posts.blade.php
I thought the render was done directly to the post view, not posts =[
=> Always expand post if jumpTo is not defined

resources/assets/coffee/forum.coffee
- First post link always goes to the top
- Topmost scroll offset limit is 60px instead of 0 to avoid it being covered by fixed header
=> Improved post targeting

bootstrap.sh, vagrant/Dockerfile, vagrant/Vagrantfile
Useful for development on Linux.
I'm not sure how the default provider is determined. The docs say that VirtualBox is always the default, but on my work machine, Vagrant automatically chooses Docker even if I don't explicitly pass `--provider docker` to `vagrant up`.
It could be that Vagrant detects that VirtualBox isn't installed and so tries the next provider?
Will need to test for compatibility before merge.
=> Add support for Docker as a provider for Vagrant.

app/Http/Controllers/Forum/TopicsController.php, resources/views/forum/topics/show.blade.php
Previous fix didn't fix case for invalid `end` parameter.
=> Ignore invalid jumpTo instead of trying fixing it

build.sh
Once you have the site running, the `storage` folder is filled with files owned by `www-data`. Provisioning is done by the `vagrant` user, which doesn't have permission to `chmod` those files. If you run `vagrant reload` to update the container, the `chmod` step in `build.sh` can cause provisioning to fail.
=> Change provisioning to not fail on chmod error for cache directories.

app/Models/Store/Product.php
For the latest product addition, each sub-product has its own images_json definition. This allows those definitions to override the master_product's, when present.
=> Prioritise local images_json over masterProducts'.

resources/views/store/product.blade.php
I'm using custom_class in the fulfillment process to determind certain types of items. In the case of the new tournament banners, they don't (yet?) have a custom blade, but they do need a custom class. This allows that to be possible without error to face.
Needs to be merged ASAP.
=> Allow a custom_class to be defined but not exist.

app/Http/Controllers/BeatmapController.php, app/Models/BeatmapSet.php, app/Models/Score/Combined.php, app/Models/Score/Fruit.php, app/Models/Score/Mania.php, app/Models/Score/Model.php, app/Models/Score/Osu.php, app/Models/Score/Taiko.php, app/Transformers/BeatmapSetTransformer.php, app/Transformers/GenreTransformer.php, app/Transformers/LanguageTransformer.php, resources/assets/coffee/react/beatmaps/search-filter.coffee, resources/assets/coffee/react/beatmaps/search-panel.coffee, resources/assets/coffee/react/beatmaps/search-sort.coffee
Now using DB + ElasticSearch to enable searching by rank achieved (supporter required)
Things still remaining:
- Search by rank status (for favourites, my maps, etc)
- Re-fix playmode/difficulty display
- Persist/restore state via URL
- Thumbnails
- \clean and optimize up all the codes/
=> Add ability to search by rank achieved

app/Libraries/BBCodeForDB.php, tests/Libraries/bbcode_examples/autolink.base.txt, tests/Libraries/bbcode_examples/autolink.db.txt, tests/Libraries/bbcode_examples/autolink.html
- missing scheme for www-type link
- wrong end tag for email
- there's a bug that newlines don't turn into `<br />` if written like the test. Unfortunately fixing it is a bit non-trivial
Fixes #271
=> Fix link parser

database/migrations/2016_01_12_074035_unique_user_customization_user_id.php
Raw SQL because there's no support for changing column type to `mediumint` :D
Oh and the table needs fixing as well since there seems to be some users having multiple customisations.
```sql
SELECT COUNT(1), user_id FROM user_profile_customizations GROUP BY user_id HAVING COUNT(1) > 1;
```
=> Add unique and foreign key constraints to profile customization table

resources/views/store/checkout.blade.php
because username changes aren't gonna get delayed.
=> Only show the message for physical orders.

resources/views/store/invoice.blade.php
We quite often use the tracking code for notes before an order has shipped. The user doesn't need to see these notes, so let's not let them see it.
=> Hide tracking number until order has actually shipped.

resources/assets/less/app.less, resources/assets/less/bem/kudosu-entries.less, resources/assets/less/bem/profile-extra-entries.less, resources/assets/less/bem/profile-extra-tabs.less, resources/assets/less/bem/store-cart-footer.less, resources/assets/less/bootstrap-overrides.less, resources/assets/less/bootstrap-variables.less, resources/assets/less/colours.less, resources/assets/less/forum/base.less, resources/assets/less/forum/colours.less, resources/assets/less/functions.less, resources/assets/less/sections.less, resources/assets/less/store/base.less, resources/assets/less/tournament.less, resources/assets/less/users.less, resources/assets/less/variables.less
I also noticed that attempting to mix in non-US English when the rest of libraries use US English results in useless confusion (variables, method names, etc).
Thereby I propose using US English for everything except as display text (e.g. values in `resources/lang/en`) ┐(･_･)┌
=> Red color take two

app/Http/Controllers/StoreController.php, app/Models/Store/Order.php, app/Models/Store/Product.php, database/migrations/2016_01_26_194005_disable_products.php
We need to be able to have hidden store items for internal use (tournament prizes for example) to generate invoices and tracking information. We also want to be able to hide items which are no longer relevant, such as the 2015 OWC banners.
This adds the basic ability to disable store products.
=> Add enabled state to store items.

resources/assets/coffee/react/profile-page/user-page.coffee
=> Don't show "supporter required" message when user is supporter.

app/Models/RankHistory.php, resources/assets/coffee/react/profile-page/historical.coffee
First day is removed for now so the furthest back is 89 days (not that anyone can tell yet because there's no tooltip). The heuristic in old site is... _nice try_.
Not fixing the rank scale because I can't think of better solution yet.
Here's another case of log vs linear:
current idea is to check if difference between max and min rank is over an (or two) order of magnitude (coming soon™).
=> Chart fixes

app/Http/Controllers/CommunityController.php
Fixes situation where certain streams weren't possible to be highlighted.
=> Cast twitch's ID to float, since int was overflowing.

app/Transformers/UserTransformer.php
Let's not return infinite results.
=> Limit number of top played maps shown in user profile to 100.

resources/assets/coffee/_classes/forum.coffee
And boot first to avoid triggering anything when scrolling to target post.
=> Scroll page last because other actions may change page height

.travis.yml
Because PHP 7 is looking pretty stable and more efficient for our particular environment. Also it runs composer/artisan much faster OOTB.
=> Stop targeting HHVM for now.

bootstrap.sh
Installing without the `mbstring` and `dom` (included in `php7.0-xml`) extensions results in errors when setting up using Vagrant. The `zip` extension was added to make Composer installs quicker.
=> Add the missing extensions that certain Composer packages want

app/Console/Commands/StoreCheckOrderTrackingStatus.php, app/Models/Store/Order.php, resources/views/store/invoice.blade.php
Now that we are sending packages via airmail and other methods, the tracking code field can regularly contain notes for us and for the user which aren't valid tracking numbers.
This change matches tracking codes using the JP Post specification for them via regex.
=> Use regular expressions to pull out tracking codes specifically.

build.sh
This was running too early and restarting the workers with the old code. Added a seperate step to the auto-deployment system to do this instead.
=> Remove queue:restart from build script

resources/assets/coffee/react/profile-page/recent-achievements.coffee
Apparently the event name was left unchanged at some point.
=> Fixed user's 'more achievements' link not working

resources/assets/coffee/_classes/tooltip-default.coffee
If qtip is already activated for an element but title attribute is readded
later and thus triggers the event, replace the tooltip content instead of
immediate stop.
Fixes #491.
=> Fix interaction between react and qtip2

database/migrations/2016_02_29_081309_create_beatmap_discussion_posts.php, database/migrations/2016_04_11_071007_use_user_id_for_resolving_issue.php, database/migrations/2016_04_12_111756_add_last_editor_id_to_beatmap_discussion_posts.php
The migrations seem to be failing on rollback because of some missing drop foreign indexes instructions.
=> Fix failing migrations

resources/assets/coffee/react/beatmapset-page/contents-beatmap-icon.coffee, resources/assets/coffee/react/beatmapset-page/contents-tab.coffee
Right now they point at `/s/<set-id>#undefined`.
=> Fix broken links on beatmap icons and mode tabs

resources/views/forum/topics/_post.blade.php
`/forum/p/{post_id}` which will redirect to same previous url ¯\\\_(ツ)_/¯
Can use a visible hint of which post is it in the thread though.
=> Generate simpler post url

resources/assets/coffee/react/beatmapset-page/header.coffee, resources/assets/coffee/react/beatmapset-page/main.coffee, resources/assets/less/bem/beatmapset-header.less
Fixes audio-preview overlay on the beatmapsets header making the title/artist links unclickable
Also tweaks the visual appearance a bit to always be visible and rewinds the preview when stopped
=> Beatmapset audio-preview overlay fixes and tweaks

resources/assets/coffee/react/_components/beatmapset-panel.coffee, resources/assets/less/bem/beatmapset-header.less, resources/assets/less/bem/beatmapset-panel.less
Should (hopefully) improve performance on slower browsers when hovering the panels
=> Display tweaks for Beatmapsets

resources/assets/coffee/_classes/tooltip-default.coffee
Broken when moving title content into its own element.
=> Don't show title if it's blank

app/helpers.php, resources/assets/coffee/_classes/forum-cover.coffee, resources/assets/coffee/_classes/osu-layzr.coffee, resources/assets/coffee/_classes/timeago.coffee, resources/assets/coffee/_classes/tooltip-default.coffee, resources/assets/coffee/main.coffee, resources/assets/coffee/osu_common.coffee
Just realized yesterday that version 5 has one important change which obsoletes some of previously used techniques.
Namely it saves document using `cloneNode` so elements data and events are cleared out upon navigation. Storing element state using `el.someData = value` doesn't quite work anymore.
Reference: https://github.com/turbolinks/turbolinks/issues/30
=> Turbolinks fixes

resources/assets/coffee/_classes/forum-cover.coffee
Previously checked class exists even though the upload button doesn't.
=> Fix wrong check on overlay setter

resources/assets/coffee/react/mp-history/content.coffee
fixes team scores displaying as 0 after updating from a match in progress
=> Don't cache team scores before match end

app/Http/Controllers/ContestsController.php, resources/lang/en/contest.php, resources/views/contests/enter.blade.php
Prevents entry page from exploding when user is not logged in and adds a message explaining that silenced/restricted users can't enter contest (instead of just failing on upload)
=> Fixes for contest entry system

resources/lang/pt-br/user_verification.php
2* attempt to pull, now with a single commit
this file was originally translated according to /lang/em/user_verification.php root file
all translations and dependencies are fully included in this file since the last change, commit: 128fbf8
=> added user_verification translated to pt-br

resources/lang/es/beatmaps.php
there was a ':user' in this translation.
=> wrong text in translation

package.json, yarn.lock
It's already dependency of another package(s) but since it's explicitly used in gulpfile, it should be listed as such.
=> Add missing dependency

resources/assets/less/bem/contest.less, resources/views/contests/voting.blade.php
Makes links in the contest description box less blue.
Also collapses all sections within nested contests by default. Contests having lots of entries resulted in the other sections being pushed off-screen. This led to confusing UX as users may not see the other headings and realise they're expandable/collapsable...
=> Contest tweaks

resources/assets/coffee/_classes/beatmap-discussion-helper.coffee, resources/assets/coffee/react/_components/beatmap-basic-stats.coffee, resources/assets/coffee/react/beatmap-discussions/new-discussion.coffee
Beatmapset durations:
- 0:30 (or should it be 00:30?)
- 1:30
- 10:05
- 2:05:05 (or 02:...?)
- 10:05:05 (god why)
Modding timestamps:
- 00:00.000
- 01:20.300
- 70:10.000 (should it show 1:10:10.000 (or 01:...) instead?)
- 1000:00.000
Note that writing timestamp in hours format (01:01:01:001) still isn't supported.
=> Hours duration

resources/assets/coffee/_classes/user-login.coffee, resources/assets/coffee/react/contest/voting/voter.coffee
There's a bug which prevented `LoadingOverlay.hide` from being triggered after user login.
=> Fix user login

app/Http/Controllers/UsersController.php, app/Libraries/OsuAuthorize.php
Different way to fix #216.
As global scope is available, it's actually possible to properly hide restricted user as well. Except I haven't figured out how to tell login system to remove the scope when looking for the user.
...closes #341?
=> Use priv_check to authorize access to profile page

app/Http/Controllers/BeatmapDiscussionPostsController.php, app/Libraries/OsuAuthorize.php, resources/assets/coffee/react/beatmap-discussions/new-reply.coffee
Changing status (to resolved/unresolved) requires correct privilege (thread owner, beatmapset owner, or admin).
Currently it'll always reopen (unresolve) thread whenever anyone replies to it which doesn't sound right.
=> Change resolve status behavior

app/Models/Chat/PrivateMessage.php, app/Models/User.php
`->orWhere('column', '~')` causes error.
=> orWhere with two arguments is a bit broken

app/Libraries/LocaleMeta.php, resources/assets/less/bem/wiki-content.less
I'm not sure if Norwegian should be just "Norsk" or "Norsk bokmål".
=> Wiki locales and margins

app/Models/User.php
There are currently 10-ish people who have their email containing uppercase letter in the database.
=> Lowercase email for lookup

app/Traits/UserAvatar.php
Apparently laravel (or whatever stack it uses) magically transforms warnings into exceptions.
Except they forgot to do it in `artisan tinker`.
=> Handle 404s when purging avatar

app/Http/Middleware/SetLocale.php
Should've been removed when moved to using controller instead of middleware.
=> Don't override locale that's set in controller

resources/assets/less/bootstrap-variables.less
Windows 10 Chrome (and possibly others?) sometimes doesn't fallback correctly to sans serif font for CJK text.
=> Fix CJK font fallback

resources/views/layout/metadata.blade.php
In mobile chrome, able to set the android toolbar color : [document link](https://developers.google.com/web/updates/2014/11/Support-for-theme-color-in-Chrome-39-for-Android)
So, I'm Added this meta tag with osu symbol color : `#ff66a`
<meta name="theme-color" content="#ff66aa">
=> Add "theme-color" meta tag

resources/assets/coffee/_classes/profile-page-hash.coffee
Splitting empty string results in single element array of empty string
=> Fix starting mode when loading user profile page

bin/mysql_debian_install
Latest deb file contains latest key already. And the gpg server fails at random.
...except the new one also fetches key. Oh well, at least it's using a different server which hopefully is more stable than the other one.
=> No more key from gpg server

app/Models/Event.php
Looks like there are some changes which broke current parser.
=> Report unrecognized events to sentry

app/Libraries/BBCodeFromDB.php, app/helpers.php
And `null[0]` is apparently a valid php.
=> fast_imagesize doesn't return false anymore.

app/Models/Beatmapset.php
Currently they're stored as GMT+8, thanks to legacy stuff
=> 'Fix' timezone for Beatmapset datetime fields

resources/assets/coffee/react/profile-page/header-extra.coffee
Tiny fix for ranking graphs that don't have all data points set
See https://osu.ppy.sh/u/3666350 vs https://new.ppy.sh/u/3666350; the latter graph shows incorrectly shifted dates. This change fills the gap with a straight line
=> Fix user ranking graphs with missing data

app/Models/Model.php
And use plain scope. Not sure why I used macro before.
Fixes #1112.
=> Don't generate invalid query when ids is empty

app/Http/Controllers/ArtistsController.php, resources/assets/less/bem/artist.less, resources/lang/en/artist.php, resources/views/artists/index.blade.php, resources/views/artists/show.blade.php
Hides non-visible artists from being viewed (except to admins). Also adds the display of non-visible artists on the index for admins.
=> Prevent viewing of unreleased artists

resources/assets/less/bem/contest-list-item.less, resources/assets/less/bem/contest-list-legend.less, resources/assets/less/bem/contest-list.less, resources/assets/less/bem/osu-page-header-v2.less, resources/assets/less/variables.less
Styling changes to fix #797.
- applies when `@mobile`
- ~~reset text-overflow, overflow, and white-space rules for contest entry name~~
- increase entry item height to allow more text
- (increase image height to match above)
- decrease legend font-size
- decrease contest list padding to give more space for text, image, border, etc.
- reset heading top margin to 0
- use new defined font-size for mobile header v2
- issue: 3 lines max for both contest entry name and headers (or they will overflow when `@mobile`)
- `justify-content: center;` for heading v2
_Left: this branch; Right: current_
=> Fix mobile view for contest entry names and headers

resources/assets/less/bem/wiki-content.less
_(Continued from #1109.)_ Increase `margin-bottom` for `<p/>` tags inside `.wiki-content` to `1em` (was `10px`).
=> osu!wiki - increase margin-bottom for paragraph

resources/assets/coffee/_classes/turbolinks-disable.coffee
Returning false isn't enough to cancel the event.
=> Properly cancel turbolinks event

app/Console/Commands/BuildsUpdatePropagationHistory.php
Will probably be better for eventual grouping.
=> Store exactly the same time for all build histories

resources/lang/pt-br/ranking.php
Thought 'header' and the contents on 'type' were two different words but they're actually a sentence. Turns out it looks really weird in portuguese.
=> ranking.php bug-fix in portuguese

resources/assets/coffee/_classes/store-supporter-tag.coffee
Apparently, Safari was the only browser that cared about the missing `]`
=> Fix missing ']' in store-supporter-tag querySelector.

resources/assets/less/bem/store-slider.less, resources/assets/less/jquery-ui/slider.less, resources/assets/less/variables.less, resources/views/store/products/supporter-tag.blade.php
Makes the grabbable area of the callout slightly bigger than the callout visual itself.
Seems like we can't make the clickable area of the slider any larger, though, without making the slider itself larger. 🤔 
Also pointer cursors for everyone.
=> Increase the grabbable area of the supporter tag slider

resources/assets/coffee/react/_components/play-detail.coffee, resources/assets/less/bem/detail-row.less, resources/assets/less/variables.less
resolves #1146 
There's already logic to show the accuracy if there's no `score.weight` or `score.pp`; this just makes it show all the time.
It might look kind of unbalanced, though?
=> Always show accuracy in play-details

resources/assets/less/bem/mod.less
Sets `min-height` so Safari doesn't consider it a 0 height block.
=> fixes #1256

app/Transformers/UserTransformer.php, app/helpers.php, resources/assets/coffee/react/profile-page/header-extra.coffee
Also adds a tooltip for users that have been here "since the beginning", showing the month+year they joined on hover.
Fixes #1254
=> Remove user registration date formatting from UserTransformer

app/helpers.php
Searching with reserved keywords in terms (e.g, 'AND', 'OR', etc) will trigger an error from Elasticsearch. Converting terms to lowercase fixes this - search results shouldn't be affected because they're indexed case-insensitively.
=> Fix boolean operators breaking elasticsearch

resources/views/wiki/show.blade.php
=> wiki: Always show action buttons

resources/views/objects/_usercard.blade.php
Currently there is _at least_ one [user](https://osu.ppy.sh/users/7705650) which flag acronym country supposedly is an empty string. This causes an exception in the friends page because in _usercard.blade.php was not handled the case of user->country being null.
=> Fix friends page if there is a friend with empty flag

resources/assets/coffee/react/_components/beatmapset-panel.coffee, resources/assets/less/bem/beatmapset-panel.less
If there are more than 10 diffs in the beatmap listing, condense them showing for each mode the icon of the hardest diff and the number of diffs of that mode.
=> Condense difficulty icons when needed in the listing page

.travis.yml
Travis is rolling out `Trusty` as the default environment: https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming
Except the base image comes with a much older version of yarn which breaks our CI build
https://github.com/travis-ci/travis-ci/issues/7951
Alternatively, we could install yarn on every build 🤷‍♂️
=> Set CI to install yarn 0.27.5

app/Models/User.php, app/helpers.php
Thankfully only two characters need to be escaped.
=> Properly escape string for use with like search

app/Models/BeatmapDiscussionPost.php, resources/assets/coffee/react/beatmap-discussions/post.coffee
Only show either deleted or edited but not both. Currently, deleting updates updated_at which causes edited status to show up as well.
=> Fix beatmap discussion status

resources/assets/coffee/_classes/form-confirmation.coffee, resources/assets/coffee/_classes/landing-hero.coffee, resources/assets/coffee/_classes/landing-user-stats.coffee, resources/assets/coffee/_classes/store-supporter-tag.coffee, resources/assets/coffee/_classes/user-verification.coffee, resources/assets/coffee/react/mp-history/content.coffee, resources/assets/coffee/react/mp-history/game-header.coffee, resources/assets/coffee/react/mp-history/game.coffee, resources/assets/coffee/react/mp-history/header.coffee, resources/assets/coffee/react/mp-history/score.coffee
This was causing some issues with locales that aren't fully translated. Some examples currently are multiplayer matches in Polish, and the supporter store page in Italian
=> Replace direct calls to Lang.get with osu.trans

app/Http/Controllers/BeatmapDiscussionPostsController.php, app/Transformers/BeatmapDiscussionPostTransformer.php, resources/assets/coffee/react/beatmap-discussions/post.coffee
Two little things:
- Fixes 'Last edited by <original poster>' always being shown after a deleted post is restored (even if it hadn't been edited)
- Hide the edit post interface when hitting 'save' with no changes (instead of just doing nothing)
=> Misc discussion fixes

app/Transformers/EventTransformer.php
Should be `event_id` (or just `getKey()`). I thought I reverted this erroneous change but turned out I didn't.
=> Correct event id

app/Http/Controllers/FriendsController.php, app/Jobs/RegenerateBeatmapsetCover.php, app/Jobs/UpdateUserFollowerCountCache.php, app/Models/User.php, app/Transformers/BeatmapCompactTransformer.php, app/Transformers/BeatmapPlaycountTransformer.php, app/Transformers/BeatmapsetCompactTransformer.php, app/Transformers/ScoreTransformer.php, app/Transformers/UserTransformer.php
First phase reduces the amount of (unused) beatmapset json being sent initially to speed up downloading and parsing. (should reduce page size by ~50-60%)
In addition, caching has been added for user follower counts to ease the load from more popular players.
Also, the max displayed beatmaps in each section has been temporarily reduced to 50 for the time being.
More optimisations to come...
=> User profile optimisation (stage 1)

app/Http/Controllers/Forum/TopicsController.php
Apparently I missed the mention of the helper. And then they removed the mention of `Event::fire` at all in 5.3 and later.
=> Simpler event dispatch

app/Http/Controllers/UsersController.php
=> Fix profiles showing zeroed stats when defaulting to user's default playmode

app/Libraries/OsuAuthorize.php
Should be between an hour ago and now, not before an hour ago.
Fixes #1485.
=> Wrong condition for vote rate limit

app/Http/Controllers/UsersController.php
There's check in `#show` but nowhere else.
=> Return 404 if user not found or locked

database/migrations/2017_09_07_084729_better_forum_posts_index.php
It confuses mysql query planner when ordering by post_id.
=> Remove index

app/Exceptions/ValidationException.php, app/Models/Store/Order.php, app/Models/Store/OrderItem.php, resources/lang/en/model_validation.php
Why is model validation on save not a standard thing?  ಠ_ಠ
This also always forces `OrderItem` to always have a `cost` value when adding or updating the cart because right now, it doesn't.
=> Validate order item on saving

app/Transformers/BeatmapsetCompactTransformer.php
Required for the beatmap panel thingy it seems. Fixes #1564.
@nekodex may want to check it.
=> Beatmap panel attributes

app/Http/Controllers/Admin/ContestsController.php, app/helpers.php
Would sanitize `file..png` into `filepng`, which would then be excluded by the `*.*` glob when creating the zip of entries...
=> Fix sanitizing of double '.' in filenames

docker-compose.yml
Previously it would fail on creating the osuweb user, seems to be broken in the mysql container.
=> Fix docker breaking on initial load

resources/assets/coffee/react/beatmap-discussions/nominations.coffee
Javascript can't break out twice (`switch` and `for`). Fixes #1601.
=> Fix nominator finder loop

app/Models/BeatmapDiscussionPost.php, resources/assets/coffee/react/beatmap-discussions/new-discussion.coffee, resources/assets/coffee/react/beatmap-discussions/new-reply.coffee, resources/assets/coffee/react/beatmap-discussions/post.coffee
Newline never happens on output and this ensures it's filtered on input as well. Fixes #1615.
=> Disable newline in beatmap discussion

app/Libraries/OrderCheckout.php, app/Libraries/Payments/XsollaPaymentProcessor.php, app/Models/Store/Order.php
If nothing in an order required shipping, the order should immediately be marked as `delivered` instead of just sitting at `paid` once the payment is confirmed.
This make the invoice page show the appropriate text.
=> Orders with no shippable items should be delivered immediately

app/Models/User.php, app/Providers/AppServiceProvider.php
Inactive user renaming can potentially set off too many errors.
=> Add option to skip validation when renaming inactive users.

app/Models/Model.php
The generic message is not so useful when the user validation keeps being set off on users trying to change their username.
=> Include the validation error message when throwing ModelNotSavedException

app/Libraries/Fulfillments/UsernameChangeFulfillment.php
Everything is being set to `support` now. This doesn't affect the cost of changes.
=> Username change history should be paid type if cost > 0.

app/Models/User.php
Username changes are failing because some users have existing field
values which no longer pass the validation.
=> Skip field validations if field hasn't changed.

app/Models/Wiki/Page.php
So TF, many IDF.
Fixes #1644. Maybe.
Ignore TF/IDF for locale matches. Otherwise incorrect result is generated from slight imbalance in document sharding.
References:
- https://www.elastic.co/guide/en/elasticsearch/guide/master/ignoring-tfidf.html
- https://www.elastic.co/guide/en/elasticsearch/guide/master/relevance-is-broken.html
=> Search adjustments

resources/assets/coffee/store-username-change.coffee
Resolves the issue where the validation result did not match the username entered.
=> Use correct value for username change store item validity response

resources/assets/app.js, resources/assets/coffee/jquery-prefilter.coffee
Preferable to 18 pages of https://jquery.com/upgrade-guide/3.0/ and mystery breakage of existing things under jQuery 3.
This would be more of an issue if we actually made cross-domain calls through jQuery 🤷‍♂️ 🤷‍♀️
=> Add cross-domain script jquery prefilter.

app/Http/Controllers/Payments/PaypalController.php
fixes #1682 always returning the unknown error message
=> Return correct message when Paypal checkout fails

.env.example, app/Events/Fulfillments/FulfillmentValidationFailed.php, app/Events/Fulfillments/ValidationFailedEvent.php, app/Libraries/Fulfillments/SupporterTagFulfillment.php, app/Notifications/Store/ErrorMessage.php, app/Notifications/Store/Message.php, app/Notifications/Store/OrderMessage.php, app/Notifications/Store/StoreMessage.php, app/Notifications/Store/ValidationMessage.php, app/Traits/StoreNotifiable.php, config/store.php
Makes store notification serializable.
Try not to dump entire nested contents of `Order` object into queue.
Set a timeout when sending to Slack.
Also fix a wrong `addError` method call. 
The queue worker should be called with something like `--queue=store-notifications --delay=60 --tries=10` to prevent it from spamming retries forever.
=> Make Store notifications actually queueable.

app/Http/Controllers/BeatmapsetsController.php, app/Models/Beatmapset.php, resources/assets/coffee/react/beatmaps/main.coffee, resources/assets/coffee/react/beatmaps/search-sort.coffee
Add sort by updated option (and remove unused options).
Not smart enough to hide ranked/ranking/plays sort option (on non-ranked maps) and updated sort option (on ranked maps) at the moment.
That will require some fancy refactors.
=> Beatmapset search update

resources/assets/coffee/react/beatmaps/main.coffee
=> Beatmap search results for 'Qualified' should be sorted by ranked time not last updated time by default

app/Models/User.php
closes #1605 
fixes 404s when looking up numeric usernames (ex. "630" - [old site](https://osu.ppy.sh/u/630), [new site](https://osu.ppy.sh/users/630))
not sure if this is the best way to go about it
=> Fix user lookups for numeric usernames

app/Models/Beatmapset.php
Didn't realize the cutoff date is different for each maps :D 
Short of constructing the queue to figure it out (+7 days, check queue size and put on the first available day for all beatmapsets in queue), everything else seems like approximation. So might as well use the simplest one.
Fixes #1782. Kind of.
=> Fix ranking eta

resources/assets/coffee/react/beatmap-discussions/new-discussion.coffee
For posts made/updated in last 24 hours (any longer should still be checked in case forgotten).
Fixes #1774.
=> Ignore posts made by same user for duplicate check

app/Models/User.php
Allow exact matches to come up first. And then sort by id.
Fixes #1788 but partially reverts #1269. Probably should be checked by @nekodex.
=> Revert back to giving shorter length priority

app/Console/Commands/FixUsernameChangeTopicCache.php, app/Console/Kernel.php
turns out that getting the ids and then using `array_chunk` and selecting just the chunks is much faster than using Eloquent's `::chunk`
=> Add command to refresh topic cache to fix username change updating wrong field

app/Models/User.php
Because that would be silly.
Reverting to a username that was recently taken will be blocked by the unique constraint on `username_clean`
=> Shouldn't run username validation when reverting usernames.

app/Models/Wiki/Page.php
=> Remove unrelated search params

app/Models/Wiki/Page.php, app/helpers.php, resources/assets/less/bem-index.less, resources/assets/less/bem/wiki-notice.less, resources/lang/en/wiki.php, resources/views/wiki/show.blade.php
Just like news, put `outdated: true` in page metadata area
```
---
outdated: true
---
<content goes here>
```
Fixes #1827.
=> Add way to put outdated notice box in wiki page

app/Libraries/OsuAuthorize.php, resources/assets/coffee/react/beatmapset-page/info.coffee
fixes #1852
fixes #1855
Client-side just checks for existance of bbcode to decide whether to show the edit button to avoid adding more properties to the transformer, since the description bbcode is only sent if the user has edit permissions.
=> Allow moderators to edit beatmap info description

app/Models/BeatmapDiscussion.php, app/Models/BeatmapDiscussionPost.php, resources/assets/coffee/react/beatmap-discussions/discussion.coffee, resources/assets/coffee/react/beatmap-discussions/system-post.coffee, resources/assets/less/bem/beatmap-discussion-system-post.less
~Side effect includes having a discussion to look like repeatedly reopened without any closing posts in between~. Now with fancy logic which hides resolved event indicator when no resolved state change.
Fixes #1835.
[//]: # (https://s.myconan.net/2017-11/firefox_2017-11-29_16-07-41.png)
=> Link post with its resolve state change

resources/views/layout/metadata.blade.php
This doesn't yet clean up _all_ the noise, but it's a start.
Parts taken from https://docs.sentry.io/clients/javascript/tips/
=> Prevent some errors from being sent to Sentry

resources/assets/coffee/_classes/changelog-chart.coffee
At mouse cursor `y=0`, first build/stream will always match because it must end at least at `y=0`. So make sure there's actual data before deciding that it's the correct build.
=> Skip blank data

app/Models/UserRelation.php
Ba dum tss.
Also it's currently impossible to be false anyway because `explode(' ', $something)` used for `config('osu.user.super_friendly')` will always return an array with at least 1 element, even on empty string.
```
>>> explode(' ', '')
=> [
"",
]
```
```
>>> count(true)
=> 1
```
=> No count boolean

app/Transformers/BeatmapsetTransformer.php, config/osu.php, resources/assets/coffee/react/beatmapset-page/header.coffee
=> Add links to legacy forum threads on beatmapset pages that don't use moddingv2

app/Models/User.php
sort of related to #1944
tried adding an index to `dateadded` for sorting but mysql didn't seem to want to use it
=> Show favourite beatmaps on user profile in reverse favourited order

app/Models/Beatmapset.php, app/helpers.php
otherwise laravel will fail to select with joins on tables with the same
column names.
fixes search broken by #1999
=> support qualified column name with model_pluck.

resources/assets/coffee/react/beatmap-discussions/new-reply.coffee, resources/assets/less/bem/beatmap-discussion-post.less
with cancel button or `esc` key
=> Allow beatmap discussion reply editor to be closed

resources/assets/coffee/react/beatmap-discussions/new-discussion.coffee
Turns out it doesn't quite work in react.
=> Don't use ujs for confirmation

app/Http/Controllers/Forum/TopicsController.php
fixes https://github.com/ppy/osu-web/issues/1873#issuecomment-348544535
Apparently, mysql is fetching all the matching rows before applying min
=> Get first post id of topic faster

app/Http/Controllers/UsersController.php
Pending -> last updated time descending
Ranked -> ranked date descending
Favourites -> favourite time descending (already implemented)
=> Apply better sorting defaults to beatmap sections in profile

app/Models/Beatmapset.php
fixes #1875
Ended up not renaming the associated functions as that ended up cascading a lot of changes through, and changes the output of the transformers as well. Probably should do a refactor of the scope and transformer include methods to use a list of states to filter for, instead.
=> Include qualified beatmapsets on user profile page.

resources/assets/coffee/_classes/menu.coffee, resources/assets/coffee/_classes/nav.coffee, resources/assets/less/bem/nav-popup.less, resources/assets/less/variables.less
- Reduce the delay for showing and dismissing the navigation menu.
- hacky auto resize menu if the content for that sub menu exceeds a certain height (hi language menu).
fixes #2110 and eliminates need to keep updating the menu size when a new language gets added.
=> Reduce menu delay and auto resize menu

app/Models/BeatmapDiscussion.php, app/Transformers/BeatmapDiscussionTransformer.php
- replace empty key with something more useful
- fix replying on timeline which map has been updated with shorter duration resulting in existing timestamp to exceed the new duration
=> Discussion timeline fix

app/Transformers/BeatmapsetTransformer.php
Difficulty data is not populated for unranked beatmapsets, so the page explodes when trying to show the star difficulty.
Probably not the correct way to fix this, but it stops the page from exploding for now.
Fixes #2184
=> Hotfix unranked beatmapset pages breaking

app/Models/Elasticsearch/BeatmapsetTrait.php
Should fix the sorting by certain fields in ascending order when searching for Pending beatmapsets, after a clean index is created.
The issue was that beatmapsets that weren't set as active yet could have their records removed (instead of a soft delete) from elsewhere, which meant the change wouldn't be picked up on indexing.
=> Only query for active Beatmapsets when indexing.

composer.json, composer.lock
Latest version breaks commonmark-table.
Or wait until this thing is fixed (webuni/commonmark-table-extension#16).
=> Lock commonmark version

app/Libraries/Search.php, app/Models/Beatmapset.php, app/Providers/AppServiceProvider.php, config/datadog-helper.php
laravel-datadog-helper prefixes all tags by default now.
=> change datadog prefix config key to get old tag prefixes back.

composer.json, composer.lock
Required to use `Symfony\Component\Yaml\Yaml`;
Used to be included implicitly by phpunit, not anymore.
=> composer require symfony/yaml

README.md, bootstrap.sh
Looks like updated symfony package uses new syntax introduced in PHP 7.1
Probably due to #2218?
=> Increase minimum php version to reflect updated symfony package requirements

package.json, yarn.lock
...by updating url-polyfill
The polyfill provided `URL` couldn't handle the `window.location` object in the constructor, updating fixes this.
The polyfill also seems to be loading in Safari when it shouldn't be, which is a different issue.
=> Fix broken url parsing in beatmapset discussions

app/Models/Contest.php
Entries were being sorted case-sensitively before which was... counter-intuitive.
=> Improve 'community choice' contest entry display sorting

resources/assets/coffee/react/_components/beatmapset-panel.coffee
Looks a bit better without them (still visible in hover tooltip).
=> Remove total counts of hype and nominations from search panels

resources/assets/coffee/osu_common.coffee
Laravel now passes error json as well with same key as existing ones. With default of empty string.
Fixes #2186.
=> Prevent showing empty error message

app/Http/Controllers/BeatmapsetWatchesController.php, resources/assets/coffee/react/beatmap-discussions/beatmap-list.coffee, resources/assets/coffee/react/beatmap-discussions/main.coffee, resources/assets/coffee/react/beatmap-discussions/subscribe.coffee
As beatmaps are now linked with discussions, remove beatmapset updater. It's already partly broken anyway because it doesn't usually contain deleted beatmaps. Its only user is watch function which is updated to simply toggle the watch state instead of passing the whole beatmapset.
Comes with bonus of hiding unresolved post count of deleted beatmaps.
On unrelated news, generating json of set with large discussions takes quite a long time... 🌈
=> Hide deleted beatmaps with no discussions

app/Models/Forum/TopicVote.php, resources/lang/en/model_validation.php, resources/views/forum/topics/_poll.blade.php
fixes #2288
In theory, the error message shouldn't appear anymore.
Of course, this means you can't click the button anymore if js isn't enabled, but then again, there's going to be problems with the rest of the site without js enabled :trollface:
=> Disable vote button initially; return more user-friendly error

app/Libraries/TransactionState.php
Default behaviour of `array_unique` calls `__toString()` ...which can fail.
Then there's the other sort modes which have varying levels of different kinds
of insanity.
=> Avoid using array_unique for getting unique models in transaction.

app/Models/BeatmapDiscussion.php, tests/Models/BeatmapDiscussionTest.php
`total_duration` is only for the end of hit objects and not the end of the map/music.
=> Allow starting discussion beyond last hit object

resources/assets/coffee/_classes/tooltip-default.coffee, resources/assets/coffee/react/_components/beatmapset-mapping.coffee, resources/assets/coffee/react/beatmap-discussions/event.coffee
Weird bug otherwise when the date is specified using `title`. Also prevent running the tooltip repeatedly on the specific class.
=> Require title attribute for time tooltip

resources/assets/coffee/react/beatmap-discussions/nominations.coffee
=> Display nominations in order of nomination

app/Models/Elasticsearch/UserTrait.php
Apparently having a filter context means "include everything" <_<
fixes #2349
=> Don't include results that didn't match the username matchers

resources/assets/coffee/osu_common.coffee, resources/assets/coffee/react/beatmapset-page/scoreboard-table.coffee, resources/assets/coffee/react/beatmapset-page/scoreboard.coffee, resources/assets/less/bem/beatmap-scoreboard-table.less
Adds highlighting of your own and your friends' scores on beatmap scoreboards.
(Also prevents double headers happening if you're at the top of a scoreboard)
fixes #2321
=> Scoreboard friend/self highlighting

resources/assets/coffee/react/beatmap-discussions/nominations.coffee, resources/lang/en/beatmaps.php
Not sure if intentional but the button of "Leave Feedback" which appears in discussions of ranked/loved/graveyard mapsets was only displaying in English as there's no string in locale to translate it. This PR should fix that.
=> Make "Leave Feedback" button able to be translated

resources/assets/coffee/react/_components/playmode-tabs.coffee
Use currentTarget instead of target.
Fixes #2471.
=> Allow clicking on children to switch mode

resources/assets/coffee/react/beatmap-discussions/main.coffee
It has been comparing between string, event object, and discussion object.
And it also has been checking nonexistent event attribute because it's not defined in transformer.
:rainbow: :horse:
=> Fix discussion lastUpdate logic

resources/assets/less/bem/account-edit-entry.less, resources/assets/less/bem/account-edit.less, resources/assets/less/bem/beatmap-discussion-new-float.less, resources/assets/less/bem/beatmap-discussion-post.less, resources/assets/less/bem/beatmap-discussion.less, resources/assets/less/bem/beatmap-icon.less, resources/assets/less/bem/beatmapset-beatmap-picker.less, resources/assets/less/bem/beatmapset-panel.less, resources/assets/less/bem/beatmapset-row.less, resources/assets/less/bem/btn-circle.less, resources/assets/less/bem/btn-osu-big.less, resources/assets/less/bem/changelog-build.less, resources/assets/less/bem/detail-row.less, resources/assets/less/bem/landing-hero.less, resources/assets/less/bem/loading-overlay.less, resources/assets/less/bem/notification-banner.less, resources/assets/less/bem/osu-page-header.less, resources/assets/less/bem/page-extra-tabs.less, resources/assets/less/bem/product-box.less, resources/assets/less/bem/profile-extra-entries.less, resources/assets/less/bem/search-entry.less, resources/assets/less/bem/search-result.less, resources/assets/less/bem/support-osu-popup.less, resources/assets/less/forum/base.less, resources/assets/less/functions.less
Safari does something with `content: ' '` even when it's not in `::before`/`::after` ┐(' ヮ' )┌
=> Unbreak safari

app/Libraries/Fulfillments/ApplySupporterTag.php
It was always being assigned the donor's id through the association.
Except, nothing that uses it is actually used anywhere :trollface: 
...which is also probably why it wasn't noticed >_>
=> Fix wrong target_user_id being saved in UserDonation

resources/assets/less/bem/usercard.less, resources/views/objects/_usercard.blade.php
Accidentally the wrong class on background container, meaning it'd `opacity: 0` 😅
=> Fix usercard covers in popups

app/Http/Controllers/AccountController.php, app/Http/Controllers/BeatmapDiscussionPostsController.php, app/Http/Controllers/BeatmapDiscussionsController.php, app/Http/Controllers/Forum/PostsController.php, app/Http/Controllers/Forum/TopicsController.php, app/Models/BeatmapDiscussion.php, app/Models/BeatmapDiscussionPost.php, app/Models/Forum/Topic.php, tests/Models/BeatmapDiscussionPostTest.php, tests/Models/BeatmapDiscussionTest.php
Implement actual validation instead of using `null` check. And do some refactors on handling `ModelNotSaved`.
Can be simplified further by doing it at global exception handler for general cases (all of them at the moment). Maybe later (and not sure if good idea yet).
Fixes #2550.
=> Proper delete validation

app/Http/Controllers/API/BeatmapsetsController.php, routes/web.php
Similar to beatmap lookup, currently only supports looking up by `beatmap_id`.
e.g.: `/api/v2/beatmapsets/lookup?beatmap_id=660345`
Ideally this functionality will eventually be merged into search, along with the ability to search other beatmap/set metadata, etc.
fixes #2625
=> API beatmapset lookup endpoint

app/Jobs/RegenerateBeatmapsetCover.php, config/queue.php
Default timeout is 60s and some runs have exceeded that and been killed (due to some combination of slow osz retrieval, large backgrounds, network latency spikes, etc)
=> Increase timeout for beatmap cover generation jobs

resources/assets/less/bem/beatmap-discussion-nomination.less
Keep forgetting about IE overflowing instead of extending the box on `flex: 1`.
=> Unbreak discussion page nomination box (IE)

resources/assets/coffee/react/beatmapset-page/info.coffee, resources/assets/less/bem/beatmap-success-rate.less
Previous calculation was dividing `passcount` by `playcount + passcount` for some reason.
Also adds a tooltip to the percentage to also show raw pass/play counts.
fixes #2652
=> Fix success rate display for beatmaps

app/Http/Controllers/UsersController.php
Either that or fake it correctly and not just empty array? :man_shrugging: 
The only react component using it already does the null check.
The client doesn't like empty array :dancer:
=> Null rank history if blank

app/Http/Controllers/Admin/BeatmapsetsController.php, app/Http/Controllers/LegacyInterOpController.php
This will let us prioritise admin removal/regeneration jobs ahead of normal jobs.
Usually this is not an issue, but when there's a backlog (e.g. batch reprocessing), admin-initiated jobs can get held up.
Will require an update to the thumbnailer box to pick up jobs on the new queues
=> Rename beatmap job queue and split into priorities.

resources/assets/coffee/_classes/beatmap-discussion-helper.coffee
Fixes parse failing when url has a trailing `/` or one of the components is empty.
Also does whitelisting of `mode` and `filter` when parsing.
=> Fix client beatmap discussion failing to parse url with empty path components

app/Transformers/UserMonthlyPlaycountTransformer.php, app/Transformers/UserReplaysWatchedCountTransformer.php, app/helpers.php, resources/assets/coffee/_classes/line-chart.coffee, resources/assets/less/bem/chart.less
Use `json_date` and update the function to return date-only version of iso8601.
Also updated the helpers to be compatible with any `DateTime` while at it.
Not sure if should just call `moment.utc` when parsing instead ┐(°_° )┌
Fixes #2643.
Also includes fix for tooltip on [ie](https://github.com/philipwalton/flexbugs#flexbug-12) due to using `::before` and `::after` as flex element.
=> Profile history graph date fix

resources/assets/coffee/react/beatmap-discussions/main.coffee
=> Fix counting per-mode open issues

resources/assets/coffee/react/beatmap-discussions/main.coffee
Immediately set currentMode instead of pretending mode update.
=> Fix switching mode when clicking filter

app/Jobs/CheckBeatmapsetCovers.php, app/Models/Beatmapset.php, app/helpers.php
...and queue a regeneration if any are missing
=> Check beatmap cover images on qualification

app/Models/BeatmapFile.php
otherwise header detection fails
=> Strip the UTF-8 BOM before attempting to parse .osu files

app/Http/Controllers/UsersController.php
The tiles rely on more info than the compact transformer provides and we've optimised the 'full' transformer to remove most of the slowness unless included anyway.
fixes #2704
=> Use full transformer instead of compact for beatmaps on user profiles

resources/assets/coffee/react/beatmap-discussions/discussion.coffee, resources/assets/coffee/react/beatmap-discussions/main.coffee, resources/assets/coffee/react/beatmapset-page.coffee, resources/assets/coffee/react/beatmapset-page/main.coffee, resources/assets/coffee/react/profile-page.coffee, resources/assets/coffee/react/profile-page/main.coffee, resources/assets/coffee/turbolinks-overrides.coffee
Should fix part of #2696. Need more checks. There are some components not yet updated to `registerPersistent` thingy.
- unmount after replacing the page
- save state on `before-cache` to where the component is attached to
- disable anchor existence check in turbolinks because some of the anchors used don't exist which causes page fetch on history navigation
=> Turbolinks, react, and navigation

app/Models/Score/Best/Model.php
Scores should be deleted when their associated beatmap is deleted (but they're not being in some cases right now), so this handles that case as a precaution.
=> Prevent user profiles from breaking when scores exist for (soft) deleted beatmaps

config/osu.php, resources/views/layout/metadata.blade.php
env() helper returns nulls when combined with cached configs
=> Move site-switcher JS file hash to config var

resources/assets/less/bem/beatmapset-header.less
Because `flex-start` will happily go over 100% when needed :tada:
=> Prevent overflowing title

resources/assets/coffee/react/profile-page/header-main.coffee, resources/assets/less/bem/avatar.less, resources/assets/less/variables.less
Old artifact ┐(' ヮ' )┌
Also allows right clicking any elements without closing the popup.
Fixes #2841.
=> Remove profile avatar z-index

resources/assets/less/bem/navbar-mobile-item.less
=> Don't lowercase the username line in mobile nav

resources/assets/coffee/_classes/form-toggle.coffee, resources/assets/coffee/react/_components/bbcode-editor.coffee, resources/assets/coffee/react/beatmapset-page/info.coffee, resources/assets/coffee/react/profile-page/user-page-editor.coffee, resources/assets/less/base.less, resources/assets/less/bem-index.less, resources/assets/less/bem/post-editor-footer.less, resources/assets/less/bem/post-editor.less, resources/views/forum/topics/_post_box_footer.blade.php, resources/views/forum/topics/create.blade.php
- migrate profile page editor to use `BBCodeEditor`
- cleanup the component
- migrate topic creation page to use shared footer component
- fix toolbar alignment. Fixes #2887 
- (css) style updates
- other related stuff
=> Refactor post editor (and footer)

resources/assets/less/bem/nav2.less, resources/assets/less/layout.less, resources/assets/less/variables.less
- smaller logo and avatar to fit polish menu
- adjust padding for search button
- fix padding because I confused vertical and horizontal
- always visible scroll bar
=> Navigation header metric tweaks

database/migrations/2018_04_06_081112_unique_beatmapset_discussion_votes.php
Forgot a unique index =)
Fixes #2923.
Useful stuff:
```php
DB::table('beatmap_discussion_votes')->groupBy(['user_id','beatmap_discussion_id'])->having('count(*)', '>', 1)->selectRaw('count(*), max(id), max(score), min(score), beatmap_discussion_id, user_id')->get();
// clean up
$a = DB::table('beatmap_discussion_votes')->groupBy(['user_id','beatmap_discussion_id'])->having('count(*)', '>', 1)->selectRaw('count(*), max(id), max(score), min(score), beatmap_discussion_id, user_id')->get()->pluck('max(id)')->toArray();
BeatmapDiscussionVote::whereIn('id', $a)->get()->each->delete();
php artisan kudosu:recalculate-discussions-grants
```
=> Prevent duplicate voting to same discussion

app/Libraries/Elasticsearch/QueryHelper.php
`simple_query_string` discards the invalid parts of `query_string` instead of letting Lucene explode on badly formed queries.
tbh, neither should be used for public facing queries
=> use simple_query_string instead of query_string

app/Models/Store/Order.php
It should be waiting for `status` to finish committing, otherwise it's doing the check with an old value and then queueing the delete anyway
=> Wait to acquire row lock before checking if record can be deleted.

app/Models/Model.php, app/Models/Store/Order.php
=> Use $this->getConnection() instead of DB::connection($this->connection)

app/Http/Controllers/HomeController.php, resources/views/home/support-the-game.blade.php
Fixes:
- Supporter status page breaking when missing purchase data for tags.
- Expiration date being hidden for people who've been gifted tags but never purchased any.
- Misnamed variable (`used` was actually `remaining`)
=> Supporter status page fixes

resources/assets/coffee/react/beatmap-discussions/new-discussion.coffee
Incorrectly showing 'disqualify' for BNs. Fixes #2983.
=> Show correct button labels

resources/assets/coffee/forum/post-box.coffee, resources/assets/coffee/react/_components/bbcode-editor.coffee
Fixes #2970.
Couldn't find a way to tell react to not select anything hence the dumb workaround ಠ_ಠ
=> Reset size selector on select and load (browser form saving)

app/Http/Controllers/HomeController.php, app/Models/Contest.php, resources/assets/coffee/react/_components/beatmapset-panel.coffee, resources/assets/coffee/react/_components/tracklist-track.coffee, resources/assets/coffee/react/beatmap-discussions/new-reply.coffee, resources/assets/coffee/react/beatmapset-page/header.coffee, resources/assets/coffee/react/contest/voting/entry.coffee, resources/views/contests/_voting-entrylist.blade.php, resources/views/home/download.blade.php, resources/views/home/landing.blade.php, resources/views/home/user.blade.php, resources/views/objects/beatmap-panel.blade.php
Fixes missing icons in beatmap discussion and replaces cloud download icon.
fixes #2993
=> font-awesome icon fixes

resources/views/master.blade.php
Previously included in header template for some reason ┐(' ヮ' )┌
=> Put back popup template

resources/assets/less/bem/profile-extra-entries.less
fixes #2794
also causes other text like the kudosu history to wrap
=> Allow activity text on user profile page to wrap

webpack.mix.js
2 copies of React and friends were being served ( ﾟ ヮﾟ)
=> Define React and friends as externals in webpack

package.json, resources/assets/coffee/react/beatmaps/main.coffee, resources/assets/less/bem/beatmapsets.less, resources/assets/less/bootstrap-variables.less, resources/assets/lib/import-shims.coffee, yarn.lock
sort of fixes #2117
Virtualizes the beatmap listing to keep it fast after scrolling through many pages. 
I gave up on using `react-virtualized` and opted to fork`react-virtual-list` to make it work with our flexbox layout on the page instead, since:
- it required way too many changes to work
- didn't do a very good job of restoring the scroll position when navigating back in history.
- this option turned out to be massively simpler ( ﾟ ヮﾟ)
It doesn't eject the already loaded data yet
=> Virtualize beatmap listing

app/Libraries/OsuMarkdownProcessor.php
Should fix cases where `json_encode` fails due to `strtolower` deciding the text is ascii.
Also less environment dependent ಠ_ಠ
```
>>> strtolower('かなAAmĄkA')
=> b"ÒüïÒü¬aamõäka"
>>> mb_strtolower('かなAAmĄkA')
=> "かなaamąka"
>> strtolower('欢迎来到')
=> "欢迎来到"
>>> mb_strtolower('欢迎来到')
=> "欢迎来到"
>>> strtolower('欢迎来到Ą')
=> b"µ¼óÞ┐ÄµØÑÕê░õä"
>>> mb_strtolower('欢迎来到Ą')
=> "欢迎来到ą"
```
=> Use mb_strtolower in OsuMarkdownProcessor.

app/Models/Model.php, app/Transformers/UserTransformer.php
There's null, and then there's empty string.
=> Filter out empty string username_last

resources/assets/less/bem/badge-rank.less
=> Use '100%' instead of 'cover' for .badge-rank

app/Http/Controllers/AccountController.php, app/Models/User.php, app/Transformers/UserTransformer.php, resources/assets/coffee/_classes/tooltip-default.coffee, resources/assets/coffee/react/_components/click-to-copy.coffee, resources/assets/coffee/react/profile-page/header-extra.coffee, resources/assets/less/bem-index.less, resources/assets/less/bem/click-to-copy.less, resources/lang/en/accounts.php, resources/lang/en/common.php, resources/lang/en/model_validation.php, resources/lang/en/users.php, resources/views/accounts/edit.blade.php
(reuses the existing `user_jabber` field for now until we can rename the database column)
fixes #1286 (but doesn't nuke skype)
=> Add Discord field to user profiles

resources/assets/coffee/react/_components/play-detail.coffee
Base it on pp value instead of beatmapset status. Fixes #3039.
=> Fix check for showing pp

resources/assets/coffee/react/_components/bbcode-editor.coffee
Ensure it's always at the beginning. Also current behavior is different between firefox and chrome.
Fixes #3014.
<sup><sup><sup>not sure if it's actually better</sup></sup></sup>
=> Improved cursor position on edit start

app/Http/Controllers/BeatmapsetsController.php
Went missing when page output caching was reverted to beatmapset id
caching
=> Eagerload beatmaps.

app/Libraries/Search/BeatmapsetSearch.php
Filter on beatmap_id instead, removing the extraneous database query.
=> Switch beatmap search rank filter to filter on beatmap_id

resources/views/layout/metadata.blade.php
I guess forum posts haven't had proper bold or italics since we changed to Noto Sans?
=> Load bold and italic versions of Noto Sans

resources/views/forum/topics/_post_edit.blade.php
Currently explodes when editing post of a deleted user.
=> Use correct user for rendering post info in editor

app/Libraries/BBCodeFromDB.php, resources/assets/less/bbcode.less, resources/assets/less/bem/forum-post.less, tests/Libraries/BBCodeForDBTest.php, tests/Libraries/BBCodeFromDBTest.php, tests/Libraries/bbcode_examples/quote_newline.base.txt, tests/Libraries/bbcode_examples/quote_newline.db.txt, tests/Libraries/bbcode_examples/quote_newline.html, tests/TestCase.php
Fixes #2947.
And other misc fixes.
=> Remove spaces after quotes

resources/assets/less/bem/news-post-preview.less
Unless it should always be wrapped, or not...?
=> Right align the news preview post date if it happens to wrap

routes/web.php
Currenty the redirect only works for wiki paths one level deep:
`/wiki/Welcome` -> `/help/wiki/Welcome`
This fixes the redirects for anything deeper:
`/wiki/Mascots/Gallery` -> `/help/wiki/Mascots/Gallery`
`/wiki/we/need/to/go/deeper` -> `/help/wiki/we/need/to/go/deeper`
=> Allow redirecting wiki paths more than one level deep

app/Http/Controllers/Users/ModdingHistoryController.php, app/Models/BeatmapDiscussion.php, app/Models/BeatmapDiscussionPost.php, app/Models/BeatmapDiscussionVote.php
fixes #3145 
`request()->all()`/`request()->toArray()` also does not have the same values as `request()`
=> Fix modding history not applying user filter

app/Traits/UserAvatar.php, config/osu.php
Was still used in some places (usercards, etc)
=> Replace the old default avatar

app/Libraries/Payments/PaymentProcessor.php
stops treating the cancelling of already cancelled payments from paypal as errors.
=> Check if cancelled Order already has a cancelled Payment

resources/assets/coffee/react/beatmap-discussions/main.coffee
fixes #3167 and makes username sorting case-insensitive
=> Filter blank discussions and change to case-insensitive username sort

resources/assets/coffee/react/_components/beatmapset-panel.coffee, resources/assets/less/bem/beatmapset-panel.less
This had been bothering me, so I fixed it.
(also includes a bit of cleanup, removing an unneeded container class or two)
=> Retina-ify beatmapset-panel

resources/assets/coffee/_classes/beatmap-discussion-helper.coffee
Repeating `text.replace` call for each urls don't work because it may incorrectly replace previously linkified urls.
Fixes #3176.
=> Fix discussionLinkify

app/Models/Store/OrderItem.php, app/framework_helper_overrides.php, resources/assets/coffee/_classes/store-supporter-tag-price.coffee, resources/assets/coffee/main.coffee, resources/assets/coffee/osu_common.coffee, resources/assets/coffee/store-username-change.coffee, resources/assets/less/bem/simple-form.less, resources/lang/en/forum.php, resources/views/accounts/_edit_playstyle_checkbox.blade.php, resources/views/forum/topics/_create_poll.blade.php, resources/views/home/_search_results.blade.php, resources/views/home/search.blade.php, resources/views/packs/index.blade.php, resources/views/store/checkout.blade.php, resources/views/store/products/supporter-tag.blade.php, resources/views/store/products/username-change.blade.php, resources/views/users/posts.blade.php, tests/LocaleTest.php
To work with crowdin. Fix `Lang.choice` and do minor cleanup while at it.
- only use `trans()` and `trans_choice()` for php
- only use `osu.trans()` and `osu.transChoice()` for javascript
- add `osu.presence` helper to allow chaining
- don't set fallback locale
- as it turned out the library hasn't been updated with plural rule bug fix
=> Override trans to ignore empty strings

resources/assets/coffee/_classes/beatmap-helper.coffee
Allow switching to mode which all maps are deleted by falling back to plain `_.last` when there's no active maps available.
Fixes #3197.
=> Fix mode switching in discussion

app/Http/Controllers/Store/CartController.php
~~since #3213 explicitly makes the cart null when not found.~~
since #3213 checks the cart now
=> Order checkout validation does not support null carts

resources/assets/coffee/_classes/nav-button.coffee
Mainly for landing page which doesn't have the nav.
=> Conditionally activate nav button javascript

resources/assets/coffee/_classes/account-edit-playstyle.coffee, resources/assets/coffee/_classes/account-edit.coffee
On update, immediately:
- abort previous request
- show spinner
Fixes #3258.
=> Synchronize account saving behavior

app/Exceptions/Handler.php
`ajax` only covers requests with `X-Requested-With=XMLHttpRequest`.
And change `expectsJson` to `wantsJson`. The former also includes `ajax` requests.
=> Return json on error for a json request

.env.example, app/Http/Controllers/API/LegacyController.php, app/Jobs/RemoveBeatmapsetBestScores.php, app/Libraries/ReplayFile.php, app/Models/Beatmapset.php, app/Models/ReplayViewCount/Fruits.php, app/Models/ReplayViewCount/Mania.php, app/Models/ReplayViewCount/Model.php, app/Models/ReplayViewCount/Osu.php, app/Models/ReplayViewCount/Taiko.php, app/Models/Score/Best/Model.php, app/Traits/Scoreable.php, config/filesystems.php, config/osu.php, database/migrations/2015_01_01_133337_base_tables.php
=> Delete scores on qualification

app/Models/Forum/Post.php, app/Models/Forum/Topic.php, app/Models/User.php
The old one was a scope which was made before `macro` was created, causing broken stuff when real `last` function/macro is created.
=> Remove overlapping `last` function

app/Libraries/Search/BeatmapsetSearch.php
When searching for recommended difficulties of any mode type, it should default to the
user's playmode instead of using `osu`.
fixes #3302
=> Use user's playmode when searching for recommended difficulties.

resources/assets/less/bem/usercard.less
Match with `.avatar`. Fixes #3309.
=> Fix avatar scaling in usercard

resources/assets/less/bem/changelog-change.less
fixes #3323 
Also align items to baseline which has the side-effect of aligning the text on mobile to the left instead of centre.
=> Unjustify changelog change text.

app/helpers.php
Fixes #2752. Not adding to beatmap packs because it doesn't seem to make sense unless people really care about the exact time.
=> Add full date tooltip on registration date

resources/assets/coffee/_classes/account-edit-blocklist.coffee, resources/assets/coffee/main.coffee
Skip updating block count for guest and ensure `currentUser` is updated early enough.
=> Fix logging in

app/Jobs/UpdateUserForumCache.php, app/Models/Elasticsearch/PostTrait.php, app/Models/Elasticsearch/TopicTrait.php, app/Models/Forum/Forum.php, app/Models/Forum/Post.php, app/Models/Forum/Topic.php, app/Models/User.php, app/Traits/EsIndexable.php, app/helpers.php
- update `DB::transaction` to `$this->getConnection()` in some models
- directly increment/decrement cache counts
- queue heavy updates
- still need to be checked further
=> Faster topic cache update

resources/lang/en/changelog.php
It doesn't match the default style.
=> Remove period from placeholder changelog description

resources/assets/less/bem/nav2-header.less
- fixes #3395
caused by rounding of layout values.
---
Stops the top of the navigation bar's background from leaking through the bottom
=> Prevent navigation background from vertically repeating

resources/assets/coffee/react/_components/friend-button.coffee, resources/lang/en/friends.php
fixes #3346
---
Shows the add friend button and disables it instead of hiding it when the friend limit is reached.
=> Disable add friend button instead of hiding

app/Models/Beatmapset.php, database/migrations/2018_06_25_072709_update_beatmapset_datetimes_datatype.php
The last two columns (`cover_updated_at` and `queued_at`) are assigned from new web and doesn't have timezone adjustment so it's been stored in UTC. The rest were assigned from old web which uses UTC+8 and thus readjusted because conversion is done in UTC timezone.
Fixes #3399.
---
=> Fix datetime datatype for osu_beatmapsets

app/Models/Build.php, app/Transformers/BuildTransformer.php
Filtering in model relation doesn't work when combined with eager load because $this is null for eager load.
---
=> Fix changelog listing showing no legacy entries

resources/assets/coffee/_classes/beatmap-helper.coffee
closes #3490
Still need a different icon for coverts.
---
Difficulties now sorted according to; converts, key mode (for mania), star difficulty; with the converts going at the end.
=> Change beatmap page difficulty sort order

app/Http/Controllers/Payments/XsollaController.php, app/Models/News/Index.php, app/Models/News/Post.php, app/Models/Wiki/Image.php, app/Models/Wiki/Page.php, app/helpers.php
Covers a bit more than #3493 which misses handler for news pages which are also needed for home page (and wiki pages).
Fixes #3193.
closes #3493
---
=> Add caching fallback for GitHub pages

app/Libraries/Search/ForumSearch.php, resources/views/home/_search_result_forum_post.blade.php
Avoids using has_child to get the first post in a forum search. This particular portion of the query seems excessively expensive.
---
=> Retrieve first posts for forum search using a separate query

composer.json, composer.lock, config/datadog-helper.php
Fixes issue with Datadog not liking metrics that have large numbers of unique tags on them - each request was getting tagged with the full uri requested... which resulted in lots of tags.
(also includes composer dependency updates)
---
=> Switch to using forked laravel-datadog-helper with url tagging disabled

app/Libraries/Elasticsearch/Search.php
Don't consider the search window as exceeded if query size is 0, otherwise aggregations and other queries that don't require any hits won't run.
fixes breakage from #3500 
---
whoops
=> Fix missing user best performance

app/Models/Elasticsearch/TopicTrait.php, resources/views/home/_search_result_forum_post.blade.php
Topics moved to a new topic shouldn't be indexed as they have no post content.
Also handle a case when showing results that haven't finished propagating through the index (`topic` updated but `post` is still waiting)
---
=> Don't index topics that were moved to a new topic

config/schemas/posts.json
Removes duplicate tokens from the `search_content` token stream when indexing.
Speeds up searching and scoring the `search_content` field on `posts` index.
The `posts` index should be recreated to apply the updated analyzer
---
=> Add unique token filter to post text analyzer

app/Models/User.php, database/factories/OrderFactory.php, tests/Libraries/Fulfillments/BannerFulfillmentTest.php, tests/Libraries/Fulfillments/SupporterTagFulfillmentTest.php, tests/Libraries/Fulfillments/UsernameChangeFulfillmentTest.php
- use orders that are in a paid state when running fulfillment tests
- explicitly set `UsernameChangeHistory` timestamp instead of `null`.
---
=> Use paid orders in fulfillment tests

app/Http/Controllers/HomeController.php, app/Models/User.php, resources/views/home/support-the-game.blade.php
Supporter expires the day after `osu_subscriptionexpiry`, so this is reflected in the display now.
This also changes the expiration shown to be an absolute date instead of a relative datetime. Having a time doesn't make sense when `osu_subscriptionexpiry` is only of day granularity and not guaranteed to expire at a specific time.
fixes #3527
---
=> Fix supporter expiration display

app/Models/News/Index.php, app/Models/News/Post.php, app/helpers.php
Probably should be a bit smarter by updating expiration date to `now()` instead?
---
=> Fix news refresh logic

database/migrations/2015_01_01_133337_multiplayer_base_tables.php
mediumint isn't enough to hold mania mods data. Live database has been updated to match this change.
Fixes #3537. Kind of.
---
=> Update multiplayer games mods column datatype

resources/assets/coffee/_classes/nav2.coffee
fixes #3535
Fractional CSS transforms makes text blurry...but not on retina displays
---
=> Make sign-in popup less blurry

app/Models/TournamentRegistration.php
Noticed this when `TableTest::testTableExistence()` failed while running on a test database that wasn't named `osu`.
---
=> Remove explicit database name in TournamentRegistration table definition

app/Models/Contest.php, app/Transformers/ContestEntryTransformer.php
Resolves an issue where images (that were not yet uploaded prior to the contest page being accessed for the first time) were being cached as a 404, which resulted in having no image dimension metadata (which broke the javascript image viewer relying on this metadata).
---
=> Force image dimensions to be rechecked when contests are made live

resources/assets/coffee/_classes/tooltip-beatmap.coffee, resources/assets/coffee/_classes/tooltip-default.coffee
if not triggered by touch.
Browser doesn't send touch events? TOO BAD. (looking at you Edge)
closes #3343
---
=> Disable tooltip auto hiding

app/Http/Controllers/ArtistsController.php
closes #3579
No index since the small table size meant mysql didn't use it for sorting anyway
---
=> Show featured artists in alphabetical order

app/Models/BeatmapMirror.php, app/Models/Beatmapset.php
Seems like this behaviour was broken when adding the ability to download Beatmaps (when the `BeatmapMirror` logic was unified).
---
=> Fix beatmap processor not using mirrors listed in config

.travis.yml
TravisCI recently made changes where `key_url` isn't fetched unless safelisting is disabled.
---
=> Switch TravisCI to pre-whitelisted mysql-5.7

resources/assets/coffee/_classes/tooltip-beatmap.coffee, resources/assets/coffee/_classes/tooltip-default.coffee
Adds `click` as a trigger to hide qtip2.
Seems like many things can cause qtip2 to not trigger the default `mouseleave` handler to hide the qtip, such as: modifying the element's properties, modifying the element's children, moving the cursor out too fast after clicking, breathing on it, displaying another element over the current element.
closes #3571
---
=> Hide tooltip on click

resources/assets/coffee/react/beatmap-discussions/post.coffee, resources/views/forum/topics/_post.blade.php
Discourages Googlebot from spidering individual posts unnecessarily -- the threads/discussions they belong to are being indexed already.
---
=> Add rel='nofollow' to forum and moderation post permalink... links.

resources/assets/less/variables.less, resources/views/layout/metadata.blade.php
Now with correct backtick unlike noto sans'.
=> Switch default content font to open sans

resources/views/home/search.blade.php
closes #3633
Beatmap listing wasn't affected since the `<input>` there wasn't in a `<form>`
---
=> Turn off form autocomplete for the search page

app/Libraries/OsuAuthorize.php
Fixes #3358. Or more like fixes a different bug caused by recent merge.
Though looking again, we shouldn't even allow deleting first post.
=> Check for first deleted post if there's no visible post

resources/assets/coffee/_classes/url.coffee
Apparently "#" stays so the check fails when location is something like "/home#".
=> Fix internal url check

docker/php/Dockerfile
Composer didn't want to install some packages because of `fileinfo` missing.
=> Add missing php extension to docker

app/Http/Controllers/AccountController.php, app/Libraries/Session/Store.php
Yeah so Redis' SCAN command isn't so scalable.
This replaces the need to perform the SCAN by maintaining an additional SET (per user) alongside the normal session keys that contains a list of all their sessions.
---
=> Change user session management to use sets instead of scan

app/Http/Controllers/BeatmapsetsController.php, app/Http/Controllers/UsersController.php, app/Libraries/Elasticsearch/HasChildQuery.php, app/Libraries/Elasticsearch/HasSearch.php, app/Libraries/Elasticsearch/Search.php, app/Libraries/Elasticsearch/SearchParams.php, app/Libraries/Search/BeatmapsetSearch.php, app/Libraries/Search/BeatmapsetSearchParams.php, app/Libraries/Search/BeatmapsetSearchRequestParams.php, app/Libraries/Search/ForumSearch.php, app/Libraries/Search/ForumSearchParams.php, app/Libraries/Search/ForumSearchRequestParams.php, app/Libraries/Search/MultiSearch.php, app/Libraries/Search/PostSearchRequestParams.php, app/Libraries/Search/UserSearch.php, app/Libraries/Search/UserSearchParams.php, app/Libraries/Search/UserSearchRequestParams.php, app/Libraries/Search/WikiSearch.php, app/Libraries/Search/WikiSearchRequestParams.php
- parse parameters and set defaults earlier.
- changes `HasSearch` from trait to class.
- limit use of `page` to request params.
- include `_id` as part of beatmap search sort order, so that there's a deterministic order if the sort values would otherwise have ben the same.
- excluding `_source` from results should be using `false` instead of fields that don't exist in `_source` (`_id` is always included in the elasticsearch response).
This is a dependency of some incoming changes but this is PR'ed first since it's not dependent on the other changes, so we can check for breakage on this part separately.
---
=> Search classes refactoring

resources/assets/lib/report-form.coffee
fixes #3750 
`Lang.locale` doesn't get set until later, so we can't use `osu.trans` during the module/class loading
---
=> Fix report reasons localization

app/Libraries/Elasticsearch/Search.php
Fixes possible missing results in beatmap listing on the tail end of results when ordering by ranking date and including maps that aren't ranked.
javascript thinks `-9223372036854775808` is `-9223372036854776000` 🥇 
---
=> Convert int cursors to string for javascript

resources/assets/coffee/react/beatmaps/search-panel.coffee
because the portal placeholders don't exist if you're not logged in
---
=> Fix beatmap listing not showing if not logged in

resources/assets/less/bem/nav2-header.less
closes #3845
The triangle background in header peeks through at some scaling levels making it look like the sticky bits below it are not attached.
---
=> Fix triangle background in header peeking through

app/Libraries/OsuAuthorize.php
wrong variable name :fire:
Basically for about an hour only the poll creator and moderators could see the post until the editable period expires
closes #3893
---
=> Fix not being able to see forum posts with a poll

app/Http/Controllers/Chat/ChannelsController.php, app/Libraries/OsuAuthorize.php, app/Models/Chat/Channel.php, tests/Controllers/Chat/ChannelsControllerTest.php
- use (and update) `ChatChannelJoin` auth check
- allow admin to join any channels
- only allow channel type public for others for now
- return code on joining non-public channel is changed (from 404 to 403) but should be fine because `channelId` doesn't give out much information?
- not sure why it's never used ?_?
- remove type check in `addUser`/`removeUser`
- only one place is using it (and already checked) so it should be safe
- it looks like `ChatController#newConversation` can be updated to use `addUser`
=> Use priv_check for joining/leaving channel

resources/assets/less/bem/osu-md.less
closes #3928 
We should probably look at supporting markdown extensions for custom header ids (which seems to have made no progress in commonmark) instead, like:
```
```
---
=> Fix anchor offsets on news pages

app/Models/Wiki/Page.php, app/helpers.php, resources/views/wiki/show.blade.php
I might've missed more places requiring this workaround. Will fix them as encountered.
Works around laravel/framework#26715.
=> Don't fail when passing certain string for route parameter

app/Exceptions/Handler.php, app/Http/Controllers/AuthorizationController.php, app/Http/Controllers/Passport/AuthorizationController.php, app/Http/Controllers/UsersController.php, app/Http/Kernel.php, app/Http/Middleware/RequireScopes.php, app/Providers/AppServiceProvider.php, app/Providers/AuthServiceProvider.php, app/Transformers/UserTransformer.php, app/helpers.php, resources/lang/en/api.php, routes/web.php, tests/Controllers/Chat/Channels/MessagesControllerTest.php, tests/Controllers/Chat/ChannelsControllerTest.php, tests/Controllers/Chat/ChatControllerTest.php, tests/Controllers/Passport/AuthorizationControllerTest.php, tests/RequireScopesTest.php, tests/RouteScopesTest.php, tests/TestCase.php
- Makes the API endpoints require OAuth tokens to have the correct scopes.
- ~~Implicit scope normalization isn't included in this change, so for the time being, scopes will have to be explicitly requested.~~
The current checking of permissions and the ability to filter output based on permissions is kind of crap, so we're probably going to have to do something about that too.
Initially, the only scope available for third-party authorization is `identify` for `/me`; other endpoints and scopes will be made available as they're checked.
Expected behaviour should be:
- `require-scopes` with parameters should require tokens to have all the scopes listed
- `require-scopes` without parameters should deny access by default except for tokens with `*` scope, or more explicit scopes are required
- …
=> Apply OAuth permission scoping to API

app/Http/Controllers/Controller.php, resources/assets/coffee/_classes/user-login.coffee
Removed when adding user session listing. Also allow `js-login-required--click` to intercept UJS.
=> Immediately regenerate csrf token on login

app/Http/Middleware/RequireScopes.php
Because the middleware list can contain functions
---
=> Fix RequireScopes middleware containsScoped check

app/Http/Controllers/WikiController.php
The helper accepts wiki page path but redirect target includes hash target. Fixes #3988.
=> Don't use helper for wiki redirect

resources/assets/coffee/turbolinks-overrides.coffee
Closes #3948
Doesn't have effect on pages where scrolling to anchor is done by some other means, e.g. modding discussions
---
=> Update url when navigating to anchors

app/Http/Middleware/AutologinFromLegacyCookie.php
Otherwise user might not be able to verify if the first thing a user goes to on the new site triggers verification. 
---
=> Set csrf token when logging in from legacy cookie

SETUP.md
Since with Node.js 11, ./build.sh fails for node-saas incompatibilty, I modified the requirements indicating the latests compatible version of NodeJS with node-saas.
=> Edited node.js requirement

app/Models/ChangelogEntry.php, tests/Models/ChangelogEntryTest.php
Split by `\n\n---\n` just like new one except the first part is used for title instead of hidden.
=> Add message support for legacy changelog entries

app/Models/BeatmapsetArchive.php
Was incorrectly ignoring path when checking for the presence of background images.
---
=> Fix beatmapset cover thumbnailer image presence check

package.json, yarn.lock
~~Not sure why my configuration doesn't auto-install this one~~. Apparently I have leftover `node_modules` in directory above `osu-web` (web root is `/.../osu/osu-web`, and there's `/.../osu/node_modules`) and it's got the vue thing installed so it has been using that one 😐
=> Add missing package

resources/assets/less/bem/forum-topic-title.less, resources/assets/less/functions.less
Thanks, autoprefixer :100: 
Or the lack of finalized actual standard for this (I think?).
=> Fix chrome/webkit line-clamp styling

resources/assets/coffee/main.coffee, resources/assets/less/bem/navbar-mobile.less, resources/assets/lib/import-shims.coffee, resources/assets/lib/osu-core.ts, resources/assets/lib/window-vh-patcher.ts
closes #3852
Still has problems on mobile Safari where the body element behind the menu will scroll instead of the menu in some cases, but there doesn't seem to be a reliable solution for this as long as the body is scrollable (and Safari insists the body is scrollable as long as the content extends past the visible window).
---
=> Allow burger menu to be scrolled on mobile

tests/Libraries/Multiplayer/ModTest.php
Previously only testing the first combination because the function it tests throws so the next iteration isn't run.
Also going fancy with phpunit dataProvider :dancer:
=> Fix mods combination test

app/Transformers/CountryStatisticsTransformer.php, app/Transformers/UserCompactTransformer.php, app/Transformers/UserTransformer.php, resources/assets/coffee/react/_components/flag-country.coffee
closes #3875
would be better if `transform` itself could return null instead of array
---
=> Return null instead of object with null fields if country is null.

resources/lang/en/fulfillments.php, resources/views/emails/store/supporter_gift-en.blade.php
- title of email was vague
- removed `now`, since a user might still have osu!supporter
- proper styling of `osu!supporter`
- periods
---
=> Fix wording on osu!supporter gift email

app/Models/User.php
In cases a user profile is hit using `user_id`, there is a potential that php/eloquent will be "smart" and not quote it as a string in the adjusted query, causing a complete index miss.
Fix has been applied server-side.
=> Fix username lookups with ints instead of strings

app/Transformers/ScoreTransformer.php
Don't `getMode` for multiplayer scores because it doesn't have a mode
---
=> Hotfix ScoreTransformer for multiplayer scores

resources/assets/coffee/_classes/forum.coffee
Anchor position is now at the bottom of the header, so the post position was incorrect which breaks the keyboard navigation.
closes #4116
---
=> Fix forum post keyboard navigation

tests/Libraries/Fulfillments/SupporterTagFulfillmentTest.php, tests/Libraries/UserRegistrationTest.php
One is more sane than the other. Also I keep forgetting which one is correct. Time comparison is updated to use carbon's `equalTo`.
=> Update tests to use assertSame instead of assertEquals

app/Models/Wiki/Page.php
Accessing a wiki page in a language that doesn't have a localization of that page (besides the default language) for that language will cause the default `en` version to disappear if both versions are considered expired.
=> Fix disappearing wiki pages

app/Libraries/Search/BeatmapsetSearchRequestParams.php, resources/assets/coffee/react/beatmaps/search-sort.coffee, resources/lang/en/beatmaps.php
closes #2536
Should just work?
Not sure `Favourites` is the best name, though.
=> Allow sorting beatmap listing by favourite count

resources/assets/coffee/_classes/beatmap-helper.coffee
It's been a long time since the color brackets for difficulties were touched. Lots has changed in the star-rating system and community since then. This PR updates the thresholds to reflect that.
To numerically justify this change, I've analyzed every ranked osu!standard beatmap containing one of a number of different difficulty keywords in its version name and plotted them by time vs. difficulty, showing clear striation:
(Outliers include "[**Hard**est](https://osu.ppy.sh/beatmapsets/662526#osu/1402392)" and "[s**hard**ex's Extra](https://osu.ppy.sh/beatmapsets/819112#osu/1720423).") Note that the highest difficulty category is "Extra"—this is practically synonymous with "Expert" as the two terms occupy the same vertical space, but "Extra" is simply used more frequently than "Expert" …
=> Update difficulty color bracket thresholds

webpack.mix.js
Previous `DefinePlugin` weirdness (where an Object gets inserted instead) was caused by `DefinePlugin` not actually being defined in the final config :best:
=> Remove env check in mix build

app/Libraries/Markdown/OsuMarkdown.php, app/Libraries/Markdown/OsuMarkdownProcessor.php
camo uses old url library and it fails to normalize the url properly so it requests `/./` as is instead of normalizing it to `/`.
Ideally camo itself should be fixed to do the url normalization properly. It's rather annoying to test because the tools I tried normalize the url.
=> Fix relative image url

resources/assets/coffee/_classes/user-card.coffee, resources/assets/coffee/main.coffee, resources/assets/lib/user-card-tooltip.tsx
Lookup parameter can be a username and shouldn't be parsed into `number`
closes #4275
=> Fix user card tooltip lookup

app/Libraries/WikiRedirect.php
`$flag` should be an `int` and `(int) true` is `Yaml::DUMP_OBJECT` which does
nothing for `Yaml::parse`.
=> remove useless flag

app/Transformers/ScoreTransformer.php
Named `mode_int` to match the nested beatmap response in `api/v2/beatmaps/{id}/scores`
=> Add mode_int to scores api response

app/Libraries/ChangeUsername.php, app/Libraries/UsernameValidation.php, tests/Libraries/ChangeUsernameTest.php
Does the reserved username validation before the time availability checks.
Fixes the misleading "username will be available in x days" when they're actually not.
Also removes the flaky rank check on inactive users since ranks stop getting updated when they're inactive
=> Change username validation short-circuiting order

app/Http/Controllers/HomeController.php, app/Http/Middleware/SetLocale.php, app/Libraries/AcceptHttpLanguage/Parser.php, app/helpers.php, tests/Libraries/AcceptHttpLanguage/ParserTest.php
Selects a default language from the preferred languages in the `Accept` according to priority, or a compatible one if an exact one can't be found.
Ported from parser part of https://github.com/iain/http_accept_language (so the syntax in the comments are all wrong 🥇)
closes #4194
---
=> Improved accept language detection

app/Libraries/Search/BeatmapsetSearch.php, config/schemas/beatmaps.json
Support prefix search of terms from 3 to 8 characters; if it's not found with 8, it's probably not going to found with more.
Also limits the partial matching of multiple terms to the more relevant fields.
=> Add support for searching on Beatmapset title prefix

resources/assets/less/bem/osu-page.less, resources/views/forum/topics/_post.blade.php, resources/views/forum/topics/show.blade.php, resources/views/home/search.blade.php, resources/views/home/user.blade.php, resources/views/users/posts.blade.php
The gap on both sides were taking too much space away from content on narrower screens, so we decided to remove it.
=> Remove gap between content and edge of screen on mobile layout

app/Http/Controllers/Forum/TopicsController.php, app/Libraries/OsuAuthorize.php, app/Models/Forum/Topic.php, app/Models/Forum/TopicPoll.php, database/migrations/2019_04_01_202237_add_poll_hide_results_to_topics.php, resources/lang/en/forum.php, resources/lang/en/model_validation.php, resources/views/forum/topics/_create_poll.blade.php, resources/views/forum/topics/_poll.blade.php, resources/views/forum/topics/_poll_row.blade.php
suggested in #osu-loved to help prevent bandwagoning or fraud votes
probably a good idea for any poll where the outcome is important
=> Add option to keep forum poll results hidden until the poll ends

.travis.yml, app/Console/Commands/EsCreateSearchBlacklist.php, app/Console/Kernel.php, app/Libraries/Search/BeatmapsetSearch.php
Adds search blacklist support via inline `terms` query.
Currently applies the blacklist to selected fields, but can be made to have different blacklisted keywords for different fields.
Managing the blacklist is currently manual and already set on production.
=> Support search keyword blacklist

resources/assets/lib/notification-widget/item.tsx
Probably more useful than linking to initial post.
=> Link grouped forum topic events to first unread post

resources/assets/coffee/react/mp-history/score.coffee
fixes #4322
Will show `undefined` country in the link but since no flag is rendered, the link isn't visible.
Underlying issue is that having no country set was previously serialized as `country: { code: null, name: null }` but now it's just `country: null`
=> Fix multiplayer match not loading when a user has no country set

app/Transformers/BeatmapsetTransformer.php
Needed for authorization check when the beatmap is deleted.
=> Preload beatmapset in the transformer

resources/assets/coffee/_classes/polyfills.coffee
Polyfills `Event.prototype.composedPath()`; not completely accurate but does what we need it for, at least until it gets implemented in Edge.
=> Simple polyfill for composedPath

app/Http/Controllers/BeatmapsetsController.php, app/Jobs/BroadcastNotification.php, app/Libraries/OsuAuthorize.php, app/Models/Beatmapset.php, app/Models/BeatmapsetEvent.php, app/Models/Notification.php, app/Transformers/BeatmapsetTransformer.php, database/migrations/2019_04_17_103403_add_discussion_locked_to_beatmapsets.php, database/migrations/2019_04_23_051152_add_discussion_locked_to_beatmapset_events.php, resources/assets/coffee/react/beatmap-discussions/discussion.coffee, resources/assets/coffee/react/beatmap-discussions/event.coffee, resources/assets/coffee/react/beatmap-discussions/new-discussion.coffee, resources/assets/coffee/react/beatmap-discussions/nominations.coffee, resources/assets/less/bem/beatmapset-event.less, resources/assets/lib/models/notification.ts, resources/assets/lib/notification-widget/item.tsx, resources/lang/en/authorization.php, resources/lang/en/beatmaps.php, resources/lang/en/beatmapset_events.php, resources/lang/en/notifications.php, routes/web.php
ಠ_ಠ
- only moderators can post on locked beatmap
- generates beatmap event
- generates notification
- requires reason for locking (not actual post, just inlined in the event)
- should name who locked it visible? (it's currently partially visible)
=> Add beatmap discussion lock

resources/assets/coffee/_classes/osu-audio.coffee
aborted playback/loads don't need to be logged
=> Reduce error noise on Sentry from audio player

app/Http/Controllers/RankingController.php
mysql 8.0.16 has an issue where it sees the `where` clauses in the users subquery and thinks that query will be smaller, making it scan and join the entire table.
=> Force query to run smaller subquery first when getting rankings

resources/assets/coffee/_classes/user-card.coffee
Turns out `solo` also changes the behaviour of whether events on the target element trigger keeping a qtip open or not.
=> Fix user card tooltip closing too early

app/Models/Beatmapset.php
fixes this issue when the first nominator is an NAT member and the second nominator is BN on probation
---
=> Count NAT as full BNs when checking for full BN nominations

resources/assets/lib/notification-widget/worker.ts
On showing more, it creates additional connection as there is no check.
=> Fix incorrectly opening multiple websocket connections

tests/Models/BeatmapsetTest.php
additional tests for #4416;
checks limited BNs can't make the qualifying nomination if someone from NAT or BNG has not nominated.
=> Additional beatmapset nomination tests

app/Models/BeatmapMirror.php
As we add more user-run beatmap mirrors, this is a minor security consideration to reduce the amount of data mirrors can collect.
=> Stop sending user_id to beatmap mirror on request

resources/assets/lib/chat/chat-orchestrator.ts, resources/assets/lib/chat/chat-state-store.ts, resources/assets/lib/chat/conversation-view.tsx
Will only be enabled when you scroll to the bottom of a conversation or when you send a message.
There's some weirdness with scroll position occasionally not being reset when switching channels and this will also completely ignore the unread marker, but I'll fix those issues later... for now this should at least make having a conversation less annoying.
=> Re-add autoscrolling behaviour for chat

app/Http/Controllers/Chat/Channels/MessagesController.php, app/Http/Controllers/Chat/ChatController.php, app/Models/Chat/Channel.php, app/Models/Chat/Message.php, app/Models/Chat/UserChannel.php, database/migrations/2019_05_22_041713_add_hidden_to_user_channels.php, resources/assets/less/bem/chat-conversation-list-item.less, resources/assets/less/bem/chat-conversation-list-seperator.less, resources/assets/lib/actions/chat-actions.ts, resources/assets/lib/chat/chat-api.ts, resources/assets/lib/chat/chat-orchestrator.ts, resources/assets/lib/chat/chat-worker.ts, resources/assets/lib/chat/conversation-list-item.tsx, resources/assets/lib/stores/channel-store.ts, tests/Controllers/Chat/ChannelsControllerTest.php, tests/Controllers/Chat/ChatControllerTest.php
Leaving/closing a PM channel will hide it until a new message arrives in the channel.
Messaging the same user again will show the past chat history (if present and not culled), although right now the experience of re-opening a chat is a bit awkward and requires sending a message before the history is reloaded/shown (will fix later™).
=> Add ability to close PMs

app/Console/Commands/ModdingRankCommand.php
Misleading scope name `rankedOrApproved` also includes qualified. Approved state does not need to be considered for this queue (last `approved = 2` beatmap was 2015-08).
=> Fix ranking command considering qualified beatmaps in recent count

app/Console/Commands/FixMissingUserChannels.php, app/Console/Kernel.php
Required to fix missing associations that were the result of channel join/part permissions getting wanged and allowing people to leave PM channels when they shouldn't have been able to.
=> Task to fix missing UserChannels

resources/assets/less/bem/comment.less
Changed the capitalization of permalinks in comments as it isn't fully correct in every language to capitalize the first letter of *every* word.
---
=> Change the capitalization of permalinks in comments

docker/php/Dockerfile
PR:
* Ensures `alpine` is pinned to a specific version. Going off the [hadolint rule](https://github.com/hadolint/hadolint/wiki/DL3007), it's safer to pin it and update the `Dockerfile` with new releases of `alpine`
* Merge the `RUN`s, so that there's only one layer
* Add the `--no-cache` flag so the index isn't cached locally
* Run `rm -rf /var/cache/apk/*` at the end to further reduce the image size
=> pin alpine version + reduce layers + image size

app/Exceptions/API/ChatMessageEmptyException.php, app/Http/Controllers/Chat/Channels/MessagesController.php, app/Http/Controllers/Chat/ChatController.php, app/Models/Chat/Channel.php, resources/assets/lib/chat/chat-api.ts, resources/assets/lib/chat/chat-worker.ts, resources/assets/lib/chat/input-box.tsx, resources/assets/lib/globals.d.ts
Additionally:
- adds behaviour to the prevent sending of messages that appear to be slash-commands.
- adds more leading/trailing space trims to prevent scenarios where blank messages could be sent.
resolves #4550
=> Add chat actions

docker-compose.yml, docker/yarn/Dockerfile
node alpine images don't come with git installed which then causes the package install to fail.
=> Add git to yarn container

resources/assets/coffee/react/profile-page/header.coffee
helps #4516 with Safari.
#4520 doesn't fix it for Safari as it's compositing the banner with the invisible animation layer behind it.
To fix it in Safari, the layer behind the banner needs to be completely removed by using one of the options:
- `display: none`
- unsetting `will-change` and `animation`
- not rendering the loading spinner at all
all of which will break the spinner's fade in/out unless some delayed class changing hacks are used.
This fixes the blurry banner for everyone except the current user by not rendering the spinner if the header is not editable since it doesn't show anyway.
=> Additional blurry tournament banner fixes

app/Http/Controllers/MatchesController.php, app/Libraries/OsuAuthorize.php, app/Models/Multiplayer/Match.php, app/Models/User.php, database/factories/Multiplayer/EventFactory.php, database/factories/Multiplayer/MatchFactory.php, tests/Controllers/MatchesControllerTest.php
A private match that doesn't have 'public match history' enabled requires a user to have participated in the match to view the history.
NOTE: a bancho/client update and manual sql migration is required before this goes live.
fixes #4491
=> Restrict the viewing of history for private matches

app/Models/ChangelogEntry.php
Should fix #4573 though it looks like some fields are marked as non-nullable even though they are.
- `repository`
- `github_url`
- `url`
- `message_html`
Also APIChangelogBuild got typo in it - `VersionNatigation`.
=> Add some defaults for placeholder changelog entry

resources/assets/lib/react-turbolinks.coffee
fixes #4604
Apparently iOS10 can't delete dataset attributes that aren't set yet.
=> Fix empty pages on iOS 10 

webpack.mix.js
This change makes the minified js output workaround more pre-2018 Safari bugs https://bugs.webkit.org/show_bug.cgi?id=171041
fixes #4604 (again)
=> Fix Safari not rendering pages

app/helpers.php
It will point to nowhere but better than completely failing?
=> Add default stream name for older builds

karma.conf.js, webpack.mix.js
By default each entry point has a copy of the webpack runtime; a side-effect of this is that each entry point has its own module cache, meaning imports resolved via different entry points ended up being different instances. This led to things like:
- singletons only being singletons within their entry point instead of app wide.
- Definitions in the same module being considered 'different' resulting in weird things like `[mobx] Cannot obtain atom from [object Object]`, especially if mobx devtools are loaded.
Moving the runtime to `commons` means there's only a single module cache and importing the same module results in the same instance across all entry points. Overall bundle size is also a tiny bit smaller since the runtime isn't duplicated everywhere.
=> Move webpack runtime to commons chunk

yarn.lock
Updates:
- `shopify` 2.5.0 &rarr; 2.6.0
- `mobx` 5.10.1 &rarr; 5.11.0
- `@types/react` 16.8.22 &rarr; 16.8.23
- dependencies' dependencies (also removes redundant ones)
=> More javascript updates and remove unused dependencies

config/sentry.php
When an error isn't an exception, laravel throws its own exception. It's usually dealt by catching it or just letting it be reported by exception handler.
Unfortunately in the latest update sentry also reports non-aborting errors, and as it's different to what laravel throws, it results in either duplicated report or caught report being incorrectly reported (as you can't usually catch non-aborting errors).
=> Fix incorrect sentry report

app/Libraries/Search/BeatmapsetSearchRequestParams.php
`status` was updated to explicitly use strings in #4523 but the comparisons for setting the default sort order weren't updated.
closes #4631
=> Set correct default sort order for beatmap listing

app/Transformers/UserTransformer.php
Make sure array is actually array as `->unique()` may transform array into something that's not quite array.
>>> json_encode(collect(['a','a','b'])->unique()->toArray())
=> "{"0":"a","2":"b"}"
>>> json_encode(collect(['a','a','b'])->unique()->values()->toArray())
=> "["a","b"]"
=> Fix profile page not rendering on users with repeated username change

resources/assets/coffee/react/_components/comment-editor.coffee, resources/assets/coffee/react/beatmap-discussions/new-discussion.coffee, resources/assets/coffee/react/beatmap-discussions/new-reply.coffee, resources/assets/coffee/react/beatmap-discussions/post.coffee
The wording on changelog was confusing - it's not `innerRef` now supports `React.createRef` but instead passing `ref` works as expected.
Fixes #4643.
=> Fix auto focus of some text boxes

resources/assets/less/bem/forum-post.less, resources/views/forum/topics/_post_info.blade.php
".link--white" has lower priority than ".forum-post a". As ".link--white" itself is used somewhere else, add new style instead.
Fixes #4656.
=> Fix user link in mobile forum

app/Models/Beatmapset.php, app/Models/Elasticsearch/UserTrait.php
Because `unique()` may return an associative array instead.
There's a bunch of other places where we should be calling `values()` after `unique()` but they're not affected by the same issue because their result is just passed into a `whereIn` in the query builder which gets the values anyway.
closes #4645
user will show up again after being indexed.
=> Fix users with duplicate previous or reverted usernames not being indexed

resources/assets/less/bem-index.less, resources/assets/less/bem/search-entry.less, resources/assets/less/bem/search-forum-post.less, resources/assets/less/bem/search-result.less, resources/assets/less/bem/search-wiki-page.less, resources/assets/less/bem/user-card.less, resources/views/home/_search_result_wiki_page.blade.php
Fixes neutral grey usages and updates wiki search result design to match forum post results.
Also adds a splash of colour to the search result on-hover outlines.
Side note: the result sections should probably eventually match the site section colours... but right now 3/4 of them (user, forum, beatmaps)  use the same colour, so... _yeeeah_.
=> Search design updates

app/Models/User.php
Fixes #4544.
For cases where the recommended star difficulty would be zero stars, the website now recommends one start.
=> Adjust recommended star difficulty for users with no ranked plays

app/Models/User.php
Previously it was based on how long user has active tag for themselves (including given by others). This changes it to include tags given to others and exclude tags given by others.
Incoming complains from people who mainly receive tags ( '_')a
(they'll still get level 1 at the minimum though)
=> Base user support level on contributed supporter tags

resources/views/master.blade.php
it's already there in metadata template
=> Remove duplicate meta scale element

resources/assets/coffee/osu_common.coffee
=> Only show users as bots in modding discussions when it is their primary usergroup

resources/assets/less/layout.less, resources/assets/less/variables.less, resources/views/layout/metadata.blade.php
This commit makes the website use Microsoft JhengHei instead of Microsoft YaHei for Traditional Chinese (`zh-tw`).
I'm not sure what `Hiragino Sans GB` is, but the equivalent for Traditional Chinese is `Hiragino Sans TC`, apparently.
The glyphs for JhengHei adhere to the standards that Taiwan has put out. In general, the font is lighter and increases readability (in my opinion) for Traditional Chinese.
Note for historical purposes: #3560 is the commit that added the `zh` fonts for both Simplified and Traditional Chinese.
=> Add fonts specific to zh-tw

resources/assets/less/bem/osu-layout.less, resources/assets/less/bem/store-order-item.less
Makes it so the line item doesn't spill off the edge when viewed on narrower widths.
Doesn't do anything about the Xsolla logo as it'd probably have to be made a separate image to move properly
=> Fix store cart wrapping

app/Exceptions/ClassNotFoundException.php, app/Http/Controllers/RankingController.php, app/Http/Controllers/UsersController.php, app/Libraries/Search/BeatmapsetSearchRequestParams.php, app/Models/Beatmap.php, app/Models/Score/Model.php, app/Models/UserStatistics/Model.php, tests/Controllers/BeatmapControllerTest.php, tests/Controllers/RankingsControllerTest.php, tests/Controllers/ScoresControllerTest.php, tests/Models/Score/ModelTest.php, tests/Models/UserStatistics/ModelTest.php
Throws an exception that triggers a 404 if trying to do a lookup with a mode that doesn't have a corresponding model class.
=> Check if score class exists for type

app/Http/Controllers/UsersController.php, routes/web.php, tests/RouteScopesTest.php
Similar to `users/:id/:mode`, it's `me/:mode`
=> Allow setting non-user-default mode for /me

app/Http/Controllers/ChangelogController.php, resources/views/vendor/apidoc/partials/info.blade.php, routes/web.php
The recently added route overlaps with existing route.
This merges both actions and handle the best it can.
=> Fix changelog redirect handling

app/Models/BeatmapDiscussion.php, app/Models/BeatmapDiscussionPost.php, app/Models/BeatmapDiscussionVote.php, app/Transformers/BeatmapDiscussionTransformer.php, database/migrations/2019_08_07_070216_add_last_post_at_to_beatmap_discussions.php, database/migrations/2019_08_07_070216_add_last_reply_at_to_beatmap_discussions.php, resources/assets/coffee/react/beatmap-discussions/discussions.coffee
Should stop editing/deleting/restoring posts from bumping discussions in 'last updated' view.
(also lays the groundwork for some future optimisations)
=> Add new column for beatmap discussion sorting order

resources/assets/less/bem/page-mode-link.less
This thing: ![](https://puu.sh/E2Hx3/dd94cc1b28.png)
=> Fix mode tab using incorrect colours when disabled

resources/assets/lib/user-card-tooltip.tsx
Wrong tooltip gets shown on reused DOM elements since there's already a tooltip bound to them
=> Fix wrong user card tooltip on keyed components

resources/assets/lib/user-card-tooltip.tsx
Fixes navigation dying after a tooltip gets replaced on a reused DOM element.
=> Fix component not unmounted when removing user card tooltip

app/Http/Controllers/Users/ModdingHistoryController.php, app/Libraries/OsuAuthorize.php, app/Models/Beatmap.php, app/Models/BeatmapDiscussion.php, app/Models/BeatmapDiscussionPost.php, database/migrations/2019_08_21_104727_add_index_to_beatmapset_events.php
This replaces the authorisation hotfix from #4804 and adds some further query optimisations to the modding profile page.
As a side-note, this fix means moderators will stop seeing events/discussions/posts from deleted beatmaps/beatmapsets on the modding profile page. (If you need them for moderation/investigation purposes, they'll still be visible under the 'see more' links)
=> Modding profile fixes and optimisations

resources/views/accounts/_edit_entry_simple.blade.php
=> Fix some errors not being shown when editing account settings

resources/assets/coffee/osu_common.coffee
Can't reset attribute by assigning undefined:
someDom.style.backgroundImage = undefined
doesn't do anything.
=> Fix urlPresence to return null on blank/null string

app/Http/Controllers/RankingController.php
before:
```
mysql> explain select * from osu_user_stats FORCE INDEX (rank_score) where exists (select * from `phpbb_users` where `osu_user_stats`.`user_id` = `phpbb_users`.`user_id` and (`user_warnings` = 0 and `user_type` = 0)) and `osu_user_stats`.`country_acronym` = 'KW' order by `rank_score` desc limit 50 offset 2550;
+----+-------------+----------------+------------+--------+------------------------+------------+---------+----------------------------+-------+----------+----------------------------------+
| id | select_type | table          | partitions | type   | possible_keys          | key        | key_len | ref                        | rows  | filtered | Extra                            |
+----+-------------+----------------+------------+--------+------------------------+---------- …
```
=> Revert "force index to make mysql do the smaller query first"

docker/php/Dockerfile
Used by clockwork when set to use sqlite
=> Add pdo_sqlite extension to php container

app/Models/OAuth/Client.php
maybe fixes #4801
```
mysql> explain update `oauth_refresh_tokens` set `revoked` = 1 where `access_token_id` in (select `id` from `oauth_access_tokens` where `user_id` = 2387883 and `client_id` = 5);
+----+--------------------+----------------------+------------+-----------------+-------------------------------------------+---------+---------+------+---------+----------+-------------+
| id | select_type        | table                | partitions | type            | possible_keys                             | key     | key_len | ref  | rows    | filtered | Extra       |
+----+--------------------+----------------------+------------+-----------------+-------------------------------------------+---------+---------+------+---------+----------+-------------+
|  1 | UPDATE             | …
```
=> Faster revoking of refresh tokens when revoking client permissions

package.json, resources/assets/less/app.less, resources/assets/less/variables.less, resources/views/layout/metadata.blade.php, yarn.lock
Revert "Use "Inter" for content font"
This reverts commit 845a0eb34640767f1f17d7b2c80db34336ea9ba6.
(current forum listing pages don't use content font afair)
=> Only use inter for pages using torus

app/Http/Controllers/RankingController.php
When listing the performance ranking, because of the sub select, mysql is deciding to query the entire users table first:
```
mysql> explain select * from osu_user_stats where exists (select * from `phpbb_users` where `osu_user_stats`.`user_id` = `phpbb_users`.`user_id` and (`user_warnings` = 0 and `user_type` = 0)) order by `rank_score` desc limit 50 offset 2550;
+----+-------------+----------------+------------+--------+------------------------+---------+---------+-------------------------+----------+----------+----------------------------------------------+
| id | select_type | table          | partitions | type   | possible_keys          | key     | key_len | ref                     | rows     | filtered | Extra                                        | …
```
=> Force better indices when listing rankings

resources/assets/less/bem/nav2-header.less, resources/assets/less/bem/nav2.less, resources/assets/less/bem/navbar-mobile.less, resources/assets/less/variables.less
- nav2 is inside nav2-header so the z-index in nav2 isn't really useful and doesn't quite work for non-legacy menu when combined with another floating header: the background will be underneath the additional floating header while the menu on top of everything
- change navbar-mobile to use the same z-index as nav2-header. Should be fine. Maybe
Previous:
```
[nav2-header: z-index 500]
[nav2-header body]
[nav2-header menubg] ← underneath sticky header when nav2 popup menu is shown
[nav2: z-index 501] ← popup menu on top of sticky header
[sticky header]
```
New:
```
[nav2-header: z-index 500]
[nav2-header body: z-index 1]
[nav2-header menubg]
[nav2]
[sticky header]
```
=> Adjust header z-index

resources/assets/less/variables.less
Will be needed for full screen reply box. They shouldn't overlap in normal case.
=> Set fixed bar z-index above nav bar

resources/views/beatmapsets/show.blade.php
when both are in the same line, it's a lot more common to read _artist - title_ instead of _title - artist_ (current)
also fixes the inconsistent formats in discord embeds (line 1 is t-a, line 2 is a-t)
was going to submit as an issue but the change is so simple that i might as well pr
=> Switch song title and artist in page title

app/Http/Controllers/UsersController.php
Use empty string instead of null if post data is missing. 
Most of the username validation methods are typed not to allow null, so this change will make it return a validation error response.
=> Change default username check to use empty string

resources/assets/lib/news-show/main.tsx
fixes #4781
`<audio>` doesn't have a volume attribute, go figure. 🤷‍♂
=> Set volume of audio tags within news posts to 45% on page load

app/Http/Kernel.php, app/Http/Middleware/DatadogMetrics.php
Lets us see request-time at a per-action level
=> Add action tag to Datadog request-time metrics

app/Libraries/MorphMap.php
The class really should be called BeatmapsetDiscussion.
Actual column update will be done separately as it should still work with full class name.
Currently used by KudosuHistory.
=> Add polymorphic mapping name for BeatmapDiscussion

resources/assets/less/bem/btn-osu-big.less
This makes the upload image button grow to as large as it needs, but keeping a minimum size of `@avatar-size--base`.
It fixes #5016
This might cause issues with design consistency, though.
=> "Automatic" width for upload image button

app/Http/Controllers/OAuth/ClientsController.php
Just don't show the client instead of having `revoked: true`. This brings the behaviour in-line with the one on the account settings page.
=> Exclude revoked OAuth clients from client list

app/Models/Beatmapset.php, app/Models/UserScoreable.php, app/helpers.php
closes #5039 
Allows at most one caller to run the cache remember callback within the duration of the lock.
It's not a direct drop in replacement for `cache_remember_with_fallback` as callers will need to handle the case where the value doesn't exist yet instead of assuming the callback always runs.
`cache()->add()` is conveniently atomic so there shouldn't be any race conditions unlike getting and setting keys across multiple calls.
There are more efficient and lower latency ways to implement this using `set ex nx`, `mutli` and `ttl` but that involves a bit more low level handling
=> Add version of Cache::remember with callback mutex

app/Http/Controllers/ArtistsController.php
MySQL doesn't support repositioning null values and laravel has been silently converting it to desc (and they changed it in 5.8 to throw error instead).
=> Fix featured artist tracks sort order

tests/Libraries/Fulfillments/FulfillmentFactoryTest.php, tests/Libraries/Fulfillments/UsernameChangeFulfillmentTest.php
Annotation for exception assertion is deprecated in [phpunit 8](https://phpunit.de/announcements/phpunit-8.html).
=> Use expectException function instead of annotation

bin/phpunit
Use shell script instead of php for preloading framework override before starting test. They added this ability in 7.4.
Also it fixes problem in phpunit 8 as the start script can't be run using `require` because of `strict_types` declaration being on second line.
As a bonus, it removes the appearance of shebang line in test due to how `require` works.
=> Improve phpunit wrapper

webpack.mix.js
Having one server generate sourcemap and the other not will result in different files being generated.
So generate them everywhere to make sure compiled files have same hash and stuff.
=> Always generate sourcemap

app/Http/Controllers/ArtistsController.php, app/Models/Artist.php, app/Models/ArtistAlbum.php, app/Models/ArtistTrack.php, app/Transformers/ArtistAlbumTransformer.php, app/Transformers/ArtistTrackTransformer.php, resources/assets/coffee/react/_components/track-preview.coffee, resources/assets/coffee/react/_components/tracklist-track.coffee, resources/assets/less/bem-index.less, resources/assets/less/bem/artist-album.less, resources/assets/less/bem/artist-sidebar-album.less, resources/assets/less/bem/artist.less, resources/assets/less/bem/pill-badge.less, resources/assets/less/bem/tracklist.less, resources/lang/en/common.php, resources/views/artists/index.blade.php, resources/views/artists/show.blade.php
Few tweaks to the pages:
Artist Listing:
- Adds a 'new' badge and glow effect to artists that have had new tracks added in the last month (or who are new featured artists)
Artist Page:
- Adds a 'new' badge and glow effect to albums added within the last month (in headers+sidebar)
- Adds a 'new' badge to tracks added within the last month
- Change sort order of albums to show the latest at the top
- Change sort order of tracks (singles/outside albums) to show the latest at the top
- Adds cover image fallback for tracks that don't have covers defined (uses album cover if present, otherwise falls back to artist profile image)
resolves #5046
=> Featured Artists pages updates

app/Http/Controllers/Users/ModdingHistoryController.php, app/Http/Controllers/UsersController.php, app/Transformers/UserStatisticsTransformer.php, resources/assets/coffee/react/profile-page/rank-count.coffee
prefer grade_counts instead; closes #5025.
It doesn't do anything about events still using `XH` instead of `ssh` or any of the css names
=> Remove scoreRanks from user statistics response

app/Transformers/BeatmapDiscussionTransformer.php
Having votes summary in otherwise empty object (deleted discussion) confuses the filter. Resolves #4988.
=> Hide votes summary for deleted discussions

app/Http/Controllers/StoreController.php, app/Models/Store/Product.php
~~It stops overriding in laravel 6 it seems.~~ They added eloquent builder function with same name in 5.7 so it takes higher priority. Previously it was only in query builder.
=> Rename scope to not override laravel builtin

resources/assets/lib/turbolinks-reload.ts
`TurbolinksReload.load` should return true if loading a new script. Previously, this was returned implicitly due to coffeescript.
=> Fix Xsolla payment widget not working

resources/views/beatmapset_events/_item.blade.php
Laravel 6 route doesn't allow null value if the route parameter is required, but is fine with it if
the parameter is keyed with the parameter name; then it generates the
same route as 5.5 did.
A proper fix is to not have the link if the beatmapset is null, but fixing that is a bit more involved than this
=> Hotfix route generation for null beatmapset on modding event.

app/Http/Controllers/Payments/PaypalController.php
It didn't work previously (405 after first redirect) and it doesn't work at the moment (exploding thanks to null order) and not sure if the fix should be redirecting to cart or just 404.
=> Fix error on invalid parameter on paypal decline

app/Http/Controllers/RankingController.php, resources/views/vendor/apidoc/partials/info.blade.php
includes total and next page as a cursor value in the response. Cursor is `null` if there are no more pages.
closes #4917
now returns
```json
{
"cursor": {
"page": 2
},
"ranking": [...stats in rank order],
"total": 1243
}
```
=> Include total and cursor in ranking api response

resources/assets/coffee/react/beatmapset-page/header.coffee
Workaround for older library no longer needed.
Fixes #5090.
=> Fix double escaping of beatmap search

app/Http/Controllers/BeatmapDiscussionPostsController.php, app/Models/BeatmapDiscussionPost.php, resources/views/beatmap_discussion_posts/index.blade.php, resources/views/objects/_pagination_simple.blade.php
- preload being broken after update to laravel 6
- it has been pretty slow mainly thanks to counting the total, so I switched it to pagination-without-total
=> Fix beatmap discussion post listing

app/Models/Beatmapset.php
It may delete no row so use the return of `delete()` call instead.
=> Correctly decrement user favourite count

app/Transformers/CommentTransformer.php
Missing from #4872; otherwise there's no markdown to parse
=> Include comment message markdown in response

resources/assets/lib/beatmaps/beatmapset-search-controller.ts
Possibly another leftover from old routing library can't escape things.
=> Fix double escaping of beatmap search url

resources/assets/less/bem/nav2-header.less, resources/views/master.blade.php
Edge doesn't seem to like `calc()` within `hue-rotate()`
fixes #5118
=> Fix header image colour in Edge

app/Events/BeatmapsetDiscussionQualifiedProblemNotificationEvent.php, app/Events/NewNotificationEvent.php, app/Events/NewPrivateNotificationEvent.php, app/Events/NotificationEventBase.php, app/Events/UserSubscriptionChangeEvent.php, app/Http/Controllers/BeatmapDiscussionPostsController.php, app/Jobs/BroadcastNotification.php, app/Models/Notification.php, database/factories/UserFactory.php, resources/assets/lib/notification-maps/category.ts, resources/assets/lib/notification-maps/icons.ts, resources/assets/lib/notification-maps/url.ts, resources/lang/en/notifications.php, tests/Controllers/BeatmapDiscussionPostsControllerTest.php
requires
First step for #4784.
Just sends a notification to BNs and NATs when a problem is posted on a qualified beatmapset. There are no options for it yet.
=> Send notification to NATs and BNs when a problem is posted on a qualified beatmap

config/osu.php, resources/assets/less/bem/landing-footer-social.less, resources/views/home/landing.blade.php, resources/views/layout/_nav2.blade.php
- We don't update the facebook page near as often as we should.
- We can use extra header space.
- Facebook just generally sucks.
=> Remove facebook link from header

app/Http/Controllers/BeatmapDiscussionPostsController.php, tests/Controllers/BeatmapDiscussionPostsControllerTest.php
Only notify new problem if there's no currently open problems.
The whole thing should probably be moved out of controller.
=> Limit notification of new problem on qualified maps

resources/assets/less/bem/artist.less, resources/views/artists/index.blade.php
lets the name overflow instead
(hopefully this should be a rare occurrence and we don't end up with a page of overlapping artist names...)
=> Prevent long artist names from breaking the featured-artist index/grid alignment

app/Http/Controllers/UsersController.php
Resolves #5202. 
Because catching nonexistent class is not an error.
=> Import correct exception class

resources/assets/less/bem/beatmap-discussion-post.less, resources/assets/less/bem/beatmap-discussions-user-filter.less, resources/assets/less/bem/modding-profile-vote-card.less, resources/assets/less/bem/user-group-badge.less, resources/assets/less/colors.less
Figured it was worthwhile after seeing how many places we've duplicated this logic in.
Not sure about whether the group names should live in `user-group-badge.less` or not though...(should eventually stop being defined in CSS anyway... right?)
=> Create helper to make using group colours less tedious.

app/Http/Middleware/AuthApi.php, tests/Controllers/CommentsControllerTest.php
closes #5225
Adding the path and method check is currently the easiest way, but probably not what we want to keep doing in the future.
=> Allow guest access to comments via API

.travis.yml
When elasticsearch starts booting, the port is not open yet, which causes connection refused to get returned immediately. wget defaults to 20 retries and with `--waitretry=1` it was pretty much always only waiting for about 20 seconds, ignoring the other timeout value 🥇
=> Fix travis giving up too early waiting for elasticsearch to start

app/Libraries/UserVerification.php
Static variable "cache"s stay across tests.
=> Fix user verification instance cache

webpack.config.js, webpack.mix.js
fixes issue with #5240
The `mix` config is loaded during `require(Mix.paths.mix())`, so that needs to be done after the locale files are built, otherwise mix can't find them. This fix delays the loading until the promise is ready to be resolved.
(the issue didn't happen if the files from a previous build already existed)
=> Fix locale files not being resolved in mix build

app/Models/User.php
Accessing relation using `->relation` already caches it.
=> Simplify user model's friend/block caching

app/Models/BeatmapDiscussion.php
The migration to the short name has been completed so the full name doesn't need to be included anymore.
=> Update kudosu counting query

app/Exceptions/UserVerificationException.php, app/Http/Controllers/AccountController.php, app/Libraries/UserVerification.php
- as it turned out empty string is empty, so cast to integer first
- use message key instead of its translation
=> Less confusing verification log

app/Libraries/AuthorizationResult.php, app/Libraries/OsuAuthorize.php, resources/lang/en/authorization.php, tests/Controllers/ForumTopicsControllerTest.php
The message will be a bit confusing in some places as there's currently no way to manually trigger verification...
=> Fix wrong exception being thrown from authorization check

app/Models/Chat/Channel.php, phpunit.xml
This also changes the order of precedence a bit, meaning invalid messages will now also count towards the limit
=> Use Redis instead of DB for chat message throttling

app/Jobs/BroadcastNotification.php
This is the closest thing I can see on causing issue #5380.
If I remember correctly it's done to make sure the ids are valid but it's probably fine to skip it as it shouldn't cause too much harm and the number may get pretty big and thus will take a while to finish (if at all).
=> Skip fetching user details when generating notifications

app/Http/Controllers/Chat/ChannelsController.php, app/Http/Controllers/LegacyInterOpController.php, app/Models/Chat/UserChannel.php, routes/web.php
Also adds a LIO endpoint for batch marking channels as read (for bancho).
This is mainly to fix the issue where players chat a bunch in-game, then later load up the website to a bunch of notifications for the conversations they had earlier in-game.
There's some known-issues with mark-as-read for chat on the web, but they will be fixed separately:
- when initially loading the chat page, a mark-as-read for the starting channel is not always sent
- while actively looking at a channel, mark-as-read isn't always sent reliably
(this partially addresses #4896, but needs the above needs to be fixed before the issue can be closed)
=> Clears notifications when a channel/pm is marked as read

app/Transformers/BeatmapsetTransformer.php
Apparently tournament client requires this or something.
=> Put back bpm in beatmapset api

app/Models/Chat/Channel.php
Should be using the markAsRead function instead of manually updating user channel
=> Correctly trigger mark-as-read behaviour on message send

app/helpers.php, composer.json, composer.lock, resources/views/beatmapset_events/_item.blade.php
- routing fixes (hopefully all of them)
- more updates
~~Transaction manager needs some fixing as laravel/framework#30883 changed the transaction level on commit event.~~ Temporarily lock laravel to 6.8.0.
=> Laravel fixes

app/Libraries/Search/WikiSearch.php
After fixing caching 404, those caches end up included in search because the path now matches.
Resolves #5366.
=> Filter out blank pages from wiki search

resources/assets/coffee/_classes/sticky-header.coffee
Some arbitrary low number because it's kind of per-design specific. I think ideally it should be (`header_height - ((menu_height - overlap_allowance) + title_height)`) except there's no specific number defined for `title_height` and `overlap_allowance`\* at the moment.
\* `overlap_allowance` is the transparent bottom part of the menu.
=> Fix header menu and title overlap

app/Http/Middleware/AuthApi.php, app/Http/Middleware/VerifyUserAlways.php
API auth middleware is run after global middleware so the one in VerifyUserAlways (global) has been doing nothing.
Resolves https://github.com/ppy/osu/issues/7341.
=> Fix marking api sessions verified

app/Http/Middleware/DatadogMetrics.php
Avoids case where laravel tries to `mb_strpos` a non-string without checking if it's a string
=> Assume controller is already resolved or null when sending performance metrics

app/Http/Middleware/AuthApi.php
closes #5378
Also fixes user always being null on API endpoints that don't require authentication.
=> Fix user_votes not included in comments API response

app/Models/LoginAttempt.php
Looks like there's an unexpected error when saving the record but not sure what because it's caught but not handled.
=> Prevent null when fetching login attempt record

webpack.mix.js
Just setting it in webpackConfig doesn't work for css as the loaders need to be passed similar options and mix only passes it if we call `.sourceMaps()` to it.
devtool in webpackConfig is redundant as sourceMaps also set whatever it's getting as default config. Except the dev default (eval-source-map) is not working for css files so it needs to be set to the correct type.
Also explicitly set the type for production so they are always the same between environments and not rely on defaults.
=> Generate sourcemaps for css files

app/Models/UserStatistics/Fruits.php, app/Models/UserStatistics/Mania.php, app/Models/UserStatistics/Model.php, app/Models/UserStatistics/Osu.php, app/Models/UserStatistics/Taiko.php, app/Transformers/UserStatisticsTransformer.php, resources/views/rankings/_spotlight_rankings_table.blade.php
closes #5252
Adds new attribute that uses `accuracy` if `accuracy_new` doesn't exist.
Not sure if should just change all uses of `accuracy_new` to `hit_accuracy`, though
=> Fix missing hit_accuracy in spotlight ranking API

resources/views/vendor/apidoc/partials/route.blade.php
Didn't notice this when upgrading the docs generator library. Good job, me '_')b
=> Fix missing route description in apidoc

database/migrations/2020_01_20_031913_json_news_post_page.php
TEXT is sometimes barely enough. It's not enough for the latest post (spotlight 2019 autumn) when the camo hostname is a bit long (22 characters in my case).
And dbal can't handle JSON datatype.
=> Use JSON datatype for news page

resources/assets/less/bem/wiki-main-page.less
50% in grid ignores the gap size so it overflows by 7px (the gap).
=> Fix wiki panel size

resources/assets/coffee/react/modding-profile/header.coffee
closes #5579
modding profile page doesn't have `currentMode`
=> Fix missing game mode when linking from modding profile

app/Models/Wiki/Page.php
If a request to wiki page with the wrong casing is made before the actual page is indexed, the redirect lookup may end up getting the wrong document as the closest match
closes #5512
=> Fix wiki redirecting to empty page

app/Models/UserScoreable.php
Add `score_id` aggregate and sort by it between scores with same pp. Resolves #5382.
=> Fix sort order of personal best performance

app/Models/NewsPost.php
It doesn't generate error on normal operation. Any errors will need to be fixed right way.
=> Don't catch errors on news sync

resources/views/vendor/apidoc/partials/info.blade.php
Forgot about this yesterday when updating the json responses.
=> Add breaking change note for beatmap and build stream json response update

app/Libraries/Elasticsearch/SearchParams.php, app/Libraries/Search/BeatmapsetSearchRequestParams.php, app/Libraries/Search/ForumSearchRequestParams.php, app/Libraries/Search/PostSearchRequestParams.php, app/Libraries/Search/UserSearchRequestParams.php, app/Libraries/Search/WikiSearchParams.php, app/Libraries/Search/WikiSuggestionsParams.php
broken by #5541
Fixes best performance showing empty when cache gets refreshed after being viewed by a guest .
Also moving the overrides to the params classes for requests since non-request params should be useable without any authentication (e.g. in when console)
defaulting `isLoginRequired` to `true` was not the best idea (・_・ヾ
=> Fix user best performance returning empty

app/Http/Controllers/CommentsController.php, resources/docs/source/includes/_structures.md
Type for `pinned` field is a lie until #5648 is merged.
=> Update comment API documentation

resources/assets/coffee/_classes/nav2.coffee, resources/assets/lib/click-menu.ts
Only hide blackout if the menu was previously shown.
Should fix #5656.
=> Fix event handler for mobile menu hiding too many blackouts

resources/assets/lib/beatmap-discussions/disable-tokenizers-plugin.ts, resources/assets/lib/beatmap-discussions/review-post.tsx
The previous parser settings would cull nodes that used disabled markdown features instead of just rendering the source/unformatted text.
This change will just leave the Markdown raw unless it's one of the enabled features.
Feels kinda silly that I have to implement this as a plugin that overrides the core tokenizers... 🤷‍♂
=> Change how the Markdown within beatmap discussion reviews are rendered

resources/assets/lib/beatmap-discussions/autolink-plugin.ts, resources/assets/lib/beatmap-discussions/review-post.tsx, resources/assets/lib/globals.d.ts
Changed to ignore markdown-formatted links and instead autolinks urls that appear instead.
=> Change handling of urls within beatmap discussion reviews

resources/lang/en/layout.php
Recent change to footer link missed translation update.
=> Fix missing translation on landing page footer

database/migrations/2020_03_09_100459_remove_multiplayer_rooms_high_accuracy_precision.php
It died if the aggregate accuracy of plays went over 9.9999 because of the precision set on the column; this is already fixed on production
ref: ppy/osu#8062
=> Fix error when submitting score in multiplayer rooms

resources/assets/coffee/react/_components/beatmapset-mapping.coffee, resources/assets/less/bem/beatmapset-mapping.less, resources/lang/en/beatmapsets.php
Change beatmap mapping details translation keys to force them to stop using the old translations without variables.
=> Fix translated dates not showing on beatmap info 

resources/lang/en/page_title.php
Resolves #5745. I'm not sure if it's the correct title.
=> Add missing title for multiplayer match page

phpunit.xml
Fewer random failures and it should be explicitly set on related tests (which doesn't exist at the moment?).
=> Disable all id-specific forums on test

resources/assets/less/variables.less
It covers a bit more character sets compared to Torus and looks good enough in case of Cyrillic script.
=> Add Inter as default fallback font

resources/assets/coffee/react/beatmaps/search-panel.coffee
Fixes input composition events firing too often on safari.
closes #5766
=> Fix IME input on beatmap listing

app/Models/Beatmapset.php, resources/assets/coffee/react/beatmap-discussions/nominations.coffee, resources/lang/en/model_validation.php
Validation magic convenience. Except it's not used in the other place.
Resolves #5696.
=> Check discussion lock status on hype validation

app/Http/Controllers/WikiController.php, app/Models/Wiki/Page.php, resources/views/wiki/_notice.blade.php, resources/views/wiki/show.blade.php
As it turned out we're already fetching the parent page on every requests so I just save that somewhere and use it for subtitle (parent title).
Resolves #5511.
=> Show correct wiki parent page title

app/Http/Controllers/ClientVerificationsController.php, app/Models/UserClient.php, resources/assets/less/bem/dialog-form.less, resources/lang/en/common.php, resources/lang/en/layout.php, resources/lang/en/page_title.php, resources/views/client_verifications/create.blade.php, tests/Controllers/ClientVerificationsControllerTest.php
There's timing issue when multiple verifications of same client sent at the same time. And the button should be disabled on submit.
Moved exceptions around to skip manually handling errors.
=> Fix duplicated client verification submission error

bin/db_setup.sh
The script is run in weird way (presumably to skip exporting variables?) and result in the main shell having nounset and errexit set, breaking the init script.
The script is simple enough already so the options aren't really needed.
Should resolve #5809.
=> Fix script used by docker

tests/Controllers/SessionsControllerTest.php
In `SessionsControllerTest::testLoginInactiveUser` the created user has random country but ForceReactivation class detects the request country as `null`. Null obviously doesn't match with the user's country and it redirects to password reset page so the test fails.
If you need to test if the created user has the same country as the request, there should be a new testcase for that.
How on earth does this test pass on your setups?
_I run tests from inside of the container with `bin/phpunit -d memory_limit=-1`_
=> Fix country mismatch in inactive user test

app/Http/Controllers/LegacyInterOpController.php, routes/web.php
- regenerating covers now also indexes, `regenerate-beatmapset-covers/{beatmapset}` renamed to `index-beatmapset/{beatmapset}`
- deletes from index if soft-deleted
=> Add _lio endpoint for indexing beatmapsets

app/Transformers/UserCompactTransformer.php
I felt like I forgotten a case when looking at storing that instance variable. And it's this one.
Resolves #5866.
=> Fix wrong profile customisation being used in transformer

app/Models/Beatmapset.php, resources/assets/lib/beatmapsets-show/metadata-editor.tsx, resources/lang/en/model_validation.php
Resolves #5850.
I was thinking adding column like `settable` to indicate whether it can be used for beatmapset but I couldn't find a good name so it's id-based for now. Id 0 is kind of special already so it should be fine...? 🤷‍♂ 
Also fixed validation message.
=> Prevent language/genre Any from being set

resources/lang/en/community.php
remove mention of friends list rankings not working, because it does.
Will change store page from:
https://i.imgur.com/xqvCR7A.png
to
https://i.imgur.com/sWE9kti.png
=> Update the store page

resources/assets/app.js, resources/assets/coffee/jquery-prefilter.coffee
It was backported from 3.x when using 2.x. Already updated to 3.x so the patch is not needed anymore.
=> Remove jQuery prefilter patch

app/Libraries/Elasticsearch/FunctionScore.php, app/Libraries/Search/BeatmapsetSearch.php
closes #5681
I was going to include `play_count` into the scoring as well, but that doesn't get updated in the index since we stopped doing a full reindex
There looks like a more suitable `rank_feature` type in elasticsearch 7 for handling this, but other changes need to be done before we can move to it.
=> Include beatmap favourite count in search scoring

resources/assets/less/bem/profile-detail-bar.less
Resolves #5713.
...except not really. The original reported bug has been (accidentally) fixed in #5653.
This PR further fixes the height change that occurs when toggling rank detail view due to one of the bar contents being slightly taller than expected. That pushes the entire container height when it's rendered, resulting in the buttons being moved around.
and resolves #5775
=> Adjust height of profile page detail bar

app/helpers.php, resources/assets/coffee/_classes/timeago.coffee, resources/assets/coffee/_classes/tooltip-default.coffee, resources/assets/coffee/osu_common.coffee, resources/assets/coffee/react/_components/beatmapset-mapping.coffee, resources/assets/less/bem/beatmapset-mapping.less, resources/assets/lib/time-with-tooltip.tsx
- cuts off at 4 weeks
- add `timeago` support to `TimeWithTooltip`
- switch to react component for rendering
closes #5682
=> Add cutoff for showing relative time in beatmap info

app/Http/Controllers/ContestEntriesController.php, app/Traits/Uploadable.php, resources/assets/coffee/react/contest-entry/uploader.coffee
PHP was running out of memory while checking the mimetype of uploaded files (see: OSU-WEB-7B1 on sentry)
This should fix that (reference: https://laravel.com/docs/6.x/filesystem#storing-files).
One side effect will probably be that mimetypes are detected via file extension instead of file content, but that's probably... acceptable? 🤷‍♂️
(also bumps up the size limits for contest entries)
=> Change Uploadable to use file streams for uploads

app/Libraries/Search/BeatmapsetSearch.php
0 favorites shouldn't cause the relevancy score to be 0.
Found this when checking for #5956 but I'm not sure if this alone will fix the issue.
=> Fix beatmaps search relevancy score weighting

package.json, yarn.lock
This one is mainly to update the vulnerable dependencies of dependencies. Using the hints I gathered over this week.
- karma and karma-typescript are updated to the latest version (no way around this)
- some of the dependencies have been updated by manually removing their entries in `yarn.lock` ([based on this tips](https://github.com/yarnpkg/yarn/issues/4986#issuecomment-395036563)
- deduplicated dependencies using [yarn-deduplicate](https://github.com/atlassian/yarn-deduplicate) (this also updated some direct dependencies)
=> Update some nodejs dependencies

app/Events/UserSubscriptionChangeEvent.php
This is so existing events already in the queue can be deserialized and processed
=> Temporarily restore UserSubscriptionChangeEvent

app/helpers.php, resources/assets/less/colors.less, resources/assets/less/sections.less
Maps the menu colours to the same ones as in the `section_to_hue_map` function.
`darkorange` was only defined in the `$colourToHue` array and found no mention of it in the Colour Palette, but I added it in `colors.less` ; was it the right thing to do?
Resolve #5984.
=> Match the header menu items colours with the sections colours

resources/assets/lib/popup-menu-persistent.tsx
Children can be passed as part of props so the whole thing can be simplified.
=> Clean up PopupMenuPersistent

app/Libraries/ModdingHistoryEventsBundle.php, app/Models/BeatmapsetEvent.php, resources/assets/coffee/react/modding-profile/events.coffee, resources/assets/lib/beatmap-discussions/event.tsx, resources/assets/lib/beatmap-discussions/events.tsx
caused by #5963; the query builder causing the issue didn't change but ended up used in a condition that doesn't work very well.
- `BeatmapDiscussionPost::scopeVisible()` should not be called without filtering by `user_id`, and especially not when the condition has `whereHas('user' ...->default())`. The discussion post listing didn't use `visible()` to filter so it didn't have the same issue.
- posts not actually needed on listing page, so no longer fetched
Turns out the implicit `deleted_at` and `active` global scopes on `Beatmapset` has no index covering them making `whereHas('beatmapset')` not so great to use; if only one condition is included, it's fine, but having both is bad. 
Then there's inconsistency where `BeatmapDiscussion::beatmapset()` includes `withTrashed()` but …
=> Fix slow beatmap events listing

app/Http/Controllers/ScoresController.php, app/Models/Score/Best/Model.php, resources/assets/less/bem/score-beatmap.less, resources/assets/less/bem/score-dial.less
- more accurate rank calculation (resolves #6035)
- disable hidden scores
- more centered score grade
The accurate score rank calculation used to be rather slow but it should be fine now after denormalizing `hidden` column and updating index?
=> Score detail page fixes

app/Http/Controllers/SessionsController.php, tests/Controllers/SessionsControllerTest.php
To differentiate between missing parameter and actual auth fail requests.
=> Update auth failure status code to 403

app/Models/Chat/UserChannel.php, tests/Controllers/Chat/ChatControllerTest.php
Tests fixes from #6057
Also reset `OsuAuthorize` cache between requests, otherwise it uses the existing result instead of actually checking again.
=> Add additional test when sending message to previously closed PM

resources/assets/less/colors.less
Thanks to `hsl` (and `hsla`) function accepting single variable for its first _n_ parameters, we can do tricks like `hsl(var(--hsl-pink-1))` and `hsla(var(--hsl-pink-1), 0.5)`.
To be used to fix comment clipping fadeout in safari.
Additionally this will make it easier to mess around with colour in web inspector (just put in the name instead of figuring out the correct percentages etc).
Thankfully this still works with `osu-hsla` so no other change is needed.
Maybe in the future we can remove the less variables (and `osu-hsla` function) completely and use `hsl(var(--hsl-x))` directly instead?
=> Move raw colour HSL values to CSS variable

resources/assets/less/bem/comment.less, resources/assets/less/bem/comments.less, resources/assets/less/bem/osu-page.less
Fade colour from correct transparent bg colour instead of transparent black (?).
Fixes this:
=> Fix comment clipping fadeout in Safari

app/Http/Controllers/Multiplayer/Rooms/Playlist/ScoresController.php, app/Models/Multiplayer/PlaylistItem.php, app/Models/Multiplayer/PlaylistItemUserHighScore.php, database/migrations/2020_05_28_072624_add_multiplayer_scores_high_top_scores_index.php, routes/web.php, tests/api_routes.json
Scores are returned in `total_score` descending order, with submission order tiebreaker.
No pagination yet.
- <del>add migration `2020_05_28_072624_add_multiplayer_scores_high_top_scores_index` </del> small enough should be fine being done during deploy (-nanaya)
```
alter table `multiplayer_scores_high` add index `top_scores`(`playlist_item_id`, total_score DESC, `score_id`);
```
=> Add endpoint returning playlist item's scores

resources/assets/lib/beatmap-discussions/editor-discussion-component.tsx, resources/assets/lib/beatmap-discussions/editor.tsx
Also now handles the case where references to a deleted beatmap are pasted in
fixes #6110 (regression caused by #6103)
=> Ensure deleted beatmaps aren't selected by default in a review (attempt 2)

app/Http/Controllers/ChatController.php, app/Libraries/Chat.php, app/Models/Chat/Channel.php, tests/Libraries/ChatTest.php
Found this when working on a different issue.
Also `DB::transaction` only works for default database which `Channel` model isn't using.
=> Don't save new PM channel if message is not sent

app/Http/Controllers/Chat/ChannelsController.php, app/Libraries/Chat.php, app/Models/Chat/Channel.php, app/Transformers/Chat/ChannelTransformer.php, resources/docs/source/includes/_structures.md, routes/web.php, tests/Controllers/Chat/ChannelsControllerTest.php, tests/api_routes.json
Resolves #6105.
`join` sounds like a better name but it already exists and there's no way to re-purpose that for this as it requires `channel_id` which not known.
A blank channel data will be returned if there's no existing channel. Not sure if it makes sense but an empty response doesn't sound much better either :thinking: 
The alternative is to include `hidden` channels in presence?
=> Add endpoint to rejoin PM channel

resources/assets/lib/beatmap-discussions/editor-helpers.ts
`currentMarks` could sometimes end up with `undefined` props, so the next node could incorrectly check `undefined !== false` and add more asterisks.
can be tested in modding review paragraph with 3 words, first italics, second normal, third bold.
=> Fix broken bold/italic on slate serialization

tests/Libraries/BeatmapsetDiscussionReviewTest.php
I missed some more in my previous fix, causing the test to still randomly fail.
=> Update factory for creating qualified beatmapset

app/Http/Controllers/Chat/ChannelsController.php, app/Transformers/Chat/ChannelTransformer.php
So client can just pass it the same way as ChatMessage from other responses.
=> Include sender in Channel#store recent_messages

app/Http/Controllers/BeatmapDiscussionsController.php, app/Libraries/ModdingHistoryEventsBundle.php, resources/assets/coffee/react/beatmap-discussions-history.coffee, resources/assets/coffee/react/beatmap-discussions-history/main.coffee, resources/assets/coffee/react/modding-profile.coffee, resources/assets/coffee/react/modding-profile/main.coffee, resources/assets/lib/beatmap-discussions/editor.tsx
The selector was erroneously showing all beatmaps that were loaded on the modding profile/history page in every editor (i.e. dropdown selectors were not limited to the review's beatmapset)... this also meant that beatmaps that weren't referenced didn't appear in the selectors either.
Both these issues are fixed by this PR.
(Server-side validation would have rejected any invalid reviews that were submitted in the meantime however)
fixes #6086
=> Fix review beatmap selector on the modding profile/history pages

database/migrations/2020_05_15_083037_sync_structure.php
This isn't full sync (as in it won't generate 0 diff between dev and prod dump) but should be pretty close.
Could be cleaned up further but not sure if worth it 🤷 
I kind of suspect this won't work on people's existing dev db. Sure could use some test on that.
Differences:
- character set and collation dump cleanup (see below)
- most of the partitions aren't copied over (some are rolloing so it's pointless trying to copy that)
- some unused tables (for osu-web) aren't copied over
- additional manual changes are needed on prod (see below)
- `osu_mirrors` has interesting default value on prod
Dump cleanup: (vim command)
```
:%s/ CHARACTER SET utf8mb4 / /g
:%s/ CHARACTER SET utf8mb4,/,/g
:%s/ CHARACTER SET utf8 / /g
:%s/ CHARACTER SET utf8,/,/g
:%s/ COLLATE utf8mb4_0900_ai_ci / /g
:%s/ …
```
=> Synchronize database schema with production

docker-compose.yml
Prevents accidentally creating unaliased indices with the wrong schema.
=> Disable docker elasticsearch index auto creation

app/Http/Controllers/Forum/TopicsController.php, app/Models/Forum/Topic.php, app/helpers.php
Recycling unicode trim from topic. Probably should update `string_split` to exclude blank items instead? :thinking: 
Resolves #6131.
=> Remove blank poll option

resources/assets/coffee/react/profile-page/detail-bar.coffee, resources/assets/less/bem/profile-detail-bar.less
Almost forgot about this. Found yesterday when adding that mania variants.
=> Hide redundant ranking in mobile

resources/assets/coffee/osu_common.coffee
Found this while cleaning up old branches. Thankfully not a problem so far.
=> Escape url for use in css

resources/assets/less/bem/beatmap-discussion-editor.less
For people who complained about being unable to perform text selection starting from the placeholder space above the button-bar.
Padding seems to work fine if it's on the child instead of the parent (which would have that overflow issue referenced in the deleted comment).
=> Change margin to padding for easier input box focus and text selection

config/querydetector.php
A bit hidden in clockwork and log is better than disabling it altogether.
=> Remove alert display for query detector

app/Libraries/LocaleMeta.php
Now with a capital letter, like other languages
=> FIx spelling of the Ukrainian language

resources/lang/ar/model_validation.php, resources/lang/be/model_validation.php, resources/lang/bg/model_validation.php, resources/lang/cs/model_validation.php, resources/lang/da/model_validation.php, resources/lang/el/model_validation.php, resources/lang/fi/model_validation.php, resources/lang/hu/model_validation.php, resources/lang/it/model_validation.php, resources/lang/ja/model_validation.php, resources/lang/no/model_validation.php, resources/lang/pl/model_validation.php, resources/lang/pt/model_validation.php, resources/lang/ro/model_validation.php, resources/lang/sk/model_validation.php, resources/lang/sv/model_validation.php, resources/lang/tr/model_validation.php, resources/lang/uk/model_validation.php, resources/lang/vi/model_validation.php, resources/lang/zh-tw/model_validation.php
Put back translations that are gone when updating key from `beatmap_discussion_post` to `beatmapset_discussion_post`. The files will need to be reuploaded to crowdin once merged.
I also noticed `sk` never has its translation updated (not included in @peppy's update script after initial import?). Updated `model_validation.php` file here so the file can be uploaded without nuking other updated translations.
=> Translation key update

resources/assets/coffee/react/beatmapset-page/score-top.coffee
It was updated to the wrong props.
Resolves #6221
=> Fix missing mode from links in beatmap top/own score

app/Models/Elasticsearch/BeatmapsetTrait.php, app/Models/Elasticsearch/PostTrait.php, app/Models/Elasticsearch/TopicTrait.php, app/Models/Elasticsearch/UserTrait.php, app/Traits/EsIndexableModel.php
Also exclude beatmapsets with `download_disabled_url` set.
The explicit `getDeletedAtColumn` test when reindexing entire table is removed and `esShouldIndex` is now used instead. This means indexing `Topic` and `Post` will need to eager load `forum`, adding additional overhead mostly from laravel.
=> Add additional exclusions when indexing Beatmapsets

app/Http/Controllers/BeatmapsetsController.php, resources/views/layout/metadata.blade.php
I thought of just adding a generic `$metadata` field to allow adding any number of custom `meta` tags, but then there's these open graph tags that use `property` instead of `name`, and the additional code for allowing arbitrary keys looks dumb ಠ_ಠ
=> Add meta tag on pages webcrawlers should not be indexing

app/Models/NewsPost.php
Cursory check shows this is the only remaining possible fail case ( ﾟ◡ﾟ)
(probably should have a better title)
The alternative is to not publish the news post if title is missing.
=> Don't fail on missing title

app/Libraries/LocaleMeta.php
Language names in Spanish are common nouns (_nombres comunes_) and the first letter shouldn't be capitalised.
=> Change "Español" to "español" (correct spelling)

app/Models/BeatmapDiscussionPost.php
Reverts ppy/osu-web#6199
It seems in some cases the query will do a lookup on `beatmap_discussions` using temporary tables and filesort first instead of getting `beatmap_discussion_posts` first
=> Revert "Hide replies of deleted discussion"

app/Http/Middleware/CheckUserBanStatus.php, app/helpers.php
`RequestGuard` used by API doesn't have a `logout()` method. This wasn't an issue previously because the `CheckUserBanStatus` middleware didn't apply properly in API requests due to the user not being resolved early enough.
=> Fix logout incorrectly called on guards without the method

resources/assets/lib/laroute.ts, resources/assets/lib/ziggy.d.ts
Instead of relying on `APP_URL` set during build time, fill them in as they're being accessed. Simplifies dusk testing for docker.
=> Use current url to generate url on js side

app/helpers.php
It ended up a bit too permissive when updated a while ago.
Resolves #6262.
=> Fix int/float caster to return null on empty string

resources/assets/lib/quick-search-button.tsx
Not sure if useful but maybe can reduce confusion like in #6265 by directing guest to search page instead when clicking the quick search button?
=> Link quick search button to search page for guest

app/Http/Controllers/Multiplayer/RoomsController.php, app/Models/Multiplayer/Room.php, app/Transformers/Multiplayer/RoomTransformer.php, database/migrations/2020_07_08_042634_add_category_to_multiplayer_rooms.php, database/migrations/2020_07_10_105258_add_ends_at_index_to_multiplayer_rooms.php
- nowhere to set it apart of manually editing database
- use parameter `category` in rooms listing endpoint to filter by category (normal or spotlight)
- add support for cursor based pagination. Sort option is implied by existing parameter `type`
- cursor for more results will need to be built manually
- for type `ended`, following are required:
- `cursor[ends_at]`
- `cursor[id]`
- for other types:
- `cursor[id]`
- I can't add those cursor hint in the response without breaking current api ( ﾟ ヮﾟ)
Resolves #6226.
=> Add category and pagination to multiplayer rooms

app/Models/Multiplayer/Room.php
Why `startGame` an instance function though :thinking:
=> Include database defaults when returning new room data

resources/assets/coffee/_classes/sticky-header.coffee
Every discussion post triggers an `osu:page:change` event when mounted; this ends up not working so well when there're hundreds of them continually triggering the handler that needs to do a layout, before the page has even finished rendering all the components.
Would be useful if there was a way to tell if the page finished rendering 🤔 
related #6285; I'm pretty sure the lag with typing is a different issue
(also not sure if `throttled-scroll` should just use the debounced handler as well)
=> Faster initial render when there are many beatmap discussion posts

app/Http/Controllers/Multiplayer/Rooms/Playlist/ScoresController.php
I saw the syntax and thought was neat but forgot to check which version it's added.
=> Use older syntax for array merge

resources/views/multiplayer/rooms/_rankings_table.blade.php
Seems like it should show number of attempts instead of number of played maps.
=> Show correct play count for multiplayer leaderboard

resources/assets/less/bem/chat-conversation-list-item.less, resources/assets/lib/chat/conversation-list-item.tsx
Appears to be mostly an issue with Chrome's handling of layout when the conversation list has a scrollbar.
Making the close button and unread indicator `position: absolute` makes Chrome stop trying to relayout nearly everything on screen.
Safari and Firefox do not appear to have the same relayout issue.
The position of some elements get moved slightly as preserving them ended up having too many confusing calculations
closes #6200
=> Improve chat UI performance with many channels

resources/assets/lib/notifications/worker.ts
fix #6300 
The problem is when logout, `this.userId` is still saved. After login again, it returns in this condition
https://github.com/ppy/osu-web/blob/b72dd938498c18b758596ac90a4d43666ac287bb/resources/assets/lib/notifications/worker.ts#L211-L213
and doesn't call `this.boot()`, so `this.active` is not changed to `true`.
Alternative solution: call `this.boot()` inside condition above. But I'm not sure which one is better.
=> Fix notification and chat icon don't load

resources/assets/lib/quick-search/main.tsx, resources/assets/lib/quick-search/worker.ts
fix #6308 
Should I change this
https://github.com/ppy/osu-web/blob/eeaecc44c06a4a657765a5eb4a0180a74a93e2ce/resources/assets/lib/quick-search/worker.ts#L25-L30
to this
```ts
interface SearchResult {
beatmapset?: SearchResultBeatmapset;
forum_post?: SearchResultSummary;
user?: SearchResultUser;
wiki_page?: SearchResultSummary;
}
```
to check another potential undefined?
=> Fix quick search bug when using space keyword only

app/Models/Tournament.php, app/Models/UserStatistics/Model.php, database/migrations/2020_07_17_021430_add_play_mode_variant_to_tournaments.php, tests/Models/TournamentTest.php
Should be pretty straightforward: set `play_mode_variant` column (`4k` or `7k` for mania) as needed. Empty string isn't a valid variant. Null (value, not "null" string) is.
=> Add support for play mode variant to tournament

app/Libraries/OsuAuthorize.php
The user is still guest so some things like personal difficulty rating search won't work.
Resolves #6314.
=> Allow beatmapset search when authenticated using oauth

resources/assets/less/bem/ranking-filter.less, resources/assets/lib/ranking-filter.tsx, resources/assets/lib/sort.tsx, resources/lang/en/rankings.php, resources/views/rankings/index.blade.php
Closed #6201 
I only change based on the design and don't modify `Sort` component to prevent changes in other page.
**Desktop**
**Mobile**
The mobile view is cover up half of the screen. Should I make it horizontal?
=> Change view ranking filter header

app/Http/Controllers/Chat/ChatController.php
One time `request()` call and remove redundant check `$since >= messages.last.id` after a `messages.id > $since` query.
=> Chat controller cleanup

config/database.php
Manually set default SQL mode because [ProxySQL only supports protocol version 5.x](https://github.com/sysown/proxysql/issues/2021) and [Laravel sends obsolete SQL mode](https://github.com/laravel/framework/blob/36fdbd4c6a35d689384eebd4c33477a6b444d883/src/Illuminate/Database/Connectors/MySqlConnector.php#L183) if set to strict mode and detect older server version.
=> Manually set default SQL mode

resources/docs/source/includes/_structures.md
Fixes #6354.
Also add documentation on how to use the cursor.
=> Fix typo on multiplayer score API documentation and add more detail on using its cursor

app/Http/Middleware/RequireScopes.php
Resolves #6361.
The alternative is for client to request client grant token and use that instead :thinking:
=> Allow public access of news API endpoint

app/Http/Controllers/PasswordResetController.php
Current prefix ending with `-` makes it difficult to gather stats of.
=> Fix redis prefix for password reset throttling namespace

config/schemas/beatmaps.json
requires reindex `php artisan es:index-documents --types=beatmapsets --yes --cleanup`
closes #6284
=> Increase length of Beatmapset title prefix matching

app/Http/Controllers/AccountController.php, app/Http/Controllers/Forum/TopicsController.php, app/Models/UserProfileCustomization.php, app/Transformers/UserCompactTransformer.php, resources/assets/coffee/_classes/forum.coffee
`with_deleted` query string will still override the saved setting, but won't change it, unless the option is toggled.
I was looking at streamlining some of the `with_deleted` handling but it turned out to be quite messy keeping the url param, blade and js state in sync, so I ended up skipping it.
closes #6218
=> Persistent "Hide Deleted Posts" setting

app/Http/Controllers/OAuth/ClientsController.php
When creating a new OAuth client through the UI, if the callback didn't have anything entered into it previously, it would be treated as `null` and the column is not nullable.
=> Fix creating client with empty callback

app/Libraries/Session/CacheBasedSessionHandler.php, app/Libraries/Session/SessionManager.php, app/Libraries/Session/Store.php
Resolves #6386. Guests still need session at least for csrf so shorten the duration instead. 2 hours should be enough :thinking:
=> Shorten duration of guest sessions

app/Transformers/BeatmapTransformer.php, config/schemas/beatmaps.json, database/factories/BeatmapFactory.php, database/factories/ScoreBestFactory.php, database/seeds/ModelSeeders/BeatmapSeeder.php, database/seeds/ModelSeeders/ScoreSeeder.php, database/seeds/ModelSeeders/SpotlightSeeder.php, resources/assets/lib/interfaces/beatmap-json-extended.ts
The value is obsolete and shouldn't be visible/used anymore. Resolves #6426.
=> Remove invalid count_total

bootstrap/autoload.php
Precompiling is now done by composer and this check hasn't been useful for a while now. The file itself has been removed in laravel since 5.x but we still need it to preload helper overrides.
=> Remove old cache loader

app/Models/User.php
`isBot()` is actually for chat bots (with group identifier `bot`) which is different from the from the "bot" group that is supposed to be excluded here.
caused by #6419
=> Fix User hasProfile check

app/Http/Controllers/Multiplayer/Rooms/Playlist/ScoresController.php
Android version is having an issue where it can't access files inside apk to provide the expected hash. For the time being we are allowing an exception for this build, but it won't send an md5sum in this case, rather a string which needs to be md5'd locally to correctly match database.
I wasn't expecting to have to do this, but the database field is a binary and doesn't allow storing a string for direct matching.
=> Add temporary exception for timeshift submission from unsupported clients

resources/assets/less/bem/forum-topic-nav.less
Proper fix will probably take a bit long so just undo the change for now.
=> Undo scrollable forum navigation bar

app/helpers.php
Apparently email with non-ascii local part is valid email (mail server support varies) ( ﾟ ヮﾟ)
Resolves #6468.
=> Fix encoding of obscure email function

resources/assets/less/bem/changelog-chart.less
My data was missing recent changelog usage chart so it wasn't shown and then I forgot to actually check it :pensive:
=> Add missing relative position for changelog graph

app/Http/Controllers/Forum/TopicsController.php, app/Models/Forum/Post.php
Found when checking other stuff.
There's still at least one more but it's rare case (one extra query for displaying polls) and I'm not yet sure how to properly cache it.
=> Add missing preload for forum topic page

resources/assets/less/bem/search-forum-options.less, resources/views/forum/topics/_watch.blade.php
That was weird.
(the gap between button and menu is too far)
(labels flew off somewhere)
(some stuff shouldn't stick to the edge)
=> Fix forum topic bookmark menu and search form

app/Http/Middleware/StartSession.php
This has been broken for a while due to internal change on upstream library. Should be testing this but not quite sure how :thinking:
=> Fix skipping saving session on invalid csrf token

resources/assets/less/bem/forum-post-info.less, resources/views/forum/topics/_post_info.blade.php
Having multiple qtips on the same element where one of them involves disabling all the tooltip interaction on the element turns out to be not a very good idea. 🤔 
Also fixes the usercard position since 100% width ends up always pushing it too far to the side.
`word-break: break-word` actually overrides `overflow-wrap`, but Safari
doesn't support `overflow-wrap: anywhere` yet.
closes #6516
=> Wrap long username instead of truncating

app/Libraries/User/DatadogLoginAttempt.php
=> Add missing dot in datadog login attempts name

app/Http/Controllers/SessionsController.php
The action has been renamed. It won't work by default because it would fail csrf check but this is for when someone doing weird thing.
=> Fix guest middleware for login endpoint

app/Http/Controllers/Multiplayer/Rooms/Playlist/ScoresController.php
Title must come before anything. Even the group declaration.
Reference: https://github.com/mpociot/laravel-apidoc-generator/blob/8be084e39e4373197aa734e6ef6da7deed3655af/src/Extracting/Strategies/Metadata/GetFromDocBlocks.php#L64
=> Fix documentation formatting for multiplayer

resources/assets/less/bem/user-verification.less
Should display under the input box instead of all the way to the side.
Although, it seems weird that this text has `position: absolute ` at all 🤔 
It'd only benefit multi-line text not changing the layout, but then, if there's too many lines, it'd just start overlapping the other text? `min-height` could be used to maintain a minimum space for 2 lines but still allow more lines to expand the space 🤷
=> Fix verification dialog error message position

app/Models/Event.php
otherwise, events with the same date can show in any order and get duplicated or not show at all when they have the same date at offset cutoffs.
closes #6576
=> Return user recent events in consistent order

app/Http/Controllers/Payments/PaypalController.php, app/Libraries/Payments/PaypalExecutePayment.php, composer.lock
~~Apparently `getData()` will return null in many cases which the Sentry logger does not like.~~
~~`getMessage()` should at least be an empty string in the worst case.~~
Looks like updated `sentry-laravel` package uses `?string` instead of `string` 🤔
=> Fix error reporting failure when connection to Paypal fails

app/Models/Multiplayer/UserScoreAggregate.php
`$prev` and `$current` are of different type :face_with_head_bandage: 
It also means last_score_id hasn't been assigned correctly. And we need to run this again...
```
UPDATE multiplayer_rooms_high
SET last_score_id = (
SELECT MAX(sh.score_id)
FROM multiplayer_scores_high sh
JOIN multiplayer_playlist_items pi
ON (sh.playlist_item_id = pi.id)
WHERE
pi.room_id = multiplayer_rooms_high.room_id
AND sh.user_id = multiplayer_rooms_high.user_id
)
WHERE
completed > 0
AND last_score_id IS NULL
```
=> Fix recording last highest score id on multiplayer

app/Libraries/UserBestScoresCheck.php
Apparently sorting over `_id` uses too much memory (because it's text fielddata?). 
Fortunately, `score_id` is still indexed and is the same value (and a number)
=> Switch UserBestScoreCheck to cursor over score_id

app/Transformers/BeatmapCompactTransformer.php
That was weird. Probably leftover when we moved loading the leaderboard separately.
=> Remove unused json transformer include

app/Http/Controllers/UsersController.php, app/Transformers/UserCompactTransformer.php, resources/assets/coffee/react/profile-page/detail.coffee, resources/assets/coffee/react/profile-page/header.coffee
I'm not going to document `rankHistory` key =)
Duplicated until other api users update the thing.
=> Add correctly-named rank history data in user json

resources/assets/coffee/_classes/stacked-bar-chart.coffee, resources/assets/coffee/react/beatmapset-page/info.coffee
- ~~fix broken chart when the data is all zero~~
- fix missing chart when toggling between beatmap with and without plays (resolves #6570)
- ~~hide data for converted maps (I think those pass/play counts in osu_beatmaps don't include converts? @peppy )~~
Split off the fixes.
=> Fix missing beatmap fail rate charts when switching difficulties

app/Transformers/BeatmapCompactTransformer.php
The chart data are actually shared between modes. Additionally make sure the response always include both attributes (exit and fail).
=> Show failtime for all modes

resources/assets/coffee/react/beatmap-discussions/discussion.coffee
page broke in #6627 because `readPostIds` can be undefined, and previously `_.includes` was silently handling it
=> Fix error when viewing discussions through user modding profile

resources/assets/coffee/_classes/beatmap-discussion-helper.coffee, resources/assets/less/bem-index.less, resources/assets/less/bem/beatmap-discussion-timestamp-decoration.less, resources/assets/less/bem/beatmapset-discussion-message.less, resources/assets/lib/beatmap-discussions/editor.tsx, resources/assets/lib/beatmap-discussions/review-post.tsx
Saves having to add arbitrary `beatmapset-discussion-message` wrappers when utilising the style
=> Extract timestamp decoration style out into separate BEM block

app/Models/UsernameChangeHistory.php
In a distant past, we wanted to hide these to hide certain name changes (ie. when a user asked for a change due to their previous name being their legal name of social security number). This process has since changed and we actually want these to show, as they are the only name change type which allows admins to change a username without incrementing the cost of a name change.
=> Show username change history even for admin changes

resources/assets/less/bem/beatmap-discussion-post.less, resources/assets/less/bem/beatmap-discussion.less, resources/views/beatmap_discussion_posts/_item.blade.php, resources/views/beatmap_discussions/_item.blade.php
I kinda broke the padding for review posts (left padding too small).
Trapped into trying to fix `beatmap-discussion-post` block until I noticed some of the elements are being used everywhere without the accompanying block and fixing them will be rather involved (not to mention it's getting a redesign).
=> Fix discussion post paddings

app/Models/User.php, database/migrations/2020_09_25_092826_create_phpbb_banlist.php, resources/lang/en/model_validation.php
Migrates a missing feature from old web.
Check is similar to the one for usernames and `phpbb_disallow`.
The format is `*@domain` or even `*@domain*` where `*` becomes the regex equivalent of `.*?`
`ban_start` is not checked.
`isValidEmail()` is a bit janky as it'll just append additional errors on multiple calls.
Not sure if the migration should just go into the base tables, but then we added this `2020_05_15_083037_sync_structure` 🤔
=> Add support for user registration email domain block list

.env.example, app/Libraries/OsuAuthorize.php, config/osu.php, resources/lang/en/authorization.php
defaults to true (allows verified sessions to skip play count requirement)
add `USER_MIN_PLAYS_ALLOW_VERIFIED_BYPASS=false` to .env to disable the play count bypass.
Effects
- chat
- posting to beatmap discussions
- posting to forum
known issues:
~~Failing the check when not verified will automatically send a verification email out - the issue is, on chat, the verification dialog doesn't show when the message fails to send and doesn't show what the error is.~~ It should only attempt verification if the option is enabled, now. Chat still has the issue where if doesn't show the reason for error.
=> Add option to disable minimum play count on verified sessions for certain actions

resources/assets/coffee/react/_components/comment-editor.coffee
setting `selectionStart` causes iOS safari to scroll to the element when a keyboard is active.
closes #6670
=> Fix Safari auto scrolling to comments box

resources/assets/coffee/_classes/stacked-bar-chart.coffee
Initialize the bars at the correct position on bottom side.
Resolves #6649.
=> Better beatmap point of failure chart transition

app/helpers.php, tests/LocaleTest.php
Er ( ﾟ ヮﾟ)
(using `nb` / Bokmål as it seems to be the most common and has some words in it in current general `no` translations)
=> Add correct momentjs locale mapping for Norwegian

resources/assets/lib/globals.d.ts, resources/assets/lib/lang-overrides.ts
Resolves #6709 
I was debugging this issue and it seems like the original function for getPluralForm takes two arguments instead of just one. The missing argument that we currently have causes Lang.js to always pick the first of the two choices (singular). This PR fixes this issue by taking in consideration of the second argument.
=> Fix pluralization issue

.env.example, app/Models/Beatmapset.php, config/osu.php
Changes the nominations required for 'Hybrid' Beatmapsets to be (by default) 2*(playmode count).
Note that while the required nominations number has been moved to a `.env` variable, _decreasing_ the number may result in Beatmapsets being left in limbo and not entering a qualified state if the new value is below their current nomination count.
(this is the first part in addressing #6689)
=> Change nomination requirement for 'hybrid' beatmapsets

resources/assets/lib/beatmap-discussions/chart.tsx
Either hide them or just clamp to 1 (which is what this PR does).
=> Limit max timestamp of beatmap discussion timeline chart

app/helpers.php
=> Correctly escape user id part when generating profile link

resources/assets/lib/chat/chat-api.ts, resources/assets/lib/chat/chat-orchestrator.ts, resources/assets/lib/chat/chat-worker.ts
contains part of #6731
Wrapping jquery calls with `Promise` isn't needed anymore.
Also converts some of the calls to use `await`.
This doesn't fix any of the `action`/`transaction` bits
=> Remove promise wrapping for chat api calls

app/Libraries/BBCodeForDB.php, app/Libraries/OsuAuthorize.php, app/Models/User.php, resources/views/forum/topics/_post_info.blade.php
Shouldn't be a need to be able to `User::lookup` users in the `no_profile` group
closes #6736
=> Exclude no_profile user group from user lookup

resources/assets/less/bem/profile-info.less
The box itself already has correct pointer events but the container doesn't.
=> Prevent invisible username history from blocking other elements

app/Libraries/Elasticsearch/QueryHelper.php, app/Libraries/Elasticsearch/SearchResponse.php, app/Libraries/Search/BeatmapsetSearch.php, app/Models/Wiki/Page.php
Found this when trying the latest elasticsearch.
Some queries currently incorrectly generate nested array [which is not actually supported and finally disallowed in later version (7.7?)](https://discuss.elastic.co/t/must-not-boolean-query-in-7-7/233269).
Also added a minor compat layer for updated total value in 7.x.
Haven't actually done thorough check yet.
=> Fix incorrectly nesting array for elasticsearch query

resources/assets/lib/models/notification-stack.ts, resources/assets/lib/stores/notification-stack-store.ts, resources/assets/lib/stores/notification-store.ts, resources/assets/lib/stores/widget-notification-stack-store.ts
Noticed this weird dependency on WidgetNotificationStackStore for handling notifications as read (especially when it's by notification id).
Move responsibility of marking Notification objects from WidgetNotificationStackStore (and partially from NotificationStackStore) to NotificationStore. 
This slows things down a bit for type/stack read as the NotificationStore doesn't have the grouping so it has to loop the entire array.
As a bonus, this fixes bug where "clear :type" <del>for non-"all" type</del> from notification popup widget sometimes doesn't mark notifications in history page read.
=> Mark notifications (the model) as read direct from its store

resources/assets/lib/notifications-index/main.tsx
Seems weird using `observe` instead of simply `computed` for the links :thinking:
=> Simplify notifications history header links

.travis.yml, app/Console/Commands/EsIndexDocuments.php, app/Console/Commands/EsIndexWiki.php, app/Jobs/EsIndexDocumentBulk.php, app/Libraries/Elasticsearch/Indexing.php, app/Models/Elasticsearch/BeatmapsetTrait.php, app/Models/Elasticsearch/PostTrait.php, app/Models/Elasticsearch/TopicTrait.php, app/Models/Elasticsearch/UserTrait.php, app/Models/Elasticsearch/WikiPageTrait.php, app/Models/Wiki/Page.php, app/Traits/EsIndexable.php, app/Traits/EsIndexableModel.php, composer.json, composer.lock, config/schemas/beatmaps.json, config/schemas/posts.json, config/schemas/users.json, config/schemas/wiki_page.json
Types have been removed from Elasticsearch, so they're going to eventually have to be removed from our schemas.
Setting `_type` to `_doc` as part of the migration path forwards.
It appears that `_doc` can be used as a substitute for what was originally set for the schema's `_type` in the current version of Elasticsearch we're using.
`elasticsearch-php` updated for an updated param list that includes `include_type_name`
=> Use _doc as _type for Elasticsearch

app/Http/Controllers/Payments/PaypalController.php, app/Libraries/Payments/PaymentProcessor.php, app/Models/Store/Order.php, database/migrations/2020_10_13_064901_add_provider_reference_to_orders.php
Save more metadata when processing Paypal payments. This is mostly useful for looking up failed orders, etc.
The main changes are the transaction's `PAYID` number (which is what their API uses) is stored when starting the transaction, and the IPN transaction number is written even if the order fails processing.
Moving forwards, the payment provider and the transaction reference id from the provider will be recorded in separate columns. In the case of Paypal, the PAYID is used for the reference since this is the one that's available at the start of the transaction and supports API lookups.
This PR doesn't make any changes to how they are currently read and used, but moving forwards we'll want to read from `provider` and `reference` instead of `transaction_id` on `Order`.
=> Save Paypal API transaction id when processing orders

app/Libraries/OsuAuthorize.php, tests/Libraries/ChatTest.php
Adds `ensureSessionVerified` that can be used as a replacement for `ensureLoggedIn`.
#6688 still needs to be addressed.
This means there's now:
- toggle for requiring verification on write HTTP verbs (`USER_POST_ACTION_VERIFICATION`)
- toggle for skipping min plays when verified (`USER_MIN_PLAYS_ALLOW_VERIFIED_BYPASS`)
- requiring verification separate from the above
closes #6726
=> Require verification to send chat message

resources/assets/coffee/react/profile-page/links.coffee, resources/docs/source/includes/_structures/user.md, resources/lang/en/users.php
The integration has been broken for a while (and never got added to new web) so remove it.
Keeping backend removal separate as lazer seems to be still using it.
=> Remove display of user lastfm

app/Models/DeletedUser.php, app/Models/User.php, app/Models/UserNotFound.php, app/Transformers/UserTransformer.php
Keep the attribute but make sure the value is always null. Also remove from model phpdoc so it doesn't crowd the autocomplete...?
Docs cleanup is accidentally in #6768 whoops ( ﾟ ヮﾟ)
=> Hide user lastfm from API

docker-compose.yml
Current elasticsearch PHP version is 6.7.2 updated in d21fb10c6130c3cad4596acb1ea1b29fa15e6167 but docker-compose.yml was not similarly updated, breaking search and seed functionality under the Docker image. This commit rectifies this missing change.
=> Match docker's elasticsearch image version with composer.json

resources/assets/coffee/_classes/tooltip-default.coffee
Forgot to add the tooltip handler when adding the new ellipsis overflow thing.
=> Fix missing tooltip on some cut off text

build.sh
Some dependencies require upgrade to work on v2. Some also require php v7.4 whereas live is currently running 7.3.
Stuff will break if composer version is too old and doesn't recognize the `--1` argument :shrug:
=> Use composer v1

routes/web.php
Laravel routing fallback (`Route::fallback`) will return 405 for non-GET/HEAD requests on invalid routes.
Apparently it's a feature [1] and not a bug.
It seems weird so instead manually do what `fallback(...)` thing does but accept all HTTP verbs.
[1] https://github.com/laravel/framework/issues/25555 (probably should've linked this one instead of 25550)
=> Fix fallback routing

app/Http/Controllers/FallbackController.php
Seems more logical returning json if the request explicitly requested json format even on invalid routes...? :thinking: 
Now I looked at the response not sure if empty array (`[]`) makes sense though as opposed to maybe empty object (`{}`).
=> Return json-formatted 404 for json requests on invalid routes

.github/workflows/phpcs.yml
The image used to run the workflows was recently updated to use composer 2, which needs #6812 due to conflicting package dependencies.
=> Use composer v1 for running phpcs workflow

resources/assets/less/bem/avatar.less
The border isn't quite antialiased properly in firefox. This causes additional paint but the size is probably too small to matter.
=> Fix navbar avatar hover border

app/Models/Wiki/Page.php
There should be another fix of not indexing them in the first place but this should do for now.
Related: #6834
=> Only show valid languages in wiki language menu

app/Exceptions/Handler.php
Exceptions thrown from the guzzle http client also have a `getReponse` method which shouldn't be passed to the middleware.
This also removes rendering `getResponse` from laravel's `ValidationException`, but we don't use those validators anymore; there's one instance in the store pages for updating addresses, but we don't make use of the page anymore, so maybe we should remove it?
=> Fix exception handler returning wrong type of response to middleware

app/Http/Controllers/Payments/ShopifyController.php, tests/Controllers/Payments/ShopifyControllerTest.php
There aren't any records to match on our end, so record some data for tracing instead of exploding.
The Shopify stuff seems to be reliable enough that we don't need to force a hard fail here.
=> Log orders made directly from Shopify

phpcs.xml
I noticed `in_array` with missing strict parameter isn't being checked. And `==`/`!=` as well.
=> Add check for php strict comparisons

app/Models/UserNotification.php
Using the wrong format in the request causes no ids to be extracted
=> Skip trying to mark notifications as read if no ids were extracted from params

app/Libraries/Search/BeatmapsetSearch.php
This shouldn't be needed anymore since the index only uses `_doc` now and it's one of the things that doesn't auto remap when querying.
closes #6898
=> Remove ids query type filter

.github/workflows/phpcs.yml
seems like `ubuntu-latest` defaults to php 8 now which breaks at least one thing due to optional function parameters no longer being allowed before required parameters
=> Set php version for phpcs action

app/Transformers/BeatmapsetCompactTransformer.php
The previous function returns a builder which is always true. It doesn't fail on live site because php up to 7.3 allows array access on null
```
>>> $a = null
=> null
>>> $a['x']
=> null
>>> $a = null
=> null
>>> $a['x']
PHP Notice:  Trying to access array offset on value of type null in /home/edho/osu/osu-webeval()'d code on line 1
```
=> Fix beatmapset qualification check

resources/assets/coffee/react/_components/beatmapset-panel.coffee
Matches the model's allowed states for hyping. Not sure if it makes sense showing hypes/nominations for qualified maps though? But it's still shown and I think people can still hype them :thinking: 
Resolves #6915.
=> Fix states which beatmap hypes/nominations are shown

resources/assets/coffee/react/beatmapset-page/scoreboard-table-row.coffee, resources/assets/less/bem/beatmap-scoreboard-table.less
I didn't want to this originally in #6886 because having overlapping links is silly and should be avoided, but after trying it some more, the usercard placement now looks silly.
This basically renders a link on top of another link.
=> Reduce username hover area on beatmap scoreboard

resources/assets/coffee/react/beatmapset-page/scoreboard-table-row.coffee
I knew there was another reason to make it `relative` 🤔 
fixes #6937
=> Fix username position on scoreboard when scrolling

database/seeds/ModelSeeders/CountrySeeder.php
closes #6742
Fixes ISO-3166 naming for the State of Palestine. This is also my first PR in this repository, so let me know if I edited the wrong file or if there are other files that need to be addressed regarding this fix.
=> Fix country name formatting for the State of Palestine

.github/workflows/phpcs.yml
We switched to v2 a while ago so this should be locked to v2.
=> Use composer 2 for phpcs Github action

app/Http/Controllers/Multiplayer/Rooms/Playlist/ScoresController.php, app/Models/Multiplayer/Room.php, database/migrations/2020_12_03_075220_add_realtime_to_multiplayer_rooms.php, resources/views/multiplayer/rooms/show.blade.php, tests/Controllers/Multiplayer/RoomsControllerTest.php
Add parameter `category` of `realtime` (also for listing). `ends_at` parameter can be skipped.
And then I noticed there's no way to indicate number of people inside the room :thinking: 
Todo:
=> New multiplayer room type

resources/assets/lib/beatmaps/beatmapset-search.ts, resources/assets/lib/beatmaps/result-set.ts, resources/assets/lib/notifications/worker.ts
`JSON` isn't what one may think it is. `unknown` should be fine if it's only being passed around.
Also removed one unused interface.
=> Clean up TypeScript typing

resources/assets/lib/beatmap-discussions/editor-beatmap-selector.tsx, resources/assets/lib/beatmap-discussions/editor-discussion-component.tsx, resources/assets/lib/beatmap-discussions/editor-insertion-menu.tsx, resources/assets/lib/beatmap-discussions/editor-issue-type-selector.tsx, resources/assets/lib/beatmap-discussions/editor-toolbar.tsx, resources/assets/lib/beatmap-discussions/editor.tsx, resources/assets/lib/beatmap-discussions/icon-dropdown-menu.tsx, resources/assets/lib/beatmap-discussions/slate-context.ts, resources/assets/lib/notification-widget/item-group.tsx, resources/assets/lib/notification-widget/item.tsx, resources/assets/lib/notifications-index/main.tsx, resources/assets/lib/user-card-brick.tsx
Typings when using the 'new' React context need to be explicitly declared.
=> Declare correct context type for components

resources/assets/coffee/react/profile-page/account-standing.coffee
Account standing dates used to be displayed manual way, not using ``TimeWithTooltip``, which resulted in them not having the tooltip with detailed information like other dates displayed on the site.
=> Use proper date display for user account standing

app/Models/Beatmapset.php, config/schemas/beatmaps.json, database/migrations/2020_08_27_202640_add_nsfw_flag_to_beatmapsets.php
Data schema part of #6575 so they can be indexed beforehand. `es:index-documents --types=beatmapsets` will need to be run as well in addition to the migration.
=> Add database and elasticsearch explicit flag for beatmapsets

app/Http/Middleware/VerifyUserAlways.php
Always require verification when performing any action that uses a http delete (separate from the optional env setting).
This does lead to some seemingly strange scenarios where watching something doesn't require verification, but unwatching it does. There's also still the issue where posts can be edited without verification.
The other option is explicitly requiring verification performing the permission checks; that requires a bit more work since displaying the delete button for some things share the same permission check as performing the action itself causing the button to not be there when not verified, e.g. `BeatmapsetDelete`.
=> Require verification for delete actions

.env.example, app/Models/Chat/UserChannel.php, config/osu.php
Doesn't return if limit was hit in the response yet, tacking that on is a bit messier (and the default of _visible_ channels is more than plenty)
=> Limit number of channels used for presence

app/Libraries/ChangeUsername.php, tests/Libraries/ChangeUsernameTest.php
Fixes #7005
Displays same username error message rather than username is in use. We had trouble trying this out in the local web environment, but the php unit tests reflect that it works.
Co-authored by @angelaz1
=> Show correct error message when changing username to different casing

app/Transformers/FollowCommentTransformer.php, app/Transformers/FollowModdingTransformer.php
` DeclaredPermissionsTest` expects all the transformers to be parameterless.
Failing to set up the data provider only prints a warning :|
=> Fix test data provider warnings

SETUP.md
Possibly obvious, but still tripped me up when setting up. Wasn't expecting the key to be only available on the old site.
I had other issues - aside from me screwing up and assuming `docker-compose` will come from the same PPA as `docker`, resulting in me having a 2017 version of the former with the 2020 version of the latter and refusing to work with a relative path in `docker-compose.yml` (which I consider irrelevant to the setup document), `APP_KEY` was initially blank for some reason - but on consulting with another person that was setting up recently, that doesn't seem to be something universal. Might have been a weird linux thing? No idea.
=> Clarify API key origin in setup procedure

resources/views/home/_user_beatmapset.blade.php, resources/views/home/user.blade.php
As I discovered that accessing `beatmapset_show_nsfw` casts `options` from json [twice](https://github.com/ppy/osu-web/issues/7055).
=> Fix error on dashboard page when user has no profile settings

app/Libraries/Search/BeatmapsetSearchRequestParams.php
The setting was in the wrong place (should be inside advanced search), with wrong check.
Resolves #7053.
=> Fix setting of beatmap nsfw search parameter

app/Models/UserProfileCustomization.php
Cuts down about 25 `json_decode` calls for exact same string.
Resolves #7055.
=> Reduce number of casting when accessing user settings

app/Http/Controllers/BeatmapsetsController.php, app/Models/BeatmapsetEvent.php, database/migrations/2021_01_15_092749_add_nsfw_toggle_to_beatmapset_events.php, resources/assets/less/bem/beatmapset-event.less, resources/assets/lib/beatmap-discussions/event.tsx, resources/lang/en/beatmapset_events.php
Not sure if should keep adding new event type or make a "metadata change" event instead.
The wording can use some improvement.
Use blue colour to follow other metadata edit. I wonder if explicit colour (`orange-2`) is better here.
Resolves #7042.
=> Log beatmap explicit state change

resources/assets/coffee/react/modding-profile/main.coffee, resources/assets/coffee/react/profile-page/main.coffee, resources/assets/lib/coffee-modules.d.ts, resources/assets/lib/user-profile-container.tsx
While refactoring the beatmap discussion components, I've scrolled past this big block that looks the same so many times 🤔 
(The tree depth of the pages section of the modding profile version also appears to be wrong?)
=> Refactor user profile page masking into component

app/Console/Commands/NotificationsSendMail.php, app/Jobs/UserNotificationDigest.php, app/Models/Count.php, database/migrations/2020_06_12_112518_set_last_mail_notification_id_sent.php, database/migrations/2021_01_25_050834_add_count_last_mail_user_notification_id_sent.php, tests/Commands/NotificationsSendMailTest.php
There's currently no index on user_notification.notification_id.
The migration should probably work as is and not take too long.
=> Send user notification digest by user_notification.id

app/Transformers/BeatmapCompactTransformer.php, app/Transformers/BeatmapTransformer.php, resources/assets/coffee/react/beatmapset-page/score-top.coffee, resources/assets/coffee/react/beatmapset-page/scoreboard-table-row.coffee, resources/assets/coffee/react/beatmapset-page/scoreboard-table.coffee, resources/assets/less/bem/beatmap-score-top.less, resources/assets/lib/interfaces/beatmap-json.ts, resources/assets/lib/play-detail.coffee, resources/assets/lib/scores-show/stats.tsx, resources/assets/lib/scores/pp-value.tsx, resources/assets/lib/utils/beatmap-helper.ts, resources/docs/source/includes/_structures/beatmap.md, resources/docs/source/includes/_structures/beatmap_compact.md
- no pp column for scores on non-ranked maps
- detailed pp value tooltip
- notice of score processing when value is 0 or null
- beatmap status in json always visible (moved to BeatmapCompactTransformer)
Continues off #7124.
=> Update PP display on score details

app/Transformers/ScoreTransformer.php
`->best` is already assumed loaded so always use it instead of relying on potentially outdated `high_score_id`.
Resolves #7137. Also removes link to nonexistent score (when it's not high score anymore).
=> Validate score best_id

app/Http/Controllers/BeatmapsetsController.php, resources/lang/en/beatmapsets.php, resources/lang/en/layout.php, resources/lang/en/page_title.php
Things get a bit weird because of how redirect for `GET` is handled ಠ_ಠ
The wordings can be improved.
Resolves #3634.
=> Better error message when exceeding download limit

app/helpers.php
If anything, url passed to camo should be percent-encoded. Especially the query strings.
Resolves #7155.
Also adjusted timing of various other checks.
=> Don't percent decode url for media proxy

resources/assets/lib/play-detail.coffee
Should always check beatmap instead of beatmapset.
Resolves #7163.
=> Fix score pp display check on mixed state beatmap

resources/assets/less/bem/tournament.less
That was weird. Also the body is somehow already using correct padding.
=> Adjust padding of tournament description area

app/Libraries/RouteSection.php, app/Libraries/UserVerification.php, routes/web.php
Avoids old sessions from retrying with invalid sessions and just generally better without `/home` prefix.
=> Move notifications endpoint
