config/database.php
=> Strict mode database connection

resources/assets/coffee/react/beatmap-discussions/main.coffee
=> Fix beatmap discussion live-update breaking on beatmapsets that have no events yet

resources/assets/coffee/react/beatmap-discussions/events.coffee, resources/assets/less/bem/beatmapset-events.less, resources/lang/en/beatmap_discussions.php
And no more maxed out page size.
=> Show info when there's no event yet

app/Http/Controllers/BeatmapDiscussionPostsController.php
=> Fix beatmapset nomination resetting

resources/assets/less/bem/forum-topic-entry.less, resources/views/forum/forums/_topic.blade.php
Here's version with less transparent border.
```less
&::after {
.full-size();
width: calc(100% ~'+' (@main-margin * 2));
margin: 0 (-@main-margin);
background-color: fade(#fff, 50%);
}
```
=> Indicate deleted topic in forums listing

app/Http/Controllers/BeatmapDiscussionPostsController.php
Thanks to timing of discussion and post id get assigned.
Fixes #1927. I think.
=> Actually store discussion and post id

resources/assets/less/bem/forum-post.less
fixes #1929 
maybe breaks IE? :trollface:
=> set flex: 1 1 auto on forum post content

resources/assets/coffee/_classes/beatmap-discussion-helper.coffee, resources/assets/coffee/react/beatmap-discussions/post.coffee
Use proper word boundary matcher. Fixes #1939.
=> More formatter fixes

app/Models/Beatmapset.php, resources/views/beatmapset_watches/index.blade.php
=> Remove duplicated function

resources/views/objects/_usercard.blade.php
=> No counting null

resources/assets/coffee/react/beatmapset-page/scoreboard.coffee
=> Don't show key mods on scoreboard if beatmap is not a convert.

app/Http/Controllers/BeatmapsetWatchesController.php
=> Ignore deleted beatmapsets in watchlist index

resources/assets/coffee/react/_components/beatmapset-panel.coffee
=> Fix number formatting on beatmap panels

app/Http/Controllers/Admin/BeatmapsetsController.php, app/Models/Beatmapset.php, resources/assets/less/bem-index.less, resources/assets/less/bem/beatmapset-cover-admin.less, resources/lang/en/admin.php, resources/lang/en/layout.php, resources/views/admin/beatmapsets/cover.blade.php, resources/views/admin/beatmapsets/show.blade.php, routes/web.php
=> Add admin ability to remove beatmapset covers

resources/assets/coffee/react/beatmapset-page/score-big.coffee, resources/assets/coffee/react/beatmapset-page/score-top.coffee, resources/assets/coffee/react/beatmapset-page/score.coffee, resources/assets/less/bem/beatmapset-score.less, resources/lang/en/beatmapsets.php
The scoreboards are getting a bit too dense... will need extra work to make stuff actually readable.
Fixes #1997
=> Add misses and max combo to scoreboards 🌈

app/Http/Controllers/Payments/PaypalController.php, app/Http/Controllers/Store/CheckoutController.php, app/Libraries/Payments/PaymentProcessor.php, app/Listeners/Fulfillments/PaymentSubscribers.php, app/Notifications/Store/ErrorMessage.php, app/Traits/StoreNotifiable.php
- Send error notification and skip if payment is already cancelled.
- include more info in error notification message.
=> Handle Paypal sending multiple ipns for same order

app/Libraries/Payments/CentiliPaymentProcessor.php, app/Libraries/Payments/PaypalPaymentProcessor.php, app/Libraries/Payments/XsollaPaymentProcessor.php, app/helpers.php
Fix with more sane value comparison.
fixes #1968
Should think about possibility of treating all currency values as a formatted integer or something.
=> Compare money values with integers instead of floats.

resources/assets/coffee/react/beatmap-discussions/new-reply.coffee, resources/assets/less/bem/beatmap-discussion-post.less
looks silly in safari >_>
and everything not chrome
also remove the button that isn't supposed to be there :trollface:
=> Fix beatmap discussion reply's cancel button style

app/Models/Wiki/Page.php
Removed during last refactor ( ﾟ◡ﾟ)
=> Index wiki page title

app/Http/Middleware/UpdateUserLastvisit.php
=> Skip validation on updating user's last visit

resources/assets/coffee/react/_components/play-detail.coffee
=> Only show pp if score has weight attribute

app/Models/Score/Best/Model.php
=> Readd own user id when doing friend ranking lookup

resources/lang/fr/artist.php, resources/lang/fr/changelog.php, resources/lang/fr/contest.php, resources/lang/fr/home.php, resources/lang/fr/users.php
fixes #2052
Should be using the singular rule for 0, apparently? I don't know French ヽ( ﾟ ヮﾟ)ﾉ
=> Fix you have 0 new messages for French translation

app/Models/BeatmapDiscussion.php, app/Models/Beatmapset.php, app/Models/User.php, resources/assets/coffee/react/beatmap-discussions/new-discussion.coffee
Show actual number and fix validation.
Fixes #2054.
=> Fixes user hype

app/Console/Commands/UserRecalculateRankCounts.php, app/Console/Kernel.php
artisan command that recalculates and updates the rank counts for user stats.
=> Recalculate user stats rank counts

app/Http/Controllers/UsersController.php
=> Limit parsing params to relevant actions

app/Models/Beatmapset.php
was sorting on play counts on beatmaps instead of the beatmap set
=> Sort on correct play count field

app/Models/Beatmapset.php, app/helpers.php
Match with old site.
Closes #2073.
=> Data is in datetime which ignores timezone setting

resources/lang/sv/home.php
Replaced old download array with new from en/home.php to make the new download page translated
[Image](https://imgur.com/a/XoAWv)
=> Fix Swedish download translation

resources/views/rankings/performance.blade.php, resources/views/rankings/score.blade.php
=> Show combined SS and S counts on score boards

app/Models/Elasticsearch/BeatmapsetTrait.php, app/Models/Elasticsearch/PostTrait.php
=> Use read-only connection for indexing query instead of primary

resources/assets/less/variables.less
temporary solution
Idea from #966
¯\\\_(ツ)\_/¯
=> Increase menu height to fit all localisations

app/Http/Controllers/FriendsController.php, app/Transformers/UserCompactTransformer.php, routes/web.php
=> Add API endpoint for Friends list

resources/assets/coffee/react/_components/icon-expand.coffee, resources/assets/coffee/react/beatmap-discussions/discussion.coffee, resources/assets/coffee/react/beatmap-discussions/discussions.coffee, resources/assets/less/bem/beatmap-discussions.less, resources/assets/less/bem/btn-osu-lite.less, resources/lang/en/beatmaps.php
=> Allow beatmap discussions sorting by post or updated time 

resources/assets/coffee/_classes/menu.coffee, resources/views/layout/_popup_menu.blade.php
=> Limit nav menu auto-sizing to the nav menu

app/Models/Beatmapset.php
=> Fix nullref in approved_date setter

app/Models/Beatmapset.php
supersedes  #2101 
Fixes artist, title and difficulty sorting
=> Fix beatmap search sorting to use correct elasticsearch fields

app/Console/Commands/EsIndexCommand.php, app/Console/Commands/EsIndexDocuments.php, app/Console/Commands/EsIndexUsers.php, app/Console/Kernel.php, app/Models/Elasticsearch/UserTrait.php, app/Models/User.php, app/Traits/EsIndexable.php, app/helpers.php
Allow fancy pants username searching.
Prioritises exact matches, then fancy pants partial matching
Should fix #1863 and works for short usernames in #1788
Closes #2012 (i think)
=> User search with elasticsearch

resources/assets/coffee/_classes/store-supporter-tag-price.coffee, resources/lang/en/common.php, resources/lang/en/supporter_tag.php, resources/lang/fr/common.php, resources/lang/fr/supporter_tag.php, resources/lang/ko/common.php, resources/lang/ko/supporter_tag.php, resources/lang/pl/common.php, resources/lang/pl/supporter_tag.php, resources/lang/pt-br/common.php, resources/lang/pt-br/supporter_tag.php, resources/lang/ru/common.php, resources/lang/ru/supporter_tag.php, resources/lang/sv/common.php, resources/lang/sv/supporter_tag.php, resources/lang/zh/common.php, resources/lang/zh/supporter_tag.php
Cleanups. Doesn't \<verb\> #2144 because I don't speak pl ┐(° ヮ° )┌
=> General month/year count

app/Models/Store/OrderItem.php, app/Models/SupporterTag.php, resources/assets/coffee/_classes/store-supporter-tag-price.coffee
=> Fix supporter tag email translation

resources/assets/less/bem/beatmap-icon.less, resources/assets/less/variables.less
=> Use and update existing difficulty color variables

resources/assets/coffee/react/beatmap-discussions/discussions.coffee, resources/assets/coffee/react/beatmap-discussions/main.coffee
=> More deterministic beatmap discussion post ordering

app/Http/Controllers/UsersController.php, app/Libraries/BBCodeFromDB.php, app/Libraries/CleanHTML.php, resources/assets/coffee/_classes/user-card.coffee
With card. And allow string based id for card.
Fixes #2139.
=> New user profile url

resources/assets/coffee/react/beatmap-discussions/post.coffee
Fixes #2135. Also reverts message on cancel.
=> Fix discussion cancel

resources/views/home/_search_advanced_forum_post.blade.php
=> Cast to int when comparing forum id

app/Http/Controllers/FriendsController.php, app/Http/Controllers/RankingController.php, app/helpers.php
=> Add user cover to ranking results

app/Models/Beatmap.php, app/Transformers/BeatmapTransformer.php
=> Proper key amount for convert maps

app/Models/Beatmap.php
=> Prevent division by zero

package.json, resources/assets/coffee/react/beatmap-discussions/post.coffee, resources/lang/en/common.php, webpack.mix.js, yarn.lock
clicking 'permalink' now copies the permalink url to the clipboard
fixes #1848
=> Make beatmapset discussion permalinks useful

app/Listeners/Fulfillments/PaymentSubscribers.php
=> $eventName missing from closure

app/Models/BeatmapDiscussionPost.php, resources/assets/coffee/_classes/beatmap-discussion-helper.coffee
=> Increase beatmapset discussion post character limit

app/Models/Beatmapset.php
=> Skip saving beatmapset on refresh if no change

app/Models/Beatmapset.php
Not sure how no-one noticed until now..
=> Fix beatmapset cover regeneration using stale cached images

resources/assets/coffee/react/beatmap-discussions/nominations.coffee
=> Don't change modes for leaving feedback

app/Exceptions/Handler.php, app/Providers/AuthServiceProvider.php, build.sh, composer.json, composer.lock, database/migrations/2017_02_06_083745_nullable_cover_json_on_user_profile_customizations.php, tests/Hashing/OsuHasherTest.php
And packages (just php). Needs more testing but at least the tests are green 🥗 
On unrelated note, it seems the tumblr package isn't used anymore.
=> Latest laravels

app/Http/Controllers/PasswordResetController.php
=> Fix password reset error handler

config/datadog-helper.php
=> Remove default prefix from datadog-helper

.env.example, .travis.yml, bin/mysql_debian_install
=> Container travis

app/Jobs/EsDeleteDocument.php, app/Jobs/EsIndexDocument.php, app/Models/Beatmapset.php, app/Traits/EsIndexable.php
Seems to work
fixes #2195 
as a side note, I don't think `refreshCache()` should be automagically indexing the document; `save()`, yes, but not `refreshCache()`
=> dispatch elasticsearch asynchronously when refreshing hypes

composer.json, composer.lock
- remove tumblr
- laravel minor update
- ~clockwork update, now with cache viewer ヽ( ﾟ ヮﾟ)ﾉ~ or maybe not because it's rather broken ヽ( ﾟ ヮﾟ)ﾉ itsgoingd/clockwork#203
=> More updates

app/Http/Controllers/LegacyInterOpController.php, routes/web.php
=> Add LIO endpoint for refreshing beatmapset cache

app/Models/BeatmapPack.php, resources/assets/less/bem/beatmap-pack-download.less, resources/views/packs/show.blade.php
fixes #2235
left the `foreach (explode(...` in until the dev data removes them
=> Change beatmap pack to single download

resources/assets/coffee/react/beatmap-discussions/discussions.coffee
Give each tab its own sort order.
fixes #2232
=> Handle beatmap discussion sorting per-tab

app/Http/Controllers/AccountController.php, resources/assets/coffee/_classes/form-clear.coffee, resources/lang/en/accounts.php, resources/lang/es/accounts.php, resources/lang/fr/accounts.php, resources/lang/ko/accounts.php, resources/lang/pl/accounts.php, resources/lang/pt-br/accounts.php, resources/lang/ru/accounts.php, resources/lang/sv/accounts.php, resources/lang/zh/accounts.php, resources/views/accounts/_edit_email.blade.php, resources/views/accounts/_edit_password.blade.php, tests/Controllers/AccountControllerTest.php
Use browser's reset form. And remove popup because there's already indicator right next to the submit button.
Fixes #2224.
=> Better form clear

resources/assets/coffee/react/beatmap-discussions/nominations.coffee
I don't think there's any scenario where we'd need to hide the nominators 🤷‍♂️
fixes #2176
=> Always show nominators (if present)

app/Http/Controllers/BeatmapDiscussionPostsController.php, app/Libraries/OsuAuthorize.php
=> Fix resetting nominations checking against daily nomination quota

resources/assets/coffee/react/beatmap-discussions/discussions.coffee
=> Always put mapper note at the top

app/Http/Controllers/BeatmapPacksController.php, app/Models/BeatmapPack.php, resources/assets/less/bem/beatmap-packs.less, resources/assets/less/bem/paginator.less, resources/views/packs/index.blade.php
=> Paginate beatmap pack list and use the same sort on all types.

database/seeds/ModelSeeders/ForumSeeder.php
While seeding forums, also adds a forum for userpages at the defauld id in config. Useful for when someone might want to test userpages, i guess.
=> Create userpage forum when seeding

app/Models/Beatmapset.php, resources/assets/coffee/_classes/beatmapset-filter.coffee, resources/assets/coffee/react/beatmaps/search-sort.coffee
=> Allow and default sorting by updated for own maps

resources/assets/lib/store-checkout.coffee, resources/views/store/_checkout_centili.blade.php
=> Make centili payments send cart to processing state.

tests/TestCase.php
Seems to fix transaction error in #2182 😕 ❓
=> Add more databases for transaction thingy

app/Models/Forum/Post.php, app/Models/Forum/Topic.php, app/helpers.php
=> Handle null time

app/Models/BeatmapDiscussion.php
=> Don't explode encountering deleted beatmapset

resources/lang/en/forum.php, resources/lang/es/forum.php, resources/lang/fr/forum.php, resources/lang/it/forum.php, resources/lang/ko/forum.php, resources/lang/nl/forum.php, resources/lang/pl/forum.php, resources/lang/pt-br/forum.php, resources/lang/ru/forum.php, resources/lang/sv/forum.php, resources/lang/zh/forum.php, resources/views/home/_search_forum_post.blade.php
Comes with lang file sorting =]
=> Don't fail on deleted topic in search

app/Mail/ForumNewReply.php, app/Mail/PasswordReset.php, app/Mail/SupporterGift.php, app/Mail/UserEmailUpdated.php, app/Mail/UserPasswordUpdated.php, app/Mail/UserVerification.php
ヽ( ﾟ ヮﾟ)ヮﾟ)ヮﾟ)ヮﾟ)ヮﾟ)ヮﾟ)ヮﾟ)ヮﾟ)ヮﾟ)ヮﾟ)ヮﾟ)ヮﾟ)
=> Queue mails

app/Models/User.php, composer.json, composer.lock, resources/lang/en/model_validation.php
Apparently the one used by laravel.
=> Actual email validator

resources/assets/coffee/_classes/beatmap-discussions-chart.coffee, resources/assets/coffee/_classes/tooltip-default.coffee, resources/assets/less/bem/beatmap-discussions-chart.less, resources/assets/less/bem/tooltip-default.less
- remove underline hover on firefox
- correct mouse cursor on chrome
- add tooltip on hover
=> Better discussion chart link

resources/assets/coffee/osu_common.coffee, resources/assets/coffee/react/mp-history/main.coffee
=> Autoscroll bottom

app/Models/BeatmapDiscussion.php, resources/assets/coffee/react/beatmap-discussions/main.coffee
=> Only count visible beatmaps for open issues

app/Models/Beatmapset.php
=> Reindex beatmapset after commit

app/Models/Score/Best/Model.php
=> Fix scoreboard sorting

.travis.yml, app/Console/Commands/LocaleCheck.php, app/Console/Kernel.php
Stuff ヽ( ﾟ ヮﾟ)ﾉ (also in travis)
```
artisan locale:check
```
=> Basic locale check command

app/Http/Controllers/Admin/Store/OrdersController.php, app/Http/Controllers/StoreController.php, app/Models/Store/Order.php, app/Models/Store/OrderItem.php, app/Models/Store/Product.php, config/store.php, resources/views/admin/store/orders/show.blade.php, resources/views/store/invoice.blade.php, resources/views/store/objects/order.blade.php
- order orders by date paid
- invoices for shipping should only show items that are shippable.
=> Store admin shipping tweaks

resources/assets/coffee/react/profile-page/extra-tab.coffee, resources/assets/coffee/react/profile-page/main.coffee, resources/assets/less/bem/page-mode.less
Lock sortable drag item within its container.
Kind of fixes #2320.
=> Slightly better profile page sortable

resources/assets/coffee/react/profile-page/stats.coffee, resources/assets/less/bem/profile-stats.less, resources/lang/en/common.php, resources/lang/en/users.php
=> Pluralize play time units

app/Models/Wiki/Page.php
```
tags:
- some stuff
- that can
- be searched
```
Fixes #2261?
=> Add support for wiki page tags

resources/assets/coffee/react/_components/friend-button.coffee, resources/assets/less/bem/friend-button.less
=> Use css for friend button hover

resources/assets/coffee/react/_components/user-avatar.coffee, resources/assets/coffee/react/profile-page/header-info.coffee, resources/lang/en/users.php, resources/views/accounts/edit.blade.php
=> Add a link to avatar edit on the avatar in user profile

app/Models/BeatmapDiscussion.php, app/Models/BeatmapDiscussionPost.php, tests/Models/BeatmapDiscussionPostTest.php, tests/Models/BeatmapDiscussionTest.php
=> Allow discussion/post delete

README.md, build.sh, docker-compose.yml, docker/php/Dockerfile, docker/php/setup.sh, docker/yarn/Dockerfile, docker/yarn/setup.sh
* don't cache config and routes when in debug env (`APP_DEBUG` is not `false`)
* ~~upgrade PHP to 7.2~~ not yet, pending library updates
* switch yarn to a self-installed setup (as `npm install yarn` is apparently deprecated)
* add redis and elasticsearch
=> Docker updates

resources/assets/coffee/react/beatmap-discussions/beatmap-list-item.coffee
=> Uppercased keys count suffix

app/Http/Controllers/Forum/ForumsController.php
=> Increase per-page topics listing

resources/assets/coffee/react/_components/play-detail.coffee, resources/assets/less/bem/beatmapset-panel.less, resources/assets/less/bem/detail-row.less
=> Less whitespace

resources/assets/less/bem/beatmap-basic-stats.less
=> Bigger stat icon and fixed spacings

app/Http/Controllers/UsersController.php, app/Models/UserProfileCustomization.php, app/Transformers/UserTransformer.php, resources/assets/coffee/react/profile-page.coffee, resources/assets/coffee/react/profile-page/main.coffee, resources/assets/coffee/react/profile-page/recent-activities.coffee, resources/assets/coffee/react/profile-page/recent-activity.coffee, resources/lang/da/users.php, resources/lang/en/users.php, resources/lang/es/users.php, resources/lang/fr/users.php, resources/lang/it/users.php, resources/lang/ko/users.php, resources/lang/nl/users.php, resources/lang/pl/users.php, resources/lang/pt-br/users.php, resources/lang/ru/users.php, resources/lang/sv/users.php, resources/lang/zh/users.php, routes/web.php
=> Add 'show more' for recent activity on user profiles

resources/assets/less/bem/beatmap-basic-stats.less
Forgot to update margin of the container.
=> Fix margin for basic map stats

app/Http/Controllers/BeatmapsetsController.php, app/Models/Beatmapset.php, app/Transformers/BeatmapsetTransformer.php, resources/assets/coffee/react/beatmapset-page/info.coffee, resources/assets/less/bem/beatmapset-info.less, resources/lang/en/beatmapsets.php
- show genre
- show language
- limit tags to 20 (and show '...' if applicable)
- extend the box height up to 270px
- adjust description box to new height
Fixes #2383.
=> Show genre and language and fix styles

resources/views/home/_user_beatmapset.blade.php
=> Show usercard for mapper name in welcome page

resources/assets/less/bem/news-post-preview.less, resources/assets/less/bem/user-home.less, resources/lang/en/common.php, resources/views/home/user.blade.php
No link for beatmapset because there's no listing page for last 24h popular ┐(' ヮ' )┌
Fixes #2394.
=> Link to news index

resources/assets/coffee/react/beatmap-discussions/main.coffee
=> Don't fail when there's deleted beatmap

app/Http/Controllers/AccountController.php, app/Models/User.php, resources/assets/coffee/react/profile-page/header-main.coffee, resources/assets/coffee/react/profile-page/header.coffee, resources/assets/less/bem/page-mode.less, resources/assets/less/bem/profile-header.less, resources/lang/en/users.php
Fixes #2368. Can use a bit cleanup.
=> Allow setting default playmode in profile page

resources/views/forum/forums/_topic.blade.php
=> Different icon for unread topic

resources/lang/en/beatmaps.php
Fixes #2434
I hope I'm doing this right ò.ó
=> Revise English remaining hype message

resources/assets/less/bem/profile-extra-user-page-editor.less
Not sure why it's disabled.
Fixes #2479.
=> Allow resizing me! input box

app/Models/User.php
=> Filter out inactive maps from profile

resources/assets/coffee/_classes/menu.coffee, resources/assets/coffee/_classes/nav.coffee, resources/views/layout/_popup_menu.blade.php
=> Decouple nav menu resize from generic menu class

app/Libraries/OsuAuthorize.php, resources/lang/en/authorization.php, tests/Controllers/BeatmapDiscussionsControllerTest.php
Fixes #2350.
Backend only. Frontend side will be done later... maybe...
=> Limit voting based on current beatmapset state

resources/assets/coffee/react/profile-page/main.coffee
=> Missed update to snake case

resources/assets/less/bem/logo-menu.less, resources/assets/less/bem/nav-popup.less, resources/assets/less/bem/navbar-mobile-item.less, resources/assets/less/bem/user-verification.less, resources/views/layout/_popup_user.blade.php, resources/views/layout/header_mobile/user.blade.php, resources/views/objects/logo-menu.blade.php, resources/views/users/_verify_box.blade.php
=> Logout links are button.

app/Libraries/TransactionStateManager.php, app/Providers/TransactionStateServiceProvider.php
=> TransactionState cleanups

app/Libraries/TransactionStateManager.php, tests/Libraries/Transactions/AfterCommitTest.php, tests/TestCase.php
dispatching to queue breaks destructor timing or something ┐(ツ)┌
=> Force disconnection after every test

resources/assets/coffee/_classes/tooltip-default.coffee, resources/assets/coffee/react/profile-page/header-extra.coffee, resources/assets/less/bem/forum-topic-nav.less, resources/assets/less/bem/tooltip-default.less, resources/assets/less/forum/base.less, resources/views/forum/forums/_forums.blade.php
Fixes #2146, fixes #2513, and some other stuff people may or may not have noticed.
=> Tooltip update

resources/assets/less/bem/nav-popup.less
=> Unify case for locale menu

resources/lang/da/layout.php, resources/lang/en/layout.php, resources/lang/es/layout.php, resources/lang/fr/layout.php, resources/lang/it/layout.php, resources/lang/ko/layout.php, resources/lang/nl/layout.php, resources/lang/pl/layout.php, resources/lang/pt-br/layout.php, resources/lang/ru/layout.php, resources/lang/sv/layout.php, resources/lang/zh/layout.php
=> Replace "Log Out" with "Sign Out"

resources/assets/coffee/react/profile-page/historical.coffee
=> Add usercard to profile historical listing

app/Models/BeatmapDiscussion.php, app/Models/BeatmapDiscussionPost.php, resources/assets/coffee/react/beatmap-discussions/post.coffee
Also fixes random test failure. Apparently it never worked. The test usually worked because the time hasn't changed from the previous update/restore.
=> Fix softDelete of beatmapset discussion post 

app/Http/Controllers/BeatmapsetsController.php, resources/lang/da/layout.php, resources/lang/en/layout.php, resources/lang/es/layout.php, resources/lang/fr/layout.php, resources/lang/it/layout.php, resources/lang/ko/layout.php, resources/lang/pl/layout.php, resources/lang/pt-br/layout.php, resources/lang/ru/layout.php, resources/lang/sv/layout.php, resources/lang/zh/layout.php, resources/views/beatmapsets/discussion.blade.php, resources/views/beatmapsets/show.blade.php, resources/views/forum/forums/show.blade.php, resources/views/forum/topics/show.blade.php, resources/views/master.blade.php, resources/views/news/index.blade.php, resources/views/news/show.blade.php, resources/views/store/products/show.blade.php, resources/views/wiki/show.blade.php
Flipped stuff around. Additionally added "| osu!" at the end. Inputs welcome.
Fixes #2108.
=> Improved page title

resources/views/home/landing.blade.php, resources/views/layout/footer.blade.php
=> Remove footer links on landing page

resources/assets/coffee/react/profile-page/beatmaps.coffee, resources/assets/coffee/react/profile-page/kudosu.coffee, resources/assets/coffee/react/profile-page/recent-activity.coffee, resources/assets/coffee/react/profile-page/show-more-link.coffee, resources/assets/coffee/react/profile-page/top-ranks.coffee, resources/assets/less/bem-index.less, resources/assets/less/bem/profile-extra-entries.less, resources/assets/less/bem/show-more-link.less
=> Full width show more link

resources/lang/en/users.php, resources/views/objects/_usercard.blade.php
Thanks, laravel variable scoping.
=> Usercard loading name

resources/assets/less/bem/mp-history-game.less
=> Reduce mp header text size on mobile

app/Libraries/BBCodeFromDB.php, app/Listeners/Forum/NotifySlack.php, app/Models/Event.php, app/Models/User.php, app/helpers.php
PHP is awesome like that.
Fixes #2549.
=> Unify call for html entity decode function

resources/assets/less/bem/beatmap-discussion-nomination.less, resources/assets/less/bem/beatmap-discussions-header-bottom.less
=> Enforce word break on nomination box

resources/assets/less/bem/beatmapset-event.less
=> Text wrap for history page

app/Transformers/UserTransformer.php, resources/assets/coffee/react/profile-page/header-extra.coffee, resources/lang/en/users.php
#2059
no link to post history yet, that will be separate
=> Show post count on user profile page

resources/assets/less/bem/avatar.less, resources/views/layout/_header_user.blade.php
Not sure what the bug was :dancer: 
Fixes #2537.
And less redundant rounding.
=> Avatar positioning

app/Models/Beatmap.php, app/Transformers/BeatmapTransformer.php, resources/assets/coffee/_classes/beatmap-helper.coffee, resources/assets/coffee/react/beatmap-discussions/beatmap-list-item.coffee
More convenient when searching.
=> Show keys for osu!mania maps

app/Transformers/BeatmapTransformer.php, resources/assets/coffee/_classes/beatmap-helper.coffee, resources/assets/coffee/react/beatmap-discussions/beatmap-list-item.coffee
=> Remove redundant attribute

resources/assets/coffee/osu_common.coffee
It's been comparing between function and integer all this time woo \o/
<sup><sup><sup>thanks javascript</sup></sup></sup>
=> Fix bottom page detection function

resources/assets/coffee/forum/post-box.coffee, resources/assets/coffee/react/profile-page/user-page-editor.coffee
=> Trigger react state change when inserting bbcode

resources/assets/coffee/react/profile-page/header-extra.coffee, resources/lang/pl/users.php
=> Format user profile post count

app/Models/Wiki/Page.php
=> Add fallback locale in path-based search for redirect

app/Libraries/Elasticsearch/Highlight.php
=> Highlight defaults are backwards

resources/assets/coffee/react/_components/beatmapset-mapping.coffee
Fixes #2547. Unifying everything took a bit too long (and initial attempt looked terrible) so this should work in the meantime.
=> Add usercard on mapper name and link avatar to profile

app/Http/Controllers/Controller.php, app/Libraries/LocaleMeta.php, app/Libraries/OsuMarkdownProcessor.php
=> Markdown and locale updates

app/Models/BeatmapFile.php
some of them old beatmaps were _great_ 🤷‍♂️
=> Add more fallbacks for missing backgrounds

resources/assets/coffee/react/beatmapset-page/header.coffee
=> Don't specify noVideo if the beatmapset doesn't contain a video

resources/assets/coffee/react/beatmapset-page/score-top.coffee, resources/assets/coffee/react/beatmapset-page/scoreboard-table.coffee, resources/assets/coffee/react/mp-history/score.coffee, resources/assets/coffee/react/profile-page/header-info.coffee, resources/assets/less/bem/avatar.less, resources/assets/less/bem/beatmap-score-top.less, resources/assets/less/bem/tooltip-default.less, resources/assets/less/variables.less
Fixes #2669. Cleaned up some styles while at it.
=> Tooltips and flag links

resources/assets/coffee/_classes/beatmap-helper.coffee
=> Avoid selecting deleted beatmap as default

resources/assets/coffee/react/_components/beatmapset-panel.coffee, resources/assets/coffee/react/beatmapset-page/header.coffee, resources/assets/less/bem/beatmapset-header.less, resources/assets/less/bem/beatmapset-panel.less, resources/lang/en/beatmapsets.php
=> Add beatmap status to beatmap panels and beatmap page

resources/assets/coffee/_classes/nav-search.coffee
Should give more time for slower typists to get their search query in.
fixes #2667
=> Increase debounce delay for searches

resources/assets/coffee/store-username-change.coffee, resources/lang/en/store.php, resources/views/store/products/username-change.blade.php
ಠ_ಠ
and make strings localizable
=> Store username change script shouldn't be setting html

app/Models/Beatmapset.php
I think this is correct-ish without using string matching.
...maybe.
Fixes #2703.
=> Update ranking eta calculation

app/Models/Beatmap.php
Wrong minimum value. Updated reference link while at it.
=> Fix converted mania keys calculation

app/framework_helper_overrides.php
Otherwise wrong pluralization system will be used.
=> Explicitly set locale when using fallback in trans_choice

resources/lang/en/home.php, resources/lang/fr/community.php, resources/lang/fr/home.php, resources/lang/it/community.php
=> Language changes (free-to-win)

app/Traits/EsIndexable.php
=> Fix elasticsearch deprecation warnings

resources/assets/less/bem/navbar-mobile-item.less
=> force mobile navbar to use lowercase

app/Models/User.php
Prevents user profiles with scores on deleted beatmaps from breaking.
=> Handle scores for deleted beatmaps in more places.

app/Models/Beatmapset.php, config/osu.php
Quick fix to cache some of the results of the beatmap listing to reduce the queue size on elasticsearch.
=> Cache beatmap listing search result

app/Http/Controllers/Forum/ForumsController.php, app/Models/Forum/Forum.php, database/factories/ForumFactory.php, resources/views/forum/forums/_forums.blade.php
=> Faster forum index/show

resources/assets/less/bem/profile-badges.less
=> Update profile badge size

resources/assets/less/bem/profile-badges.less
=> Fix badge size

app/helpers.php, config/osu.php, resources/lang/da/layout.php, resources/lang/en/layout.php, resources/lang/es/layout.php, resources/lang/fr/layout.php, resources/lang/it/layout.php, resources/lang/ko/layout.php, resources/lang/pl/layout.php, resources/lang/pt-br/layout.php, resources/lang/ru/layout.php, resources/lang/sv/layout.php, resources/lang/zh-tw/layout.php, resources/lang/zh/layout.php
stat.ppy.sh has been deprecated
=> Update footer link to server status

app/Http/Controllers/BeatmapDiscussionPostsController.php, app/Http/Controllers/BeatmapsetsController.php, app/Jobs/NotifyBeatmapsetUpdate.php, app/Models/BeatmapsetWatch.php
=> Improve "last update time" used for checking beatmap notification

resources/assets/less/bem/profile-badges.less
Now with less rounded badges ಠ_ಠ
=> Update badge style

app/Http/Controllers/HomeController.php, resources/assets/coffee/react/_components/friend-button.coffee, resources/assets/coffee/react/profile-page/header-extra.coffee, resources/assets/less/bem-index.less, resources/assets/less/bem/friend-button.less, resources/assets/less/bem/profile-header-extra.less, resources/assets/less/bem/user-action-button.less, resources/lang/en/users.php, resources/views/forum/topics/_posts.blade.php, resources/views/objects/_usercard.blade.php, routes/web.php
- add temporary pm link/button
- fix forum posts rendering when starting with deleted post
Not sure why I got unassigned #2813 but this branch got some other useful stuff in it so figured might as well :dancer: 
(can remove the pm commit if needed)
=> Misc fixes and user pm link

resources/assets/coffee/_classes/click-menu.coffee, resources/assets/coffee/_classes/nav2.coffee, resources/assets/less/bem/bg.less, resources/assets/less/bem/login-box.less, resources/assets/less/bem/nav2-header.less, resources/assets/less/bem/nav2.less, resources/assets/less/bem/simple-menu.less, resources/assets/less/variables.less, resources/views/layout/_popup_user.blade.php, resources/views/layout/header.blade.php
- link profile popup header to profile
- so margin adjustments for the popup
- cleanups
=> Header fixes

resources/lang/en/forum.php
=> Remove unnecessary "on" from edited message

resources/assets/coffee/_classes/user-login.coffee, resources/assets/coffee/react/_components/bbcode-editor.coffee, resources/assets/coffee/react/profile-page/user-page-editor.coffee
- missed an update when changing to bbcode editor component
- hide login box after logged in
=> Show verification and hide login fixes

app/Libraries/OsuAuthorize.php, app/Models/BeatmapDiscussion.php, app/Transformers/BeatmapsetTransformer.php
And then snowballed into ensuring discussion always has beatmapset
=> Fix kudosu grant check

resources/assets/less/forum/base.less
=> Increase the margins for .forums

resources/assets/less/layout.less
Not sure why ┐(ಠ_ಠ)┌
Fixes #2926.
=> Fix tooltip positioning on Edge

app/Http/Controllers/BeatmapsetWatchesController.php, app/Models/BeatmapsetWatch.php
=> Hide inactive beatmapsets from watch list

resources/lang/da/artist.php
Fixing the title and fixing missunderstandings
=> Danish translation fix 1

resources/lang/da/layout.php
=> Danish translation fix 2

database/migrations/2018_04_12_080404_add_index_to_achievements_name.php
=> Add index to achievements name column

app/Http/Controllers/ArtistsController.php, database/migrations/2018_04_12_085114_add_spotify_and_osu_profile_to_artists.php, resources/assets/less/bem/artist-link-button.less, resources/assets/less/colors.less, resources/lang/en/artist.php, resources/views/artists/show.blade.php
=> Add Spotify and osu! profile links to Featured Artists' pages

resources/assets/coffee/react/profile-page/show-more-link.coffee
Import `i` used for the spinner.
Fixes #2986.
=> Fix show more link in user profile

app/Http/Controllers/UsersController.php, app/Models/UsernameChangeHistory.php, app/Transformers/UserTransformer.php, resources/assets/coffee/react/profile-page/header-info.coffee, resources/lang/en/users.php
A very basic one. Fixes #2013.
=> Username history

app/Models/BeatmapsetEvent.php, resources/assets/coffee/react/beatmap-discussions/event.coffee, resources/lang/da/beatmapset_events.php, resources/lang/en/beatmapset_events.php, resources/lang/es/beatmapset_events.php, resources/lang/ko/beatmapset_events.php, resources/lang/pl/beatmapset_events.php, resources/lang/pt-br/beatmapset_events.php, resources/lang/sv/beatmapset_events.php, resources/lang/zh-tw/beatmapset_events.php, resources/lang/zh/beatmapset_events.php, resources/views/beatmapset_events/_item.blade.php
Forgot to actually do this. Now with preview for nomination resets as well.
Fixes #2982.
=> Update event component to handle new disqualification

app/Http/Controllers/UsersController.php, app/Transformers/UserTransformer.php, resources/assets/coffee/react/profile-page/header-info.coffee, resources/lang/en/users.php
Less misleading because its content is very simple.
=> Rename previous usernames include

resources/assets/coffee/osu_common.coffee, resources/assets/less/bootstrap-variables.less
=> Fix osu.isDesktop/isMobile

resources/assets/coffee/react/profile-page/header-info.coffee, resources/assets/less/bem-index.less, resources/assets/less/bem/profile-info.less, resources/assets/less/bem/profile-previous-usernames.less, resources/assets/less/variables.less, resources/lang/en/users.php
Doesn't quite work on mobile ┐(°～° )┌
=> Updated design for displaying previous usernames

app/Libraries/OsuMarkdownProcessor.php, app/Libraries/OsuTableRenderer.php, resources/assets/less/bem/osu-md.less
=> Wrap table in container

resources/assets/coffee/_classes/click-menu.coffee, resources/views/layout/_header_user.blade.php
=> Allow middle clicking profile icon

resources/assets/less/bem/user-action-button.less
=> Fix friend button icons on hover

resources/assets/coffee/react/beatmapset-page/score-top.coffee, resources/assets/less/bem/beatmap-score-top.less
=> Add achievement date to top score

resources/assets/less/bem/beatmapset-panel.less
Was done on wrong place.
Fixes #2706.
=> Correctly hide beatmapset status icons

resources/lang/da/accounts.php, resources/lang/en/accounts.php, resources/lang/es/accounts.php, resources/lang/fr/accounts.php, resources/lang/ko/accounts.php, resources/lang/pl/accounts.php, resources/lang/pt-br/accounts.php, resources/lang/ru/accounts.php, resources/lang/sv/accounts.php, resources/lang/zh-tw/accounts.php, resources/lang/zh/accounts.php
Redoing the forgotten pull request (#2501).
=> Remove 'edit' word from account settings page

resources/assets/coffee/react/profile-page/header-extra.coffee
=> Hide scheme from user web link text

app/Transformers/ContestEntryTransformer.php, config/osu.php, resources/assets/coffee/react/contest/voting/art-entry.coffee
hopefully this will be _temporary_
=> Add hacky support for art contest thumbnails

app/Http/Controllers/ChangelogController.php, app/Models/BuildPropagationHistory.php, resources/views/changelog/_changelog_build.blade.php
- handle new versioning scheme
- hide online users counter if 0
=> Changelog version fix

resources/assets/coffee/react/_components/play-detail.coffee
Until score tables get the pp data...?
=> Less misleading title when pp data doesn't exist for ranked maps

app/Models/Beatmapset.php, database/migrations/2018_04_20_100654_add_queue_time_to_beatmapsets.php
Something like this...? Seems working.
=> Update beatmapset ranking queue system

resources/assets/less/bem/forum-topic-reply.less
=> Solid color for reply form background

resources/assets/coffee/react/profile-page/historical.coffee
=> Allow chart ticks to be fewer than 6 in mobile

app/Models/User.php
And minor fixes to the setter.
Fixes #3061.
=> Filter user website value on output as well

app/Libraries/BBCodeForDB.php, app/Libraries/BBCodeFromDB.php
Part of #2930. 
Not sure about url shortening because I sometimes find it annoying instead of useful (cuts possibly interesting part of url, more difficult to copy multiple urls).
=> Properly show shortened url when editing post

resources/assets/less/bem/account-edit-entry.less, resources/assets/less/bem/btn-osu-big.less, resources/lang/en/accounts.php, resources/lang/en/common.php, resources/views/accounts/edit.blade.php
After internal discussion we decided it made more sense to put the link on the user settings page amongst the rest of the changeable user profile fields.
fixes #2421
=> Add button on user profile linking to change username store page

resources/assets/less/bem/beatmap-discussion-new.less
The reply and edit box already uses correct font.
=> Use correct font for new discussion text box

.gitignore
=> Ignore yarn error log file and remove irrelevant npm ignore

app/Libraries/BBCodeFromDB.php
I was blind and didn't notice the quotes are different.
Fixes #3088. Hopefully old forum handles both cases =]
=> Fix bbcode url editing

app/Exceptions/Handler.php, resources/views/layout/error.blade.php
A bit too *verbose* at the moment. Also unifies the message generation between ajax and html.
=> Less verbose error message

app/Http/Controllers/Users/ModdingHistoryController.php, app/Models/Beatmapset.php, resources/views/beatmapset_events/_item.blade.php
also skips modding history for bots
=> fix modding history events page if beatmapset was deleted

docker-compose.yml
Apparently 8.0 dropped a few days ago :dancer:
=> Keep Docker MySQL container version at 5.7

resources/lang/es/users.php
I have deleted a placeholder that wasn't being used and was appearing on the user page, that's all.
=> [ES] Changes on User page 

resources/assets/coffee/react/beatmap-discussions/new-discussion.coffee
=> Sort discussion by timestamp

app/Transformers/UserCompactTransformer.php, resources/assets/coffee/react/beatmap-discussions/post.coffee, resources/lang/en/beatmap_discussion_posts.php
=> Add tooltip to modding history link & hide on bots

app/Http/Controllers/Users/ModdingHistoryController.php
=> Redirect user modding history to path using the user id

resources/assets/less/bem/beatmap-discussions-header-top.less, resources/assets/less/bem/counter-box.less
=> Fix discussion counts wrapping under chart on mobile

app/Libraries/Payments/PaymentProcessor.php
will be handled manually instead
=> Skip releasing of reserved stock on cancelled payments

resources/assets/coffee/react/beatmap-discussions/header.coffee, resources/assets/coffee/react/beatmap-discussions/main.coffee
=> Only show discussion starters in user filter

app/Models/Score/Model.php
Filter out plays on deleted beatmap.
=> Fix recent plays listing on user page

app/Models/Tournament.php, database/migrations/2018_05_09_083801_add_wiki_and_store_link_to_tournaments.php, resources/assets/less/base.less, resources/assets/less/bem/tournament.less, resources/lang/en/tournament.php, resources/views/tournaments/show.blade.php
Link to support the team and wiki page.
=> Add more info to tournament page

resources/assets/less/bem/profile-header.less
Scale on the image itself instead of the container.
=> Fix tournament banner scaling

resources/views/objects/_usercard.blade.php
https://osu.ppy.sh/store/products/208
=> Only show pm icon if user exists

resources/assets/less/bem/btn-osu-big.less
When the text gets a bit too long...
=> Allow larger button in beatmapset header

app/Libraries/OsuAuthorize.php
Skip checking topic if it doesn't exist.
=> Fix editing user page

resources/views/packs/index.blade.php, resources/views/store/checkout.blade.php
=> Don't escape trans where markup is passed by param

app/Http/Controllers/RankingController.php, resources/views/rankings/index.blade.php
=> Fix ranking page titles

app/framework_helper_overrides.php, tests/LocaleTest.php
=> Cleanup trans and trans_choice

app/Http/Controllers/UsersController.php, app/Models/Beatmapset.php, app/Models/User.php, app/Transformers/UserTransformer.php, resources/assets/coffee/react/profile-page/beatmaps.coffee, resources/assets/coffee/react/profile-page/main.coffee, resources/lang/en/users.php
fixes #2680
and reorder the includes in `UserTransformer`
=> Add loved beatmaps to user profile

app/Libraries/OrderCheckout.php
turns out there was a reason I did it the other way before 🔥
=> Don't add to error array if empty

resources/lang/en/home.php
=> Change new approved beatmaps to new ranked beatmaps

resources/assets/coffee/react/_components/user-avatar.coffee, resources/assets/coffee/react/beatmapset-page/header.coffee, resources/assets/less/bem/beatmapset-favourites.less
Update to use `UserAvatar` component which has the background.
Fixes #3233.
=> Fix avatar background in beatmap favorite popup

resources/assets/less/base.less
They look ugly.
Before:
After:
=> Never display iframe borders

config/osu.php, resources/assets/coffee/_classes/nav-button.coffee, resources/assets/coffee/main.coffee, resources/assets/less/bem/nav2.less, resources/views/layout/_nav2.blade.php
Now with more javascripts to hide the buttons when the window isn't wide enough.
=> Add social buttons menu bar

resources/assets/less/bem/supporter-icon.less, resources/views/objects/_supporter_icon.blade.php, resources/views/objects/_usercard.blade.php
Unifies the icon. Fixes #2695.
=> Remove supporter icon background color

resources/assets/coffee/react/beatmap-discussions/nominations.coffee
=> Switch mode if needed for new discussion buttons

resources/assets/coffee/react/_components/user-avatar.coffee
t'was breaking the beatmap modding page
=> Fix beatmap modding pages not working for guests

resources/assets/less/bem/account-edit-entry.less, resources/views/accounts/_edit_email.blade.php, resources/views/accounts/_edit_entry_simple.blade.php, resources/views/accounts/_edit_password.blade.php, resources/views/accounts/_edit_playstyle_checkbox.blade.php, resources/views/accounts/_edit_privacy.blade.php, resources/views/accounts/_edit_signature.blade.php
- text boxes doesn't have linked labels anymore
- rearrange checkboxes to limit label range
=> Update account settings labels

app/Models/Event.php
=> Add artist name in beatmapset qualification event

resources/assets/coffee/react/beatmap-discussions/beatmap-list.coffee
=> Fix overlay on navigation from beatmap discussion page

resources/assets/less/bem/page-extra-tabs.less, resources/assets/less/bem/page-mode.less
Scrapped the almost invisible texture. Fixes #2451.
=> Less padding on floating page extra tabs

resources/assets/less/bem/ranking-page.less, resources/views/rankings/index.blade.php
=> Add pagination above of ranking table

resources/assets/coffee/react/_components/beatmapset-panel.coffee, resources/lang/en/beatmapsets.php
In place of source.
Fixes #2555.
=> Show unranked update date in card

resources/views/beatmapset_watches/index.blade.php
=> Link cover in beatmapset watchlist to discussion page

resources/assets/coffee/_classes/beatmap-discussion-helper.coffee, resources/assets/coffee/_classes/forum.coffee, resources/assets/coffee/_classes/turbolinks-disqus.coffee, resources/assets/coffee/react/beatmap-discussions/user-filter.coffee
- avoid using `_` as variable in js
- restore lodash after loading disqus
- remove useless interpolation (not related)
=> Unbreak lodash

resources/assets/less/bem/simple-menu.less, resources/views/layout/_nav2.blade.php
=> Limit locale menu height

app/Http/Controllers/ChangelogController.php
Re-sort after merging legacy entries.
=> Fix changelog sort

app/Models/ChangelogEntry.php, resources/views/changelog/_changelog_change.blade.php
Less wall of links in changelog page. Fixes #3299.
=> Only link github pr number text

resources/views/beatmapset_watches/index.blade.php
=> Unwatch beatmap discussion buttons should have the same icon

resources/assets/coffee/_classes/user-login.coffee, resources/views/layout/_popup_login.blade.php
=> Clear previous sign in failure message when signing in again

resources/assets/coffee/_classes/forum-topic-reply.coffee, resources/assets/coffee/_classes/user-login.coffee, resources/assets/less/bem/forum-topic-reply.less, resources/lang/en/forum.php, resources/views/forum/topics/show.blade.php
- Shows sign-in popup if not signed in
- flashes the reply box when clicking reply while at the bottom of a thread.
fixes #2890
=> Prompt for login when clicking on forum thread reply button

app/Models/Beatmapset.php
=> Reset user rating on beatmapset qualification

app/Console/Commands/BuildsCreate.php, app/Console/Kernel.php, app/Models/UpdateStream.php
```
artisan builds:create --stream-id=7
```
Will create a `2018.619.0` build with orphan changelog entries. Or no build if there's no unused changelog entries.
=> Add command to generate build

app/Http/Controllers/ChangelogController.php, app/helpers.php, resources/views/changelog/_changelog_build.blade.php, resources/views/changelog/show.blade.php, routes/web.php
Redirect old urls to first build found.
=> Require stream name to view build

resources/lang/en/layout.php
Forgot about action name change.
=> Fix changelog show title

app/Http/Controllers/ChangelogController.php, resources/views/changelog/_changelog_build.blade.php
Fetched but wasn't actually used.
=> Use correct stream when finding build

.github/pull_request_template.md
Add a template with the new changelog-friendly PR description format.
=> Add a simple Pull Request template

resources/assets/less/bem/changelog-entry.less
=> Update changelog message styles

app/Libraries/OsuAuthorize.php
Sure is convenient with centralized auth source (hopefully) :dancer: 
Closes #3360.
---
=> Disallow nominator from resolving beatmap discussion issues

app/Http/Controllers/BeatmapDiscussionPostsController.php, app/Libraries/OsuAuthorize.php, app/Models/BeatmapDiscussion.php, resources/assets/coffee/react/beatmap-discussions/new-discussion.coffee, resources/lang/en/authorization.php, resources/lang/en/model_validation.php, tests/Controllers/BeatmapDiscussionPostsControllerTest.php, tests/Models/BeatmapDiscussionTest.php
=> Allow everyone authorized to post note

resources/assets/coffee/react/_components/build.coffee, resources/assets/coffee/react/changelog-build/main.coffee, resources/assets/less/bem/build.less
Version is now on top, with larger font, swapping place with build date getting smaller font.
---
=> Update changelog build page title styling

resources/lang/en/changelog.php, resources/views/changelog/build.blade.php
Fixes #3412. Not sure if should be capitalized or not.
---
=> More descriptive title for changelog build page

app/Http/Controllers/BeatmapDiscussionPostsController.php, app/Libraries/OsuAuthorize.php, app/Transformers/BeatmapDiscussionTransformer.php, resources/assets/coffee/react/beatmap-discussions/new-reply.coffee, tests/Controllers/BeatmapDiscussionPostsControllerTest.php
=> Allow everyone to reopen discussion issues

app/Models/User.php, app/Transformers/UserTransformer.php, resources/assets/coffee/react/profile-page/header-extra.coffee, resources/lang/en/users.php
Forgot to actually remove this.
---
=> Remove birthday

app/Traits/UserAvatar.php
Assign empty string if null.
---
=> Workaround not null constraint on user avatar

app/Models/Build.php, app/Models/ChangelogEntry.php, app/Models/Repository.php, app/Models/UpdateStream.php, database/migrations/2018_06_22_132317_link_streams_to_repositories.php
Adds many-to-many relationship between streams and repositories and allow creating build on orphan changelog specific to stream (instead of any streams).
---
=> Find changelog entry orphans by stream id

resources/assets/coffee/react/_components/bbcode-editor.coffee, resources/lang/en/common.php
=> Add confirmation on exiting editor with unsaved changes

app/Models/Beatmapset.php
Use helper method to ensure the unsigned number not subtracted to negative.
---
=> Fix error on negative favourite count

app/Http/Controllers/API/LegacyController.php, app/Http/Controllers/RankingController.php, app/Libraries/Search/BeatmapsetSearch.php, app/Models/CountryStatistics.php, app/Models/Score/Model.php, app/Models/UserStatistics/Model.php
Method name was too misleading 
---
=> Return class instead of new instance from getClass()

resources/lang/en/tournament.php, resources/views/tournaments/index.blade.php
Fixes #3461, not sure about the wordings.
---
=> Add tooltip for registered players count

resources/assets/coffee/_classes/beatmap-discussion-helper.coffee, resources/assets/coffee/react/beatmap-discussions/event.coffee, resources/assets/coffee/react/beatmap-discussions/nominations.coffee
- wrong usage of _.truncate
- unify message preview generation logic
- don't parse if truncated
Fixes #3456.
---
=> Fix beatmapset disqualification message preview

app/Http/Controllers/ChangelogController.php, app/Models/ChangelogEntry.php
Forgot to include after changing to actual relation.
---
=> Fewer queries on changelog index page

resources/assets/less/bem/osu-page-header-v3.less
Fixes #3483. Most likely leftover from initial attempts.
---
=> Flexible title height for new header

resources/lang/en/forum.php, resources/views/forum/forums/_forums.blade.php, resources/views/forum/forums/_topic.blade.php
Fixes #2808. Also fixed wordings in topic listing for topics without replies.
---
=> Prefix replied topics title with Re: in forum listing

app/helpers.php, resources/views/forum/topics/_post.blade.php
=> Add link to post editor profile

app/Jobs/RemoveBeatmapsetBestScores.php
force index beatmap_score_lookup
---
=> Force index when removing beatmapset high scores

resources/lang/en/beatmapset_events.php
=> More descriptive beatmap qualification event text

resources/assets/coffee/react/changelog-build/main.coffee
=> Fix layout on Changelog builds page

app/Libraries/Fulfillments/SupporterTagFulfillment.php, app/Mail/SupporterGift.php, tests/Libraries/Fulfillments/SupporterTagFulfillmentTest.php
=> Show correct supporter gift duration in mail

resources/assets/coffee/react/changelog-build/main.coffee
Yet another missed part when updating the header.
---
=> Hide menu page title when showing menu

app/Http/Controllers/BeatmapsetsController.php, app/Libraries/Search/BeatmapsetSearch.php, resources/lang/en/beatmaps.php
=> Cosmetic updates to beatmapset search filters

resources/lang/en/authorization.php
closes #3450
---
remove references to time
=> Change double post protection message

app/Http/Controllers/BeatmapsetsController.php, app/Libraries/OsuAuthorize.php, app/Models/Beatmapset.php, app/Models/BeatmapsetEvent.php, app/Models/Event.php, app/Models/UserGroup.php, app/Transformers/BeatmapsetTransformer.php, database/migrations/2018_07_26_110501_add_love_type_to_beatmapset_events.php, resources/assets/coffee/react/beatmap-discussions/nominations.coffee, resources/lang/en/beatmaps.php, resources/lang/en/beatmapset_events.php, routes/web.php
=> Allows beatmaps to be set as 'loved'

public/images/layout/store-logo-bg.svg
No more using all your cpu cycles while idling on the store page
---
=> Stop spinning the store logo

app/Http/Kernel.php, composer.json, composer.lock, config/app.php, config/clockwork.php, storage/.gitignore
- refresh its config
- ignore its sqlite default path
- remove manual loads as they're not needed anymore since 5.5
---
=> Update to latest clockwork

app/Http/Kernel.php, app/Http/Middleware/DisableSessionCookiesForAPI.php, app/Http/Middleware/VerifyCsrfToken.php
=> Prevent csrf and session cookies from being sent in API responses.

app/Events/Fulfillments/SupporterTagEvent.php, app/Libraries/Fulfillments/SupporterTagFulfillment.php, tests/Libraries/Fulfillments/SupporterTagFulfillmentTest.php
Make it easier for support to find the corresponding transaction for gifts.
---
=> Include recipient of supporter tag in admin notification

resources/views/forum/topics/_post.blade.php, resources/views/forum/topics/_post_hide_action.blade.php, resources/views/forum/topics/replace_delete_button.blade.php
=> Fix forum delete link visibility

app/Models/Score/Best/Model.php, app/Models/User.php, app/Models/UserReport.php, database/migrations/2015_01_01_133337_base_tables.php
Base table and model for #2580 and #2583
---
=> Add base table for osu_user_reports

composer.lock
3.0.1 fixes an issue were certain pages take forever to load in debug mode.
Also I'm not sure why composer keeps changing that other line 👻 
---
=> Update clockwork to 3.0.1

app/Libraries/Payments/CentiliPaymentProcessor.php, app/Libraries/Payments/PaymentProcessor.php, app/Libraries/Payments/PaypalPaymentProcessor.php, app/Libraries/Payments/XsollaPaymentProcessor.php, database/migrations/2018_08_27_053717_add_country_code_to_payments.php
Store country code of payments for accounting purposes.
---
=> Record payment country of origin

resources/assets/coffee/_classes/current-user-observer.coffee, resources/assets/coffee/_classes/forum-cover.coffee, resources/assets/coffee/osu_common.coffee, resources/assets/coffee/react/_components/beatmapset-mapping.coffee, resources/assets/coffee/react/_components/track-preview.coffee, resources/assets/coffee/react/_components/user-avatar.coffee, resources/assets/coffee/react/beatmap-discussions/header.coffee, resources/assets/coffee/react/beatmaps/search-panel.coffee, resources/assets/coffee/react/beatmapset-page/header.coffee, resources/assets/coffee/react/beatmapset-page/score-top.coffee, resources/assets/coffee/react/contest/voting/art-entry.coffee, resources/assets/coffee/react/mp-history/game-header.coffee, resources/assets/coffee/react/profile-page/badges.coffee, resources/assets/coffee/react/profile-page/cover-selection.coffee, resources/assets/coffee/react/profile-page/header-main.coffee, resources/assets/coffee/react/profile-page/historical.coffee
=> Don't set background-image url if undefined

app/Libraries/Payments/CentiliPaymentProcessor.php
=> Check more fields for country codes in Centili response

resources/views/objects/_pagination_v0.blade.php
By capping it in the view so it doesn't render more page numbers
---
=> Hotfix pager going way past the page limit

resources/assets/less/bem-index.less, resources/assets/less/bem/btn-osu-big.less, resources/assets/less/bem/forum-topics-pager.less, resources/assets/less/bem/forum-topics.less, resources/lang/en/forum.php, resources/views/forum/forums/_new_topic.blade.php, resources/views/forum/forums/_topics.blade.php, resources/views/forum/forums/show.blade.php
=> More distinct new topic button

SETUP.md
This seemed small enough that making an issue for it would be extraneous. I believe I interpreted the intent of the sentence correctly but could always be mistaken.
=> Fix grammar in setup.md

resources/assets/less/bem-index.less, resources/assets/less/bem/btn-osu-big.less, resources/assets/less/bem/forum-topic-entry.less, resources/assets/less/bem/forum-topics-spacer.less, resources/assets/less/bem/forum-topics.less, resources/assets/less/variables.less, resources/views/forum/forums/show.blade.php
=> First new topic button in forum is too wide

resources/assets/coffee/_classes/beatmap-discussions-chart.coffee, resources/assets/less/bem/beatmap-discussions-chart.less
=> Reduce opacity for deleted points on the timeline

app/Http/Controllers/LegacyInterOpController.php
Missed this when looking for `News`.
=> Update legacy controller to use NewsPost model

database/migrations/2018_07_31_101323_create_news_posts.php
Already updated in production.
=> Limit column length for compatibility with older MySQL

app/Models/Score/Model.php
=> Correctly return class name in score's getClass

app/Http/Controllers/Forum/TopicsController.php, resources/views/forum/topics/replace_button.blade.php
Another bug from recent forum moderation update.
=> Add missing variable for topic lock view

app/Models/Comment.php, app/Transformers/CommentTransformer.php, resources/assets/coffee/react/_components/comment.coffee
Looks like using username isn't a good idea.
=> Better display name for unmatched users

resources/assets/less/bem/osu-page.less, resources/assets/less/bem/profile-header-extra.less
Fixes #3640... I think. I can't reproduce the problem.
=> Fix background color on profile page

resources/assets/less/bem/comment.less
=> Fix comments not word wrapping

app/Http/Controllers/BeatmapsetsController.php, app/Http/Controllers/ChangelogController.php, app/Http/Controllers/CommentsController.php, app/Http/Controllers/NewsController.php, app/Libraries/CommentBundle.php, app/Libraries/OsuAuthorize.php, app/Models/Comment.php, app/Transformers/CommentTransformer.php, app/helpers.php, resources/assets/coffee/react/_components/comment-editor.coffee, resources/assets/coffee/react/_components/comment-show-more.coffee, resources/assets/coffee/react/_components/comment.coffee, resources/assets/coffee/react/_components/comments.coffee, resources/assets/less/bem-index.less, resources/assets/less/bem/comment-show-more.less, resources/assets/less/bem/comment.less, resources/assets/less/variables.less, resources/views/beatmapsets/show.blade.php, resources/views/changelog/build.blade.php, resources/views/news/show.blade.php
=> Paginate comments

resources/assets/coffee/_classes/user-verification.coffee
=> Don't close verification modal when escape key is pressed

app/Http/Controllers/Forum/TopicsController.php, app/Models/Forum/Topic.php, resources/assets/coffee/_classes/forum-topic-title.coffee, tests/Controllers/ForumTopicsControllerTest.php
Add presence validation at model level and remove the one in controller (which is missing in update action).
=> Validate presence of topic title

bin/db_setup.sh
=> Add missing osu_charts to database setup script

resources/assets/less/bem/btn-circle.less, resources/assets/less/store/base.less, resources/views/store/objects/address.blade.php
- use correct icon and adjust position for delete address button
- adjust size of delete (and mail notification) button in topic subscriptions page
=> Update various delete buttons

app/Libraries/HasDynamicTable.php, app/Models/BeatmapLeader/Model.php, app/Models/BuildPropagationHistory.php, app/Models/Chat/Model.php, app/Models/UserStatistics/Model.php, app/Models/UserStatistics/Spotlight/Model.php, app/Scopes/MacroableModelScope.php, tests/TableTest.php
Inherit `App\Models\Model` instead.
=> Change all remaining models inheriting laravel model

app/Http/Controllers/Admin/ContestsController.php, app/Http/Controllers/Admin/UserContestEntriesController.php, app/Models/UserContestEntry.php, database/migrations/2018_09_26_082418_add_soft_delete_to_user_contest_entries.php, resources/assets/coffee/react/admin/contest.coffee, resources/assets/coffee/react/admin/contest/_base-user-entry.coffee, resources/assets/coffee/react/admin/contest/user-art-entry.coffee, resources/assets/coffee/react/admin/contest/user-entry-delete-button.coffee, resources/assets/coffee/react/admin/contest/user-entry-list.coffee, resources/assets/coffee/react/admin/contest/user-entry.coffee, resources/assets/less/bem-index.less, resources/assets/less/bem/admin-contest-entry.less, resources/assets/less/bem/admin-contest.less, resources/assets/less/bem/usercard.less, resources/views/admin/contests/index.blade.php, resources/views/admin/contests/show.blade.php, resources/views/home/_search_result_user.blade.php, routes/web.php, webpack.mix.js
(also contains a bit of a facelift for the contest admin page)
---
=> Add ability for admins to delete contest entries

resources/assets/less/bem/play-detail-menu.less, resources/assets/less/bem/simple-menu.less, resources/assets/lib/play-detail-menu.coffee
=> Some style tweaks for the popup menu on play details

app/Http/Controllers/Users/ReplaysController.php
Also fixes the wrong replay being downloaded in come cases. 
---
=> Fix missing replay content length in downloaded replays

app/Http/Controllers/API/RoomsController.php, app/Libraries/Session/Store.php, composer.json, composer.lock, config/app.php, config/database.php, docker/php/Dockerfile
Seems working except for `artisan queue:listen` (laravel job worker) which recreates php process all the time and thus still making new connection. It's fine with `artisan queue:work` (same job worker but persists php processes) though.
=> Use persistent connection for Redis

app/Http/Controllers/Store/CheckoutController.php, app/Http/Controllers/Store/Controller.php
fixes #3735
Not so much of an issue since you have to be logged in to even begin checking out, but this will handle cases where the session expires in between viewing the cart and checking out.
---
=> Prompt for login if not logged in when starting a checkout

app/Libraries/OsuAuthorize.php, resources/assets/coffee/react/_components/comment.coffee, resources/lang/en/authorization.php
=> Disallow editing deleted comment

resources/assets/coffee/react/beatmapset-page/main.coffee
=> Allow commenting on all beatmaps

config/markdown.php
Disable unsafe links and limit nesting level.
Reference: https://commonmark.thephpleague.com/security/
=> Better markdown default settings

resources/assets/coffee/_classes/beatmapset-filter.coffee, resources/assets/coffee/react/beatmaps/main.coffee, resources/assets/coffee/react/beatmaps/paginator.coffee, resources/assets/coffee/react/beatmaps/search-filter.coffee, resources/assets/coffee/react/beatmaps/search-panel.coffee
continuation of #3738
Clean up/streamline the state and render handling of the beatmap search panel.
The links should show the correct urls now; closes #3671
The `page` param will be replaced by a `cursor` param soon™️ 
---
=> Beatmap search panel cleanups

app/Http/Controllers/UsersController.php
=> Don't limit beatmaps listing of user profile page 

resources/assets/coffee/react/beatmap-discussions/main.coffee, resources/assets/less/bem/back-to-top.less, resources/assets/less/variables.less
=> Add back to top button on beatmap discussion page

.docker/.gitignore, docker-compose.yml
=> Move docker user home directory

build.sh, docker-compose.yml
=> Allow skipping file permission override during build

resources/lang/en/tournament.php
---
Fixes a minor wording issue displayed to users who registered for a tournament via the Tournaments system.
=> Fix tournament registration wording error

app/Http/Controllers/ChangelogController.php
Forgot to update when content of the variable was changed from json/array to actual model.
=> Fix build propagation chart

resources/assets/coffee/react/profile-page/historical.coffee
React complains about unique keys...but only sometimes
---
=> Fix missing react key on profile page

resources/assets/coffee/react/_components/comment.coffee, resources/assets/less/bem/comment-vote.less, resources/assets/less/bem/comment.less, resources/assets/less/variables.less
Add background to vote button and lighten separator.
=> Comment style updates

app/Models/BeatmapDiscussionPost.php, resources/assets/coffee/_classes/beatmap-discussion-helper.coffee, resources/assets/coffee/react/beatmap-discussions/message-length-counter.coffee, resources/assets/coffee/react/beatmap-discussions/new-discussion.coffee, resources/assets/coffee/react/beatmap-discussions/new-reply.coffee, resources/assets/coffee/react/beatmap-discussions/post.coffee, tests/Models/BeatmapDiscussionPostTest.php
=> Only limit characters for timeline messages

resources/lang/en/beatmapsets.php
=> Fix hype message on beatmapset pages

resources/assets/coffee/forum/topic-ajax.coffee
=> Fix edit post cancel button not working after navigating back

app/Models/Forum/TopicPoll.php
Apparently it's been backwards all this time :D
---
=> Fix forum poll duplicate options check

resources/lang/en/forum.php, resources/views/forum/topic_watches/_topic_buttons.blade.php
=> Better tooltip for notification toggle

resources/lang/en/beatmaps.php
=> Add missing translation key for disqualification alert

app/Models/Chat/Channel.php
Already checked by the caller in controller.
=> Remove type check in model on removing user from channel

build.sh, deploy.sh
Should fix the config cache being generated too early in the build process.
---
=> Fix deploy process

app/Http/Controllers/Chat/ChatController.php, resources/assets/less/bem-index.less, resources/assets/less/bem/chat-conversation-list.less, resources/assets/less/bem/chat-logo.less, resources/assets/less/bem/header-v3.less, resources/assets/less/bem/osu-page.less, resources/assets/ts/chat/chat-logo.tsx, resources/assets/ts/chat/chat-worker.ts, resources/assets/ts/chat/input-box.tsx, resources/assets/ts/chat/main-view.tsx, resources/assets/ts/header-v3.tsx, resources/assets/ts/models/chat/channel.ts, resources/assets/ts/stores/channel-store.ts
Some small usability fixes:
- Autofocus on input box when window is focused/first loaded
- Parted channels will now be removed when updates are received
- New compact header (resolves #3902)
- Better handling of the case where users part PM channels (someone accidentally an admin bypass)
---
Some usability tweaks - chat box will autofocus, parted channels will be reflected without needing a page reload and a new compact header design.
=> Chat tweaks and fixes

resources/assets/less/bem/wiki-toc.less
=> Minimize wiki table of contents' height

resources/assets/lib/play-detail-menu.coffee
Fixes first half of #3919. The other half is a bit more involved.
=> Show login popup to download replay

resources/assets/coffee/react/_components/comment.coffee
=> Fix incomplete comment moderation check

app/Http/Controllers/ChatController.php, app/Http/Controllers/HomeController.php, config/osu.php
`CHAT_WEBCHAT_ENABLED` has been removed and instead replaced with:
```
CHAT_WEBCHAT_ENABLED_SUPPORTER
CHAT_WEBCHAT_ENABLED_ALL
```
---
=> Add .env variable to allow toggling of webchat for everyone

app/Http/Controllers/Forum/ForumsController.php, resources/views/forum/forums/_mark_as_read.blade.php
=> Disable mark as read button if not signed in

resources/assets/less/bem/chat-conversation.less, resources/assets/ts/chat/conversation-view.tsx, resources/assets/ts/models/chat/channel.ts, resources/assets/ts/stores/channel-store.ts, resources/lang/en/chat.php
---
- Fixes an issue where incoming updates would prematurely dismiss the placeholder new-PM tab
- Adds a message stating the limitations of the new chat system when starting a new PM
- Temporarily disables the auto message scrolling until it can be properly fixed
=> Chat fixes

app/Http/Controllers/AccountController.php, app/Http/Controllers/UsersController.php, app/Transformers/UserTransformer.php, resources/assets/coffee/react/profile-page/beatmap-playcount.coffee, resources/assets/coffee/react/profile-page/detail-bar.coffee, resources/assets/coffee/react/profile-page/detail-mobile.coffee, resources/assets/coffee/react/profile-page/header-info.coffee, resources/assets/coffee/react/profile-page/header.coffee, resources/assets/coffee/react/profile-page/play-time.coffee, resources/assets/less/bem/beatmap-playcount.less, resources/assets/less/bem/profile-detail-bar.less, resources/assets/less/bem/profile-detail-mobile.less, resources/assets/less/bem/profile-info.less, resources/assets/less/bem/profile-page-toggle.less, resources/assets/less/bem/profile-previous-usernames.less, resources/lang/en/common.php, resources/lang/en/users.php
Fixes #3953, fixes #3950, fixes #3957.
=> Profile page fixes

resources/assets/less/bem/osu-layout.less
=> Update profile background color

resources/assets/less/bem/beatmap-playcount.less, resources/assets/less/bem/page-extra.less
Too many layers causing layout to take too much time while scrolling
---
=> Reduce number of render layers on user profile page

app/Exceptions/Handler.php
It has been updated by upstream years ago.
=> Update exception handler for debug mode

resources/assets/coffee/react/profile-page/detail-mobile.coffee, resources/assets/coffee/react/profile-page/detail.coffee
Further clean up of chart renderer will be done later.
=> Fix rank chart render check

resources/assets/coffee/react/artist-page.coffee
=> Fix disappearing tracklist when clicking on a featured artists album

resources/views/artists/show.blade.php
=> Fix anchor offset for featured artists albums

app/Http/Controllers/Multiplayer/RoomsController.php, app/Models/Multiplayer/Room.php, app/Models/Multiplayer/UserScoreAggregate.php, app/Transformers/Multiplayer/UserScoreAggregateTransformer.php, tests/Models/Multiplayer/UserScoreAggregateTest.php
Pass `limit` (default 50, minimum 1, maximum 50) and `page` (default 1) parameter to paginate leaderboard.
=> Leaderboard pagination

app/Http/Controllers/Multiplayer/RoomsController.php
=> Add host country to room response

app/Models/Multiplayer/Room.php
=> Ensure multiplayer rooms always have at least one playlist item

app/Libraries/OsuAuthorize.php, app/Models/Multiplayer/Room.php
=> Ensure players aren't restricted/silenced when creating rooms/submitting scores

resources/assets/coffee/_classes/account-edit.coffee
=> Trim auto submitted text fields when editing profile

resources/assets/coffee/react/beatmapset-page/header.coffee, resources/lang/en/beatmapsets.php
closes #2592
The text seems kind of wordy for a button, though.
---
=> Add button prompting for login on beatmap page

resources/assets/coffee/_classes/beatmap-pack.coffee, resources/assets/less/bem/beatmap-pack.less
=> Allow beatmap pack list item to be toggled close

resources/assets/coffee/react/beatmaps/main.coffee, resources/assets/less/bem/beatmapsets.less, resources/assets/less/bem/show-more-link.less
Broken when updating sort menu.
=> Fix padding of beatmapsets show more button

resources/assets/less/bem/page-extra.less
=> Update account standing info bar color

resources/assets/coffee/react/_components/comment-editor.coffee, resources/assets/coffee/react/_components/spinner.coffee, resources/assets/less/bem/btn-osu-big.less, resources/assets/less/bem/comment-editor.less, resources/assets/less/spinner.less
=> Update comment input box style

app/Models/Event.php
Added support for updated mode names.
=> Update event mode string parser

app/Http/Controllers/BeatmapsetEventsController.php, app/Http/Controllers/Users/ModdingHistoryController.php, app/Libraries/OsuAuthorize.php, app/Models/BeatmapsetEvent.php, resources/views/beatmapset_events/index.blade.php
Fixes #4140.
The search interface will be a bit confusing because some event types may be unavailable when searching by username.
=> Synchronize public events list in model and authorize

resources/views/home/landing.blade.php
=> Remove sign in tooltip at landing page

app/Http/Controllers/BeatmapsetsController.php, resources/assets/coffee/react/beatmaps/main.coffee, resources/assets/coffee/react/beatmaps/paginator.coffee
=> Remove show more from beatmap listing if there isn't any more

tests/Libraries/Fulfillments/SupporterTagFulfillmentTest.php
=> Fix SupporterTagFulfillmentTest#testPartiallyRevokedOrder randomly failing

resources/assets/less/bem/beatmapsets.less
On beatmapset search page when nothing found.
=> Fix margin to match latest structure

resources/assets/coffee/react/beatmap-discussions/discussions.coffee
=> Add missing react key

resources/assets/coffee/_classes/forum.coffee, resources/assets/less/bem/forum-post.less
Add a border around the post that is linked or jumped to.
closes #2369
---
=> Highlight linked post

resources/assets/less/bem/osu-md.less
=> Adjust markdown header margins

app/Http/Controllers/BeatmapsetsController.php, app/Libraries/Search/BeatmapsetSearch.php, app/Libraries/Search/BeatmapsetSearchParams.php, resources/assets/coffee/react/beatmaps/main.coffee, resources/assets/coffee/react/beatmaps/search-filter.coffee, resources/assets/coffee/react/beatmaps/search-panel.coffee
closes #2565
Just adds additional text onto the filter.
---
=> Show star rating used for recommended difficulty

resources/assets/lib/globals.d.ts, resources/assets/lib/import-shims.coffee
Noticed while looking at other stuff
---
=> Fix missing argument in typings

app/Models/ChangelogEntry.php, app/Transformers/CommentTransformer.php
The thing doesn't even exist anymore.
=> Remove unused import

app/Http/Controllers/StatusController.php, resources/assets/coffee/_classes/status-chart.coffee, resources/assets/coffee/_classes/status-map.coffee, resources/assets/coffee/react/status-page/incident.coffee, resources/assets/coffee/react/status-page/page.coffee, resources/assets/less/bem/line-chart.less
Has been broken for a while but noone noticed (as we're not using it yet).
Updates d3/LineChart usage for the new API and fixes styling, also some cleanup.
=> Fix status page

database/factories/GroupFactory.php
Prevents the case where duplicate random numbers will result in primary key conflicts
---
=> Fix group factory

.travis.yml, travis-php.ini
Should be fine with this...? Also seems a bit faster. MySQL 8 in travis still require `sudo` it seems.
=> Travis updates

resources/assets/less/bem/osu-md.less
=> More compact news page

resources/assets/less/bem/user-action-button.less
=> Fix friend button alignment

app/Models/Wiki/Page.php, app/helpers.php
Add logging to help figure out disappearing pages
---
=> Add some logging when indexing wiki pages

app/Models/User.php
`orWhere` should be scoped to the current predicate.
closes #4221
---
=> Fix user lookup query

app/Models/Wiki/Page.php
_probably_ don't need it anymore
=> Stop logging wiki index actions to Sentry

app/Models/Forum/PollOption.php, resources/assets/less/bem/bar.less, resources/assets/less/bem/forum-poll-row.less, resources/views/forum/topics/_poll_row.blade.php
Now a text in bar chart type thing
closes #4202
=> Wrap poll text

resources/assets/lib/report-score.coffee
Wasn't updated with the download link fix.
closes #4238
=> Use correct mode when reporting plays on converts

resources/assets/lib/chat/conversation-view.tsx, resources/assets/lib/chat/message-divider.tsx, resources/assets/lib/chat/message-group.tsx, resources/assets/lib/globals.d.ts, resources/assets/lib/models/chat/message.ts, resources/assets/lib/news-index/post-item.tsx, resources/assets/lib/news-show/main.tsx, webpack.mix.js
=> Add typing for moment

app/Http/Controllers/Payments/ShopifyController.php
At least until we work out how to integrate the workflow for them
=> Ignore manually created orders from Shopify callback

app/Http/Controllers/CommentsController.php, app/Libraries/MorphMap.php, app/Models/Comment.php, app/Models/UserReport.php, app/Providers/AppServiceProvider.php, app/Transformers/CommentableMetaTransformer.php
The mapping is shared so it makes more sense to put them in one place.
=> Group morph map definitions

composer.json, composer.lock
The newline fix has been merged but no release.
=> Use latest upstream linkify

resources/assets/less/bem/forum-post-actions.less, resources/assets/less/bem/osu-page-header.less
=> Move up wiki GitHub button on mobile

app/Http/Controllers/Store/CartController.php, app/Http/Controllers/Store/CheckoutController.php, app/Http/Controllers/Store/Controller.php, app/Http/Controllers/Store/NotificationRequestsController.php, app/Http/Controllers/StoreController.php, app/Libraries/ChangeUsername.php, app/Models/Store/Order.php, config/store.php, resources/lang/en/model_validation.php, tests/Libraries/ChangeUsernameTest.php
=> Allow restricted users to use the store

resources/views/forum/topics/_poll.blade.php
There's no variable scoping in blade so it has been kind of working anyway.
=> Fix compact usage

resources/assets/coffee/_classes/tooltip-default.coffee
=> Show seconds in time tooltip

.gitignore
Not sure if should just ignore entire `.env.*` instead :thinking:
=> Ignore env files

resources/assets/coffee/_classes/beatmap-discussion-helper.coffee, resources/assets/coffee/react/beatmap-discussions/discussion.coffee, resources/assets/coffee/react/beatmap-discussions/discussions.coffee, resources/assets/coffee/react/beatmap-discussions/main.coffee, resources/assets/less/bem/beatmap-discussions.less, resources/lang/en/beatmaps.php
Resolves #1991.
Won't look quite correct if all discussions are deleted.
=> Add toggle to hide deleted discussions

app/Models/Forum/TopicWatch.php
Resolves #4334.
The underlying names need fixing... <sub>maybe later™</sub>
=> Match forum topic popup notification with email

resources/views/forum/topic_watches/_topic_buttons.blade.php
Less mail, more generic icon.
<sub>(the underlying names still need updating)</sub>
=> Update icon for notification toggle button

.travis.yml, bin/run_tslint.sh, package.json, resources/assets/lib/admin-menu.tsx, resources/assets/lib/chat/chat-logo.tsx, resources/assets/lib/chat/conversation-list.tsx, resources/assets/lib/chat/conversation-view.tsx, resources/assets/lib/chat/input-box.tsx, resources/assets/lib/chat/main-view.tsx, resources/assets/lib/coffee-modules.d.ts, resources/assets/lib/gallery-contest-vote-button.tsx, resources/assets/lib/header-v3.tsx, resources/assets/lib/news-header.tsx, resources/assets/lib/news-index/main.tsx, resources/assets/lib/news-index/post-item.tsx, resources/assets/lib/news-show/main.tsx, resources/assets/lib/notification-widget/category-group.tsx, resources/assets/lib/notification-widget/item.tsx, resources/assets/lib/notification-widget/main.tsx, resources/assets/lib/notification-widget/type-group.tsx, resources/assets/lib/play-detail-menu.tsx, resources/assets/lib/report-comment.tsx, resources/assets/lib/user-card.tsx, tslint.json, yarn.lock
Include linting on typescript and jsx as part of the CI build. 
Build should fail if there are lint errors but still pass if there are only warnings.
=> Run tslint on CI

resources/assets/coffee/react/profile-page/account-standing.coffee
~~Somehow managed to delete this.~~
`a` was added by #4303
=> Fix missing import in AccountStanding

resources/assets/less/bem/notification-popup-item.less
Less confusing especially the mark as read button.
=> Add hover effect on notification item and button

resources/assets/coffee/_classes/current-user-observer.coffee, resources/views/layout/metadata.blade.php, webpack.mix.js
Lite version of the other one.
=> Reenable sentry for js

app/Jobs/BroadcastNotification.php
=> Notify topic watches only if they're receiving mail

resources/assets/coffee/_classes/user-card.coffee, resources/assets/lib/notification-widget/worker.ts, resources/assets/lib/stores/channel-store.ts, resources/views/layout/metadata.blade.php
- use more compatible functions
- ignore old Firefox js parsing errors
=> Reduce Sentry error logging noise

resources/assets/less/bem/user-card.less, resources/assets/lib/user-card.tsx
heavier font-weight only on username; 
brighter online circle; 
overlay for offline users slighty more opaque.
=> More new user card tweaks

resources/assets/less/bem/osu-layout.less, resources/views/beatmaps/index.blade.php, resources/views/beatmapsets/discussion.blade.php, resources/views/home/download.blade.php, resources/views/packs/index.blade.php, resources/views/wiki/show.blade.php
Darken page backgrounds for the remaining pages that still have a white/light background.
Step 1 / ??? of darkificiation.
=> Darken page backgrounds

resources/assets/less/bem/user-cards.less, resources/assets/less/variables.less
=> Up to 3 columns on friends list

app/Libraries/OsuAuthorize.php, app/Models/User.php, app/Models/UserGroup.php, app/Transformers/UserTransformer.php
so now bns are either 28 (normal) or 32 (limited/probationary), not both @peppy 
---
=> Refactor BN groups

resources/assets/less/bem/beatmap-discussion-new-float.less, resources/assets/less/bem/page-extra-tabs-before.less, resources/assets/less/bem/page-extra-tabs.less
Update to match #4385. Fixes #4391.
=> Update background colour of new discussion box

app/Console/Commands/DisqusImport.php, app/Http/Controllers/ChangelogController.php, app/Models/ChangelogEntry.php, app/Models/Store/Order.php
=> Update array destructuring syntax

resources/assets/coffee/_classes/form-error.coffee, resources/views/accounts/_edit_email.blade.php, resources/views/accounts/_edit_password.blade.php
Good job, me (ノ･_･)ノ︵ ɐʎɐuɐu
Also removed leftover data attributes from older implementation.
=> Fix account settings validation error

app/Http/Controllers/NotificationsController.php
=> Fix loading more notifications

resources/assets/coffee/react/_components/comment.coffee, resources/assets/coffee/react/_components/comments-manager.coffee, resources/assets/coffee/react/_components/comments.coffee, resources/assets/less/bem-index.less, resources/assets/less/bem/comments.less, resources/assets/less/bem/deleted-comments-count.less, resources/assets/less/bem/sort.less, resources/assets/lib/deleted-comments-count.tsx, resources/lang/en/comments.php, resources/lang/en/common.php
=> Add toggle to hide deleted comments

resources/assets/less/bem/qtip.less, resources/assets/less/bem/user-card.less
Card is smaller than it should be
=> Fix user card tooltip size

tsconfig.json
Stop looking inside my stuff drawer. And probably fewer directory lookup.
=> Limit ts compiler search path

app/Libraries/OsuAuthorize.php, app/Models/User.php
not really sure why this existed in the first place. was only used two times, once by Noffy (QAT) because I asked her to when I was afk, and once by Pawsu (GMT) as a joke or something that was reverted
---
=> Remove GMT and NAT ability to move beatmapsets to Loved

resources/assets/less/bem/user-card.less
=> Add indication when hovering over user card button

resources/assets/coffee/react/mp-history/event.coffee, resources/assets/coffee/react/mp-history/game-header.coffee
=> Include seconds in multiplayer match events

app/Libraries/OsuAuthorize.php
=> Allow restricted users to still join public chat channels

resources/lang/en/accounts.php
might need a crowdin string reset or whatever
=> Update wording on auto-subscribe option to be more descriptive

resources/assets/lib/store.ts, tsconfig.json
Except lodash' _ because Microsoft/TypeScript#30760.
=> Ensure no unused locals for typescript

resources/assets/lib/notification-widget/item.tsx
=> Mark notification read when clicking the message

resources/assets/coffee/react/beatmap-discussions/discussion.coffee
Found when looking for something else.
=> Remove unused variable

resources/assets/coffee/react/_components/comment.coffee
=> Show login box when trying to vote comment as guest

app/Http/Controllers/UsersController.php, resources/assets/coffee/react/profile-page/main.coffee
Increases initial scores count from 5 to 10 and additional loads from 20 to 50. Resolves #4431.
=> Show more scores in profile page

resources/assets/coffee/_classes/osu-audio.coffee
=> Ignore not found errors from audio player

resources/assets/lib/friends-index/main.tsx, resources/views/home/_user_header_nav.blade.php
Capitalisation style uses old version for now. Fixes #4484.
=> Use same translation and order for home navigation

resources/assets/less/bem/chat-message-group.less
(for english-like languages anyway)
fixes #3914
=> Fix chat wrapping

app/Http/Controllers/CommentsController.php, resources/assets/coffee/react/_components/comment.coffee, resources/assets/less/bem/comment.less
- hide badge on deleted object
- correct font size for deleted object
- show correct parent username in single thread view
=> Comment misc fixes

resources/views/beatmapset_watches/index.blade.php
=> Use correct translation key for unwatch button title

resources/assets/less/bem/chat-input.less, resources/assets/less/bem/chat-message-group.less
=> Change the chat font to a legible one

resources/views/vendor/apidoc/partials/info.blade.php
Fixes:
- link to postman collection
- base url in some sections not being https
=> Documentation fixes

resources/assets/lib/chat/input-box.tsx, resources/assets/lib/globals.d.ts
=> Refocus input box on channel change

app/Models/Event.php
closes #4562
generates text in the format:
`[http://osuweb.test/beatmapsets/402995 Taneda Risa - Wareta Ringo (TV edit)] by [http://osuweb.test/users/475002 iamapen] has just been ranked!`
=> Generate event text for Bancho

resources/assets/coffee/react/_components/comment.coffee
=> Fix accidental lowercase links on comments

resources/assets/less/bem/notification-popup-item.less
Increases the hitbox size and provides clearer feedback for when hovering said hitbox.
=> Improved 'mark-as-read' button on notifications

resources/assets/lib/friends-index/main.tsx, resources/assets/lib/globals.d.ts
=> Show correct cover on friends page

app/Exceptions/Handler.php, app/Http/Controllers/ChangelogController.php, app/Http/Controllers/CommentsController.php, app/Http/Controllers/NewsController.php, app/Http/Controllers/UsersController.php, app/helpers.php
=> Replace expectsJson to include api request path check

app/Models/Multiplayer/Match.php, tests/Controllers/MatchesControllerTest.php
=> Fix private match viewing

resources/assets/less/bem/forum-post.less, resources/lang/en/forum.php, resources/views/forum/topics/_post_info.blade.php
=> Add topic starter indicator

webpack.mix.js
config smart merge isn't very smart, apparently.
=> Enable sourcemaps when minifying

app/Transformers/ContestEntryTransformer.php, app/Transformers/UserContestEntryTransformer.php, app/helpers.php, resources/assets/coffee/react/admin/contest/user-art-entry.coffee
This was overlooked while adding thumbnails to the voting pages
=> Use thumbnails for art entries on admin page

package.json, resources/assets/coffee/react/_components/comment-editor.coffee, resources/assets/coffee/react/beatmap-discussions/new-discussion.coffee, resources/assets/coffee/react/beatmap-discussions/new-reply.coffee, resources/assets/coffee/react/beatmap-discussions/post.coffee, resources/assets/lib/beatmaps/beatmapset-search.ts, resources/assets/lib/notification-widget/worker.ts, resources/assets/lib/tooltip-context.tsx, tests/karma/foo.spec.ts, tsconfig.json, yarn.lock
Seems working.
Not updated:
- bootstrap: not sure what to do with this
- coffeescript: should be moved to typescript
- karma-webpack: newer version doesn't work
- mobx-react: [missing devtool tabs on newer version](https://github.com/mobxjs/mobx-devtools/issues/56)
- qtip2: yarn being confused
=> Update JavaScript packages

app/Events/Fulfillments/SupporterTagEvent.php, app/Exceptions/Handler.php, app/Http/Controllers/Payments/ShopifyController.php, app/Jobs/RegenerateBeatmapsetCover.php, app/Models/Event.php, composer.json, composer.lock, config/app.php
~~Part 2 would be upgrading commonmark~~. Haven't even tested this one apart of tinker starts fine and some pages still load.
=> Update PHP dependencies

app/Models/BeatmapsetEvent.php
=> Fix error when passing non-array parameter

app/Libraries/Search/BeatmapsetSearchRequestParams.php
Fixes https://github.com/ppy/osu/issues/5319 temporary until it gets updated and other legacy stuff. Not tested.
=> Add missing loved legacy status map

resources/assets/less/bem/page-mode-link.less, resources/assets/less/bem/user-session-list-session.less
For the number of beatmap difficulties and current user session
=> Increase contrast on badges

resources/assets/coffee/react/beatmapset-page/scoreboard.coffee, resources/assets/less/bem/beatmap-score-top.less, resources/assets/less/bem/beatmap-scoreboard-table.less
=> Show droplet misses instead of droplets

resources/views/forum/topics/_post_info.blade.php
Resolves #4668, resolves #4123.
=> Hide posts link for restricted user

resources/assets/less/bem/beatmap-scoreboard-table.less
=> Fix scoreboard table color

resources/assets/less/bem/beatmap-discussion-new.less
=> Better color for notice area of new discussion box

resources/views/layout/metadata.blade.php, resources/views/master.blade.php
=> Colourize Chrome for Android's chrome to match the per-section themes

resources/assets/coffee/react/admin/contest/user-art-entry.coffee, resources/assets/coffee/react/admin/contest/user-entry-delete-button.coffee, resources/assets/coffee/react/admin/contest/user-entry-list.coffee, resources/assets/coffee/react/admin/contest/user-entry.coffee, resources/assets/less/bem-index.less, resources/assets/less/bem/admin-contest-entry.less, resources/assets/less/bem/admin-contest.less, resources/assets/less/bem/forum-cover-admin-item.less, resources/assets/less/bem/osu-layout.less, resources/assets/less/bem/osu-page.less, resources/assets/less/bem/osu-table.less, resources/views/admin/contests/index.blade.php, resources/views/admin/contests/show.blade.php, resources/views/admin/forum/forum_covers/index.blade.php, resources/views/admin/logs/index.blade.php, resources/views/admin/pages/root.blade.php, resources/views/admin/store/orders/show.blade.php
Order listing page left bright as it's not really used ATM.
Also adds an 'osu-table' class that will be used to standardise simple tables (in the style of the beatmap leaderboards).
=> Dark design pass on admin section

resources/lang/en/community.php
- Fixes a small grammatical error on gifted tags text
- Fixes non-capitalised first character of osu!direct benefit
=> Small changes to support page on en lang

database/migrations/2019_07_23_034016_add_score_process_queue.php
=> Add score_process_queue migration

app/Models/ChangelogEntry.php
Capitalised first found label for category and 'add' type if the title starts with 'add'.
=> Guess changelog entry category and type

app/Http/Controllers/LegacyInterOpController.php
=> Return achievement id for compatibility

app/Models/Wiki/Page.php, resources/lang/en/wiki.php, resources/views/wiki/show.blade.php
like wikipedia's Template:Update
=> Add custom "outdated" message for English wiki articles

app/Events/UserSessionEvent.php, app/Exceptions/UserVerificationException.php, app/Http/Controllers/AccountController.php, app/Http/Controllers/Controller.php, app/Http/Controllers/NotificationsController.php, app/Http/Kernel.php, app/Http/Middleware/VerifyPrivilegedUser.php, app/Http/Middleware/VerifyUser.php, app/Libraries/Session/Store.php, app/Libraries/UserVerification.php, app/Libraries/UserVerificationState.php, app/Mail/UserVerification.php, app/Models/LegacySession.php, resources/assets/coffee/_classes/user-verification.coffee, resources/assets/less/bem-index.less, resources/assets/less/bem/account-verification-completed.less, resources/assets/less/bem/account-verification-message.less, resources/assets/less/bem/oauth-form.less, resources/assets/lib/notification-widget/worker.ts, resources/lang/en/accounts.php, resources/lang/en/layout.php, resources/views/accounts/verification_completed.blade.php, resources/views/accounts/verification_invalid.blade.php, resources/views/emails/user_verification-en.blade.php, resources/views/users/verify.blade.php, routes/web.php, tests/Controllers/AccountControllerTest.php, tests/Controllers/BeatmapDiscussionPostsControllerTest.php, tests/Controllers/BeatmapDiscussionsControllerTest.php
Click the link and the open verification box will be magically verified. Or something.
=> Add verification link

app/Libraries/Multiplayer/Mod.php
Not sure if we need to safely make hidden incompatible.
https://github.com/ppy/osu/blob/8caf9ade01749fd549fed4cedef143ab2a2535f6/osu.Game.Rulesets.Osu/Mods/OsuModSpinIn.cs#L29
---
=> Add spin in mod for lazer multi

app/Http/Controllers/Forum/TopicsController.php, app/Http/Controllers/FriendsController.php, app/Http/Controllers/GroupsController.php, app/Models/User.php, app/Transformers/UserCompactTransformer.php, resources/assets/less/bem/supporter-icon.less, resources/assets/less/bem/user-action-button.less, resources/assets/less/bem/user-card.less, resources/assets/less/bem/user-cards.less, resources/assets/less/bem/user-list.less, resources/assets/less/variables.less, resources/assets/lib/globals.d.ts, resources/assets/lib/supporter-icon.tsx, resources/assets/lib/user-card.tsx, resources/assets/lib/user-cards.tsx, resources/assets/lib/user-list.tsx, resources/lang/en/users.php
Applies to friends and groups user lists.
Adds a toggle next to the sorter:
is squisher
closes #4232
=> Add list view mode toggle for user lists

app/Models/UserBadge.php, app/Transformers/UserBadgeTransformer.php, database/migrations/2019_07_25_082550_add_url_to_badges.php, resources/assets/coffee/react/profile-page/badges.coffee
=> Add url support to profile badges

resources/lang/en/beatmaps.php
Removes assumption and says status clearly instead, fixes #1809.
---
=> Reword graveyard beatmap discussion message

app/Http/Controllers/LegacyInterOpController.php, app/Models/Score/Best/Model.php
=> Include user's high scores for reindexing via LIO

app/Http/Controllers/RankingController.php, resources/views/rankings/index.blade.php
country filtering is supposed to be only for performance ranking, apparently?
=> Remove country filtering for score rankings

resources/assets/coffee/react/_components/beatmap-basic-stats.coffee
=> Hide bpm on Beatmaps that have silly BPM values

resources/assets/coffee/react/_components/comments.coffee, resources/assets/less/bem/fragment-target.less, resources/assets/less/utilities.less, resources/views/forum/forums/index.blade.php
=> Fix pointer events for anchor target

resources/lang/en/events.php
=> Fix invalid html in translation

resources/assets/less/bem/forum-topic-entry.less
=> Fix alignment of topic icon

app/Libraries/BBCodeFromDB.php, app/Libraries/Markdown/OsuMarkdown.php, app/helpers.php, resources/views/forum/_header.blade.php, resources/views/layout/_popup_login.blade.php, resources/views/layout/footer.blade.php, resources/views/objects/_pagination_v2.blade.php, resources/views/objects/_show_more_link.blade.php
=> Create helper for generating class with modifiers

app/helpers.php
=> Allow adding modifiers to spinner

package.json, resources/assets/less/app.less, resources/assets/less/variables.less, resources/views/layout/metadata.blade.php, yarn.lock
`typeface-inter` is a lie. `inter-ui` seems fine.
=> Use "Inter" for content font

resources/assets/less/bem/comment.less
=> Style code blocks to be dark in comments

app/Console/Commands/ModdingRankCommand.php
Intended to stop people camping the ranking process.
=> Add random delays to ranking process

resources/views/beatmapset_events/index.blade.php
=> Fix checkboxes in beatmapset event listing page

resources/assets/coffee/react/profile-page/user-page.coffee, resources/assets/less/bem/profile-extra-user-page.less
Bottom area missing the padding thanks to collapsing margins.
=> Fix padding on new user page section

app/Http/Controllers/AccountController.php, app/Http/Controllers/PasswordResetController.php, app/Models/UserAccountHistory.php
- password reset
- email change
=> Log user security related activities

resources/assets/less/bem/forum-list.less, resources/assets/less/bem/forum-title.less, resources/assets/less/bem/header-v4.less, resources/assets/less/functions.less, resources/assets/less/variables.less
- match with previous name
- create function for default padding
- `@adjustment` isn't used yet but should be simple enough to check
=> Clean up new layout gutter variable

resources/assets/less/bem/account-edit-entry.less, resources/assets/less/bem/forum-post.less, resources/assets/less/variables.less, resources/views/accounts/_edit_signature.blade.php
=> Limit height for signature preview

resources/assets/less/bem-index.less, resources/assets/less/bem/bootstrap/modal-body.less, resources/assets/less/bem/form-select.less, resources/assets/less/bem/search-forum-options.less, resources/views/forum/topics/_moderate_move.blade.php, resources/views/objects/search/_forum_options.blade.php
Part of #4919 but just the modal dialog for moving topic.
=> Dark forum topic move dialog

resources/views/forum/topics/_poll_row.blade.php
=> Fix forum poll percentage being broken on several locales

resources/assets/coffee/react/beatmap-discussions/user-filter.coffee
=> Fix user color in discussion filter

resources/assets/less/bem/forum-post.less, resources/assets/less/functions.less
=> Use content font for signature

app/Http/Controllers/NotificationsController.php
=> Prevent Chrome from using outdated response

resources/assets/less/bem/landing-footer-social.less
~Not sure if should change the sizes to match the ones in the navigation header which have better horizontal alignment because of the sizes~
Now with  matching sizes
=> Fix social media icons alignment on landing page

app/Http/Controllers/PasswordResetController.php, resources/views/password_reset/_initial.blade.php
=> Show inline error message for reset password form

app/Libraries/BBCodeForDB.php, tests/Libraries/bbcode_examples/basic_code.base.txt, tests/Libraries/bbcode_examples/basic_code.db.txt, tests/Libraries/bbcode_examples/basic_code.html
Actual style will be fixed separately.
=> Fix newline rendering in bbcode code block

app/Libraries/BBCodeFromDB.php, resources/assets/less/bem/bbcode-spoilerbox.less, tests/Libraries/bbcode_examples/box_with_surrounding_newlines.html, tests/Libraries/bbcode_examples/spoilerbox_with_surrounding_newlines.html
=> Update styling for (spoiler) box

resources/assets/less/bem/beatmapset-description-editor.less, resources/assets/less/bem/post-editor.less
Resolves #4998. Initially planned to update to the new form just like for forum post but it's quite a bit more work than expected.
=> Update color for beatmap description editor

tests/Libraries/BBCodeForDBTest.php, tests/Libraries/BBCodeFromDBTest.php, tests/Libraries/Markdown/IndexingProcessorTest.php, tests/TestCase.php
Also cleanup comparison for BBCodeForDBTest.
=> Update tests to use data provider

app/Models/BeatmapDiscussion.php
Missed this in previous update.
=> Update to use correct polymorphic mapping

resources/views/users/disabled.blade.php
=> Fix text color for account disabled page

resources/views/accounts/_edit_sessions.blade.php, resources/views/artists/index.blade.php, resources/views/forum/forums/_topics_sort.blade.php, resources/views/forum/posts/_button_quote.blade.php, resources/views/forum/topics/show.blade.php, tests/Controllers/BeatmapControllerTest.php
I missed the views and tests last time.
=> Routing parameter fixes

app/Models/RankHistory.php
Missing null check on users without statistics.
=> Fix error on users without ranking

app/Models/BeatmapDiscussion.php
Handle (ignore) unique constraint error on voting.
=> Fix voting race condition error

resources/assets/less/bem/osu-page-header.less
=> Fix wiki main page title not being centered on mobile

resources/assets/less/bem/beatmapsets-search.less
=> Fix color of beatmap search text

resources/assets/coffee/_classes/forum-topic-reply.coffee, resources/assets/coffee/shared.coffee, resources/assets/less/bem/forum-post-edit.less, resources/views/forum/topics/_post_edit_form.blade.php
- less red box border on firefox
- improved focus
- improved blur (resolves #5065)
=> Forum reply box fixes

app/Http/Controllers/BlocksController.php, app/Models/User.php, app/Models/UserRelation.php
Not sure where to put the scope ಠ_ಠ
=> Remove restricted users from friend list

resources/assets/coffee/react/mp-history/event.coffee, resources/assets/coffee/react/mp-history/game-header.coffee, resources/assets/lib/time-with-tooltip.tsx
=> Add date tooltip on multiplayer page

app/Libraries/UserRegistration.php
The title doesn't sound right but not sure how to fix it ಠ_ಠ
=> Count user registration from API

app/Libraries/UsernameValidation.php
=> Switch connection used for previous users of username lookup

app/Models/Elasticsearch/BeatmapsetTrait.php, app/Models/Elasticsearch/PostTrait.php, app/Models/Elasticsearch/TopicTrait.php, app/Models/Elasticsearch/UserTrait.php
left the `::on` part in case we need to move it again >_>;;
=> Switch connection used for batch indexing query

resources/assets/coffee/_classes/forum.coffee
Also inline variable to its only user.
=> Fix with_deleted parameter showing up for non-moderators

app/Http/Controllers/UsersController.php, app/Libraries/UserRegistration.php
- base rate is 60 times per 10 minutes
- additional limit of 10 successful registrations per 10 minutes
=> Update rate limit for registration

app/Console/Commands/FixForumDisplayOrder.php, app/Console/Kernel.php
=>  Add command to fix forum listing order 

app/Http/Controllers/RankingController.php, app/Models/Spotlight.php, app/Transformers/SpotlightTransformer.php
=> Add spotlight rankings to API

app/Http/Controllers/AccountController.php, app/Http/Controllers/UsersController.php, app/Libraries/OsuAuthorize.php, app/Models/Log.php, app/Models/UserAccountHistory.php, resources/assets/coffee/react/profile-page/user-page-editor.coffee, resources/assets/coffee/react/profile-page/user-page.coffee, routes/web.php
=> Allow moderation of profile page

resources/assets/coffee/react/beatmap-discussions/main.coffee, resources/assets/coffee/react/beatmapset-page/hype.coffee, resources/lang/en/beatmapsets.php
=> Add instruction for reporting problems on qualified beatmaps

app/Http/Controllers/ChatController.php, resources/assets/lib/chat.ts, resources/assets/lib/models/user.ts, resources/assets/lib/osu-core.ts, resources/assets/lib/stores/channel-store.ts
You already can't create a new conversation with yourself anyway.
also fixes the test failure in #5071 when checking the routes
=> Fix the views when trying to PM yourself

.gitignore, storage/clockwork/.gitignore
It's been appearing in my repo for quite some time now.
=> Add a file to gitignore

app/Http/Controllers/UsersController.php, tests/Controllers/UsersControllerTest.php
Adding that parameter is the easiest thing, so ( ﾟ◡ﾟ)
Not sure if the response needs to contain anything.
=> Allow validation-only user registration

app/Http/Controllers/BeatmapPacksController.php, app/Models/BeatmapPack.php, database/migrations/2019_10_23_023102_add_hidden_to_beatmapset_packs.php
=> Allow hiding beatmap pack 

app/Transformers/BeatmapsetTransformer.php, config/osu.php
Old forum no longer exists and discussions now happen in new site.
=> Update link to legacy beatmap discussion thread

resources/assets/coffee/react/_components/beatmapset-mapping.coffee
=> Use beatmapset data for mapper name and id

app/Models/Beatmap.php
Rounding it at the model should fix #5080.
=> Uniform star difficulty rounding

resources/assets/less/bem/wiki-main-page.less
Resolves #5186 if it's still a thing.
=> Use content font for wiki main page blurb

app/Http/Controllers/BeatmapDiscussionPostsController.php, app/Http/Controllers/BeatmapDiscussionsController.php
Resolves #5159 if it's going to be a thing.
=> Allow guest access for beatmap discussion listing pages

app/Http/Controllers/BeatmapsController.php
Either this or use `$beatmap->beatmapset_id` (and 404 after redirect).
=> Ensure beatmapset exists before redirecting

app/Libraries/BBCodeForDB.php
=> Remove extra youtube parameters

app/Models/Event.php
=> Update medal achievement event to use transformer for detail

resources/assets/coffee/_classes/user-verification.coffee, resources/views/users/verify.blade.php
Reload page after verifying only on verification page.
=> Don't reload page after verification

resources/assets/coffee/react/profile-page/play-time.coffee
Different rounding causing confusion. Resolves #5272.
=> Fix rounding of play time

resources/assets/lib/notification-widget/main.tsx, resources/assets/lib/notification-widget/type-group.tsx, resources/assets/lib/notification-widget/worker.ts
=> Fix marking notification read moves things around

app/Http/Controllers/BeatmapsController.php, app/Jobs/RemoveBeatmapsetBestScores.php, app/Models/Score/Best/Model.php, database/migrations/2019_11_14_032004_add_new_index_to_scores_high.php
=> Update to use new high scores table index

app/Exceptions/Handler.php, resources/views/store/products/show.blade.php, tests/Controllers/BeatmapDiscussionPostsControllerTest.php, tests/Controllers/MatchesControllerTest.php
Resolves #5298.
Also added login requirement to product page's add to cart button for fewer network accesses.
=> Fix error response for ajax requests

resources/assets/less/bem/beatmap-discussion-post.less, resources/assets/less/bem/modding-profile-vote-card.less
The styling was gone when moved to its own component except for this part. Remove unused class (with same element name) while at it.
=> Fix discussion reply avatar

resources/assets/coffee/react/mp-history/content.coffee, resources/assets/less/bem/mp-history-content.less
=> Fix Multiplayer history pager colour

resources/assets/coffee/react/beatmap-discussions/post.coffee
=> Don't use the markdown renderer for replies

app/Http/Controllers/UsersController.php, phpunit.xml, tests/Controllers/UsersControllerTest.php
=> Limit registration endpoint to guest

app/Http/Controllers/Account/SessionsController.php, app/Http/Controllers/Controller.php, app/Http/Controllers/SessionsController.php, app/Http/Middleware/CheckUserBanStatus.php, app/Libraries/UserVerification.php, app/Models/User.php, app/helpers.php
Also moved the `logout` function to a helper
=> Disable login for accounts with empty email addresses

app/Http/Controllers/BeatmapDiscussionsController.php
=> Fix permission for beatmap discussion redirect link

app/Libraries/OsuCookieJar.php, app/Providers/AppServiceProvider.php, app/helpers.php, config/app.php
Using `setcookie` doesn't work in test.
=> Use laravel cookie jar for clearing cookies

app/Exceptions/Handler.php, app/Http/Controllers/LegacyInterOpController.php, app/Libraries/Chat.php, routes/web.php
That was weird.
Also no actual batch querying involved apart of fetching senders and targets.
=> Allow batch sending of message

app/Http/Controllers/MatchesController.php, app/Libraries/OsuAuthorize.php, app/Models/Chat/Channel.php, app/Models/Multiplayer/Match.php, database/factories/Chat/ChannelFactory.php, database/factories/Multiplayer/MatchFactory.php, tests/Controllers/Chat/Channels/MessagesControllerTest.php, tests/Controllers/Chat/ChannelsControllerTest.php
This is mainly for lazer/tournament clients
=> Allow clients to join the chat channels of 'tournament' matches in a read-only fashion

resources/assets/less/bem/user-card.less
fixes #4824
at least until is gets updated
=> Always use font-default on user card

app/helpers.php
This section makes no sense when the user is logged out
=> Hide profile section from mobile nav when logged out

resources/assets/coffee/react/beatmap-discussions/nominations.coffee
All these checks should probably be centralized somewhere...
=> Fix check for showing disqualify button

app/Http/Controllers/LegacyInterOpController.php
- add per-item status logging
- don't fail on empty messages
- cleanup params
=> Update batch sending message

resources/assets/coffee/react/changelog-build/main.coffee, resources/assets/less/bem/header-nav-v4.less, resources/assets/less/bem/header-v3.less, resources/assets/less/bem/header-v4.less, resources/assets/less/bem/osu-page-header-v3.less, resources/assets/less/variables.less, resources/assets/lib/friends-index/main.tsx, resources/assets/lib/header-v4.tsx, resources/assets/lib/news-header.tsx, resources/assets/lib/news-index/main.tsx, resources/assets/lib/news-show/main.tsx, resources/views/forum/_header_breadcrumb.blade.php
Updated news and friends pages.
=> Update header of some pages

database/migrations/2019_12_11_045755_add_show_in_client_to_user_contest_entries.php
=> Add migration for show_in_client on user_contest_entries

resources/assets/less/bem/header-v4.less
Fix its size and make sure it's always centered.
=> Prevent header overlay from moving around

app/Models/Chat/UserChannel.php
Looping over `Collection::where()` is really slow for large lists 💃 
Replaces there `where`s with a lookup table.
=> Faster chat presence

app/Http/Controllers/HomeController.php, config/osu.php, resources/assets/less/bem/osu-page.less, resources/lang/en/layout.php, resources/views/home/testflight.blade.php, routes/web.php
remember to add the `.env` vars:
```
TESTFLIGHT_LINK=
TESTFLIGHT_LINK_SUPPORTER=
```
=> Add testflight page (for ios lazer builds)

config/osu.php, resources/views/layout/metadata.blade.php
New site is in a state we don't really need this any more.
=> Turn off site switcher on new site

resources/views/home/search.blade.php
The extra inputs were outside the form.
=> Fix forum advanced search

app/Transformers/UserTransformer.php, resources/assets/less/bem/header-v4.less, resources/assets/lib/header-v4.tsx, resources/views/layout/_page_header_v4.blade.php
=> Prevent restricted user notice and header overlap

resources/assets/coffee/_classes/fancy-chart.coffee
=> Fix chart being rendered multiple times in dashboard

app/Exceptions/Handler.php
Actual OAuth exception now wrapped in another exception...except when it's not
=> Stop reporting OAuth grant failures to sentry

database/factories/ArtistFactory.php, database/factories/ContestEntryFactory.php, database/factories/ContestFactory.php
Use a random exisiting image for now instead.
=> Fix test failing due to unreliable image generator

app/Libraries/GithubImporter.php
=> Fix GithubImporter repository variable

app/Libraries/Search/BeatmapsetSearch.php
Caused by the change in #5069 to be able to handle beatmaps in a set individually.
Inverse of a query on a nested document isn't just flipping the `bool` term.
closes #5561
=> Fix unplayed filter not filtering properly

app/Libraries/LocaleMeta.php
No wonder something seemed a bit wrong.
=> Use correct flag for arabic language

app/Models/Beatmap.php, app/Transformers/BeatmapTransformer.php, resources/assets/coffee/react/beatmapset-page/header.coffee, resources/assets/coffee/react/beatmapset-page/main.coffee
=> Show per-beatmap approval and scoreable state on detail page

app/Http/Controllers/SessionsController.php, app/Libraries/UserVerification.php, app/helpers.php, resources/views/forum/topics/replace_button.blade.php, resources/views/forum/topics/replace_delete_button.blade.php, resources/views/forum/topics/replace_watch_button.blade.php, resources/views/users/show.blade.php
=> Remove blade string renderer helper

resources/assets/lib/quick-search/user.tsx
=> Fix missing badge on user quick search

database/seeds/ModelSeeders/UserSeeder.php
```
SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '{"group_id":1,"group_type":1,"group_founder_manage":0,"group_name":"default","group_desc":"default","group_desc_bitfield":"","gr' for column 'group_id' ... <snip>
```
=> Fix UserSeeder

app/Models/UserGroup.php
should be unused, otherwise things would have been dying 🤔
=> Remove unused function

app/Models/Score/Best/Model.php, database/migrations/2020_02_13_080406_add_country_acronym_to_scores_high.php
=> Use existing country column for scores filter

app/Http/Controllers/Multiplayer/RoomsController.php
=> Include beatmap detail on room creation

app/Transformers/BeatmapTransformer.php, app/Transformers/UpdateStreamTransformer.php, resources/assets/coffee/react/_components/changelog-header-streams.coffee, resources/assets/coffee/react/beatmapset-page/scoreboard-table-row.coffee
This updates the remaining transformers which still use `item` and returns single item array to use `primitive`.
=> Transformer simple value

resources/lang/en/mail.php
"Community-provided" sounds nicer?
=> Update mail wording

resources/assets/less/bem/js-react-modal.less, resources/assets/less/variables.less
Mainly for quick search. Navbar z-index can use some adjustments but that needs a bit more change.
=> Fix z-index of modal dialog

app/Libraries/Multiplayer/Mod.php
Fixes https://github.com/ppy/osu-web/issues/5676
(I don't have a dev checkout to work with so plz test)
=> Fix Nightcore/Daycore mods not working in multiplayer

resources/assets/lib/header-v4.tsx
- fix attributes not being set (resolves #5683)
- fix menu staying visible after selecting item (resolves #5646)
=> Mobile header menu fixes

resources/assets/less/bem/tournament-list-item.less, resources/assets/less/bem/tournament-list.less
Remove unwanted outer margin of the items
=> Fix tournament listing page layout

app/Http/Controllers/HomeController.php, app/Models/Beatmapset.php
=> Update popular beatmapsets query

tests/TestCase.php, tests/Transformers/BeatmapDiscussionPostTransformerTest.php, tests/Transformers/BeatmapDiscussionTransformerTest.php, tests/Transformers/BeatmapTransformerTest.php, tests/Transformers/BeatmapsetDescriptionTransformerTest.php, tests/Transformers/BeatmapsetEventTransformerTest.php, tests/Transformers/BeatmapsetTransformerTest.php, tests/Transformers/CommentTransformerTest.php, tests/Transformers/OAuth/ClientTransformerTest.php, tests/Transformers/UserTransformerTest.php
Adds test helpers for creating and setting users with group permissions
=> Add test helpers for creating users

app/Http/Controllers/UsersController.php, app/Models/Model.php
Previously sorted by score which is not shown in the listing.
=> Fix first place ranks listing order in profile page

resources/lang/en/beatmaps.php
=> Fix capitalization of beatmaps extra filter name

resources/assets/less/bem/tooltip-beatmap.less
=> Fix expert tooltip colour becoming unreadable with colour change

app/helpers.php
=> Remove report link and move wiki link to help

app/Http/Controllers/UsersController.php, app/Models/User.php, resources/assets/coffee/react/profile-page/header-info.coffee, resources/assets/less/bem/profile-info.less, resources/assets/less/bem/user-group-badge.less, resources/assets/lib/user-group-badge.tsx
Combined with removing users with redundant title and badge combination should take care of #5657.
=> Show user badge in profile

resources/assets/coffee/react/beatmapset-page/score-top.coffee, resources/assets/coffee/react/mp-history/score.coffee
=> Consistent accuracy number format

resources/assets/coffee/react/modding-profile/detail-bar.coffee, resources/assets/coffee/react/profile-page/detail-bar.coffee, resources/assets/less/bem/profile-detail-bar.less, resources/assets/less/bem/profile-detail-mobile.less, resources/assets/less/bem/profile-stats.less, resources/assets/less/variables.less
- use new gutter size
- fix incorrect sizing on header menu
- always show ranking and hide exp bar
=> Adjust profile page on mobile

database/migrations/2020_03_09_095216_add_channel_type_index_to_channels.php
=> Add chat channel types database index

resources/assets/less/layout.less, resources/assets/less/variables.less, resources/views/layout/metadata.blade.php
=> Add Vietnamese specific font
