resources/assets/less/bem/update-streams-v2.less
resources/assets/less/bem/user-cards.less
resources/assets/less/bem/user-list.less
resources/assets/lib/groups-show/main.tsx
resources/assets/lib/user-list.tsx
resources/lang/en/page_title.php
resources/views/groups/show.blade.php

- add group name. Resolves #5740
- fix title
- fix margins

Update group listing page

---

resources/assets/less/bem/artist-link-button.less
resources/assets/less/bem/artist.less
resources/assets/less/bem/game-mode-link.less
resources/assets/less/bem/game-mode.less
resources/assets/less/bem/header-v4.less
resources/assets/less/bem/osu-md.less
resources/assets/less/bem/osu-page.less
resources/assets/less/bem/search-forum-post.less
resources/views/rankings/index.blade.php

- update ranking page paddings
- update font weight of artist description, resolves #5719
- update alignment of game mode selector, resolves #5733
- fix wiki title indentation
- update font weight for page title
- update font weight for artist links

Style adjustments

---

resources/assets/lib/notifications/legacy-pm.tsx

Don't show legacy PM notification if none

---

routes/web.php

To match the naming of other wiki pages

Title case wiki sitemap url

---

resources/lang/en/page_title.php

Add missing title for password reset page

---

resources/assets/lib/quick-search/main.tsx
resources/assets/lib/quick-search/worker.ts

- always show link to beatmap search. Resolves #5690
- correctly highlight forum and wiki search link on hover

Quick search fixes

---

resources/assets/less/bem/mobile-menu-tab.less
resources/assets/lib/chat-icon.tsx
resources/assets/lib/register-components.coffee
resources/views/layout/_header_mobile.blade.php
resources/views/layout/_nav2.blade.php

:thinking: 
Also, overflow ![](https://s.myconan.net/2020-03/firefox_2020-03-13_17-07-30.png)

Add chat icon to header menu

---

.travis.yml
app/Http/Controllers/ChatController.php
app/Http/Controllers/Forum/TopicsController.php
app/Libraries/ProfileCover.php
resources/views/forum/topics/replace_button.blade.php
resources/views/rankings/index.blade.php
resources/views/store/products/show.blade.php

Seems working.
- Closes https://github.com/ppy/osu-web/pull/5779
- Closes https://github.com/ppy/osu-web/pull/5780

Update to latest PHP

---

app/Libraries/Multiplayer/Mod.php
tests/Libraries/Multiplayer/ModTest.php

Quick check showed it's usually in the correct type (int).

Add more ruleset check

---

resources/views/vendor/apidoc/partials/info.blade.php

Add note about state parameter in API documentation

---

resources/assets/less/variables.less
resources/assets/lib/import-shims.coffee

Fixes incorrectly aligned floating new discussion box in beatmapset discussion on mobile.

Fix incorrect js-side header height in mobile

---

app/Models/NewsPost.php

Fix news posts navigation

---

app/Libraries/Multiplayer/Mod.php
tests/Libraries/Multiplayer/ModTest.php

Add taiko random mod

---

resources/views/vendor/apidoc/partials/route.blade.php

The directive was added in recent version and used in one place but nothing renders it.

Show URL parameters documentation

---

resources/views/vendor/apidoc/partials/info.blade.php

Add missing parameter in OAuth api doc

---

app/Exceptions/ModelNotSavedException.php

It's user-side error and shouldn't be reported.

Don't report model validation errors to sentry

---

resources/assets/less/bem/user-card-brick.less
resources/assets/lib/user-card-brick.tsx

- smaller font
- shorter height
- friend button removed
- add outline for mutual (pink) and friend (green, if not on friends page)
Resolves #5823.

Update user brick styles

---

resources/assets/less/bem/user-card-brick.less

Using box shadow seem to work better. Also fixed the height being different based on the friend status.
Resolves #5848.

Fix user brick outline

---

resources/assets/lib/user-card-brick.tsx

Forgot that `currentUser` is outside of react.

Fix user brick not updating friend status outline

---

app/Libraries/ProfileCover.php

Was expecting modulo operation to return `0 <= x < base`

Fix user profile cover error on negative id

---

app/Http/Controllers/MatchesController.php
resources/assets/coffee/react/mp-history/content.coffee
resources/assets/coffee/react/mp-history/main.coffee
resources/assets/less/bem/osu-layout.less
resources/assets/less/bem/osu-page.less
resources/views/multiplayer/match.blade.php

Add title to multiplayer match page

---

resources/lang/en/layout.php
resources/lang/en/page_title.php

Copied off 422 because they're relatively similar from client perspective.

Fix page for error code 400

---

app/Http/Controllers/PasswordResetController.php

prefixing is apparently a new thing in laravel 6

Throttle password reset requests

---

app/Libraries/UserVerification.php
resources/lang/en/page_title.php

Fix title of account verification page

---

resources/assets/less/app.less

Use '~' to resolve node_module.
Reference: https://github.com/webpack-contrib/less-loader#webpack-resolver

CSS import cleanup

---

app/Libraries/BBCodeForDB.php
tests/Libraries/BBCodeFromDBTest.php
tests/Libraries/bbcode_examples/autolink.base.txt
tests/Libraries/bbcode_examples/autolink.db.txt
tests/Libraries/bbcode_examples/autolink.html
tests/TestCase.php

Fix bbcode autolink

---

resources/assets/coffee/react/beatmap-discussions/event.coffee
resources/assets/less/bem/beatmapset-event.less
resources/lang/en/beatmapset_events.php

looked inconsistent with other events

Style loved modding event correctly

---

app/Jobs/BroadcastNotification.php
resources/assets/lib/notification-maps/url.ts

Links notifications to the mode specific page if the achievement has a mode-specific setting.
closes #5835

Link medal notification to game mode

---

resources/assets/coffee/react/beatmap-discussions/nominations.coffee
resources/assets/less/bem/beatmap-discussion-nomination.less
resources/assets/less/bem/beatmap-discussions-header-bottom.less

Nomination show and cleanup

---

resources/assets/lib/models/chat/channel.ts

Hide "show more" button on empty chat channel

---

app/Http/Controllers/NewsController.php
app/Models/NewsPost.php
resources/assets/lib/news-sidebar/main.tsx
resources/assets/lib/news-sidebar/month-listing.tsx

Two extra months from previous year when listing for current year during the first three months.
Resolves #5805.

Show extra months on news sidebar

---

resources/assets/coffee/react/beatmapset-page/hype.coffee
resources/assets/less/bem/beatmapset-hype.less
resources/lang/en/beatmapsets.php

- remove titles which are never shown and seems redundant
- adjust margin between items
- full width button because it almost take half of the box width and there are variations in width between locales (up to almost full width)
Resolves #5166.

Beatmap page style adjustments

---

app/Libraries/Multiplayer/Mod.php

Add osu!lazer mania 10K mod

---

resources/assets/coffee/_classes/tooltip-beatmap.coffee
resources/assets/coffee/osu_common.coffee
resources/assets/less/bem/beatmap-icon.less
resources/assets/less/bem/tooltip-beatmap.less
resources/assets/less/layout.less
resources/assets/less/variables.less
resources/assets/lib/beatmap-icon.tsx
resources/assets/lib/globals.d.ts

With the power of css variables.

Simplify difficulty color styling

---

resources/assets/coffee/react/_components/beatmapset-mapping.coffee

Should be on the topmost one in the mapping

Fix react key on wrong element

---

app/Events/NewNotificationEvent.php

Temporarily restore NewNotificationEvent

---

app/Models/Contest.php
resources/lang/en/contest.php

Add different translation for ended contests without end date

---

app/Libraries/BBCodeForDB.php
tests/Libraries/bbcode_examples/basic_audio.base.txt
tests/Libraries/bbcode_examples/basic_audio.db.txt
tests/Libraries/bbcode_examples/basic_audio.html

Copied off image tag parser.
Fixes #5974.

Fix bbcode audio tag parsing

---

resources/assets/less/bem/chat-message-group.less
resources/assets/lib/chat/message-group.tsx

Fix styling "fix" (`/me`) which broke something else (message status), this time it works with both.

Fix chat message status styling

---

resources/assets/coffee/react/beatmapset-page/score-top.coffee
resources/assets/coffee/react/beatmapset-page/scoreboard-table-row.coffee
resources/views/rankings/_spotlight_rankings_table.blade.php
resources/views/rankings/performance.blade.php
resources/views/rankings/score.blade.php

Resolves #5921. Also in beatmap detail page scroreboard. Except it's only for the main link, not  card 🤔

Link user to related mode in ranking and beatmap page

---

resources/assets/coffee/react/beatmap-discussions/nominations.coffee

Clean up nomination buttons

---

resources/assets/coffee/react/beatmap-discussions/discussion.coffee

There's another place which errorred out when post is null.

Add more null check for discussion posts

---

app/Models/Chat/UserChannel.php

Only fetch the ones to be used by ChatStart's hasBlocked/hasFriended.

Limit fetching friends/foes data

---

app/Libraries/Payments/NotificationType.php
app/Libraries/Payments/PaymentProcessor.php
app/Libraries/Payments/PaypalPaymentProcessor.php

web has no process for handling them

Ignore new_case IPN messages

---

resources/assets/less/bem/score-player.less
resources/assets/lib/scores-show/player.tsx

Resolves #6038.
Slightly moves things around but I'd rather have this than dealing with z-index ┐( ･_･)┌
<sub>There's also static positioning the score number but that's just confusing</sub>

Move mods layer on top of score number

---

app/Libraries/Chat.php

Make sure to add sender to channel when sending pm

---

app/Jobs/BroadcastNotification.php
app/Libraries/BeatmapsetDiscussionReview.php
app/Models/Notification.php
resources/assets/lib/notification-maps/category.ts
resources/assets/lib/notification-maps/message.ts
resources/assets/lib/notification-maps/url.ts
resources/lang/en/notifications.php

(also, not sure if conflicts/broken with the refactoring @notbakaneko is doing of `broadcast_notification`)

Add new notification type for the creation of modding reviews

---

resources/assets/less/bem/beatmap-discussion-editor.less

Should work better with larger hover target for the block itself.

Easier hover target for beatmap review toolbar

---

resources/assets/lib/utils/beatmap-helper.ts

Wrong conditional during migration to TypeScript.
Resolves #6078.

Fix default beatmap selector

---

resources/assets/coffee/react/beatmap-discussions/discussion.coffee
resources/assets/coffee/react/beatmap-discussions/user-card.coffee

closes #6085
also fixes missing divider colour on discussion posts

Fix missing usergroup badge

---

app/Http/Controllers/UsersController.php
routes/web.php
tests/Controllers/UsersControllerTest.php

Fix user page redirect on API requests

---

resources/assets/coffee/react/beatmapset-page/score-top.coffee
resources/assets/coffee/react/beatmapset-page/scoreboard-table-row.coffee
resources/assets/less/bem/beatmap-score-top.less
resources/assets/less/bem/beatmap-scoreboard-table.less

Clickable scoreboard rows

---

resources/assets/lib/beatmap-discussions/editor-discussion-component.tsx

Ensure deleted beatmaps aren't selected by default in a review

---

resources/assets/coffee/_classes/beatmap-discussion-helper.coffee

Fix timestamp regex for review editor

---

resources/assets/coffee/react/profile-page/header-info.coffee
resources/assets/less/bem/beatmapset-mapping.less
resources/assets/less/bem/profile-previous-usernames.less
resources/assets/less/bem/user-search-card.less
resources/assets/less/utilities.less
resources/assets/lib/user-card.tsx
resources/views/master.blade.php
resources/views/users/show.blade.php

This is very not thorough.
Also I know I haven't updated page title for beatmap discussion page even though I updated the one inside the page itself.
Maybe enough to resolve #5942?

Improve visibility of spaces in username in some places

---

resources/assets/less/bem/beatmap-discussion-review-post-embed-preview.less

Force line-wrapping for text within review embeds that are too long

---

resources/assets/coffee/react/_components/comments-sort.coffee
resources/assets/coffee/react/beatmap-discussions/user-filter.coffee
resources/assets/less/bem/beatmap-discussions-user-filter.less
resources/assets/less/bem/ranking-select-options.less
resources/assets/less/select-options.less
resources/assets/lib/coffee-modules.d.ts
resources/assets/lib/ranking-filter.tsx
resources/assets/lib/report-form.coffee
resources/assets/lib/select-options.coffee
resources/assets/lib/sort.tsx
resources/assets/lib/spotlight-select-options.coffee
resources/assets/lib/user-list.tsx
resources/views/rankings/index.blade.php

Additional changes excluded from #5889
value change event prop -> `onChange`
event handler -> `handleX` (implies bound function and receives event as first parameter)
`SelectOption`'s `item` is now `option`
`Sort.sortMode ` is `Sort.currentValue`

More conventional prop and function names for SelectOption and Sort

---

resources/assets/lib/notification-maps/url.ts
resources/assets/lib/notification-widget/item-compact.tsx

~~one~~ two of the issues in #5905

Fix user achievement notification missing icons and url

---

app/Http/Controllers/UsersController.php

We're assuming every users have associated with a country in various places.

Add Sentry alert when user registered from unknown country

---

app/Models/Forum/Topic.php
tests/Models/Forum/TopicTest.php

Trim topic title

---

resources/assets/less/bem/osu-md.less

Resolves #6109 (-ish). Not sure if should just disable image in comment altogether.

Limit image size in comment

---

database/factories/BeatmapsetFactory.php

Remove duplicate 'approved_date' in BeatmapsetFactory

---

resources/assets/less/bem/beatmap-discussion-review-post-embed.less
resources/assets/lib/beatmap-discussions/review-post-embed.tsx
resources/assets/lib/globals.d.ts

Fade out deleted embeds within reviews for moderators

---

app/Transformers/Chat/ChannelTransformer.php

Match order of recent messages with messages index

---

app/Http/Controllers/RankingController.php
app/Http/Controllers/UsersController.php
app/Models/Beatmap.php
app/Models/UserStatistics/Mania4k.php
app/Models/UserStatistics/Mania7k.php
app/Models/UserStatistics/Model.php
app/Transformers/UserStatisticsTransformer.php
database/migrations/2020_06_09_041029_add_user_stats_mania_4k7k.php
resources/assets/coffee/_classes/tooltip-default.coffee
resources/assets/coffee/react/profile-page/pp.coffee
resources/assets/coffee/react/profile-page/rank.coffee
resources/assets/less/bem/ranking-filter.less
resources/assets/lib/ranking-filter.tsx
resources/assets/lib/register-components.coffee
resources/assets/lib/sort.tsx
resources/lang/en/beatmaps.php
resources/lang/en/rankings.php
resources/views/rankings/index.blade.php
resources/views/rankings/performance.blade.php
tests/Models/UserStatistics/ModelTest.php

Add ranking page and user rank/pp for 4K and 7K mania

---

resources/assets/less/bem/osu-md.less

Left align standalone image in comment

---

app/Libraries/Multiplayer/Mod.php

Required after https://github.com/ppy/osu/pull/9275

Add pitch adjustment settings to WU and WD mods

---

app/Models/Language.php
database/seeds/ModelSeeders/MiscSeeder.php

Better than having default `language_id` in beatmapset table set to 14.

Swap language id for unspecified and other

---

app/Models/Forum/Post.php
tests/Models/Forum/PostTest.php

Accidentally broken validation when adding the check for quote-only post.
Resolves #6119.

Fix validation for profile page

---

app/Http/Controllers/Multiplayer/Rooms/Playlist/ScoresController.php

Resolves #6101.
Also fixes n+1 on users and countries.

Include cover in score list of multiplayer channel

---

app/Libraries/Search/BeatmapsetSearch.php
app/Models/Beatmap.php
app/Models/BeatmapDifficultyAttrib.php

Seems a bit faster this way with wonderful raw query.

Use subquery to fetch max_combo

---

app/Models/Build.php

Build stream filter wasn't using the list of active streams config.

Match stream filter of builds with active streams

---

app/helpers.php

The included helper builds full client even when disabled. In addition to useless construction, it caused error when pdo_sqlite is not installed even when clockwork is disabled.

Don't initialise clockwork on production

---

app/Libraries/Elasticsearch/Search.php
app/Providers/AppServiceProvider.php
app/helpers.php
config/datadog-helper.php

There are quite a few places we're missing datadog enable check and those were fine so might as well remove all the checks to simplify things.

Remove datadog enable check

---

app/Http/Controllers/Multiplayer/Rooms/Playlist/ScoresController.php
app/Http/Controllers/Multiplayer/RoomsController.php
tests/api_routes.json

I thought I did this already but apparently not 🤔 
There should be anything particularly special in the response.
closes #6055

Add multiplayer rooms and scores to public scope

---

resources/assets/lib/osu-url-helper.ts
routes/web.php

Also adds `wiki` to the internal url list because for some reason all the links in the wiki main page point to `/wiki` instead of `/help/wiki` (but really the main page render should be fixed 🤔 )

Apply web middleware group to redirects

---

app/Models/BeatmapDiscussion.php
app/Models/BeatmapDiscussionPost.php
app/Models/BeatmapDiscussionVote.php
app/Models/BeatmapsetEvent.php
app/helpers.php

Not a complete fix but at least this will refuse generating link to pages beyond 501 and misleading page number when entered manually.

Fix display of pages using max_offset

---

resources/assets/coffee/react/beatmap-discussions/discussion.coffee
resources/assets/lib/beatmap-discussions/review-post-embed.tsx

Skip full page load on review embed/parent links when possible

---

app/Http/Controllers/BeatmapsetsController.php
resources/assets/coffee/react/beatmapset-page.coffee
resources/assets/coffee/react/beatmapset-page/main.coffee
resources/assets/coffee/react/beatmapset-page/score-top.coffee
resources/assets/coffee/react/beatmapset-page/scoreboard-table-row.coffee
resources/assets/coffee/react/beatmapset-page/scoreboard-table.coffee
resources/assets/coffee/react/beatmapset-page/scoreboard.coffee
resources/views/beatmapsets/show.blade.php

Could be useful? :thinking: 
As it turned out, the data is redundant.

Reduce data for countries in beatmapset page

---

app/helpers.php
resources/lang/en/users.php
resources/views/master.blade.php
resources/views/users/show.blade.php

Remove extra spaces in page title and update user page description

---

app/Http/Middleware/DatadogMetrics.php
app/Http/Middleware/VerifyCsrfToken.php

Abort on csrf error for login

---

app/Models/NewsPost.php

Unescape news post author entry from markdown output

---

resources/assets/less/bem/mp-history-game.less

Ellipsis long title in multiplayer match history

---

resources/assets/coffee/react/_components/notification-banner.coffee

Fix navigation after blocking a user

---

app/Http/Controllers/Multiplayer/RoomsController.php
app/Libraries/RouteSection.php
app/helpers.php
database/factories/UserFactory.php
resources/assets/lib/multiplayer-select-options.tsx
resources/assets/lib/osu-url-helper.ts
resources/assets/lib/register-components.coffee
resources/lang/en/layout.php
resources/lang/en/page_title.php
resources/lang/en/rankings.php
resources/views/multiplayer/rooms/_rankings_table.blade.php
resources/views/multiplayer/rooms/show.blade.php
resources/views/rankings/country.blade.php
resources/views/rankings/index.blade.php
routes/web.php
tests/Browser/SanityTest.php
tests/api_routes.json

Timeshift rankings

---

app/Models/Multiplayer/RoomUserHighScore.php
resources/views/multiplayer/rooms/_rankings_table.blade.php

Displaying the sum would be confusing

Show average accuracy on multiplayer ranking

---

resources/assets/lib/react-turbolinks.coffee

Fix link with scroll target sometimes not scrolling properly

---

app/Http/Controllers/Multiplayer/RoomsController.php
app/Models/Multiplayer/Room.php
app/Models/Multiplayer/RoomUserHighScore.php
app/Models/Multiplayer/UserScoreAggregate.php
database/migrations/2020_07_13_055413_add_last_score_id_to_multiplayer_rooms_high.php

Updating the table may take a while :thinking: 
`updated_at` can't be used because any attempts will update the row.
Resolves #6293.

Additionally sort by score id for multiplayer room rankings

---

app/Http/Controllers/Multiplayer/RoomsController.php
app/helpers.php
resources/views/multiplayer/rooms/_rankings_table.blade.php
resources/views/multiplayer/rooms/show.blade.php

A simple pagination.
Resolves #6294 (html part since api part is already has one)

Multiplayer room rankings pagination

---

resources/assets/less/bem/footer.less

Fix #5819 
**Before**
**After**

Fix overflow in footer

---

resources/assets/lib/scoreboard-time.tsx

Fix scoreboard locale shift

---

resources/assets/coffee/react/beatmap-discussions/mode-switcher.coffee
resources/assets/less/bem/page-extra-tabs-before.less
resources/assets/less/bem/page-extra-tabs.less
resources/assets/less/bem/page-mode-link.less
resources/assets/less/bem/page-mode.less

Closed https://github.com/ppy/osu-web/issues/6018
Based on this design https://github.com/ppy/osu-web/issues/6018#issuecomment-637350615
**User page navigation**
**Beatmap discussion page navigation**
Currently I can't check it because I don't know how to create beatmap discussion page. Need help how to create it.

Change floating navigation view

---

app/Http/Controllers/Chat/Channels/MessagesController.php

But somehow the user channel exists.

Fix trying to get chat messages from non-existent channel

---

app/Jobs/Notifications/BroadcastNotificationBase.php
database/factories/UserFactory.php
tests/BroadcastNotificationTest.php

Don't generate notifications for bots

---

app/Libraries/ModsHelper.php
resources/assets/coffee/react/_components/mods.coffee
resources/assets/coffee/react/beatmapset-page/score-top.coffee
resources/assets/coffee/react/beatmapset-page/scoreboard-table-row.coffee
resources/assets/less/bem/mod.less
resources/assets/less/bem/mods.less
resources/assets/lib/play-detail.coffee
resources/lang/en/beatmaps.php

Hidden from web because no icon.
Resolves #6034.

Add support for score v2 mod

---

app/Models/UserProfileCustomization.php

Fix comment section sort not saved

---

app/Http/Controllers/Multiplayer/Rooms/Playlist/ScoresController.php
routes/web.php
tests/api_routes.json

For client to show user's current high score without having to figure out the score id beforehand.

Add endpoint to show user's high score of a multiplayer playlist item

---

app/Models/UserStatistics/Mania4k.php
app/Models/UserStatistics/Mania7k.php

Fix missing hit_accuracy in API response

---

resources/assets/less/bem/chat-input.less
resources/assets/less/bem/osu-layout.less

Fix chat input and no conversations page width mobile

---

app/Http/Controllers/BeatmapsController.php
app/Http/Controllers/RankingController.php
app/Models/Multiplayer/Score.php
app/Models/Score/Best/Model.php
app/helpers.php
config/database.php

New handled by mysql proxy.
Resolves #6318.

Remove readonly db connection

---

app/Http/Controllers/Forum/TopicsController.php
tests/Controllers/ForumTopicsControllerTest.php

Mark topic read on creation

---

.styleci.yml
app/Http/Controllers/Forum/TopicsController.php
app/Models/BeatmapDiscussion.php
app/Models/Forum/Topic.php
config/database.php
tests/Libraries/Transactions/AfterCommitTest.php

Config update and more things being caught by the linter.

StyleCI update

---

app/Models/Beatmapset.php
app/Transformers/BeatmapsetCompactTransformer.php
resources/assets/coffee/react/_components/beatmapset-panel.coffee
resources/assets/coffee/react/beatmap-discussions/header.coffee
resources/assets/coffee/react/beatmapset-page/header.coffee
resources/assets/coffee/react/mp-history/game-header.coffee
resources/assets/coffee/react/profile-page/beatmap-playcount.coffee
resources/assets/lib/beatmapsets/beatmapset-json.ts
resources/assets/lib/play-detail.coffee
resources/assets/lib/quick-search/beatmapset.tsx
resources/assets/lib/scores-show/beatmap-info.tsx
resources/assets/lib/user-link.tsx
resources/assets/lib/utils/beatmap-helper.ts
resources/lang/en/accounts.php
resources/views/beatmapsets/show.blade.php
resources/views/packs/raw.blade.php

missing from #6271
closes #3217
Not sure if I should also rename the option 🤔

Include artist when changing display preferences for Beatmap

---

app/Libraries/Multiplayer/Mod.php

See: https://github.com/ppy/osu/pull/9595

Add start scale to grow/deflate mods

---

app/Http/Controllers/Forum/ForumsController.php
resources/views/forum/topics/show.blade.php
resources/views/objects/search/_forum_options.blade.php
routes/web.php

It redirects back to `home/search` anyway

Remove old forum search redirect

---

resources/assets/coffee/react/beatmaps/search-sort.coffee

Include sorting by updated date for more beatmapset search categories

---

SETUP.md

Some instructions were already added in #6255 for docker
closes #6095

Add documentation for running tests

---

app/Mail/UserNotificationDigest.php
database/migrations/2020_06_12_112518_set_last_mail_notification_id_sent.php
resources/lang/en/mail.php
resources/views/accounts/edit.blade.php
resources/views/emails/user_notification_digest.blade.php

Add missing title and link to settings page. And fix wrong initial marker though it's a bit too late now.

Mail notification fixes

---

app/Console/Kernel.php

Send batch notifications every hour instead of every 10 minutes

Change notification mail interval to 1 hour

---

app/Libraries/Markdown/Indexing/RendererExtension.php
app/Libraries/Markdown/Indexing/TableRenderer.php
app/Libraries/Markdown/OsuMarkdown.php
app/Libraries/Markdown/OsuMarkdownProcessor.php
app/Libraries/Markdown/OsuTableRenderer.php
composer.json
composer.lock

Resolves #5985, resolves #6411.

Update to latest markdown

---

app/Models/User.php

Change hardcoded check bot account in user check profile

---

resources/assets/less/bem/beatmap-scoreboard-table.less

Fix unnecessary horizontal scroll in beatmapset page on mobile

---

resources/assets/less/bem/beatmap-discussion-editor-insertion-menu.less
resources/assets/less/variables.less

Fix discussion review editor block insertion menu covering parts of embed menu

---

resources/assets/less/bem/page-extra-tabs.less

At least in desktop mode; the bar isn't there on mobile
closes #6405

Make User profile navigation bar always be present in viewport

---

resources/assets/less/bem/beatmap-discussion-editor.less

Insertion menu display logic has been changed and it's not needed anymore.

Remove unused placeholder

---

resources/assets/less/bem/dialog-form.less

Fix overlay on oauth page

---

resources/assets/less/bem/play-detail.less

Oversized rank score and pp number hiding at bottom right.

Add missing positioning of play detail on mobile

---

resources/assets/less/bem/score-info.less
resources/assets/less/bem/score-stats.less

I thought I've checked it :thinking: 
Also added fix for horizontal scroll on mobile.

Fix positioning of score page elements

---

resources/assets/less/bem/forum-item.less
resources/assets/less/bem/forum-list.less
resources/assets/less/bem/forum-post.less
resources/assets/less/bem/mods.less
resources/assets/less/bem/mp-history-game.less

Fixes #6498, fixes #6500 and another two problems on multiplayer page.

More fixes on positioning

---

resources/assets/less/bem/landing-hero.less
resources/assets/less/bem/landing-nav.less
resources/assets/less/variables.less

Fix landing page links not being clickable

---

app/Libraries/Multiplayer/Mod.php

Add multiplayer support for mania invert mod

---

resources/assets/coffee/react/beatmap-discussions/nominations.coffee
resources/assets/less/bem/beatmap-discussion-nomination.less
resources/assets/less/bem/btn-osu-big.less

Hopefully this should make the buttons easier to identify and prevent people from accidentally clicking the wrong ones...
fixes #6550

Group beatmap discussion moderation buttons separately and add colour

---

resources/assets/less/bem/download-page.less
resources/lang/en/home.php
resources/views/home/download.blade.php

Not sure if should link to forum or some wiki page :thinking: 
Also adds enchant button.
Reworked the page a bit as well while at it.

Add troubleshooting help on download page

---

resources/assets/coffee/react/beatmap-discussions/new-reply.coffee
resources/assets/less/bem/beatmap-discussion-post.less

Fix position of close button in modding reply box

---

database/seeds/ModelSeeders/ForumSeeder.php

they're used in some places and should be set for normal forums

Seed f_read and f_postcount forum auth options

---

resources/assets/coffee/_classes/stacked-bar-chart.coffee

Fix failtime chart when the data is all zero

---

resources/views/users/beatmapset_activities.blade.php

fixes #6613 , looks like it was forgotten when updating player info page

Fix user modding page title and description

---

database/migrations/2020_09_09_042555_update_comments_index.php

Already done. This adds the migration.

Add sort index and remove unused disqus index

---

composer.lock

fixes #6612, jenssegers/agent checks for it in latest version

Fix Edge browser name

---

app/Jobs/Notifications/CommentNew.php
resources/views/accounts/_edit_notifications.blade.php
tests/Models/CommentTest.php

Temporary fix until someone figures out better place to set the default.
Resolves #6618.

Change default for comment reply notification option

---

resources/views/admin/beatmapsets/show.blade.php

i guess nobody noticed because nobody uses this anymore ='(

Fix modding v2 activation link in admin view

---

resources/assets/less/bem/dialog-form.less
resources/views/layout/_popup_login.blade.php
resources/views/objects/_captcha_script.blade.php
resources/views/sessions/create.blade.php

The other login form used by client verification and oauth.

Add captcha to single-page login form

---

resources/assets/lib/beatmap-discussions/editor.tsx

Previous optimization of not parsing docs on first mount isn't needed anymore. I don't think the `componentDidUpdate` check is still needed either but I keep that for now just in case?

Fix blank form when editing existing beatmap discussion review

---

resources/assets/less/bem/changelog-entry.less

More missed fix from removal of global relative positioning.

Fix changelog icon positioning

---

resources/assets/less/bem/audio-player.less
resources/assets/lib/osu-audio/main.ts

Or if the duration is unknown.
Resolves #6659.

Better duration format when the file hasn't been loaded

---

app/Models/User.php

Regressed during merge of https://github.com/ppy/osu-web/pull/6683.

Fix new email validation function not being used

---

app/Http/Controllers/RankingController.php
resources/docs/source/includes/_structures/cursor.md
resources/views/vendor/apidoc/partials/example-requests/bash.blade.php
resources/views/vendor/apidoc/partials/example-requests/javascript.blade.php

- remove `authenticated` badge
- use proper format for `urlParam`
- add missing `queryParam`
- I think those are all...?
Resolves #6692.

Update documentation for rankings API endpoint

---

resources/views/store/products/show.blade.php

The product title font, style and colour has changed so it's time for this to go.
closes #3629

Remove store product banner text overlay

---

app/Libraries/Payments/PaypalPaymentProcessor.php

Ignore mass-payment callbacks from PayPal

---

resources/assets/coffee/react/beatmap-discussions/main.coffee

Resolves #6122.
Not sure if resolved filter is needed as well :thinking: It's not too difficult to implement but it adds processing overhead.

Show reviews with open issues in pending filter on beatmap discussion

---

README.md

missed this during the changeover

Remove StyleCI badge

---

resources/assets/coffee/main.coffee
resources/assets/lib/app-deps.ts
resources/assets/lib/gallery.coffee
resources/assets/lib/import-shims.coffee

Resolves #6723.
Everything in `_classes` should be relatively easily converted to module :thinking:

Fix broken gallery

---

app/Libraries/BBCodeForDB.php
tests/Libraries/BBCodeForDBTest.php

backend part of #4050 . now on the forum they end up missing the bold and user card since they're plain urls, but that should be the behavior of any url with a user link

Convert [profile] bbcode to [url] at post time

---

resources/assets/coffee/react/beatmapset-page/header.coffee

Alternative for #6456 as it seems rather abandoned. Pretty much what I [said here](https://github.com/ppy/osu-web/pull/6456#issuecomment-673250331).
Resolves #6250.

Fix beatmap favourites listing sometimes not showing correctly

---

app/Libraries/ModdingHistoryEventsBundle.php
app/Libraries/Payments/PaymentProcessor.php
app/Libraries/Payments/PaypalPaymentProcessor.php
app/Models/Artist.php
app/Models/Model.php
app/Models/User.php
app/Traits/Memoizes.php

noticed this pattern in lots of places

Move memoization logic to trait

---

app/Models/Rank.php
app/Models/User.php
app/Transformers/UserTransformer.php
database/migrations/2020_10_06_010117_add_url_to_ranks.php
resources/assets/coffee/react/profile-page/header-info.coffee
resources/assets/less/bem/forum-post-info.less
resources/assets/less/bem/profile-info.less
resources/views/forum/topics/_post_info.blade.php

resolves #3706, downside is if you want to re-use the same title with multiple URLs (like "Featured Artist" from the issue) you'd have to make more ranks.

Add links to user titles

---

resources/assets/less/bem/audio-player.less

Fix alignment of audio player bar under [centre] BBCode

---

resources/assets/less/bem/score-tower.less
resources/assets/lib/scores-show/tower.tsx

not achieved = <del>0.25</del> 0.1 opacity and grayscale
achieved rank = normal opacity
lower than achieved rank = <del>0.5</del> 0.4 opacity
<details>
<summary>before</summary>
</details>
<details>
<summary>after</summary>
</details>

Clearer score rank indicator

---

app/Models/BeatmapPack.php
resources/views/packs/raw.blade.php

Transition to single url is done. Kind of, depending #5477.

Simplify beatmap pack url render

---

resources/assets/lib/chat/chat-worker.ts

Previously, it would just silently fail with a red x.
Also, the ugly error popup is back 🤔 .

Show verification dialog when sending chat message if required

---

resources/assets/lib/chat/chat-orchestrator.ts
resources/assets/lib/chat/chat-state-store.ts
resources/assets/lib/chat/conversation-list-item.tsx
resources/assets/lib/chat/conversation-view.tsx
resources/assets/lib/chat/input-box.tsx
resources/assets/lib/stores/beatmapset-store.ts
resources/assets/lib/stores/channel-store.ts
resources/assets/lib/stores/client-store.ts
resources/assets/lib/stores/comment-store.ts
resources/assets/lib/stores/commentable-meta-store.ts
resources/assets/lib/stores/own-client-store.ts
resources/assets/lib/stores/root-data-store.ts
resources/assets/lib/stores/store.ts
resources/assets/lib/stores/ui-state-store.ts
resources/assets/lib/stores/user-store.ts

Explicit constructor dependency instead of going through `RootDataStore`
part of #6731 plus moving chat state store up one level.

Make store/state constructor dependencies explicit

---

resources/assets/lib/chat.ts
resources/assets/lib/chat/main-view.tsx

It's preparing the app's view state for the views, it shouldn't be in the view's constructor.
more bits from #6731

Move setting of chat initial channel out of view

---

app/Http/Controllers/Forum/ForumsController.php
app/Http/Controllers/Forum/TopicsController.php

Add noindex header to forums and topics which indexing is disabled

---

app/Models/Match/Score.php

Show game and score mods on multiplayer scores

---

app/Http/Controllers/UsersController.php
app/Libraries/ModdingHistoryEventsBundle.php
app/Models/UserScoreable.php
app/Transformers/UserCompactTransformer.php
resources/assets/coffee/react/profile-page/historical.coffee
resources/assets/coffee/react/profile-page/top-ranks.coffee
resources/docs/source/includes/_structures/user_compact.md

Resolves #6633. Some of the counts may not reflect what can actually be fetched thanks to pagination hard limit.
The count seems to be fast enough (including on account with 60k+ plays) so it should be fine...? :shrug:

Include more user profile related counts

---

app/Models/Score/Model.php

MySQL, its wonderful character set system, and its patch version breaking stuff. There might be other breakages but this is enough to get the test pass.
Also I don't know why this works.

Workaround prepared statement and character set incompatibility

---

resources/assets/less/bem/header-buttons.less
resources/assets/less/bem/simple-menu.less
resources/views/wiki/_actions.blade.php

Fix wiki locale menu blocking content underneath it while invisible

---

app/Libraries/LocaleMeta.php

Closes https://github.com/ppy/osu-web/issues/6840.

Adjust language case rules to match expectations

---

resources/assets/less/bem/user-card.less
resources/assets/lib/user-card.tsx

Prevent username from blocking the clicking of the user-card

---

resources/assets/lib/user-group-badge.tsx

fixes issue mentioned in https://github.com/ppy/osu-web/pull/6846#issuecomment-721625603

Fix 'probationary' modifier leaking between user group badges

---

resources/assets/less/bem/chat.less

Fix empty chat overflow

---

composer.json
composer.lock

Something with it made chat system slower.
Also downgraded explicit jwt requirement for minimal change to `composer.lock` file (compared to before the update).

Rollback update of laravel and other packages

---

app/Jobs/Notifications/BroadcastNotificationBase.php
app/Models/UserNotification.php
composer.json
composer.lock

The test I did previously was either incomplete or I read something wrong... or maybe because it's actually fixed by mysql 8.0.22 and that's what's I'm using in my dev.

Speed up marking notifications read

---

app/Models/Beatmapset.php

Skip transaction on inserting new nomination event entry to reduce possibility of two nomination processes running at the same time with both seeing neither of each other's new nomination due to everything being wrapped in transaction.
Additionally make sure only one process can qualify.
Theoretically should resolve #6857.

Reduce potential timing problem on beatmapset nomination

---

.travis.yml

No more fails from mysql download error.

Update Ubuntu used for Travis

---

app/Libraries/ModsHelper.php
app/Models/BeatmapPack.php
app/Models/Score/Best/Model.php
app/Models/Score/Model.php
database/migrations/2020_11_13_025024_add_no_diff_reduction_to_beatmap_packs.php
resources/assets/less/bem-index.less
resources/assets/less/bem/beatmap-pack-description.less
resources/lang/en/beatmappacks.php
resources/views/packs/raw.blade.php

Add "no difficulty reduction mods" mode for beatmapset packs

---

app/Models/Chat/Channel.php

Strip newlines in chat message

---

resources/assets/less/bem/report-form.less

Fix report form button's overlay position

---

app/helpers.php
resources/lang/en/layout.php

Add link for 'report abuse' to help menu

---

resources/lang/en/community.php

Change "non-ranked" text to "pending" for more clarity

---

app/Libraries/Notification/BatchIdentities.php
app/Models/UserNotification.php
resources/assets/lib/notifications/notification-resolver.ts

Fix not being able to delete grouped notifications

---

app/Models/Score/Model.php

This will make report notification on score to link to details page.
Resolves #6902.

Add url method to high score model

---

app/Http/Controllers/LegalController.php
app/Libraries/Markdown/OsuMarkdownProcessor.php
routes/web.php

Side effect is wiki links on page with fallback locale will go to same fallback locale instead of requested locale.

Fix url in legal pages

---

app/Http/Controllers/WikiController.php

That was weird :upside_down_face:

Ensure wiki images endpoint to only serve images

---

app/Transformers/BeatmapCompactTransformer.php
app/Transformers/BeatmapTransformer.php
resources/docs/source/includes/_structures/beatmap.md
resources/docs/source/includes/_structures/beatmap_compact.md

Mainly to be used for lazer multiplayer listing.

Include total length in beatmap json response

---

resources/lang/en/users.php

Fix "in" appearing twice in silence expiry messages

---

resources/assets/lib/beatmap-discussions/nominator.tsx
resources/assets/lib/beatmapsets/beatmapset-json.ts

Fix front-end part of full BN nomination check

---

resources/assets/coffee/react/beatmapset-page/header.coffee
resources/lang/en/beatmapsets.php

Renders a different message and link to the wiki if `download_disabled_url` is set to `rule_violation`

Support beatmapset rule violation message

---

resources/assets/coffee/react/profile-page/detail-bar.coffee
resources/assets/lib/follow-user-modding-button.tsx

Resolves #6939.
Interesting this wasn't caught by the test :thinking:

Hide button for anonymous user

---

app/Models/Beatmapset.php
app/Transformers/BeatmapsetCompactTransformer.php
app/Transformers/BeatmapsetTransformer.php
resources/assets/coffee/react/_components/beatmapset-panel.coffee
resources/assets/coffee/react/beatmapset-page/header.coffee

That was a lot of queries :eyes:

Reduce query for nominations count display

---

resources/assets/coffee/react/_components/comment.coffee
resources/assets/less/bem/comment-vote.less

Remove vote background if user can't vote on a comment

---

app/Http/Controllers/WikiController.php

Resolves #6951 and more (`/$otherLocale/tournament` &rarr; `/$userLocale/Tournament`).

Fix wiki locale on redirect

---

resources/assets/coffee/react/beatmaps/search-sort.coffee

Don't show nominations sort for graveyarded beatmaps

---

app/Models/Multiplayer/Room.php

Never sent by the client. Maybe.

Always use current time for room starts_at

---

resources/assets/lib/click-menu.ts

Fix click menu incorrectly closed in some cases

---

app/Http/Controllers/Multiplayer/Rooms/Playlist/ScoresController.php

Skip client check for admins

---

resources/assets/coffee/_classes/store-supporter-tag.coffee
resources/assets/lib/register-components.coffee
resources/assets/lib/user-card-store.tsx
resources/views/layout/header_mobile/user.blade.php
resources/views/objects/_usercard.blade.php
resources/views/store/products/supporter-tag.blade.php

User card doesn't need all the extra data from `User::defaultJson()`.
I thought it was weird the data for `currentUser` kept getting queried twice 🤔

Reduce data queried for mobile navbar usercard

---

resources/assets/lib/notification-maps/url.ts

resolves #6995 
Took me a long while to figure out what's going on and how the infrastructure works, the fix came out rather simple, though.

Linkify comment replies in stack properly

---

app/Http/Controllers/AccountController.php
resources/assets/coffee/osu_common.coffee

Add better error message when change profile for silenced user

---

app/Transformers/UserTransformer.php

Don't count deleted comments for profile display

---

resources/assets/lib/chat/conversation-view.tsx
resources/lang/en/chat.php

There's been a rule for it for a while now but it was never mentioned in the list of reasons.

Add min plays to list of reasons for not being able to chat

---

app/Http/Controllers/FollowsController.php
tests/Controllers/FollowsControllerTest.php

Forgot that `$follow` may be null.
edit: added tests

Fix error on missing follow

---

app/Models/Multiplayer/Room.php

To prevent orphan room when the user is disconnected after creating the room but before connecting to the multiplayer websocket server.

Enforce ends_at for some multiplayer rooms

---

app/helpers.php

Fix status code check for redirect

---

app/Models/OAuth/Client.php

Skip user oauth client count check if user is not specified

---

SETUP.md

Added a few points that can potentially help future devs deploying environments like https://dev.ppy.sh

Update SETUP documentation

---

resources/assets/less/bem/search-forum-post.less

I can't find documentation on exact conditions so `pointer-events` applies but setting relative position seems to work, so :thinking:

Fix forum search result's username and timestamp

---

resources/lang/en/store.php

Fix typo on store page

---

resources/assets/coffee/react/beatmaps/search-content.coffee

Correctly hide explicit cover for search header based on user setting

---

resources/assets/coffee/_classes/store-supporter-tag.coffee
resources/assets/coffee/store-username-change.coffee
resources/lang/en/errors.php

That was some ancient code. Update the handler to use generic error handler instead with an extra one time "click" handler to show correct thing after verifying.

Fix confusing error message in store

---

resources/views/vendor/passport/authorize.blade.php

Show translated scope description

---

app/Http/Controllers/LegacyInterOpController.php
app/Models/Chat/Channel.php

I tried adding more tweaks but the test hated it (invalid channel name for pm).
And there are definitely more things that can be optimized...

Preload some user data for sending chat

---

resources/assets/coffee/react/beatmapset-page/main.coffee

Keep current beatmap id when switching mode in beatmapset page

---

app/Http/Middleware/VerifyUser.php
app/Libraries/RouteSection.php
resources/assets/lib/notification-widget/main.tsx
resources/assets/lib/notifications/worker.ts
resources/lang/en/notifications.php

Resolves #7079.
This sure took longer than I thought it should :eyes:

Don't show verification for wiki pages

---

resources/assets/less/bem/beatmapsets-search-filter.less
resources/lang/en/beatmaps.php

The label is kinda long and turns out it's already overflowing for some languages.
Resolves #7077.

Update explicit content beatmap filter label

---

app/Http/Controllers/ScoresController.php

Fix include for user card in score detail json

---

resources/assets/coffee/_classes/account-edit.coffee

The usefulness is questionable at best and should be done server side if needed :shrug: 
Resolves #3322 (the column charset has been fixed).

Don't trim account setting fields

---

bin/run_dusk.sh
composer.lock

Add version check for chrome driver installation

---

app/Models/Chat/Channel.php

- inject loaded relation
- guess user id for pm channel
- cache user channels
- preload pm users

Reduce queries for user chat

---

app/Models/Event.php

Simplify event sort query

---

app/Console/Commands/UserNotificationsCleanup.php

Add count to `osu.web.notifications_cleanup.user_notifications`.

Track user notifications cleanup

---

app/Models/Score/Best/Model.php

The check was kinda very wrong :upside_down_face: 
Resolves #7120.

Fix cached rank check

---

resources/assets/lib/play-detail.coffee
resources/lang/en/scores.php

Limited to profile page for now.

Update display of scores currently being processed

---

app/Models/UserNotification.php

Use primary key and chunk by 1000.

Faster notification deletion

---

resources/assets/coffee/react/beatmapset-page/score-top.coffee
resources/assets/lib/play-detail.coffee
resources/assets/lib/scores/pp-value.tsx
resources/lang/en/scores.php
resources/lang/en/users.php

Resolves #7128 and others (fix handling non-best scores, tooltip area).

pp display fixes

---

app/Models/Score/Best/Model.php
routes/web.php

Not sure how I saw the endpoint was hit before :thinking: 
Also add some datadog tracing.

Fix type check for rank lookup

---

resources/assets/coffee/react/contest-voting/art-entry-list.coffee
resources/assets/coffee/react/contest-voting/art-entry.coffee
resources/assets/coffee/react/contest-voting/base-entry-list.coffee
resources/assets/coffee/react/contest-voting/entry-list.coffee
resources/assets/coffee/react/contest-voting/entry.coffee
resources/assets/less/bem/btn-osu-big.less
resources/assets/less/bem/contest-voting-list.less
resources/lang/en/contest.php

A bit late with only 2 days left for the relevant contest ( ﾟ ヮﾟ)a
Resolves #7099.

Add button to only show voted entries

---

resources/assets/lib/notifications/worker.ts

I forgot to check this when trying to figure out the error few days ago.

Fix notification worker function binding

---

app/Libraries/Multiplayer/Mod.php

Add support for osu!mania constant speed mod

---

app/Models/Multiplayer/UserScoreAggregate.php
app/Transformers/Multiplayer/RoomTransformer.php

Don't save temporary user score for transformer placeholder

---

resources/assets/less/bem/user-group-badge.less
resources/assets/lib/beatmap-discussions/mapper-group.ts
resources/assets/lib/user-group-badge.tsx

Update styling of badge for mapper

---

app/Libraries/Multiplayer/Mod.php

Add support for classic osu! mod

---

resources/assets/coffee/react/beatmap-discussions/mode-switcher.coffee

Show difficulty name in beatmapset discussions mode switcher

---

app/Http/Controllers/Forum/TopicsController.php

Simplify null coalesce

---

resources/assets/coffee/react/beatmap-discussions/mode-switcher.coffee

Not sure how I missed this :upside_down_face:

Fix discussion tabs label

---

resources/assets/lib/chat/conversation-view.tsx
resources/lang/en/authorization.php
resources/lang/en/chat.php

Resolves #6981.
There's no notice for public channel...? :thinking:

List being silenced as one of the reasons for not being able to send message

---

app/Http/Controllers/Forum/TopicsController.php

esShouldIndex now always returns false.

Fix condition for topic noindex

---

app/Libraries/Multiplayer/Mod.php
app/Models/Multiplayer/PlaylistItem.php
tests/Libraries/Multiplayer/ModTest.php

Check for exclusive mods that's already required

---

README.md
travis-php.ini

Remove extra unused TravisCI config

---

app/Models/Forum/Topic.php

Fix forum topic deleted post count

---

resources/assets/lib/chat/chat-api-responses.ts
resources/assets/lib/chat/chat-state-store.ts
resources/assets/lib/chat/conversation-view.tsx
resources/assets/lib/models/chat/channel.ts
resources/assets/lib/stores/channel-store.ts

Some reorganizing/fixes because I don't want to keep comparing these diffs while moving chat to use websockets

Slight ConversationView component refactor

---

app/Libraries/Elasticsearch/HasSearch.php
app/Libraries/Elasticsearch/SearchParams.php
app/Libraries/Search/BeatmapsetSearchRequestParams.php
app/Libraries/Search/ForumSearchRequestParams.php
app/Libraries/Search/UserSearchRequestParams.php
app/Libraries/Search/WikiSearchRequestParams.php

Allowing modification of search parameter seems like a rather dangerous idea.
Resolves #7287.

Update dependent parameter when changing search size

---

resources/assets/coffee/react/beatmap-discussions/main.coffee

Exclude hypes from discussion starters list

---

app/Libraries/Payments/PaymentProcessor.php

Fix PaymentProcessor metric name

---

app/Libraries/Search/BeatmapsetSearch.php
app/Libraries/Search/BeatmapsetSearchRequestParams.php
app/Models/Wiki/Page.php
app/helpers.php

Found them when looking around to add the new beatmapset search functions.

Remove old Elasticsearch functions

---

app/Libraries/Search/BeatmapsetQueryParser.php
app/Libraries/Search/BeatmapsetSearch.php
app/Libraries/Search/BeatmapsetSearchParams.php
app/Libraries/Search/BeatmapsetSearchRequestParams.php
tests/Libraries/Search/BeatmapsetQueryParserTest.php

There should be a link to its documentation somewhere...
Resolves #5998.
Depends on:

Advanced query for beatmap search

---

app/Models/User.php
composer.json
composer.lock

Found this when adding favourite button on card. Also updated other lookups while at it.
Bonus point if the servers are updated to have the native extension installed instead of using polyfill (`php7.x-ds`) (native is automatically prioritised over polyfill if installed).

Cache some user related lookup operations

---

app/Jobs/Notifications/BroadcastNotificationBase.php

This is kind of raw but seem to speed up sending notifications with lots of receivers (10s this vs 1min individual inserts on 200k user notifications).

Batch insert notifications

---

app/Models/Beatmapset.php
resources/assets/lib/beatmapsets/beatmapset-json.ts
resources/assets/lib/utils/beatmap-helper.ts

closes #7380
Automatically fallback to `artist` and `title`.
Wonder if they should be named something else 🤔 
(yes the function order is weird)

Fix null artist_unicode and title_unicode fields

---

resources/views/objects/_captcha_script.blade.php

Fix access to captcha instance

---

app/Http/Controllers/Forum/TopicsController.php

I tried updating the count to include deleted posts when showing them but it ended up quite a lot more involved.
Resolves #7278.

Fix jump to last post

---

resources/views/beatmapset_activities/_user.blade.php

The page needs some renovation but here's a patch so I don't need to append `?page=2` just to see how it currently renders.

Fix discussion post listing page with null user

---

resources/assets/lib/utils/beatmapset-discussion-helper.ts

Resolves #7409 (or more like work around it?).

Prevent error on invalid url

---

app/Libraries/Multiplayer/Mod.php

Add AlwaysPlayTailSample classic mod setting

---

resources/assets/lib/beatmapsets/beatmapset-json.ts
resources/assets/lib/interfaces/beatmapset-extended-json.ts

Only adding those used by the new beatmapset card :eyes:  (or probably more)

Update Beatmapset Json interface

---

resources/assets/lib/osu-audio/main.ts

To be used in conjunction with #7419.

Additional attribute when audio plays past halfway

---

app/Http/Controllers/Solo/ScoresController.php
tests/Controllers/Solo/ScoresControllerTest.php

That was a rather fatal oversight :eyes:

Check user id for score completion

---

app/Http/Controllers/ScoresController.php

Changed to `application/x-osu-replay` according to #7202

Less generic replay download MIME type

---

resources/assets/less/bem/beatmapset-panel.less
resources/assets/lib/beatmapset-panel.tsx

This is like the less important problem to fix :eyes:  (but also the easiest)
Follows the one in beatmap info page.

Easier to read date on beatmap card

---

app/Libraries/Multiplayer/Mod.php

To be in line with https://github.com/ppy/osu/pull/12367.

Add follow delay flashlight mod setting

---

resources/assets/less/bem/beatmapset-panel.less
resources/assets/less/bem/beatmapset-status.less
resources/assets/lib/beatmapset-panel.tsx

Limit showing 12 difficulties on beatmap card

---

resources/assets/less/bem/beatmapset-panel.less

Larger cover on beatmap card

---

app/Libraries/Multiplayer/Mod.php

Add support for barrel roll mod

---

app/Models/Solo/Score.php
tests/Models/Solo/ScoreTest.php

Resolves #7477. It's already stored in correct format so there's no need to fix existing data.

Score mods should be of type object

---

.gitignore
package.json

Doesn't fix slowness of checking single file but better than nothing for checking multiple files.
Also rearranged cache file ignores. A bit weird the ignores for `storage` folder are in two different files though.

Cache default eslint call

---

resources/assets/lib/chat/message-group.tsx
resources/assets/lib/user-card-tooltip.tsx
resources/assets/lib/user-link.tsx

Instead of everything just erroring.
Also, finally removes chat's custom user link rendering.
(and fixes usercard missing tooltip position)

Gracefully handle missing user in channels

---

app/Http/Controllers/Solo/ScoresController.php
app/Models/Solo/Score.php
tests/Controllers/Solo/ScoresControllerTest.php
tests/Models/Solo/ScoreTest.php

Add legacy score entry for solo play

---

app/Http/Controllers/FallbackController.php
resources/lang/en/errors.php

Resolves #7516. There's no way to do partial match check from what I can tell.

More useful error on invalid route

---

app/Http/Controllers/UsersController.php
tests/Controllers/UsersControllerTest.php

No redirect on user show API

---

app/Libraries/DbCursorHelper.php

Fix getting last item for cursor

---

app/Libraries/Markdown/StyleBlock/Renderer.php

I just learned in other PR that `new Set(null)` does not work...

Fix fail when no StyleBlock classes are allowed

---

resources/assets/coffee/react/contest-voting/art-entry-list.coffee
resources/assets/coffee/react/contest-voting/art-entry.coffee

Resolves #7584
Can use more clean up but it'll be for another time...

Fix contest art display in "show voted" filter mode

---

resources/assets/coffee/react/contest-voting/art-entry.coffee
resources/assets/less/bem/contest-art-entry.less
resources/assets/less/bem/contest.less

Apparently I didn't push the correct final branch which fixed some mistakes on certain conditions.

Fix art contest page style

---

app/Libraries/OsuAuthorize.php

Check user status when changing beatmap owner

---

resources/assets/lib/beatmap-discussions/event.tsx

Missed the other renderer when updating the thing.
Resolves #7605.

Fix event colour in profile and listing page

---

app/Libraries/OsuAuthorize.php
resources/assets/lib/beatmap-discussions/nominator.tsx
tests/Controllers/BeatmapsetsControllerTest.php

Disallow nomination of beatmapset containing own beatmap

---

resources/assets/coffee/react/beatmap-discussions/discussion.coffee
resources/assets/coffee/react/beatmap-discussions/post.coffee
resources/assets/lib/utils/beatmapset-discussion-helper.ts

Resolves #7604.
There's similar problem on general all and reviews but it needs larger changes to not cause large number of looping through all of the set's beatmaps.

Show correct guest badge in per-beatmap discussion replies

---

resources/assets/lib/utils/beatmapset-discussion-helper.ts

and also the listing
closes #7617

Fix guest badge check for discussions on modding profile page

---

resources/assets/lib/notification-widget/item-group.tsx

Saw this when checking for other stuff :thinking:

Fix hiding mark as read button nearby "show more" button

---

resources/assets/lib/chat/input-box.tsx

Remove stray debug line

---

resources/assets/coffee/react/profile-page/detail-bar.coffee

I thought I checked all instances where currentUser is used in that file :eyes: 
Will look into adding test later.
Resolves #7623

Fix user page not rendering for guest

---

app/Http/Controllers/NewsController.php

Matches landing/dashboard page (kind of).

Don't restrict year when no year is specified for news listing

---

tests/Browser/SanityTest.php

Nothing fancy, just duplicating existing tests but without user logged in.

Add browser tests for guest

---

composer.json
composer.lock

Now with proper php version support :tada:

Update to latest upstream xsolla sdk

---

resources/assets/less/bem/beatmapset-panel.less

Kinda slow and not quite animated correctly.

Remove animated height on beatmap card resize

---

app/Jobs/Notifications/BroadcastNotificationBase.php
app/Models/UserNotificationOption.php
resources/views/accounts/_edit_notifications.blade.php
tests/BroadcastNotificationTest.php

To avoid potentially spamming inactive people who didn't set notification options :thinking:

Disable mail notification by default

---

resources/assets/lib/profile-page/header-info.tsx

Fix missing mobile header background in profile page

---

resources/assets/lib/profile-page/links.tsx

The other css class I forgot to add back in 🤔

Fix missing highlight on last seen date in user profile

---

app/Http/Controllers/MatchesController.php
app/Libraries/OsuAuthorize.php
app/Models/Chat/Channel.php
app/Models/LegacyMatch/Event.php
app/Models/LegacyMatch/Game.php
app/Models/LegacyMatch/LegacyMatch.php
app/Models/LegacyMatch/Model.php
app/Models/LegacyMatch/Score.php
app/Transformers/LegacyMatch/EventTransformer.php
app/Transformers/LegacyMatch/GameTransformer.php
app/Transformers/LegacyMatch/LegacyMatchTransformer.php
database/factories/Chat/ChannelFactory.php
database/factories/LegacyMatch/EventFactory.php
database/factories/LegacyMatch/GameFactory.php
database/factories/LegacyMatch/LegacyMatchFactory.php
tests/Browser/SanityTest.php
tests/Controllers/MatchesControllerTest.php

Just php casually making a word reserved in php 8.
Apparently it's fine for namespace and class method...? :shrug:

Rename Match to LegacyMatch 

---

app/Models/Multiplayer/Room.php

Fortunately nothing appears to use it...yet 👀

Fix Rooms DbCursorHelper sort order

---

.env.example
config/app.php
config/osu.php

Absolute url for default path of user avatar

---

app/Libraries/Multiplayer/Mod.php

Reference: https://github.com/ppy/osu/pull/12568
Only the osu! mod has a seed for now, so I've added a separate entry rather than combining all random mods into one. Will combine once it's moved to the base class (https://github.com/ppy/osu/issues/13319).

Add osu! random mod

---

app/Libraries/Multiplayer/Mod.php

The seed has been moved into the base mod (https://github.com/ppy/osu/pull/13322)
Can be merged at any point - has no logical difference since it's all string mappings.

Combine random mods into one definition

---

app/Libraries/Search/BeatmapsetQueryParser.php
tests/Libraries/Search/BeatmapsetQueryParserTest.php

Good thing test exists :eyes: 
Resolves #7698.

Allow search keyword "star" as alternative to "stars"

---

resources/lang/en/livestreams.php
resources/views/livestreams/_featured.blade.php
resources/views/livestreams/_livestream.blade.php

Use pin icon for livestream promotion and add confirmation dialog

---

build.sh

New thing in composer 2 ( ﾟ ヮﾟ)
Wasn't there similar problem around this before? (was it npm?)

Fix running composer as superuser

---

resources/views/forum/topics/replace_button.blade.php
tests/Controllers/ForumTopicsControllerTest.php

That was fun.
When you dutifully wrote test but forgot to actually commit it.

Fix error when replacing forum button

---

.eslintrc.js
resources/assets/lib/captcha.ts
resources/assets/lib/news-index/main.tsx
resources/assets/lib/news-show/main.tsx
tslint.json
webpack.unmix.js

React `data-*` props makes eslint want to quote all the props

Change ESLint quote-props to as-needed

---

app/Http/Controllers/WikiController.php
app/Libraries/BBCodeForDB.php
app/Libraries/BBCodeFromDB.php
app/Libraries/ImageProcessorService.php
database/migrations/2020_12_03_075220_add_realtime_to_multiplayer_rooms.php
phpcs.xml
tests/Browser/SanityTest.php
tests/TestCase.php

Only a few errors, thankfully.

Add check for string quote style in php files

---

app/Libraries/Multiplayer/Mod.php

See: https://github.com/ppy/osu/pull/13514

Add osu! "Approach Different" mod

---

app/Libraries/Multiplayer/Mod.php

See: https://github.com/ppy/osu/pull/13546

Add AD mod exclusivities

---

resources/assets/less/bem/show-more-link.less

Especially notable on locales with taller font like Japanese.

Fix alignment of arrows on show more button

---

resources/assets/coffee/react/_components/comment.coffee
resources/assets/lib/follows-comment/main.tsx
resources/assets/lib/interfaces/comment-json.ts
resources/assets/lib/models/comment.ts
resources/assets/lib/stores/commentable-meta-store.ts

more things I found after #7756. `CommentableMeta` transformer makes for a weird type.

Fix typing of `Comment` and `CommentableMeta`

---

.github/workflows/lint.yml
.github/workflows/lint/problem-matcher.json
.github/workflows/lint/readme.txt
.github/workflows/lint/src.txt

Incorrect php version were used.
Seems to work :shrug:

Manually run phpcs instead of using action

---

app/Libraries/CommentBundle.php

Fix username display of comment moderators

---

app/Libraries/OsuAuthorize.php

Fix authorize check return typo

---

app/Libraries/Groups.php

Correct usage of local caching

---

resources/assets/coffee/react/modding-profile/detail-bar.coffee

Fix incorrect size of menu button in user modding page

---

app/Libraries/Multiplayer/Mod.php

See https://github.com/ppy/osu/pull/13682 for reference.
This really shows just how complex the osu!-side relationships are to follow :/

Adjust approach rate mod exclusivities

---

app/Models/Multiplayer/Room.php
app/Models/Multiplayer/UserScoreAggregate.php
app/Transformers/Multiplayer/RoomTransformer.php
database/migrations/2021_07_01_091316_add_in_room_to_multiplayer_rooms_high.php

Also only include users currently in room for recent participants of open room.

Add active user indicator in multiplayer rooms high table

---

resources/assets/lib/beatmap-discussions/nominator.tsx
resources/assets/lib/beatmap-discussions/review-document.ts
resources/assets/lib/click-menu.ts
resources/assets/lib/stores/notification-store.ts

Minor typescript lint fixes

---

app/Jobs/Notifications/CommentNew.php

Skip trying to send notification to comment parent if user doesn't exist

---

resources/assets/lib/beatmap-discussions/review-post.tsx
resources/assets/lib/quick-search/worker.ts

I missed those during previous round of fixes.

Wrap switch case with variable declaration in a block

---

app/Models/Notification.php
app/Models/UserGroupEvent.php
app/Models/UserNotificationOption.php

```
>>> User::find(475001)->notificationOptions->first()->user
=> null
```

Fix some user relations using wrong foreign keys

---

app/Models/Twitch/Stream.php

Some links are broken at the moment.

Fix Twitch stream links

---

app/Http/Controllers/Multiplayer/RoomsController.php
app/Models/Multiplayer/Room.php
app/Transformers/Multiplayer/RoomTransformer.php
database/migrations/2021_07_07_065618_add_password_to_multiplayer_rooms.php
resources/lang/en/multiplayer.php
tests/Controllers/Multiplayer/RoomsControllerTest.php

Nothing fancy, just storing the passed parameter to database so the multiplayer server can then take care of it. It's not supposed to be secure either (and may be reset once the room ends).

Multiplayer realtime room password

---

app/Libraries/Payments/PaypalExecutePayment.php

missed one while removing the instance field 🙃

Use correct variable

---

resources/assets/coffee/react/contest-voting.coffee

Missed one part when fixing this file.

Fix render error of contest voting page

---

database/migrations/2021_07_07_065618_add_password_to_multiplayer_rooms.php

Fix multiplayer rooms password migration rollback

---

resources/assets/lib/beatmap-discussions/editor-insertion-menu.tsx

The linter is [a bit buggy](/typescript-eslint/typescript-eslint#3582) at the moment. I think it's better this way anyway as class callbacks using should be bound on declaration.
Made the functions and variables private while at it.

Pre-bind function for throttle

---

resources/assets/less/bem/bbcode-editor.less

closes #7852 
80% viewport size seemed fine to me, so I went with that 🤷

limit maxium height of description modal

---

resources/assets/coffee/react/_components/tracklist.coffee
resources/views/artists/show.blade.php

It was only working for albums...

Fix audio player playlist for non-album listing

---

resources/assets/coffee/react/beatmapset-page/info.coffee
resources/assets/coffee/react/beatmapset-page/stats.coffee
resources/assets/coffee/react/profile-page/historical.coffee
resources/assets/coffee/react/profile-page/rank-chart.coffee
resources/assets/lib/react-turbolinks.ts

Rendering chart on detached 0&times;0 DOM element isn't going to work right.

Fix chart rendering

---

resources/assets/lib/blackout.ts

Broken on conversion to typescript and I missed the slight logic change.

Fix blackout default visible opacity

---

resources/assets/coffee/react/comments-index/main.coffee

Fix selector for comment listing pagination

---

resources/assets/lib/socket-worker.ts

Nothing is separately handling the promise and it's just causing lint error.

Skip returning socket worker start function promise

---

resources/assets/lib/models/chat/channel.ts
resources/assets/lib/models/chat/message.ts
resources/assets/lib/models/user.ts

Kind of pointless to use `Object.create` to skip the constructor call now, not to mention the other quirks from using `Object.create`

Use constructor instead of Object.create

---

resources/assets/lib/beatmap-discussions/discussions-context.ts
resources/assets/lib/beatmap-discussions/review-post-embed.tsx

Fix typing of component and related context.

Review embed typing updates

---

resources/assets/coffee/react/beatmaps/search-panel.coffee

:raised_eyebrow: 
Resolves #7876.

Query correct page when cleaning up during react component mount

---

app/Http/Controllers/ScoresController.php
resources/assets/less/bem/score-player.less
resources/assets/lib/scores-show/player.tsx

Too slow on maps with lots of scores.

Remove score country rank display

---

resources/assets/lib/notifications/worker.ts
resources/assets/lib/socket-message-event.ts
resources/assets/lib/socket-worker.ts

and reject incoming messages missing the `event` property.
Also remove another use of not actually json type 🙃

Add typings for incoming socket messages

---

app/Models/Wiki/Page.php
app/Transformers/WikiPageTransformer.php
resources/views/layout/metadata.blade.php
resources/views/wiki/_actions.blade.php
resources/views/wiki/_locale_menu.blade.php
resources/views/wiki/layout.blade.php
resources/views/wiki/main.blade.php
resources/views/wiki/show.blade.php
resources/views/wiki/sitemap.blade.php

Add language hint on wiki pages

---

resources/assets/lib/shopify-debug.ts

More like working around it because a proper fix of maybe importing `@types/shopify-buy` seems quite involved.

Fix shopify debug typing

---

resources/assets/coffee/_classes/beatmap-discussion-helper.coffee
resources/assets/coffee/_classes/forum-topic-reply.coffee
resources/assets/coffee/_classes/forum.coffee
resources/assets/coffee/osu_common.coffee
resources/assets/coffee/react/beatmap-discussions/main.coffee
resources/assets/coffee/react/beatmapset-page/main.coffee
resources/assets/coffee/turbolinks-overrides.coffee
resources/assets/lib/beatmaps/beatmapset-search-controller.ts
resources/assets/lib/chat.tsx
resources/assets/lib/forum-post-input.ts
resources/assets/lib/globals.d.ts
resources/assets/lib/import-shims.coffee
resources/assets/lib/laroute.ts
resources/assets/lib/notifications/notification-controller.ts
resources/assets/lib/quick-search-button.tsx
resources/assets/lib/ranking-filter.tsx
resources/assets/lib/react-turbolinks.ts
resources/assets/lib/user-list.tsx
resources/assets/lib/utils/beatmapset-discussion-helper.ts
resources/assets/lib/utils/turbolinks.ts

Resolves #7895 and probably more?

Fix current url handling

---

config/octane.php

Fix octane watch sometimes not reloading

---

resources/assets/coffee/react/modding-profile/main.coffee
resources/assets/coffee/react/profile-page/main.coffee
resources/assets/lib/utils/turbolinks.ts

Missed those during previous update.

Update remaining use of document.location

---

app/Models/BeatmapDiscussion.php

Tried adding test but it's taking too long :shrug: 
Resolves #7930.

Fix new problem notification for qualified maps

---

app/Models/BeatmapsetEvent.php

Resolves #7935.
Tests will be added later™

Don't generate beatmap event from a reply

---

tests/Controllers/BeatmapDiscussionPostsControllerTest.php

There was a test for new problems but not one for covering reopening problems which ended up not providing enough coverage leading to #7930

Add notification tests for reopening problems on Beatmap discussions

---

resources/views/home/landing.blade.php
resources/views/layout/_nav2.blade.php
resources/views/layout/header_mobile/nav.blade.php
resources/views/layout/metadata.blade.php
resources/views/master.blade.php

Another thing split off #7925.

Generate nav links and locale meta once when rendering view

---

app/Libraries/BeatmapsetDiscussionReview.php

As usual, tests coming soon™
Resolves #7942.

Fix qualified problem notification being sent on non-qualified maps

---

app/Http/Controllers/PasswordResetController.php
resources/lang/en/password_reset.php

Fix session error on password reset

---

resources/lang/en/follows.php

- change "beatmap" to "beatmaps"
pretty simple change that no one _really_ needs but thought I'd fix it up anyway since I noticed it

Fix wording for mapping follow tooltips

---

resources/assets/coffee/react/_components/big-button.coffee

Just `fa-fw` doesn't quite do anything anymore.

Fix button size randomly changing

---

app/Http/Controllers/ChangelogController.php
app/Models/ChangelogEntry.php
app/Transformers/ChangelogEntryTransformer.php
resources/views/docs/_structures/changelog_entry.md
tests/Models/ChangelogEntryTest.php

Include raw markdown in changelog

---

tests/Controllers/BeatmapDiscussionPostsControllerTest.php
tests/Libraries/BeatmapsetDiscussionReviewTest.php

Additional tests for #7936 #7943

Additional beatmap discussion event tests

---

resources/assets/coffee/react/_components/comment.coffee

I missed this one when updating the function :eyes: 
Resolves #7969.

Fix comment vote button style

---

resources/views/accounts/_edit_notifications.blade.php
resources/views/accounts/_edit_options.blade.php
resources/views/accounts/_edit_playstyles.blade.php
resources/views/accounts/_edit_privacy.blade.php
resources/views/beatmap_discussions/index.blade.php
resources/views/beatmapset_events/index.blade.php
resources/views/forum/topics/_create_poll.blade.php
resources/views/forum/topics/_poll_form.blade.php
resources/views/objects/_switch.blade.php
resources/views/objects/search/_forum_options.blade.php

Pass variables for switch template in `$locals` variable

---

app/Models/Multiplayer/Room.php
app/Transformers/Multiplayer/RoomTransformer.php
database/migrations/2021_08_03_090146_add_type_to_multiplayer_rooms.php
tests/Controllers/Multiplayer/RoomsControllerTest.php

<del>Fake category value in response for now until client is updated....</del> or is it not needed?
Resolves #7962.

Change multiplayer realtime category into types

---

app/Models/Multiplayer/Room.php
tests/Controllers/Multiplayer/RoomsControllerTest.php

Count playlist and realtime rooms separately

---

app/Http/Controllers/Multiplayer/RoomsController.php
app/Models/Multiplayer/Room.php
app/Transformers/Multiplayer/RoomTransformer.php

The query involved is wunderbar ( ﾟ ヮﾟ) (also the way preloading is done)
Haven't checked if index is required but doesn't seem too slow.
Resolves #7972.

Include recent participants in rooms index

---

app/Libraries/Multiplayer/Mod.php

See: https://github.com/ppy/osu/pull/14173

Add support for osu!catch mirror mod

---

README.md

Before I forget about this again for the 13049135th time after looking at the readme.

Update PHP version requirement in `readme`

---

resources/lang/en/beatmapsets.php

Title describes it. Small fix but a fix nonetheless

Fix grammar for empty friend leaderboard notice

---

app/Http/Controllers/BeatmapDiscussionsController.php
app/Http/Controllers/BeatmapsController.php
app/Http/Controllers/ScoresController.php

Relying on `findOrFail` to filter out silly input turns out to be not as reliable as expected. 🙃

Use model key when possible for redirecting

---

app/Http/Controllers/Chat/ChatController.php
app/Libraries/UserChannelList.php
app/Models/Chat/Message.php

Found when checking the refactor PR.

Reduce query for chat page

---

resources/assets/coffee/react/_components/tracklist-track.coffee
resources/lang/en/artist.php

As suggested in staff chat room. Only changes the text for now because the whole thing is getting a redesign.

Rename featured artist track osu! exclusive to osu! original

---

app/Http/Controllers/ArtistsController.php

Slightly faster query. Or much faster.

Existence check for featured artist maps instead of full count

---

composer.json
composer.lock

update framework to support commonmark v2.0

Update laravel framework to version 8.58

---

resources/assets/less/bem/osu-md.less

Remove extra top margin of first child.

Fix wiki infobox padding

---

app/Models/UserReport.php
resources/assets/coffee/react/beatmapset-page/header.coffee
resources/assets/lib/utils/beatmapset-helper.ts
resources/lang/en/model_validation.php

Limit reportable beatmap states

---

resources/assets/lib/core/osu-audio/main.ts

Forgot there are two different players :eyes: 
Should get around combining and converting them to react sometime...
Resolves #8131

Add missing play button

---

app/Libraries/OsuAuthorize.php
app/Models/Chat/Channel.php
tests/Libraries/ChatTest.php
tests/Models/Chat/ChannelTest.php

Allow chat bots to send messages to users regardless of block or friend settings

---

app/Models/Multiplayer/Score.php

The test for multiplayer score update is missing :eyes: 
Will add that later.

Fix multiplayer score validation

---

app/Models/Chat/Message.php
app/Models/Chat/UserChannel.php
app/Models/Score/Model.php
app/Models/Spotlight.php

For some reason there are still a few left.

Remove redundant Eloquent model guard setting

---

app/Models/Solo/Score.php
tests/Models/Solo/ScoreTest.php

Fix missing legacy stats when converting lazer score

---

resources/assets/coffee/react/_components/comments-manager.coffee

Fix CommentsManager event handler leak

---

database/factories/BuildFactory.php
database/factories/CommentFactory.php
database/seeders/ModelSeeders/ChangelogSeeder.php
tests/Browser/SanityTest.php
tests/Controllers/Multiplayer/Rooms/Playlist/ScoresControllerTest.php
tests/Controllers/Solo/ScoreTokensControllerTest.php
tests/Libraries/ReportCommentTest.php
tests/Models/CommentTest.php
tests/RouteScopesTest.php

And refactors of related things :broom:

Multiplayer score update test

---

composer.json
phpcs.xml

No wonder things didn't quite work until I manually run composer install :raised_eyebrow:

Add missing model factory psr-4 definition (and adjust linter)

---

app/Models/User.php

Also log (and return generic hint) when invalid username is being passed through oauth password auth.

Simplify OAuth password auth handling

---

app/Libraries/Markdown/OsuMarkdown.php
resources/views/contests/enter.blade.php
resources/views/contests/voting.blade.php

Allow html input for contest page markdown

---

resources/views/store/products/show.blade.php

Fix store request notification button style 

---

resources/assets/coffee/react/modding-profile/detail-bar.coffee
resources/assets/coffee/react/profile-page/detail-bar.coffee
resources/assets/lib/popup-menu.coffee
resources/assets/lib/profile-page/extra-menu.tsx

Fix popup menu clipping offscreen

---

app/Http/Controllers/Solo/ScoreTokensController.php
app/Models/Beatmap.php
database/factories/BeatmapFactory.php
tests/Controllers/Solo/ScoreTokensControllerTest.php

Update allowed beatmap types for score submission

---

resources/assets/lib/beatmap-discussions/icon-dropdown-menu.tsx
resources/assets/lib/coffee-modules.d.ts
resources/assets/lib/popup-menu.coffee

Just recycles the existing clipping logic for now.
Doesn't test for clipping in the other direction since that isn't needed.....yet 👀

Fix discussion review selector menu popup direction

---

database/factories/UserFactory.php

Ensure unique username and email in tests

---

app/Models/Multiplayer/Room.php
database/migrations/2021_11_17_073841_add_queue_mode_to_multiplayer_rooms.php

Updating existing migration while deploy hasn't happened yet :shushing_face:
Blocking until I can test (PRing for CI).

Update queue mode names

---

resources/assets/lib/interfaces/event-json.ts
resources/assets/lib/profile-page/parse-event.tsx
resources/assets/lib/profile-page/recent-activity.tsx
resources/assets/lib/utils/switch-never.ts

Placing things where they belong :broom: 
(also the `switchNever`)

Move EventJson to its own file

---

resources/assets/lib/profile-page/detail.tsx

Fix profile page detail class name

---

app/Http/Controllers/Chat/ChannelsController.php

Fix params target_id cast

---

resources/assets/coffee/react/profile-page/game-mode-switcher.coffee
resources/assets/coffee/react/profile-page/main.coffee
resources/assets/lib/interfaces/game-mode.ts
resources/assets/lib/utils/beatmap-helper.ts

Seems like it belongs there instead?

Move gameModes to GameMode interface file

---

app/Models/User.php

Nothing is using it anymore :shrug:

Remove User lastPlayed function

---

app/Http/Controllers/LegacyInterOpController.php

Quick update splicing in support for public channels into LIO
will fix #8393 after other relevant parts are updated to send to `_lio`

Add support for sending public channel messages through LIO

---

app/Models/Chat/Channel.php

The `return` was to skip incrementing the join count 🤔

Revert channel.join counting change

---

app/Http/Controllers/LegacyInterOpController.php
app/Http/Middleware/LegacyInterOpAuth.php
app/Libraries/OsuAuthorize.php

In hindsight, `type` is just `pm` or `not pm` 👀

Support sending message to any channel type via LIO

---

app/Libraries/OsuAuthorize.php

The user channel entry will need to be added eventually...

Allow access to non-pm channels when using interop

---

app/Models/Multiplayer/PlaylistItem.php
app/Models/Multiplayer/Room.php
app/Transformers/Multiplayer/PlaylistItemTransformer.php
database/migrations/2021_12_03_102651_add_played_at_to_playlist_items.php
tests/Models/Multiplayer/RoomTest.php

Rather than abusing `updated_at`.

Add played_at column to playlist items

---

database/factories/UserFactory.php

That's not what the second parameter is for...

Fix substring call in user model factory

---

resources/lang/en/beatmappacks.php

- simplify installation instructions 
- rephrase a few things

simplify beatmap pack installation instructions

---

resources/assets/lib/profile-page/achievement-badge-popup.tsx
resources/assets/lib/profile-page/achievement-badge.tsx
resources/assets/lib/profile-page/medals.tsx
resources/assets/lib/profile-page/parse-event.tsx

noticed while reviewing #8372 that only the date is needed

Simpler props for AchievementBadge

---

resources/assets/lib/chat/conversation-view.tsx

Before I forget about it again.
This seems to have been missing forever 👀

Remove listener on ConversationView unmount

---

app/Models/Multiplayer/Room.php

There's no `$user` in `Room` (and everything that calls it is amazingly after `setRelation`)

Fix preset relation name in Room

---

resources/assets/less/bem/btn-osu-big.less

I forgot that `background` property overrides all other background properties 👀

Fix download button hover background

---

resources/assets/lib/stores/channel-store.ts

Fix chat public channel order

---

resources/assets/lib/playmode-tabs.tsx

Fix display check for playmode tabs count label

---

database/factories/BeatmapsetFactory.php

Too long title causing test failures 😐

Limit title length for beatmapset model factory

---

resources/assets/coffee/_classes/current-user-observer.coffee

Fix error trying to observe guest user's nonexistent cover

---

resources/assets/lib/import-shims.coffee

Forgot to remove after updating relevant files...
Also removed unused imports.

Remove unused export shims

---

resources/assets/coffee/_classes/account-edit-avatar.coffee
resources/assets/coffee/_classes/forum-cover.coffee
resources/assets/coffee/react/contest-entry/uploader.coffee
resources/assets/lib/import-shims.coffee

One thing and another lead to cleaning up export shims... 👀

Directly import fileupload callback

---

webpack.unmix.js

Only used in one place which already does importing.

Remove Cookies webpack plugin

---

database/migrations/2015_01_01_133337_base_tables.php

Already updated live and making migration just for this is a bit too much effort ( ﾟ ヮﾟ)

Update username change history table to use utf8(mb4)

---

resources/assets/lib/charts/line-chart.ts
resources/assets/lib/profile-page/historical.tsx

Use UTC time for charts

---

app/Http/Controllers/BeatmapsetsController.php
tests/Controllers/BeatmapsetsControllerTest.php

Resolves #8524. The card will still be shown but its link will be 404.

Only show beatmapset page if it has beatmaps

---

app/Models/Score/Best/Model.php
app/Models/Score/Model.php
app/Transformers/Score/CurrentUserAttributesTransformer.php
app/Transformers/ScoreTransformer.php
resources/assets/lib/core/user/score-pins.ts
resources/assets/lib/osu-core.ts
resources/assets/lib/utils/score-helper.ts

Fix unable to pin best score from non-best score model

---

app/Libraries/Multiplayer/Mod.php

Reference: https://github.com/ppy/osu/pull/16473

Add support for flashlight mod size settings

---

package.json
resources/assets/lib/entrypoints/app.ts
yarn.lock

Removed unused url polyfill and ran yarn-deduplicate while at it.

Remove url-polyfill

---

yarn.lock

As it's been yelling in the console all this time. (also ran yarn-deduplicate)

Update browserslist package

---

resources/assets/less/bem/account-edit-entry.less

Fix account settings saved message

---

resources/assets/lib/profile-page/header-info.tsx

Import specific lodash util

---

resources/assets/less/bem/osu-layout.less

Remove unused layout css modifiers

---

resources/assets/less/bem/page-mode-link.less
resources/assets/less/bem/page-mode.less

There was a time when floating forum topic reply box shared style with page-mode. And then it's not anymore 🧹

Remove unused css modifiers

---

resources/assets/lib/user-multiplayer-index/multiplayer-history.tsx
resources/lang/en/multiplayer.php

closes #8568
inb4 different languages need different grammar 👀

Show different text for empty lists of different game types

---

app/Libraries/Multiplayer/Mod.php

Usually I do these one by one, but this time three mods made upstream in two days, so I'm batching these together to reduce noise.
References:
* https://github.com/ppy/osu/pull/16658
* https://github.com/ppy/osu/pull/5774
* https://github.com/ppy/osu/pull/16701
Didn't bother specifying incompatibility groups with autoplay in 2/3 cases as autoplay is not a user-playable mod anyway.

Add support for new lazer mods

---

app/Libraries/Markdown/OsuMarkdown.php

Temporarily disable inline container for wiki markdown

---

tests/Models/UserProfileCustomizationTest.php

Preventing last week's breakage from happening again ( ﾟ ヮﾟ)

Add test for user settings update

---

tests/Browser/SanityTest.php
tests/Controllers/BeatmapDiscussionsControllerTest.php
tests/Libraries/BeatmapsetDiscussionReviewTest.php
tests/Models/BeatmapDiscussionPostTest.php
tests/Models/BeatmapDiscussionTest.php
tests/Models/BeatmapsetTest.php

`'discussion_enabled' => true` is already the default; might as well change them all now

Skip calling Beatmapset factory with discussion default

---

config/osu.php

Seems like a better target these days.

Update footer server status link to page rather than twitter

---

app/Libraries/User/ScorePins.php

Uh, yeah, that'd definitely be slower over time otherwise 👀

Filter score pins by user

---

resources/assets/coffee/react/beatmap-discussions/new-discussion.coffee
resources/lang/en/beatmaps.php

Add confirmation for reporting problem on qualified maps

---

app/Http/Controllers/Multiplayer/RoomsController.php
app/Models/Multiplayer/Room.php
app/Transformers/Multiplayer/RoomTransformer.php
app/helpers.php

Removes beatmap include and adds `difficulty_range.min` and `difficulty_range.max` 🤔 
...when `x-api-version: 20220215` is specified on the header.

Restructure rooms listing

---

resources/assets/coffee/shared.coffee

Like #8533 but actually working.
Resolves #8532.
closes #8533

Fix removal of popup message element after fading out

---

SETUP.md

Found a possible typo in the docs.

Fix typo in the setup docs

---

resources/assets/less/bem/header-v4.less
resources/assets/less/bem/profile-info.less
resources/assets/lib/components/header-v4.tsx
resources/assets/lib/profile-page/cover.tsx
resources/assets/lib/profile-page/detail.tsx
resources/assets/lib/profile-page/header.tsx

Fix location of profile cover update spinner

---

resources/assets/less/bem/header-v4.less

Adjust nav menu background opacity of user page

---

resources/assets/less/bem/profile-stats.less

Remove highlight for ranked score

---

resources/assets/lib/profile-page/detail-bar.tsx

Shouldn't have removed the other check when updating the block check method 👀

Hide message link on own profile page

---

resources/assets/less/bem/profile-detail-bar.less
resources/assets/lib/profile-page/detail-bar.tsx

As reported somewhere else <sup>(reddit)</sup>

Fix profile page detail bar button height

---

resources/assets/less/bem/bbcode-editor.less
resources/assets/less/bem/page-extra.less

Missed this when doing the page extra restyle.

Fix style of profile page me! section editor

---

resources/assets/less/bem/page-extra.less
resources/assets/less/bem/sortable-handle.less
resources/assets/less/variables.less

After looking closer, the handles aren't quite aligned correctly.

Fix alignment of profile page sort handle

---

resources/assets/less/bem/wiki-notice.less
resources/assets/lib/profile-page/top-scores.tsx

Current `b4` is the same as section background...

Fix ranks section notice background

---

resources/assets/less/bem/profile-detail.less
resources/assets/less/bem/profile-stats.less
resources/assets/less/bem/value-display.less
resources/assets/lib/profile-page/detail.tsx

Equal width stats column (to align with ranking display) and fix font size of ranking display.

Adjust mobile version of profile page details

---

resources/assets/less/bem/profile-info.less

A bit larger (actually closer to original design) and add some margins and increase font size on mobile.

Increase cover username area

---

resources/assets/less/bem/value-display.less

Fix kudosu value font size

---

app/Http/Controllers/Multiplayer/RoomsController.php

...maybe? 🤔 Only for realtime/multiplayer rooms.

Hide maps without scores for multiplayer display page

---

app/Transformers/Multiplayer/RoomTransformer.php
resources/assets/lib/interfaces/room-json.ts
resources/assets/lib/user-multiplayer-index/room.tsx

Turns out end time is nullable.

Fix active rooms end time display

---

resources/assets/lib/user-multiplayer-index/room.tsx

Show active maps count for active room

---

resources/assets/less/bem/profile-stats.less

Before I forget about this again 👀 
Resolves #8688.

Center user stats

---

app/Libraries/Multiplayer/Mod.php

Reference: https://github.com/ppy/osu/pull/17054

Add "Adaptive Speed" mod

---

resources/assets/lib/beatmap-discussions/post.coffee

Combine isReview check

---

app/Models/BeatmapDiscussionPost.php

Revert slow beatmap discussion post listing query

---

package.json
yarn.lock

🤨 
Originally required by elixir (ha ha).

Remove unused require-dir

---

app/Models/UserReport.php
resources/assets/lib/components/report-form.coffee
resources/lang/en/users.php
tests/Libraries/ReportCommentTest.php
tests/Libraries/ReportScoreTest.php
tests/Libraries/ReportUserTest.php

resolves #8123
- redirects all score related reports to the cheating endpoint
- requires comments for report to be submittable

Report improvements

---

resources/assets/lib/beatmaps/search-panel.coffee

Found this when checking for react update.

Update mobx observable using runInAction

---

app/Libraries/Multiplayer/Mod.php

Reference: https://github.com/ppy/osu/pull/17331

Add incompatibility rule for Aim Assist & Relax mods

---

app/Models/Solo/ScoreData.php
tests/Controllers/Solo/ScoresControllerTest.php

The one coming from controller is already an object (from output of `Mod::parseInputArray`).

Try converting input mod data to array

---

app/Libraries/Multiplayer/Mod.php

See https://github.com/ppy/osu/pull/17356

Add support for strict tracking mod

---

resources/assets/less/bem/osu-md.less

Looks like we made them too compact 🤔 
closes #8743

Fix wiki infobox stacking

---

resources/assets/lib/chat/chat-api.ts
resources/assets/lib/entrypoints/chat.tsx
resources/assets/lib/models/user.ts
resources/assets/lib/osu-core.ts
resources/assets/lib/stores/root-data-store.ts
resources/assets/lib/stores/user-store.ts
tests/karma/osu-core.spec.ts

We never ended up making use of it and probably won't with the current direction

Remove unused User.load() feature

---

app/Libraries/Markdown/Osu/Extension.php
tests/Libraries/Markdown/ProcessorTest.php

Use correct id attribute for wiki table of content

---

app/Models/Comment.php
tests/Models/CommentTest.php

Unpin comment on delete

---

resources/assets/coffee/osu_common.coffee
resources/assets/lib/beatmapsets-show/main.coffee
resources/assets/lib/modding-profile/main.coffee
resources/assets/lib/utils/beatmapset-page-hash.ts

Pretty much only used in one component

Typescript osu_common setHash

---

app/Models/RankHistory.php
resources/assets/lib/profile-page/rank-chart.tsx

Remove need of readjusting for display.

Use live rank for rank history last entry

---

resources/assets/lib/beatmapsets-show/main.coffee

Remove beatmap page event listener on unmount

---

app/Libraries/Multiplayer/Mod.php

See ppy/osu#17588. Please don't merge just yet, will deploy alongside the next lazer release as this will be a somewhat breaking change.

Rename "Aim Assist" to "Magnetised"

---

resources/assets/lib/components/mod.tsx

Originally intended to combine the modifiers and mod but then noticed the component no longer has any actual modifiers.

Simplify Mod component

---

resources/assets/lib/components/user-card-brick.tsx

I don't think there's anything passing such object yet...

Fix array access in case the user is observable

---

resources/assets/less/bem/user-card-brick.less
resources/assets/less/bem/user-cards.less

Gap on flexbox is now a thing.

Simplify user brick margin

---

resources/lang/en/home.php

someone i know found an typo and i ended up finding another two. I believe its now correct, but someone please double check as i am not a native english speaker
could use "any problems" instead of "a problem", no clue which one is preferred

Fix Typos on Downloads Page

---

resources/assets/less/bem/chat-conversation-list-separator.less
resources/assets/less/bem/chat-conversation-list.less
resources/assets/lib/chat/conversation-list.tsx
resources/lang/en/chat.php

And remove the group separators as part of the newer chat channel list design

Add channel type group headers to channel list 

---

resources/assets/lib/utils/user-helper.ts

block checking now goes through `UserModel.blocks`

Remove unused helper

---

app/Http/Controllers/BeatmapsController.php
tests/Controllers/BeatmapsControllerTest.php

Accept int for mods parameter

---

resources/assets/less/bem/beatmap-playcount.less

Remove padding to avoid taller text from increasing item height

---

resources/views/objects/_beatmapset_cover.blade.php

No need to check if the map isn't explicit to begin with 🤷

Skip user preferences check if not needed

---

resources/assets/lib/beatmap-discussions/main.coffee
resources/assets/lib/beatmap-discussions/new-discussion.coffee

More of the fallout from mount-before-render update.
Also for auto focus for new discussion.

Fix discussion link sometimes not scrolling to the discussion

---

app/Models/Beatmap.php

Remove unused function in beatmap model

---

resources/assets/coffee/_classes/beatmap-discussion-helper.coffee
resources/assets/lib/beatmap-discussions/header.coffee
resources/assets/lib/utils/beatmapset-page-hash.ts
resources/assets/lib/utils/math.ts

Resolves #8857.
Also added a useful version of `parseInt` called `getInt`.

Add conditional default mode and switch to timeline when switching diff

---

resources/assets/coffee/_classes/beatmap-discussion-helper.coffee
resources/assets/lib/notification-maps/url.ts

Unfortunately there's no indicator in the event whether it's a reply or new discussion so everything have post id appended even for new discussion 🤔 
Resolves #8843

Link to post for beatmap discussion notifications

---

resources/assets/lib/artist-tracks-index/main.tsx
resources/assets/lib/beatmap-discussions/editor.tsx
resources/assets/lib/beatmap-discussions/love-beatmap-modal.tsx
resources/assets/lib/beatmap-discussions/nominator.tsx
resources/assets/lib/beatmaps/main.tsx
resources/assets/lib/beatmapsets-show/metadata-editor.tsx
resources/assets/lib/components/report-reportable.tsx
resources/assets/lib/globals.d.ts
resources/assets/lib/models/oauth/client.ts
resources/assets/lib/models/oauth/own-client.ts
resources/assets/lib/notifications/notification-resolver.ts
resources/assets/lib/oauth/authorized-client.tsx
resources/assets/lib/oauth/client-details.tsx
resources/assets/lib/oauth/own-client.tsx
resources/assets/lib/stores/channel-store.ts
resources/assets/lib/utils/ajax.ts

Apparently I forgot about this myself 🙃 
Also `catch` and jquery ajax doesn't quite work well together because there's no reliable way to check if the error is a jquery xhr.

Remove osu.ajaxError from typescript and fix missing mobx action

---

app/Http/Controllers/UsersController.php
resources/assets/lib/beatmap-discussions/beatmap-owner-editor.tsx
resources/assets/lib/beatmap-discussions/beatmaps-owner-editor.tsx
resources/assets/lib/models/user.ts

Add missing `action`s, normalise input username, and update debounce logic with one that hopefully works better.

Beatmap owner editor lookup fixes

---

routes/web.php
tests/Controllers/HomeControllerTest.php
tests/api_routes.json

Fix routing for download quota check

---

app/Http/Controllers/CommentsController.php
app/Libraries/OsuAuthorize.php
app/Models/Beatmapset.php
app/Models/Comment.php
resources/lang/en/authorization.php
tests/Controllers/BeatmapsetsControllerTest.php
tests/Controllers/CommentsControllerTest.php

Disable description edit and comment on certain beatmaps

---

resources/assets/lib/core/user/user-login.ts

What's the worst that can happen 🤷

Immediately reload on login if no callback is set

---

resources/assets/lib/beatmapsets-show/nsfw-warning.tsx

Almost nothing else waits for it to finish 🤔

Remove wait for preference setting update

---

resources/assets/lib/beatmapsets-show/metadata-editor.tsx

Simplify int parsing

---

resources/assets/lib/beatmapset-panel/beatmaps-popup.tsx

Before I forget about this again.

Fix wrong beatmap popup position on resize

---

resources/assets/less/bem/page-nav-fancy.less

Fix news nav icon visibility

---

resources/assets/less/bem/beatmaps-popup.less

Don't animate beatmap popup repositioning

---

.github/workflows/pack.yml

SENTRY_AUTH_TOKEN secret is already added org-wide

👷 Submit tagged releases to Sentry

---

resources/assets/less/bem/comment-editor.less

Fix positioning of user avatar in new comment box

---

DEPLOYMENT.md
app/Http/Controllers/Payments/XsollaController.php
resources/assets/lib/store-xsolla.coffee
webpack.unmix.js

Seems to make sense this way? 🤔 
Mainly to reduce need of passing env vars to js during build step.

Pass XSolla sandbox option when fetching token

---

resources/assets/less/bem/page-extra-tabs.less

Resolves #8701 (or more like works around).

Fix gap on profile page nav header on Chrome

---

resources/assets/coffee/osu_common.coffee
resources/assets/coffee/shared.coffee
resources/assets/lib/core-legacy/forum.coffee
resources/assets/lib/globals.d.ts
resources/assets/lib/notification-widget/item.tsx
resources/assets/lib/utils/html.ts
tests/karma/utils/html.spec.ts

Also consider option to be input element.

Typescript isClickable and isInputElement

---

resources/assets/lib/chat/chat-state-store.ts
resources/assets/lib/utils/html.ts

Resolves #8770. This will nicely conflict with the new announcement thing 🙃

Set channel name on browser title

---

app/Libraries/OsuWiki.php
app/Models/NewsPost.php

Fix missing news posts

---

app/Libraries/BBCodeFromDB.php
app/Libraries/CleanHTML.php
app/Providers/AppServiceProvider.php

Reuse html purifier instance and always create cache directory

---

app/Models/Solo/Score.php

That was weird 🤨 
The function will be used by transformer include.

Add missing solo score relation and function

---

app/Libraries/Groups.php
database/migrations/2022_05_23_052743_add_unique_index_to_groups_identifier.php

@ppy need a new migration entry
```
2022_05_23_052743_add_unique_index_to_groups_identifier
```

Add unique constraint to group identifier

---

app/Models/Solo/Score.php
app/Models/Solo/ScorePerformance.php

I forgot the migration already exists so things are easier than I initially thought 🕺

Add ScorePerformance model

---

app/Models/User.php

That was weird. Update to use morbin helper while at it.

Add missing notifiable type filter

---

app/Libraries/Score/UserRankCache.php
app/Models/Score/Best/Model.php

To be used by solo score as well.

Split out user rank cache function

---

app/Http/Controllers/Chat/ChannelsController.php
app/Models/Chat/Channel.php
app/Transformers/Chat/ChannelTransformer.php
resources/assets/less/bem/chat-conversation.less
resources/assets/less/bem/user-card-brick.less
resources/assets/less/bem/user-cards.less
resources/assets/less/spinner.less
resources/assets/lib/chat/chat-api.ts
resources/assets/lib/chat/chat-state-store.ts
resources/assets/lib/chat/conversation-view.tsx
resources/assets/lib/components/user-card-brick.tsx
resources/assets/lib/components/user-list.tsx
resources/assets/lib/models/chat/channel.ts
resources/assets/lib/models/user.ts
resources/assets/lib/stores/channel-store.ts
resources/lang/en/chat.php
tests/Models/Chat/ChannelTest.php

(mostly) The relevant portions for rendering the list of users in announcement channels extracted from #8747.
closes #8950

Show user list in announcement channel

---

app/Models/Multiplayer/Room.php
database/migrations/2022_05_27_094956_add_featured_artist_to_multiplayer_rooms_category.php

filtering should work just like `spotlight` except using `featured_artist` instead.

Add featured artist category to multiplayer rooms

---

package.json
webpack.unmix.js
yarn.lock

The svg is included this one so it should be more reliable compared to additional download in postinstall script.

Use a different twemoji package

---

config/osu.php

Update email recovery process link in account verification dialog

---

resources/assets/lib/chat/chat-api.ts
resources/assets/lib/chat/chat-state-store.ts
resources/assets/lib/chat/conversation-list-item.tsx
resources/assets/lib/chat/create-announcement.tsx
resources/assets/lib/models/chat/create-announcement.ts
resources/lang/en/chat.php
tests/Controllers/Chat/ChannelsControllerTest.php
tests/Libraries/ChatTest.php

Fix announcement typo

---

resources/assets/lib/chat/conversation-list.tsx

closes #8980
I knew there was another reason I originally put at the end of the entire channel list 👀

Render create announcement button even list is empty

---

app/Http/Controllers/UsersController.php

This actually only result in one more query because it removes two queries after adding three 🤔 
Related to ppy/osu#18517

Include per ruleset statistics for own profile endpoint

---

app/Http/Controllers/Admin/BeatmapsetsController.php
app/Http/Controllers/BeatmapDiscussionPostsController.php
app/Http/Controllers/BeatmapDiscussionsController.php
app/Http/Controllers/BeatmapsetWatchesController.php
app/Http/Controllers/BeatmapsetsController.php
app/Models/Beatmapset.php
app/Transformers/BeatmapsetTransformer.php
database/factories/BeatmapsetFactory.php
resources/assets/lib/beatmapsets-show/header-links.ts
resources/assets/lib/interfaces/beatmapset-extended-json.ts
resources/lang/en/admin.php
resources/views/admin/beatmapsets/show.blade.php
resources/views/docs/_structures/beatmapset.md
resources/views/docs/info.blade.php
tests/Controllers/BeatmapDiscussionPostsControllerTest.php

Remove beatmap state check for beatmap discussion page

---

resources/assets/lib/beatmaps/search-panel.tsx

There's no input type `textbox` 🤨

Fix input type

---

resources/assets/lib/beatmap-discussions/editor.tsx
resources/assets/lib/beatmap-discussions/new-discussion.coffee
resources/assets/lib/beatmap-discussions/new-reply.coffee

instead of trying to throttle...or have unused throttle ಠ_ಠ

Limit to single pending request when posting discussion

---

resources/assets/lib/components/comment-editor.coffee

Don't abort and resend request when posting comment

---

app/Libraries/Mods.php

Ignore new mods when converting to bitset

---

app/Models/Multiplayer/PlaylistItem.php
tests/Controllers/Multiplayer/RoomsControllerTest.php

As it turned out these parts weren't tested.

Fix incorrect attribute name

---

app/helpers.php
tests/Libraries/ModsTest.php

Support casting boolean mods settings

---

.env.example
config/sentry.php

In order to get https://dev.ppy.sh reporting to Sentry as well :)

✨ Add customizable Sentry environment setting

---

database/factories/BeatmapPackFactory.php
tests/Browser/SanityTest.php
tests/Models/BeatmapPackTest.php

Found this when checking if the test for pack completion check is missing (it's already there).

Use class factory for BeatmapPack

---

.github/workflows/tests.yml
database/migrations/2019_08_21_104727_add_index_to_beatmapset_events.php
database/migrations/2020_05_15_083037_sync_structure.php
database/migrations/2020_07_22_045416_add_timestamp_index_to_user_account_history.php
database/migrations/2020_10_13_064901_add_provider_reference_to_orders.php
database/migrations/2021_08_30_153214_add_track_id_to_beatmapsets.php

Fix migration rollbacks

---

database/mods.json

Update mods data

---

database/mods.json

https://github.com/ppy/osu/pull/19089

Add single tap mod definition

---

app/Console/Commands/OAuthDeleteExpiredTokens.php

Fix oauth client grant token clean up message

---

resources/assets/less/bem/beatmap-scoreboard-table.less

Fix scoreboard hover performance on Safari

---

app/Libraries/Search/ScoreSearchParams.php

Fix user score rank sort option

---

app/Libraries/Score/BeatmapScores.php

Fix incorrect limit parameter for user best score search

---

resources/assets/lib/beatmap-discussions/nominator.tsx

Skip deleted beatmaps for ownership check on nomination

---

app/Libraries/Score/BeatmapScores.php

That'd be weird returning random score for best score request.

Fix own best solo score lookup

---

resources/assets/less/bem/mobile-menu.less
resources/assets/less/bem/navbar-mobile.less
resources/assets/less/layout.less
resources/assets/less/variables.less
resources/assets/lib/core-legacy/nav2.coffee

Doing what the comment has been saying...

Adjust z-index of navigation menu

---

app/Libraries/BBCodeForDB.php
tests/Libraries/bbcode_examples/basic_email.base.txt
tests/Libraries/bbcode_examples/basic_email.db.txt
tests/Libraries/bbcode_examples/basic_email.html
tests/Libraries/bbcode_examples/basic_email_parameter.base.txt
tests/Libraries/bbcode_examples/basic_email_parameter.db.txt
tests/Libraries/bbcode_examples/basic_email_parameter.html

Missed this when updating the url etc tag parser.
Reported in ppy/osu-wiki#7721

Fix bbcode email parsing

---

app/Console/Commands/EsIndexScoresSetSchema.php

The function in the ScoreSearch was actually a leftover (and nothing is using it) but as I'm adding more things to it, it's probably fine being there 👀

Use existing score search set schema function for artisan command

---

app/Console/Commands/EsIndexScoresQueue.php
app/Libraries/Search/ScoreSearch.php

<del>I'll eventually move the score test to use that and add separate test for the commands...</del>
Wait that should be comment for the next pr, not this one.

Allow using score schema set in redis

---

app/Models/Solo/Score.php
database/migrations/2022_08_05_103407_remove_deleted_at_from_solo_scores.php

Nothing is using it and there's `preseve` flag already for indexing...

Remove unused soft delete for scores

---

app/Libraries/Search/ScoreSearch.php
app/Models/Solo/Score.php
tests/Controllers/BeatmapsControllerSoloScoresTest.php

The check is rather fragile (it doesn't check if the index content is actually correct) but I think it's good enough for testing purpose. Better than waiting 3s especially as more tests are added.

Reduce wait time for score indexing in test

---

app/Models/Solo/Score.php

Forgot about this when doing the merge.

Remove resolved todo comment

---

app/Models/Solo/Score.php

Also updated position of data attribute as the processor depends on it being the last one.

Add missing ruleset attribute for processing queue

---

app/Models/Solo/Score.php
app/Models/UserReport.php
database/migrations/2022_08_08_083336_add_solo_score_to_report_types.php
resources/assets/lib/components/play-detail-menu.tsx
resources/assets/lib/scores-show/buttons.tsx
resources/assets/lib/utils/score-helper.ts

 Support reporting solo scores 

---

resources/assets/less/bem/circular-progress.less

Completely hide progress label for beatmap player

---

app/Libraries/Markdown/OsuMarkdown.php

Hope there isn't a stray `:: ::` in news posts 👀 
closes #9185 
closes #9118

Enable custom containers for news post markdown

---

app/Libraries/Markdown/Chat/Extension.php
tests/Libraries/Markdown/chat_markdown_examples/link.html
tests/Libraries/Markdown/chat_markdown_examples/link.md

Enable markdown links for announcement messages

---

resources/assets/lib/beatmapsets-show/scoreboard/controller.ts

Fix beatmap scoreboard loading state

---

app/Console/Commands/EsIndexScoresQueue.php

Inline score id count and assignment on score queue command

---

tests/RouteTest.php

Fix test route url

---

resources/assets/lib/beatmap-discussions/new-discussion.tsx
resources/assets/lib/beatmap-discussions/nominations.coffee

It doesn't work right on anything but General (All) page. It was originally slightly better - as in it additionally worked in General (diff) and Timeline - but the recent refactor broke it over there as well.

Fix behaviour of "Hype Beatmap!" button

---

resources/assets/less/bem/beatmap-discussion-new.less
resources/assets/lib/beatmap-discussions/new-discussion.tsx

closes #9228
React and flexbox fun 🤨

Better new beatmap discussions footer alignment

---

resources/lang/en/notifications.php

Add missing translation key for beatmapset revival

---

app/Models/BeatmapFailtimes.php

Skip using laravel model casting in the data attribute generation loop and update primary keys settings.

Clean up BeatmapFailtimes model

---

app/Http/Controllers/LegacyInterOpController.php

Reindex solo scores as part of user reindex

---

app/Models/Contest.php
tests/Models/ContestTest.php

Don't error on guest user

---

app/Http/Controllers/ContestsController.php

It'll probably be useful being able to see the result regardless the play state 🙃

Only restrict entry display during voting period

---

resources/assets/lib/beatmapsets-show/main.tsx
resources/assets/lib/profile-page/beatmap-playcount.tsx
resources/assets/lib/profile-page/play-detail.tsx
resources/assets/lib/utils/beatmapset-page-hash.ts
resources/assets/lib/utils/url.ts

Use non-redirect beatmap url

---

database/migrations/2022_09_09_080211_create_osu_beatmap_performance_blacklist.php

There's no issue for this one but I need it :thinking:

Add migration for `osu_beatmap_performance_blacklist`

---

database/mods.json

In line with https://github.com/ppy/osu/pull/20370.

Add angle sharpness setting to random mod

---

.github/workflows/pack.yml

Draft until https://github.com/ppy/osu-kubernetes-config/pull/60 is merged (private).

👷 Trigger staging deployment with values

---

.github/workflows/pack.yml

~~Draft for now, depending on https://github.com/ppy/osu-kubernetes-config/pull/57~~
Ready to merge

👷 Add job for osu-web octane deployment in production on k8s

---

resources/assets/lib/cli/mod-names-generator.js
resources/assets/lib/utils/score-helper.ts

Forgot about this extra case 👀 
closes #9307

Missing No Mod tooltip

---

resources/assets/lib/scores/pp-value.tsx
resources/lang/en/scores.php

Fix label when pp is missing for solo score. Resolves #9219.

Support solo score pp value labels

---

app/Models/Model.php

Other models are still using the slower `getAttribute` function 👀

Put back custom getKey function

---

app/Libraries/BeatmapsetDiscussionPostsBundle.php

Wow it already found a bug of accessing invalid attribute <_<

Use correct key for beatmaps in discussion post API

---

app/Models/Beatmapset.php

Add missing laravel attribute magic

---

resources/assets/lib/store-xsolla.coffee

Token got changed (and should fail elsewhere if the token is wrong anyway)

Skip xsolla token length check

---

app/Models/User.php

Fix blank user twitter attribute

---

tests/Models/UserTest.php

Add test for user model's twitter field

---

.eslintrc.js
resources/assets/lib/beatmap-discussions/editor-insertion-menu.tsx
resources/assets/lib/beatmap-discussions/editor-toolbar.tsx
resources/assets/lib/beatmap-discussions/nominator.tsx
resources/assets/lib/beatmap-discussions/review-post.tsx
resources/assets/lib/beatmaps/search-panel.tsx
resources/assets/lib/beatmapsets-show/header.tsx
resources/assets/lib/chat/message-item.tsx
resources/assets/lib/components/click-to-copy.tsx
resources/assets/lib/components/landing-news.tsx
resources/assets/lib/components/wiki-search.tsx
resources/assets/lib/profile-page/cover.tsx
resources/assets/lib/profile-page/detail-bar.tsx
resources/assets/lib/profile-page/play-detail.tsx

Add jsx tag spacing lint

---

app/Models/Beatmapset.php
app/Models/Score/Best/Model.php
tests/Models/UserReportTest.php

I guess it's not actually used anywhere. It's still kind of expected to work anyway though so I added test while at it.

Add missing relation accessor

---

app/Http/Controllers/Chat/Channels/MessagesController.php

Channel is used by transformer's isAnnouncement check 💃

Add missing preload for chat messages and use correct transformer

---

.github/workflows/lint.yml
.github/workflows/tests.yml

All the running servers have been updated a while ago.

Update nodejs for GitHub Action

---

app/Models/BeatmapDiscussionPost.php

It was weird after a closer look 👀

Fix incorrect state revert on already saved model

---

app/Http/Kernel.php

A subtle bug as any requests to html page will fix the problem for the rest of the worker's lifetime.

Add missing proxy trust middleware

---

app/Models/User.php

Fix typing of `User::defaultGroup()`

---

app/Models/Beatmapset.php

not used so I guess that's why nobody noticed before.

Fix Beatmapset approver relation

---

app/Models/UserGroup.php
tests/Models/ModelCompositePrimaryKeysTest.php

Another relatively simple one and doesn't actually change much if at all.

Define attributes for user group model

---

.github/workflows/lint.yml

Otherwise it'll just keep increasing.

Enforce maximum js lint warnings

---

app/Models/Solo/Score.php

...that was weird. Hopefully it doesn't break any tests 👀

Fix score query scope

---

app/Models/User.php

Increase username reuse limit

---

app/Http/Controllers/Chat/ChatController.php
resources/views/docs/_structures/chat_message.md

Accept uuid parameter for new PM

---

app/Http/Middleware/AuthApi.php

To match the one in osu-notification-server.

Add note about user verification on token auth

---

docker/deployment/entrypoint.sh

Will be used to increase workers count.

✨ Support passing additional arguments to octane

---

resources/assets/coffee/osu_common.coffee
resources/assets/lib/beatmap-discussions/review-post.tsx
resources/assets/lib/globals.d.ts
resources/assets/lib/models/chat/create-announcement.ts
resources/assets/lib/models/chat/message.ts
resources/assets/lib/utils/seq.ts

Cleaning out more stuff from `osu_common.coffee`
Not may things use this anymore so I just put it in `seq.ts`

Convert osu.uuid to typescript

---

app/Http/Controllers/BeatmapsController.php

Fix docs for /beatmaps API

---

resources/assets/lib/notification-maps/icons.ts

Match beatmapset revive notification icon to profile page event

---

resources/assets/coffee/osu_common.coffee
resources/assets/lib/components/header-v4.tsx
resources/assets/lib/components/track-preview.tsx
resources/assets/lib/components/tracklist-track.tsx
resources/assets/lib/components/user-avatar.tsx
resources/assets/lib/contest-voting/art-entry.coffee
resources/assets/lib/core-legacy/current-user-observer.coffee
resources/assets/lib/core-legacy/forum-cover.coffee
resources/assets/lib/follows-mapping/main.tsx
resources/assets/lib/globals.d.ts
resources/assets/lib/news-show/main.tsx
resources/assets/lib/notification-widget/item.tsx
resources/assets/lib/profile-page/badges.tsx
resources/assets/lib/profile-page/cover-selection.tsx
resources/assets/lib/profile-page/cover.tsx
resources/assets/lib/quick-search/user.tsx
resources/assets/lib/utils/css.ts
resources/assets/lib/utils/html.ts
tests/karma/utils/css.spec.ts

Convert urlPresence to typescript
