app/Models/Multiplayer/Score.php
The user's mods list contains both the required mods and the allowed mods they selected.
```
allowed_mods = HR
required_mods = DT
mods = [DT, HR]
```
Please advise if there are tests to be updated here or if this is improper code style w.r.t. performance and all that :).
=> Fix multiplayer allowed mods check failing

app/Libraries/Transformers/Scope.php, resources/assets/coffee/react/modding-profile/header.coffee, resources/assets/coffee/react/profile-page/header.coffee, resources/docs/source/includes/_structures/user.md
Returns `null` instead of `[]` if the transformer and its includes are empty. This is an issue with the `UserStatisticsRulesetsTransformer` if there are no statistics since empty arrays get serialized as `[]`
Serializing empty `stdClass` results in proper empty object `{}`, however, the transformer library used can't handle anything but array which would require a lot more stuff to be reimplemented.
I don't think there's any case where the main transformer returns a non-associative array with values, so an option shouldn't be necessary.
=> Support null output for empty transforms

app/Http/Controllers/Multiplayer/Rooms/Playlist/ScoresController.php, app/Models/Multiplayer/PlaylistItem.php, app/Models/Multiplayer/Room.php, app/Transformers/Multiplayer/PlaylistItemTransformer.php, database/migrations/2021_02_17_073637_add-expired-column-to-playlist-items.php
I was debating whether to name this `played` or `expired`, but picked `expired` in the end as it could be used for more than multiplayer. For example if a host is ever to be able to "delete" playlist items then we could also set `expired = 1` in that case and preserve scores/etc. Whether such functionality should exist or not is a different question altogether, but I hope the example demonstrates why I didn't want to tie this property down to _just_ the playlist item having been "played" in multiplayer.
=> Add `expired` property to multiplayer playlist items

resources/assets/lib/chat.ts, resources/assets/lib/chat/chat-state-store.ts
Better handling of selected chat channel when navigating back to chat.
It now selects the channel you were previously on; this also means `sendto` in the url is ignored when loading from history if another channel was selected before navigating away; `sendto` in the url should be removed when changing channels in a future update since it doesn't reflect the actual state of the UI.
fixes #7249
=> Improved remembering of selected chat channel

app/Libraries/Multiplayer/Mod.php
Just noticed this while going through mod incompatibilities - spunout is incompatible _only_ with autopilot, and not with nofail and all others.
=> Fix spunout being incompatible with too many mods

app/Http/Controllers/FriendsController.php, app/Http/Controllers/GroupsController.php, app/Http/Controllers/UsersController.php, app/Libraries/ModdingHistoryEventsBundle.php, app/Models/UserStatistics/Model.php, app/Transformers/UserCompactTransformer.php, app/Transformers/UserStatisticsTransformer.php, resources/assets/coffee/react/profile-page/rank-chart.coffee, resources/assets/coffee/react/profile-page/rank.coffee, resources/assets/lib/interfaces/user-json.ts, resources/assets/lib/interfaces/user-statistics-json.ts, resources/assets/lib/user-list.tsx, resources/docs/source/includes/_structures/rankings.md, resources/docs/source/includes/_structures/user.md, resources/docs/source/includes/_structures/user_compact.md, resources/docs/source/includes/_structures/user_statistics.md, resources/views/vendor/apidoc/partials/info.blade.php
Resolves #7240. `rank.country` will be removed later once everything is moved to use `country_rank`.
I'm not sure the current usage state in osu though :thinking: This assumes they moved to use `global_rank` already.
=> Remove redundant rank data

app/Libraries/Multiplayer/Mod.php
Creating multiplayer room with CL (classic_note_lock=false etc) required_mods will throw "unknown setting for CL (no_slider_head_accuracy)"
This pr adds classic mod's options at multiplayer/mod.php
https://github.com/ppy/osu-web/pull/7195 (Classic PR)
=> Fix osu classic mod settings from multiplayer mod

app/Http/Middleware/VerifyCsrfToken.php
I hope I didn't miss anything :thinking: 
The exception check logic is a bit worrying (repeated url parsing for each entry, twice) but it's probably fine...
=> Fix token check on callbacks and user registration

.github/workflows/tests.yml
Seems like redis extension needs to be explicitly specified for the Ubuntu 20 runner
=> Update Github Actions Tests action

app/Libraries/Payments/PaymentProcessor.php
Some visibility into the incoming payment gateway callbacks that's not just a controller status code.
=> Add Datadog metrics for IPN callbacks

app/Libraries/Transformers/Scope.php, app/helpers.php
If an item in a transformer collection `null`, it wasn't supposed to be there in the first place.
This works around fractal's limitation and doesn't include the `null` by duplicating `executeResourceTransformers` and adding an extra check.
(hopefully we don't have anything that actually relies on the `null` being there to work) 🤔
=> Exclude nulls from transformer collections

app/Jobs/BeatmapsetDelete.php
Seems like something that shouldn't be in comments after a beatmapset gets deleted (and `whereHas()` on `commentable` is probably not something we want to do on listing 🤔 )
closes #7264
=> Delete comments when deleting Beatmapset

resources/assets/less/bem/gallery-previews.less
A side-effect of `background-size: cover` is it will zoom in to "fit" the image into the container; in the case of wider containers, this causes the bottom of the image to be truncated.
Note that at certain viewport widths, it's fine:
after (`background-size: contain`):
It's not really an issue on other preview images in the store that view fine when zoomed in, but it's really noticeable if there's anything in the edges that should be visible.
=> Workaround tournament support banner previews being cutoff in store

config/schemas/beatmaps.json
This will allow searching for beatmaps with specific combination of attributes.
For example, searching for beatmap with difficulty rating of 3 and drain rate of 8 using the old structure may return beatmapset which contain two different beatmaps, one with diff 3 (but maybe drain 7) and another one with drain 8 (but maybe diff 4).
This is required to match lazer behavior for advanced query search.
Removed the old attributes except playmodes because it's the field still in use by legacy web although I think it could be easily updated to use the nested one?
=> Move beatmap attributes to per-beatmap document

app/Jobs/Notifications/BroadcastNotificationBase.php
Mainly for "global" type notifications. Avoid doing large `whereIn` query.
Resolves #7325.
=> Fix notification not sent in some cases

config/schemas/beatmaps.json
This should be the more appropriate prefix tokenizer when `es_query_and_words` is removed with #7293
together with changes from #7293 should close #6446.
reindex is required: `php artisan es:index-documents --types=beatmapsets --yes --cleanup`
=> Update Beatmapset title search tokenizer

database/migrations/2021_03_19_065458_add_external_contest_type.php, resources/assets/coffee/react/contest-voting.coffee, resources/assets/coffee/react/contest-voting/entry.coffee
This new contest type allows for entries to link to... things.
(this is for an upcoming skinning contest, where we want to be able to link to forum threads... figured I'd make it generic enough for future uses instead of specifically linking to forum threads by id or whatever)
=> Add 'external' contest type

app/Console/Commands/MigrateFreshAllCommand.php
I ended up with loads of old wiki index after a while. The other index already cleans up itself.
I wonder if it's because the new index is empty but anyone who cares about the content can reindex the thing afterwards or should just not run "fresh all" command.
=> Remove old wiki index on database reset

resources/assets/coffee/react/profile-page/beatmap-playcount.coffee
Left over from when `dangerouslySetInnerHTML` was used, shouldn't be needed anymore.
closes #7384
=> Fix double escaped artist names on user profile beatmap play counts

resources/assets/coffee/react/beatmap-discussions/post.coffee
Deleted discussion (thread starter) was missing deletion date display because it was using wrong model for the date.
=> Fix display of beatmap discussion delete date

resources/assets/coffee/react/beatmap-discussions/discussion.coffee, resources/assets/coffee/react/beatmap-discussions/post.coffee, resources/assets/coffee/react/modding-profile/posts.coffee
Deleted user object no longer has null id.
Resolves #7345.
=> Fix display of discussion post editor name

resources/assets/coffee/react/_components/comment.coffee, resources/assets/coffee/react/_components/comments.coffee, resources/assets/lib/deleted-comments-count.tsx
Resolves #7254.
The comment hiding option stays as it's still useful for showing replies of deleted comment.
=> Always show deleted comment count

resources/assets/lib/beatmaps/main.tsx, resources/assets/lib/chat/conversation-view.tsx, resources/assets/lib/chat/input-box.tsx
TIL `disposeOnUnmount` is a thing in mobx.
Only works on react components, though...
=> Cleanup observers when unmounting components

app/Libraries/BeatmapsetDiscussionsBundle.php
`BeatmapDiscussionShow` permission calls `BeatmapShow` which needs beatmap.
Model cache sure would be useful here since a superset of the beatmaps is going to be loaded elsewhere...
=> Eager load beatmap for beatmapset discussion listing

resources/assets/coffee/react/profile-page/detail-bar.coffee, resources/assets/less/bem/profile-page-toggle.less
The padding change accidentally also resized button in other place. Resized back to the closest correct size. Also fixed undefined variable.
=> Fix detail menu button size in profile page

resources/assets/less/bem/circular-progress.less, resources/assets/lib/circular-progress.tsx
Another part of new beatmap card.
The over50 data must still be added manually by whatever process updating the css which is kinda annoying but I couldn't figure out better way.
Usage example for audio player in beatmap card:
```less
&--beatmapset-panel {
font-size: 50px; // circle size
pointer-events: none;
background-color: transparent;
--circle-center-fill: transparent;
--label-colour: transparent;
--circle-transform: rotate(calc(var(--progress) * 1turn));
[data-audio-over50="1"] & {
.over50();
}
}
```
=> Allow css to control circular progress component

app/Http/Controllers/FallbackController.php
=> Return empty response for json route not found

resources/assets/coffee/react/beatmaps/search-content.coffee, resources/assets/coffee/react/beatmaps/search-sort.coffee, resources/assets/lib/beatmapset-search-filters.ts
Moves the calculation of `sorting` and makes it observable. This is part of a larger state store cleanup that also moves all the store references to use the current instance instead of the static one on module import.
=> Update SearchSort component to observe changes

resources/assets/coffee/osu_common.coffee, resources/assets/lib/beatmapset-panel.tsx, resources/assets/lib/import-shims.coffee, resources/assets/lib/utils/html.ts
Explicitly use `@2x` size because otherwise it'll be blurry mess (still blurry mess on 150dpi+ displays).
The version itself is used in a few places like discussion watchlist and discussion listing although maybe it's a good idea to unify them anyway? The styling will need some adjustments.
Also this doubles number of image requests ( ﾟ ヮﾟ)
=> Use "list" image for beatmap card left side thumbnail

resources/assets/less/bem/nsfw-badge.less
The label shouldn't be that long...
Resolves #7491
=> Prevent text wrapping of explicit badge

app/Http/Controllers/Forum/TopicsController.php, tests/Controllers/ForumTopicsControllerTest.php
Accessing topic with no posts currently causes a redirect loop.
I'm not sure what the correct response should be in such case...
Resolves #7464 (osu-web side, beatmapset getting in weird state is fixed separately)
=> Prevent redirect loop on invalid topic

app/Libraries/Search/BeatmapsetQueryParser.php, app/Libraries/Search/BeatmapsetSearch.php
Include loved and approved maps for search by ranked date, limit keys search to mania, and add "key" alias for keys search to match lazer.
Resolves #7483, resolves #7498.
=> Beatmap search adjustments

app/Models/Contest.php, app/Models/ContestEntry.php, app/Transformers/ContestEntryTransformer.php, app/Transformers/ContestTransformer.php, database/migrations/2021_04_16_083901_rename_contest_shape_extra_option.php, resources/assets/coffee/react/contest-voting/art-entry.coffee, resources/views/admin/contests/show.blade.php, resources/views/contests/_voting-entrylist.blade.php
Renames `shape` to `thumbnail_shape` (within `extra_options`) and standardizes the derived attributes.
Also stops including the unused `artMeta` for non-art contests, plus general cleanups.
cc @Ephemeralis - be aware that once this is merged, you should start using `thumbnail_shape` instead of `shape` when making contests
=> Contest extra_options and artMeta cleanup

package.json, yarn.lock
- update libraries in vulnerability list (except immer/slate)
- update latest karma (related to item above)
- remove webpack-dev-server (not used)
=> Update javascript dependencies

.eslintrc.js
Annoyingly there's no fixer for this on eslint.
Even more annoying it is case sensitive while tslint one isn't.
=> Add class member sort lint for eslint

app/Models/Contest.php, app/Transformers/ContestTransformer.php, resources/assets/coffee/react/contest-voting/art-entry.coffee, resources/assets/less/bem/contest-art-entry.less
Enabled by setting `"show_names": true` under `extra_options`
=> Add option to show entry names for external/art contests.

app/Transformers/ContestEntryTransformer.php
Just set the dimensions to 0 instead of dying; it doesn't fix the issue to stale data being in the cache in the event the image gets fixed but the url doesn't have its cache busting updated.
=> Workaround getting size of contest entry missing image

app/Libraries/Multiplayer/Mod.php
Reference: https://github.com/ppy/osu/pull/12834
Should also probably hoist up other exclusivities present in `EXCLUSIVITY_COMMON` into here at some point...? Quite a few are ruleset-specific.
=> Add taiko swap mod

app/Libraries/ModsHelper.php, resources/assets/less/bem/mod.less, resources/lang/en/beatmaps.php
Matches current lazer naming and allows more correct mods conversion from lazer score.
=> Update short name for Relax mod

resources/lang/en/admin.php, resources/lang/en/beatmaps.php, resources/lang/en/beatmapsets.php, resources/lang/en/model_validation.php
Removes the `beatmapset` terminology from the site based on [https://github.com/ppy/osu-wiki/issues/4723](https://github.com/ppy/osu-wiki/issues/4723)
=> Remove `beatmapset` terminology from the site localisation

resources/assets/lib/profile-page/links.tsx
Forgot to add `relative` in #7505 as the previously used `osu.timeago` sets `js-timeago`
fixes #7658
=> Show user last visit as relative time

resources/assets/less/bem/beatmap-playcount.less, resources/assets/less/bem/beatmapset-search-card.less, resources/assets/less/bem/beatmapset-watches.less
- Quick search
- Beatmap discussion watchlist
- Profile page's most played (kinda follows size in new design)
For some reason the mapper watchlist uses card (400&times;140 (new) full, 80&times;40 scaled on page) which is actually closer compared to previous full size of 400&times;100
=> Update beatmap cover size

resources/assets/coffee/react/changelog-build/main.coffee
Recent transformer update of nullifying empty array sometimes causes error in testing.
=> Prevent error in dev/testing when there's only single build

app/Http/Controllers/GroupsController.php
PHP somehow allows string parameter passed to a function which requires int... :raised_eyebrow: 
```
>>> $a = fn (int $val) => $val;
=> Closure(int $val) {#4857 …2}
>>> $a(1)
=> 1
>>> $a('1')
=> 1
>>> $a('1 ')
=> 1
>>> $a('1 wat')
TypeError: {closure}(): Argument #1 ($val) must be of type int, string given on line 1
>>>
```
=> Make sure to pass int group id

app/Jobs/UserNotificationDigest.php
`sendNow` and `send` are the same since 6.10 and the former is removed in 8.x.
Sure would be nice if they actually put up a notice instead of just silently deprecating it in a PR (laravel/framework#30999) and then suddenly removing it in 8.x :neutral_face:
=> Update usage of deprecated `sendNow` method

app/Jobs/NotifyForumUpdateMail.php, app/Jobs/UpdateUserForumTopicFollows.php, app/Libraries/OsuAuthorize.php, tests/Controllers/BeatmapDiscussionPostsControllerTest.php, tests/Controllers/Chat/ChatControllerTest.php, tests/Controllers/ForumTopicsControllerTest.php, tests/Jobs/UpdateUserForumTopicFollowsTest.php
Automatically reset on new requests (both for octane and test).
Jobs auth is manually reset every time as needed. Probably also fixes bug as job runner is a long running process.
Using Map so it's passed around by reference instead of value when using array.
Also changed admin check to use Set instead of array lookup.
=> Store auth data in request object

app/Libraries/User/FindForProfilePage.php
Not sure if should put back the check for modding profile because it's kind of visible already from the overall listing page.
=> Allow profile page for bot

.github/workflows/tests.yml
Live servers have been updated so no need to test on earlier version anymore. Keeping it as matrix because that seems convenient for future use.
=> Remove test on PHP 7.4

.gitattributes
Seems like a good thing to add to reduce noise on some `git grep`
=> Mark fonts and images as binary file in git

resources/assets/coffee/react/_components/comment.coffee
I think it's only a problem for old disqus comments with no user attached. random example https://osu.ppy.sh/comments/174156
=> Fix check to display comment owner badge

app/Http/Controllers/UsersController.php, app/Libraries/BBCodeFromDB.php, app/Transformers/UserCompactTransformer.php
Hopefully this doesn't break anything :eyes: 
An alternative is to match `withoutImageDimensions` option between preview and real.
Or just remove `withoutImageDimensions` option considering it's calculated during preview and everything goes through the proxy anyway...? &larr; now this (previously was matching `.bbcode img` and `.proportional-container` vertical-align css)
Resolves #7771.
=> Match user page with its preview

resources/assets/lib/beatmap-discussions/editor-discussion-component.tsx, resources/assets/lib/enchant.ts
Not sure when they slipped in (or when they're added by eslint) but they are fixed using `yarn eslint --fix`
=> Automated lint fix from eslint

app/Http/Controllers/ContestEntriesController.php, app/Models/UserContestEntry.php
`getClientSize()` was removed in an earlier version of Symfony; should be calling `getSize()` instead which is what `getClientSize()` was calling anyway
=> Fix contest upload

app/Libraries/Multiplayer/Mod.php
See: https://github.com/ppy/osu/pull/13629
Mod settings should really be validated per-ruleset. At the same time we'll need to figure out a path forward for acronym conflicts in the first place (which, I guess this could be treated as).
But the taiko setting is already in there so...
=> Add osu!catch "hard rock offsets" to DA mod

config/scribe.php, resources/views/vendor/scribe/index.blade.php
This kinda requires the svg to stay in the same url forever (or updated together). It'll be rather problematic if we ever move to fully hashed assets although it could also be fixed by uploading a copy to somewhere more static like assets.ppy.sh.
=> Add osu! logo to docs

app/Http/Controllers/BeatmapsController.php
Mainly coming from user events (`App\Models\Event`).
Resolves #7739.
=> Accept legacy "m" parameter for beatmap redirect mode

app/Models/LivestreamCollection.php
5 minutes outdated list is better than nothing.
=> Prevent showing empty livestream listing on error

app/Models/LegacyMatch/Score.php, app/Models/Score/Best/Model.php, app/Models/Score/Model.php, app/Transformers/ScoreTransformer.php, resources/assets/lib/interfaces/score-json.ts, resources/views/docs/_structures/score.md
Lazer currently sends actual ongoing rank for non-passing scores instead of "F" so they're all shown in profile page.
Resolves #7847.
=> Filter out fail scores by the pass flag instead of rank

resources/assets/coffee/_classes/sticky-header.coffee
Mainly for beatmapset search page where it's used for the floating search box.
Resolves #7867.
=> Fix sticky header component not available when mounting react

.eslintrc.js
Not really useful and just adding noise to fix the existing ones.
Typescript also already has `private` visibility for classes.
=> Remove underscore identifier lint

app/Http/Controllers/UsersController.php
Resolves #7673.
I also noticed fetching beyond 100 isn't actually allowed in the first place.
=> Increase user stats per-page limit to 100

config/osu.php
Initially disabled because it was still experimental. Seems fine so far so enable it by default.
=> Allow user registration by default

resources/assets/lib/scores-show/buttons.tsx
Resolves #7884.
The flow isn't quite right when downloading from logged out state for privileged user (it reloads the page after logging in to show the verification window). There isn't an easy fix for that apart of disabling verification for the download endpoint.
=> Fix download score replay button

app/Casts/PresentString.php, app/Models/Multiplayer/Room.php
External components may set the value to an empty string.
Resolves #7890.
=> Null blank room password

app/Libraries/Multiplayer/Mod.php
Closes https://github.com/ppy/osu/issues/13938.
[Reference for settings & incompatibility rules.](https://github.com/ppy/osu/blob/master/osu.Game.Rulesets.Osu/Mods/OsuModTarget.cs) (`OsuModApproachDifferent` and `OsuModTraceable` are the only two implementations of `IRequiresApproachCircles` game-side.)
=> Add settings and incompatibility rules for osu! target mod

resources/assets/lib/osu-url-helper.ts
Currently causing plain browser navigation instead of turbolinks. I wonder if checking for external links instead is better now :thinking:
=> Add group url as osu-web url

app/Models/Solo/Score.php, tests/Models/Solo/ScoreTest.php
We are also applying a fix at the lazer end but it's probably best to have this. Could be converted to a validation rule (throw on incorrect values) if/when we support "F" ranks in lazer, but that's still up for discussion.
Closes https://github.com/ppy/osu/issues/13897.
=> Fix (lazer) failed plays showing up in profile recent plays

app/Models/Solo/Score.php, tests/Models/Solo/ScoreTest.php
As it turns out, F causes errors with deserialisation at lazer's end.
This might not be the final case but just want to stop breakage for now.
=> Use rank D instead of F for failed plays

resources/assets/coffee/react/modding-profile/main.coffee, resources/assets/coffee/react/profile-page/main.coffee
Navigating to `/users/:user#:section` from another page doesn't correctly scroll on Firefox.
=> Fix profile page navigation scroll on Firefox

composer.json, composer.lock
Current version doesn't have correct support for octane and generates slightly useless report. The [updated version is still in review](https://github.com/getsentry/sentry-laravel/pull/495) but seems to work, so, yay? :shrug:
=> Update Sentry to support Octane

app/Libraries/Session/Store.php
Session handler instance is persistent so the duration needs to be set before saving.
=> Fix session duration for non-guest user on octane

resources/lang/en/layout.php, resources/lang/en/page_title.php
Simpler change compared to #7925 by just duplicating the translations. Changes for `page_title` on another locales have already applied :eyes:
=> Adjust page and menu titles

app/Libraries/Multiplayer/Mod.php
Reference: https://github.com/ppy/osu/pull/14016
The existing `MANIA_MIRROR` was genericised to avoid duplication (the client also did this). Also note that the incompatibility with `HARDROCK` is intentionally not applied to rulesets other than osu!, matching client implementation.
Putting the `reflection` setting as valid for all rulesets is a bit dicey - as it also only applies to osu! - but there's precedent for taking the shortcut of making it globally valid (namely, [`DIFFICULTY_ADJUST`](https://github.com/ppy/osu-web/pull/7779)).
=> Add osu! mirror mod

app/Libraries/Multiplayer/Mod.php
Reference: https://github.com/ppy/osu/pull/14041
Valid for all rulesets, no incompatibility rules (yet?). Metronome setting being persisted server-side makes _some_ sense as it makes things a bit easier.
<personal_opinion>Playtesting that this works with multi was quite dreadful gameplay-wise. Never touching this mod with a ten foot pole again...</personal_opinion>
=> Add muted mod

resources/assets/coffee/_classes/beatmap-discussion-helper.coffee, resources/assets/coffee/react/beatmap-discussions/discussion.coffee, resources/assets/coffee/react/beatmap-discussions/new-discussion.coffee, resources/assets/lib/beatmap-discussions/discussion-type.ts, resources/assets/lib/beatmap-discussions/editor-insertion-menu.tsx, resources/assets/lib/beatmap-discussions/editor-issue-type-selector.tsx, resources/assets/lib/beatmap-discussions/review-post-embed.tsx, resources/assets/lib/globals.d.ts
Noticed while reviewing stuff, also removed the roundabout camelCasing.
There's still the usage of `mapperNotes` in coffeescript for handling the grouping in some places, but I left that for now.
=> Add beatmap discussion message type typings

resources/assets/less/bem/flag-country.less, resources/assets/less/bem/ranking-page-table.less
Apparently the shadow causes lag for some people. It was done that way because some flags are shaped differently.
People affected should check if this test page is actually smoother: https://osunext.dev.myconan.net/rankings/osu/performance
=> Remove country flags drop shadow

app/Models/Beatmap.php, app/Models/Elasticsearch/BeatmapsetTrait.php
Resolves #7846.
A full reindex is needed for correct search result.
=> Fix typo and wrong index data for converted mania maps

app/Exceptions/Handler.php, app/Http/Controllers/ChangelogController.php, app/Http/Controllers/FollowsController.php, app/Http/Controllers/RankingController.php, app/Http/Controllers/Store/Controller.php, app/Models/Store/Order.php, resources/views/layout/error.blade.php, resources/views/store/header.blade.php
As it turned out it's not intended as per-request global variable store for view but just global per app and to be set during application start. And thus it's not reset by octane between requests.
Resolves #7952.
=> Remove invalid usage of shared view variables

app/Console/Commands/BeatmapsetNominationSyncCommand.php
Missing nomination modes from the migration in #7793
Also fixes nominations being marked as reset when they shouldn't be if the command is run multiple times.
Should be able to just truncate `beatmapset_nominations` and run `php artisan beatmapset:nomination-sync` again.
Tried to use `upsert` but it seems `upsert` doesn't like `mode` value being an array 🤔
=> Fix beatmapset nomination sync command

app/Console/Commands/BeatmapsetNominationSyncCommand.php
`User::beatmapsetNominationsToday()` was relying on `created_at` so the date should be preserved
Missing from #7983 found while checking #7861 again
=> Use original BeatmapsetEvent timestamp for BeatmapsetNomination migration

resources/assets/less/bem/chat-input.less
closes #7918
Manually apply `max-height` via css.
Likely due to #7798 causing the line height calculation to be `NaN` on first render when arriving via turbolinks navigation.
Can't just call `updateLineHeight` on `TextareaAutosize` after mounting as it's a `forwardRef`.
=> Fix chat input autosize height

.eslintrc.js, webpack.config.js, webpack.unmix.js
The default order is `ignore` :thinking: 
Side effect is it also sorts `require`.
=> Fix eslint import order settings

app/Http/Controllers/InterOp/BeatmapsetsController.php, routes/web.php, tests/BeatmapsetEventNominationResetTest.php
post to `/_lio/beatmapsets/${beatmapsetId}/disqualify` with `{ message: "post message" }` to disqualify or reset nomination.
Returns the discussion id in the response.
=> Add interop endpoint for disqualifying or reseting nominations

app/helpers.php
For legal index page, path being empty results in `/en/WIKI_PATH` get replaced with `/en/` instead of just `/en`.
Resolves #8016.
=> Strip trailing slash when generating wiki url

resources/views/wiki/_actions.blade.php
The button doesn't work on legal pages.
=> Fix wiki refresh button

app/helpers.php
Fixes redirect. This assumes there won't be page which contain '#' in its name.
Resolves #8030.
=> Don't escape '#' character for wiki url

app/Libraries/Markdown/StyleBlock/Element.php, app/Libraries/Markdown/StyleBlock/Parser.php, tests/Libraries/Markdown/html_markdown_examples/new_style_block.html, tests/Libraries/Markdown/html_markdown_examples/new_style_block.md, tests/Libraries/Markdown/html_markdown_examples/new_style_block_invalid_class.html, tests/Libraries/Markdown/html_markdown_examples/new_style_block_invalid_class.md, tests/Libraries/Markdown/html_markdown_examples/new_style_block_invalid_space.html, tests/Libraries/Markdown/html_markdown_examples/new_style_block_invalid_space.md, tests/Libraries/Markdown/html_markdown_examples/new_style_block_unclosed.html, tests/Libraries/Markdown/html_markdown_examples/new_style_block_unclosed.md, tests/Libraries/Markdown/html_markdown_examples/style_block_nested.html, tests/Libraries/Markdown/html_markdown_examples/style_block_nested.md, tests/Libraries/Markdown/indexable_markdown_examples/new_style_block.md, tests/Libraries/Markdown/indexable_markdown_examples/new_style_block.txt
As mentioned in https://github.com/ppy/osu-web/pull/8087#issuecomment-913779554, this PR add support for new `:::` syntax and old `{{{` as intermediate step until wiki migrate to new syntax (https://github.com/ppy/osu-wiki/pull/6067) and old syntax will be drop in https://github.com/ppy/osu-web/pull/8087.
Also drop support for nested `StyleBlock` for simplicity. Can be added back until there's such need from wiki-side.
=> Add support for new style block syntax

resources/assets/less/variables.less
#7909 increased the z-index to prevent beatmap-card borders to be above the extra tabs, however this lead to the cover selector being below them now.
Increased the editors index and left a note that it must be at least 1 higher than extra-tabs
=> Fix cover-editor being below page-extra-tabs

app/Models/User.php
Received a request to increase this via email, and it does seem like it could do with a bit of a bump. I've also added a hard minimum because it is feasible that a user with no friends still wants to block at least a few users.
Previously, non-supporter could block up to 25 users, supporter up to 50 (based on friend count div 10). Numbers are now double that, with a minimum of 5 entries.
=> Increase max blocked users to double the previous amount

app/Libraries/ApidocRouteHelper.php, resources/views/docs/info.blade.php, resources/views/vendor/scribe/index.blade.php, resources/views/vendor/scribe/partials/endpoint.blade.php
closes #8116
Badge colour `#ad2a66` is just a complement of `#87ad3a`
=> Label routes requiring a user in API docs

config/schemas/beatmaps.json, config/schemas/wiki_page.json
Wasn't needed since `standard` analyzer already applies a lowercase filter
=> Remove unused analyzer from schemas

app/Http/Controllers/Chat/ChatController.php
closes #8157
(not returning `204` if silences are not included as not requesting silences isn't part of the old behaviour)
=> Fix disappearing chat

app/Models/User.php, composer.json, composer.lock
Returning in `hint` field same message as the one on osu-web login box.
```json
{
"error": "invalid_grant",
"error_description": "The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.",
"hint": "your IP address is locked. Please wait a few minutes.",
"message": "The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client."
}
```
=> Add login error hint to OAuth authorisation failure

database/migrations/2021_10_05_064929_create_solo_scores_performance.php
:thinking: 
This matches existing table on live database and does nothing on osu-web.
=> Add score performance table

app/Http/Controllers/ScoresController.php, app/Libraries/ReplayFile.php, database/factories/BeatmapFactory.php, tests/Controllers/ScoresControllerTest.php, tests/Libraries/ReplayFileTest.php
`headerChunk` throwing error is too late to abort once streamDownload runs.
=> Handle replay download with missing beatmap or user

resources/assets/less/utilities.less, resources/assets/lib/artist-tracks-index/search-form.tsx
`display: none` is no-go but `opacity: 0; pointer-events: none` is a-ok it seems :ok_hand: 
Wanted to add `enterkeyhint` as well for fancy blue button but our current React version is too old and doesn't support it yet.
Resolves #8261.
=> Fix artist track search's enter to submit on Safari

database/factories/UserFactory.php
Sometimes the user generated by the factory fails to save but we can't see what the exact error is.
=> Throw validation error when failing to save factory user

resources/assets/app.ts, resources/assets/coffee/main.coffee, resources/assets/lib/app-deps.ts, resources/assets/lib/globals.d.ts, resources/assets/lib/lang-overrides.ts, tests/karma/osu_common.spec.ts
Make the patch a function instead of global and set locale on initialisation.
Currently with `Lang.setLocale` set quite late, `model/user`'s `deletedUser` (and potentially others?) isn't translated correctly on `pt-br` due to its locale being set as `pt-BR` (as per html lang tag) instead of `pt-br`.
This isn't related to the coffeescript module thingy change but has been a thing for quite a while (if not forever). I think.
Can be cleaned up further by moving translation related functions as its own utils but I'm not quite sure on the exact method yet.
=> Update Lang.js initialisation

resources/assets/lib/popup-menu.coffee
Always use existing popup menu wrapper to simplify handling menu ref.
Resolves #8312.
=> Fix custom popup menu causing error

resources/assets/lib/beatmap-discussions/icon-dropdown-menu.tsx
I didn't see the additional styling when removing the class :eyes: 
I think the menu can also use a custom anchor positioning option...
=> Fix styling for discussion review selector menu

app/Libraries/Multiplayer/Mod.php
Reference: https://github.com/ppy/osu/pull/15540
No new settings. Tested multiplayer & solo submission both with the new catch mod as well as the existing osu! mod, both work on my local setup (game + spectator server + web).
I believe that due to method of storage renaming the constant (while keeping its value the same) should be safe. Similar things have been done in the past, too (62929f1c).
=> Enable no scope mod for osu!catch

app/Models/BeatmapsetEvent.php
Was `type` a convenience param or something? 🤔 
`type` should be `string` or `null` instead of something weird like `array`
=> Cast BeatmapsetEvent search type param to string

app/Http/Controllers/ChatController.php, app/Models/Chat/Channel.php, resources/assets/lib/chat/channel-join-event.ts, resources/assets/lib/chat/chat-state-store.ts, resources/assets/lib/chat/chat-worker.ts
Opening chat with `?sendto=$userId` causes other tabs with chat open to have that channel's display reset.
Also fixes another issue with the user preloading order when rejoining channels (causes other chat tabs to die because details in the socket event are missing)
=> Fix displayed channel messages being reset when opening new PM

resources/assets/lib/beatmaps/beatmapset-card-size-selector.tsx, resources/assets/lib/chat-icon.tsx, resources/assets/lib/chat/main-view.tsx, resources/assets/lib/main-notification-icon.tsx, resources/assets/lib/notification-widget/main.tsx, resources/assets/lib/notifications-index/main.tsx, resources/assets/lib/oauth/client-details.tsx, resources/assets/lib/oauth/new-client.tsx, resources/assets/lib/oauth/own-clients.tsx, resources/assets/lib/user-multiplayer-index/room.tsx, resources/assets/lib/user-profile-container.tsx
As it turned out there are quite a lot of mobx-decorated classes missing `makeObservable` call in their constructor, rendering the decorations useless :eyes:
=> Add missing makeObservable calls

app/Http/Controllers/BeatmapsController.php, tests/Controllers/BeatmapsControllerTest.php
It should stop on not null, not the other way... :raised_eyebrow: 
Closes https://github.com/ppy/osu/issues/15912.
=> Fix looking up beatmap with multiple parameters

app/Http/Controllers/ChatController.php
Actually return a json `boolean` instead of `{}` in those cases where there was no previous channel.
...and fix a `git stash pop`ping fail 🤨
=> Fix new chat PM may not be correctly showing if you can't send a message

app/Models/Chat/Channel.php
channel `join` event should also be sent to the recipient of the PM if they left the channel.
=> Fix PM not being displayed after leaving a channel

app/Models/Score/Best/Model.php, app/Transformers/ScoreTransformer.php
Fix `weightedPp` value return and prevent returning invalid value when weight data is not loaded.
This was initially to make weight part of score includes for user profile but looking again it shouldn't be used as such and only explicitly include it for best scores.
...so it ended up being just an unrelated clean up.
=> Fix score weight transformer include

app/Models/Chat/UserChannel.php
extracted from #8418
While looking at making the chat event broadcast dispatch after the transactions are committed instead of during the transactions, came across this issue again where `last_read_id` is a query `Expression` instance when it gets read after it's updated
=> Don't return Builder from UserChannel::last_read_id

resources/assets/less/bem/line-chart.less, resources/assets/lib/charts/line-chart.ts
Trying to show tooltip on either edge of the chart is pretty difficult at the moment.
This should make it easier
=> Extend line chart hover area

resources/lang/en/beatmappacks.php, resources/views/packs/_header.blade.php
Prevents old one with removed `:scary` key from being used on other languages.
=> Move translation key of updated beatmap pack instruction

resources/assets/lib/profile-page/historical.tsx
Resolves #8450.
So the reason is difference on how moment and native Date parses timezone-less date:
```
>> moment('2021-01-01').toString()
"Fri Jan 01 2021 00:00:00 GMT-0800"
>> (new Date('2021-01-01')).toString()
"Thu Dec 31 2020 16:00:00 GMT-0800 (Pacific Standard Time)"
```
=> Always use UTC time for historical chart labels

app/Libraries/Markdown/OsuMarkdown.php
The new page from ppy/osu-wiki#6512 causes unexpected error as the page yaml header is parsed as string.
=> Fix error when parsing non-array markdown yaml header

build.sh, composer.json
Recent composer update switched installation method to disallow code execution by default.
Also added flag to disable prompt on build scripts.
=> Allow required plugin on composer install

app/Models/Forum/TopicPoll.php
Properly handle error instead of returning vague error message.
=> Check for poll title length

app/Http/Controllers/InterOp/ArtistTracksController.php, routes/web.php
This should be hit whenever artist related tables (`artists`, `artist_albums`, `artist_tracks`) are updated. This does full reindex but at current number of tracks it's simpler to do that instead of trying to figure out which tracks to update.
Inplace reindex doesn't delete deleted tracks so a new index will need to be created (by passing `inplace=false` parameter) although I don't think it's a common case at the moment? Old index (the one previously used) will be removed by default unless `cleanup=false` is specified.
=> Add endpoint to reindex artist tracks

database/migrations/2021_10_14_094706_add_build_id_to_solo_score_tokens.php
Can't find any docs for `null()` in https://laravel.com/docs/8.x/migrations.
The code is written with the intention of supporting nulls (notice the null propagating `?` operator): https://github.com/ppy/osu-web/blob/37551ebb2f38ec9ef95451f0bd11903666ed1e34/app/Http/Controllers/Solo/ScoreTokensController.php#L31-L36
Finally, this is the only usage of `null(true)` in migrations.
=> Fix incorrect nullable specification in migration

database/migrations/2022_01_17_104933_update_default_beatmaps_bpm.php
Recently added to live system...
...except it's currently missing `NOT NULL` constraint 🤔 
@peppy please confirm whether or not the constraint is needed.
Also the migration entry will be `2022_01_17_104933_update_default_beatmaps_bpm`.
=> Update default beatmaps bpm

Dockerfile.development
composer's already installed from its website later in file, and this was breaking `composer install` by making a php8.1 installation without the right extensions
=> Remove composer package from development Dockerfile

app/Libraries/Markdown/OsuMarkdown.php
closes #8570
Apparently we don't actually use this feature in wiki pages and a cursory glance through the wiki pages seems to confirm this. It ends up causing issues in the link markdown as `UrlAutolinkParser` starts replacing anything that it thinks is a link (even just ` www `) with a link node before the closing elements of the `[]()` markdown has been parsed.
`[label](link)` and `<link>` still work as usual.
It may be useful for comments so it's left enabled for them 🤷
=> Disable autolink extension in wiki

package.json, webpack.unmix.js, yarn.lock
Compilation seems to be a bit faster and `--watch` correctly watches updates to interface-only files.
=> Use dedicated plugin for TypeScript type check

app/Models/Solo/Score.php
Found this as I'm reading through the new infrastructure planning.
=> Fix 24h osu!catch scores from lazer missing count50 values

app/Models/UserProfileCustomization.php
The disappointment is immeasurable.
The alternative to this is filling up existing rows with empty array.
=> Fix saving user settings when the options column is null

resources/assets/less/bem/user-card-brick.less, resources/assets/less/bem/user-list.less, resources/assets/lib/friends-index/main.tsx, resources/assets/lib/groups-show/main.tsx, resources/views/friends/index.blade.php, resources/views/groups/show.blade.php
margin-bottom of `osu-page--users` removed in #8557 accidentally also affects user listing page (friends, groups) and removed the space between content and footer. Fixed this by using different modifier and adding specific background through user list container class. Also removed some wrapper classes while at it.
Also made the background `b4` for added bonus of making hover effect of sort buttons visible.
=> Clean up user list page styling

resources/assets/coffee/react/beatmap-discussions/events.coffee, resources/assets/coffee/react/modding-profile/events.coffee, resources/assets/lib/components/beatmapset-event.tsx, resources/assets/lib/components/beatmapset-events.tsx, resources/assets/lib/register-components.coffee
Not only conflicts with the one in coffeescript but the component isn't used by the beatmap-discussions itself.
=> Move beatmapset events listing to components directory

tests/Controllers/BeatmapDiscussionsControllerTest.php, tests/TestCase.php
continuing from #8591, more discussion-related test cleaning up, with more usage of data providers.
Also fix `TestCase::actAsUser` incorrectly preserving the previous verified status (we shouldn't be calling as multiple users in the same test case, anyway).
=> More discussion-related test cleanups

resources/assets/lib/profile-page/controller.tsx
Use id from `current_user_attributes` because the original one may be from different model.
=> Normalise score id before adding it to pinned array

package.json
It's barely readable and needlessly fills up log page.
=> Don't render progress bar when building assets for production

resources/assets/less/layout.less
Stop it from blocking outer part of the actual popup. It's only noticeable on `info` popups because the other types also have full page blackout overlay blocking everything.
=> Fix popup hover area

resources/lang/en/mail.php, resources/views/emails/password_reset.blade.php
There's no real reason for the user to reply in these cases as there's not much we can do, and not much room for actually compromising accounts using such a request.
=> Change password reset emails to not urge the user to reply

resources/assets/less/bem/profile-info.less
Otherwise the icon on normal state floats up too high when there are many usernames.
=> Fix positioning of previous usernames popup

app/Models/Beatmapset.php
In disqualify or reset function, it originally did receive post but then updated to be discussion instead but the variable name stayed, causing confusion.
=> Fix variable name of beatmapset discussion

app/Models/Solo/Score.php, tests/Models/Solo/ScoreTest.php
Some scores are/were submitted with statistics keyed CamelCased.
Related: ppy/osu#17157
=> Handle different casing of statistics object

package.json, yarn.lock
Originally used for react-autosize-textarea when it wasn't imported using es module.
=> Remove direct prop-types dependency

resources/assets/lib/components/click-to-copy.tsx
- always reset on mouse leave to ensure reset timer from onclick to not run on next hover
- titles are predefined; no need to obtain from element
- use ref instead of event target for qtip api
=> Fix click to copy component behaviour

app/Models/Multiplayer/Room.php, database/migrations/2022_03_18_125356_add_auto_start_duration_to_multiplayer_rooms.php
Duration provided in seconds as I don't believe there's a time-span compatible MYSQL data type. Capped at SMALLINT as we're likely never going to support auto-start countdowns longer than 5 minutes.
=> Add support for multiplayer auto countdown timers

resources/assets/lib/components/friend-button.tsx
There's a different bug but it can't normally be triggered/visible.
=> Fix user friends mobx being accessed outside reactive context

app/Transformers/ScoreTransformer.php
I noticed the client was receiving responses with `"replay": null` values, which causes client-side exceptions.
It was changed in https://github.com/ppy/osu-web/pull/8731, and I believe it to be an unintentional change since the sequence `?? null` doesn't make sense.
=> Fix null return for replay field in scores

resources/assets/less/bem-index.less, resources/assets/less/bem/chat-conversation-panel.less, resources/assets/less/bem/chat.less, resources/assets/less/bem/footer.less, resources/assets/less/bem/osu-layout.less, resources/assets/less/utilities.less, resources/assets/lib/chat/chat-state-store.ts, resources/assets/lib/chat/conversation-list-item.tsx, resources/assets/lib/chat/conversation-list.tsx, resources/assets/lib/chat/conversation-panel.tsx, resources/assets/lib/chat/conversation-view.tsx, resources/assets/lib/chat/input-box.tsx, resources/assets/lib/chat/main-view.tsx, resources/assets/lib/entrypoints/chat.tsx, resources/assets/lib/stores/channel-store.ts, resources/assets/lib/turbolinks.d.ts, resources/lang/en/chat.php, resources/views/chat/index.blade.php
...although this is really about no longer returning uninitialized channels from the state store and removing the `selectedBoxed` boxed primitive so there'll be less layers to go through when updating the channel selection logic for create/join new channels/announcements.
~~The `u-chat`/`osu-layout--mobile-app` class is moved to the body since it _seems_ to work now on current mobile Safari, except there are new issues (that happen even without the change) with mobile Safari that need fixing separately.~~
Turns out it's needed on `html` thanks to safari's scrolling but the layout shift navigating through history seems fixed by applying `fancy-scrollbar` separately to the body...
=> Update location bar when switching chat channels

resources/assets/lib/beatmapsets-show/main.coffee
Noticed this when preparing to typescript things. Leftover from updating score loader system.
=> Remove use of nonexistent state

resources/assets/lib/interfaces/beatmapset-extended-json.ts
As it turned out the legacy thread url may be null...
=> Fix typing for beatmapset extended json

.github/workflows/pack.yml
Pushes to Docker Registry everytime a tag is added, pushing both `latest` and current git tag.
Credentials are already added in the GitHub organization.
=> 👷 Add Docker push GitHub workflow

resources/assets/lib/components/big-button.tsx
It's pretty difficult to pass non-changing props due to `text` and `props` attributes being objects and they're usually specified inline.
=> Change button component type to non-pure

app/Libraries/OsuAuthorize.php, tests/Controllers/BeatmapsControllerTest.php
Part of #8243.
The test can use some clean up but it's a bit more tricky than I expected.
=> Allow moderator to change beatmap difficulty owner

resources/assets/lib/profile-page/beatmapsets.tsx
To be after loved instead of pending.
Resolves #8828.
=> Move guest participation beatmap listing on profile page

resources/assets/lib/beatmapsets-show/header.coffee, resources/assets/lib/components/beatmapset-cover.tsx
I forgot there's already different check hiding the whole page.
=> Always show cover for beatmap info page

resources/assets/less/bem/profile-extra-entries.less, resources/assets/lib/profile-page/parse-event.tsx, resources/assets/lib/profile-page/recent-activity.tsx
Should we color them as proposed initially? If so how?
With additionnal classes based on event type in `resources/assets/less/bem/page-extra.less` ?
closes #8410
=> Add additional icons in recent events

app/Libraries/Search/BeatmapsetSearchRequestParams.php
Mainly to prevent error being thrown when array is passed for string parameters which currently missing initial check.
Also changed default for `explode` value to empty string as what it's expecting (error will be thrown if strict mode is enabled).
=> Sanitise search parameters

resources/assets/coffee/_classes/beatmap-discussion-helper.coffee
Mainly so the <del>upcoming</del> banchobot post on older maps will always be the first visible thing when visiting the page but also probably makes more sense as mapper or moderators usually put note in there (maybe).
=> Change default discussion page to general all

app/Http/Controllers/Forum/TopicsController.php
The collection stops being normal array ("list") and becomes associative array along the way and thus `0` isn't the first item in it.
Resolves #8846.
=> Fix forum topic auto pagination

resources/assets/lib/beatmap-discussions/beatmap-owner-editor.tsx
Noticed while assigning usernames earlier that e.g. `Andrea ` didn't link to `Andrea`, trimming should fix this.
=> Trim username in beatmap owner editor

.github/workflows/pack.yml
Runs build on Git tag events. Tagging the Docker image using the Git SHA, the Git tag, and `latest` if the tag doesn't contain a hyphen.
=> Fix Docker build tagging

resources/assets/lib/beatmapsets-show/score-top.tsx, resources/assets/lib/beatmapsets-show/scoreboard-table-row.tsx, resources/assets/lib/scores-show/stats.tsx, resources/assets/lib/utils/score-helper.ts
Comparing `combo` attribute with beatmap's `max_combo` attribute seems to be the most correct method but there's currently nowhere to put it in the json. Even score's `beatmap.max_combo` in score display page could be wrong because that attribute ignores the score mods combination.
=> Update source for perfect combo score highlight

composer.json, composer.lock
Seems like a good idea and to remove warning from sentry interface.
Also that `sentry-laravel` has been on dev branch since we migrated to octane 👀
=> Use latest Sentry libraries

.github/workflows/pack.yml
This and the other two PRs should be all that's needed. During build, `APP_URL` and `DOCS_URL` are only for documentation and shouldn't affect normal/non production usage too much.
=> Include expected env vars for docker build

app/Models/Solo/ScoreData.php
Some data json may not have the values set.
=> Include table columns when creating score data object

resources/lang/en/beatmapsets.php
Keys are countable, so "amount" is wrong. Other reasons include:
- the [circle size wiki article](https://osu.ppy.sh/wiki/en/Beatmapping/Circle_size#osu!mania) uses key count
- the stable osu!mania editor uses key count
- most translations of this string are worded "number of keys" (going off google translate), and "number" indicates countable nouns.
- the circles and sliders statistic tooltip says "circle/slider count"
- the [hard coded string in lazer was once "key count"](https://github.com/ppy/osu/blob/2ef791069c67911d548c0da48886f32bd95b7634/osu.Game/Screens/Select/Details/AdvancedStats.cs#L123)
The translations don't need to be wiped as they are correct (as said in point 3).
=> Rename key amount to key count on beatmap info page

package.json, yarn.lock
Older version of `deasync` binary doesn't appear to be available so deploy tries to build with `node-gyp` which now requires python 3.6+ which is currently on none of the servers.
=> Update deasync to latest

app/Libraries/ReplayFile.php, app/Models/LegacyMatch/Score.php, app/Models/Score/Best/Model.php, app/Models/Score/Model.php, app/Models/Solo/Score.php, app/Models/Traits/Scoreable.php, app/Transformers/ScoreTransformer.php, database/factories/Score/Best/ModelFactory.php
The `gameModeString` cache is removed but hopefully it doesn't affect much...? Functions where it's repeatedly accessed have been updated to only do it once.
And it's no longer static function because it's only useful for the main legacy score classes under `App\Models\Score`; solo/multiplayer/legacy match score classes aren't split by ruleset.
=> Combine score ruleset function

app/Libraries/GithubImporter.php, app/Models/Build.php, database/migrations/2022_05_23_072546_rename_builds_build_on_release.php
There's delay between tag and actual release so create the build entry on release instead.
=> Create build on release event instead of tag

.github/workflows/pack.yml
Sentry releases are actually org-wide rather than project-wide, so we need to prefix release names by a slug unique to each project.
=> 🔧 Add prefix to Sentry release name

resources/assets/lib/beatmapsets-show/scoreboard/controller.ts
After the initial scores are loaded, selecting mod and immediately unselecting it will show error instead of showing the already loaded scores.
=> Fix error on changing mod on score listing while loading

app/Http/Controllers/CommentsController.php, app/Libraries/CommentBundle.php, app/Libraries/Commentable.php, app/Libraries/OsuAuthorize.php, app/Models/Beatmapset.php, app/Models/Build.php, app/Models/NewsPost.php, app/Transformers/CommentableMetaTransformer.php, database/migrations/2022_06_08_065812_add_comment_locked_to_beatmapsets.php, resources/assets/lib/components/comment-editor.coffee, resources/assets/lib/components/comment.coffee, resources/assets/lib/components/comments-manager.coffee, resources/assets/lib/components/comments.coffee, resources/assets/lib/interfaces/comment-json.ts
Resolves #8985 but only for admins with database access (or whatever other system) to actually disable commenting.
```sql
update osu_beatmapsets set comment_locked = 1 where beatmapset_id = $beatmapsetId;
```
This involves adding `comment_locked` column of type boolean/tinyint with default value of 0. Migration entry is
```
2022_06_08_065812_add_comment_locked_to_beatmapsets
```
in case manual migration is needed @peppy.
=> Allow disabling comment on specific item

resources/assets/lib/chat/create-announcement.tsx
Better? server-side message to be done separately.
This is just to limit the occurrences of `Unknown error occurred` when the database truncates the field for being too long. Naturally doesn't work well for multibyte characters.
=> Add form input length limits to Create Announcement UI

resources/assets/lib/models/notification-details.ts, resources/assets/lib/notification-maps/url.ts
Somehow managed to use the correct key for single item but wrong one for group items.
closes #9001
=> Fix announcement notification group link

resources/assets/lib/components/comment-show-more.coffee, resources/assets/lib/components/comments.coffee
`commentableType` and `commentableId` used by the pager got moved in #8997
=> Fix comments show more pager

resources/assets/lib/components/comment-show-more.coffee
Not sure why I expected the parent comment to still be using the old property names ಠ_ಠ
On further inspection, it seems that `load replies` hasn't been accounting for deleted comments in the replies for a while, since it has been passing the `parent_id` of the parent but not the `commentable_type` and `commentable_id`
closes #9015
=> Fix comment load replies

.github/workflows/pack.yml
Added a job to trigger our staging deployment workflow on new builds.
Also split Sentry releasing into its own job, to avoid the whole workflow to fail even if build succeeds.
The deploy job requires the `KUBERNETES_CONFIG_REPO_ACCESS_TOKEN` secret; see https://github.com/marketplace/actions/repository-dispatch#token
Pending on further modifications depending on workflow validation in the internal repository.
=> 👷 Trigger automated staging deploy on tags push

app/Libraries/User/FindForProfilePage.php
Otherwise `/users/someuser?key=username` will redirect to `/users/<someid>?key=username`.
=> Reset key parameter on profile path redirect

database/migrations/2022_06_27_073817_create_solo_scores_legacy_id_map.php
Resolves #9060 (nothing is using it at the moment).
@peppy the existing table has wrong type for `score_id`. It should be `unsigned bigint` but currently it's just `bigint`. That said, practically it shouldn't be a problem? And migration name for this is `2022_06_27_073817_create_solo_scores_legacy_id_map`.
=> Create legacy score id mapping table

database/mods.json
I wonder what should happen if a score is submitted from older client with the removed settings set 🤔 I think currently it'll throw error.
=> Sync mods data

app/Transformers/ScoreTransformer.php, resources/views/docs/_structures/score.md
Looking again it's a bit weird as int but should be fine as long it's in the expected format (with all the paddings) until year 9999.
Docs to be added later. The docs is currently missing version header info entirely and that also needs to be added.
=> Allow api request to obtain scores in new json format

.github/workflows/pack.yml
This is so we can use `latest-dev` in our staging deployment manifests rather than `latest`, which doesn't reflect the nature of the actually deployed images.
This is something we should probably add to our other pipelines.
=> 👷 Tag Docker dev images as latest-dev

database/migrations/2022_07_08_085310_add_allow_performance_to_osu_builds.php
Not sure what the correct default value should be - I've gone with `false` for now but maybe it'll be `true` in the future when lazer is more "stable"?
Kinda required for https://github.com/ppy/osu-queue-score-statistics/pull/44.
=> Add `allow_performance` column to `osu_builds`

Dockerfile.deployment, docker/deployment/nginx-assets.conf
`php` command has been removed. Also assets should have expires header.
=> Fix docker default command and assets expiration header

resources/assets/lib/beatmapsets-show/main.tsx
Seems like this isn't as new as it looks but the exact condition to trigger it might not be so common 🤔 
Because the component of the next page mounts before the current out unmount, `autorun` ends up triggering `setHash` if any of the observables it's watching gets updated.
It just so happens that current user `playmode` ends up being observed if via `findDefault()` through `currentBeatmap()`
if a beatmap hasn't explicitly been selected yet, which causes `autorun` to trigger when `core.setCurrentUser` is triggered on navigation.
A more complete fix would to be set the default beatmap when initializing `beatmapsets-show/controller` so that currentUser doesn't set sometimes observed.
closes #9114
=> Fix setHash triggering on wrong page after navigation.

app/helpers.php
The function to start the event is `begin()`, not `start()`. Move things around while at it to reduce redundant `microtime()` and `clock()` calls.
=> Fix clockwork timeline timing

app/Models/Chat/Channel.php, resources/assets/less/bem/btn-osu-big.less, resources/assets/less/bem/chat-input.less, resources/assets/lib/chat/create-announcement.tsx, resources/assets/lib/chat/input-box.tsx, resources/assets/lib/models/chat/message.ts
Limit max length so it doesn't get truncated by mysql.
Also increases the maximum height of the textbox in announcement channels to the same size as those in creating announcements, and anchors the textarea to the bottom.
Was going to add a message length counter but I figure that should be separate 🤔
=> Set max length on channel message input box

resources/assets/less/bem/chat-conversation-list-item.less, resources/assets/lib/chat/conversation-list-item.tsx
Mobile view will still show the full length of the name.
=> Truncate long channel names in channel list

app/Http/Controllers/Solo/ScoreTokensController.php, tests/Controllers/Solo/ScoreTokensControllerTest.php
Also added missing ruleset validation (just the number, not whether or not it makes sense in relation to the beatmap).
Resolves #9115.
=> Check for beatmap hash when creating score token

app/Console/Commands/BeatmapLeadersRefresh.php, app/Console/Commands/ForumTopicCoversCleanup.php
Otherwise it may not display the actual final number and not quite filled up.
=> Add missing `finish()` call on progress bars

resources/assets/lib/core/click-menu.ts
This prevented other things which are listening to click event on document from being triggered.
If I remember correctly this was originally to prevent parent menu from being hidden but the current system have full tree on which menu should be shown so it shouldn't be a problem anymore. Maybe 👀 
Resolves #9105. The hover menu z-index will be fixed separately.
=> Fix click event on menu button not propagated

routes/web.php, tests/api_routes.json
Mainly to allow the client to be sure that it's actually too many downloads and not related to the global request limit.
And nginx update is probably in order as well? 🤔 But at least I think one will return json and the other... whatever nginx returns (usually html).
Also I could make it a same top group divided by throttle existence but that'll rearrange middleware order.
Something like this
```php
Route::group(['as' => 'api.', 'prefix' => 'api/v2', 'middleware' => ['api', 'require-scopes']], function () {
Route::group(['middleware' => [ThrottleRequests::getApiThrottle()]], function () {
...
}
Route::get('beatmapsets/{beatmapset}/download', 'BeatmapsetsController@download');
}
```
(also I don't know about the `v2` separation there if it still makes sense at all)
Related: ppy/osu#19522
=> Skip global throttle for beatmapset download endpoint

docker-compose.yml
Noticed while trying to get score indexing to work locally.
=> Set correct elasticsearch host for solo scores index on docker-compose

database/migrations/2022_08_04_220851_create_bss_process_queue.php
- Closes #9091 
Migration done as per the table creation showcase that was [posted in the thread](https://github.com/ppy/osu-web/issues/9091#issuecomment-1177198550):
```mysql
CREATE TABLE `bss_process_queue` (
`queue_id` int unsigned NOT NULL AUTO_INCREMENT,
`beatmapset_id` int unsigned NOT NULL,
`start_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
`status` tinyint(1) NOT NULL DEFAULT '0',
`update_time` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (`queue_id`),
KEY `status` (`status`),
KEY `beatmapset_id` (`beatmapset_id`)
) ENGINE=InnoDB
```
=> Add migration for creating `bss_process_queue` table

app/Console/Commands/EsIndexScoresQueue.php
Makes it easy to figure out where to resume from after it's stopped midway.
=> Use score id for progress bar number

.github/workflows/tests.yml, app/Console/Commands/EsIndexScoresQueue.php, app/Console/Commands/EsIndexScoresSetSchema.php, app/Libraries/Search/ScoreSearch.php
Also removed unused indexAll and support for env `schema`.
=> Support indexing to active schemas

database/migrations/2022_08_15_081810_index_user_ruleset_id_on_solo_scores.php
Replaces index on `user_id` column.
migration entry is `2022_08_15_081810_index_user_ruleset_id_on_solo_scores`
index name is `user_ruleset_id_index`, the columns are `(user_id, ruleset_id, id DESC)`
also drop index `solo_scores_user_id_index` since it's redundant with the new index
=> Add index for user recent solo scores

database/migrations/2022_08_15_074123_index_beatmap_id_on_solo_scores.php
To be used for deleting scores when its beatmap(set) state is changed.
migration entry is `2022_08_15_074123_index_beatmap_id_on_solo_scores`
index name is `solo_scores_beatmap_id_index`
=> Add beatmap id index on solo scores

app/Libraries/BBCodeFromDB.php, tests/Libraries/bbcode_examples/invalid_email_url.db.txt, tests/Libraries/bbcode_examples/invalid_email_url.html, tests/Libraries/bbcode_examples/invalid_email_url.txt
Stop at the unescaped closing tag.
There's still some weirdness if there's another tag inside (e.g. `profile`), where, `email` won't link it and `url` will try to turn `profile` into a link (and creates 2 links instead because `a` can't be in `a`) due to differences in their escaping in `BBCodeForDB`
Not sure what to do about that so I left it for the moment 🤔 
closes #9191
=> Fix bbcode email and url parsing

routes/web.php
Wasn't supposed to be added with #8747 - this was for testing until announcements changed to use a different lookup 👀
=> Remove unused route

app/Models/Solo/ScorePerformance.php
The table doesn't have the relevant columns.
=> Fix timestamps being set for solo score performance

app/Libraries/RouteScopesHelper.php
Fixes apidocs not being generated on production builds.
It turns out that `laravel-query-detector` causes the `Http\Kernel` boot via its `QueryDetectorServiceProvider` registration, which gets excluded if dev dependencies are not installed, causing the middleware groups to not be set on the router when run from the console.
Or maybe we should always have the http kernel and middleware groups set even in console... 🤔
=> Ensure http kernel and router middleware groups are set

database/factories/Solo/ScoreFactory.php
faker uses number of digits, not a range... 👀
=> Fix Solo Score factory generated total_score

app/Models/Solo/ScoreData.php, app/Models/Solo/ScoreDataStatistics.php, resources/assets/lib/interfaces/solo-score-json.ts
Up next will be replacing `total_score` with `legacy_total_score` and calculation function in js for display.
=> Add new statistics attributes for score data json

app/Http/Controllers/Solo/ScoresController.php
Uh ( ﾟ ヮﾟ)
@peppy, if client has been sending it, it's never stored in the db.
=> Fix maximum statistics attribute not being stored

.github/workflows/tests.yml
I vaguely remember about this when seeing the PR yesterday but then followed by nothing.
=> Update env name for score indexer service

app/Models/Beatmapset.php, app/Models/BssProcessQueue.php, tests/Models/BeatmapsetTest.php
The model name and relation seem rather questionable but otherwise should work 🤷‍♀️
Resolves #9246.
=> Queue beatmapset for bss process when ranked

app/Http/Controllers/ContestsController.php, app/Models/Contest.php, resources/lang/en/contest.php, resources/views/contests/voting.blade.php, tests/Models/ContestTest.php
Add `requirement` object inside `extra_options`:
```json5
{
"requirement": {
"name": "playlist_beatmapsets",
"room_ids": [1, 2, 3],
"must_pass": false // optional (default true)
},
// ...other options...
}
```
Contest with child contest(s) is currently not supported quite right. Namely the requirement must be duplicated and they all must be the same.
=> Add contest vote requirement

database/migrations/2022_09_09_011035_upgrade_legacy_scoreids_to_bigint.php
This PR is just to get the ball rolling to make sure the change isn't forgotten about. I have not tested if osu!web doesn't actually fall over in some way with `score_id > int_max`.
So @nanaya / @notbakaneko please feel free to take over this PR and/or build on top of it if any additional changes are necessary.
For comparison:
[Before](https://github.com/ppy/osu-web/files/9531736/before.txt)
[After](https://github.com/ppy/osu-web/files/9531737/after.txt)
[Rollback](https://github.com/ppy/osu-web/files/9531780/rollback.txt)
=> Add migration changing all `score_id`s to `BIGINT`

app/Models/UserReport.php
The fix is a bit long and involves overriding function (see [this](/staudenmeir/eloquent-json-relations/issues/52) for example) and nothing is using it at the moment anyway (otherwise errors would've been thrown a long time ago).
=> Remove unused broken `UserReport#score` relation

app/Http/Controllers/BeatmapsController.php, app/Http/Controllers/LegacyInterOpController.php, app/Http/Controllers/ScoresController.php, app/Jobs/RemoveBeatmapsetBestScores.php, app/Libraries/Search/BeatmapsetSearch.php, app/Libraries/User/ScorePins.php, app/Libraries/UserBestScoresCheck.php, app/Models/Score/Model.php, app/Models/Solo/Score.php, app/Models/Spotlight.php, app/Models/Traits/UserScoreable.php, app/Models/UserStatistics/Model.php, database/seeders/ModelSeeders/SpotlightSeeder.php, tests/Controllers/BeatmapsControllerTest.php, tests/Controllers/Solo/ScoresControllerTest.php, tests/Models/Score/Best/ModelTest.php, tests/Models/Score/ModelTest.php
Also updated some variables to the latest naming `$ruleset` and `$rulesetId`.
It looks like the method itself should be called `getClassOrFail`... (but that's topic for another day)
=> Uniform `getClass` between UserStatistics and Score

.github/workflows/lint.yml, .github/workflows/tests.yml
Seems useful.
<del>Just `github.ref` doesn't seem to work for PR 🤔 </del> It does work but with different name: head_ref uses just the branch name `gh-concurrent` in this case and ref uses a more pr specific name `refs/pull/9268/merge`
=> Stop previous test run on new push to same branch/PR

app/Transformers/KudosuHistoryTransformer.php, app/helpers.php
Found this when checking if there's a better way to get class by ruleset ಠಿ_ಠ
=> Remove `get_model_basename` helper

app/Http/Controllers/BeatmapsController.php
Mainly to ensure reliable test. The alternative is for the test to ignore order when checking but that would require some more changes.
=> Order returned beatmaps by id

.dockerignore, resources/assets/lib/cli/mod-names-generator.js
The `.dockerignore` ignores a bit too many things...
Create build directory on the fly instead. This may or may not get annoying as anything writing to the directory has to create the directory first.
=> Fix docker deployment build

app/Http/Controllers/NewsController.php, database/migrations/2022_09_13_080115_index_news_posts_tumblr_id.php, resources/assets/lib/utils/url.ts, routes/web.php
@peppy the nginx config needs updating so `/news/` isn't handled by old web as defined in `osu_fallback_common.conf`.
Also I wonder if we should just move the news url to `/news/2022-07-27-some-slugs` from current `/home/news/2022-07-27-some-slugs`.
Resolves #9239.
=> Redirect old tumblr news post urls

resources/assets/less/utilities.less, resources/assets/lib/beatmapsets-show/scoreboard/table-row.tsx
...maybe 🤔 
`overflow-x: scroll` on the scoreboard causes Safari to always compose the scoreboard as a separate layer which Safari apparently takes as a free license to discard and recompose whenever it feels like while scrolling (instead of just repainting)...and then has to recompose all over again with cpu rendered `filter`
This makes Safari use the gpu for the scoreboard flag layer (and apparently stop throwing away the whole scoreboard).
The new issue is the colour levels applied by `filter` on gpu rendered layers are different, and it's not applied to all flags because it makes the larger flags become a blurry mess in Chrome.
=> Better beatmap scoreboard performance on mobile Safari

resources/assets/less/bem/flag-country.less, resources/assets/less/utilities.less, resources/assets/lib/beatmapsets-show/scoreboard/table-row.tsx
Always render flag in a separate layer; speeds up rendering on Safari especially on pages with a lot of flags (particularly mobile safari - desktop Safari doesn't seem to have the issue to the same extent unless in a scrollable element).
This was generally avoided previously due it turning the flags into a blurry mess on Chrome, except a recent update seems to always turn it into a blurry mess anyway.
The flag ratio is changed to the original 100/72 of the svg instead of 4/3; this stops the flag from turning into a blurry mess on Chrome.
fixes #9299
=> Faster and less blurry flags

composer.lock
This version was released over a year ago now. [Link](https://github.com/knuckleswtf/scribe/blob/v2/CHANGELOG.md#2710-wednesday-30-june-2021) to the changelog.
=> Bump knuckleswtf/scribe from 2.7.9 to 2.7.10

database/migrations/2022_09_21_052117_create_osu_difficulty_attribs.php
Expected:
```sql
> SHOW CREATE TABLE osu_difficulty_attribs\G;
***************************[ 1. row ]***************************
Table        | osu_difficulty_attribs
Create Table | CREATE TABLE `osu_difficulty_attribs` (
`attrib_id` smallint unsigned NOT NULL,
`name` varchar(256) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
`visible` tinyint(1) NOT NULL DEFAULT '0',
PRIMARY KEY (`attrib_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
```
Actual:
```sql
> SHOW CREATE TABLE osu_difficulty_attribs\G;
*************************** 1. row ***************************
Table: osu_difficulty_attribs
Create Table: CREATE TABLE `osu_difficulty_attribs` (
`attrib_id` smallint unsigned NOT NULL,
`name` varchar(256) NOT NULL DEFAULT '',
`visible` tinyint(1) NOT NULL DEFAULT …
```
=> Add migration for `osu_difficulty_attribs` table

app/Jobs/RemoveBeatmapsetSoloScores.php, app/Models/Beatmapset.php, tests/Jobs/RemoveBeatmapsetSoloScoresTest.php, tests/TestCase.php
This only deletes the scores without adjusting user statistics (still done by `BestScores` removal job).
=> Remove solo scores on beatmap state change

app/Http/Controllers/UsersController.php, app/Transformers/UserCompactTransformer.php
Reorder the includes while at it.
The alternative is to remove them entirely. We've marked them deprecated for long enough now.
=> Skip rebuilding redundant transformer includes

app/Transformers/UserCompactTransformer.php
Wasn't quite fixed completely in lazer yet 👀 
Will be fixed in https://github.com/ppy/osu/pull/20498; reverting order for backwards compatibility
=> Revert UserCompactTransformer rank_history include order

app/Http/Controllers/UsersController.php, app/Transformers/ScoreTransformer.php
The other preload is harder to do. Also this will still rerun the user transformer. Looking again it seems a bit overkill passing the whole thing repeatedly for each item just to display the username 🤷
Also who knows what else it's currently being used for in term of api.
=> Skip refetching same user from database

app/Libraries/Elasticsearch/SearchResponse.php
Apparently it's still being used by legacy score search.
=> Fix total value handling for legacy score

app/Libraries/Elasticsearch/SearchResponse.php
The other error from removal of total's response compat function (which was reverted due to also used by legacy score search).
=> Fix empty elasticsearch response

app/Libraries/BeatmapsetDiscussionsBundle.php, app/Libraries/ModdingHistoryEventsBundle.php, resources/assets/lib/beatmap-discussions-history/main.coffee, resources/assets/lib/beatmap-discussions/beatmapsets-context.ts, resources/assets/lib/entrypoints/beatmap-discussions-history.coffee, resources/assets/lib/entrypoints/modding-profile.coffee, resources/assets/lib/interfaces/beatmapset-discussion-json.ts, resources/assets/lib/modding-profile/discussions.coffee, resources/assets/lib/modding-profile/main.coffee
Bringing the modding profile and discussion history pages more in line with the actual discussions page (no embedded `beatmapset`, explicit prop).
This PR is mainly to check for breakage against the existing components while I convert `Discussion` to typescript as that doesn't seem to make any reference to `discussion.beatmapset` but some parts look like they would benefit from having `beatmapset` being `BeatmapsetExtendedJson` instead of just `BeatmapsetJson` 👀
=> Sideload beatmapsets in bundle instead of embedding in discussions

app/Models/Beatmap.php, app/Models/Beatmapset.php, app/Transformers/BeatmapCompactTransformer.php, app/Transformers/BeatmapTransformer.php, app/Transformers/BeatmapsetCompactTransformer.php, app/Transformers/BeatmapsetTransformer.php, app/helpers.php
Boy, is it ever ugly. The following wrk test on my dev with clockwork and debug disabled went from:
```
$ wrk -t 4 -c 12 -d 10s https://on.nanaya.pro/beatmapsets/
Running 10s test @ https://on.nanaya.pro/beatmapsets/
Thread Stats   Avg      Stdev     Max   +/- Stdev
Latency   387.51ms   34.22ms 733.90ms   90.55%
Req/Sec     8.07      4.26    20.00     84.00%
307 requests in 10.14s, 91.35MB read
Requests/sec:     30.28
Transfer/sec:      9.01MB
```
to:
```
$ wrk -t 4 -c 12 -d 10s https://on.nanaya.pro/beatmapsets/
Running 10s test @ https://on.nanaya.pro/beatmapsets/
Thread Stats   Avg      Stdev     Max   +/- Stdev
Latency   228.60ms   21.20ms 450.01ms   89.46%
Req/Sec    12.91      4.76    20.00     66.46%
522 requests in 10.09s, …
```
=> Skip laravel casting for beatmap and beatmapset transformers

app/Transformers/BeatmapsetTransformer.php
Addition to #9321 
Along with `nsfw` and `spotlight` flags on beatmapsets `download_disabled` was also affected
=> Fix beatmapset 'download disabled' boolean casting

app/Libraries/StorageWithUrl.php
Accessing `user_avatar` uses this class but only the `url` part which doesn't actually require the storage.
=> Delay disk storage instance initialisation

app/Http/Controllers/BeatmapsetsController.php, resources/views/beatmapsets/index.blade.php
10 minutes caching for guest user (when guest advanced search is disabled). Just the transformed data. My db is quite slow so the actual improvement might not be as dramatic since one hits db and the other doesn't.
Before:
```
Run 1:   600 requests in 10.10s, 177.53MB read
Run 2:   568 requests in 10.09s, 168.07MB read
Run 3:   607 requests in 10.08s, 179.61MB read
Run 4:   627 requests in 10.09s, 185.52MB read
Run 5:   608 requests in 10.09s, 179.90MB read
Run 6:   611 requests in 10.07s, 180.79MB read
Run 7:   623 requests in 10.06s, 184.34MB read
Run 8:   568 requests in 10.09s, 168.07MB read
Run 9:   575 requests in 10.10s, 170.14MB read
Run 10:   577 requests in 10.07s, 170.73MB read
Final run:
Running 10s test @ https://on.nanaya.pro/beatmapsets/
Thread …
```
=> Cache beatmaps page json response for guest

app/Http/Controllers/BeatmapsetsController.php, app/Libraries/LayoutCache.php, app/Providers/AppServiceProvider.php, resources/views/beatmapsets/_filters.blade.php, resources/views/beatmapsets/index.blade.php
This makes restarting server required when updating language and genre but then again we don't do that, so... 🤷‍♀️
Also I think the workers are currently restarted every 500 requests (default) so it should eventually be correct.
Maybe just use this for Groups caching as well... 🤔 
Before:
```
Run 1:   1781 requests in 10.10s, 526.98MB read
Run 2:   1873 requests in 10.10s, 554.21MB read
Run 3:   1784 requests in 10.10s, 528.06MB read
Run 4:   1832 requests in 10.09s, 542.07MB read
Run 5:   1808 requests in 10.19s, 534.97MB read
Run 6:   1855 requests in 10.09s, 548.88MB read
Run 7:   1844 requests in 10.08s, 545.64MB read
Run 8:   1843 requests in 10.00s, 545.37MB read
Run 9:   1804 requests in 10.08s, 533.79MB read
Run 10:   1874 requests in 10.18s, 554.55MB read
Final run:
Running 10s …
```
=> Cache beatmapset filters

app/Models/Model.php
Clockwork calls `getKey()` on everything in `Clockwork\DataSource\EloquentDataSource::collectModelEvent` and some models have `$primaryKey` explicitly set to `null`.
=> Allow null key for getRawAttribute

app/Libraries/ReplayFile.php, app/Models/Score/Best/Model.php, app/Models/Score/Model.php, tests/Libraries/ReplayFileTest.php
Included fix for setting `replayViewCount` relation correctly.
Before:
```
Run 1:   628 requests in 10.10s, 34.38MB read
Run 2:   594 requests in 10.06s, 32.51MB read
Run 3:   625 requests in 10.20s, 34.21MB read
Run 4:   622 requests in 10.12s, 34.05MB read
Run 5:   631 requests in 10.09s, 34.54MB read
Run 6:   602 requests in 10.10s, 32.95MB read
Run 7:   615 requests in 10.15s, 33.67MB read
Run 8:   622 requests in 10.09s, 34.05MB read
Run 9:   619 requests in 10.09s, 33.88MB read
Run 10:   619 requests in 10.10s, 33.88MB read
Final run:
Running 10s test @ https://on.nanaya.pro/beatmaps/567606/scores?mode=osu&type=global
Thread Stats   Avg      Stdev     Max   +/- Stdev
Latency   199.70ms   33.47ms 617.46ms   93.87%
Req/Sec    14.94      5.81    30.00 …
```
=> Define attributes for score best model

app/Models/Chat/Message.php, app/Transformers/Chat/MessageTransformer.php
Benchmark below is with #9372.
Before:
```
Run 1:   2052 requests in 10.09s, 32.28MB read
Run 2:   2058 requests in 10.10s, 32.38MB read
Run 3:   1950 requests in 10.09s, 30.69MB read
Run 4:   2032 requests in 10.09s, 31.97MB read
Run 5:   1950 requests in 10.10s, 30.68MB read
Run 6:   2020 requests in 10.08s, 31.78MB read
Run 7:   2018 requests in 10.09s, 31.75MB read
Run 8:   2059 requests in 10.09s, 32.39MB read
Run 9:   1965 requests in 10.10s, 30.91MB read
Run 10:   1925 requests in 10.18s, 30.29MB read
Final run:
Running 10s test @ https://on.nanaya.pro/community/chat/channels/861699/messages?return_object=1
Thread Stats   Avg      Stdev     Max   +/- Stdev
Latency    63.11ms   28.50ms 436.36ms   97.27%
Req/Sec    49.06     10.13    60.00     65.50%
1978 …
```
=> Define attributes for chat message model

app/Models/BeatmapDiscussionPost.php, tests/Browser/SanityTest.php
`save()` sets `$exists` to true, bypassing actual existence check in `callAfterCreating` in factory.
And then also fix the underlying problem of creating non-timeline starting post for a (potentially) timeline discussion.
=> Fix discussion model-related test

app/Http/Middleware/DatadogMetrics.php
The datadog daemon may run on different host so the host tag will be incorrect (mainly on k8s deployment).
=> Add actual hostname tag to datadog

app/Models/Comment.php, app/Transformers/CommentTransformer.php
The beatmap page can definitely use some more speedups...
Before:
```
Run 1:   143 requests in 10.07s, 24.77MB read
Run 2:   154 requests in 10.11s, 26.67MB read
Run 3:   155 requests in 10.12s, 26.84MB read
Run 4:   156 requests in 10.03s, 27.02MB read
Run 5:   154 requests in 10.03s, 26.67MB read
Run 6:   148 requests in 10.03s, 25.63MB read
Run 7:   146 requests in 10.04s, 25.29MB read
Run 8:   156 requests in 10.04s, 27.02MB read
Run 9:   156 requests in 10.11s, 27.02MB read
Run 10:   153 requests in 10.03s, 26.50MB read
Final run:
Running 10s test @ https://on.nanaya.pro/beatmapsets/41823
Thread Stats   Avg      Stdev     Max   +/- Stdev
Latency   765.35ms  141.59ms   1.35s    92.26%
Req/Sec     7.07      6.51    20.00     81.08%
155 requests in 10.12s, …
```
=> Define attributes for comment model

app/Models/Group.php
I doubt this makes much actual difference but it's simple enough 🤷 
Also simplified colour attribute logic.
```
$u = App\Models\Group::first(); $t = new App\Transformers\GroupTransformer; json_item($u, $t); $start = hrtime(true); for ($i=0;$i<100000;$i++) { json_item($u, $t); }; echo ((hrtime(true) - $start)/1000000000).PHP_EOL;
```
|   Before    |    After    |
|-------------|-------------|
| 9.665466267 | 2.690609318 |
=> Define attributes for group model

resources/assets/lib/beatmap-discussions/new-discussion.tsx
Resolves #9395. Or more like it's already supported but broken after conversion to typescript.
=> Fix note posting permission check for guest mapper

resources/assets/lib/beatmap-discussions/new-reply.tsx
May or may not resolve issue mentioned in #9405. I couldn't reproduce it but updating the storage synchronously seem to make more sense.
Also only focus input box after pressing the reply button and nothing else (posting reply on another open box).
=> Clean up discussion reply handling

app/Http/Controllers/Account/SessionsController.php, app/Http/Controllers/AccountController.php, app/Http/Controllers/Admin/Controller.php, app/Http/Controllers/BeatmapDiscussionPostsController.php, app/Http/Controllers/BeatmapDiscussionsController.php, app/Http/Controllers/BeatmapsetDiscussionVotesController.php, app/Http/Controllers/BeatmapsetEventsController.php, app/Http/Controllers/BlocksController.php, app/Http/Controllers/Chat/ChannelsController.php, app/Http/Controllers/Chat/ChatController.php, app/Http/Controllers/Chat/Controller.php, app/Http/Controllers/ChatController.php, app/Http/Controllers/ClientVerificationsController.php, app/Http/Controllers/Forum/PostsController.php, app/Http/Controllers/FriendsController.php, app/Http/Controllers/HomeController.php, app/Http/Controllers/Payments/PaypalController.php, app/Http/Controllers/Payments/XsollaController.php, app/Http/Controllers/ScorePinsController.php, app/Http/Controllers/SessionsController.php, app/Http/Controllers/Store/CartController.php, app/Http/Controllers/Store/CheckoutController.php, app/Http/Controllers/Store/NotificationRequestsController.php, app/Http/Controllers/StoreController.php, app/Http/Controllers/UsersController.php, app/Models/UserStatistics/Model.php, app/Models/UserStatistics/Spotlight/Model.php
`new Thing()` should always be returning the object and no one should be calling `->__construct()` anyway...
=> Remove unneeded return in __construct()

routes/web.php, tests/api_routes.json
Seems useful for chat  👀 
```
POST /api/v2/chat/ack
{ since: $id_of_last_received_message }
```
also returns recent silences since the last message
=> Add chat/ack endpoint to api

app/Http/Controllers/Chat/ChatController.php
Otherwise it'll query `->where('message_id', '<=', null)` which is invalid 🤷
=> Add default chat ack parameter value

app/Console/Commands/UserRecalculateRankCounts.php, app/Events/Fulfillments/PaymentEvent.php, app/Http/Controllers/UsersController.php, app/Libraries/BBCodeFromDB.php, app/Libraries/CurrentStats.php, app/Libraries/Elasticsearch/SearchParams.php, app/Libraries/Fulfillments/GenericFulfillment.php, app/Libraries/ImageProcessorService.php, app/Libraries/NewForumTopic.php, app/Libraries/Payments/CentiliSignature.php, app/Libraries/Payments/PaypalSignature.php, app/Libraries/Payments/XsollaSignature.php, app/Libraries/Search/ArtistTrackSearchParams.php, app/Libraries/Search/BeatmapsetSearchParams.php, app/Libraries/Search/ForumSearchParams.php, app/Libraries/Search/UserSearchParams.php, app/Libraries/Search/WikiSearchParams.php, app/Libraries/Search/WikiSuggestionsParams.php, app/Libraries/ValidationErrors.php, app/Listeners/Fulfillments/PaymentSubscribers.php, app/Mail/UserNotificationDigest.php, app/Models/Event.php, app/Models/Forum/TopicVote.php
Explicitly declare used instance variables.
Some cleanups in the process of adding static analysis. 
This doesn't bother with fixing the magic laravel stuff.
=> Declare missing instance variables

app/Http/Controllers/BeatmapsetsController.php
It's laravel/framework#26715 again which apparently isn't going to be fixed (or more like "isn't a problem") and should be manually done everywhere (still happens on latest laravel 9.19).
=> Fix error when weird id for beatmapset download is passed

.github/workflows/lint.yml
GitHub PR files tab may hang otherwise ಠ_ಠ
Looks like it's been fixed (or the unchanged files annotation is removed). But it's probably still a good idea anyway if they're going to readd the thing later? 🤷‍♀️
=> Silence lint warnings output

app/Libraries/Search/ScoreSearch.php
There appears to be some implicit limit in the number of items that can go in the `terms` condition before elasticsearch starts rewriting that portion of the query into many smaller combinations of the query (and it's not an A+B+C union situation)
From some initial testing, 18 mods seems fine, 19 starts to take 1+ second, 35 took 9 seconds, etc.
Breaking the into smaller terms seems to avoid the issue...even if it's in sets of 10 🤔 
This needs a bit more testing to ensure the mod filter behaves as expected
maybe fixes #9432?
=> Split score search mod exclusion into separate terms

app/Transformers/TransformerAbstract.php
just random thing i noticed
- typo in docs, but it doesnt seem necessary anyway
- return value worked as-is but the parent only returns ResourceInterface or false, so I think this should match.
=> Fix `TransformerAbstract::callIncludeMethod()` docs and return value

resources/assets/coffee/osu_common.coffee, resources/assets/lib/core-legacy/store-checkout.coffee, resources/assets/lib/globals.d.ts, resources/assets/lib/store.ts
Shouldn't be needed anymore since jquery3 conforms to the current Promise/A+ behaviour.
Also fixes an incorrect redirect after a free checkout (complete -> invoice -> redirect away) that's been there for who knows how long 💦
=> Remove osu.promisify

resources/assets/lib/beatmap-discussions/editor.tsx
May cause errors if the selection isn't unset when resetting the editor value as slate tries to make a selection at a position that doesn't exist.
=> Reset review editor cursor position after posting

resources/assets/coffee/bootstrap-modal.coffee, resources/assets/coffee/osu_common.coffee
Can't seem to trigger any issue on iOS in the other place that makes use of this (verification modal).
Also, mobile safari seems to ignore the focus() anyway 🤷
=> Remove osu.isIos

app/Models/Beatmapset.php
Use relation cache so it's not loaded multiple times (for `#description` and `#editableDescription`).
...although it really only affects beatmap owner and admins 🤷‍♀️
Cleaned up related functions a bit while at it.
=> Query beatmapset description post once

app/Libraries/CommentBundle.php, app/helpers.php
Also:
- combine parent fetching on null commentable and reply request
- skip querying on empty ids
- use Set for reject lookup
- don't reconcat `$allComments` with `$comments`
=> Remove nulls before whereIn query in comment bundle

resources/assets/coffee/osu_common.coffee, resources/assets/coffee/ujs-common.coffee, resources/assets/lib/admin/contest/user-entry-delete-button.coffee, resources/assets/lib/beatmap-discussions/discussion.coffee, resources/assets/lib/beatmap-discussions/nominations.coffee, resources/assets/lib/beatmap-discussions/subscribe.coffee, resources/assets/lib/components/comment.coffee, resources/assets/lib/components/comments-manager.coffee, resources/assets/lib/contest-entry/user-entry.coffee, resources/assets/lib/contest-voting/voter.coffee, resources/assets/lib/core-legacy/bbcode-preview.coffee, resources/assets/lib/core-legacy/beatmap-pack.coffee, resources/assets/lib/core-legacy/form-error.coffee, resources/assets/lib/core-legacy/forum-topic-title.coffee, resources/assets/lib/core-legacy/forum.coffee, resources/assets/lib/core-legacy/store-checkout.coffee, resources/assets/lib/utils/ajax.ts
Use the typescript version in `ajax.onError` instead.
Convert `emitAjaxError` to typescript.
`xhrErrorMessage` to be done separately due to being a bit less straight forward with the typings
=> Remove ajaxError from osu_common

app/Http/Controllers/Controller.php, app/Http/Kernel.php, app/Http/Middleware/SetSessionVerification.php, app/Http/Middleware/UpdateUserLastvisit.php, app/Http/Middleware/VerifyUser.php, app/Http/Middleware/VerifyUserAlways.php, app/Libraries/UserVerification.php, app/Libraries/UserVerificationState.php
- only use bypass verification option on login
- this means changing the variable later doesn't update existing sessions retroactively but shouldn't be too much hassle...?
- better than checking the option every time for production
- set verification related variables early
- only change verification requirement if not yet verified
- only check user privilege for verification requirement
- set frequently used variables
- use User#isSessionVerified for user lastvisit update check
Resolves #9460.
I've only done basic testing 👀
=> Refactor session verification

resources/assets/lib/utils/ajax.ts
For when the error response is not json (e.g. nginx error page).
=> Fix non-json xhr error handling

app/Http/Controllers/Chat/ChannelsController.php, app/Transformers/Chat/ChannelTransformer.php, resources/views/docs/_structures/chat_channel.md, resources/views/docs/info.blade.php
This was deprecated long ago; osu-web doesn't use it (it's not even in `ChannelJson`) and only kept around for compatibility with https://github.com/ppy/osu/blob/4bc26dbb487241e2bbae73751dbe9e93a4e427da/osu.Game/Online/API/Requests/Responses/APIChatChannel.cs#L17-L18 having a reference to it
=> Mark recent_messages as deprecated

app/Libraries/Elasticsearch/Search.php, app/Libraries/Score/FetchDedupedScores.php
Change in #9527 means getting extra scores for deduping needs passing in a extra param in the cursor which is expected to be boolean by the value returned for the cursor is an integer....
Currently the part handling the cursor doesn't have enough info about the parameter to perform any casting.
=> Hot fix solo scores leaderboard when extra scores need to be fetched

resources/assets/lib/utils/lang.ts
The `lang.d.ts` definition needs the type to be exported from `lang.ts` otherwise it'll treat it as `any` (but doesn't trigger any errors).
=> Add missing export for type definition

app/Models/Wiki/Image.php
Wait up to 10 seconds on first image load if other worker is already doing it and holding the lock.
=> Prevent incorrect error on simultaneous first wiki image request

app/Http/Controllers/Chat/ChatController.php
Returns `messages: []` in the `/chat/updates` endpoint for compatibility with older lazer clients which expect `messages` to be present and not null.
=> Return empty messages in chat updates for compatibility

app/Models/Store/OrderItem.php
Maybe 🤷‍♀️ Seems to work on a different test of setting casts value manually to something else and reaccessing the attribute.
=> Ensure correct cast type for order item extra data

resources/views/store/objects/order.blade.php
Randomly found this weird thing 🤨
It's immediately followed by another closing tag so browser automatically fixes it (and there's no matching open tag for what it's closing).
=> Fix store line item closing tag

composer.json, composer.lock
Swoole 5 removes `Server::tick()` so an update to `laravel/octane` 1.3 is needed to remove calls to it.
This is the same as #9627 with only the updates for updating octane (and hopefully without extra breaking changes).
=> Update octane package to support swoole 5

app/Console/Kernel.php
I don't think any of the jobs benefit that much from running simultaneously. Some may even cause weird result.
=> Limit cron job task to single worker

app/Http/Controllers/RankingController.php, resources/assets/lib/components/ranking-filter.tsx
`display` column was originally for store: 0 only means it's not shipping there. It shouldn't be used to determine whether or not to show in the ranking list.
Also sort all countries except user own country alphabetically.
Resolves #8699.
=> Adjust country list in ranking page

.github/workflows/tests.yml, docker-compose.yml
Not used, so no point having elasticsearch try to update it while starting or spitting out not enough shards errors
=> Disable elasticsearch geoip downloader for docker compose

Dockerfile.deployment, Dockerfile.development
Noticed the following error in production logs:  
Curious that this never reached Sentry.
No idea what's the impact -- maybe our produced jpegs are heavier now? We surely would have heard about it from support if it directly impacted users. Also no idea if that was installed on our previous droplets.
Both `libjpeg-progs` and `libjpeg-turbo-progs` provide the `jpegtran` binary. I couldn't figure which implementation is best through this codebase and Laravel docs, but overall `libjpeg-turbo-progs` seems best.
=> 🐛 Fix missing jpegtran binary

app/Http/Middleware/VerifyUser.php
Previous fix on it only applies when `USER_POST_ACTION_VERIFICATION` was set to false (or maybe the option didn't even exist at the time).
=> Always skip verification for preference update

app/Libraries/Markdown/OsuMarkdown.php, app/helpers.php
It's been renamed to just [`convert`](https://commonmark.thephpleague.com/releases/#220---2022-01-22)
=> Update commonmark conversion function call

app/Http/Controllers/Chat/Channels/MessagesController.php
apparently `->whereHas('sender')` doesn't work cross database so just filter out the nulls
=> Filter missing sender before transform

app/Libraries/OsuAuthorize.php, tests/Libraries/ChatTest.php
Accounts in the `bot` group probably aren't expected to have plays; expands on #9702 to apply in general instead of just chats.
Includes some updates to ChatTest to use `expectCountChange` instead of the previous method of asserting changes.
=> Skip minplays check for bot group

resources/assets/lib/chat/message-divider.tsx, resources/lang/en/chat.php
Found this in one of the ancient branches.
=> Translatable unread message label

app/Http/Controllers/UsersController.php, app/Http/Middleware/VerifyCsrfToken.php, resources/views/users/create.blade.php, routes/web.php, tests/Controllers/UsersControllerTest.php
CSRF requirement with web registration makes it rather difficult to return correct error message.
Also add tests which discovered confirmation field check isn't actually working 👀
Although as there's already check on frontend it's probably not actually needed?
=> Split client and web registration endpoints

resources/assets/less/bem/mod.less
Resolves #9765. Kind of. The label will be too large in cases where the element size is in wrong proportion (due to flexbox sizing etc).
There are more problems with rendering many mods but those are for another time...
=> Fix mod background styling

resources/assets/less/bem/chat-message-item.less, resources/assets/less/bem/osu-md.less, resources/assets/lib/chat/message-item.tsx, resources/assets/lib/models/chat/message.ts
Should be safe to just apply the whole `osu-md` class since chat markdown only uses a limited subset with nothing floating around 🤔
=> Apply markdown container styling to announcement messages

resources/css/bem/chat-conversation-list-item.less, resources/css/bem/chat-conversation-list.less, resources/js/chat/conversation-list.tsx
Mainly for mobile because you can't see which group you're in.
For announcement and public channels, I just used the same icon as their notification icons; PM has a different icon to differentiate it without using multiple icons (I think maybe the notification icon for PMs should be updated to match?; legacy-pm has its own row in notifications so sharing the icon here shouldn't be a problem). Nothing returns group chat yet so a random icon was picked.
This also changes the sticky headers to scroll off instead of overlapping each other.
=> Add icons to chat conversation list headers

app/Libraries/Fulfillments/ApplySupporterTag.php, tests/Libraries/Fulfillments/SupporterTagFulfillmentTest.php
When the order has multiple tags to the same user.
Turns out there was actually a reason the user lookup wasn't done in the constructor 💦
=> Fix supporter tag duration not applying properly

tests/Libraries/Fulfillments/SupporterTagFulfillmentTest.php
Just to get the test to pass before we update the month to be 730 hours.
=> Fix test adding supporter tags in two separate items

app/Libraries/Fulfillments/ApplySupporterTag.php, app/Models/User.php, database/factories/UserFactory.php, database/migrations/2023_01_30_080509_use_datetime_for_supporter_expiry.php, tests/Libraries/Fulfillments/SupporterTagFulfillmentTest.php
1 month is now 730 hours.
depends on:
=> Fairer duration for supporter tags

resources/js/interfaces/user-multiplayer-history-json.ts
It's removed when its functionality was replaced `current_playlist_item`.
=> Remove unused interface fields

resources/lang/en/events.php
It was originally linking to the user actually getting supporter tag but the current one just link to whoever purchased the support (probably for the better).
Resolves #9683.
=> Adjust wordings for first support event entry

app/Libraries/OsuAuthorize.php
Missing some logging and mailing (and silencing) that exist in bot command version.
...it's still visible for admins though.
It may be put back if someone bothered to move those additional stuff to osu-web but for now 🤷‍♀️
Resolves #9774.
=> Hide delete beatmap button for moderators

app/Models/BeatmapDiscussion.php
It's only doable by moderator when there are replies and in such cases the entire thread is intended to be gone.
This should resolve #8700 although it doesn't retroactively delete existing replies. <sub>I'll figure out a query to do it one of these days maybe</sub>
=> Recursively delete discussion post

resources/js/components/discrete-bar.tsx
Fixes #9850
(when you expect clamp to be between 2 numbers, but it's not 👀 )
=> Fix very wide hype button

.github/workflows/lint.yml, .github/workflows/tests.yml, Dockerfile.deployment, Dockerfile.development, composer.json, composer.lock
Upgrading to laravel 9 turned out to be a bit more annoying than expected so this can go in first instead. As additional bonus we may be able to just jump directly to 10 instead with this.
I'm not updating php specification in composer because notification and thumbnailer servers' php need to be updated separately. It'll be done as soon as it's deployed so I don't bother keeping old version in test matrix.
I'll update the branch protection rule accordingly once this pr is approved 👀
=> Update to php 8.1

app/Http/Controllers/ChangelogController.php, app/Http/Controllers/Passport/AuthorizationController.php, app/Libraries/Search/BeatmapsetSearchRequestParams.php
Probably missed some of the more hidden ones..or the ones that look non-null but actually could be null 🤔
=> Fix calling explode() on null deprecation

.github/workflows/pack.yml
[GitHub environments](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment) allow for per-environment secrets and protection rules, the latter being very needed for production deploys.
=> 🔧 Enable GitHub environments settings

resources/js/components/header-v4.tsx, resources/js/core-legacy/forum.coffee
Mainly in core-legacy/forum where for some reason one of its function (topicMeta) uses newBody when the rest of it uses currently displayed document.
Resolves #9869. (going to user profile from a forum topic show)
=> Fix page change event triggered before page load

docker/development/entrypoint.sh
=> Run octane as correct user in docker

.gitignore, app/Libraries/Ip.php, app/Libraries/Ip2Asn.php, app/Libraries/Ip2AsnUpdater.php, docker/development/prepare.sh
The combined table contains `::` - `::1` entry which is in incorrect order when combined with ipv4 as it ends at `::ffff:ffff` (`::255.255.255.255`) after conversion.
Also technically converted ipv4s should be prefixed with `::ffff:0:` (or `::ffff:`) instead of `::`.
I don't know where to put enums 🤔  (should it be in `App\Enums` or something)
=> Separate ipv4 and ipv6 lookup

.github/workflows/pack.yml
Adds a payload containing a `dockerTag` variable to be consumed by the osu-web production deploy workflow in the `osu-kubernetes-config` repository.
=> 🔧 Add docker tag in production deploy dispatch payload

database/mods.json
Most importantly, includes the new "Fade out hit circles earlier" setting for classic mod. The setting is out in a lazer release, so deployment should probably be expedited.
Addresses https://github.com/ppy/osu/discussions/22779.
=> Update mod definitions

app/Models/User.php, database/migrations/2015_01_01_133337_base_tables.php
- use existing scope
- use correct type (2 means ignore, 3 means "founder")
Saw this when messing around with user type.
=> Adjust user type column handling

resources/js/beatmapsets-show/header.tsx
Less confusion for when the page being checked as guest.
=> Always show limited beatmap availability info

resources/css/bem/page-tabs.less
- use gap
- stretch-align the items in follows (not sure why it's flex-start)
Resolves #7047
=> Fix alignment of page tabs

app/Http/Controllers/BeatmapPacksController.php, app/Models/BeatmapPack.php, resources/js/core-legacy/beatmap-pack.coffee, resources/views/packs/_header.blade.php, resources/views/packs/index.blade.php, resources/views/packs/raw.blade.php, resources/views/packs/show.blade.php, routes/web.php, tests/Browser/SanityTest.php, tests/Browser/ScaffoldDummy.php
- add proper habtm between pack and set
- default to tag instead of id for url parameter
- combine show and raw endpoint
- use json date formatting as formatLocalized is deprecated in php 8.1
- cache current user variable
- lookup completion data with Set
Also looked into using tag for "primary key" but the join and sort columns still depend on id.
=> Clean up beatmap pack rendering

app/Http/Kernel.php, app/Http/Middleware/SetLocale.php, app/Http/Middleware/SetLocaleApi.php, resources/views/docs/info.md.blade.php, tests/LocaleTest.php
Different behaviour added for `*` so it can be used when the http client enforces the header.
Resolves #8113.
=> Prioritise accept-language header for api endpoint

app/Http/Controllers/HomeController.php, resources/css/bem/btn-osu-big.less
- Use correct locale for download page platform names
- using static means the content doesn't change between requests
- Simpler header passing
- the original headers are stored in a different place
- Allow button to expand on locales with longer text
- for example in japanese
=> Various fixes for download page

resources/css/bem/header-nav-v4.less
Something I came across while borrowing the nav for the markdown editor.
Switch to using `gap` instead of margin/padding offsetting
=> Cleanup header nav styling

app/Http/Controllers/BeatmapPacksController.php, resources/css/bem/beatmap-pack.less
Not really solving #2761 but should help reducing number of pages to browse through. Reduces padding a bit so it's quite too long.
=> Increase number of beatmap packs per page

.github/workflows/tests.yml
It's two different bugs ಠ_ಠ
- beatmap indexing added to the model's `afterCommit` a while back unintentionally fills up es
- es returning cursor itself can't actually parse (for null timestamps `Long.MAX_VALUE`/`MIN_VALUE`)
=> Clean up ES index after PHPUnit test on GitHub Action

app/Providers/AppServiceProvider.php, config/octane.php
Customisable octane state path and recognise `dusk.local` env as it's what the dusk octane would be started under. It's needed because octane doesn't seem to respect any changes to `APP_ENV` in the `.env` file so when the test replaces `.env` file with the dusk one which has `APP_ENV=testing`, the actual env stays at whatever it originally started as (usually `local`). Apparently reported two years ago at laravel/dusk#949 and no update since.
=> Fix running multiple octane instances at the same time

app/Libraries/BBCodeFromDB.php, resources/css/bbcode.less, tests/Libraries/bbcode_examples/autolink.html, tests/Libraries/bbcode_examples/basic_list.html, tests/Libraries/bbcode_examples/basic_quote.html, tests/Libraries/bbcode_examples/list_title.html, tests/Libraries/bbcode_examples/quote_newline.html
Resolves #5505.
Spacing between blockquotes and lists is now done with `<br />` instead of margin.
=> More precise bbcode newline normalisation

resources/js/beatmap-discussions/editor-discussion-component.tsx, resources/lang/en/beatmaps.php
Resolves #6193. Technically people translating this could've done this themselves ("If this post (:type)") but looking again the English version seems kind of weird anyway with capitalised type. And it already says "Posts" for All difficulties tooltip.
=> Remove type in timestamp tooltip

resources/js/beatmap-discussions-history/main.coffee, resources/js/beatmap-discussions/discussion.tsx, resources/js/beatmap-discussions/post.tsx, resources/js/modding-profile/discussions.tsx, resources/js/modding-profile/main.coffee, resources/js/modding-profile/posts.coffee
Simpler alternative to #9969
Essentially disables modification on pages that can't really handle the entire discussion response properly.
=> Disable editing beatmap discussion post on user modding profile

resources/css/bem/beatmapset-header.less, resources/css/bem/beatmapset-info.less, resources/css/bem/beatmapset-stats.less, resources/js/beatmapsets-show/header.tsx, resources/js/beatmapsets-show/info.tsx
I was looking at #8787 figuring might as well merge that instead of waiting for the new design but then realized that the page margin is wrong on mobile and description box is done in a rather interesting way (and also missing bottom padding and has right padding for some reason).
This includes the change to overflow tags but shares style with description overflow instead of its own style (and without `__box` in `__box`).
I just remembered why the description is done that way - it's so the box doesn't expand when expanding spoiler box. It's already expanding everywhere else though so I think it's fine here as well.
=> Adjust beatmap page margin and add tags overflow

app/Libraries/Search/BeatmapsetSearch.php, config/schemas/beatmapsets.json
Resolves #7627. Partial username match isn't supported. Username with space in it must currently be specified using id. The same with username which consists of only numbers.
=> Allow searching beatmap by difficulty owner

app/helpers.php, resources/js/components/beatmapset-panel.tsx, resources/js/components/comment.coffee, resources/js/utils/html.ts
As it turned out ICU already have the relevant formatting (of course they do). It's shortened to M/B/T on the php side but I think it's fine. It's already shortened on javascript side.
Resolves #4192.
=> Localise suffixed number format

resources/css/bem/beatmapset-header.less
There's a different problem of things moving around when hovering around difficulties with vastly different length but solving that is a lot more annoying.
Resolves #10057.
=> Enforce wrapping of beatmap difficulty name

.env.dusk.local.example, .env.testing.example, SETUP.md, docker-compose.yml, docker/development/entrypoint.sh
Reusing dev octane doesn't work for dusk. Additionally prevent the new octane instance from overwriting existing octane state.
~~Removed verbose logging while at it.~~ Wait no it's also defined in run_dusk.sh ಠ_ಠ maybe for another time
=> Fix running test in docker

app/Notifications/UserReportNotification.php
Resolves #9195. Or more like "resolves".
Attempted:
- ❌ escape with backslash
- ❌ use html entity
- ❌ percent encode
=> Escape brackets in user link part of report for discord

resources/js/form-errors.ts
Initially also looked into improving handling of `form_error` itself but it's more annoying than expected ಠ_ಠ
=> Fix FormErrors error when receiving non-json error response

app/Models/Tournament.php, tests/Models/TournamentTest.php
Better than silently doing nothing. This is an admin error so this should be sufficient (as opposed to adding more checks in `isRegistrationOpen` etc).
=> More useful error on registering running tournaments

package.json, yarn.lock
There doesn't seem to be any change to the two api calls we're using? Although my dev setup doesn't even work with the older library so depending on how the live store is currently setup there may need some changes over there instead? 🤷‍♂️
=> Update shopify api library

app/Exceptions/ModelNotSavedException.php, app/Http/Controllers/AccountController.php, app/Http/Controllers/InterOp/UsersController.php, app/Http/Controllers/UsersController.php
I thought of handling the exception right with the exception itself but there's nowhere to pass the model field name to the exception.
Also apparently errors on `user_profile_customization` in `Account#updateOptions` weren't included at all.
=> Unify handling of model-based form error response

resources/js/notification-maps/message.ts, resources/js/utils/lang.tsx
Explicitly pass fallbackLocale for checking existence of dynamically generated key.
=> Fix js transExists incorrectly checking fallback locale

app/Models/User.php
There was a problem with deleting some ten of thousands tokens recently and this should alleviate it. There may still be problem with the actual process taking a while but that'll be for another day.
=> Revoke OAuth tokens in multiple batches for user reset session

resources/js/osu-core.ts
Only update current user state if the json exists otherwise going back will reset to guest as the json is removed on initial read.
Resolves #10179.
=> Fix incorrect user state on navigation

app/Http/Controllers/UsersController.php
Offset can't go below 0 - it'll just be offset 0 anyway. Additionally, `pow(0.95, -100000)` results in INF, causing `json_encode` to fail.
=> Fix incorrect weight on negative offset

resources/views/accounts/edit.blade.php
So I can link better from the old site as we turn things off.
=> Add anchor for legacy API settings

app/Http/Controllers/BeatmapsetsController.php, app/Libraries/OsuAuthorize.php, app/Transformers/BeatmapsetCompactTransformer.php, resources/js/beatmapsets-show/metadata-editor.tsx, resources/js/interfaces/beatmapset-json.ts, tests/Controllers/BeatmapsetsControllerTest.php
Reduces confusion on what it currently actually does. May be reverted once the tags are updated in client as well.
=> Limit users who can edit online tags

app/Models/Forum/Post.php
Resolves #10196. The second most edited post is at just a bit over 10k so there's not much point increasing the column size.
=> Stop post edit counter after 64k

app/Models/UserReport.php, resources/lang/en/model_validation.php, tests/Models/UserReportTest.php
Seems weird to be able to report messages without being in a channel 👀 
(also apparently there's legit use-case for allowing reports without being in a channel)
=> Require being in a channel to report chat message

app/Console/Commands/RouteConvert.php, app/Libraries/RouteScopesHelper.php
Shouldn't be escaped; also, apparently `JSON_UNESCAPED_SLASHES` exists 🤔
=> Fix forward slash escaping when printing route:convert to console

app/Models/User.php, resources/js/profile-page/links.tsx
Closes #10257 
Due to the rollout that may take months, I've added the ability to use either a pomelo or discriminator Discord username/tag.
**Here are some screenshots of how it will display:**
- If discriminator is present
- If no discriminator is present (pomelo, prefixes with "@")
Validation still exists, it either must be a full discriminator or not have one at all...
=> Support new Discord username format

.github/workflows/tests.yml
disables xdebug coverage on tests to speedup action
=> Disable xdebug coverage in GitHub Action

.github/workflows/lint.yml
improve phpcs run time disabling xdebug on github action
=> Disable xdebug coverage in GitHub Action (lint)

resources/css/bem/beatmap-discussion-timestamp.less, resources/css/bem/page-extra-tabs.less, resources/css/layout.less
There's no telling when new design will happen so this should make do in the meantime. It doesn't work when new discussion box is being pinned but getting that to work would involve updating the js side which is being refactored so it's not happening here 🤷‍♀️
Resolves #1394. There's also #2382 but it seems to be a different issue requesting full timeline to be anchored somewhere.
=> Always show timestamp in discussion page timeline

app/Libraries/Search/BeatmapsetSearch.php
When `BEATMAPSET_GUEST_ADVANCED_SEARCH` is enabled.
=> Fix error when searching for favourited beatmaps as guest

app/Models/Chat/Channel.php, app/Transformers/Chat/ChannelTransformer.php, resources/js/chat/input-box.tsx, resources/js/interfaces/chat/channel-json.ts, resources/js/models/chat/channel.ts, resources/js/models/chat/create-announcement.ts, resources/js/models/chat/message.ts
There's one problem with this approach that is the length for new channel isn't known until it's saved 🤔 
Resolves #9590.
=> Include channel message length limit data

resources/js/core-legacy/forum.coffee, resources/js/utils/blackout.ts
Resolves #4115. I feel preventing event from bubbling out of the dialog dom in the first place would be better but that's for another day I guess 🤔
=> Fix navigation incorrectly triggered when dialog is visible

.github/workflows/pack.yml
Since the main production deploy set-up has been working fine, enhancing it today with support for multiple tracks (master and private-staging).
Unfortunately, env vars cannot be used in some properties (eg. jobs `if` or environment names) so there's more repetition than I'd like...
@peppy Please configure the project to require manual approval for the `private-staging` environment!
=> 👷 Enable multiple production tracks

resources/js/core-legacy/forum-auto-click.coffee
Target and event name were flipped so the listeners are never actually removed ಠ_ಠ
=> Remove correct event listener

app/Libraries/Search/ScoreSearch.php
There may not be required parameter after optional parameters.
=> Fix invalid function default value

app/Libraries/Search/BeatmapsetQueryParser.php, tests/Libraries/Search/BeatmapsetQueryParserTest.php
Otherwise `11/04-2016` ended up being parsed to having timezone of -20:16 and rejected by elasticsearch.
(this change doesn't fix it to parse to year 2016 but still better than having exploding elasticsearch)
=> Always set time for beatmapset query to utc

app/Models/Multiplayer/Room.php, app/Models/Multiplayer/UserScoreAggregate.php, tests/Models/Multiplayer/RoomTest.php
Laravel already have the exactly same attribute just with different name.
=> Remove redundant isNew attribute

app/Http/Controllers/Multiplayer/Rooms/Playlist/ScoresController.php, tests/api_routes.json
There's an explicit `if ($user !== null)` check when looking up the user score and it returns `null` if there's no user, but the middleware wasn't updated to not require `auth` and therefore always requires a user, so I'm not sure what's actually supposed to be going on here 🤔
=> Allow guest user to view Playlist scores

resources/views/docs/info.md.blade.php
Hi, I'm the developer of [osu.py](https://github.com/sheppsu/osu.py), a purely Python API wrapper for specifically v2 of the osu api. I regularly update the library and actively seek to improve it. Was wondering if I could get it added onto the list of API wrappers on the docs.
=> Add osu.py to list of API wrappers on the docs

app/Models/Multiplayer/PlaylistItemUserHighScore.php
"Updating" nonexistent record is noop in laravel because apparently it previously updates the whole table instead (laravel/framework#12083) (ha ha ha) and then updated to be noop because filling the model and saving it as requested makes too much sense.
=> Fix saving new user playlist high score

app/Libraries/BBCodeFromDB.php, tests/Libraries/bbcode_examples/imagemap.html, tests/Libraries/bbcode_examples/imagemap_invalid_content_escape.base.txt, tests/Libraries/bbcode_examples/imagemap_invalid_content_escape.db.txt, tests/Libraries/bbcode_examples/imagemap_invalid_content_escape.html
The other fix fixed the problem globally while this one is doing the right thing for this specific tag without relying on the global cleaner (which turned out was disabled).
=> Fix escaping in invalid imagemap

resources/views/docs/_structures/user_compact.md
Wasn't added in https://github.com/ppy/osu-web/pull/9861.
=> Add `ProfileBanner` `image@2x` field to api docs

resources/js/profile-page/account-standing.tsx, resources/lang/en/users.php
closes #10417, I've also let this affect restrictions as well since the same wording logic applies
=> Rename "permanent" bans to "indefinite"

resources/css/bem/account-edit.less, resources/css/bem/artist-album.less, resources/css/bem/beatmap-discussions.less, resources/css/bem/comments.less, resources/css/bem/contest.less, resources/css/bem/footer.less, resources/css/bem/header-v4.less, resources/css/bem/landing-sitemap.less, resources/css/bem/osu-layout.less, resources/css/bem/osu-page.less, resources/css/bem/search.less, resources/css/bem/store-products.less, resources/css/bem/tournament-list.less, resources/css/bem/tournament.less, resources/css/bem/user-home.less, resources/css/variables.less, resources/views/accounts/_edit_legacy_api.blade.php, resources/views/accounts/_edit_notifications.blade.php, resources/views/accounts/_edit_oauth.blade.php, resources/views/accounts/edit.blade.php, resources/views/artists/index.blade.php, resources/views/home/landing.blade.php, resources/views/master.blade.php
Moves the `margin-bottom` gap to the section container.
Apparently it's supposed to be everywhere; except it looks really odd in chat, especially on mobile, so I removed it there.
=> Cleanup layout footer gap

app/helpers.php, database/migrations/2016_02_27_103851_create_osu_slack_users_table.php, database/migrations/2016_02_29_052133_create_beatmapset_discussions.php, database/migrations/2016_03_02_214730_change_primary_key_on_slack_users.php, database/migrations/2016_03_03_223651_osu_slack_user_make_slack_id_nullable.php, database/migrations/2016_03_09_083112_add_index_on_slack_id.php, database/migrations/2016_03_18_170000_create_oauth_scopes_table.php, database/migrations/2016_03_18_170001_create_oauth_grants_table.php, database/migrations/2016_03_18_170002_create_oauth_grant_scopes_table.php, database/migrations/2016_03_18_170003_create_oauth_clients_table.php, database/migrations/2016_03_18_170004_create_oauth_client_endpoints_table.php, database/migrations/2016_03_18_170005_create_oauth_client_scopes_table.php, database/migrations/2016_03_18_170006_create_oauth_client_grants_table.php, database/migrations/2016_03_18_170007_create_oauth_sessions_table.php, database/migrations/2016_03_18_170008_create_oauth_session_scopes_table.php, database/migrations/2016_03_18_170009_create_oauth_auth_codes_table.php, database/migrations/2016_03_18_170010_create_oauth_auth_code_scopes_table.php, database/migrations/2016_03_18_170011_create_oauth_access_tokens_table.php, database/migrations/2016_03_18_170012_create_oauth_access_token_scopes_table.php, database/migrations/2016_03_18_170013_create_oauth_refresh_tokens_table.php, database/migrations/2016_08_25_055700_create_contest_vote_aggregates_view.php, database/migrations/2016_10_28_000000_update_oauth_tables.php, database/migrations/2016_12_19_132350_add_kudosu_refresh_votes_to_beatmap_discussions.php, database/migrations/2017_02_01_105338_drop_slack_users.php, database/migrations/2017_02_13_013536_delete_contest_vote_aggregates_view.php, database/migrations/2017_08_28_110634_drop_beatmapset_discussions.php, database/migrations/2017_11_22_081837_remove_kudosu_refresh_votes_from_beatmap_discussions.php, database/migrations/2021_03_24_130818_create_solo_scores.php, database/migrations/2021_09_15_065842_create_new_score_tables.php
random problem i found while testing #10454. see `2016_10_28_000000_update_oauth_tables` for example
=> Fix migrations with dependencies failing if run by themselves

resources/views/docs/info.md.blade.php
I maintain a JS/TS API wrapper called osu.js that supports API v1 and v2 and would like to see it added to the current list of API wrappers.
[Repository](https://github.com/L-Mario564/osu.js)
=> Add link to osu.js API wrapper

SETUP.md
It confused me because this version is not used now
=> Remove the Laravel Mix docs link in SETUP.md

.eslintrc.js, database/mods.json, resources/js/beatmapsets-show/scoreboard/mod.tsx, resources/js/beatmapsets-show/scoreboard/table-row.tsx, resources/js/beatmapsets-show/scoreboard/top-card.tsx, resources/js/cli/mod-names-generator.js, resources/js/components/mod.tsx, resources/js/interfaces/score-mod-json.ts, resources/js/interfaces/solo-score-json.ts, resources/js/profile-page/play-detail.tsx, resources/js/scores-show/player.tsx
Resolves #10471... mostly in lazer site because current prod only shows legacy score in most areas except for `/scores/{solo_score_id}`.
depends on:
=> Show settings in the mod tooltip

app/Http/Controllers/ScoresController.php, app/Models/Score/Best/Model.php, app/Models/Solo/Score.php, resources/js/utils/score-helper.ts, routes/web.php, tests/Browser/SanityTest.php, tests/Controllers/ScoresControllerTest.php, tests/api_routes.json
Download action stays separate because I can't figure out how to have optional parameter in the middle without leaving extra slash when optional parameter is empty.
=> Add api endpoint for new score show and download routes

app/Http/Controllers/Multiplayer/RoomsController.php, routes/web.php, tests/api_routes.json
closes #10491
Added some basic docs for `@queryParam` so I don't have to keep digging for it; `category` is omitted due to being deprecated.
=> Remove filtering multiplayer rooms by route path parameter

resources/js/remark-plugins/legacy-link/micromark.ts, resources/js/remark-plugins/old-link/micromark.ts
Apparently, `consume` isn't allowed immediately following `exit`, and, triggers assertion failures in the dev version of `micromark` which webpack 5 will use by default for development builds - production does not include `assert`s; performance of dev builds with assertions enabled is another issue.
I decided to go with the simplest fix which is wrapping `consume`s following an `exit` with a dummy effect that only contains the value consumed.
=> Fix old and legacy link markdown parsing errors 

resources/js/profile-page/parse-event.tsx, resources/lang/en/events.php
Resolves #8877?
It's just a `<strong>` and no font resize. But the current legacy css doesn't have specific styling either and I can't find reference to the original `epicN` classes.
Also the bold is not quite visible 🤷
=> Highlight new top rank (1-50) in event

app/Http/Controllers/Chat/Channels/MessagesController.php, app/Models/Chat/Channel.php, app/Models/Chat/Message.php, app/Transformers/Chat/ChannelTransformer.php
A combination of low id and high timestamp means the query spends a lot of time searching for nonexistent messages.
Resolves #10510.
=> Fix slow query when looking up messages beyond backlog limit

app/Transformers/UserBadgeTransformer.php, resources/js/interfaces/user-badge-json.ts, resources/views/docs/_structures/user.md, resources/views/docs/_structures/user_compact.md
Resolve #10434
~~I'm not sure if naming the new field as `image@2x` and duplicating `image_url` as `image` would be better or not.~~
=> Add 2x image url to user badge

resources/css/bem/beatmap-discussion-post.less, resources/css/bem/beatmap-discussion.less, resources/css/bem/beatmap-discussions.less, resources/css/layout.less, resources/js/beatmap-discussions/discussion.tsx, resources/js/beatmap-discussions/discussions.tsx, resources/js/beatmap-discussions/main.coffee
Something like this, maybe? 🤔 
Uses native `scrollIntoView` function ~~and `scroll-margin`~~; `instant` scroll avoids triggering lazy loaded images except when the image is close to the current view position. Chrome and Firefox should still handle it fine since they support scroll anchoring, Safari will still jump, not sure about Edge. The default of `auto` won't work because Safari just takes it to mean `smooth` even on load....
Updating `scroll-padding` instead of adding `scroll-margin` to the elements as it doesn't seem to use the correct position to offset of layout shift when images get loaded in.
Moved some of the element `padding` to `margin` otherwise Chrome still anchors to the wrong position 🤨 (also noticed some of the element structure could be updated to better handle it, but …
=> Fix beatmap discussion jump to anchor position

app/Models/Solo/Score.php
Split off #9427 and #9438 so I can separate both PR without conflicting with each other. Not used anywhere but it's similar to legacy score model.
=> Add default scope for solo score

resources/css/bem/beatmap-discussions.less, resources/js/beatmap-discussions/discussions.tsx, resources/views/beatmap_discussion_posts/_item.blade.php, resources/views/beatmap_discussions/_item.blade.php
Remove creating an necessary layer (immediate `beatmap-discussion` child element already is own layer); the overflow also doesn't do anything anymore.
There's a different overflow/overlap problem which `overflow-x` here doesn't fix, anyway.
=> Remove unnecessary beatmap discussion wrapper

app/Libraries/Search/BeatmapsetQueryParser.php, app/Libraries/Search/BeatmapsetSearch.php, app/Libraries/Search/BeatmapsetSearchParams.php, app/Libraries/Search/BeatmapsetSearchRequestParams.php
`difficulty=best`
`difficulty="with spaces"`
closes #10083
=> Add beatmapset difficulty name search filter

package.json, yarn.lock
1. it's been deprecated
2. we don't even initialize it anywhere 👀 
3. mobx 6 doesn't even support it
=> Remove mobx-react-devtools

package.json, resources/js/beatmap-discussions/new-discussion.tsx, resources/js/beatmap-discussions/new-reply.tsx, resources/js/beatmap-discussions/post.tsx, resources/js/chat/input-box.tsx, resources/js/components/comment-editor.tsx, resources/js/components/textarea-autosize.tsx, resources/js/oauth/client-details.tsx, resources/js/oauth/new-client.tsx, yarn.lock
`react-autosize-textarea` hasn't been updated in a while and doesn't have current versions of React in its dependencies.
It's just wrapping `autosize`, anyway, so we might as well use `autosize` directly - the component is just a convenience wrapper to attach and detach `autosize` and doesn't use `forwardRef`, making the implementation more straight-forward.
=> Remove react-autosize-textarea

Dockerfile.deployment
...by building it natively.
Other changes include switching back to `apt-get` because `apt` apparently shouldn't be used for scripting and updating node installation to the current supported method.
The final build doesn't have a lot of things like node or even composer. I think it should work fine without them?
Build log: https://github.com/nanaya/osu-web/actions/runs/6171056504/job/16748549037
Build result: https://hub.docker.com/layers/nanaya/osu-web/master/images/sha256-437563725df4e7c0255fa4b148181965dbedb2e2affb372ac24d61c8670c83a9
=> Speed up assets building on non-native platform

app/helpers.php
Apparently it was for forum topic reply command in slack.
=> Remove unused base62 encode function

resources/js/artist-tracks-index/main.tsx
`header` doesn't do anything :thinking: 
replaced with `generic-compact` which only changes box shadow, which was noticeably missing from the sides
=> Fix artist tracks search form class

app/Libraries/User/UsernamesForDbLookup.php, app/Models/User.php
Should've done this in the other pr but forgot to actually do it 👀
Also found another place it can be used.
=> Combine lookup username array generation logic

app/Models/Beatmap.php
The osu-web portion of #10566. Should be safe to deploy anytime as it'll only be used if not 0.
=> Use beatmap max combo column value if available

.github/workflows/pack.yml
Removing some deprecation warnings. Seems to [build](https://github.com/nanaya/osu-web/actions/runs/6325885794/job/17178327916) (failed to push due to no permission).
=> Update github pack action

resources/js/beatmap-discussions/main.coffee, resources/js/beatmap-discussions/new-discussion.tsx, resources/js/beatmap-discussions/new-review.tsx
`position: sticky` and `scroll-padding` don't quite behave well together.
Typing into the text area or selecting text constantly triggers scrolling into view and the combination of `position: sticky` and `scroll-padding` makes the entire page scroll; this doesn't happen if the total `scroll-padding-top` is less vertical position where it's focusing into view (which it normally isn't). 
closes #10578
=> Fix page scrolling when typing into new discussions text box 

app/Models/Multiplayer/PlaylistItemUserHighScore.php
I think this should fix showUser endpoint error in some cases (by hiding those scores just like everywhere else)
=> Fix multiplayer scores around query returning unmigrated entries

app/Docs/Strategies/UsesCursor.php, app/Http/Controllers/BeatmapDiscussionsController.php, app/Http/Controllers/BeatmapPacksController.php, app/Http/Controllers/BeatmapsetsController.php, app/Http/Controllers/EventsController.php, app/Http/Controllers/Forum/TopicsController.php, app/Http/Controllers/Multiplayer/Rooms/Playlist/ScoresController.php, app/Http/Controllers/NewsController.php, config/scribe.php
Standardize the `cursor_string` description instead of repeating the description text everywhere; some other params could probably be standardized as well.
The down side is they are all ordered at the bottom at the moment 🤔
=> Support annotations to handle cursor_string parameter for apidocs

resources/views/docs/info.md.blade.php
I recently transferred the ossapi repository from the circleguard org to my personal account. Links currently redirect fine, but as I expect this move will be permanent, we might as well link avoid a redirect in the docs.
=> update ossapi link

database/migrations/2023_10_24_122345_drop_id_from_user_profile_customizations.php
That's a lot more involved than I expected. I suspect a manual migration is required.
```sql
alter table `user_profile_customizations` modify `user_id` int unsigned not null;
alter table `user_profile_customizations` drop `id`;
alter table `user_profile_customizations` add primary key (`user_id`);
alter table `user_profile_customizations` drop index `user_profile_customizations_user_id_unique`;
```
=> Drop id column from user profile customisations table

database/migrations/2023_10_25_093434_drop_unused_score_link_columns.php, database/migrations/2023_10_25_094633_drop_score_link_id_from_multiplayer_scores_high.php, database/migrations/2023_10_25_094642_drop_last_score_link_id_from_multiplayer_rooms_high.php
~~Three migrations, two of which should be pretty trivial (drop columns) but the last one is a bit involved and includes creating a new primary key so maybe another manual migration.~~
```sql
alter table `multiplayer_score_links` drop `id`;
alter table `multiplayer_score_links` drop `room_id`;
alter table `multiplayer_score_links` drop `beatmap_id`;
alter table `multiplayer_score_links` drop `build_id`;
alter table `multiplayer_score_links` drop `created_at`;
alter table `multiplayer_score_links` drop `updated_at`;
alter table `multiplayer_score_links` add primary key (`score_id`);
alter table `multiplayer_score_links` drop index `multiplayer_score_links_score_id_index`;
alter table `multiplayer_score_links` drop index `multiplayer_score_links_room_id_user_id_index`;
```
```sql
alter …
```
=> Remove unused multiplayer score link related columns

app/Libraries/CleanHTML.php
The warning when using tinker is pretty annoying.
=> Prevent html purifier mkdir error in simple case

app/Models/Multiplayer/ScoreLink.php, tests/Models/Multiplayer/ScoreLinkTest.php
The `allowed_mods` list being empty is not supposed to mean that any mod is allowed. Any and all allowed / "free" mods must (and will) be explicitly listed in `allowed_mods`; if the list is empty, then it means that the score's mods must be exactly set-equal to `required_mods`.
I discovered this when working on https://github.com/ppy/osu/issues/5378 - I was very surprised when web set me submit a play with the "Touch Device" mod active even when it was (by design) not included in either the required or allowed mods. As it turns out, it would only let me do this if no allowed / "free" mods were set; if at least one allowed mod was specified, the client would correctly report an error when trying to submit the score.
(And yeah that means I'm likely going to be adding a carve-out for the …
=> Fix multiplayer score mods not being validated properly when playlist item has no allowed mods

app/Libraries/Countries.php
Accidentally accessed the method when doing review of another PR thinking it's public as it's the first method of the class.
=> Move private method

resources/js/components/select-options.tsx, resources/js/utils/blackout.ts
Blackout doesn't get cleared/set properly on the discussion beatmap list and spotlights selector when they're open and navigating back/forwards to the page.
=> Fix beatmap and spotlight selector blackout when navigating via history

database/migrations/2015_01_01_133337_base_tables.php, database/migrations/2015_01_01_133337_chat_base_tables.php, database/migrations/2016_06_21_054206_create_poll_votes_table.php, database/migrations/2016_06_21_055139_create_poll_options_table.php, database/migrations/2016_06_21_134532_create_banchostats_table.php, database/migrations/2016_07_21_072328_create_artist_tables.php, database/migrations/2016_07_29_024320_create_contest_tables.php, database/migrations/2016_08_16_101048_create_sessions_table.php, database/migrations/2016_09_30_064049_create_user_contest_entries_table.php, database/migrations/2016_12_07_063316_create_artist_albums_table.php, database/migrations/2017_02_21_084403_mb4_forum_last_topic.php, database/migrations/2017_07_20_013337_create_osu_beatmappacks_table.php, database/migrations/2017_07_20_013338_create_osu_beatmappacks_items_table.php, database/migrations/2017_09_01_101541_create_osu_profile_banners.php, database/migrations/2017_09_12_065003_fix_logs_table_encoding.php, database/migrations/2017_10_10_082642_add_ip_bans.php, database/migrations/2017_11_27_064736_fix_user_sig_encoding.php, database/migrations/2020_09_25_092826_create_phpbb_banlist.php, database/migrations/2022_10_18_103120_create_osu_user_performance_rank_highest.php
The prod tables have been updated separately (not all of them but as needed) and I've been ignoring it on the last two structure sync.
The utf8_bin technically should be changed to utf8mb4_bin but I don't see any of those requiring the specific `bin` collation (that is the exact binary match instead of case insensitive etc) so I dropped those as well.
I think `compressed` should be something to be considered on per-deployment basis but that's for another day 🤷‍♂️ On the other hand dynamic has been default for however long so those are removed.
=> Remove encoding and non-compressed row format

package.json
The script has been moved and changed to be an exported module instead of a cli.
=> Remove yarn localize script

database/migrations/2023_11_22_055714_change_multiplayer_scores_high_attempts_to_int.php
I'm not sure where it came from 🤨 (probably because I saw it on playlist item `max_attempts`)
This one matches the one in `multiplayer_rooms_high`
=> Use correct int size for multiplayer attempts column

app/Providers/AuthServiceProvider.php, tests/Providers/AuthServiceProviderTest.php
Test to ensure the relevant routes are registered and not registered to the appropriate controller actions, to avoid getting trolled since we're not using the default passport behaviour.
=> Add OAuth route registration sanity test

app/Models/Multiplayer/UserScoreAggregate.php
The change to always create playlist item high score entry broke the exist check.
Note: untested.
Resolves #10778 (probably)
=> Fix incorrect check for completed playlist item

tests/TestCase.php
No need to mock things when can just pass the correct header.
=> Pass actual oauth token in test

app/Libraries/Search/ScoreSearch.php
Found this when cleaning up branches.
=> Reuse generated score id array for queue

app/Models/Solo/Score.php, database/migrations/2023_12_18_085034_update_scores_table.php
Matches current prod except the partitioning.
=> Update scores table structure

app/Http/Controllers/AccountController.php, app/Libraries/Search/ScoreSearchParams.php, app/Models/UserProfileCustomization.php, app/Transformers/UserCompactTransformer.php
This doesn't do anything by itself but should theoretically allow me to update the other new score PRs without going back to interleaving the commits with each other.
I hope.
Added helper because it's needed in quite a few places.
=> Add toggle for legacy score only view

app/Models/Beatmapset.php, tests/Models/BeatmapsetTest.php
**Please exercise caution when reviewing. I'm PRing this in the hope that this can be helpful and at least partially offload other team members, but I only _sort of_ know what I'm doing here and operating mostly off intuition. Please take any steps that you feel expedient in validating the assumptions behind these changes, which I will attempt to explain below, first.**
---
The reasoning for this change is related to the introduction of legacy scoring attributes (https://github.com/ppy/osu-difficulty-calculator/pull/224) which are intended to be used by `osu-difficulty-calculator` to recalculate scores imported from stable to the new standardised scoring scheme.
Today it was revealed that some stable scores could not be imported to the new scoring tables due to missing legacy scoring …
=> Always push beatmaps to BSS queue after they become eligible for score submission

resources/js/components/beatmapset-event.tsx, resources/js/components/modal.tsx, resources/js/components/portal.ts, resources/js/utils/lang.tsx
Some updates of the react types to prepare for updating to React 18.
`ReactChild` and `ReactFragment` are deprecated, `ReactFragment` not even actually a `Fragment`
=> React typing fixes

SETUP.md
- `build --no-cache` is smart enough now to not rebuild same things repeatedly
- using `docker compose up` skips dependency update which may cause confusion
=> Update docker dev documentation

resources/js/core/timeago.ts, resources/js/notifications/notification-controller.ts
targeting `ES2022` and later changes fields to be initialized earlier (but still after parent class, so `this.props` is generally fine)
=> Fix field initialization order

app/Http/Controllers/PasswordResetController.php, tests/Controllers/PasswordResetControllerTest.php
Seems to make more sense. Also avoids reset re-triggering forced reactivation when the redirect never happens and the user logs in again from a different session.
=> Mark user active on password reset

app/Transformers/UserCompactTransformer.php, resources/css/entrypoints/docs.less, resources/views/docs/_structures/user.md, resources/views/docs/info.md.blade.php
Should use `active_tournament_banners` for the list of banners instead
=> Deprecate active_tournament_banner property in User API response

tests/Browser/SanityTest.php
Well.
Or maybe use youtube-nocookie.com instead? 🤔
=> Ignore third party cookie error from youtube

app/Http/Controllers/UsersController.php, app/Models/Solo/Score.php, app/Models/User.php, app/Transformers/UserCompactTransformer.php
This will roll through all the user's scores but apparently it's already doing something like it anyway due to the user index in prod has a lot more columns in it (instead of just user_id and ruleset_id). So maybe it'll be fine? 🤷‍♀️
One of the worst cases is going through something like 200k rows.
Resolves #10912.
=> Limit recent scores to 48h

app/Http/Controllers/Solo/ScoresController.php, app/Models/Solo/Score.php, tests/Controllers/Solo/ScoresControllerTest.php, tests/Models/Solo/ScoreTest.php
Not needed anymore after migration to new score table.
The converter function stays because it's still used by transformer.
Removal of the old transformer will be done later. Maybe.
~~(this PR is untested)~~ the test passed so it should be fine™
=> Remove lazer score conversion to legacy score

database/migrations/2024_01_31_181425_unview_scores.php
Force index doesn't work on view...
(actual force index was pushed directly to master)
Removal of other aliases will come later™
=> Remove alias for for scores table

app/Models/Solo/Score.php
This prevents scores that's waiting to be processed from being deleted by different clean up process.
Failing scores stay marked as not preserved initially as there's less processing involved.
Resolves #10942.
=> Better initial score preserve value

app/Transformers/ScoreTransformer.php
I forgot `?->` doesn't absolve the need to make sure the variable exists in the first place.
=> Fix undefined variable

app/Models/Traits/Scoreable.php
It originally used enum but then converted to string and catch stayed as is 👀
=> Fix rank calculator for catch

resources/js/modding-profile/main.tsx, resources/js/modding-profile/votes.tsx
resolves #10956. the section was empty because the user store was not being read from correctly, and fallback behavior is to not show anything in that component
seems to have regressed in #10409 and I think it went unnoticed because `UserJson[]` can assign to `Partial<Record<number, UserJson>>`...
=> Fix recent votes section of modding profile

.env.example, config/osu.php, resources/js/models/user.ts
the guest user correctly shows a 1x or 2x variant, but a real user with default avatar only shows 1x at the moment
feels weird to write in a `@2x` like this but I think it's fine? alternatively `avatar_url` could be null for default but I don't think that's what API consumers would want.
=> Use 2x variant for default avatar image

app/Models/Solo/Score.php
Calling this a mess is a bit of understatement. Also it's still kind of wrong.
```csharp
if ((CurrentScore.CountMiss + CurrentScore.Count50 + CurrentScore.Count100) == 0 && ((float)CurrentScore.CountKatu / CurrentScore.TotalHits) < 0.1)
CurrentScore.Perfect = true;
else
CurrentScore.Perfect = false;
```
Related: #10679
=> An attempt to get legacy perfect for mania closer to what it should be

resources/js/beatmap-discussions/nominations.tsx
`window.setTimeout` is for if the page has to switch from the History tab, otherwise the focus won't trigger.
=> Fix disqualify button not focusing on new discussion text box

app/Libraries/CurrentStats.php, app/Models/BanchoStats.php, app/Models/Build.php, database/migrations/2024_02_12_000001_add_users_lazer_to_bancho_stats.php
Resolves #10991.
Something to note is that this doesn't change the user counts used for the user graph, since this works by Bancho inserting user counts on an interval and that doesn't seem possible with the `osu_builds` table.
The issue mentions caching the user count for around a minute, however the homepage is already doing a 5 minute cache on all of the stats so I don't think it's necessary.
=> Update `BanchoStats` to include `users_lazer` for online user count(s)

app/Libraries/Search/WikiSuggestionsRequestParams.php
Passing an array `query` would cause error. Also ensured to not pass null to trim.
=> Fix error on passing unexpected parameter type

app/Libraries/Elasticsearch/Hit.php, app/helpers.php, resources/views/home/_search_result_forum_post.blade.php
There may be another `<em>` after $cap that's still below $limit. When that happens, the $limit cutoff may include the extra tag without its corresponding closing tag.
Additionally, use `mb_` for position calculation and `truncate` for truncating text because str_limit uses "width" nonsense.
=> Fix search highlight cutoff position

docker-compose.yml
This speeds up shutdown time since artisan queue doesn't quite handle signal correctly. Similarly with schedule loop.
=> Use docker builtin init

.dockerignore, Dockerfile.deployment, docker/deployment/entrypoint.sh
The previous default action was removed, making it invalid. And then the new default is defined in a different place. The end result is two defaults defined separately.
=> Fix default deployment docker command

resources/js/core/fix-relative-link.ts, resources/js/osu-core.ts
Turbolinks appends the url right away and clicking the link again will append it again which is definitely not the intended effect.
Resolves #10662.
=> Update relative link to absolute link on click

resources/js/beatmap-discussions/beatmap-list.tsx, resources/js/beatmap-discussions/discussions-state.ts
closes #10987
also added the filter to the url for middle clicks
=> Fix beatmap discussion filter resetting when switching difficulties or page tabs

app/Jobs/Notifications/UserAchievementUnlock.php
To be used for lazer-side display of awarded medals (https://github.com/ppy/osu/issues/18880, client-side PR to come shortly). Previously discussed [on discord](https://discord.com/channels/188630481301012481/188630616286167041/1209458059638874142).
Opening as draft to start with since I'm not completely sure yet we're going to be using the notifications websocket for this client-side. But I did test full-stack and it appears to work.
=> Add description to user achievement unlock event payload

resources/css/bem/supporter-icon.less, resources/js/components/supporter-icon.tsx, resources/js/components/user-card.tsx, resources/js/quick-search/user.tsx
Looks better on 100ppi display with 100%, 150%, and 200% scaling. Also on phone with 445ppi display with unknown scaling.
Cleaned up SupporterIcon component while at it.
Resolves #1574.
=> Improve supporter icon alignment

resources/js/core/wiki/reference-link-tooltip.ts
There are nbsp's between the backlinks.
=> Remove trailing space of reference link tooltip

app/Jobs/Notifications/UserAchievementUnlock.php
Explicitly set so it doesn't depend on the base class providing the expected defaults.
=> Specify defaults for medal unlock notification options

app/Models/Solo/Score.php, resources/js/scores-show/player.tsx
No point fetching the rank from es if it's not supposed to have one? Using 0 as placeholder.
=> Skip fetching rank for certain score types

app/Jobs/RemoveBeatmapsetSoloScores.php, app/Models/Solo/Score.php, tests/Jobs/RemoveBeatmapsetSoloScoresTest.php
Prevents scores from being actually deleted, for things like multiplayer scores which scores should stay.
=> Update ranked flag to remove scores from index

app/Exceptions/Handler.php, tests/Controllers/Passport/ApproveAuthorizationControllerTest.php
Thanks, passport :neutral_face:
=> Ignore invalid session error from oauth approval endpoint

resources/css/bem/beatmap-scoreboard-table.less, resources/js/beatmapsets-show/scoreboard/table-row.tsx, resources/js/beatmapsets-show/scoreboard/table.tsx, resources/js/beatmapsets-show/scoreboard/top-card.tsx, resources/js/scores-show/stats.tsx, resources/js/utils/score-helper.ts
Related: https://github.com/ppy/osu/issues/27473
In stable, both fruit misses and large droplet misses were counted as full misses and shown in the miss column. In lazer they are two disparate statistics (misses and large tick misses).
Because we cannot retroactively get this data out for all scores on stable, this PR changes the display instead so that lazer scores have misses and large tick misses summed up in the "miss" column, which restores parity (stable scores will be full misses which actually include large tick misses, plus zero "actual" large tick misses, and lazer scores will just sum actual full misses and actual large tick misses).
In the process this fixes silent CSS breakage due to implicit dependency of the CSS rule changed on the textual value of `attribute` key of each …
=> Fix inconsistency in displayed miss count between stable & lazer catch scores

app/Exceptions/FastImagesizeFetchException.php, app/Transformers/ContestEntryTransformer.php, app/helpers.php, resources/views/store/products/show.blade.php
Trying to figure out wtf is happening with contest image. 
Also added similar logging for store product image so it doesn't silently fail.
=>  Better image size error logging

app/Exceptions/GitHubInvalidDataException.php, app/Libraries/OsuWiki.php
Somehow github returned an object without content (twice) but it's not supposed to happen so having an idea what it actually returns may help.
=> Include more detail when GitHub returns unexpected response

app/Libraries/User/PasswordResetData.php
While the initial step does check for valid email, the current user status check that happens later doesn't.
=> Fix password reset error on null email

resources/css/bem/blackout.less, resources/js/beatmap-discussions/beatmap-list.tsx, resources/js/components/modal.tsx, resources/js/components/select-options.tsx, resources/js/core-legacy/nav2.coffee, resources/js/utils/blackout.ts
Instead of simple show/hide toggle, record the elements requesting blackout and show the blackout based on if there's anything still requesting it. The idea is similar to the one in Modal component.
(originally mentioned in #10737)
Resolves #11037 (obvious), resolves #10940 (BeatmapList's blackout toggle from document click running after modal's)
=> Fix blackout handling

app/Models/Beatmapset.php
It should be regenerated when it comes back and update is re-triggered 🤷
=> Skip beatmap cover regenerate on missing archive

app/Http/Controllers/BeatmapsController.php, app/Http/Controllers/RankingController.php, app/Libraries/Search/UserSearch.php, app/Libraries/User/Cover.php, app/Transformers/ScoreTransformer.php, app/Transformers/UserCompactTransformer.php, app/Transformers/UserTransformer.php
🧹 
<del>drafting since I forgot to add migration to remove the column</del> Will do that after this one is deployed instead.
=> Remove usage of profile customization model for user cover

app/Models/Beatmapset.php
`get_stream_filename` doesn't need specific position cursor (and nor has it been reset for things processed through image processor).
Also removed bytesWritten as it's not used anywhere.
=> Remove unnecessary function and variable

app/Libraries/User/Cover.php, app/Models/User.php, tests/Libraries/UserRegistrationTest.php
Consistent profile cover if we're to add more or change presets. The existing ones also need to be filled in but it can be done with one liner tinker.
=> Always set default cover id

app/helpers.php
errno is still 0 if returned by target server (4xx, 5xx).
=> Log more fastimage errors

app/Models/Multiplayer/ScoreLink.php, tests/Models/Multiplayer/ScoreLinkTest.php
Related: https://github.com/ppy/osu-queue-score-statistics/issues/141, https://github.com/ppy/osu-web/pull/10946
We want to preserve failed scores if they come from multiplayer so that the results of the multiplayer room can be accessed in the indeterminate future. Currently this would not happen if a multiplayer score was a fail.
=> Always preserve multiplayer scores regardless of pass/fail

docker-compose.yml
Set start_interval to 1s and use default (30s) for after the service is started.
=> Change docker compose service healthcheck interval

app/Models/Comment.php
=> Fix null user id error when reporting old (imported) comments

app/Models/Solo/Score.php
=> Mark score not ranked if not passed

app/Models/Store/Order.php, app/Models/Store/OrderItem.php, app/Models/Store/Product.php, resources/views/store/products/show.blade.php
Initialize the add to cart button as disabled instead of relying on javascript to run first; on production the script that doesn't disable the button doesn't seem to trigger at the right time allowing an empty username to be added to the cart, which isn't valid. 
I can't seem to replicate the issue on dev on any browser 🤷 
The null coalesce for the username change check is a quick hotfix until better validation for the cart input is added for `extra_data` and `extra_info`
=> Hotfix adding empty username to cart

app/Jobs/EsDocument.php, app/Jobs/Notifications/BeatmapsetNotification.php, app/Jobs/RegenerateBeatmapsetCover.php, app/Jobs/RemoveBeatmapsetBestScores.php, app/Jobs/RemoveBeatmapsetSoloScores.php
Include the model id to help tell what the job is actually running on, especially for `EsDocument` (also, displayName is added when job is queued, not when it runs)
```
2024-04-15 10:23:20 App\Jobs\EsDocument (App\Models\User 475001) .......................... RUNNING
2024-04-15 10:23:20 App\Jobs\EsDocument (App\Models\User 475001) ..................... 92.40ms DONE
2024-04-15 10:24:56 App\Jobs\EsDocument (App\Models\Beatmapset 600016) .................... RUNNING
2024-04-15 10:24:56 App\Jobs\EsDocument (App\Models\Beatmapset 600016) ............... 80.64ms DONE
2024-04-15 10:26:05 App\Jobs\RemoveBeatmapsetBestScores (Beatmapset 600040) ............... RUNNING
2024-04-15 10:26:05 App\Jobs\RemoveBeatmapsetBestScores (Beatmapset 600040) .......... 93.41ms DONE
2024-04-15 10:26:05 …
```
=> Include more information in queue worker output

.env.example, config/services.php, package.json, resources/js/core-legacy/current-user-observer.coffee, resources/views/layout/metadata.blade.php, webpack.config.js, yarn.lock
We don't use it anymore and saves me the trouble of shimming the outdated types for `Sentry` in typescript
=> Remove js-side Sentry

app/Transformers/Multiplayer/RoomTransformer.php
`ScoreTransformer` isn't imported so anything calling this should have already errored.
I thought I PR'd this already 👀
=> Remove unused include from RoomTransfomer

resources/js/models/chat/message.ts
Happens if the endpoint returns before the websocket message arrives.
=> Fix chat messages not updating to replacement words

app/Models/Score/Model.php, app/Models/Solo/Score.php
It's not actually used in the json.
It's also causing additional queries during conversion for searching played beatmapset because of missing preload.
=> Skip beatmapset_id for converting to legacy score

resources/css/bem/beatmap-owner-editor.less, resources/css/bem/play-detail.less, resources/css/functions.less, resources/css/utilities.less
Create a general mixin and then apply accordingly instead of using the one from utility class which has `!important` applied to all the styles.
Conveniently lesscss has the directive to mark mixin styles as `!important`.
=> Fix ellipsis overflow mixin

app/Models/User.php
Includes but not limited to sending non-array `osu_playstyles` to account option update.
=> Fix error on setting playstyle to null

app/Http/Controllers/UsersController.php, app/Models/User.php
(probably) resolves #10556
I hope the request cost thing compensates for doing 2 country rank lookups on every user :thinking: 
the mentioned include in API docs isn't actually documented, but that's not really a new issue to this PR so I didn't fix it here.
=> Include variant statistics in user index API

app/Http/Controllers/Forum/TopicsController.php, app/Transformers/Forum/TopicCoverTransformer.php
Resolves #11226.
- incorrect cover file check
- missing topic id on relevant model
=> Fix forum topic cover handling

app/Console/Kernel.php
Cron is intended to run every day at 00:05 UTC. Looking at daily metrics, this should coincide with the tail end of the daily user peak. The five minutes is just supposed to be a bit of a safety gap to ensure subsequent rooms don't run into each other.
If required, the time can be probably shifted around (userbase nadir appears to be roughly somewhere between ~06:00 and 08:00 UTC), but if that is to happen, then the end date of the room will also need to be shifted forward 8 hours (currently set to 00:00 UTC of the next day).
Maybe this will be obvious to anyone but me, but notably, when I wanted to test this locally to check that this works, it didn't really fire for me until I did something along the lines of
```diff
diff --git a/app/Console/Kernel.php b/app/Console/Kernel.php
index …
```
=> Automatically schedule daily challenge room creation

app/Http/Controllers/Multiplayer/RoomsController.php, resources/views/docs/info.md.blade.php
RFC.
Currently old lazer clients die on these due to deserialisation woes (it can't figure out what enum value to deserialise `daily_challenge` to as it doesn't exist yet), which makes deployment of the feature a bit tricky logistically.
Since we can't fix old clients (because they're already released, and we would have to push an update either way), hide daily challenge rooms behind an `x-api-version` header check. Note that challenge rooms can still be accessed directly by ID regardless of API version, but that's fine for this case, since the client won't be doing it.
=> Do not return daily challenge rooms in `GET /rooms` endpoint if API version too low

resources/js/chat/message-group.tsx, resources/js/components/report-form.tsx, resources/js/components/report-reportable.tsx, resources/js/components/user-card-tooltip.tsx, resources/js/components/user-card.tsx, resources/js/components/user-link.tsx, resources/js/interfaces/reportable.ts, resources/lang/en/report.php
With the message grouping, only the last message can be actually reported. The report itself includes some number of previous messages as well so maybe it's fine?
Alternatively a different report button would need to be added instead.
=> Report chat message for user card on chat page

app/Exceptions/HasExtraExceptionData.php, app/Exceptions/InvalidSignatureException.php, app/Exceptions/Store/FulfillmentException.php, app/Exceptions/Store/OrderException.php, app/Exceptions/Store/PaymentProcessorException.php, app/Http/Controllers/Payments/PaypalController.php, app/Http/Controllers/Payments/ShopifyController.php, app/Http/Controllers/Payments/XsollaController.php, app/Libraries/Fulfillments/OrderFulfiller.php, app/Libraries/Payments/PaymentProcessor.php, app/Libraries/Payments/PaymentProcessorException.php, app/Libraries/Payments/PaymentSignature.php, app/Libraries/Payments/PaypalPaymentProcessor.php, app/Libraries/Payments/PaypalSignature.php, app/Libraries/Payments/ShopifySignature.php, app/Libraries/Payments/XsollaPaymentProcessor.php, app/Libraries/Payments/XsollaSignature.php, app/helpers.php, tests/Libraries/Fulfillments/SupporterTagFulfillmentTest.php, tests/Libraries/Fulfillments/UsernameChangeFulfillmentTest.php, tests/Libraries/Payments/PaymentProcessorTest.php, tests/Libraries/Payments/XsollaPaymentProcessorTest.php
These used to be reported to a now non-existent channel, so this is about getting visibility on payment processing validation errors back (because standard `ValidationException`s don't get reported to sentry).
=> Log payment validation errors to Sentry

resources/css/bem/beatmap-packs-header.less, resources/lang/en/beatmappacks.php, resources/views/packs/_header.blade.php
resolves #9218
in addition to what the issue says, the sorting already heavily steers you toward downloading later packs, so the warning is just unnecessary.
=> Remove warning to download beatmap packs from latest to earliest

resources/views/rankings/country.blade.php
Broken after the weighted performance update. It's either this or add a new column 🤔
=> Remove average performance column on country rankings page

resources/js/beatmap-discussions/discussions-state.ts
Reverts the default `pending` setting in #11294
Also, `praise` default was supposed to be for ranked maps only and I forgot qualified is `> 0` 👀 
Some feedback regarding it change:
- useful to see hypes and mapper notes by default (also doesn't show up after posting because filtered)
- seeing other already resolved issues
=> Change default filter for unranked Beatmaps to all

resources/js/profile-page/cover-editor.tsx
It will be more useful later.
Looked at the logic in Modal but just checking the start target seems enough (at least here)? 🤔
=> Prevent profile cover editor popup from closing when dragging outside

app/Libraries/Payments/PaypalPaymentProcessor.php, app/helpers.php
Or maybe should ignore everything without `invoice` field set 🤔 (which I recall wasn't done to make sure that callbacks for outgoing transactions that had them missing would explode)
=> Ignore more Paypal IPN transaction types

resources/lang/en/oauth.php, resources/views/vendor/passport/authorize.blade.php
The info is already shown on the settings page anyway.
Not sure about the design/wordings 🤷 
Related to #10588.
=> Show oauth client owner on authorisation page

app/Libraries/OAuth/RefreshTokenGrant.php
This shouldn't happen but it did ಠ_ಠ
These should be eventually cleaned up.
=> Don't fail if refresh token is missing corresponding access token

app/Models/Solo/ScoreData.php, resources/js/interfaces/solo-score-json.ts
The client explodes when the value is null, and then there's no point returning 0 total score 🤷
=> Remove total score without mods field if 0

app/Http/Controllers/AccountController.php
Meanwhile for some other params, the value is reset to null instead 👀 (well this one was as well but the column is not nullable)
=> Don't fail on setting invalid user ruleset

app/Http/Controllers/Multiplayer/Rooms/Playlist/ScoresController.php
Needed for daily challenge (without this client can't show position numbers for the user score on the leaderboard).
A second review for performance implications is probably best-advised, this monkey just fix no number showing with hammer. [I tried to ask once](https://discord.com/channels/188630481301012481/188630616286167041/1258386604754604083) but got no reply.
=> Include user score position when indexing playlist item scores

resources/css/bem/account-edit.less, resources/css/bem/beatmap-discussion.less, resources/css/bem/forum-topic-nav.less, resources/css/bem/landing-nav.less, resources/css/bem/loading-overlay.less, resources/css/bem/notification-action-button.less, resources/css/bem/osu-layout.less, resources/css/bem/profile-extra-entries.less, resources/css/bem/profile-extra-recent-infringements.less, resources/css/bem/search-result.less, resources/css/bem/store-slider.less, resources/css/bem/supporter-eyecatch.less, resources/css/spinner.less
🧹  (it'll be converted again to `""` if using prettier)
=> Unify empty css content

app/Models/Multiplayer/PlaylistItemUserHighScore.php, tests/Models/Multiplayer/UserScoreAggregateTest.php
Closes https://github.com/ppy/osu/issues/29073.
With the previous check, setting two scores with identical `total_score` would result in the relevant `multiplayer_scores_high` row for the user and playlist item having the ID of the *second* score in the `score_id` column.
This matters, because later, `UserScoreAggregate::refreshStatistics()` sets `last_score_id` as the maximum across all `PlaylistItemUserHighScore`s for a given user:
https://github.com/ppy/osu-web/blob/7400ab9a1c4d158cdca5e26f7d83d21cb6715250/app/Models/Multiplayer/UserScoreAggregate.php#L211
The other relevant piece of information is that `last_score_id` is used as a tie-breaker if the `total_score`s of two users'  aggregates in a room are equal:
https://github.com/ppy/osu-web/blob/7400ab9a1c4d158cdca5e26f7d83d21cb6715250 …
=> Fix considering playlist score as user high if total is equal to previous high

app/Models/DailyChallengeUserStats.php, app/Models/Multiplayer/Room.php, database/migrations/2024_07_26_100752_add_last_percentile_calculation_to_daily_challenge_user_stats.php, tests/Models/DailyChallengeUserStatsTest.php, tests/Models/Multiplayer/UserScoreAggregateTest.php, tests/TestCase.php
More useful in term of visibility but the percentile stats being updated later may look a bit weird...?
=> Update daily challenge streak count on play instead of at the end of the day

app/Http/Controllers/UsersController.php, app/Models/User.php, resources/views/docs/info.md.blade.php
It's always been a weird workaround.
=> Deprecate key option for Get User endpoint

app/Console/Commands/DailyChallengeCreateNext.php, app/Models/Multiplayer/Room.php
This fixes test when it runs exactly within 30 minutes before midnight (23:30 - 00:00).
I don't know if the behaviour is acceptable for live so it'll need maybe @bdach's confirmation (or anyone from client).
Alternatively I can just mock the time used during testing.
=> Set daily challenge room start time to be at the start of the day

app/Console/Commands/DailyChallengeUserStatsRecalculate.php, app/Console/Kernel.php, app/Models/DailyChallengeUserStats.php, app/Models/Multiplayer/PlaylistItem.php, tests/Models/DailyChallengeUserStatsTest.php
```
artisan daily-challenge:user-stats-recalculate --all
artisan daily-challenge:user-stats-recalculate 0 2 4 6 9
```
The query isn't exactly optimal but I think it should be fine for an adhoc operation...? 🤔
=> Add command to fix daily challenge stats

resources/js/profile-page/daily-challenge.tsx
As reported in discord. Somehow still works anyway and firefox magically fixes it in dev tools so I didn't notice it.
=> Fix missing closing bracket in daily challenge tier colour

app/Models/DailyChallengeUserStats.php, tests/Models/DailyChallengeUserStatsTest.php
As turned out the mock thing applies to Carbon, might as well check the streak as appropriate 🤔
=> Check most recent streak state when fixing stats

app/Http/Controllers/BeatmapsetsController.php, app/Models/BeatmapMirror.php, resources/lang/en/beatmapsets.php
This prevents error when all of the mirrors are disabled. It itself is usually caused by temporary routing error from monitoring process so returning main server is usually fine.
Also cleaned up stuff along the way.
=> Add download mirror fallback

resources/views/rankings/index.blade.php
It's got nothing to do with the pager.
=> Move beatmap list on ranking page below the table's pager links

phpcs.xml
The directory being called `app` broke the namespace matching.
=> Fix error running phpcs in docker

resources/js/profile-page/daily-challenge.tsx, resources/js/profile-page/detail.tsx
Currently the challenge adds other rulesets at random so make the stats visible on all rulesets. Instead hide it if there's no plays recorded.
=> Adjust daily challenge stats visibility

resources/css/bem/beatmapset-header.less
The class was originally directly applied to the search link and thus need to be limited in width so the empty space isn't clickable.
It has since become a container and the actual link has been moved.
Filling the whole width makes selecting text actually selects the respective line instead of whatever below/above it.
Resolves #11472.
=> Fix container size of beatmap title and artist

resources/js/core/user/user-preferences.ts, resources/js/interfaces/user-preferences-json.ts, tests/karma/test-current-user-json.ts
Resolves #11295... kind of.
1. (tab A) open a beatmap page
2. (tab B) open some page
3. (tab B) toggle lazer mode
4. (tab A) switch to different difficulty
The result is the scores are fetched using the new option but sorted using the old one.
This PR doesn't change the header correctly but there's currently no framework in place to do it so maybe if someone complains about it.
=> Sync user preferences when updated from a different tab

resources/views/rankings/index.blade.php
The title/content section of page header is not visible on mobile.
Resolves #11485.
=> Fix ruleset selector not shown on mobile

tests/Models/BeatmapsetRequalifyTest.php
At least until we explicitly pass the timestamp into the qualify function
=> Fix BeatmapsetRequalifyTest failing due to timing variance.

docker/development/prepare.sh
If the process stops between copying env file and generating app key, subsequent setup won't have the app key generated and stuff will break.
=> More reliable app key init

app/Libraries/Chat.php
This is a bad idea to do over web interface.
(working around sql bind parameter limit when dealing with some hundreds of thousands of user ids)
=> Allow more users for chat announcement

app/Http/Controllers/Chat/ChannelsController.php, app/Models/Chat/Channel.php, app/Transformers/Chat/ChannelTransformer.php, tests/Models/Chat/ChannelTest.php
In the meantime until a separate function for fetching users is added.
=> Don't send user ids for announcement channels

app/Libraries/User/PasswordResetData.php
A previous check in the process already allows `null` ಠ_ಠ
=> Check for null username parameter in password reset

app/Libraries/SessionVerification/State.php
I don't know where the current one came from but it seems a bit too long.
=> Reduce session verification key lifetime

app/Singletons/OsuAuthorize.php, resources/lang/en/authorization.php
The one place the message may make sense doesn't actually show it as the relevant part isn't even rendered. Otherwise it's just confusing when trying to use the api.
=> Improve chat announcement permission message

app/Models/User.php, database/factories/UserFactory.php
Some characters are encoded (like `>`) and thus may end up exceeding table column limit if repeated (30 &times; 4 is 120, the limit is 100).
The alternative would be to just skip html entity encoding altogether... That'd need to migrate current data and make sure nothing outside osu-web is using it directly from the db.
=> Adjust user current location length limit

app/Http/Controllers/ScoresController.php, app/Models/ScoreReplayStats.php, database/migrations/2024_10_04_082317_create_score_replay_stats.php, tests/Controllers/ScoresControllerTest.php
Just the counting part. Migration(?) will be done later after this one is deployed (either adhoc or some fancy command).
Related to #6412
=> Add new score replay count data

resources/css/bem/input-container.less, resources/css/bem/input-text.less, resources/css/bem/store-text.less, resources/lang/en/store.php, resources/views/store/products/show.blade.php
Some hack involving floating the label is involved 🔧
=> Update dropdown on store page

resources/css/bem/menu-image.less, resources/css/bem/menu-images.less, resources/js/components/menu-image.tsx, resources/js/components/menu-images.tsx, resources/views/home/user.blade.php
The glow is kinda intentional 👀
=> Adjust dashboard banner position

app/Models/OAuth/Token.php
Some users are trying weird things. Other alternatives include banning such users or just filling out the user ids.
=> Fix error on oauth client with no attached user

resources/css/bem/wiki-search.less
Always found it annoying that clicking the sides on wiki search bar does nothing. Matches other search bars now.
| Before | After | Beatmap listing search and global search |
| --- | --- | --- |
| <img width="245" alt="Screenshot 2024-10-18 at 10 10 01 PM" src="https://github.com/user-attachments/assets/dd82b439-d551-4a97-a21a-7b0e2cbc13e9"> | <img width="151" alt="Screenshot 2024-10-18 at 10 10 36 PM" src="https://github.com/user-attachments/assets/6e9ed8e5-1e3b-40e2-8008-46c2210f6a94"> | <img width="291" alt="Screenshot 2024-10-18 at 10 11 33 PM" src="https://github.com/user-attachments/assets/587e15d1-e3d0-47bf-95d6-034e470ba337"> |
=> Fix wiki search bar click area

app/Models/DailyChallengeUserStats.php, app/Models/Multiplayer/PlaylistItem.php, resources/lang/en/rankings.php, resources/views/rankings/daily_challenge.blade.php
=> Fix percentile related key names

app/Http/Controllers/FriendsController.php, app/Models/User.php, app/Transformers/UserCompactTransformer.php, app/Transformers/UserRelationTransformer.php
Like #7768 but rebased and with no docs.
Also requires specifying api version 20241022 or higher.
=> Return user relation json for friends listing endpoint

resources/js/models/chat/create-announcement.ts, resources/js/models/chat/message.ts, resources/js/turbolinks-overrides.coffee, resources/js/turbolinks.d.ts, resources/js/utils/seq.ts
It's been a thing since 2022 (thx safari).
=> Use native uuid generator function

SETUP.md
As I was going through setting up a local web server, I've noticed user registration does not work, and gives an error:
```
> (new App\Libraries\UserRegistration(["username" => "frenzi", "user_email" => "frenzibyte@gmail.com", "user_password" => "1234"]))->save();
Error  Call to a member function getKey() on null.
```
I was at a complete loss as to what's causing this, then I opened discord and searched in osu and came across [this](https://discord.com/channels/188630481301012481/188630616286167041/1259342156624302164). Turns out I have to perform the seeding step first so that the `default` user group becomes present for user registration to work (or so is what I can deduce from the error message, it might be something entirely different).
I expect to get things working by just reading …
=> Move user registration step in `SETUP.md` to be after database seeding

app/Http/Controllers/BlocksController.php, resources/js/components/block-button.tsx, resources/js/core/user/user-model.ts, routes/web.php, tests/api_routes.json
That the destroy/store endpoint is returning both friends and blocks feels a bit whack 🤨
Also it means three additional requests just to get full relation lists (friend, block, mapper (once added))...
Related to #10789.
=> Add user block management api

app/Http/Controllers/UsersController.php, app/Models/LegacyScoreFirst/Fruits.php, app/Models/LegacyScoreFirst/Mania.php, app/Models/LegacyScoreFirst/Model.php, app/Models/LegacyScoreFirst/Osu.php, app/Models/LegacyScoreFirst/Taiko.php, app/Models/User.php, app/Transformers/UserCompactTransformer.php
This adds one extra query but it uses existing order in the leader table instead of reordering it in the score table.
This also skips querying `scores_high` table entirely.
=> Speed up first place score query

resources/js/beatmapset-panel/index.tsx, resources/views/home/_user_beatmapset.blade.php
Probably a good QOL for users who don't know what icon is which yet.
Also matches hover feedback of these:
=> Add tooltips to more ruleset icons

app/Libraries/NotificationsBundle.php, composer.json, composer.lock
This removes extra filesort as mentioned [here](https://discord.com/channels/90072389919997952/1083320217259749376/1301366162046582887) but there doesn't seem to be any difference, at least on small queries (including the linked one).
Original query:
``
SELECT * FROM `user_notifications` WHERE `user_notifications`.`user_id` = 2387883 and `user_notifications`.`user_id` IS not NULL and `delivery` & 1 and exists (SELECT * FROM `notifications` WHERE `user_notifications`.`notification_id` = `notifications`.`id` and `notifiable_type` = 'build' and `notifiable_id` = 7629 and `name` in ('comment_new')) and `is_read` = 0 ORDER BY `id` DESC LIMIT 50
``
This pr:
``
SELECT `user_notifications`.* FROM `user_notifications` inner join `notifications` on `notifications`.`id` = …
=> Sort user notifications with existing notifications table index

app/Models/DailyChallengeUserStats.php, tests/Models/DailyChallengeUserStatsTest.php
If the last play was on start of week, the original check will always pass on the following week and then not selected anymore on the week afterwards.
Resolves #11618
- Last weekly streak: 2024-09-19
- End of the week of the weekly streak: 2024-09-25
- Next week streak start: 2024-09-26
- The latest play needed to keep streak: 2024-10-02 (end of the week)
Before:
| Check date | Query cutoff | Minimum last weekly streak | Result         |
|------------|--------------|----------------------------|----------------|
| 2024-10-02 | 2024-09-18   | 2024-09-19 ✔               | No reset ✔     |
| 2024-10-03 | 2024-09-25   | 2024-09-26 ✔               | Not queried ❌ |
After:
| Check date | Query cutoff | Minimum last weekly streak | Result      | …
=> Fix weekly streak not reset in some cases

app/Models/NewsPost.php, app/Transformers/NewsPostTransformer.php, app/helpers.php, resources/css/bem/news-post-preview.less, resources/css/bem/page-nav-fancy.less, resources/js/interfaces/news-post-json.ts, resources/js/news-index/post-item.tsx, resources/js/news-show/main.tsx, resources/views/docs/_structures/news_post.md, resources/views/home/_user_news_post_preview.blade.php
I looked into cleaning up the underlying `firstImage` in markdown processor but that was a can of worms and so I put the lid back on ﾉ(° -°ﾉ)
Resolves #11599
=> Add 2x support for news cover image

package.json, webpack.config.js, yarn.lock
Edit: apparently it was only resolving only top level modules 🤷 
For some reason after #11600 `qs` doesn't get installed if `devDependencies` are skipped even though it's listed as a dependency as other packages ?_? (also happens with `npm install --omit=dev`)
Not sure what the exact cause is atm, this is a quick fix for production builds not building...
`"~6.9.7"` is just the lowest version in the current lock file
=> Fix sub module resolution

package.json, webpack.config.js, yarn.lock
Mainly so webpack doesn't explode when running production setup and build with the notification config file existing.
Also moved the cleanup plugin to dev only.
=> Skip dev only webpack plugins on production

app/Models/LegacyMatch/Score.php, app/Models/Traits/Scoreable.php
Resolves #11591.
This recalculates the value every time but I think it's already done for legacy score rank anyway, so 🤷
=> Fix legacy match score rank value

composer.lock
symfony/symfony#50730 changed so non-object json body (like `null`) throws error.
~~laravel framework itself already handled such cases~~ but the update for sentry in getsentry/sentry-laravel#743 is also needed.
who am I kidding - it breaks laravel as well if something ever tries to also instantiate the related thing (`app()->make(\Psr\Http\Message\ServerRequestInterface::class)`).
=> Fix json decode error when sentry records request

.github/workflows/tests.yml
Their server isn't exactly the best and caching it for a day is probably fine.
=> Cache ip2asn db on GitHub Action

app/Models/UserAccountHistory.php
The permanent check already checks all rows so adding one more thing doesn't change much? 🤷 
Resolves #11590 except non-permanent tournament ban entry is not a thing at the moment.
=> Show all active account history

.env.example, app/Models/ProfileBanner.php, app/Models/TournamentBanner.php, app/Models/User.php, app/Transformers/UserCompactTransformer.php, config/osu.php, database/migrations/2024_11_06_074123_create_tournament_banners.php
All the environments
```bash
TOURNAMENT_BANNER_CURRENT_ID=
TOURNAMENT_BANNER_CURRENT_PREFIX=
TOURNAMENT_BANNER_PREVIOUS_ID=
TOURNAMENT_BANNER_PREVIOUS_PREFIX=
TOURNAMENT_BANNER_PREVIOUS_WINNER_ID=
```
are moved to `tournament_banners` table. Should be relatively straightforward.
=> Move active tournament banner data to table

resources/views/vendor/passport/authorize.blade.php
It's controlled by oauth library and it's easier just disabling it at the form (as opposed to returning the redirect script).
Resolves #11658
=> Disable turbo on oauth form buttons

app/Http/Controllers/RankingController.php
So I did miss at least one place when updating to laravel builtin function <_<
This is a rare edge case and must be manually typed... I think.
=> Fix parsing page parameter of ranking page

tests/TestCase.php
I don't think there's any specific reason they shouldn't be chainable. Most of the use is immediately followed by the related request 🤔
=> Make test user session/token helpers chainable

app/Http/Controllers/Multiplayer/RoomsController.php
While in the lounge, the client polls using `index()` which returns a compact model that in particular excludes the playlist. After the room is joined the playlist becomes important for the obvious reason that the user should be able to start playing, but also for the less-obvious reason that the client expects the playlist to be populated in order to preselect the first available item.
Rather than adding a special condition for the client, it seems to make more sense to return the complete model here and potentially remove the `show()` API request. As far as I can tell the only remaining use (as far as the client's concerned) is to update the recent participants list, but it's otherwise quite wasteful and polls every 5 seconds.  
Beyond that, I believe playlists would be better served by …
=> Return populated room object when joined

tests/TestCase.php
There's this test but it's testing test helper so I'm not sure if it makes sense testing it? 🤔 Can jam it somewhere... (where?)
```php
public function testWat()
{
$user = User::factory()->create();
$this->actAsScopedUser($user, ['public']);
$this->assertSame(\Auth::user()->getKey(), $user->getKey());
$this->actAsScopedUser(null, ['public']);
$this->assertNull(\Auth::user());
}
```
=> Fix acting as null user not reset existing user in test

docker-compose.yml
The native password will be gone in 9.0.
As it turned out there's implementation of `caching_sha2_password` on mariadb but just for the client. And depending on the distro, one may need to install additional package to get the relevant plugin to be able to connect to the database (`mariadb-connector-c` on alpine linux).
=> Use default mysql authentication plugin

resources/css/bem/input-container.less
The error highlight should still remain active when the field is focused. Left the hover highlight alone since it seems logical it should follow what's being hovered but not yet focused? 🤔
=> Don't override InputContainer error colour when focused

app/Models/Multiplayer/Room.php, app/Transformers/Multiplayer/RoomTransformer.php, database/migrations/2024_11_22_092704_add_status_to_multiplayer_rooms.php
Enum to support possible future expansion.
This doesn't contain the full array the client would normally use `( open, open_private, playing, ended )` because the "ended" state is difficult to handle at osu!web's end for playlist rooms.
So `idle` now represents `( open, open_private, ended )` and the client will figure out it from there.
=> Add `status` to `multiplayer_rooms`

resources/js/core/react-turbolinks.ts
Missed this when turning the `loadScripts` async.
=> Fix timing of calling boot on initial page load

app/helpers.php, package.json, resources/js/setup-turbo.ts, yarn.lock
The previous fix doesn't quite work as turbo just ends up doing a browser native visit and breaks on form action due to 200 status.
=> Fix turbo redirect

resources/js/profile-page/daily-challenge.tsx
See conversation in https://github.com/ppy/osu-wiki/pull/12392#discussion_r1861519201
Color now changes when you _reach_ the expected threshold, not surpass it.
`Math.floor` in tierStylePlaycount is to ensure consistent results given javascript's BS with floats, and to ensure consistent behavior w/ the client (see <https://github.com/ppy/osu/pull/30906>)
=> Adjust daily challenge tier thresholds to match expectations

app/Http/Controllers/Multiplayer/RoomsController.php
Doing another `load` overrides existing loaded relations.
=> Fix beatmapset preload on room

app/Models/Multiplayer/Room.php, resources/lang/en/multiplayer.php
Could've used the length validator but the model doesn't have it setup and there's a lot of other existing checks done in a different way.
=> Limit room name length to match database

package.json, resources/css/bem/circular-progress.less, resources/css/bem/loading-overlay.less, resources/css/bem/page-contents.less, resources/css/bem/profile-hue-selector.less, resources/css/bem/store-slider.less, resources/css/bem/supporter-icon.less, resources/css/bem/user-action-button.less, resources/css/jquery-ui/slider.less, yarn.lock
I needed (maybe) css native `min()` somewhere else but it exploded on current version without a literal string workaround ಠ_ಠ
Tested by diffing each branch's output css.
There are a few existing `~"/"` and other workarounds which no longer needed but that's for another day...
=> Update to latest less css

resources/css/bem/profile-info.less
I wonder if the image itself should be resized to 240x120 instead of 256x128 (or the avatar area should be of that size instead, which also integer scaled with current user avatar) ಠ_ಠ
=> Fix flag size on team page

resources/views/layout/metadata.blade.php
Resolves #11707. Or maybe works around? There's currently no way to change js locale without full reload.
=> Fix switching locale doesn't set js locale correctly

resources/css/bem/profile-info.less, resources/js/profile-page/cover.tsx
It was originally to remove `__flag-flag` wrapper but ended up removing the `--icon-*` variables entirely and rely on font-size instead.
=> Use relative sizing for icons and flags on profile page cover

app/Jobs/Notifications/BeatmapOwnerChange.php
Something like this? 🤔 
I suppose it should only notify the delta but there's no such data at the moment and this is probably better than nothing?
=> Notify all owners on beatmap owner change

resources/lang/en/layout.php, resources/views/layout/_popup_user.blade.php
Seems useful? Dunno if "My Team" title makes sense here.
=> Add link to own team from user popup menu

resources/views/admin/contests/show.blade.php
Annoyingly there's no simple way to disable form-based download globally ಠ_ಠ
Resolves #11745
=> Fix contest admin download

resources/js/profile-page/main.tsx
Not quite sure what's happening here ಠ_ಠ
=> Fix profile page reorder not working without full reload

resources/views/teams/show.blade.php
I'm not quite sure what that was for ಠ_ಠ
I suspect it was for react components - which is how I initially implemented it, and probably copied from something else - except it's pointless after the _discovery_ of `display: contents`.
=> Remove redundant container

app/Singletons/OsuAuthorize.php, tests/Controllers/Chat/ChannelsControllerTest.php
Mainly to disallow people from rejoining room after they're kicked and the room password changed. It also makes more sense because it should have same check as joining multiplayer room instead of generic chat room.
The downside is there's currently no way to join multiplayer room through other than client api but apparently we don't really want to support that at the moment? 🤷 @peppy
=> Require multiplayer api to join multiplayer room

app/Http/Controllers/TeamsController.php, app/Singletons/OsuAuthorize.php, resources/css/bem-index.less, resources/css/bem/profile-detail-bar.less, resources/css/bem/team-action-button.less, resources/lang/en/authorization.php, resources/lang/en/teams.php, resources/views/teams/show.blade.php, routes/web.php
Apart of the message that needs fixing, I wonder if the route should have team id in it... (there's also question of if it's worth adding an OsuAuthorize check for this)
=> Add leave team button

resources/js/globals.d.ts, resources/js/legacy-api-key/form.tsx, resources/js/oauth/new-client.tsx, tsconfig.json, webpack.config.js
Alternative to #11726. I think those are the minimum set of explicit types config required.
Renamed the variable to reduce confusion as it's a preprocessing done through webpack and has nothing to do with node's `process.env`.
This also fixes typing for `setTimeout` and stuff without having to use `window.setTimeout`. I'm not updating them here though.
=> Explicit typescript types and rename webpack define const

app/Http/Controllers/InterOp/BeatmapsetsController.php, app/Models/Event.php, routes/web.php
RFC.
This is needed for new BSS. osu-web-10 originally would write rows to `osu_events` on new beatmap, on beatmap update, and on revive. I would normally just reimplement that in https://github.com/ppy/osu-server-beatmap-submission and call it a day, but the logic is annoying because it contains stuff like stripping tags and other html garbage that I really don't want to touch, and that web already has implemented, so I figured that I can just parasite off of the existing LIO calls that look vaguely relevant to do the job (and add another one for update I guess since that one didn't exist).
In order to avoid old BSS double-writing these event rows I made this conditional on `x-api-version` header. This is probably a war crime, but I figured I probably should not try and invent anything …
=> Add submission-relevant events to database via LIO endpoints

database/migrations/2025_01_06_000000_create_osu_logins.php
For use in https://github.com/ppy/osu-server-spectator/pull/253.
=> Add `osu_logins` migration

docker/development/prepare.sh
Also fixed bug of github token being echoed to console if set.
Note that the `APP_ENV` in `.env.dusk.local` isn't actually used when using docker compose as it overrides the value with the one in `.env`.
=> Fix env file setup for dusk.local

app/Http/Controllers/Multiplayer/Rooms/Playlist/ScoresController.php, app/Http/Controllers/ScoreTokensController.php, app/Models/Multiplayer/Room.php, app/Models/ScoreToken.php, database/factories/ScoreTokenFactory.php, tests/Controllers/Multiplayer/Rooms/Playlist/ScoresControllerTest.php, tests/Controllers/ScoreTokensControllerTest.php, tests/Models/Multiplayer/RoomTest.php, tests/Models/Multiplayer/UserScoreAggregateTest.php, tests/TestCase.php
Combining hash and ruleset validation in the token model itself. build id stays as is because it's quite a bit more involved.
The way `beatmap_hash` is passed and validated is rather questionable 👀
=> Rework score token validation

docker/development/run.sh
This change makes octane commands wait a bit for `manifest.json` to exist if it's missing.
The first run of `bin/docker_dev.sh` causes both `nginx` and `php-dusk` fail.
php:
```
Exception
The manifest does not exist.
at app/Singletons/AssetsManifest.php:22
18▕     {
19▕         $manifestPath = public_path('assets/manifest.json');
20▕
21▕         if (!file_exists($manifestPath)) {
➜ 22▕             throw new Exception('The manifest does not exist.');
23▕         }
24▕
25▕         $this->manifest = json_decode(file_get_contents($manifestPath), true);
26▕     }
1   app/Providers/AppServiceProvider.php:96
App\Singletons\AssetsManifest::__construct()
```
php-dusk:
```
php-dusk exited with code 157
```
nginx:
```
[emerg] host not found in upstream "php-dusk" in /etc/nginx/conf.d/default.conf:53 …
```
=> Fix first-time run of `docker_dev.sh`

app/Http/Controllers/TeamsController.php, app/Models/Team.php, resources/lang/en/teams.php, resources/views/teams/show.blade.php, routes/web.php, tests/Models/TeamTest.php
This PR should contain all the things involved in deleting a team 🤔 (well, in the sense of whatever implemented at the moment which doesn't include pending team application because the model doesn't exist yet and the team chat channel)
Which currently just involves deleting the team itself and related files and member entries ┐(ﾟヮﾟ)┌
Extra things I can think of:
1. requiring the team to be empty first (but why)
2. notifying the members
=> Add disband team button

app/Http/Controllers/Users/LookupController.php, app/Libraries/Beatmapset/ChangeBeatmapOwners.php, app/Models/User.php, resources/js/beatmap-discussions/beatmap-owner-editor.tsx, resources/js/chat/create-announcement.tsx, resources/js/components/username-input.tsx, resources/js/store/store-supporter-tag.tsx, resources/js/utils/user.ts, tests/Libraries/Beatmapset/ChangeBeatmapOwnersTest.php
closes #11752
Also changes Chat Announcements and supporter tag gift lookups from the UI to exclude those groups, but I didn't change the actual check where those are applied yet.
=> Exclude bot and no profile special groups from being set as guest mappers

resources/css/bem/daily-challenge.less, resources/js/profile-page/daily-challenge.tsx
Implements https://github.com/ppy/osu-web/issues/11597 for the website.
=> Add completion marker to daily challenge profile counter

app/Models/User.php, app/Models/UsernameChangeHistory.php, database/factories/UsernameChangeHistoryFactory.php, tests/Models/UserTest.php
closes #11790
The new logic is the price goes up 1 tier for every paid change, and down 1 tier for every year since the last paid change, to a minimum of 1.
=> Adjust username change cost

app/Libraries/OsuWiki.php
They changed their 404 message recently. And then I noticed the status code is in the exception so it's probably better to just use it.
=> Fix handling of github 404 error

app/Models/UserProfileCustomization.php
`array_intersect` inside the repair function explodes if given null.
=> Fix setting null profile extras order

app/Models/User.php, tests/Models/UserTest.php
Simpler username change cost instead of the one originally in #11809.
It now just uses a window of the last 3 years. If a previous name change exists, the minimum cost is `8`, regardless if there was 0 or 1 changes in the last 3 years.
=> Simpler username cost reduction

resources/views/docs/info.md.blade.php
[osu-api-v2-js](https://github.com/TTTaevas/osu-api-v2-js) is a package I've ended up making after interacting quite a bit with osu!'s api
It is available on [npm](https://www.npmjs.com/package/osu-api-v2-js), I use it for some other project of mine and apparently, [some people have been using it for their own projects](https://github.com/TTTaevas/osu-api-v2-js/network/dependents?dependent_type=REPOSITORY)
So I think it would be a good idea to add it to the list of wrappers that is featured in the api's documentation
=> Add "osu-api-v2-js" to the list of API wrappers

resources/js/docs/sidebar-toggle.ts
I wonder if selecting anything in the navigation should also close it instead of having to close manually.
=> Fix docs nav button resetting scroll position

app/Libraries/Payments/PaymentProcessor.php, app/Libraries/Payments/PaypalPaymentProcessor.php, app/Models/Store/Order.php, resources/lang/en/store.php, resources/views/store/orders/_status.blade.php
There are a bunch of `Order`s that are in the eCheck pending state when the eChecks have been rejected already.
This adds extra handling to the IPN to mark the eCheck as rejected (`payment_status=Denied` `payment_type=echeck`).
=> Update echeck status when rejected by Paypal

database/seeders/ModelSeeders/ForumSeeder.php
This ensures that https://github.com/ppy/osu-web/pull/11706 can work on local setups.
A similar forum existed prior to https://github.com/ppy/osu-web/pull/8641 and was excised probably because it was useless at the time.
=> Create beatmap descriptions forum in forum seeder

app/Models/Solo/Score.php, tests/Models/DailyChallengeUserStatsTest.php
I think this may be confusing if client is still sending such scores? Note that this applies to solo scores as well.
Reference: https://github.com/ppy/osu/issues/31808#issuecomment-2639579715
=> Reject submission of score 0

resources/views/layout/_page_header_v4.blade.php
Confusing me for a while trying to figure why things move around.
This is just the first problem though. The other one being normal weight text can be wider than bolded which means things still move when switching weight 🥲
=> Add missing attribute quote

app/Http/Controllers/TeamsController.php, resources/css/bem/btn-circle.less, resources/css/bem/fake-bold.less, resources/css/bem/header-nav-v4.less, resources/lang/en/page_title.php, resources/lang/en/teams.php, resources/views/layout/_page_header_v4.blade.php, resources/views/teams/edit.blade.php, resources/views/teams/members/index.blade.php, resources/views/teams/show.blade.php
Also remove redundant links (header image links for team leader, "back" button on member list and settings page).
=> Add header navigation links on team page

app/Models/Multiplayer/ScoreLink.php
I considered two paths here - the first is to list every allowed mod in `allowed_mods`, and the second is to make freestyle act as a bypass. Listing every mod gets messy and wastes DB space (every playlist item is retained forever), so I've gone down the second path.
A future consideration may be that freemods is usually an all-or-nothing selection. We may want to change `freestyle` into a flags enum `{ ruleset | mods | beatmap }` and invert `allowed_mods` as `disallowed_mods`.
If you (@nanaya, @peppy) believe that's better to be done now, I can look down that path, but I'm hoping it's just as easily done in a future change.
=> Allow user mods in multiplayer freestyle

app/Http/Controllers/TeamsController.php, app/helpers.php, resources/css/bem-index.less, resources/css/bem/team-members-leaderboard-item.less, resources/css/bem/team-members-leaderboard.less, resources/lang/en/beatmaps.php, resources/lang/en/page_title.php, resources/lang/en/teams.php, resources/views/teams/_members_leaderboard.blade.php, resources/views/teams/leaderboard.blade.php, routes/web.php
I think this is pretty close to the design?
Added a lone `info` link in the header to put the ruleset selector on (mainly for mobile). Will add link to member listing and settings page for admin later (and then remove the "back" link in respective pages).
depends on
=> Team member leaderboard

app/Http/Controllers/Forum/ForumsController.php
Closes #11866 
Fixes two issues:
- `last_topics` being accidentally left in the docs for `Get Forum Listing`
- The `Forum` hyperlink going to the Forum endpoint header instead of object header
=> Fix docs for forum endpoints

app/Exceptions/ImageProcessorException.php, app/Http/Controllers/AccountController.php, app/Http/Controllers/Forum/ForumCoversController.php, app/Http/Controllers/Forum/TopicCoversController.php
Removing the same handler... which is already what the default handler does.
Also fixes error 500 when thrown somewhere else currently not having explicit handler like team settings.
=> Add general handler for image processor exception

app/Jobs/Notifications/TeamApplicationBase.php
There's no settings for it and it's probably fine with just push notification.
=>  Remove mail notification for team join/reject

resources/js/chat/chat-state-store.ts
Fixes the case where after chat and a channel was loaded and then chat was navigated away from, messages sent to that channel, would not be loaded when navigating back to that channel.
Basically, messages sent to a previously loaded channel, during the period chat is not the active page, would not be loaded. (This becomes more obvious with the upcoming Team chat link)
=> Fix chat channel not displaying some new messages

app/Models/Team.php
Flag is twice the avatar size. Header... just randomly picked 🤔 
Profile cover should probably also be limited to 4MB instead of the current one...
=> Add maximum file size for team flag/header

app/Libraries/ImageProcessor.php
For example, instead of 1200x450 image stored as is for something that's 2000x500, it's cropped to 1200x300.
=> Enforce specified aspect ratio even on smaller image

resources/js/components/changelog-entry.coffee
Also link to osu! profile page instead of github. This kinda removes direct link to the user's github but it's still visible from the PR link so maybe it's fine...?
Resolves #11935.
=> Display osu! username for changelog entry user link

app/Http/Controllers/Payments/PaypalController.php, app/Http/Controllers/Payments/ShopifyController.php, app/Libraries/OrderCheckout.php, app/Libraries/Payments/PaymentProcessor.php, app/Models/Store/Order.php, database/migrations/2025_04_06_000001_add_shopify_url_to_store_orders.php, resources/js/store.ts, resources/views/store/orders/index.blade.php
Separated to isolate the non-sdk related changes.
Draft because the Shopify dev environment doesn't work with the deprecated shopify sdk at the moment.
=> Update Shopify orders with more details

app/Models/BeatmapDiscussion.php
It seems like this is the only missing null check.
Resolves [this sentry thing](<https://sentry.ppy.sh/organizations/ppy/issues/74976>).
=> Fix error when listing event of deleted beatmapset

resources/js/stores/beatmapset-discussions-show-store.ts
If there's discussion on the general section but none on any specific beatmaps, the store's `beatmaps` property ended up empty and crashes on discussions-state:402 (finding current beatmap id).
- deleted beatmapset
- deleted beatmaps (all of them)
- no discussion on any specific beatmaps
- there's discussion on general all section (not sure if actually needed to trigger the error)
=> Fix discussion page error with no visible beatmap

Dockerfile.development
It was previously dependency of chromium-driver but not anymore in 134 (or at least 133.0.6943.141-2).
=> Specify chromium package for install

app/Console/Commands/EsIndexDocuments.php, app/Console/Commands/EsIndexWiki.php, app/Models/Traits/Es/BaseDbIndexable.php, app/Models/Wiki/Page.php
The new default stdout logging broke the progress bar. That said, there's no obvious way to resume anyway so it's barely useful.
=> Fix es document reindex output

app/Http/Controllers/BeatmapsController.php, app/Libraries/Search/ScoreSearch.php, app/Libraries/Search/ScoreSearchParams.php, resources/js/beatmapsets-show/scoreboard/controller.ts, resources/js/beatmapsets-show/scoreboard/scoreboard-type.ts, resources/js/beatmapsets-show/scoreboard/tab.tsx, resources/lang/en/beatmapsets.php
=> Add per-beatmap team ranking

resources/css/bem/profile-extra-recent-infringements.less, resources/js/profile-page/account-standing.tsx
The space got removed during mass css update which changed all `" "` to `""`.
Changed it to add space from react side instead as it seems simpler.
=> Add space between note message and user

app/Notifications/UserReportNotification.php, composer.lock
Either this or completely migrate to the new "block api". Although I don't know if it'd even work with discord's slack bridge 🤷 
Or look into actual discord notification library if exists...
-  [x] depends on #12022
=> Update slack (discord) notification library

app/Libraries/Search/BeatmapsetQueryParser.php, resources/js/beatmapsets-show/header.tsx, resources/js/beatmapsets-show/info.tsx, resources/js/utils/beatmapset-helper.ts, tests/Libraries/Search/BeatmapsetQueryParserTest.php
mm regexp. This disallows `artist="something "weird""`; inner quotes must be escaped `\"`.
The behaviour for `tag="hello world"aa` is a bit weird ┐( ･_･)┌
=> Fix parsing multiple quoted search options

app/Http/Controllers/RankingController.php, database/migrations/2025_03_18_065831_add_country_ranked_score_index_to_stats_tables.php, resources/views/rankings/score.blade.php
The final goal is to allow same filters between performance and score sorting option just like on team ranking page (and reducing number of menu items). The index is similar to the one used for performance so performance characteristics should be the same.
The columns are also added for variant statistics but the process for updating it isn't in place (yet?) so it's still one step short from being able to have sort buttons.
Migration entry is `2025_03_18_065831_add_country_ranked_score_index_to_stats_tables`.
=> Add country filter for score ranking

app/Models/User.php, tests/Models/UserTest.php
Use a known fixed number instead of  `while < $now`
=> Fix testUsernameChangeCostWindow setup

app/Http/Controllers/Payments/XsollaController.php
Leaves the order showing the more accurate `confirmation pending` message instead of the `preparing/paid` message after being redirected by the Paystation widget
=> Show more accurate order state message after xsolla redirect

resources/css/bem/store-supporter-tag.less
It's kinda silly isn't it.
1.5&times; seems like a fine width especially considering some cards now can use the additional width.
=> Fix user card length on supporter store page

app/Transformers/TagTransformer.php
Follow-up from https://github.com/ppy/osu-web/pull/12059
The client uses `GET /api/v2/tags` to retrieve all possible tags, caches the result of that for the entire gameplay session, and then uses that cached result to display a list of all possible tags to choose from on the appropriate voting control.
Without this change, it was not possible to determine whether a user tag is specific to a ruleset or not via the aforementioned API endpoint.
=> Return user tag ruleset ID when listing all tags

app/Libraries/UsernameValidation.php
Carbon 3's `diff()->days` is currently broken (briannesbitt/Carbon#3018). It should've only affected the display, not actual availability.
=> Fix username availability time display

tests/Browser/SanityTest.php
The variable isn't actually used in the function...
=> Better test dataset entry name

tests/Browser/LoginTest.php
Sometimes the popup takes a while to load and fails logout test.
=> Fix dusk failing logout test

app/Http/Controllers/Multiplayer/RoomsController.php
According to the documentation, comment and the discussion in this pull request #11240 I think we can remove the api version check in the `/rooms` endpoint.
=> Remove temporary apiVersion check in /rooms endpoint

resources/views/docs/_structures/user.md
`nominated_beatmapset_count` is one of the "beatmapset_count" properties that is returned through [Get User](https://osu.ppy.sh/docs/#get-user) but it's the only one that wasn't actually documented
This PR adds it to the list where it belongs, the same list as `ranked_beatmapset_count` and the such
=> Add `nominated_beatmapset_count` to API docs

database/migrations/2025_04_17_113658_create_multiplayer_room_events_table.php
The goal of this table is to power display of multiplayer match history for lazer rooms, e.g. https://github.com/ppy/osu-web/issues/10455.
If you squint a bit, you'll notice that the table structure is *extremely* similar to `osu_mp.events`, but to spell things out:
- `event_id` (PK): Self-explanatory.
- `room_id` (FK referencing `multiplayer_rooms`): Self-explanatory.
- `event_type`: Self-explanatory. Appears to cover all of the same types of events that the old table does, plus `game_aborted` which the tournament people asked for. Maybe there's room for future expansion, but for now I don't see anything else that may need logging here.
- `playlist_item_id` (FK referencing `multiplayer_playlist_items`, optional): Valid if `event_type` is `game_{started,aborted}`. Points at the game in …
=> Add database table for storing lazer multiplayer room events

app/Http/Controllers/Teams/ApplicationsController.php, app/Jobs/Notifications/BroadcastNotificationBase.php, app/Jobs/Notifications/TeamApplicationStore.php, app/Models/Notification.php, app/Models/TeamApplication.php, database/migrations/2025_04_22_121439_add_notification_id_to_team_applications.php, resources/js/notification-maps/category.ts, resources/js/notification-maps/icons.ts, resources/js/notification-maps/message.ts, resources/js/notification-maps/url.ts, resources/lang/en/notifications.php, tests/Controllers/Teams/ApplicationsControllerTest.php
And delete if it cancelled accordingly... which makes sense I guess? 🤔 
<del>(and I think it revealed a bug in that deleting notifications doesn't update the count correctly on the frontend)</del> looks like it just needs a very specific format of identity json.
Resolves #11907.
=> Send notification on new team join requests

app/Singletons/Mods.php
This matches how Nightcore scores show on Double Time leaderboards.
The reason this one-liner achieves that is
https://github.com/ppy/osu-web/blob/ba50432cce23fa520cebf22d1c60a9f1295608fe/app/Libraries/Search/ScoreSearch.php#L171-L174
`IMPLIED_MODS` looks to also be used in some 'legacy' places but as far as I can tell none of them should fall over from this and some don't even look used.
Addresses https://github.com/ppy/osu/discussions/33214.
=> Show Daycore scores on Half Time leaderboards

app/Models/Multiplayer/PlaylistItem.php, app/Transformers/Multiplayer/PlaylistItemTransformer.php, resources/js/interfaces/legacy-match-event-json.ts, resources/js/interfaces/legacy-match-game-json.ts, resources/js/interfaces/legacy-match-json.ts, resources/js/interfaces/playlist-item-json.ts
- nullable using actual null instead of optional (undefined)
- use explicit json time function to cast played_at
- add create time to playlist item transformer (to match legacy game start_time)
- remove a few outdated todos
- legacy match score is now based on new format
- I don't think we'll change the mods to use the new format
- conversion will be done frontend side as needed
- fix incorrect playlist item mods related typing
=> Clean up multiplayer related ts interfaces

app/Http/Controllers/BeatmapsetsController.php
As needed by the client. This should apply to `/beatmapsets/{id}` and `/beatmapsets/lookup` endpoints.
Might as well mark this as resolves #12016.
=> Add per-beatmap user playcount to beatmapset detail response

resources/js/profile-page/stats.tsx, resources/lang/en/users.php
Resolves #2780.
Opted for flooring as it looks better alongside other statistics in my opinion, but displaying up to 2 decimals would probably also work. Happy with either.
=> Add hits per play statistic to profile page

app/Http/Controllers/ScorePinsController.php, routes/web.php, tests/api_routes.json
closes #12198
pin `PUT /api/v2/score-pins/{score_id}`
unpin `DELETE /api/v2/score-pins/{score_id} `
move pin position `POST /api/v2/score-pins/{score_id}/reorder` with `after_score_id` **or** `before_score_id` as body params
=> Add API endpoint for pinning scores

app/Models/Score/Best/Model.php, tests/Models/Score/Best/ModelTest.php
It can't be blindly applied due to qualified maps no longer increment the count.
It's also wrong anyway because it doesn't account solo/new scores.
Reference: ppy/osu-infrastructure#32
=> Remove incorrect user rank count adjustment logic

resources/js/core/user/user-model.ts
The `.splice` should check the existence (non -1 index) beforehand otherwise it'll delete the wrong (last) item.
Resolves #12213 (it's a bit confusing to read)
=> Fix incorrect end state on user relation change

app/Models/Build.php, app/Models/UpdateStream.php, database/migrations/2025_06_13_095407_add_default_allow_bancho_to_streams.php, tests/Models/BuildTest.php
Per-stream option `default_allow_bancho`. Mainly for web so its builds don't create history entry in `build_propagation_histories`.
Although I wonder if it should be `default_build_attributes` instead...?
=> Add option to disable bancho when creating build from github

app/Models/Multiplayer/Room.php
There have been occasional errors relating to this. I wonder if this should be in the `search` function itself...
=> Filter out playlists with nonexistent beatmaps

app/Models/Build.php, app/Models/Repository.php, app/Models/UpdateStream.php, database/migrations/2025_06_16_080509_add_private_to_builds.php, database/migrations/2025_06_16_115140_add_parent_id_to_streams.php
Changelog entry and update stream are supposed to be connected through a different table, `repository_update_stream` but never implemented. The `stream_id` in `repositories` is only to specify the default stream when there's no stream name in the tag (`1111-streamname`).
- `repository_update_stream` needs to be filled in with existing repository/stream and also tachyon
- existing changelog entries (that's linked to tachyon related repositories) need to be linked with a tachyon build entry otherwise next tachyon release build will link all of them
- the build will need `private` flag enabled (new column) as it'll have like thousands of changelog entries
- or maybe not, just set the tachyon stream's parent to lazer (new column `streams.parent_id`)
=> Improve support for multiple update streams on changelog entries

app/Http/Controllers/Multiplayer/RoomsController.php, resources/css/bem/mp-history-game.less, resources/css/bem/mp-history-player-score.less, resources/js/entrypoints/multiplayer-room-events.tsx, resources/js/legacy-match/content.tsx, resources/js/legacy-match/game-header.tsx, resources/js/legacy-match/index.tsx, resources/js/legacy-match/score.tsx, resources/js/multiplayer-room-events/index.tsx, resources/lang/en/matches.php, resources/lang/en/multiplayer.php, resources/lang/en/page_title.php, resources/views/multiplayer/rooms/events.blade.php, resources/views/multiplayer/rooms/show.blade.php, routes/web.php
🤷 
Resolves the realtime part of #10455. I thought there's request for similar thing but for playlist but I couldn't find it.
<del>I think the main component can use a bit more code sharing with the legacy one but it'll be a bit involved and slightly annoying to type so maybe later if I feel like it when rebasing and stuff.</del> Done, but the components should probably be moved to `components` (maybe later because I don't want to deal with renames while keeping track of history here)
depends on:
=> Add realtime multiplayer event history page

app/Transformers/Multiplayer/PlaylistItemTransformer.php, resources/js/legacy-match/content.tsx
Maybe? ┐(･_･)┌
Not quite sure how it happened but it'll be either this or retroactively adding the past event which probably isn't even possible due to id-based sorting
=> Attempt to render game detail with no start event

resources/views/home/_user_beatmapset.blade.php
Daily challenge beatmaps on the dashboard now link to the daily challenge rankings page (e.g., /rankings/daily-challenge/2025-06-26) instead of the beatmapset.
Fixes #12226
=> Link daily challenge card on dashboard to daily challenge ranking page

app/Models/Beatmap.php, database/migrations/2025_06_27_071031_add_osu_file_version_to_beatmaps.php
See context in https://discord.com/channels/90072389919997952/1327149041511043134/1387774287909359629.
As I understand it this already exists in production, so production database will likely require some jiggling so that this migration doesn't attempt to run and utterly fail to do so next deploy.
=> Add migration to add `osu_file_version` column to `osu_beatmaps` table

resources/css/bem/supporter-status.less
Mainly when there's supporter tag purchases, the image container gets pushed to less than its specified width.
Also adjusted the background sizing itself so it should always be rendered in full.
=> Fix pippi in supporter page being occasionally cropped

resources/js/contest-voting/base-entry-list.coffee, resources/js/entrypoints/contest-voting.coffee
closes #11854
Also persists the show voted only flag.
Also discovered a bug if show voted only is enabled and removing a vote through the gallery view but that's not being fixed here.
~~Yes, it's saving more state than needed because it's easier than digging for the specific properties~~
=> Restore voted state on contest entry when navigating through history

app/Http/Controllers/HomeController.php
It's rendered using choice translator which does its own formatting. It's fine up to three digit numeral and then explodes once the thousand separator is included.
=> Fix incorrect early number formatting

app/Singletons/OsuAuthorize.php, database/factories/Forum/ForumFactory.php, database/factories/Forum/TopicFactory.php, resources/lang/en/authorization.php, tests/Controllers/Forum/PostsControllerTest.php, tests/Controllers/Forum/TopicsControllerTest.php
As discussed internally, you shouldn't be able to update the title of a forum topic if you can't post to it.
Also consolidate some tests and add a few more checks.
=> Apply phpbb acl check to editing Topic title and posts

app/Libraries/SessionVerification/Controller.php, app/Libraries/SessionVerification/Helper.php, app/Libraries/SessionVerification/MailState.php, tests/Browser/SanityTest.php, tests/Libraries/SessionVerification/ControllerTest.php
Preparing for a different `State` class 😄 
Things may explode when php tries to deserialise existing class...? I guess I can create a blank class inheriting the new class name but not sure if worth it.
=> Update class name for verification mail state

app/Http/Controllers/Controller.php, app/Http/Controllers/SessionsController.php
I don't think there's option for that on the frontend anymore? Or ever?
And actually enabling this option on login adds a 400 bytes of cookies thanks to how efficient laravel's cookies are.
=> Remove remember login option

app/Http/Controllers/ScoresController.php, tests/Controllers/ScoresControllerTest.php
The test was missing required header so it has been testing download with invalid referer instead.
I updated the name for this single one to DownloadLegacy but I wonder if I should've kept it the slightly wrong name since that's how the rest of the tests as well...
=> Fix error on legacy score download with invalid ruleset

tests/Browser/LoginTest.php
I think this works...? Should probably extract it somewhere but I'm inlining it for now for testing purpose.
And maybe just doing the reset every time in the `setUp` could also work...? Instead of the current cookie reset.
<sub>wouldn't it be funny if the test fails right in this pr</sub>
=> Add retry logic to the commonly failing dusk test

resources/css/bem/mod.less
Probably isn't going to last long before replaced by new mod icons but it's simple enough to check 🤷 
And using fa's svg in general could potentially result in better icon alignment in a few other places?
Before
After
=> Use svg fontawesome for mod icons

app/Models/Multiplayer/Room.php, app/Transformers/Multiplayer/RoomTransformer.php, database/migrations/2025_08_21_103748_add_pinned_description_to_multiplayer_rooms.php
- `pinned` is specifically for https://github.com/ppy/osu/issues/34537.
- I went for the flag rather than a new category of room because categories have stuff like filtering attached to them that I think doesn't make sense if a separate "pinned" room category was to be created.
- I expect that going forward all spotlights / FA rooms should also specify `pinned = true`. This would affect / require updating ASS automation (cc @peppy).
- Pinned rooms will be prioritised order-wise when listing rooms using the default `created` sort. This affects both the room listing endpoint (`GET /api/v2/rooms`), as well as the website's user playlist listing (`/users/{user_id}/playlists`). The second is arguable and could be considered as a side effect but I think it's probably fine and not worth creating …
=> Add pinned flag & description field to multiplayer rooms

app/Libraries/Search/BeatmapsetSearch.php
Works around the per query term limit of `65536`. The other option is to increase `max_terms_count` on the index
=> Fix Beatmap search played filter sometimes not working

app/Http/Controllers/Forum/TopicsController.php, app/Models/OAuth/Client.php, app/Models/OAuth/Token.php, app/Models/User.php, app/Providers/AuthServiceProvider.php, app/Singletons/OsuAuthorize.php, database/factories/Forum/ForumFactory.php, database/factories/UserFactory.php, resources/lang/en/api.php, resources/lang/en/model_validation/token.php, resources/views/docs/auth.blade.php, routes/web.php, tests/Controllers/Chat/ChannelsControllerTest.php, tests/Controllers/Forum/PostsControllerTest.php, tests/Controllers/Forum/TopicsControllerTest.php, tests/Models/OAuth/GroupPermissionTest.php, tests/Models/OAuth/TokenTest.php, tests/OAuthClientCredentialsRequestTest.php, tests/TestCase.php, tests/api_routes.json
- `forum.write_manage` scope added; scope is `client_credentials` only, requires `delegate` and requires the bot account to be in the groups listed in the forum's `moderator_groups`.
- `forum.write` can now be `delegate`d to a bot account
- Added `group_permissions` (can use some name suggestion) scope for enabling forum moderation group permissions
- ~~The OAuth scopes documentation is out of date and still needs updating~~ just moved them here instead of a larger doc update
- ~~things that support group permissions with OAuth have been changed to apply receive the group permission if the token supports delegation or is an `ownToken`.~~ The `ownToken` thing should only be only for chat.
related #7441 but this doesn't include moving or deleting
I thought of making a separate bot group for …
=> Add OAuth scope for pinning and locking topics
