ppy/osu-web

- app/Http/Controllers/BeatmapDiscussionPostsController.php
- app/Http/Controllers/BeatmapDiscussionsController.php
- app/Http/Controllers/BeatmapsetDiscussionVotesController.php
> Add missing asterisks in multiline comments

- app/Http/Controllers/HomeController.php
- app/Http/Controllers/Multiplayer/Rooms/Playlist/ScoresController.php
Another one split off from #9272.
> Move group names to class declaration

- resources/assets/coffee/osu_common.coffee
- resources/assets/lib/beatmap-discussions/nominations.coffee
The one place it's still used is already 16px
> Remove osu.focus()

- app/Libraries/CommentBundle.php
Load commentable in single query after all related comments are fetched.
> Delay loading commentable in bundle

- app/Libraries/CommentBundle.php
Don't count everything when there's hard limit 🤔
> Faster comment pagination

- app/Models/Score/Model.php
- app/Models/ScorePin.php
Apparently recent scores aren't cleaned up when beatmapset is deleted.
> Check beatmapset existence for score listing

- resources/assets/coffee/main.coffee
- resources/assets/coffee/osu_common.coffee
- resources/assets/lib/artist-tracks-index/main.tsx
- resources/assets/lib/components/multiplayer-select-options.tsx
- resources/assets/lib/components/ranking-filter.tsx
- resources/assets/lib/components/wiki-search.tsx
- resources/assets/lib/core-legacy/forum-topic-reply.coffee
- resources/assets/lib/globals.d.ts
- resources/assets/lib/quick-search/main.tsx
- resources/assets/lib/utils/turbolinks.ts
Looks mostly turbolinks-related so I put it in `utils/turbolinks` 👀
> Convert osu.navigate to typescript

- .eslintrc.js
- resources/assets/lib/beatmap-discussions/autolink-plugin.ts
- resources/assets/lib/beatmap-discussions/disable-tokenizers-plugin.ts
- resources/assets/lib/beatmap-discussions/editor-beatmap-selector.tsx
- resources/assets/lib/beatmap-discussions/editor-insertion-menu.tsx
- resources/assets/lib/beatmap-discussions/editor-issue-type-selector.tsx
- resources/assets/lib/beatmap-discussions/editor-toolbar.tsx
- resources/assets/lib/beatmap-discussions/nominator.tsx
- resources/assets/lib/beatmap-discussions/review-post.tsx
- resources/assets/lib/beatmap-discussions/timestamp-plugin.ts
- resources/assets/lib/beatmapsets-show/beatmapset-menu.tsx
- resources/assets/lib/chat/chat-api.ts
- resources/assets/lib/chat/conversation-panel.tsx
- resources/assets/lib/chat/conversation-view.tsx
- resources/assets/lib/chat/message-divider.tsx
- resources/assets/lib/cli/generate-localizations.js
- resources/assets/lib/components/bbcode-editor.tsx
- resources/assets/lib/components/beatmapset-panel.tsx
- resources/assets/lib/components/landing-news.tsx
- resources/assets/lib/components/news-header.tsx
- resources/assets/lib/components/report-form.tsx
- resources/assets/lib/components/user-card-tooltip.tsx
- resources/assets/lib/components/user-group-badge.tsx
- resources/assets/lib/core/react-turbolinks.ts
- resources/assets/lib/friends-index/main.tsx
- resources/assets/lib/quick-search/worker.ts
Seems useful to unify things. Although apparently `prettier` is the thing nowadays.
> Add lint for spaces between curly braces

- app/Http/Controllers/BeatmapsetsController.php
- app/Models/Beatmapset.php
- app/Models/BeatmapsetNomination.php
- app/Transformers/BeatmapsetCompactTransformer.php
- app/Transformers/BeatmapsetNominationTransformer.php
- resources/assets/less/bem/beatmapset-info.less
- resources/assets/lib/beatmapsets-show/info.tsx
- resources/assets/lib/interfaces/beatmapset-extended-json.ts
- resources/assets/lib/interfaces/beatmapset-json.ts
- resources/assets/lib/interfaces/beatmapset-nomination-json.ts
- resources/lang/en/beatmapsets.php
The placement seems a bit wrong (and makes the box taller) but that's the only itemised listing area.
Resolves #7008
> Show nominators on beatmap info page

- resources/assets/coffee/osu_common.coffee
- resources/assets/coffee/ujs-common.coffee
- resources/assets/lib/app-deps.ts
- resources/assets/lib/beatmaps/beatmapset-search-controller.ts
- resources/assets/lib/components/score-pin.tsx
- resources/assets/lib/contest-entry/uploader.coffee
- resources/assets/lib/core-legacy/forum-topic-title.coffee
- resources/assets/lib/core/user/user-login.ts
- resources/assets/lib/core/user/user-verification.ts
- resources/assets/lib/globals.d.ts
- resources/assets/lib/store.ts
- resources/assets/lib/utils/ajax.ts
- resources/assets/lib/utils/popup.ts
- resources/assets/lib/utils/turbolinks.ts
- resources/views/forum/topics/replace_button.blade.php
- resources/views/layout/ujs-reload.blade.php
Wasn't going to move these to modules originally as they're still used by blade views, but figured might as well do it and shim the functions for now 🤷
> Convert reloadPage and popup to typescript

- resources/views/layout/_nav2.blade.php
The recent header update from a PR a long time ago undid the fix done a while back.
Resolves #9517.
> Fix notification popup not correctly hid

- app/Models/UserAccountHistory.php
Extra is probably unnecessary 🤔
> Limit chat ack silences to last hour

- app/helpers.php
Found while going through converting `osu.trans*` to typescript
> Remove unused helpers

- app/Http/Controllers/Chat/ChatController.php
- app/Libraries/UserChannelList.php
Another one of n+1 query caused by the announcement check.
> Preload channel data

- resources/assets/lib/components/report-form.tsx
- resources/assets/lib/components/report-reportable.tsx
Also put back the form completion check which hides the form.
> Clean up Report Form component

- app/Console/Commands/ChatChannelSetLastMessageId.php
- app/Console/Commands/MigrateFreshAllCommand.php
- app/Console/Commands/MigrateFreshOrRunCommand.php
Some of the simpler issues from phpstan
> Fix variable and function return typings in Command classes

- app/Libraries/Search/ScoreSearchParams.php
It seems to help the most with fewer (1 or 2) shards though 👀
> Match sort with the schema

- resources/assets/lib/utils/lang.ts
Somehow managed to delete the params in https://github.com/ppy/osu-web/pull/9522/files#diff-0bbfe195640b4fa98d2f7906c1340a82849ec8447603a03b14c9aff1603fe4afR12
ಠ_ಠ
> Fix missing translations

- resources/assets/lib/modding-profile/main.coffee
- resources/assets/lib/user-multiplayer-index/main.tsx
> Fix tournament banner size on other user profile tabs

- .eslintrc.js
- resources/assets/lib/beatmap-discussions/discussion-type.ts
- resources/assets/lib/beatmap-discussions/editor-helpers.ts
- resources/assets/lib/beatmap-discussions/editor-toolbar.tsx
- resources/assets/lib/beatmap-discussions/icon-dropdown-menu.tsx
- resources/assets/lib/beatmap-discussions/new-discussion.tsx
- resources/assets/lib/beatmap-discussions/nominator.tsx
- resources/assets/lib/beatmap-discussions/review-document.ts
- resources/assets/lib/store.ts
Disallow truthy object comparison to prevent the condition in #9538 from happening.
The other settings will be changed separately as there's a lot of places with them.
Also fix same kind of error in `NewDiscussion.post`; This one has less of an issue as the `button` calls the check properly, but still ಠ_ಠ
> Enable ESLint strict-boolean-expressions

- app/Transformers/BeatmapDiscussionTransformer.php
So there's this primitive thing.
> Simplify discussion transformer return

- app/Models/Score/Best/Model.php
- app/Models/Score/Model.php
- app/Models/Solo/Score.php
Missed this when renaming route for legacy score. Also added url support for solo score.
> Fix score url

- resources/assets/lib/utils/lang.tsx
> Fix joining one component

- resources/views/layout/metadata.blade.php
As I looked closer, some use `App::`, some other use `app()` 👀
> Store locale variables in view

- resources/views/layout/metadata.blade.php
> Use existing locale variable

- app/Http/Controllers/Store/ProductsController.php
- app/Models/Store/Order.php
- app/Models/Store/Product.php
- resources/views/store/_product.blade.php
Please jam the url in description field "for now" 👀 
The header image should probably have some indicator of it being an external store link.
> Add support for redirect-only product

- app/helpers.php
> Use iterable for array-like typing

- app/Libraries/ApidocRouteHelper.php
not sure when that broke. should fix the confusion in #9608
> Fix "requires user" label in API docs

- app/Models/Count.php
- app/Models/RankHistory.php
- database/migrations/2022_12_12_052806_create_user_performance_rank_exp.php
> Add support for exp rank history

- app/Models/UserStatistics/Model.php
- app/Transformers/UserStatisticsTransformer.php
That was weird. Also wrong return type for global rank exp function.
> Clean up handling of global rank (and exp)

- app/Models/RankHistory.php
I thought I've already done this before but it was for BeatmapFailtimes...
> Simplify generation for data attribute of rank history model

- resources/assets/lib/profile-page/rank-chart.tsx
Not sure how frequent this happens (or if still possible to happen at all).
> Fix rank history display when there's no history

- app/Models/User.php
> Empty rank highest for exp rank

- app/Models/UserStatistics/Model.php
Yet another ever-expanding scope.
> Support exp rank for country rank

- database/factories/TournamentFactory.php
- database/seeders/ModelSeeders/ProductSeeder.php
- tests/Browser/SanityTest.php
- tests/Libraries/Fulfillments/BannerFulfillmentTest.php
- tests/Libraries/OrderCheckoutTest.php
- tests/Models/TournamentTest.php
Probably can be separate from the Store factory updates
> Convert tournament to class-based factory

- app/Http/Kernel.php
- app/Providers/AppServiceProvider.php
- composer.json
- composer.lock
- config/trustedproxy.php
There's no need to reset trusted proxy settings on each request anymore.
> Simplify proxy trusting logic

- Dockerfile.deployment
- Dockerfile.development
It's already what github action is using.
> Update docker to use latest LTS Ubuntu

- DEPLOYMENT.md
- SETUP.md
- bin/docker_dev.sh
- docker/development/prepare.sh
Current compose file requires newer docker compose.
> Update docs on docker compose

- resources/assets/lib/utils/lang.tsx
> Fix check for pluralised translation

- resources/assets/lib/globals.d.ts
Merging old branch and somehow all the `osu.` calls aren't marked as invalid 🤨
> Remove declaration of nonexistent helper object

- app/Models/NewsPost.php
> Only show published news posts for navigation

- app/Http/Middleware/AuthApi.php
User restriction should already be checked in their respective endpoints.
> Fix OAuth user check

- app/Libraries/OsuAuthorize.php
- tests/Libraries/ChatTest.php
Chat bots probably won't have plays.
closes #9701
> Allow chat bot to send chat messages without min plays

- .github/workflows/tests.yml
- docker-compose.yml
> Use updated score indexer commands

- app/Http/Controllers/WikiController.php
- resources/views/master.blade.php
Better hint for search engine indexing?
(another one from old branch)
> Match wiki pages language meta with its content

- resources/assets/less/bem/beatmap-list.less
Resolves #9726. Forgot about the behaviour difference between browsers for this one.
> Fix beatmap list scrollbar style on chrome

- resources/views/users/create.blade.php
...and set correct input type for email field.
> Allow autofill fields and set correct focus

- resources/assets/lib/profile-page/controller.tsx
- resources/assets/lib/profile-page/extra-page.ts
> Lazy load user profile page extras with game mode

- resources/assets/less/bem/lazy-load.less
- resources/assets/lib/components/lazy-load.tsx
> Remove lazy-load class when loaded

- resources/assets/less/base.less
- resources/assets/less/layout.less
> Remove unused styling

- app/Transformers/Chat/MessageTransformer.php
Doesn't look right with the extra `<p>` tags 👀
> Don't render actions in announcement channels as markdown

- app/Http/Controllers/HomeController.php
> Fix Android detection

- database/mods.json
support for https://github.com/ppy/osu/pull/21725
> Add coverage setting to Fade In and Hidden for Mania

- resources/js/beatmap-discussions/discussion-mode.ts
> Fix beatmap discussions tab order

- resources/css/bem/beatmapset-status.less
- resources/css/bem/profile-extra-entries.less
- resources/css/layout.less
- resources/js/components/beatmapset-panel.tsx
This allows having transparent status badge natively.
> Pass hsl value for beatmap status

- resources/js/beatmap-discussions/current-discussions.ts
- resources/js/beatmap-discussions/discussions.tsx
- resources/js/beatmap-discussions/main.coffee
- tests/karma/utils/beatmapset-discussion-helper.spec.ts
import directly instead of the import in the legacy typedef... 🤨 
Also `BeatmapDiscussionHelper.DEFAULT_MODE` hasn't existed for a while 👀
> Use correct BeatmapsetDiscussionJson import

- docker/deployment/nginx-assets.conf
As assets are now going to be separately deployed in staging/production, handle this redirection here.
Closes #9704
> 🔧 Add missing unknown flag redirection

- app/Libraries/UsernameValidation.php
- database/factories/RankHighestFactory.php
- tests/Libraries/UsernameValidationTest.php
> Disallow taking over inactive top player usernames

- app/helpers.php
- tests/HelpersTest.php
> Support all kinds of newline for split string parameter

- resources/js/beatmap-discussions/discussion.tsx
- resources/js/beatmap-discussions/system-post.tsx
- resources/js/interfaces/beatmapset-discussion-post-json.ts
> Fix typing for beatmapset discussion system post

- resources/js/profile-page/user-page.tsx
> Adjust me! page edit button label

- database/mods.json
Needs to be deployed ASAP as a build with this live is now out :)
> Add accuracy challenge mod support

- app/Libraries/OsuAuthorize.php
Add check for metadata edit as well.
Resolves #9847
> Disallow restricted user from editing beatmap description

- resources/css/bem/beatmapsets-search-filter.less
- resources/css/bem/beatmapsets-search.less
- resources/js/beatmaps/search-filter.tsx
- resources/js/beatmaps/search-panel.tsx
Use grid to great effect.
Resolves #9798.
> Fix beatmap search panel alignment

- app/Libraries/BBCodeForDB.php
- app/Libraries/BBCodeFromDB.php
- resources/css/bbcode.less
- tests/Libraries/bbcode_examples/basic_inline_code.base.txt
- tests/Libraries/bbcode_examples/basic_inline_code.db.txt
- tests/Libraries/bbcode_examples/basic_inline_code.html
Saw this issue and figured it's easy enough to add... if we do want it, that is. Using `[c]` tag. Style was mostly copied from markdown but with lighter background and colour that doesn't look like link 🤨
Resolves #7126.
> Add bbcode tag for inline code

- resources/css/bem/beatmap-discussion.less
The box doesn't have rounded corner on mobile.
> Fix border-radius on resolved marker on mobile

- app/Transformers/UserStatisticsTransformer.php
- resources/js/interfaces/user-statistics-json.ts
- resources/views/docs/_structures/user_statistics.md
> Add user hit counts to statistics json

- resources/js/notification-widget/item.tsx
Resolves #7687. Also fixes clicking on timestamp not marking read.
> Mark read on notification middle click

- resources/css/bem/beatmapset-badge.less
- resources/js/beatmap-discussions/header.coffee
- resources/js/beatmapsets-show/header.tsx
- resources/js/components/beatmapset-badge.tsx
- resources/js/components/beatmapset-panel.tsx
Seems useful to have them use same component.
> Unify beatmapset badge component

- app/Transformers/ProfileBannerTransformer.php
- resources/js/components/img2x.tsx
- resources/js/components/profile-tournament-banner.tsx
- resources/js/interfaces/profile-banner.ts
> Add 2x image url to profile banner

- app/Http/Controllers/HomeController.php
- resources/lang/en/home.php
> Allow translating "or later" part of os version

- app/Libraries/Elasticsearch/Es.php
- app/helpers.php
- tests/Controllers/InterOp/UsersControllerTest.php
- tests/Controllers/Multiplayer/RoomsControllerTest.php
`${` is the deprecated style for php 👀
> Fix variable usage in strings

- README.md
- composer.json
- composer.lock
All relevant servers have been updated.
> Update php version requirement

- resources/js/utils/beatmapset-discussion-helper.ts
Resolves #7591. The conditional is a bit hard to read ಠ_ಠ
> Ignore deleted post when checking nearby beatmap discussions

- app/Http/Controllers/ScorePinsController.php
- resources/js/interfaces/score-json.ts
- resources/js/profile-page/controller.tsx
- tests/Controllers/ScorePinsControllerTest.php
Pass type for adjacent scores as well.
> Fix reordering solo scores

- app/Transformers/BuildTransformer.php
- app/Transformers/ContestEntryTransformer.php
- app/Transformers/NewsPostTransformer.php
- app/Transformers/UserStatisticsTransformer.php
Reuse variable and transformers while at it.
> Replace anonymous function transformer with primitive

- app/Models/LegacyMatch/Game.php
- app/Transformers/LegacyMatch/GameTransformer.php
> Add beatmap id to legacy match game json

- app/Models/Forum/Topic.php
- database/migrations/2023_02_22_103305_add_create_time_index_to_forum_topics.php
- resources/lang/en/sort.php
- resources/views/forum/forums/_topics_sort.blade.php
As it turned out there's existing sort option already.
Resolves #9891, resolves #1705 (sort of). <sub>haha sort</sub>
> Allow sorting forum topics by creation date

- resources/js/changelog-index/main.coffee
- resources/js/components/comment-show-more.coffee
I don't remember how they used to look like.
> Remove unused style

- resources/js/notifications/legacy-pm.tsx
> Remove unused field

- resources/css/bem/qtip.less
- resources/css/bem/user-list-popup.less
> Adjust user popup margin

- app/Libraries/ModdingHistoryEventsBundle.php
- app/Libraries/OsuAuthorize.php
- app/Transformers/BeatmapsetCompactTransformer.php
- app/Transformers/BeatmapsetTransformer.php
- resources/js/beatmap-discussions/discussion.tsx
- resources/js/beatmap-discussions/new-discussion.tsx
- resources/js/beatmap-discussions/new-review.tsx
- resources/js/beatmap-discussions/post.tsx
- resources/js/beatmapsets-show/header.tsx
- resources/js/utils/beatmapset-helper.ts
- resources/lang/en/authorization.php
> Disable beatmap discussions on beatmaps which have been download limited

- resources/css/bem/forum-item-stripe.less
- resources/css/bem/forum-topic-entry.less
- resources/css/bem/forum-topic-nav.less
- resources/css/bem/header-v4.less
- resources/css/bem/pagination-v2.less
- resources/css/bem/title.less
- resources/css/layout.less
- resources/css/sections.less
- resources/views/forum/forums/_forum.blade.php
- resources/views/forum/forums/_topic.blade.php
- resources/views/forum/forums/_topics_sort.blade.php
- resources/views/forum/forums/index.blade.php
- resources/views/forum/forums/show.blade.php
- resources/views/forum/topics/_nav.blade.php
- resources/views/home/_search_page_tabs.blade.php
- use variable for colouring
- remove theming for sort buttons
- remove unused classes
- use theme colour for unread and reply marker
- lighten management category colour
- use correct category cover
Resolves #9920.
The unused `--forum-text` and `--forum-text-hover` variables are kept for now...
> Fix forum colour

- app/Transformers/ContestEntryTransformer.php
> Report missing contest image to sentry

- resources/js/beatmaps/search-panel.tsx
- resources/js/core-legacy/search.coffee
- resources/js/quick-search/main.tsx
- resources/views/home/search.blade.php
Resolves #7866.
Input type also updated to `search` so the osk will show search icon instead of enter.
> Blur input field on pressing enter

- resources/js/chat/conversation-view.tsx
> Link to pm target in chat view title

- app/helpers.php
- resources/views/forum/forums/_forum.blade.php
- resources/views/forum/forums/_topic.blade.php
- resources/views/forum/forums/_topics.blade.php
- resources/views/forum/forums/index.blade.php
- resources/views/forum/forums/show.blade.php
Uses bold because that seems to be the easiest.
Resolves #4676.
> Add indicator for own topic/last reply

- app/Models/BeatmapPack.php
- resources/lang/en/beatmappacks.php
- resources/views/packs/index.blade.php
Not sure if the label should say "Featured" or "Featured Artist" 🤔 
Also I feel it should be the first tab?
Resolves #4408.
> Add featured artist pack prefix

- resources/css/bem/profile-info.less
- resources/css/bem/profile-previous-usernames.less
> Add text shadow to profile page username area

- config/schemas/beatmapsets.json
> Index beatmap user id

- resources/css/bem/value-display.less
> Adjust kudosu value styling in profile page

- app/Transformers/GenreTransformer.php
- app/Transformers/LanguageTransformer.php
- resources/js/components/beatmapset-event.tsx
Resolves #6480.
Cleaned up relevant transformers a bit while at it.
> Translate language and genre for beatmapset event

- resources/js/notification-widget/main.tsx
- resources/js/notifications-index/main.tsx
- resources/lang/en/notifications.php
Allows using different inflection between accusative and nominative.
Resolves #7040.
> Use different list for action types

- app/Models/Beatmap.php
> Index beatmapset on beatmap update

- resources/css/bem/forum-item.less
- resources/lang/en/forum.php
- resources/views/forum/forums/_forum.blade.php
- resources/views/forum/forums/index.blade.php
- resources/views/forum/forums/show.blade.php
> Add header to forum listing

- app/Providers/AppServiceProvider.php
It was from many years ago and never actually used.
> Remove nonexistent app service registration

- resources/css/bem/header-v4.less
> Remove duplicate style definition

- resources/js/contest-voting/art-entry-list.coffee
> Show correct contest entry rank when filtered by voted

- app/Http/Controllers/BeatmapsController.php
Resolves #8808, resolves #8230.
> Allow API access to mods filtered score listing

- app/Http/Controllers/MatchesController.php
- app/Models/LegacyMatch/Game.php
> Consider beatmap ruleset for legacy match game

- app/Models/Beatmapset.php
...and I guess latest ranked since it'll be a similar issue..? 🤷 
(this is the quick fix; better would be to cache the values according to user setting 👀 )
closes #9979
> Exclude explicit beatmaps popular listing from dashboard

- resources/views/home/_user_news_post_preview.blade.php
- resources/views/multiplayer/rooms/show.blade.php
- resources/views/rankings/charts.blade.php
This should cover all `formatLocalized` usage.
> Update deprecated date formatting function

- app/Http/Controllers/BeatmapsController.php
So that was a thing I copied from the other function and the forgot to update when updating the other.
> Fix score mods filter on solo scores endpoint

- resources/views/docs/auth.blade.php
> Document refreshing access token

- app/Http/Controllers/BeatmapsController.php
- app/Libraries/Score/BeatmapScores.php
- app/Models/Score/Best/Model.php
- config/osu.php
> Add option to fetch up to 100 scores

- resources/css/bem/score-player.less
> Use smaller total score font size for score page on mobile

- app/Libraries/Search/BeatmapsetSearch.php
> Filter by beatmap status instead of beatmapset

- app/helpers.php
- resources/css/bem/search-forum-post.less
- resources/lang/en/forum.php
- resources/views/home/_search_result_forum_post.blade.php
- resources/views/objects/search/_forum_post.blade.php
- add forum name
- don't display full url
- simplify post url logic
Resolves #2863.
> Adjust forum search card

- app/Http/Controllers/BeatmapsController.php
So I was looking for where the limit is being passed when merging my other pr... 👀
> Fix limit parameter not applied for solo scores

- app/Libraries/NewForumTopic.php
- resources/views/forum/topics/_post_edit_form.blade.php
> Set correct title placeholder

- resources/js/components/user-card-tooltip.tsx
- resources/js/components/user-list-popup.tsx
Resolves #2188? Seems a bit weird but this allows moving cursor to the right.
> Reposition user card tooltip position for user list

- resources/js/beatmap-discussions/new-discussion.tsx
- resources/js/beatmap-discussions/new-review.tsx
A bit annoying working with this not being mobx when the other `NewThing` components are mobx
> Convert NewReview component to use mobx

- resources/views/docs/info.md.blade.php
The api has been relatively stable.
> Remove unstable note on current api version

- resources/js/profile-page/detail-bar.tsx
> Show message button on bot user profile page

- resources/js/beatmaps/search-sort.tsx
> Fix hover sort arrow on beatmap listing

- resources/css/bem/mp-history-player-score.less
> Don't hide failed text on mobile match page

- resources/js/beatmap-discussions/nominations.coffee
- resources/lang/en/beatmaps.php
Needed for some languages. Resolves #6828.
> Allow extra wording for rank estimate date variable

- app/Libraries/BBCodeForDB.php
- app/Libraries/BBCodeFromDB.php
- tests/Libraries/bbcode_examples/box_with_bbcode_title.base.txt
- tests/Libraries/bbcode_examples/box_with_bbcode_title.db.txt
- tests/Libraries/bbcode_examples/box_with_bbcode_title.html
~~Quote is required otherwise it's kind of difficult with just regexp.~~ Turned out it's kind of not as difficult.
Resolves #6735.
Woo more stuff being added to bbcode ( ﾟ ヮﾟ)a
> Support bbcode in box title

- app/Libraries/BBCodeForDB.php
- app/Libraries/BBCodeFromDB.php
- resources/css/bbcode.less
- tests/Libraries/bbcode_examples/autolink.html
- tests/Libraries/bbcode_examples/basic_list.html
- tests/Libraries/bbcode_examples/basic_quote.html
- tests/Libraries/bbcode_examples/list_title.html
- tests/Libraries/bbcode_examples/multiple_links.base.txt
- tests/Libraries/bbcode_examples/multiple_links.db.txt
- tests/Libraries/bbcode_examples/multiple_links.html
- tests/Libraries/bbcode_examples/quote_newline.html
> Fix consecutive links not parsed correctly

- app/Libraries/Search/MultiSearch.php
> Allow searching forum post by username/id

- app/Libraries/User/UserSignatures.php
- resources/views/forum/topics/_post.blade.php
- resources/views/forum/topics/_posts.blade.php
Variable reuse, signature caching, and other code style clean ups.
> Clean up topic post rendering

- app/Models/UserReport.php
- resources/js/components/report-form.tsx
- tests/Models/UserReportTest.php
> Only require comment when the reason is Other

- resources/lang/en/forum.php
"Write" is the mode, having it as button doesn't seem to make much sense 🤔
> Adjust bbcode editor exit preview button

- resources/js/profile-page/parse-event.tsx
Resolves #8044. Or more like the other way around because the link has been removed a long time ago but the issue has never been closed (and I didn't realize it until now).
> Link to deleted beatmap for moderators

- app/Libraries/BBCodeFromDB.php
- resources/css/bbcode.less
- tests/Libraries/bbcode_examples/autolink.html
- tests/Libraries/bbcode_examples/basic_list.html
- tests/Libraries/bbcode_examples/basic_quote.html
- tests/Libraries/bbcode_examples/list_title.html
- tests/Libraries/bbcode_examples/quote_newline.html
> Always add blank space after quote and list

- resources/js/notifications-index/main.tsx
Resolves #10006. Adjusted item margins while at it - mainly on initial load when there's only spinner and on displaying the empty message.
> Show message on empty notification

- resources/css/bem/form-select.less
- resources/css/bem/simple-form.less
This should cover everything...? 🤔
> Fix overflow in form drop-down

- app/Models/UserReport.php
- resources/js/components/report-form.tsx
- tests/Models/UserReportTest.php
There's no clear consensus so whatevs 🤷 There isn't open issue I can refer to here apart of a comment in #10054.
Also limited chat report reason to post type.
> Adjust user report comment requirement

- app/helpers.php
- resources/css/bem/news-post-preview.less
- resources/views/home/_user_news_post_preview.blade.php
Now with date pattern autogenerator magic 🪄
> Translate date in news post preview

- app/Http/Controllers/Forum/PostsController.php
- resources/js/core-legacy/forum-topic-reply.coffee
Amazing no one wondered about everything being inlined when quoting a post.
> Fix default structure of forum quote template

- database/factories/ContestEntryFactory.php
- database/factories/ContestFactory.php
- tests/Browser/SanityTest.php
- tests/Models/ContestTest.php
Really need to get this over already 😐
> Add class based factory for Contest

- database/factories/ArtistFactory.php
- tests/Browser/SanityTest.php
- tests/Models/ModelTest.php
> Add class based factory Artist

- database/factories/BanchoStatsFactory.php
- database/seeders/ModelSeeders/BanchoStatsSeeder.php
> Add class based factory for BanchoStats

- database/factories/BeatmapFailtimesFactory.php
- database/seeders/ModelSeeders/BeatmapSeeder.php
Another one that's not quite used in test.
> Add class based factory for BeatmapFailtimes

- database/factories/BeatmapMirrorFactory.php
- tests/Browser/SanityTest.php
- tests/Models/BeatmapsetTest.php
There are still over 20 models to be updated 😬
> Add class based factory for BeatmapMirror

- app/Libraries/User/UserSignatures.php
- resources/css/bem/forum-post.less
- resources/lang/en/users.php
- resources/views/forum/topics/_post.blade.php
- resources/views/forum/topics/_posts.blade.php
Resolves #8665. I'm not doing the blocking quote part because it's a small hell to delve into.
> Hide forum post of blocked user

- resources/css/bem/supporter-quote.less
Resolves #6766 in some weird way. I can't quite tell how the positioning is supposed to be.
> Put supporter page quote mark below the content

- database/factories/ChangelogFactory.php
- database/seeders/ModelSeeders/ChangelogSeeder.php
- tests/Browser/SanityTest.php
- tests/Middleware/RouteScopesTest.php
> Add class based factory for Changelog

- database/factories/ChatFilterFactory.php
- tests/Controllers/Chat/Channels/MessagesControllerTest.php
> Add class based factory for ChatFilter

- database/factories/GroupFactory.php
- tests/Browser/SanityTest.php
- tests/Models/GroupTest.php
I probably have mentioned it somewhere else but this whole thing was kind of [done](https://github.com/nanaya/osu-web/tree/more-test-stuff) some years ago and I'm just picking stuff out from there one by one 👀
> Add class based factory for Group

- app/Models/BeatmapDiscussionPost.php
- app/Models/Chat/Channel.php
- app/Models/Comment.php
- app/Models/Forum/Post.php
- app/Models/Forum/Topic.php
- app/Models/Forum/TopicPoll.php
- app/Models/User.php
- app/Models/UserReport.php
- app/Traits/Validatable.php
Split out from #9982. Notable change is comment is always trimmed.
> Share field length validation logic

- resources/js/beatmapsets-show/info.tsx
- resources/js/components/bbcode-editor.tsx
> Confirm when closing description editor

- app/Http/Controllers/BeatmapsetsController.php
- app/Models/BeatmapDiscussionPost.php
- app/Models/Beatmapset.php
- app/Models/BeatmapsetEvent.php
- app/Models/Chat/Channel.php
- app/Models/Comment.php
- app/Models/Forum/Post.php
- app/Models/Forum/Topic.php
- app/Models/Forum/TopicPoll.php
- app/Models/User.php
- app/Models/UserReport.php
- app/Traits/Validatable.php
- database/migrations/2023_03_13_100000_add_tags_edit_to_beatmapset_events.php
- resources/css/bem/beatmapset-event.less
- resources/js/beatmapsets-show/metadata-editor.tsx
- resources/lang/en/beatmapset_events.php
> Allow editing beatmap tags

- resources/css/bem/imagemap.less
> Fix imagemap when the image isn't using full width

- resources/js/beatmap-discussions/discussion-message.tsx
- resources/js/beatmap-discussions/renderers.tsx
fixes #10090
Will wrap in a factory function later 👀 
The annoying part is there doesn't seem to be a generic custom render
> Decorate timestamp in list item

- resources/js/beatmap-discussions/renderers.tsx
The typing isn't quite correct.
Resolves #10094.
> Fix rendering empty list

- resources/css/bem/imagemap.less
Resolves #10095. As it turned out my initial attempt was already correct 🤔
> Fix imagemap overflow

- database/factories/Chat/ChannelFactory.php
- database/factories/LegacyMatch/EventFactory.php
- database/factories/LegacyMatch/GameFactory.php
- database/factories/LegacyMatch/LegacyMatchFactory.php
- tests/Browser/SanityTest.php
- tests/Controllers/MatchesControllerTest.php
Might as well convert the whole directory 🤷
> Add class based factory for LegacyMatch related models

- app/Libraries/BBCodeFromDB.php
- tests/Libraries/bbcode_examples/imagemap_multi_first_invalid.base.txt
- tests/Libraries/bbcode_examples/imagemap_multi_first_invalid.db.txt
- tests/Libraries/bbcode_examples/imagemap_multi_first_invalid.html
Provided
- two imagemaps
- the first one is missing closing tag
- the last link of the first one doesn't have title
Things explode because the last link will include the whole second imagemap.
> Fix handling invalid imagemap

- database/factories/SpotlightFactory.php
- database/seeders/ModelSeeders/SpotlightSeeder.php
> Add class based factory for Spotlight

- resources/js/core-legacy/form-error.coffee
- resources/js/form-errors.ts
- resources/js/interfaces/form-error-json.ts
- resources/js/utils/json.ts
- tests/karma/utils/json.spec.ts
Apparently things explode if the value isn't an array 🤔
> Handle nested form error json

- app/Libraries/BBCodeFromDB.php
- resources/css/bbcode.less
- tests/Libraries/bbcode_examples/basic_size.base.txt
- tests/Libraries/bbcode_examples/basic_size.db.txt
- tests/Libraries/bbcode_examples/basic_size.html
- tests/Libraries/bbcode_examples/box_with_bbcode_title.html
> More customisable font size

- app/Http/Controllers/ArtistTracksController.php
- resources/js/artist-tracks-index/main.tsx
- resources/js/entrypoints/artist-tracks-index.tsx
- resources/views/artist_tracks/index.blade.php
Testing out an idea so the state sync happens automatically instead of having to manually sync whenever it's updated. Could also be used for profile page controller which has more points where it updates the state (and they all currently have explicit save state call).
> Automatic dataset sync for artist track search component

- app/Events/NewPrivateNotificationEvent.php
Parent constructor doesn't take parameters
> Call parameterless parent constructor without params

- composer.json
- composer.lock
- database/factories/Factory.php
- database/factories/Score/Best/FruitsFactory.php
- database/factories/Score/Best/ManiaFactory.php
- database/factories/Score/Best/OsuFactory.php
- database/factories/Score/Best/TaikoFactory.php
- database/factories/UpdateStreamFactory.php
- database/factories/UserDonationFactory.php
- database/factories/UserMonthlyPlaycountFactory.php
- database/factories/UserRelationFactory.php
- database/factories/UserStatistics/FruitsFactory.php
- database/factories/UserStatistics/ManiaFactory.php
- database/factories/UserStatistics/OsuFactory.php
- database/factories/UserStatistics/Spotlight/FruitsFactory.php
- database/factories/UserStatistics/Spotlight/ManiaFactory.php
- database/factories/UserStatistics/Spotlight/ModelFactory.php
- database/factories/UserStatistics/Spotlight/OsuFactory.php
- database/factories/UserStatistics/Spotlight/TaikoFactory.php
- database/factories/UserStatistics/TaikoFactory.php
- tests/Browser/SanityTest.php
- tests/Controllers/Chat/Channels/MessagesControllerTest.php
- tests/Controllers/Chat/ChatControllerTest.php
- tests/Libraries/Fulfillments/SupporterTagFulfillmentTest.php
- tests/Libraries/UserChannelListTest.php
- tests/Middleware/RouteScopesTest.php
> Remove legacy factory

- app/Transformers/UserContestEntryTransformer.php
At least we've managed to never trigger this condition 🤔
> Fix missing import in UserContestEntryTransformer

- resources/css/bem/beatmapset-panel.less
- resources/views/home/_search_result_beatmapset.blade.php
> Fix beatmapset card overflow in global search result

- resources/css/base.less
- resources/css/utilities.less
- resources/views/store/products/show.blade.php
Only keeping the store product page because the others seem fine with normal case. The store page one has kind of mixed case at the moment (quantity is capitalised but size and others are lowercase).
> Remove default uppercasing of form label

- app/Models/User.php
In case people copy pasted it and whitespaces accidentally got included.
The person never responded but this probably resolves #10075.
> Trim trailing whitespaces for twitter and discord settings

- resources/css/bem/btn-circle.less
- resources/css/bem/post-box.less
- resources/js/components/bbcode-editor.tsx
- resources/lang/en/bbcode.php
- resources/views/forum/_post_toolbar.blade.php
Seems useful. Additionally adjusted toolbar buttons to use gap instead of margin dance.
> Add link to bbcode help wiki page

- resources/js/components/bbcode-editor.tsx
- resources/js/forum/post-box.coffee
- resources/lang/en/bbcode.php
- resources/views/forum/_post_toolbar.blade.php
> Add button for image map

- resources/css/bem/chat-message-item.less
- resources/css/bem/osu-md.less
- resources/js/chat/message-item.tsx
- resources/js/remark-plugins/disable-constructs.ts
- resources/js/utils/url.ts
- tests/karma/utils/url.spec.ts
The most basic syntax for now (markdown link). I'm adding the others later (flipped markdown, legacy client, wiki).
> Use markdown parser to create link in chat

- .github/workflows/pack.yml
Needs the `DISCORD_INFRA_WEBHOOK_URL` secret.
> 👷 Add pending deployment notice

- .eslintrc.js
- package.json
- resources/js/chat/message-item.tsx
- resources/js/remark-plugins/legacy-link/from-markdown.ts
- resources/js/remark-plugins/legacy-link/index.ts
- resources/js/remark-plugins/legacy-link/micromark.ts
- tests/karma/remark-plugins/legacy-link.spec.tsx
(the `[https://wat wat]` one)
...seems working? 🤷 
<sub>probably should add test or something</sub>
> Support legacy link syntax for chat

- app/Libraries/Elasticsearch/Hit.php
- app/Libraries/Elasticsearch/SearchResponse.php
- app/Libraries/Payments/PaymentProcessor.php
- app/Models/UserStatistics/Model.php
Match the interface they're implementing.
Also removes the unnecessary(?) `setCreatedAt`
> Declare missing return types

- .github/workflows/lint.yml
Not sure when this happened ┐( ﾟ ヮﾟ)┌
> Update lint warning count

- resources/js/beatmap-discussions/nominator.tsx
Forgot about the extra `> 1` check needed 
closes #10175
> Fix hybrid nomination modal showing for single mode beatmaps

- resources/js/beatmap-discussions/renderers.tsx
- resources/js/chat/message-item.tsx
- resources/js/utils/beatmapset-discussion-helper.ts
- resources/js/utils/url.ts
React is already blocking it but throws warning (on dev).
> Disallow javascript protocol in chat links

- resources/js/beatmap-discussions/nominator.tsx
Not hybrid also doesn't mean legacy 👀
> Preselect default nomination playmode for non-hybrid beatmaps

- app/Console/Commands/NotificationsSendMail.php
Run the job synchronously if possible instead of dispatching to the queue.
The only real benefit of queueing I can think of in this case it not blocking other jobs if a job fails.
> Run user digest mail notification job synchronously

- SETUP.md
> Update setup docs with new location for obtaining API key

- .github/workflows/lint.yml
- resources/js/utils/ajax.ts
Noticed this simple one when checking lint output.
> Return void on upload error callback

- resources/css/bem/love-beatmap-modal.less
- resources/js/beatmap-discussions/love-beatmap-modal.tsx
- remove extra margin on the ruleset header
- unify checkbox size
> Adjust love beatmap dialog headers

- resources/css/bem/play-detail.less
> Handle beatmap name overflow on user play detail

- .github/workflows/lint.yml
- resources/js/beatmap-discussions/love-beatmap-modal.tsx
Immediate feedback and better typings
> Cleanup beatmap discussions love beatmap modal

- tests/Browser/SanityTest.php
> Ignore error from YouTube header

- .github/workflows/lint.yml
- resources/js/beatmap-discussions/beatmap-owner-editor.tsx
`Object.values` on interface which all properties are defined as optional using `?` results on `any[]` but doing it through `Partial` gives the expected result 🤷‍♂️
> Better partial typing

- app/Models/OAuth/Client.php
> Fix OAuth client empty callback url

- resources/js/components/comment.tsx
> Fix comment badge rendered for wrong user

- resources/js/components/comments.tsx
> Pass correct comments array for show more button component

- tests/Controllers/BeatmapsControllerSoloScoresTest.php
- tests/Models/Solo/ScoreEsIndexTest.php
- tests/TestCase.php
Picked up from #10247 since it can be applied by itself.
> Ensure db connections are reset

- app/Models/Beatmapset.php
- app/helpers.php
Apparently the default connect timeout is 5 minutes which is a bit too long.
> Add timeout for curl

- app/Models/Event.php
I can't find way to filter/group by additional data 🤔
> Set event parsing failure as tag for easier filtering

- resources/css/bem/build.less
- resources/js/components/build.coffee
Rounded corner and a bit smaller.
> Adjust display of changelog video

- app/Models/ChangelogEntry.php
> Ignore more tags for changelog category

- resources/js/components/user-card.tsx
- resources/js/core-legacy/store-supporter-tag.coffee
- resources/js/profile-page/extra-menu.tsx
- resources/js/utils/url.ts
- resources/lang/en/users.php
- resources/views/store/products/supporter-tag.blade.php
> Add link to gift supporter tag from user card

- resources/css/bem/beatmap-discussion-timestamp.less
- resources/js/beatmap-discussions/discussion.tsx
> Only stick beatmap discussion timestamp on the discussion page

- resources/views/forum/topics/replace_button.blade.php
- resources/views/forum/topics/replace_delete_button.blade.php
- resources/views/forum/topics/replace_watch_button.blade.php
Limiting its use to just coffeescript files.
> Use native timeout function directly

- resources/views/forum/topics/_feature_vote.blade.php
>  Add confirmation when voting for feature 

- resources/views/docs/info.md.blade.php
> Fix link in docs

- app/Libraries/OsuAuthorize.php
- resources/lang/en/authorization.php
> Disable pinning solo score when it's hidden

- tests/Browser/SanityTest.php
- tests/DuskTestCase.php
> Always reset browser session between tests

- resources/js/contest-entry/uploader.coffee
Controller already accepts uppercase ಠ_ಠ
> Allow contest entry file extension to be uppercase

- resources/css/bem/profile-badges.less
- resources/js/profile-page/badges.tsx
> Show 2x sized badges accordingly

- resources/js/profile-page/controller.tsx
- resources/js/profile-page/medals.tsx
Resolves #10383 (the code part).
> Fix achievement display order

- resources/css/bem/flag-country.less
- resources/js/components/flag-country.tsx
- resources/views/objects/_flag_country.blade.php
div can't be put inside span or p or some other places.
> Change element type for flag component

- app/Libraries/Search/BeatmapsetQueryParser.php
- tests/Libraries/Search/BeatmapsetQueryParserTest.php
> Support prefix search of beatmap status

- app/Models/Multiplayer/UserScoreAggregate.php
> Simplify setting model default values

- resources/js/contest-voting/art-entry-list.coffee
- resources/js/contest-voting/art-entry.coffee
(again)
I fixed this a while back which ended up breaking gallery view. And then I fixed the gallery view while inadvertently unfixed the rank number.
...I sure hope this one doesn't break anything else 🕺
> Fix contest rank number when filtered

- app/Models/Multiplayer/PlaylistItemUserHighScore.php
- app/Models/Multiplayer/UserScoreAggregate.php
Also put score pass and total score together instead of two separate locations.
Additionally add default values for PlaylistItemUserHighScore because otherwise the new score will be compared with null.
Also I just checked UserScoreAggregate and remembered why it has such weird class name related to its table name ಠ_ಠ
> Move playlist item high score functions to its model

- app/Libraries/CleanHTML.php
- tests/Libraries/bbcode_examples/autolink.html
- tests/Libraries/bbcode_examples/multiple_links.html
That allowed a bit too many things 👀
> More strict html purifier rules

- tests/Models/ContestTest.php
I took out the completed check in model and the existing tests still pass...
> Add test for multiplayer score completion check on contest

- app/Models/ChangelogEntry.php
- app/helpers.php
> Extract null return logic to function

- resources/views/store/products/show.blade.php
Leftover from grid class update.
> Remove extra closing div

- resources/js/interfaces/user-statistics-json.ts
- resources/js/profile-page/rank-chart.tsx
no need to check is_ranked again when that's the only time this component would be used
> Change `RankChart` stats prop to `UserStatisticsRankedJson`

- .github/workflows/lint.yml
- .github/workflows/tests.yml
- Dockerfile.deployment
- Dockerfile.development
- README.md
- composer.json
- composer.lock
> Update to php 8.2

- docker-compose.yml
> Update elastic-indexer command option

- .github/workflows/tests.yml
- SETUP.md
- app/Console/Commands/BeatmapLeadersRefresh.php
- app/Console/Commands/EsIndexDocuments.php
- app/Console/Commands/EsIndexWiki.php
- app/Console/Commands/ForumTopicCoversCleanup.php
- app/Console/Commands/MigrateFreshAllCommand.php
- app/Console/Commands/MigrateFreshOrRunCommand.php
- app/Console/Kernel.php
- app/Http/Controllers/InterOp/ArtistTracksController.php
Keeping `--yes` option for now in case something external is currently using it.
> Use builtin `no-interaction` option instead of custom parameter

- resources/lang/en/beatmapsets.php
- resources/views/beatmapsets/show.blade.php
Resolves #7288.
Direct link to the image because the requested page is admin only and moving it is a bit involved.
> Add link to full size cover image

- resources/js/components/big-button.tsx
Disabling button breaks title tooltip handling so this maybe a better solution than having to put the title in a parent container?
> Use different element for disabled button

- resources/css/bem/profile-badges.less
- resources/css/bem/profile-detail.less
- resources/css/bem/profile-info.less
- resources/js/modding-profile/main.tsx
- resources/js/profile-page/cover.tsx
- resources/js/profile-page/detail.tsx
- resources/js/user-multiplayer-index/main.tsx
Readjust the user info bar colour so it doesn't turn into one big section with the badges.
> Move badge to the top

- app/Models/OAuth/Token.php
> Allow delegating `chat.write_manage` scope

- resources/js/mp-history/game-header.coffee
- resources/js/mp-history/score.coffee
Missed this one when updating the mod component.
> Fix mod icon on legacy match page

- tests/HelpersTest.php
Seems useful especially as this involves matching external string 🤔
> Add test for sql unique exception check

- app/Http/Controllers/Multiplayer/RoomsController.php
- app/Models/Multiplayer/Room.php
> Include featured artist playlist in multiplayer rank page dropdown

- SETUP.md
- tests/Commands/EsIndexScoresQueueTest.php
- tests/Controllers/AccountControllerTest.php
- tests/Controllers/BeatmapsControllerSoloScoresTest.php
- tests/Controllers/BeatmapsControllerTest.php
- tests/Jobs/RemoveBeatmapsetSoloScoresTest.php
- tests/Libraries/Search/UserSearchTest.php
- tests/Libraries/User/CountryChangeTest.php
- tests/Models/Solo/ScoreEsIndexTest.php
also rename the groups to `Requires{Thing}`, that seems to make more sense to me 🤷 
closes #10466
> Add more information about test groups in documentation

- database/migrations/2023_09_06_070904_set_not_null_ruleset_id_on_playlist_items.php
It's already required on create.
> Make ruleset id column on playlist items not nullable

- tests/Controllers/BeatmapsControllerSoloScoresTest.php
I guess I forgot to update this when adding (copying) the function 🤷
> Use existing reindexScores function

- app/Http/Controllers/BeatmapsController.php
> Reorganise beatmaps controller static functions

- resources/css/bem/user-search-card.less
- resources/js/quick-search/user.tsx
> Make entire quick search user card a link

- package.json
> Move autosize types dependency

- .github/workflows/pack.yml
should be enough to run on Apple silicon macs
> Add arm64 to build platforms

- package.json
- webpack.unmix.js
- yarn.lock
Seems to work fine now? At least it outputs more or less the same as the custom one.
Also ran yarn-deduplicate while at it.
> Use existing manifest plugin instead of a custom one

- app/helpers.php
Not only the function isn't used, the return value is outdated.
> Remove unused server-side build icon function

- app/Models/Contest.php
Everything else already assumes it's boolean
> Add missing cast for Contest show_votes

- app/Models/Count.php
> Fix type of Count name

- resources/js/components/mod.tsx
According to [this comment](https://github.com/ppy/osu-web/pull/10590#issuecomment-1733257544).
> Hide unknown mod settings

- app/Http/Middleware/UpdateUserLastvisit.php
Also skipped converting the times to object and instead work directly on the ints as it's currently stored as unix timestamp.
>  Reduce user last visit recording frequency to 5 minutes 

- app/Models/User.php
- app/Models/UserRelation.php
- config/osu.php
- tests/Controllers/SessionsControllerTest.php
<del>Also fixed some manual sql queries for user online check</del>. The manual queries are now completely gone.
> Bypass date object for common last visit checks

- app/Http/Controllers/Passport/AuthorizationController.php
> Fix parsing non-string redirect uri parameter

- app/Http/Controllers/BeatmapsetsController.php
- resources/views/beatmapsets/index.blade.php
Wasn't originally done as it may break if the json structure is changed but nowadays we do care about backward compat so it should be fine? 🤷
> Stringify beatmapsets json for caching

- app/Http/Controllers/Multiplayer/RoomsController.php
> Fix error viewing realtime room on web

- app/Http/Controllers/PasswordResetController.php
- tests/Controllers/PasswordResetControllerTest.php
Better than silently doing nothing.
> Show more useful error message on resending password reset key

- database/seeders/ModelSeeders/BeatmapSeeder.php
Mainly fixing the extension to `.osu`. Also update the rest of it to match actual scheme (I think).
> Fix generated filename in beatmap seeder

- app/Models/Multiplayer/PlaylistItemUserHighScore.php
- app/Models/Multiplayer/UserScoreAggregate.php
I guess this can be deployed first to simplify migration.
> Fill in score id on multiplayer high score tables

- app/Models/Contest.php
> Preload contest entry users when included in json

- routes/web.php
- tests/api_routes.json
> Remove unused beatmapset search path parameter

- app/Libraries/StorageWithUrl.php
- app/Models/Beatmapset.php
- app/Models/Traits/UserAvatar.php
- app/Traits/Uploadable.php
Adding some types and modernise null coalescing assignment.
> Clean up `StorageWithUrl`

- app/Http/Controllers/Controller.php
- app/Providers/AppServiceProvider.php
- resources/lang/en/validation.php
Those are no longer needed after removing the address thing.
> Remove custom laravel validator and related translations/functions

- app/Traits/Uploadable.php
Theoretically this should also apply to s3 but it seems fine over there? 🤷
> Fix permission for local storage upload

- app/Libraries/Search/BeatmapsetQueryParser.php
- app/Libraries/Search/BeatmapsetSearch.php
- app/Libraries/Search/BeatmapsetSearchParams.php
- app/Libraries/Search/BeatmapsetSearchRequestParams.php
> Add `updated` beatmapset filter

- app/Models/ProfileBanner.php
- app/Transformers/UserCompactTransformer.php
- resources/js/components/profile-tournament-banner.tsx
- resources/js/interfaces/user-json.ts
- resources/js/modding-profile/main.tsx
- resources/js/profile-page/detail.tsx
- resources/js/user-multiplayer-index/main.tsx
They just stack and no limit for now 🙃
> Support showing multiple tournament banners

- resources/js/beatmap-discussions/main.coffee
Forgot to attach the handler in #10621 👀
> Fix page scrolling when typing into new review text box

- app/Http/Controllers/ScoresController.php
- app/Libraries/ReplayFile.php
- app/Models/Score/Best/Model.php
- app/Models/Solo/Score.php
- database/factories/Score/Best/ModelFactory.php
Not sure if should log the missing replay files.
Always passing filename to first parameter seems like a good way to self troll.
> Fix missing replay file error and refactor legacy download

- app/helpers.php
> Remove unused helper functions

- app/helpers.php
No need to deal with callback and stuff.
> Simplify class modifier function

- app/Enums/Ip.php
- app/Enums/Ruleset.php
- app/Libraries/Ip2Asn.php
- app/Libraries/Ip2AsnUpdater.php
- app/Models/Multiplayer/PlaylistItem.php
- tests/Libraries/ModsTest.php
> Create enums directory

- app/Models/Multiplayer/ScoreLink.php
- app/Models/ScoreToken.php
- app/Models/Solo/Score.php
- app/Models/Solo/ScorePerformance.php
- database/migrations/2023_10_31_074205_create_score_table_aliases.php
- tests/Controllers/BeatmapsControllerSoloScoresTest.php
- tests/Jobs/RemoveBeatmapsetSoloScoresTest.php
- tests/Models/Solo/ScoreEsIndexTest.php
I thought I made PR of this already but I haven't 🤔 
Closes https://github.com/ppy/osu-infrastructure/issues/24.
> Alias some score tables

- resources/views/forum/forums/show.blade.php
> Skip subforum count query and add current user variable

- app/Libraries/Opengraph/CommentOpengraph.php
> Fix opengraph on comment with legacy/nonexistent user

- app/Libraries/Opengraph/BeatmapsetOpengraph.php
> use `list` version of cover image for beatmapset opengraph header

- app/helpers.php
- resources/lang/en/store.php
- resources/views/store/invoice.blade.php
- resources/views/store/objects/order.blade.php
- resources/views/store/orders/_details.blade.php
- resources/views/store/orders/_status.blade.php
- resources/views/store/orders/_tracking.blade.php
> Add some missing translation keys to store

- resources/css/bem/account-edit-entry.less
- resources/views/accounts/_edit_country.blade.php
- resources/views/accounts/_edit_legacy_api.blade.php
- resources/views/accounts/_edit_oauth.blade.php
> Fix error message wrapping on accounts page

- app/Http/Controllers/RankingController.php
- app/Models/Country.php
- app/Transformers/CountryTransformer.php
Combine relations and remove unused transformer includes.
> Country model cleanup

- .github/workflows/lint.yml
- resources/js/interfaces/error-json.ts
- resources/js/notifications/worker.ts
> Tidy up notification worker

- app/Enums/Ruleset.php
- app/Http/Controllers/BeatmapsController.php
Supporting both `fruits` and `catch` isn't going to be fun 🙃
I was about to document the `@queryParam` but couldn't figure out good wordings for it.
> Support ruleset parameter for beatmap page

- app/Http/Middleware/StripCookies.php
So there's this magic function/string combination.
> Simplify cookie header removal

- app/Http/Middleware/DatadogMetrics.php
- app/helpers.php
- tests/Middleware/RequireScopesTest.php
Probably doesn't matter much but there's just no point in using the heavier `is` function.
Expecting the facade and app instance to be the same is a bit too much it seems ಠ_ಠ
> Simpler api request check

- composer.json
- composer.lock
Making sure the correct extensions are installed.
> Enforce native redis and ds extensions

- app/Libraries/BBCodeForDB.php
- app/Libraries/Smilies.php
The whole thing isn't instance specific at all 🤨
> Cache smiley regexps

- app/Models/Multiplayer/UserScoreAggregate.php
Test to be added soon™ (separately)
> Fix room high score recalculate not resetting playlist item score id

- app/Libraries/RouteSection.php
- resources/views/home/_user_header_default.blade.php
Use facade instead of app and call the getCurrent once in the view.
> Simplify route section helper

- resources/views/accounts/edit.blade.php
- resources/views/objects/_spinner.blade.php
> Fix spinner not showing on avatar upload

- tests/Libraries/ModsTest.php
RX and PF combination is now allowed.
> Update mods test

- app/Http/Middleware/UpdateUserLastvisit.php
> Use cached countries data for session record

- resources/css/bem/bbcode-spoilerbox.less
> Fix bbcode spoiler box link width

- app/Jobs/Notifications/ForumTopicReply.php
Somehow missed this one. (I've applied this directly to notify servers)
> Fix old file url call

- app/Models/Beatmapset.php
> Add correct scope for beatmap pack subquery

- .github/workflows/tests.yml
- Dockerfile.deployment
- Dockerfile.development
- composer.json
- composer.lock
> Update to php 8.3

- .github/workflows/tests.yml
- Dockerfile.deployment
- Dockerfile.development
- composer.json
- composer.lock
More waiting for the [php repository to be updated](https://github.com/oerdnj/deb.sury.org/issues/2063).
Either that or replace the thing with alpine instead.
(partial revert - the updated packages are kept)
> Revert back to php 8.2

- .gitignore
- docker-compose.yml
Use "official" es and mysql images and ignore override file.
> Update docker images

- .github/workflows/lint.yml
> Update github action js lint warning count

- app/Libraries/Search/ScoreSearchParams.php
As it turned out the original value is a bit cumbersome to use.
> More useful return type for user score legacy preference

- app/Models/Solo/Score.php
- public/images/badges/score-ranks-v2019/GradeSmall-F.svg
- resources/css/bem/score-rank.less
- resources/js/interfaces/rank.ts
- resources/js/scores-show/dial.tsx
- resources/js/scores-show/tower.tsx
- tests/Models/Solo/ScoreTest.php
~~No small icon but I don't think it's visible anywhere...?~~ Added the thing. Not in the score page icons "tower" as it's weird "achieving" failed rank.
Resolves #10524
> Support displaying F rank and make it default for fail scores

- app/Models/LoginAttempt.php
- tests/Controllers/SessionsControllerTest.php
> Log successful login

- .env.dusk.local.example
- docker-compose.yml
- docker/development/entrypoint.sh
- docker/development/nginx-default.conf
This seems to work. Some more clean up is still needed to make it not randomly fail due to leftover data but that's for another day (also for normal phpunit tests).
> Fix browser test on docker dev

- app/Http/Controllers/SessionsController.php
- app/Libraries/User/ForceReactivation.php
- resources/js/core/user/user-login.ts
- resources/lang/en/password_reset.php
- resources/views/password_reset/index.blade.php
Also fixed bug where ujs redirect conflicts with user login handler.
> Add message on forced password reset

- docker-compose.yml
Until the score structure update is merged.
> Use older indexer version

- resources/css/bem/simple-menu.less
- resources/lang/en/layout.php
- resources/views/layout/_popup_user.blade.php
- resources/views/layout/_score_mode_toggle.blade.php
- resources/views/layout/header_mobile/user.blade.php
> Add menu to switch score display mode

- app/Exceptions/ClientCheckParseTokenException.php
- app/Http/Controllers/Multiplayer/Rooms/Playlist/ScoresController.php
- app/Http/Controllers/ScoreTokensController.php
- app/Http/Controllers/Solo/ScoresController.php
- app/Http/Controllers/UsersController.php
- app/Libraries/ClientCheck.php
- app/Models/Build.php
- config/osu.php
- database/factories/BuildFactory.php
- phpunit.xml
- tests/Controllers/Multiplayer/Rooms/Playlist/ScoresControllerTest.php
- tests/Controllers/ScoreTokensControllerTest.php
- tests/Controllers/Solo/ScoresControllerTest.php
- tests/Libraries/ClientCheckTest.php
- tests/TestCase.php
Also applies to user registration.
> Add client hash check

- app/Models/Solo/Score.php
As requested to help score processing.
> Add ranked field in score params

- resources/views/layout/_score_mode_toggle.blade.php
> Fix incorrect parameter

- config/octane.php
Let's see if this reduces OOMs 🤷‍♀️
> Adjust octane watch list

- app/Models/OAuth/Token.php
> Apply verification bypass option for oauth tokens

- resources/js/scores-show/stats.tsx
> Fix accuracy value in score page

- app/Libraries/ClientCheck.php
- config/osu.php
```bash
CLIENT_TOKEN_LIFETIME_HOUR=0.25
```
> Add configurable client token lifetime

- app/Models/Score/Model.php
- app/Models/Solo/Score.php
- app/Transformers/ScoreTransformer.php
- resources/js/interfaces/solo-score-json.ts
- resources/js/utils/score-helper.ts
Move logic to backend and add `is_perfect_combo` attribute.
Resolves #10921
> Fix score perfect combo attribute

- resources/js/beatmapsets-show/scoreboard/table-row.tsx
- resources/js/beatmapsets-show/scoreboard/top-card.tsx
Apparently I only did like two things ಠ_ಠ
Resolves #10934.
> Use correct rank/accuracy for beatmap leaderboard

- app/Transformers/ScoreTransformer.php
- resources/css/bem/wiki-notice.less
- resources/css/layout.less
- resources/js/interfaces/solo-score-json.ts
- resources/js/scores-show/main.tsx
- resources/lang/en/scores.php
> Show notice on non-preserved score page

- app/Models/Solo/Score.php
- app/Transformers/ScoreTransformer.php
> Fix converted score type

- app/helpers.php
- resources/lang/en/layout.php
I need to remember to hide that translation from crowdin ( ﾟ ヮﾟ)a
> Add footer link to sctl page for japanese locale

- app/Http/Controllers/ScoresController.php
- app/Models/Solo/Score.php
I don't remember if there's any reason the visibility isn't checked for lazer scores.
> Match score page visiblity between lazer and legacy

- app/Http/Controllers/UsersController.php
- tests/Controllers/UsersControllerTest.php
> Match initial user locale with current session's

- app/Http/Controllers/Forum/PostsController.php
> Fix content type of forum post raw

- app/Http/Controllers/Multiplayer/Rooms/Playlist/ScoresController.php
- resources/lang/en/score_tokens.php
- tests/Controllers/Multiplayer/Rooms/Playlist/ScoresControllerTest.php
> Fix missing checks for multiplayer start play

- docker-compose.yml
Keeping session and stuff around is pretty useful 🤨
> Persistent redis for docker dev

- app/Http/Controllers/BeatmapPacksController.php
- app/Http/Controllers/BeatmapsController.php
- app/Http/Controllers/UsersController.php
- resources/views/docs/info.md.blade.php
Something like this? 🤷 
(I'm not touching the score object docs just yet)
> Update docs relating to score

- resources/js/scores-show/player.tsx
- resources/lang/en/scores.php
> Hide global rank display if a score is non-ranked or non-preserved

- app/Libraries/Search/BeatmapsetSearch.php
- app/Libraries/Search/BeatmapsetSearchParams.php
- app/Libraries/Search/BeatmapsetSearchRequestParams.php
> Use total length for beatmap search

- app/Models/Traits/Scoreable.php
Missed an equal sign.
Resolves #11025.
> Fix legacy score rank calculation

- Dockerfile.deployment
- Dockerfile.development
Original plan of updating to debian 12 went to bin due to swoole's curl breakage 🚮
> Update to nodejs 20

- resources/js/utils/offset-paginator.ts
> Simplify pagination limit parameter validation

- app/Jobs/Notifications/UserAchievementUnlock.php
- app/Models/UserNotificationOption.php
- resources/lang/en/accounts.php
- resources/lang/en/notifications.php
Mainly for client but probably makes more sense to never mail it and only have it in notification popup anyway? 🤔
> Always push (only) notification for medal unlock

- app/Models/Multiplayer/PlaylistItemUserHighScore.php
- app/Models/Multiplayer/UserScoreAggregate.php
- app/Transformers/Multiplayer/UserScoreAggregateTransformer.php
Before dropping the columns 🧹 It's all 0 from what I can tell anyway.
> Remove pp handling from multiplayer

- resources/views/emails/store/supporter_gift.blade.php
Resolves #11031 (I think). I don't think there's any potential harm here...? 🤔
> Don't escape supporter gift message mail

- app/Models/Solo/Score.php
Probably also resolves #11053?
> Fix initial ranked flag to match latest update

- app/Http/Controllers/Forum/PostsController.php
> Check topic state for post raw endpoint

- app/Models/Traits/Scoreable.php
- resources/js/utils/legacy-score-helper.ts
> Include fade in for hidden rank check

- resources/js/turbolinks-overrides.coffee
- resources/js/utils/url.ts
<del>There's no more links to old web anymore, I think? 🤔</del> making exception for old web pages instead
The last ones I can remember are pm and kudosu pages.
> Update handling method for old web links

- routes/web.php
- tests/Browser/LoginTest.php
- tests/RouteTest.php
> Move home url to root instead of subdirectory

- app/Exceptions/Handler.php
- app/Http/Controllers/Passport/AuthorizationController.php
Use library oauth to deal with auth deny.
> Use correct deny flow on oauth authorisation

- app/Models/Beatmapset.php
Better than null access error, at least 😐
> More precise error message when all mirrors are down

- app/Exceptions/Handler.php
I'm not quite sure what's happening here but this [url](/home/search?mode=forum_post&query=wat&forum_id=1890614&forum_children=on) ends up with a nested ViewException for some reason.
> Fix handling of ViewException

- app/Http/Controllers/UsersController.php
🤨
Also combined the report and moved the code to tag so it's easy to check.
> Don't report missing country for non-country code

- app/Exceptions/Handler.php
- app/helpers.php
- always pass in user id including for non-thrown log_error
- don't report/log dd
> Clean up sentry reporting

- app/Http/Controllers/RankingController.php
- resources/views/rankings/kudosu.blade.php
All it needs is the acronym which is what the user country column already specifies.
> Skip querying countries table for kudosu ranking page

- app/Http/Controllers/RankingController.php
- app/helpers.php
- resources/lang/en/layout.php
- resources/views/multiplayer/rooms/show.blade.php
- resources/views/rankings/_mode_selector.blade.php
- resources/views/rankings/index.blade.php
> Combine ranking url generation and order constant

- app/Http/Controllers/InterOp/UsersController.php
> Record medal unlock with id to datadog

- app/Models/Beatmapset.php
scthumber doesn't support bmp but not sure if should just convert to jpeg instead 🤨
> Limit image type when regenerating beatmap covers

- resources/js/turbolinks-overrides.coffee
> Add more legacy path

- app/Jobs/Notifications/BeatmapsetDisqualify.php
Why there are so many subscribers (130k+) aside, this should lower memory requirement.
> Fetch beatmap disqualification notification option in batches

- app/Http/Controllers/Forum/TopicsController.php
- app/Libraries/CommentBundleParams.php
- app/Libraries/Search/BeatmapsetSearchRequestParams.php
- app/Libraries/Search/ScoreSearchParams.php
- app/Models/Beatmapset.php
- app/Models/UserProfileCustomization.php
- app/Transformers/UserCompactTransformer.php
- app/Transformers/UserTransformer.php
- resources/views/accounts/_edit_options.blade.php
- resources/views/objects/_beatmapset_cover.blade.php
Easier way to access defaults without having to create a new instance.
> Rework profile customization defaults

- app/Models/Beatmapset.php
For some reason there are beatmaps with invalid zip file ಠ_ಠ
> Ignore broken beatmap archive for cover regeneration

- app/Libraries/User/Cover.php
Not sure how I missed this ಠ_ಠ
> Remove unused attribute

- app/Http/Controllers/UsersController.php
> Remove unused variable in Users controller

- app/Libraries/User/Cover.php
> Fix cover error on user model placeholder

- app/Libraries/Search/BeatmapsetSearch.php
> Fix incorrect query syntax

- app/Models/Multiplayer/UserScoreAggregate.php
- tests/Models/Multiplayer/UserScoreAggregateTest.php
> Exclude incomplete plays from multiplayer room aggregate

- tests/TestCase.php
Would be useful to know when running/writing tests.
> Print caller line of count change test on failure

- app/Models/Traits/UserScoreable.php
> Exclude scores without pp from user best performance

- resources/lang/en/accounts.php
- resources/views/accounts/edit.blade.php
> Reference Visual Content Considerations in avatar upload instead of community rules

- app/Models/Traits/Scoreable.php
1 (int) isn't 1 (float).
Resolves #11161.
> Fix score accuracy comparison

- app/Models/Traits/Scoreable.php
ಠ_ಠ
Could also be updated to compare with int but the variable name kinda implies a float.
> Fix another float/int mismatch

- resources/js/core/captcha.ts
- resources/views/objects/_captcha_script.blade.php
I forgot to test this and as expected it doesn't work.
> Fix captcha display language

- resources/js/components/comments-controller.ts
Accidentally removed the sort option assignment and the insertion was done in wrong order.
> Fix comments display order

- resources/js/core-legacy/nav2.coffee
- resources/js/core/captcha.ts
- resources/js/main.coffee
That's a rather questionable method of visibility check 👀
> Only request captcha challenge if visible

- app/Models/Solo/Score.php
- tests/Models/Multiplayer/UserScoreAggregateTest.php
> Add basic accuracy validation

- app/helpers.php
- tests/HelpersTest.php
Apparently this is a thing now.
Not actually sure if all the unique exceptions are now wrapped in that class but there's one way to find out 👀
> Check against specific sql unique constraint exception

- docker/development/entrypoint.sh
Apparently this has been a thing since laravel 8.
> Use schedule worker for docker dev

- resources/css/bem/avatar.less
- resources/css/bem/login-box.less
- resources/css/bem/nav2-header.less
- resources/css/bem/nav2.less
- resources/css/layout.less
- resources/css/variables.less
- resources/js/core/animate-nav.ts
- resources/js/core/sticky-header.ts
- resources/js/osu-core.ts
Seems to make more sense and it was especially jarring when navigating ranking pages.
> Remove header animation initial page load

- database/migrations/2024_05_31_062552_add_lookup_index_to_daily_challenge_queue.php
> Add lookup index to `daily_challenge_queue` table

- app/Models/Beatmapset.php
It's currently array of string if comes from cache column.
> Fix beatmapset ruleset id array

- app/Http/Controllers/BeatmapsController.php
Copied from some other place 🤔
> Fix handling invalid ruleset name

- resources/css/bem/ranking-page-table.less
> Remove icon for no rank change

- resources/js/beatmap-discussions/discussions-state.ts
> Exclude deleted beatmap difficulties from nomination required count display

- app/Models/Chat/Message.php
> Use relative time in message User Reports

- bin/make_bem_index.sh
- resources/css/bem-index.less
This is like the least smart way to do it but should work for now. I don't know if attaching license makes sense though.
And saves me annoyance whenever adding/removing files 😐
> Add bem index file generator

- database/migrations/2024_06_09_091512_add_recent_score_index.php
Used primarily for new medals.
@nanaya may want to switch the recent section of profile query to use this index now.
> Add recent score index

- app/Http/Controllers/ScorePinsController.php
- app/Models/ScorePin.php
- app/Singletons/UserScorePins.php
- database/factories/ScorePinFactory.php
- database/migrations/2024_06_14_093636_unique_score_pins_score_id.php
And drop usage of new_score_id and score_type.
> Change score pin model to use score id for primary key

- resources/css/bem/profile-cover-change-popup.less
- resources/css/bem/profile-cover-selection.less
- resources/js/profile-page/cover-selection.tsx
- resources/js/profile-page/cover-selector.tsx
- resources/js/profile-page/cover-uploader.tsx
Widen the popup and change the thumbnails to be in the actual aspect ratio.
> Adjust profile cover selector

- app/Models/Traits/Reportable.php
- app/Models/UserReport.php
- database/migrations/2024_06_11_063126_drop_unique_user_reports.php
- resources/lang/en/errors.php
- tests/Models/UserReportTest.php
> Allow reporting same object after some period

- app/Console/Commands/RankingsRecalculateCountryStats.php
- app/Models/CountryStatistics.php
Otherwise there may be some outdated entries staying in the table.
> Clean up countries without ranked scores

- app/Http/Controllers/ScoresController.php
- resources/lang/en/errors.php
> Validate score id before looking up

- resources/js/beatmap-discussions/new-reply.tsx
- resources/lang/en/beatmaps.php
> Allow ctrl+enter to resolve beatmap discussion when replying

- app/Transformers/UserTransformer.php
- resources/js/interfaces/user-extended-json.ts
- resources/views/docs/_structures/user_extended.md
And document it. The name still doesn't seem quite right but it's at least better than the current one.
> Rename user hue json field

- resources/views/users/beatmapset_activities.blade.php
- resources/views/users/multiplayer/index.blade.php
> Apply user colour to other profile tabs

- app/Libraries/Payments/PaypalPaymentProcessor.php
(I'm not sure why this didn't trigger any errors earlier)
> Fix default on missing test_ipn value

- resources/css/colors.less
- resources/css/layout.less
> Move more colour variables to body

- resources/views/docs/auth.blade.php
> Fix redirect uri description on oauth token request

- app/Models/BeatmapsetEvent.php
Things explode when it's array or some other weird stuff.
>  Ensure sort parameter is a string on beatmap event search

- app/Singletons/CleanHTML.php
- tests/Libraries/bbcode_examples/basic_youtube.html
The tests are kinda wrong 🙃
Resolves #11315
> Allow YouTube fullscreen on bbcode

- app/Libraries/BBCodeFromDB.php
- resources/css/bbcode.less
- resources/css/utilities.less
- tests/Libraries/bbcode_examples/basic_youtube.html
> Remove extra wrapper on YouTube bbcode

- app/Console/Commands/DailyChallengeCreateNext.php
Not sure why but most of the commands are missing strict mode ಠ_ಠ
> Add missing strict mode to daily challenge command

- resources/lang/en/beatmaps.php
> Fix translation for issue count

- database/factories/Multiplayer/ScoreLinkFactory.php
Spent a few minutes figuring out why things didn't work as expected 🤨
> Fix passing `passed` flag for Score factory

- app/Http/Controllers/MatchesController.php
> Fix parsing cursor param on Matches#index

- app/Models/Model.php
- app/Models/ProfileBanner.php
- app/Models/Score/Best/Model.php
- app/Models/Store/Order.php
> Type model macro related settings

- resources/css/bem/user-level.less
- resources/css/layout.less
- resources/css/variables.less
- resources/js/components/user-level.tsx
To be used for daily challenge thing... maybe.
> Move level tier to css variable

- resources/css/bem/mod.less
Otherwise some formatter may consider some of them as size with unit and make them lowercased.
> Fix quoting of lesscss string

- package.json
- resources/css/utilities.less
- resources/js/app-deps.ts
- resources/js/profile-page/main.tsx
- yarn.lock
Unfortunately this has side effect of breaking profile page's section tabs on own profile page as the sortable gesture conflicts with vertical scrolling... so I just disable the specific gesture on mobile.
Resolves #11334.
> Add touch support for jquery ui

- resources/js/profile-page/detail.tsx
> Only show daily challenge stats for specific ruleset

- app/Models/DailyChallengeUserStats.php
- tests/Models/DailyChallengeUserStatsTest.php
> Add start of week function for daily challenge

- app/Libraries/Elasticsearch/Search.php
Namely when searching for field values of infinite (`1e400` etc).
I don't see the exception being passed to the result though.
> Fix error on invalid (un-json-able) beatmap search parameter

- app/Models/Multiplayer/ScoreLink.php
> Fix error when playlist item is gone after existence check

- resources/css/bem/daily-challenge-popup.less
- resources/css/bem/daily-challenge.less
- resources/css/functions.less
- resources/js/profile-page/daily-challenge.tsx
Takes three times longer compared to the streaks.
> Add tier colour to daily challenge playcount

- .github/workflows/tests.yml
- bin/run_dusk.sh
I think I still some fails due to chromedriver somehow exiting midway...
> Use github existing chromedriver

- .github/workflows/tests.yml
- SETUP.md
- bin/run_dusk.sh
- docker/development/entrypoint.sh
- tests/Browser/SanityTest.php
1. dusk not using correct env for docker
2. chromedriver taking too long to start accepting connections
3. youtube changing their ua thing name
(I'm only guessing the number 2, also I don't remember needing the number 1 before)
> More dusk related fixes

- Dockerfile.deployment
- Dockerfile.development
Only took several months until the php crappage was sorted and then forgot to actually update the thing ( ﾟ ヮﾟ)a
> Update to Debian 12

- app/Models/DailyChallengeUserStats.php
- database/migrations/2024_08_06_071309_adjust_daily_challenge_user_stats_defaults.php
This removes the need to pretend default separately when updating things.
(it'll also be used in verification function)
> Add better default value to all user stats timestamp columns

- app/Http/Controllers/AccountController.php
- tests/Controllers/AccountControllerTest.php
> Fix changing profile country to null with empty history

- app/Models/DailyChallengeUserStats.php
- app/Models/Multiplayer/PlaylistItem.php
This shortens `calculate` function and will be reused by fixup function.
> Split percentile calculation to its own function

- bin/run_dusk.sh
> More sophisticated wait for github action chromedriver

- app/Models/BeatmapsetEvent.php
> Fix BeatmapsetEvent comment deprecation warning

- resources/css/bem/contest-judge-results-vote.less
> Wrap long contest judging result comments

- resources/views/home/landing.blade.php
> Remove redundant popup container on landing page

- app/Models/Store/Product.php
For special variants with their own description.
> Try showing variant product description

- docker/development/entrypoint.sh
> Don't fail if test js build directory is missing

- app/helpers.php
- resources/views/multiplayer/rooms/_rankings_table.blade.php
- resources/views/rankings/_spotlight_rankings_table.blade.php
- resources/views/rankings/performance.blade.php
- resources/views/rankings/score.blade.php
Let's get this nonsense fixed already 🤨 
(well, this is a rather shallow fix by only fixing the `format_percentage` and nothing else)
> Accept correct value for formatting percentage

- app/Http/Controllers/FollowsController.php
- app/Http/Controllers/Forum/ForumsController.php
- app/Http/Controllers/Forum/TopicLogsController.php
- app/Http/Controllers/Forum/TopicsController.php
- app/Http/Controllers/Multiplayer/RoomsController.php
- app/Http/Controllers/RankingController.php
- app/Http/Controllers/Store/OrdersController.php
- app/Models/Model.php
Seems useful. A few things are bumped to 50 but I think it's fine? 🤷
> Increase default per page pagination limit

- resources/views/multiplayer/rooms/show.blade.php
Otherwise the actual list may be shorter than what the number says.
> Limit participant count to completed plays

- resources/css/bem/sort.less
- resources/js/components/ranking-user-filter.tsx
- resources/js/components/ranking-variant-filter.tsx
- resources/views/rankings/_user_filter.blade.php
- resources/views/rankings/performance.blade.php
Links are link coloured and hover background is more visible (on ranking page).
> Adjust sort button colour

- resources/views/multiplayer/rooms/_rankings_table.blade.php
> Show multiplayer room leaderboard total scores in full

- resources/js/profile-page/daily-challenge.tsx
- resources/lang/en/users.php
The number on the main display but with actual description of what it is.
> Show participation count in popup

- bin/run_dusk.sh
- tests/DuskTestCase.php
chromedriver's random port broke the tests 😐
> Set chromedriver port for browser tests

- resources/css/bem/rankings-beatmapsets.less
- resources/views/rankings/_beatmapsets.blade.php
Originally for daily challenge page but it seems useful for any other ranking pages too.
> Widen beatmap card on ranking page if there's only one

- resources/css/bem/daily-challenge-popup.less
- resources/js/profile-page/daily-challenge.tsx
> Make total participation number on popup more prominent

- config/session.php
Seems useful in addition to the csrf token. This also removes warning in browser console.
> Better session cookie settings

- app/Models/DailyChallengeUserStats.php
- app/Models/Multiplayer/PlaylistItem.php
- app/Models/Multiplayer/PlaylistItemUserHighScore.php
Before I add another same query somewhere else 🤔
> Add scope to filter passing multiplayer high scores

- app/Http/Controllers/Multiplayer/RoomsController.php
- resources/views/multiplayer/rooms/_rankings_table.blade.php
Another update which mainly is for daily challenge but also useful in general.
> Always show own score on multiplayer room leaderboard

- app/Http/Controllers/Forum/TopicsController.php
- resources/js/core-legacy/forum-topic-reply.coffee
- resources/lang/en/accounts.php
> Update forum auto notification option to include replies

- app/Http/Controllers/Multiplayer/RoomsController.php
- app/Http/Controllers/Ranking/DailyChallengeController.php
- app/Http/Controllers/RankingController.php
- app/Models/Multiplayer/Room.php
- app/Singletons/RouteSection.php
- app/helpers.php
- resources/css/bem/rankings-beatmapsets.less
- resources/js/components/basic-select-options.tsx
- resources/js/core/spoilerbox.ts
- resources/js/utils/fail.ts
- resources/lang/en/rankings.php
- resources/views/rankings/_beatmapsets.blade.php
- resources/views/rankings/daily_challenge.blade.php
- resources/views/rankings/index.blade.php
- routes/web.php
- tests/Browser/SanityTest.php
> Add daily ranking page

- app/Http/Controllers/Ranking/DailyChallengeController.php
> Show daily ranking list in most recent order

- app/Console/Commands/StoreGetPaypalOrder.php
- app/Console/Kernel.php
- app/Exceptions/Store/PaymentRejectedException.php
- app/Http/Controllers/Payments/PaypalController.php
- app/Libraries/Payments/PaypalExecutePayment.php
- app/Models/Store/PaypalBanned.php
- database/migrations/2024_09_24_000001_create_store_paypal_banned.php
Also adds a command for getting an `Order`'s corresponding details from paypal.
> Add support for rejecting payments

- app/Libraries/Markdown/Osu/DocumentProcessor.php
Randomly saw this when syncing news posts.
> Fix null being passed to str replace

- routes/web.php
The action never existed and goes no where 👀
> Remove unused route

- app/Transformers/UserCompactTransformer.php
Seems useful 🤔 
(inb4 failing tests)
> Use preloaded country data for user json

- resources/views/password_reset/index.blade.php
Seems useful? 🤔 I think it may be used for some email (not from osu-web)
> Allow prefilling reset password username

- app/Http/Controllers/AccountController.php
- tests/api_routes.json
> Adjust session verification reissue limit

- resources/css/bem/forum-poll-option.less
> Prevent forum poll option image from overflowing

- resources/css/bem/artist-track-search-form.less
- resources/css/bem/input-container.less
- resources/css/bem/input-text.less
- resources/js/artist-tracks-index/search-form.tsx
- resources/js/chat/create-announcement.tsx
The smaller cleanup before going with a larger one. Mainly to unify input container styles.
Notable changes include same background colour and padding.
> Form styling cleanup

- resources/css/bem/comment-editor.less
> Remove extra padding on comment editor footer

- resources/js/beatmapsets-show/header.tsx
> Show video icon on beatmap page

- webpack.config.js
It will take at least 1 second less
> Reduce the number of emojis copied to `images/flags`

- resources/css/bem/landing-sitemap.less
- resources/css/bem/osu-layout.less
- resources/css/bem/page-extra.less
- resources/js/beatmaps/search-content.tsx
- resources/js/profile-page/beatmapsets.tsx
- resources/views/beatmapset_events/index.blade.php
- resources/views/home/landing.blade.php
...and col.
Isn't grid great 😴
> Remove osu-layout row block element

- app/Singletons/Medals.php
Handles one specific case of post-release medal name change (and nothing else).
> Do case insensitive lookup of medal name

- resources/js/chat/create-announcement.tsx
> Remove unused modifier

- app/Http/Controllers/ScoresController.php
> Fix legacy score lookup on new table

- tests/Models/BeatmapsetRequalifyTest.php
Forgot we're using the global now, not `config` 👀
> Use global config variable

- app/Models/Forum/TopicWatch.php
> Fix exception class name

- app/Http/Controllers/FriendsController.php
- app/Http/Controllers/GroupsController.php
- app/Models/User.php
- app/Transformers/UserCompactTransformer.php
> Fix user listing preload scope

- app/Libraries/Search/BeatmapsetQueryParser.php
- tests/Libraries/Search/BeatmapsetQueryParserTest.php
Elasticsearch json time is limited to four digit years.
Probably should just reject them outright but this one is easier? 🤷 
Also, trolled by mutable date from helper function 😐
> Pass timestamp to elasticsearch for beatmap search

- resources/css/bem/show-more-link.less
Block layout now has justify-items/self.
Resolves #11586.
> Fix show more button alignment on comments

- app/Http/Controllers/BeatmapsController.php
- app/Http/Controllers/ScoreTokensController.php
- app/Models/Beatmap.php
- app/Models/Multiplayer/PlaylistItem.php
- app/Models/Multiplayer/Room.php
- tests/Controllers/Multiplayer/Rooms/Playlist/ScoresControllerTest.php
- tests/Controllers/ScoreTokensControllerTest.php
- tests/Models/Multiplayer/PlaylistItemTest.php
- tests/Models/Multiplayer/RoomTest.php
Step 1 towards fixing the mess that is https://github.com/ppy/osu/issues/30415.
This is high profile breakage so I'd appreciate expedited review if possible.
> Check ruleset conversion validity when issuing submission tokens

- resources/css/bem/menu-images.less
- resources/views/home/user.blade.php
Forgot about this when moving things around.
> Fix dashboard moving around on initial load

- app/Libraries/NotificationsBundle.php
One query to count them all.
The one in `fillStacks` can probably receive similar treatment if someone want to take challenge writing window query for it.
> Reduce number of queries to count notifications

- resources/js/components/menu-images.tsx
- resources/js/register-components.tsx
> Randomise dashboard banner order

- app/Http/Controllers/FriendsController.php
- resources/js/components/friend-button.tsx
- resources/js/core/user/user-model.ts
- routes/web.php
- tests/api_routes.json
> Add api endpoint for adding/removing friends

- app/Jobs/Notifications/BroadcastNotificationBase.php
~~(untested and probably will break test)~~ oh wow nothing tests this specifically
> Don't create user notification entry if mail and push are both disabled

- .env.example
- app/Http/Controllers/FollowsController.php
- config/osu.php
- resources/lang/en/follows.php
Dunno if 5k is a good limit. After the one that's over 10k, it's 3400, 1900, 1400, and 1300 🤷‍♀️
(this pr title sounds weird 🫤)
> Limit maximum number of mappers that can be followed

- app/Http/Controllers/InterOp/Indexing/BulkController.php
For when other process deletes score(s) until #11578 is implemented.
> Support score on interop bulk indexing endpoint

- app/Models/Chat/Message.php
> Limit chat message reporting context

- app/helpers.php
- resources/css/bem/forum-user-icon.less
Seems weird it's not part of the link.
> Include user colour icon as part of the link

- SETUP.md
- docker-compose.yml
🤷 
Also added note about updating the docker images.
>  Update beatmap difficulty server port number

- resources/js/core/react-turbolinks.ts
- resources/js/core/turbolinks-reload.ts
- resources/js/store-xsolla.coffee
Properly registered with filename and map and stuff instead of being unmapped inlined stuff.
> Async script loading

- docker/development/prepare.sh
This adds about 4s on my system with fully updated images 🤔 
```
$ time docker compose build
...
real    0m3.557s
user    0m0.146s
sys     0m0.117s
```
> Do a quick build on dev start

- composer.lock
It's been a while so might as well do this.
There's still a lot of other outdated libraries 😬
> Update laravel framework

- app/Http/Controllers/Chat/Channels/MessagesController.php
- app/Http/Controllers/ContestEntriesController.php
- app/Http/Controllers/Forum/TopicsController.php
- app/Http/Controllers/MatchesController.php
- app/Http/Controllers/Multiplayer/Rooms/Playlist/ScoresController.php
- app/Http/Controllers/Multiplayer/RoomsController.php
- app/Http/Controllers/RankingController.php
- app/Http/Controllers/UsersController.php
- app/Libraries/BBCodeFromDB.php
- app/Libraries/CommentBundleParams.php
- app/Libraries/Score/BeatmapScores.php
- app/Models/Beatmap.php
- app/Models/Model.php
- app/Models/Multiplayer/Room.php
- app/Models/NewsPost.php
- app/Models/Score/Best/Model.php
- app/helpers.php
>  Use new laravel helper method

- app/Http/Controllers/SessionsController.php
> Try fixing user country on login

- docker-compose.yml
> Fix difficulty lookup cache address in docker compose

- resources/views/layout/ujs-redirect.blade.php
> Workaround ujs redirect not redirecting

- app/Models/Multiplayer/Room.php
- app/Singletons/OsuAuthorize.php
I think that's all it needed? 🤔 
Related: ppy/osu#30627
> Allow silenced user to play in playlist

- app/Http/Controllers/RankingController.php
> Fix ranking page parameter type

- app/Models/NewsPost.php
- app/Models/User.php
- app/helpers.php
> Create helper to check http(s) string

- app/helpers.php
Works around hotwired/turbo#211
Resolves #11682
> Do an explicit turbo visit for redirecting turbo request

- app/helpers.php
> Clean up proxy media function

- app/Models/Solo/Score.php
> Update total score check

- app/Http/Controllers/ScoresController.php
Failed scores are excluded atm 🤔 
(also a few other type of scores but this is the main one)
> Better wording for score listing api docs

- app/Models/Team.php
- resources/views/teams/show.blade.php
Work around in case of broken team data.
Also fixes missing import on the model.
> Fix handling of team leader

- app/Models/Solo/Score.php
> Exclude restricted user scores from score listing

- app/Models/Multiplayer/Room.php
To address https://osu.ppy.sh/community/forums/topics/2013293.
Normally wouldn't detour for this but the second message in that thread pissed me off. I feel like people will start to exploit this now so maybe I shouldn't admit to it.
> Add capability to filter by room status

- resources/css/bem/input-text.less
- resources/css/bem/team-settings-description-preview.less
- resources/views/teams/edit.blade.php
Add toolbar and lock the height.
> Adjust team description input area

- app/Models/User.php
There's already one in [session controller](https://github.com/ppy/osu-web/blob/master/app/Http/Controllers/SessionsController.php#L33) but it's probably useful in general
Related to ppy/osu#31159
> Trim username in all cases on login

- app/Models/TeamMember.php
- resources/views/teams/members/index.blade.php
- resources/views/teams/show.blade.php
Hmmm 🤔 something like this maybe.
> Fix handling of deleted and restricted team members

- app/Casts/TimestampOrZero.php
- app/Jobs/Notifications/BroadcastNotificationBase.php
- app/Models/Forum/Forum.php
- app/Models/Forum/Post.php
- app/Models/Forum/Topic.php
- app/helpers.php
Relatively straightforward...? 🤔 
Should get around actually fixing them one day...
> Use casting class for forum timestamps

- tests/TestCase.php
There's probably a better way to do this... 🤨
> Fix tag controller tests

- resources/js/core-legacy/changelog-chart-loader.coffee
> Reset changelog chart before creating a new one

- app/Http/Controllers/HomeController.php
- resources/views/layout/ujs_full_reload.blade.php
> Force browser page refresh on locale change

- resources/css/bem/beatmap-discussions-header-top.less
- resources/js/beatmap-discussions/header.tsx
fixes #11798
But the localization should still be updated to include a space.
> Always wrap Beatmap Discussion guest mapper list

- app/helpers.php
- resources/views/follows/modding.blade.php
- resources/views/forum/topics/_post_info.blade.php
- resources/views/layout/_header_user.blade.php
- resources/views/layout/_page_header_v4.blade.php
- resources/views/layout/_popup_user.blade.php
- resources/views/objects/_flag_team.blade.php
The current ones being proxied are either in error (team) or not necessary (store header image, already in assets - and the other product images aren't proxied either).
> Remove proxying option of blade background image

- app/Http/Controllers/HomeController.php
- resources/js/quick-search/user.tsx
- resources/views/home/_search_result_user.blade.php
Another places not using the const 😴
> Show team flag on user search result

- app/Models/ChangelogEntry.php
- app/Transformers/ChangelogEntryTransformer.php
- tests/Models/ChangelogEntryTest.php
┐(･_･)┌
Display and dev message:
```
Visible
---
Hidden
```
Display message only:
```
Visible
---
```
Dev message only:
```
Hidden
```
> Flip order and only store display message for changelog entry

- resources/css/bem/team-members-manage.less
- resources/views/teams/members/index.blade.php
The `link_to_user` function is kinda crap 😦
> Show user card when hovering user avatar on team member listing

- app/Models/Contest.php
Maybe? ಠ_ಠ
Add a variant field in the best_of object.
> Support ruleset variants in "best of" contests

- app/Http/Controllers/BeatmapsController.php
- resources/views/docs/_structures/beatmap.md
- resources/views/docs/_structures/beatmap_owner.md
Before I forget about it again
closes #11788
> Include beatmap owners in additional Beatmap API responses

- database/migrations/2015_01_01_133337_base_tables.php
Instead of #11807.
Resolves #11785.
> Update user table to start from id 2

- app/Models/Contest.php
As requested.
The variant would be "nk"
> Support non-4k/7k mania variant in "best of" contests

- resources/css/bem/beatmap-pack.less
- resources/lang/en/beatmappacks.php
- resources/views/packs/index.blade.php
- resources/views/packs/show.blade.php
maybe would be better to do something like `by <strong>:author</strong>` but /shrug
> Add missing localisation to beatmap pack listing

- resources/js/core-legacy/tooltip-default.coffee
- resources/js/profile-page/rank.tsx
Resolves #9439.
Alternative to #11613.
> Better position of user rank tooltip

- resources/js/store/store-supporter-tag.tsx
fixes #11849
(yay nested `disposers.add`)
Also removed `disposeOnUnmount` because that's apparently been deprecated due to React 18.
> Fix store supporter tag slider not working

- .eslintrc.js
- resources/js/cli/mod-names-generator.js
- resources/js/components/mod.tsx
- resources/js/interfaces/mod-json.ts
- resources/js/utils/score-helper.ts
> Sort mods by type and acronym

- app/Transformers/TeamTransformer.php
- resources/js/components/flag-team.tsx
- resources/js/interfaces/team-json.ts
More consistent with what it's ended up being called as.
> Adjust json field name for team flag image url

- resources/css/bem/menu-images.less
Mainly for easier targeting on mobile.
> Better menu image padding

- resources/css/bem/menu-images.less
> Move menu images selector to be right at the border

- resources/js/profile-page/chart.tsx
🤔 
Also this is a very static react component as it ignores any potential updates to the props.
> Remove commented out code

- resources/css/bem/team-info-entry.less
- resources/lang/en/model_validation.php
- resources/lang/en/teams.php
- resources/views/teams/edit.blade.php
- resources/views/teams/show.blade.php
> Show more stuff on team info section

- app/Http/Controllers/ScoresController.php
Dunno if it is worth creating an auth for...
> Allow admin to view all scores

- resources/views/teams/edit.blade.php
- resources/views/teams/show.blade.php
> Fix attribute value check

- app/Http/Controllers/TeamsController.php
- app/Jobs/Notifications/TeamApplicationBase.php
- app/Models/Team.php
- app/Transformers/TeamTransformer.php
- database/migrations/2025_02_20_220000_rename_teams_logo_to_flag.php
- resources/lang/en/teams.php
- resources/views/forum/topics/_post_info.blade.php
- resources/views/objects/_flag_team.blade.php
- resources/views/teams/edit.blade.php
Also removed unused `_remove` params parsing and delete-on-null attribute setter.
> Rename team logo column to flag

- app/Libraries/Uploader.php
- app/Models/Team.php
And use it for team file handling. There's still no proper rollback for upload/db update failure though.
Related to #11886
> Allow separating file processing and uploading

- app/Models/Team.php
> Allow full printable ascii characters for team name and short name

- resources/views/teams/edit.blade.php
> Show team flag in correct size in settings page

- resources/views/layout/header_mobile/user.blade.php
> Add link to team on mobile menu

- app/Libraries/ImageProcessor.php
- resources/views/teams/edit.blade.php
> Only allow image file type on team header/flag file dialog

- app/Models/Team.php
- tests/Models/TeamTest.php
Some people got stuck with their application on deleted teams 👀
>  Delete pending applications when deleting team 

- app/Models/Team.php
- resources/css/bem/team-settings.less
- resources/lang/en/teams.php
- resources/views/teams/edit.blade.php
> Show team-related image size hint

- app/Models/Team.php
> Add check for team url length

- resources/views/teams/edit.blade.php
> Hide image tag on team settings page if not exist

- app/Http/Controllers/TeamsController.php
- resources/lang/en/teams.php
- resources/views/teams/_members_leaderboard.blade.php
Resolves #11904.
Reuse existing translation while at it.
> Use correct user score stats

- resources/css/bem-index.less
- resources/css/bem/header-nav-item-count.less
- resources/views/layout/_page_header_v4.blade.php
> Show header nav link count badge on mobile

- app/Models/Team.php
Deleting file in transactional manner is a bit... weird. Ignore it for now.
> Ignore null file parameter

- tests/ZalgoTest.php
Well that's been testing the wrong thing for a while...
> Use correct dataprovider in ZalgoTest

- resources/css/bem/team-settings-description-preview.less
- resources/css/bem/team-settings.less
> Fix grid variables not being correctly applied in team description settings

- resources/js/core/blade-popup.ts
- resources/js/osu-core.ts
- resources/js/shared.coffee
- resources/js/utils/popup.ts
- resources/views/layout/popup-container.blade.php
Resolves #11924.
The popup width on the screenshot in the linked issue is way wider than it should be (custom css/js?).
> Apply effects on popups from blade template

- app/Http/Controllers/BeatmapsetsController.php
- app/Models/Wiki/Page.php
- app/Transformers/BeatmapsetCompactTransformer.php
- app/Transformers/Chat/MessageTransformer.php
- app/Transformers/UserContestEntryTransformer.php
- composer.lock
woo ┐( ･_･)┌
(part of php library update)
> Update php code linter

- resources/views/docs/_structures/beatmap_difficulty_attributes.md
> Update `BeatmapDifficultyAttributes` documentation

- resources/js/utils/score-helper.ts
> Adjust accuracy rounding for display

- app/Http/Controllers/BeatmapTagsController.php
- app/Models/Beatmap.php
- routes/web.php
- tests/Controllers/BeatmapTagsControllerTest.php
- tests/api_routes.json
`PUT /api/v2/beatmaps/{beatmap_id}/tags/{tag_id}` instead of body param
and expire the cache on update
> Update setting beatmap tags to use path param

- app/Http/Controllers/Multiplayer/RoomsController.php
It's kinda big and slow (especially for certain mode). It doesn't seem to be ever documented anyway 🤷
> Remove support for large json response of room listing api

- app/Http/Controllers/Multiplayer/RoomsController.php
- app/Models/Multiplayer/Room.php
- tests/api_routes.json
Resolves #11815. #12009 is highly recommended to be merged in first.
> Allow client grant token to access room listing api

- resources/lang/en/teams.php
- resources/views/teams/members/index.blade.php
As [requested](https://discord.com/channels/90072389919997952/1327149041511043134/1350335847974572032).
> Add note on overflowing team member count

- app/Http/Controllers/BeatmapsController.php
- app/Models/Beatmap.php
- app/Transformers/BeatmapCompactTransformer.php
- resources/views/docs/_structures/beatmap.md
> Include current user playcount in beatmap api responses

- app/Http/Controllers/BeatmapsetsController.php
> Fix beatmap search documentation title

- app/Http/Controllers/BeatmapsController.php
- app/Libraries/Score/BeatmapScores.php
- app/Libraries/Score/UserRank.php
> Include score count in beatmap scores response

- resources/js/beatmapsets-show/info.tsx
- resources/js/beatmapsets-show/metadata-editor.tsx
- resources/lang/en/beatmapsets.php
Resolves https://github.com/ppy/osu-web/issues/12033.
> Separate user tags on beatmapset info

- app/Notifications/UserReportNotification.php
- composer.lock
- resources/js/cli/generate-localizations.js
Just a minor change related to path...
> Update laravel js localisation library

- database/factories/SpotlightFactory.php
> Fix SpotlightFactory state return type

- app/Http/Controllers/RankingController.php
> Fix missing sort parameter on pagination link

- app/Models/Beatmapset.php
As discussed in https://github.com/ppy/osu/discussions/32451.
> Stop resetting playcounts / pass counts when beatmaps are ranked

- app/Http/Controllers/BeatmapTagsController.php
- app/Models/Tag.php
- database/factories/TagFactory.php
- database/migrations/2025_03_28_000001_add_ruleset_id_to_tags.php
- resources/lang/en/beatmap_tags.php
- tests/Controllers/BeatmapTagsControllerTest.php
> Add per ruleset tag support

- app/Jobs/Notifications/BroadcastNotificationBase.php
> Fix error when checking blocked user ids for notification

- resources/js/chat/conversation-view.tsx
Went with just not showing the message instead of a placeholder blocked message
> Filter chat messages from block users from being displayed

- app/Libraries/ImageProcessor.php
Weird edge case which has been adding noise to sentry.
> Prevent invalid image output size

- resources/css/bem/beatmapset-info.less
- resources/js/beatmapsets-show/info.tsx
The entire box is scrollable instead.
Should fix #12051
> Fix overlapping scrollable Beatmap info sections

- app/Models/Traits/Es/BaseDbIndexable.php
- app/Models/Traits/Es/BaseIndexable.php
- app/helpers.php
- config/sentry.php
> Fix php deprecations

- resources/css/bem/beatmapset-info.less
> Fix Beatmap description header hidden by imagemap

- resources/css/bem/ranking-page-table.less
- resources/views/rankings/_main_column.blade.php
- resources/views/teams/_members_leaderboard.blade.php
Also extended minimum column width.
Resolves #12103.
> Hide user avatar on non-team leaderboards

- app/Http/Controllers/HomeController.php
I think this should fix it 🤔 
Resolves #12110.
> Fix supporter tag percent display

- app/Exceptions/ChangeUsernameException.php
- app/Exceptions/ValidationException.php
- app/Jobs/RegenerateBeatmapsetCover.php
- app/Libraries/Elasticsearch/SearchResponse.php
- app/Libraries/Search/BasicSearch.php
- app/Libraries/SessionVerification/Helper.php
- app/Libraries/TransactionState.php
- app/Models/Store/Order.php
- app/Singletons/OsuAuthorize.php
- app/Transformers/UserStatisticsTransformer.php
- tests/Libraries/OrderCheckoutTest.php
> Fix nullable typing

- app/Models/Multiplayer/PlaylistItemUserHighScore.php
- app/Models/Multiplayer/UserScoreAggregate.php
To be used for display by client. @smoogipoo
> Add passed flag to playlist item attempts json

- app/Libraries/BeatmapsetDiscussion/Review.php
- app/Models/Beatmapset.php
- app/Models/Multiplayer/Room.php
- app/Transformers/BeatmapsetEventTransformer.php
- phpcs.xml
- tests/Models/BeatmapsetTest.php
Should've added this linter instead in the first place 👀 
Also added fix for passing null to json decode function.
> More php null related fixes

- app/Models/Chat/Channel.php
- app/Models/Chat/Message.php
Seems useful if I'm to add another one for team messages.
Both job classes sure are awfully similar...
> Move new message notification logic to its own function

- resources/views/teams/show.blade.php
> Show detailed team formation date on hover

- app/Models/UserStatistics/VariantModel.php
> Fix ranked score attribute on variant statistics

- resources/views/rankings/index.blade.php
> Reset variant parameter when switching ruleset

- database/migrations/2025_04_24_054138_fix_downloads_beatmapset_id_type.php
> Fix type of beatmapset id column on downloads table

- app/Libraries/Ip2AsnUpdater.php
Still defaults to the original source because the new alternative may get rather stale (and looks like the expiration is like a month?).
> Add alternative url for iptoasn database source

- app/Http/Controllers/Forum/TopicsController.php
As reported on [discord](<https://discord.com/channels/188630481301012481/188630616286167041/1370296710546456680>).
> Fix cursor for topic listing not working

- resources/css/bem/nav2.less
- resources/css/bem/quick-search.less
- resources/js/components/quick-search-button.tsx
- `something-f` shortcut (in possibly [the most obscure way](https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Global_attributes/accesskey) possible)
- button hover background
- max width on desktop
> Adjust menu search button

- app/Http/Controllers/HomeController.php
- app/Libraries/Search/QuickSearch.php
- resources/js/quick-search/main.tsx
- resources/js/quick-search/worker.ts
Use correct BeatmapsetCompact transformer while at it (and remove the includes).
> Automate quick search json generation

- app/Http/Controllers/ContestsController.php
- app/Models/Contest.php
- resources/views/contests/_voting-entrylist.blade.php
- resources/views/contests/voting.blade.php
I think that should cover that specific state 🤔 
more comprehensive fix when contests gets refactored 🤨
> Don't display contest entries when judging period is over but results not available yet

- app/Transformers/BeatmapsetCompactTransformer.php
> Add language and genre id to beatmapset json

- app/Jobs/Notifications/BeatmapsetDiscussionReviewNew.php
- app/Jobs/Notifications/BroadcastNotificationBase.php
- app/Jobs/Notifications/ChannelAnnouncement.php
- app/Jobs/Notifications/ChannelMessageBase.php
- app/Jobs/Notifications/ChannelTeam.php
- app/Mail/UserNotificationDigest.php
- resources/lang/en/notifications.php
I can't tell why they're all in separate keys.
> Simplify user channel notification mail key

- resources/js/beatmaps/beatmapset-search-controller.ts
- resources/js/beatmaps/beatmapset-search.ts
- resources/js/beatmaps/result-set.ts
- resources/js/beatmaps/search-sort.tsx
- resources/js/entrypoints/beatmaps.tsx
- resources/js/interfaces/beatmapset-search-response.ts
- resources/js/stores/root-data-store.ts
Separated from trying to fix #12169 since it turned out to be less simple that I thought....
> Move Beatmapset SearchResponse interface to own file

- app/Http/Controllers/Multiplayer/RoomsController.php
- app/Models/Multiplayer/RealtimeRoomEvent.php
- app/Models/Multiplayer/Room.php
- app/Transformers/Multiplayer/PlaylistItemTransformer.php
- app/Transformers/Multiplayer/RealtimeRoomEventTransformer.php
- database/migrations/2025_05_14_062018_add_index_to_room_id_on_multiplayer_realtime_room_events.php
- resources/js/interfaces/playlist-item-json.ts
- resources/js/interfaces/realtime-room-event-json.ts
- routes/web.php
- tests/api_routes.json
Continuation of https://github.com/ppy/osu-web/issues/10455.
I'm not super sure where I'm taking this forward, to be quite honest - this PR is me trying to play things as straight and narrow as possible and I will figure out how to thread the rest of the needle later. I'm not documenting this endpoint until I'm through making it work, because I don't want to sell this API shape as final. **External consumers eyeing this change - you have been warned, I reserve the right to change this new endpoint's contract at will until is used on the website to serve the actual views.**
Behaviourally and shape-wise this endpoint is very similar to `/api/v2/community/matches/{id}`, albeit with some notable deviations in nomenclature (`playlist_item` et al. instead of `game`), as well as one notable …
> Add API endpoint for retrieving lazer multiplayer room history

- app/Models/Traits/Es/ArtistTrackSearch.php
- app/Models/Traits/Es/BaseDbIndexable.php
- app/Models/Traits/Es/BeatmapsetSearch.php
- app/Models/Traits/Es/ForumPostSearch.php
- app/Models/Traits/Es/TeamSearch.php
- app/Models/Traits/Es/UserSearch.php
> Simplify model es json generation

- app/Libraries/Search/TeamSearch.php
May also need to look into why it still does the search...
> Fix error on forum post search by username with blank query

- app/Http/Controllers/BeatmapsController.php
- app/Http/Controllers/Multiplayer/Rooms/Playlist/ScoresController.php
- app/Http/Controllers/ScoresController.php
- app/Http/Controllers/Solo/ScoresController.php
- app/Transformers/LegacyMatch/GameTransformer.php
- app/Transformers/Multiplayer/PlaylistItemTransformer.php
- app/Transformers/ScoreTransformer.php
> Simplify score transformer format parameter

- app/Transformers/ScoreTransformer.php
> Remove ScoreTransformer non-existent variable

- resources/lang/en/page_title.php
> Fix legacy match page title

- app/Http/Controllers/Admin/ContestsController.php
- resources/css/bem/admin-contest.less
- resources/views/admin/contests/show.blade.php
separated from #12014, going to add extra buttons to calculate the scoring and maybe extra messages.
- Use flexbox/grid instead
- stop using the `contest` class
- rename variable with confusing `s` position
> Update Contest Admin page styling

- resources/css/bem/osu-table.less
The classes are all sorts of wrong and need further clean up.
> Fix overflow on mobile view of admin contest page

- resources/css/bem/mp-history-game.less
- resources/css/bem/mp-history-player-score.less
- resources/js/legacy-match/score.tsx
Gaps and stuff and align the numbers.
> Update match page score styling

- resources/js/components/build.coffee
As reported in https://discord.com/channels/188630481301012481/188630616286167041/1385149894070763560
> Fix missing changelog header colour

- app/Console/Commands/EsIndexScoresQueue.php
- app/Console/Commands/EsIndexScoresSetSchema.php
- app/Jobs/RemoveBeatmapsetSoloScores.php
- app/Libraries/Search/ScoreSearch.php
I don't think the functions were ever justified being instance function.
> Make score indexing utility functions static

- app/Http/Controllers/ChangelogController.php
- app/Models/UpdateStream.php
- app/Transformers/UpdateStreamTransformer.php
This also fixes latest build being shown regardless of visibility.
> Reduce changelog page queries

- app/Models/ChangelogEntry.php
relations should be using `setRelation`...
> Fix Changelog eager loaded user not being used

- app/Models/UpdateStream.php
The attribute is a bit of mystery without knowing how it's supposed to be used.
> Add note about update stream's `latestBuild` relation

- app/Http/Controllers/Multiplayer/RoomsController.php
Somehow misread the class name during review ಠ_ಠ
closes #12263
> Fix daily challenge room redirect

- resources/lang/en/teams.php
- resources/views/teams/show.blade.php
Inspired from #12225, with explicit open slot count.
- hide deleted/restricted user on general listing
- show available slot count
> Adjust team member display

- app/Http/Controllers/HomeController.php
- app/Models/SupporterTag.php
- resources/lang/en/community.php
- resources/views/home/support-the-game.blade.php
> Show total duration of supporter tags on supporter page

- resources/js/components/report-form.tsx
- resources/lang/en/users.php
> Add new report type

- resources/lang/en/beatmapsets.php
- resources/lang/en/common.php
- resources/lang/en/contest.php
- resources/lang/en/home.php
- resources/views/beatmapsets/show.blade.php
- resources/views/contests/base.blade.php
- resources/views/home/user.blade.php
- resources/views/layout/footer.blade.php
> Add admin menu to more pages

- app/Exceptions/UserVerificationException.php
- app/Libraries/SessionVerification/Controller.php
Add all the typings and inherit different class so it can just be rethrown.
> Clean up verification exception class

- app/Models/Event.php
- app/Models/Store/OrderItem.php
- resources/views/comments/show.blade.php
- resources/views/contests/voting.blade.php
- tests/Browser/BeatmapDiscussionPostsTest.php
> Use correct translation function

- tests/Browser/AccountTest.php
- tests/Browser/LoginTest.php
- tests/DuskTestCase.php
Continues off #12344, now with actually reusable logic.
> Wrap another randomly failing test with retries 

- tests/Browser/LoginTest.php
So that's why I thought it's weird to use additional variable 🤨
> Simplify dusk retry logic

- app/Models/BeatmapLeader.php
This matches how the leaderboard is actually rendered.
> Account classic scores when syncing beatmap leaders

- app/Transformers/ScoreTransformer.php
Also removed unused country preload.
Related: ppy/osu#34734
> Include user team data in multiplayer score responses
